### ISSUE TITLE
Migration scripts

### ISSUE THREAD

**Issue by fiji-flo** [mdn/translated-content#10]
Let's start gather simple command line scripts (`find`, `grep`, `sed`, ...) to bulk fix macro deprecation on translated content.

Just add a comment. We'll structure this soon!

**Comment by SphinxKnight** [comment]
@fiji-flo is this still relevant?

**Comment by SphinxKnight** [comment]
@fiji-flo I'm closing this, in favor of resurrecting it if something comes out of https://github.com/mdn/yari/issues/2846
