### ISSUE TITLE
Кавычки в примерах поставлены не корректно.

### ISSUE THREAD

**Issue by geighttt** [mdn/translated-content#10035]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Errors/Unterminated_string_literal

### What information was incorrect, unhelpful, or incomplete?

Кавычки были неправильно выставлены в примерах.

### What did you expect to see?

На первом изображении кавычки стоят не корректно -> 'text". На третьем изображении ситуация аналогична. Такая проблема есть только на русской версии страницы, на английской версии такой проблемы - нет.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/errors/unterminated_string_literal`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Errors/Unterminated_string_literal
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/errors/unterminated_string_literal/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b3ce62379fcd37eb9942cf2a8d5339d581805dc0
* Document last modified: 2022-10-22T20:35:15.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17375 :ok_hand: 

Thank you! :+1:
