### ISSUE TITLE
Chore: macro depreciation: ServiceWorkerSidebar to be removed

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#10170]
Hello all, 

Per https://github.com/mdn/yari/pull/7645, `{{ServiceWorkerSidebar}}` is now deprecated and should be replaced with `{{DefaultAPISidebar}}`.

@yin1999 already took care of `zh` in https://github.com/mdn/translated-content/pull/10163 :bow: 

Here are the 12 remaining occurrences: 

- 2 for @mdn/yari-content-es 
- 2 for @mdn/yari-content-fr 
- 2 for @mdn/yari-content-ja 
- 2 for @mdn/yari-content-ko 
- 2 for @mdn/yari-content-pt-br 
- 2 for @mdn/yari-content-ru 

This should be quite simple to do, but please let me know if you need help :)

**Comment by Graywolf9** [comment]
Taking care of it in #10176

Thank you @SphinxKnight

**Comment by notJoon** [comment]
@SphinxKnight 
just finished in #10188 `ko`
thank you

**Comment by sashasushko** [comment]
@SphinxKnight done for RU
