### ISSUE TITLE
Chore: macro deprecation: WebRTCSidebar should be removed

### ISSUE THREAD

**Issue by wbamberg** [mdn/translated-content#10177]
I'm currently working on removing custom sidebars from the Web/API docs. There's more context at https://discourse.mozilla.org/t/defaultapisidebar-apiref-and-groupdata/40210/24.

In https://github.com/mdn/content/pull/22486 I removed references to [`WebRTCSidebar.ejs`](https://github.com/mdn/yari/blob/main/kumascript/macros/WebRTCSidebar.ejs) from en-US content, and in https://github.com/mdn/yari/pull/7674 I'm asking for it to be deprecated.

**Comment by yin1999** [comment]
Thanks @wbamberg, I've add labels for all the locales which has used this macro, and created #10191 for remove this from l10n-zh.

**Comment by wbamberg** [comment]
> A little doubt, this is change `{{WebRTCSidebar}}` by `{{DefaultAPISidebar("WebRTC")}}`?

For pages under /web/api/webrtc_api/ yes. For all other pages, replace `{{WebRTCSidebar}}` with `{{APIRef("WebRTC")}}`.

But please feel free to tag me in your PR and I'll have a look :).

**Comment by Graywolf9** [comment]
Taking care of it in #10326 for `es`

Thank you @wbamberg !

**Comment by wbamberg** [comment]
-> https://github.com/mdn/yari/pull/8012 🎉 ! Thanks everyone :).
