### ISSUE TITLE
404 Bad link in french https://developer.mozilla.org/fr/docs/Web/API/API_IndexedDB/Using_IndexedDB

### ISSUE THREAD

**Issue by scenaristeur** [mdn/translated-content#102]
at https://developer.mozilla.org/fr/docs/Web/API/API_IndexedDB/Using_IndexedDB#%C3%A0_propos_de_ce_document
in 
> Ce tutoriel vous guide à travers l'utilisation de l'API asynchrone de IndexedDB. Si vous n'êtes pas familier avec le principe de IndexedDB, vous devriez d'abord lire les concepts basiques d'IndexedDB.

 the link goes to the 404 https://developer.mozilla.org/en-US/IndexedDB/Basic_Concepts_Behind_IndexedDB 

instead of https://developer.mozilla.org/fr/docs/Web/API/API_IndexedDB/Basic_Concepts_Behind_IndexedDB

**Comment by SphinxKnight** [comment]
@scenaristeur hello :) this repo is now opened to contribution regarding the French content. Would you be interested in making a pull request to fix this one?

**Comment by CreaTorAlexander** [comment]
I can update the link 👍

**Comment by SphinxKnight** [comment]
Thanks @CreaTorAlexander :) I've left a few comments on #248. Let me know if you need help with that!

**Comment by CreaTorAlexander** [comment]
Yes mb I created the new branch out of the branch for iss142. How can I remove a commit? 
Or shall I create a brand new branch out of main and create a new PR?
