### ISSUE TITLE
vertical-align: Live sample and images in examples are failing

### ISSUE THREAD

**Issue by mikecat** [mdn/translated-content#10287]
These pages:

* [vertical-align - CSS | MDN](https://developer.mozilla.org/pt-BR/docs/Web/CSS/vertical-align) (`pt-BR`)
  * Last commit: [`9f3b441`](https://github.com/mdn/translated-content/commit/9f3b4411439e8c8fede3aba13edd48de1e864c37)
  * Last modified: 7 de nov. de 2022
* [vertical-align - CSS | MDN](https://developer.mozilla.org/ru/docs/Web/CSS/vertical-align) (`ru`)
  * Last commit: [`bfa10f8`](https://github.com/mdn/translated-content/commit/bfa10f8d5c23d9b0bb6afab2459b069b327e2505)
  * Last modified: 7 нояб. 2022 г.

Has these issues:

* "Live sample failed!" with red background is shown where examples should be expected.
* The image `https://mdn.mozillademos.org/files/12245/frame_image.svg`, used in the example, is a blank page with HTTP 404 error.

<details><summary>Contents in the textarea by default</summary><div>

name: "[via MDN pages only // pt-br]"
description: Issue filed via "Report a problem with this content on GitHub" link on MDN pages.
labels: ["l10n-pt-br", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **Want to change this page yourself?** This content is open source!
        ↩ Go back and use the _Edit on GitHub_ link on the page.

        **Is your issue about the browser compatibility table?**
        ↩ Go back and use the _Report problems with this compatibility data on GitHub_ link on the page.

        **Need help with a browser?**
        🙋 To get help with [Firefox](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla), [Chrome](https://support.google.com/chrome/answer/95315?hl=en-GB&ref_topic=7439544), [Safari](https://www.apple.com/feedback/safari.html), or another browser, check the browser's support site.

        ---
  - type: input
    id: mdn-url
    attributes:
      label: MDN URL
      description: Set automatically. Do not modify.
    validations:
      required: true
  - type: input
    id: section
    attributes:
      label: What specific section or headline is this issue about?
  - type: textarea
    id: problem
    attributes:
      label: What information was incorrect, unhelpful, or incomplete?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Do you have any supporting links, references, or citations?
      description: Link to information that helps us confirm your issue.
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, steps to reproduce a bug, screenshots, screen recordings, or sample code
  - type: markdown
    attributes:
      value: |
        ---
        You're finished! The following fields are prefilled. Please click **Submit new issue**.
  - type: textarea
    id: metadata
    attributes:
      label: MDN metadata
      description: Set automatically. Do not modify.

</div></details>

**Comment by yin1999** [comment]
This issue has been fixed by: mdn/yari#7917.
