### ISSUE TITLE
Typo - JavaScript - function

### ISSUE THREAD

**Issue by aminelch** [mdn/translated-content#103]
[https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/function#syntaxe](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Instructions/function#syntaxe)

### Specific section or headline?
Syntaxe

instructions
    Les instructions qui constituent le corps de la fonctio. 

### should be
instructions
    Les instructions qui constituent le corps de la fonction.

**Comment by SphinxKnight** [comment]
@Antonio-Riccelli hello :) I've just assigned this one to you as the repo "opened" a few days ago.
Let me know if you need help fixing this one or if you wish to be unassigned. Thanks for offering to help!

**Comment by SphinxKnight** [comment]
Thanks @Antonio-Riccelli for the fix.
I'm closing this issue since the PR has been merged. The update should be visible on the site in 24/48hours (cf. [What'sDeployed](https://whatsdeployed.io/s/16d/mdn/translated-content))
