### ISSUE TITLE
Bad example

### ISSUE THREAD

**Issue by RomanenkoVasyl** [mdn/translated-content#10426]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds

### What specific section or headline is this issue about?

Result

### What information was incorrect, unhelpful, or incomplete?

Live sample failed!
An error occurred trying to render this live sample.
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find any live code samples for "example" within /ru/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds

### What did you expect to see?

Correct example of the explanation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/css/css_backgrounds_and_borders/using_multiple_backgrounds`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/css_backgrounds_and_borders/using_multiple_backgrounds/index.md
* Last commit: https://github.com/mdn/translated-content/commit/bfa10f8d5c23d9b0bb6afab2459b069b327e2505
* Document last modified: 2022-11-07T14:30:57.000Z

</details>

**Comment by rohini-ranjanR** [comment]
This can be solved by changing the URL of the iframe tag. 
![image](https://user-images.githubusercontent.com/109434545/208178765-a6bf3773-e81f-4156-95d6-368660f83cfa.png)
While inspecting the section need to change the iframe URL src="https://yari-demos.prod.mdn.mozit.cloud/ru/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds/_sample_.example.html" need to change to src="https://yari-demos.prod.mdn.mozit.cloud/en/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds/_sample_.example.html"

And the desired output can be seen on the browser.
