### ISSUE TITLE
[ko] ⭐6월 해결 과제 ( learn/javascript 최신화 )⭐

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#1042]
안녕하세요! 현재 ko-locale의 최신화는 많이 뒤쳐져있습니다. Javascript 부터 최신화 작업의 신호탄을 쏘아 올리고자합니다. 관심있으신 분이 있다면 같이 최신화 해나가요! 아래 괄호의 왼쪽은 번역본이 있는 한국 페이지 오른쪽은 해당 주제의 en-us 버전의 전체 페이지입니다. (png나 다른 파일들도 포함된 수치라서 정확하지 않을 수 있습니다.)

- Learn/Javascript 번역 최신화 하기 (33/98)
  - asynchronous/ (6/8)
  - client-side_web_apis/ (3/26)
  - howto/ (1/1)
  - objects/ (7/20)
  - building_blocks/ (5/18)
  - first_steps/ (10/24)
  - index.html (1/1)

우선, 주제를 정해서 하나씩 해결해나갈 예정입니다. 혹시, 같이 진행해주실 분들이 있으면 현재 이슈를 태크해주셔서 진행을 알려주세요!
 
[MDN 번역 콘텐츠에 대한 일반 지침](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md)

## learn/javascript 진행 사항

- [x] Learn/Javascript https://github.com/mdn/translated-content/pull/1046

- [ ] asynchronous
  - [ ] async_await
  - [ ] timeouts_and_intervals
  - [ ] choosing_the_right_approach
  - [ ] introducing
  - [ ] concepts
  - [ ] promises

- [ ] client-side_web_apis
  - [ ] client-side_storage
  - [ ] fetching_data 
  - [ ] introduction
  - [ ] third_party_apis
  - [ ] drawing_graphics
  - [ ] manipulating_documents
  - [ ] video_and_audio_apis

- [x] howto https://github.com/mdn/translated-content/pull/1282

- [x] objects https://github.com/mdn/translated-content/pull/1283
  - [ ] adding_bouncing_balls_features
  - [ ] object_building_practice
  - [x] basics https://github.com/mdn/translated-content/pull/1284
  - [ ] object_prototypes
  - [ ] test_your_skills_colon__json
  - [ ] inheritance
  - [ ] test_your_skills_colon__object-oriented_javascript
  - [ ] json
  - [ ] test_your_skills_colon__object_basics
  - [ ] object-oriented_js 

- [ ] building_blocks/
  - [x] build_your_own_function https://github.com/mdn/translated-content/pull/1103
  - [ ] looping_code
  - [x] conditionals https://github.com/mdn/translated-content/pull/1049
  - [x] return_values https://github.com/mdn/translated-content/pull/1103
  - [ ] events
  - [x] test_your_skills_colon__conditionals https://github.com/mdn/translated-content/pull/1049
  - [x] functions https://github.com/mdn/translated-content/pull/974
  - [ ] test_your_skills_colon__events
  - [x] image_gallery https://github.com/mdn/translated-content/pull/1146
  - [x] test_your_skills_colon__functions https://github.com/mdn/translated-content/pull/1103
  - [ ] test_your_skills_colon__loops

- [ ] first_steps
  - [x] a_first_splash https://github.com/mdn/translated-content/pull/5103
  - [ ] strings
  - [ ] useful_string_methods
  - [x] arrays https://github.com/mdn/translated-content/pull/946
  - [ ] test_your_skills_colon__arrays
  - [ ] variables https://github.com/mdn/translated-content/pull/948
  - [ ] test_your_skills_colon__math
  - [ ] what_is_javascript
  - [ ] math
  - [ ] test_your_skills_colon__strings
  - [ ] what_went_wrong
  - [ ] silly_story_generator
  - [x] test_your_skills_colon__variables https://github.com/mdn/translated-content/pull/946

**혹시 누락된 PR 있으면 알려주세요.**

## 규칙
충돌을 방지하고자 아래 몇가지 규칙을 정했습니다.

0. https://github.com/mdn/content/tree/main/files/en-us 기준으로 최신화
1. PR 이름에 해당 페이지 제목을 포함해주세요.
2. 해당 페이지에 대해 draft가 존재하는지 먼저 확인해주세요.
3. 자신이 작업중임을 표시하기위해 draft를 먼저 생성해주세요. [Github draft](https://github.blog/2019-02-14-introducing-draft-pull-requests/). 충돌이 일어날 경우 먼저 올린 PR 에 우선순위를 두어서 처리를 할 예정입니다.
4. 해당 이슈를 태크해주세요. 
5. Merge 후 진행사항은 comment나 태그해주시면 제가 확인후 수정하겠습니다.

6월에도 좋은 하루하루 보내세요 :)

---

반복되는 틀에 대해서는 기준을 정해놓는것이 통일화에 좋다고 생각해서 추가했습니다. 

- callout 틀
```html
<div class="callout">
  <h4 id="looking_to_become_a_front-end_web_developer">프론트엔드 웹 개발자가 되고자 하시나요?</h4>

  <p>목표를 달성하기 위한 모든 필수 정보가 들어있는 교육 과정을 준비했습니다.</p>

  <p>
    <a href="/ko/docs/Learn/Front-end_web_developer"><strong>시작하기</strong></a>
  </p>
</div>
```

**Comment by logic-finder** [comment]
안녕하세요 번역하다가 생각이 들었는데 각 모듈(단원?)에 들어 있는 장(챕터)들의 제목을 통일할 필요성이 있을 것 같습니다.
![image](https://user-images.githubusercontent.com/83723320/120124908-79d1be00-c1f1-11eb-92e9-5748ec39951b.png)

**Comment by hochan222** [comment]
> 안녕하세요 번역하다가 생각이 들었는데 각 모듈(단원?)에 들어 있는 장(챕터)들의 제목을 통일할 필요성이 있을 것 같습니다. 번역하시는 분마다 다르게 번역하면 보는 입장에서 조금 혼란을 느낄 수도 있을 것 같다는 생각이 듭니다.

좋은 생각입니다! 좋아 보여요! 감사합니다 :)

**Comment by gidongkwon** [comment]
> 프런트엔드 웹 개발자가 되고자 하시나요?

표기법상 "프론트엔드" 쪽이 좀 더 좋지 않을까요?

**Comment by hochan222** [comment]
해당 페이지가 프런트 엔드 분야 중 웹 분야로 한정되어있고, 영어로도 웹이 명시되어 있기 때문에 웹을 붙여주는게 더 의미 전달이 명확하다고 생각해서 붙여주어야한다고 생각합니다. 프런트 엔드에 데스크탑 앱도 포함 될 수 있으니까요!

https://developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer

**Comment by gidongkwon** [comment]
> 해당 페이지가 프런트 엔드 분야 중 웹 분야로 한정되어있고, 영어로도 웹이 명시되어 있기 때문에 웹을 붙여주는게 더 의미 전달이 명확하다고 생각해서 붙여주어야한다고 생각합니다.
> 
> https://developer.mozilla.org/en-US/docs/Learn/Front-end_web_developer

앗 프"런"트를 프"론"트로 바꾸는 게 어떠한지에 대한 제안이었습니다. 웹은 저도 들어가는게 맞다고 봅니다

**Comment by hochan222** [comment]
앗앗 론이 런으로 보였습니다 ㅠㅠ 저도 동의합니다! 제안해주셔서 감사합니다 ㅎㅎ 좋은 제안 입니다. 수정했습니다 :)

**Comment by hochan222** [comment]
--- 1081, 1089, 1099

**Comment by logic-finder** [comment]
안녕하세요 다름이 아니라 #948 은 문서 하단에 테스트 섹션만을 추가한 pr입니다. 문서 전체가 수정되지는 않아서 (현재 한국어 문서 들어가 보시면 위쪽 부분에서는 반말 사용하고 있는데 아래 부분에서는 존댓말 사용하고 있는 것을 보실 수 있습니다) 아직 완료 표시를 하기에는 이른 것 같습니다.

그리고 return values 문서만 따로 files changed 링크를 걸어놓은 이유가 있으신지 여쭤봐도 될까요?

**Comment by hochan222** [comment]
@logic-finder 님 안녕하세요. 답변 드립니다.

언급 후 merge된 PR에 대해 바뀐 부분만 확인하고 위 표에 추가했습니다. 삭제 하겠습니다.

링크에 대해서는 오타입니다. 수정했습니다. 

기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

**Comment by wisedog** [comment]
@hochan222  Learn에 나오는 Prerequisites, Objective 의 해석이 다 제각각인데 뭘로 맞추는게 좋을까요?

**Comment by wisedog** [comment]
6월도 끝났는데, 이벤트 종료인가요!?

**Comment by hochan222** [comment]
함께 기여해주셔서 감사합니다. 기여해주신 덕분에 미번역된 문서들이 많이 줄어들었습니다. 기여된 문서들은 많은 사람들에게 큰 도움이 될것입니다.

`learn` 카테고리를 선정한 이유에 대해 조금 이야기를 드리자면, 아래와 같은 이유들이 있었습니다.

- `learn` 카테고리는 전체 카테고리 중 2번째로 트래픽이 많다. (`web` 카테고리: 1위)
- MDN에서 현재 HTML 기반 문서들을 Markdown으로 변환하려는 움직임이 보였고 가장 비교적 영향이 적다.
- 세부 문법 spec과는 별도로 기본 안내서이다.

#### __최근 Markdown 변환에 대한 MDN의 공식 입장이 나왔습니다.__ (Converting MDN to Markdown https://github.com/mdn/translated-content/discussions/1236)

기존의 HTML 기반 문서들은 현지화 팀 입장에서는 너무 불편했고, 이에 Markdown으로 문서를 작성할 수 있게 yari를 개선하고 있습니다. 

정확히는 JS 문서(HTML 기반 문서)를 Markdown으로 변환하고 yari를 통해서 HTML로 렌더링할 수 있게 하는것이 목표이며, 추가적으로 JS 문서를 Markdown으로 변환하는 작업도 기능에 포함돼있습니다. 현재는 테스트 단계이며, 우선적으로 en-US 콘텐츠에 대해 7월 중순까지 `/en-US/docs/Web/JavaScript/`아래의 모든 것을 변환하여 공개한다고 합니다.

한편, HTML 기반 문서에 대해서는 영원히는 아니지만 오랫동안 HTML 소스로 작업 할 수 있도록 유지한다고 합니다.

일부 en-US 페이지들이 Markdown으로 번역이 완료되면 HTML 번역과 동기화 상태를 유지하기가 더 어려울 것입니다. 따라서, 번역 된 콘텐츠는 편리하게 빨리 변환하는 것이 좋다는 공식 입장이 해당 discussions에 있습니다.

우선, 우선 순위가 `/ko/docs/Web/JavaScript/` 가 더 높아서 `[ko] ⭐6월 해결 과제 ( learn/javascript 최신화 )⭐` 이슈는 추가적인 공식 입장이 나오면 닫으려고 합니다. 모두 기여해주셔서 감사합니다.

그전까지 저는 해당 이슈에 관심을 계속 갖고 `/learn/javascript`에 대해 기본적인 동기화는 끝맺음을 할 예정입니다. 

모두 감사합니다. 좋은 하루 보내세요 :)

---

> @hochan222 Learn에 나오는 Prerequisites, Objective 의 해석이 다 제각각인데 뭘로 맞추는게 좋을까요?

https://github.com/mdn/translated-content/pull/1081 해당 PR에서 용어 관련 부분은 7월 11일 일요일까지 내부적으로 논의한 후 기준 초안을 작성하여 올릴 예정입니다. 해당 PR에서 확인해주시고 의견 남겨주세요. 

`Objective` 단어의 경우는 해당 단어가 쓰인곳의 링크를 알려주실 수 있으신가요?

**Comment by wisedog** [comment]
> @logic-finder @gidongkwon @wisedog @yechoi42 @seung-00
> 
> 함께 기여해주셔서 감사합니다. 기여해주신 덕분에 미번역된 문서들이 많이 줄어들었습니다. 기여된 문서들은 많은 사람들에게 큰 도움이 될것입니다.
> 
> `learn` 카테고리를 선정한 이유에 대해 조금 이야기를 드리자면, 아래와 같은 이유들이 있었습니다.
> 
> * `learn` 카테고리는 전체 카테고리 중 2번째로 트래픽이 많다. (`web` 카테고리: 1위)
> * MDN에서 현재 HTML 기반 문서들을 Markdown으로 변환하려는 움직임이 보였고 비교적 영향이 적다.
> * 세부 문법 spec과는 별도로 기본 안내서이다.
> 
> #### **최근 Markdown 변환에 대한 MDN의 공식 입장이 나왔습니다.** (Converting MDN to Markdown #1236)
> 기존의 HTML 기반 문서들은 현지화 팀 입장에서는 너무 불편했고, 이에 Markdown으로 문서를 작성할 수 있게 yari를 개선하고 있습니다.
> 
> 정확히는 JS 문서(HTML 기반 문서)를 Markdown으로 변환하고 yari를 통해서 HTML로 렌더링할 수 있게 하는것이 목표이며, 추가적으로 JS 문서를 Markdown으로 변환하는 작업도 기능에 포함돼있습니다. 현재는 테스트 단계이며, 우선적으로 en-US 콘텐츠에 대해 7월 중순까지 `/en-US/docs/Web/JavaScript/`아래의 모든 것을 변환하여 공개한다고 합니다.
> 
> 한편, HTML 기반 문서에 대해서는 영원히는 아니지만 오랫동안 HTML 소스로 작업 할 수 있도록 유지한다고 합니다.
> 
> 일부 en-US 페이지들이 Markdown으로 번역이 완료되면 HTML 번역과 동기화 상태를 유지하기가 더 어려울 것입니다. 따라서, 번역 된 콘텐츠는 편리하게 빨리 변환하는 것이 좋다는 공식 입장이 해당 discussions에 있습니다.
> 
> 우선, 우선 순위가 `/ko/docs/Web/JavaScript/` 가 더 높아서 `[ko] ⭐6월 해결 과제 ( learn/javascript 최신화 )⭐` 이슈는 추가적인 공식 입장이 나오면 닫으려고 합니다. 모두 기여해주셔서 감사합니다.
> 
> 그전까지 저는 해당 이슈에 관심을 계속 갖고 `/learn/javascript`에 대해 기본적인 동기화는 끝맺음을 할 예정입니다.
> 
> 모두 감사합니다. 좋은 하루 보내세요 :)
> 
> > @hochan222 Learn에 나오는 Prerequisites, Objective 의 해석이 다 제각각인데 뭘로 맞추는게 좋을까요?
> 
> @wisedog #1081 해당 PR에서 용어 관련 부분은 **7월 11일 일요일까지** 내부적으로 논의한 후 기준 초안을 작성하여 올릴 예정입니다. 해당 PR에서 확인해주시고 의견 남겨주세요.
> 
> `Objective` 단어의 경우는 해당 단어가 쓰인곳의 링크를 알려주실 수 있으신가요?


https://developer.mozilla.org/ko/docs/Learn/JavaScript/First_steps 의 각 항목마다 Prerequisites, Objective 가 있는데 해석이 다 제각각입니다 

MDN 팀이 markdown 으로 변환하면 당분간은 `/ko/docs/Web/JavaScript/` 위주로 번역작업을 하실 계획이시죠?

**Comment by hochan222** [comment]
> https://developer.mozilla.org/ko/docs/Learn/JavaScript/First_steps 의 각 항목마다 Prerequisites, Objective 가 있는데 해석이 다 제각각입니다

아래 파트의 안내문구 안의 Objective에 대한 내용도 같이 포함해서 논의하겠습니다! (https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/A_first_splash)

![image](https://user-images.githubusercontent.com/22424891/124700051-f8bfc200-df26-11eb-9045-0674dd412597.png)

> MDN 팀이 markdown 으로 변환하면 당분간은 /ko/docs/Web/JavaScript/ 위주로 번역작업을 하실 계획이시죠?

네! 맞습니다. 저는 당분간은 /ko/docs/Web/JavaScript/ 위주로 작업을 할 계획입니다.

**Comment by zeallat** [comment]
혹시 한 문단 혹은 페이지의 일부만 번역하는 것도 받아주시나요?

**Comment by hochan222** [comment]
@zeallat 님 안녕하세요. 

방치가 되어 문서의 품질을 떨어뜨리는 경우가 많아 원칙상 [cors](https://developer.mozilla.org/ko/docs/Web/HTTP/CORS) 페이지와 같이 문서가 길지 않는 경우에는 받아들이지 않고 있습니다. 

어떤 원칙이더라도 더 합리적인 방법이 있다면 언제든지 모든 리뷰어 분들과 의논하실 수 있습니다.

좋은 하루 보내세요 :)

**Comment by hochan222** [comment]
현재 yari를 통해 미번역 페이지 확인이 가능하여 현재 이슈 닫겠습니다! 미번역 페이지는 [Yari Translations Dashboard section](https://egas.tistory.com/168#yari-translations-dashboard)의 Translation Missing 페이지에서 확인할 수 있습니다.

감사합니다 :)
