### ISSUE TITLE
Chore: macro deprecation: CanvasSidebar should be removed

### ISSUE THREAD

**Issue by wbamberg** [mdn/translated-content#10516]
👋 l10n people!

Following on from https://github.com/mdn/translated-content/issues/10177, I'm still working on removing custom sidebars from the Web/API docs. This time we are retiring the [`CanvasSidebar.ejs`](https://github.com/mdn/yari/blob/main/kumascript/macros/CanvasSidebar.ejs) macro.

In https://github.com/mdn/content/pull/22586 I removed references to `CanvasSidebar` from en-US content, and in https://github.com/mdn/yari/pull/7760 I've deprecated it.

Note that this also uses the new "Tutorial" string from [L10n-Common.json](https://github.com/mdn/content/blob/d26ee027683b70c549ed7b105149cddf4181e568/files/jsondata/L10n-Common.json#L170-L177), so if you think the value given there is wrong for your locale, please make a PR against that file and tag me for a review :).

After this there is one more custom sidebar left, [`WebGLSidebar.ejs`](https://github.com/mdn/yari/blob/main/kumascript/macros/WebGLSidebar.ejs), which will be coming up soon!

TODO:

- [x] zh-cn, zh-tw: #10521
- [x] fr #10587
- [x] ja #10680
- [x] ru #11501
- [x] ko #10567
- [x] pt-br #11500
- [x] es: #10538

**Comment by queengooborg** [comment]
All `{{CanvasSidebar}}` instances have been removed now, thanks to all for your hard work!
