### ISSUE TITLE
The example in JA translation doesn't have `::first-letter` pseudo class

### ISSUE THREAD

**Issue by kojiishi** [mdn/translated-content#10542]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/CSS/initial-letter

### What information was incorrect, unhelpful, or incomplete?

In the examples section, [the English version](https://developer.mozilla.org/en-US/docs/Web/CSS/initial-letter) has `::first-letter` pseudo class, such as:
```
.normal::first-letter {
  -webkit-initial-letter: normal;
  initial-letter: normal;
}
```
while the Japanese translation doesn't have it:
```
.normal {
  -webkit-initial-letter: normal;
  initial-letter: normal;
}
```

Both Safari and Chrome (M101) requires `::first-letter` to work, so great to have that in the Japanese translation too.

### What did you expect to see?

CSS selectors should be `.class::first-letter`.

### Do you have any supporting links, references, or citations?

https://chromestatus.com/feature/5167442033115136

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/css/initial-letter`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/initial-letter
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/initial-letter/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c61d071db5adcc275900e86f4b2f962bff654a1e
* Document last modified: 2022-11-28T15:20:08.000Z

</details>

**Comment by BoseSj** [comment]
That seems an easy fix, should I go check on that, or is anyone else on it?
