### ISSUE TITLE
Canary Channel and REST API

### ISSUE THREAD

**Issue by Africanj1952** [mdn/translated-content#10556]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/Document_Object_Model

### What specific section or headline is this issue about?

Beta Channel forming

### What information was incorrect, unhelpful, or incomplete?

all incomplete within GitHub domain

### What did you expect to see?

improvement

### Do you have any supporting links, references, or citations?

Windows Canary Channel download website

### Do you have anything more you want to share?

not until networking is formed

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/document_object_model`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Document_Object_Model
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/document_object_model/index.md
* Last commit: https://github.com/mdn/translated-content/commit/dc0e577e0933bb52434e044f47bc47b4539085c1
* Document last modified: 2022-10-01T01:42:44.000Z

</details>

**Comment by yin1999** [comment]
This seems to be an invalid issue, closed as not planned.
