### ISSUE TITLE
The example result text 'And here is a span' should be red color

### ISSUE THREAD

**Issue by iwanderer** [mdn/translated-content#10633]
name: "[via MDN pages only // zh-cn]"
description: Issue filed via "Report a problem with this content on GitHub" link on MDN pages.
labels: ["l10n-zh", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ### Before you start

        **Want to change this page yourself?** This content is open source!
        ↩ Go back and use the _Edit on GitHub_ link on the page.

        **Is your issue about the browser compatibility table?**
        ↩ Go back and use the _Report problems with this compatibility data on GitHub_ link on the page.

        **Need help with a browser?**
        🙋 To get help with [Firefox](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla), [Chrome](https://support.google.com/chrome/answer/95315?hl=en-GB&ref_topic=7439544), [Safari](https://www.apple.com/feedback/safari.html), or another browser, check the browser's support site.

        ---
  - type: input
    id: mdn-url
    attributes:
      label: MDN URL
      description: Set automatically. Do not modify.
    validations:
      required: true
  - type: input
    id: section
    attributes:
      label: What specific section or headline is this issue about?
  - type: textarea
    id: problem
    attributes:
      label: What information was incorrect, unhelpful, or incomplete?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to see?
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: Do you have any supporting links, references, or citations?
      description: Link to information that helps us confirm your issue.
  - type: textarea
    id: more-info
    attributes:
      label: Do you have anything more you want to share?
      description: For example, steps to reproduce a bug, screenshots, screen recordings, or sample code
  - type: markdown
    attributes:
      value: |
        ---
        You're finished! The following fields are prefilled. Please click **Submit new issue**.
  - type: textarea
    id: metadata
    attributes:
      label: MDN metadata
      description: Set automatically. Do not modify.

**Comment by iwanderer** [comment]
Hi @yin1999 , thanks for the reply. I did just like you told me to, it seens that there was a problem with the MDN website in zh-CN  language: https://developer.mozilla.org/zh-CN/docs/Web/CSS/General_sibling_combinator
I clicked the "Report a problem width this content on Github" link, but it did not work well like the english language site.
You can check the link to see what was wrong.
for zh-CN:
![image](https://user-images.githubusercontent.com/5506208/207546376-aa58a77f-2c98-4cd7-8ae5-df5cb5e8d10b.png)

for english:
![image](https://user-images.githubusercontent.com/5506208/207546464-61664456-f4c7-4107-b6e8-7f9d56e72297.png)

**Comment by yin1999** [comment]
@iwanderer. One more thing, is there any error that you want to report for any MDN page. Could you describe that? I would open another issue for that

**Comment by yin1999** [comment]
Hi @iwanderer, we can now report a page issue from mdn pages with zh-CN locales. Thanks for notifying this :)
