### ISSUE TITLE
New Issue mdn/transcript  Java Script

### ISSUE THREAD

**Issue by Africanj1952** [mdn/translated-content#10663]
### MDN URL

https://developer.mozilla.org/ja/docs/Learn/Server-side/Express_Nodejs

### What specific section or headline is this issue about?

text files' dislocation 

### What information was incorrect, unhelpful, or incomplete?

missing text file contents

### What did you expect to see?

copyright and trademarking 

### Do you have any supporting links, references, or citations?

MDN Japan

### Do you have anything more you want to share?

MSN Japan?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/learn/server-side/express_nodejs`
* MDN URL: https://developer.mozilla.org/ja/docs/Learn/Server-side/Express_Nodejs
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/learn/server-side/express_nodejs/index.md
* Last commit: https://github.com/mdn/translated-content/commit/cdd27b7a946dd470be1e040bd02461715c0dc78a
* Document last modified: 2022-11-26T16:12:07.000Z

</details>

**Comment by yin1999** [comment]
Please provide useful information about any content issue on MDN, I'm going to close this.
