### ISSUE TITLE
English pages instead of Japanese ones are linked from the compatibility list 

### ISSUE THREAD

**Issue by mikecat** [mdn/translated-content#10781]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/URL

### What specific section or headline is this issue about?

ブラウザーの互換性

### What information was incorrect, unhelpful, or incomplete?

表の一番左の列のリンク先がMDNの英語版ページになっている。

MDN English pages are linked from the leftmost column of the table.

### What did you expect to see?

リンク先をMDNの日本語版ページにする。

Japanese pages are linked instead of English ones.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/url`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/URL
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/url/index.md
* Last commit: https://github.com/mdn/translated-content/commit/5cd3c47356b2bdcb4e6caa3d80a7097806e1f4f6
* Document last modified: 2022-12-02T14:14:17.000Z

</details>

**Comment by manjuu-eater** [comment]
互換性の表自体の問題みたいです。
URLのページでも中韓版やポルトガル語版なんかを見ても互換性の表は英語版へのリンクになっていますし、
https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Number
などの別のページでも同様に英語版へのリンクになっています。

互換性の表は `{{Compat}}` っていう[マクロ](https://github.com/mdn/yari/blob/5d8d88976164b6f653c3f2de688f3cd76f8537bb/kumascript/macros/Compat.ejs)を変換してるのですが、その変換にリンクをローカライズする処理を加える必要があるのかもしれません。
（これ以上はわかりません…すみません）

**Comment by YujiSoftware** [comment]
こちらは、最終的に mdn/yari#10373 で修正が行われました。
どなたかクローズしていただければと思います。

**Comment by yin1999** [comment]
Hey all. I think we have resolved this after mdn/yari#10373 got merged. I'm going to close this for now :)
