### ISSUE TITLE
I can't put the maximum height in the dialog component

### ISSUE THREAD

**Issue by PedroFrancoDev** [mdn/translated-content#10805]
### MDN URL

https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

 Max height in dialog component

### What information was incorrect, unhelpful, or incomplete?

I didn't see any incorrect information.

### What did you expect to see?

__I hope to be able to put a maximum height on the component dialog__

### Do you have anything more you want to share?

__This is the code__

![Captura de tela de 2022-12-28 12-01-34](https://user-images.githubusercontent.com/84667750/209802311-fea181d1-2cd8-400c-89ac-77659bd5329a.png)

__I can't put maximum height in the white container (dialog)__

![Captura de tela de 2022-12-28 11-58-42](https://user-images.githubusercontent.com/84667750/209802442-f6f05836-ae5d-44d5-aea8-d1f88bb0b7e6.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/translated-content/commit/9f3b4411439e8c8fede3aba13edd48de1e864c37
* Document last modified: 2022-11-06T15:41:26.000Z

</details>

**Comment by yin1999** [comment]
Hi @PedroFrancoDev, this is not a content issue.

And... I'm not sure should [`max-height`](https://developer.mozilla.org/en-US/docs/Web/CSS/max-height) property is what you're looking for.

I'm going to close this issue, and if you have any problem about this, feel free to comment.
