### ISSUE TITLE
Traduction de void

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#10818]
### MDN URL

https://developer.mozilla.org/fr/docs/Glossary/Void_element

### What information was incorrect, unhelpful, or incomplete?

Si en anglais la terminologie utilisée est bien "void element",

dans le premier paragraphe de la page française il faudrait mieux traduire 
_Un élément vide (void element en anglais) est un élément HTML, ..._
que par
_Un élément vide (empty element en anglais) est un élément HTML, ..._ 

afin de rester cohérent avec la terminologie HTML.

### What did you expect to see?

Un élément vide (void element en anglais) est un élément HTML, 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/glossary/void_element`
* MDN URL: https://developer.mozilla.org/fr/docs/Glossary/Void_element
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/glossary/void_element/index.md
* Last commit: https://github.com/mdn/translated-content/commit/15dc79d1f671a6472ca301d4eeb37371ff8294bc
* Document last modified: 2022-11-28T09:06:21.000Z

</details>

**Comment by SphinxKnight** [comment]
Il y avait eu un déplacement/changement de titre pour la page anglaise par le passé, je propose une mise à jour de la page pour corriger ça.

Merci d'avoir remonté le problème :)
