### ISSUE TITLE
English titles are displayed in the menu in the left of the page

### ISSUE THREAD

**Issue by mikecat** [mdn/translated-content#10840]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/IndexedDB_API

### What specific section or headline is this issue about?

Related Topics / ガイド

### What information was incorrect, unhelpful, or incomplete?

日本語のページなのに、以下の英語版のページのタイトルがメニューに使われている。

* Using IndexedDB
* IndexedDB key characteristics and basic terminology
* Browser storage limits and eviction criteria
* Checking when a deadline is due

### What did you expect to see?

メニューに日本語版のページのタイトルを表示する。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/indexeddb_api`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/IndexedDB_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/indexeddb_api/index.md
* Last commit: https://github.com/mdn/translated-content/commit/43d827dcb94055f333ad8a52f812acfd32b9976c
* Document last modified: 2022-12-18T09:12:56.000Z

</details>

**Comment by yin1999** [comment]
This is a known issue of yari platform: mdn/yari#7438.
