### ISSUE TITLE
MDN-ის თარგმნა ქართულ ენაზე

### ISSUE THREAD

**Issue by jshar** [mdn/translated-content#10873]
ეს არის მთავარი თემა, სადაც შეგიძლიათ შესთავაზოთ თქვენი დახმარება, დასვათ შეკითხვები ან გააზიაროთ წინადადებები.

ზოგიერთი განყოფილებისთვის შეიქმნა ცალკეული ნომრები სათარგმნი გვერდების სიით, სადაც შეგიძლიათ აირჩიოთ რა უნდა თარგმნოთ, მანამდე უბრალოდ გააუქმეთ გამოწერა, რათა სხვებმა იცოდნენ თქვენი ნამუშევრების შესახებ და ჩვენ მოგნიშნავთ სიაში.

თუ გსურთ თარგმნოთ გვერდი იმ განყოფილებიდან, რომლისთვისაც ცალკე საკითხი არ არის, გთხოვთ, შეგვატყობინოთ აქ. ასევე სასურველია წინასწარ აცნობოთ ძირითადი ცვლილებების შესახებ.

და რა თქმა უნდა, სანამ დაიწყებთ, აუცილებლად წაიკითხეთ [თარგმანის სახელმძღვანელო](https://github.com/mdn/translated-content/blob/main/docs/ka/translation-guide.md).

**Comment by jshar** [comment]
ეს არის მთავარი თემა, სადაც შეგიძლიათ შესთავაზოთ თქვენი დახმარება, დასვათ შეკითხვები ან გააზიაროთ წინადადებები.

ზოგიერთი განყოფილებისთვის შეიქმნა ცალკეული ნომრები სათარგმნი გვერდების სიით, სადაც შეგიძლიათ აირჩიოთ რა უნდა თარგმნოთ, მანამდე უბრალოდ გააუქმეთ გამოწერა, რათა სხვებმა იცოდნენ თქვენი ნამუშევრების შესახებ და ჩვენ მოგნიშნავთ სიაში.

თუ გსურთ თარგმნოთ გვერდი იმ განყოფილებიდან, რომლისთვისაც ცალკე საკითხი არ არის, გთხოვთ, შეგვატყობინოთ აქ. ასევე სასურველია წინასწარ აცნობოთ ძირითადი ცვლილებების შესახებ.

და რა თქმა უნდა, სანამ დაიწყებთ, აუცილებლად წაიკითხეთ [თარგმანის სახელმძღვანელო](https://github.com/mdn/translated-content/blob/main/docs/ka/translation-guide.md).

**Comment by yin1999** [comment]
Hi @jshar, please specific the problem you have encountered. Feel free to append on this thread.
