### ISSUE TITLE
Regarding the disappearance and untranslation of the directory after localization

### ISSUE THREAD

**Issue by fwqaaq** [mdn/translated-content#10892]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Web_Workers_API/Transferable_objects

### What information was incorrect, unhelpful, or incomplete?

No sidebar
![image](https://user-images.githubusercontent.com/82551626/210472162-d7194079-a18d-4124-8821-0a34df2d44f6.png)

AND

untranslated sidebar

![image](https://user-images.githubusercontent.com/82551626/210472358-52b4ffc8-1441-409a-8cd1-711a73b27963.png)

### What did you expect to see?

Sidebar
![image](https://user-images.githubusercontent.com/82551626/210472198-23f13fdd-89fc-4495-a561-58bd622f4f2b.png)

**Comment by yin1999** [comment]
> untranslated sidebar
>
> ![image](https://user-images.githubusercontent.com/82551626/210472358-52b4ffc8-1441-409a-8cd1-711a73b27963.png)

The same issue metioned by #10840. This is a known issue of yari platform: https://github.com/mdn/yari/issues/7438.

The only thing we should do for this issue should be **Add sidebar macro this this document**.

**Comment by fwqaaq** [comment]
ohhhh, but why no sidebar? Or what we need to do?

**Comment by yin1999** [comment]
All the sidebar in documents are rendered by sidebar macro. In this page, we use [`DefaultAPISidebar`](https://github.com/mdn/content/blob/59a0a003281f70f55ac524bb3c370b19f0a7a14a/files/en-us/web/api/web_workers_api/transferable_objects/index.md?plain=1#L12).

See also: https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Page_structures/Macros/Commonly_used_macros#%E6%B7%BB%E5%8A%A0%E4%BE%A7%E8%BE%B9%E6%A0%8F

**Comment by fwqaaq** [comment]
Soga, but the question about the translation is still in progress?

**Comment by yin1999** [comment]
Tracked in the mentioned issue, but there seems to be no any process on this. If you are interested in [the issue](https://github.com/mdn/yari/issues/7438), you can have a look on this.

**Comment by fwqaaq** [comment]
Okay
