### ISSUE TITLE
Invalid link in "HTTP Methods" page: DELETE, GET, HEAD, POST

### ISSUE THREAD

**Issue by shc0743** [mdn/translated-content#10928]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Methods/GET

(not only this page; also see `Do you have any supporting links, references, or citations?`)

### What specific section or headline is this issue about?

DELETE; GET; HEAD; POST

### What information was incorrect, unhelpful, or incomplete?

"此文档尚未被撰写，期待你的贡献!"
![image](https://user-images.githubusercontent.com/60457042/210727723-86714b20-1dad-4113-984f-47ccfd0585d2.png)
![image](https://user-images.githubusercontent.com/60457042/210728784-568c64c4-de48-4744-a3b0-19c3f012310c.png)

### What did you expect to see?

These links should be accessable
![image](https://user-images.githubusercontent.com/60457042/210729511-5e7768a3-9648-4833-bcd8-5c2d6fc9c196.png)

### Do you have any supporting links, references, or citations?

These links should be accessable because the page has written:
```
https://developer.mozilla.org/zh-CN/docs/Glossary/Safe
https://developer.mozilla.org/en-US/docs/Glossary/Cacheable
```

But these page says they are unwritten.
```
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Methods/DELETE
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Methods/GET
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Methods/HEAD
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Methods/POST
```
![image](https://user-images.githubusercontent.com/60457042/210728784-568c64c4-de48-4744-a3b0-19c3f012310c.png)

### Do you have anything more you want to share?

In `DELETE` `GET` `HEAD` `POST` , these two links are unaccessable;
but in `CONNECT` `OPTIONS` `PATCH` `PUT` `TRACE` , they are accessable because the English document is correct.
![image](https://user-images.githubusercontent.com/60457042/210730136-8bb215fa-0924-402a-bfa9-4c67a7215bf8.png)
![image](https://user-images.githubusercontent.com/60457042/210730260-498cbebe-4993-46c1-900f-599f6e42b841.png)
I don't know how to edit it

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/http/methods/get`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Methods/GET
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/http/methods/get/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d322295b60e2ec47e0567937a7e439c849b19a9e
* Document last modified: 2022-09-21T23:46:25.000Z

</details>

**Comment by fwqaaq** [comment]
You can refer https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Write_a_new_entry_in_the_glossary

**Comment by yin1999** [comment]
See: https://github.com/mdn/content/blob/71b18d8e3e4a51dc9eddd4b6690df48a41ae184a/files/en-us/web/http/methods/get/index.md?plain=1#L17-L44

just replace `{{Glossary("安全")}}` with `{{Glossary("Safe/HTTP", "安全")}}`, etc

**Comment by shc0743** [comment]
> See: https://github.com/mdn/content/blob/71b18d8e3e4a51dc9eddd4b6690df48a41ae184a/files/en-us/web/http/methods/get/index.md?plain=1#L17-L44
> 
> just replace `{{Glossary("安全")}}` with `{{Glossary("Safe/HTTP", "安全")}}`, etc
> 
> * `{{Glossary("幂等")}}` ---> `{{Glossary("Idempotent", "幂等")}}`
> * `{{Glossary("可缓存")}}` ---> `{{Glossary("Cacheable", "可缓存")}}`

Thanks!
I'm going to open a pull request.
