### ISSUE TITLE
画像のリンク切れ

### ISSUE THREAD

**Issue by Yukinyaaa** [mdn/translated-content#10992]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/Window/alert

### What specific section or headline is this issue about?

例

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/65931718/211180187-38c14253-44bb-4021-bb1a-370a8a961301.png)

### What did you expect to see?

![image](https://developer.mozilla.org/en-US/docs/Web/API/Window/alert/alerthelloworld.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/window/alert`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Window/alert
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/window/alert/index.md
* Last commit: https://github.com/mdn/translated-content/commit/5cd3c47356b2bdcb4e6caa3d80a7097806e1f4f6
* Document last modified: 2022-12-02T14:14:17.000Z

</details>

**Comment by manjuu-eater** [comment]
英語版では2021/01/05に既に直されてたみたいですね。
https://github.com/mdn/content/commit/0d3aa5d45e3155d193964323556d1fae40afa7aa

新参者ですが、皆さんお忙しいようですし直してみます
