### ISSUE TITLE
In the french version of canvas tutorial , animation section , the images canvas_sun.png are not present

### ISSUE THREAD

**Issue by yanniser** [mdn/translated-content#10995]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations

### What specific section or headline is this issue about?

https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations#un_syst%C3%A8me_terrestre_anim%C3%A9

### What information was incorrect, unhelpful, or incomplete?

The earth animation is not functioning because the png images are not present ( they are in the english version) 

### What did you expect to see?

The earth with its moon rotating around the sun

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/canvas_api/tutorial/basic_animations`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Basic_animations
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/canvas_api/tutorial/basic_animations/index.md
* Last commit: https://github.com/mdn/translated-content/commit/bb284d0cc7f7582193829dc7f35dc2b5eb249eec
* Document last modified: 2022-12-14T08:11:14.000Z

</details>

**Comment by SphinxKnight** [comment]
this is https://github.com/mdn/yari/issues/5652
I'll be commenting on the PR itself
