### ISSUE TITLE
Little misstype in word "in" in Chinese

### ISSUE THREAD

**Issue by Zerokkkkk** [mdn/translated-content#11046]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Set-Cookie

### What information was incorrect, unhelpful, or incomplete?

Set-Cookie
响应标头 Set-Cookie 被用来由服务器端向用户代理发送 cookie，所以用户代理可再**_（It should be “在” rather than “再”）_**后续的请求中将其发送回服务器。服务器要发送多个 cookie，则应该在同一响应中发送多个 Set-Cookie 标头。

### What did you expect to see?

replace “再” with "在"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/http/headers/set-cookie`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/Set-Cookie
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/http/headers/set-cookie/index.md
* Last commit: https://github.com/mdn/translated-content/commit/8364767a38e76d865eb1df74721eb7ca7eecebeb
* Document last modified: 2023-01-02T11:57:16.000Z

</details>

**Comment by yin1999** [comment]
Good catch. This is a simple typo error. If you have time, please modify this line and create a PR. I'd like to review :)

https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/http/headers/set-cookie/index.md?plain=1#L8
