### ISSUE TITLE
Guide의 번역 

### ISSUE THREAD

**Issue by coding-Alice** [mdn/translated-content#11093]
### MDN URL

https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-title

### What information was incorrect, unhelpful, or incomplete?

`Guide`의 번역이 현재 다 재각각입니다. 

어디서인가는 [안내서](https://developer.mozilla.org/ko/docs/Web/Guide) 로 번역이 되고 있고, 어디서는 [가이드](https://developer.mozilla.org/ko/docs/Learn/Forms)라고 번역이 되고 있습니다. 

현재 [MDN Korea 문서](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-title) 에서는 `지침` 으로 번역이 되어있지만, 많은 본문에서 ([예제1](https://developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout#%EC%95%88%EB%82%B4%EC%84%9C), [예제2](https://developer.mozilla.org/ko/docs/Learn/CSS/Building_blocks/Values_and_units#%EC%88%AB%EC%9E%90_%EA%B8%B8%EC%9D%B4_%EB%B0%8F_%EB%B0%B1%EB%B6%84%EC%9C%A8)) `Instruction`의 번역으로 `지침` 이라는 단어를 많이 사용합니다. 

### What did you expect to see?

(국립국어원)[https://www.korean.go.kr/front/imprv/stndrdView.do?mn_id=159&imprv_stndrd_seq=24]에 따르면 guide를 `가이드`로 표준화해서 사용이 가능하니, `가이드` 로 번역하는 것에 대해 어떻게 생각하시나요?

**Comment by coding-Alice** [comment]
cc. @mdn/yari-content-ko

**Comment by ProHC** [comment]
@hochan222

**Comment by ProHC** [comment]
@mdn/yari-content-ko

**Comment by hochan222** [comment]
안녕하세요..! 깃허브에서 조직에 속해있지 않으면 팀을 멘션해도 알람을 받을수 없어 늦게 확인이 되었네요. 다음에는 제 이름으로 멘션 부탁드려요 :) 

현재 `directives` 도 지침으로 사용되고 있어서 용어 정리를 해야할것같습니다.

의견 부탁드려요. (cc. @mdn/yari-content-ko , @coding-Alice )

### AS IS

- Instruction: 지침
- directives: 지침
- Guide: 지침

### TO BE

- Instruction: 
- directives: 지침
- Guide: 안내서

**Comment by pje1740** [comment]
- Instruction: 설명

그런데 설명이란 단어는 또 다른 데서 중복될 수도 있겠다 싶기도 하네요 🤔
Guide를 그냥 `가이드`로 번역해도 된다면 개인적으로는 

- Instruction: 안내
- directives: 지침
- Guide: 가이드

이렇게도 번역해도 괜찮지 않나 싶어 소소하게 의견 남겨봅니다!

**Comment by coding-Alice** [comment]
> Guide는 겹치지 않게 안내서로 변경해도 좋을것같습니다. 기존 문서에 안내서로 번역된 곳도 꽤 많아서요.)

안내서 라는 번역 저도 괜찮을 것 같아요! 전에 margin 과 padding 관련해서 안쪽 여백, 바깥 여백 이렇게 하기로 한게 기억나서 우선 kumascript/macro 상에는 안내서로 번역해뒀습니다. 

Microsoft에서는 어떻게 번역했나 확인해봤습니다. 
|단어|번역|예제|
|----|----|---|
|guide|가이드|[예제1](https://learn.microsoft.com/ko-kr/dotnet/csharp/programming-guide/arrays/jagged-arrays), [예제2](https://learn.microsoft.com/ko-kr/dynamics365/fasttrack/implementation-guide/overview)|
|guideline|지침|[예제1](https://learn.microsoft.com/ko-kr/dotnet/standard/design-guidelines/naming-guidelines), [예제2](https://learn.microsoft.com/ko-kr/gaming/accessibility/guidelines)|
|instruction|지침|[예제1](https://learn.microsoft.com/ko-kr/windows-hardware/drivers/debugger/x64-instructions), [예제2](https://learn.microsoft.com/ko-kr/windows-hardware/drivers/debugger/assembling-and-disassembling-instructions)|
|directives|지시문|[예제1](https://learn.microsoft.com/ko-kr/dotnet/csharp/language-reference/preprocessor-directives), [예제2](https://learn.microsoft.com/ko-kr/cpp/preprocessor/preprocessor-directives?view=msvc-170)

이렇게 번역하네요! 

@pje1740 님의 의견과 마소의 번역을 반영해서 이렇게 어떨까요?

`Guide`: 안내서
`Guideline`: 지침
`Instruction`: 안내
`Directives`: 지시문

**Comment by logic-finder** [comment]
안녕하십니까? 만약 실례가 되지 않는다면 지금 문제가 되고 있는 용어 통일/번역에 대한 제 생각을 조금 말씀드리고 싶습니다 (카카오톡 채팅방의 메시지를 보았습니다).

우선, 지금 제가 이렇게 문장을 쓰면 여러분께서 제가 무슨 생각을 했는지 이해하실 수 있는 이유는 단어와 문법이 어떤 개념에 대한 약속된 정의를 가지고 있기 때문이라고 생각합니다. 한편, 제 생각에 번역을 한다는 것은 한 언어로 표현되어 있는 의미를 다른 언어로 옮기는 것이라고 생각합니다. 그러나 문제는 언어가 1:1 대응이 되지 않기 때문에 같은 것을 두고 번역해도 번역하는 사람에 따라서 결과가 다를 수 있고 바로 이것이 현재 제기되는 문제의 원인이라고 생각합니다.

이런 측면에서 보았을 때 현재 용어 지침에서 기술적인 용어들에 대한 번역 규칙을 만들어 놓은 것은 합리적이라고 생각합니다. 왜냐하면, 예를 들어, 클래스에서의 method라는 용어를 글자 그대로 방법이라고 번역한다면 읽는 사람 입장에서는 그 의미를 파악하지 못해 당혹스러울 것이기 때문입니다. 그러므로 "method를 어떻게 번역해야 할 것인가"라는 문제에 대해서는, 번역의 목적이 정보의 전달이고 또 그러기 위한 유일한 방법은 모두가 사용하는 용어를 사용하는 것 뿐일테니까, 당연히 메서드는 메서드라고 불러야 한다고 생각하며 현재 지침상에도 메서드에 대한 번역이 이와 동일하게 제시되고 있습니다.

그러나 저는 그렇다고 해서 일반적인 용어들에 대한 번역 지침을 만들 필요는, 앞서 이에 대한 토의를 하신 것을 고려하면 대단히 실례지만, 없다고 생각합니다. 이것은 왜냐하면 두 가지 이유 때문입니다. 첫째로, 번역하고자 하는 단어가 일반적인 용어들인만큼 맥락상, 혹은 저자의 의도상 어떻게 쓰일지를 알 수가 없는데 이를 하나의 의미로 고정시키는 것은 제가 앞서 말씀드린 저희가 하고자 하는 번역의 목적에 부합하지 않을 것이라고 생각합니다. 둘째로, 이런 일상적인 단어 하나까지 신경써야만 한다면 번역하시는 분께서나 해당 번역을 검수하시는 분께서나 정신적으로 부담이 클 것이라고 생각합니다. 앞서 언급된 용어 중에 이런 일반적인 용어는 instruction이라고 생각합니다만 저는 상기한 논리대로 instruction은 문맥에 맞춰 번역해야 한다고 생각합니다. 왜냐하면, 라면을 끓이는 방법도 instruction이라고 할 수 있을테고 사전의 정의에 따르면 컴퓨터가 수행해야 할 명령도 instruction이라고 부르기 때문입니다.

한편, guide나 prerequisite같은 단어들은 문단의 제목(header)이나 형식적인 위치에서 공통적으로 등장하는 단어들이기 때문에 이러한 단어들의 경우 별도로 취급할 수 있다고 생각합니다. 예를 들자면 정돈되거나 전문적인 느낌을 주기 위해 해당 단어들의 번역을 통일하는 것이 있겠습니다. 만약 이런 경우라면 프로그래밍적으로 처리하는 게 효율적일 수 있겠다는 생각이 듭니다.

이상입니다. 감사합니다.

**Comment by hochan222** [comment]
@logic-finder 님 의견주셔서 감사합니다. logic-finder 님 말씀대로 현재 이슈 내에서는 [Section Title](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-title), [Section Subtitle](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#section-subtitle) 범위 안으로 한정시키는것이 좋아 보입니다.

다만, Instruction의 경우 `## Installation instructions`나 `### Processing instructions`와 같이 section-subtitle에서 사용되고 있어서 같이 정하는 것이 좋아보입니다.

> 상기한 논리대로 instruction은 문맥에 맞춰 번역해야 한다고 생각합니다.

의견에 동의합니다. 제목이나 안내문구를 제외한 용어 지침에 대해서는 다른 번역이 더 자연스럽다면 리뷰시 강제하고 있지 않습니다. 제목이나 안내문구를 제외한 용어 지침은 모두 기술 용어에 해당합니다. 따라서, **[용어 지침](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/glossary-guide.md#%EC%9A%A9%EC%96%B4-%EC%A7%80%EC%B9%A8)의 어느 범주에도 들지 못하는 일반적인 단어에 대해서는 지침을 정의하지 않는것이 좋다고 생각합니다.**

**한가지 예외 상황은** 용어 지침에 정의하기전 많은 mdn 문서에서 method는 "메서드"와 "메소드"가 혼용되어 사용되고 있었습니다. method는 일반적인 단어 범주에는 속하지 않지만 이와 같이 표기나 오해의 소지가 있을 법한 용어들은 일반적인 용이여도 지침에 추가해도 괜찮다고 생각합니다.

--- 

아래 용어들은 제목에서 사용되는 경우로 한정합니다.

### Directives

Directives는 보통 아래와 같은 경우에서 많이 사용됩니다. 

```
// mdn 문서
## Directives

- `<auth-scheme>`

// RFC 7234 문서
cache directives (e.g. Cache-Control: no-store).
```

따라서 **지시어**가 적합하다고 생각합니다.

### Instruction

Instruction는 보통 아래와 같이 다른 단어에 대한 **지침**의 의미로 많이 사용됩니다.

```
## Installation instructions
### Processing instructions
```

### Guide

현재 MDN content repo에서 제목들에 대해 더 좋은 내용 전달을 위해 변경하자는 토론이 있습니다. Guides와 같이 단독으로 쓰이지 않고 다른 단어와 같이 제목에서 사용되는 guideline 의 경우는 제목이 사라질 수도 있으므로 아직까지는 Guides를 정의하는것 만으로도 충분히 guideline의 번역을 참고할 수 있기에 조금 더 먼 미래에 정의하는 것이 좋아보입니다.

```
## Guides
```

**안내서**가 좋아보입니다.

> [국립국어원](https://www.korean.go.kr/front/imprv/stndrdView.do?mn_id=159&imprv_stndrd_seq=24)에 따르면 guide를 가이드로 표준화해서 사용이 가능하니

@coding-Alice 님, `표준화 대상어(가이드)`를 `표준화 용어(안내서)`로 표준화해야한다고 이해했는데,  혹시 제가 잘못 이해한 부분이 있을까요? 

---

## 요약

- Directives: 지시어 / 지시문
- Instruction: 지침
- Guide: 안내서

의견 부탁드립니다. 큰 의견 없으시면 빠른 의사결정을 위해 이모지 남겨주세요!

**Comment by coding-Alice** [comment]
아 가이드도 좋구, 안내서도 좋습니다! 가이드를 사용하면 안될 이유가 없습니다! `튜토리얼` 같은 경우 `자습서`로 번역을 하고 있어서, `가이드`도 비슷하게 `안내서`로 가도 좋을 것 같다는 의견입니다!

**Comment by hochan222** [comment]
@coding-Alice 님, 늦게 답변드려서 죄송합니다! 국립국어원에서 가이드 사용은 지양하고있다는 의미였습니다. 제가 혼동이되게 의견을 전달드렸네요!

넵넵!! 모두 반영해서 PR 생성했습니다. 모두 의견주셔서 감사합니다. 좋은 하루 보내세요 :)
