### ISSUE TITLE
Issue with "Set": Japanese translation follows the original

### ISSUE THREAD

**Issue by sajikix** [mdn/translated-content#11107]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set

### What specific section or headline is this issue about?

Set

### What information was incorrect, unhelpful, or incomplete?

[Set](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set) 配下のページの以下の部分について英語版と日本語版で乖離が見られました。
- [トップページ](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set) : 「解説」と「値の等価性」の項の説明が追記・変更されている
- [`Set.prototype[@@iterator]()`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set/@@iterator)  : 最初の説明部分が追記されている。またexample2つが逆順になっており、それぞれに説明も追加されている
- [`get Set[@@species]`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set/@@species) : 章立てが変わっており(Syntax などの追加)、例の説明も増えている
- [`Set.prototype.add()`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set/add) : 最初の説明部分に追記がある
- [`Set.prototype.delete()`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set/delete) : 例の説明部分に追記がある
- [`Set.prototype.has()`](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set/has) :「返値」のメモ部分が不要になっている(トップページにアルゴリズムに関する記述が追加されたため？)
- [`Set.prototype.keys()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/keys) : 日本語版のページが無い

説明の追記など理解向上につながる部分が多いと思うので日本語版を原文に追従させる形で翻訳させていただきたいです。

### What did you expect to see?

日本語版が原文に追従した形で翻訳されている。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/javascript/reference/global_objects/set`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Set
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/javascript/reference/global_objects/set/index.md
* Last commit: https://github.com/mdn/translated-content/commit/da0f483eb3deea46c4397a0748cdc84f8c18e060
* Document last modified: 2022-09-23T12:30:47.000Z

</details>

**Comment by mfuji09** [comment]
@sajikix さん
ご自身で翻訳されますか？

**Comment by sajikix** [comment]
はい！可能であれば自分で翻訳させていただきたいです！(今PRの準備をしているところです)

**Comment by mfuji09** [comment]
よろしくお願いします。担当者として割り当てておきます。
なお、PRは日本語で結構です（日本語版へのPRは、日本人しか見ません）。
