### ISSUE TITLE
document out-of-date: Fetching_data

### ISSUE THREAD

**Issue by Long-louis** [mdn/translated-content#11117]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data

### What specific section or headline is this issue about?

XMLHttpRequest

### What information was incorrect, unhelpful, or incomplete?

为例子做些准备，将 [ajax-start.html](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/ajax-start.html) 和四个文本文件 — [verse1.txt](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/verse1.txt), [verse2.txt](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/verse2.txt), [verse3.txt](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/verse3.txt), [verse4.txt](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/verse4.txt) — 复制到你计算机上的一个新目录。在这个例子中，我们将通过 XHR 在下拉菜单中选择一首诗（您可能会认识 — "如果谷歌翻译可以翻译的话"）加载另一首诗。**ajax-start.html链接报错page not found**
![image](https://user-images.githubusercontent.com/41790869/212844747-7bca84c6-2035-4ed0-9f00-e700178768ca.png)

### What did you expect to see?

Update this document (sync with the english document)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/client-side_web_apis/fetching_data`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/client-side_web_apis/fetching_data/index.md
* Last commit: https://github.com/mdn/translated-content/commit/050ba20cb04305b4c7b1fe299f85454ca7c6a249
* Document last modified: 2023-01-01T01:30:06.000Z

</details>

**Comment by yin1999** [comment]
Thanks for raising this @Long-louis. This document is out-of-date and we need a **full** sync with the reflecting english document. This issue could be resolved with #11118 (I'm going to closing that one).
