### ISSUE TITLE
Translate Learn/Accessibility/HTML/index.md in l10n-ko

### ISSUE THREAD

**Issue by youthfulhps** [mdn/translated-content#11119]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML

### What specific section or headline is this issue about?

HTML: A good basis for accessibility

### What information was incorrect, unhelpful, or incomplete?

'HTML: A good basis for accessibility' page is not translated enough

### What did you expect to see?

translate 'HTML: A good basis for accessibility' page in ko

**Comment by se030** [comment]
@youthfulhps 안녕하세요. 해당 이슈 제가 작업하고 싶은데 혹시 괜찮을까요?
번역 초안을 만들어둔 상태인데 살펴보니 이슈가 만들어져있어 코멘트 남깁니다.

**Comment by youthfulhps** [comment]
@se030 안녕하세요, 먼저 이슈를 선점하고 작업이 늦어진 점 죄송합니다. 이슈 담당해주셔도 좋습니다 감사합니다!

**Comment by se030** [comment]
@youthfulhps 아니에요. 양해해주셔서 감사합니다. 좋은 주말 보내세요!
