### ISSUE TITLE
 xhr-basic.html找不到页面1

### ISSUE THREAD

**Issue by Long-louis** [mdn/translated-content#11118]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data

### What specific section or headline is this issue about?

Fetch

### What information was incorrect, unhelpful, or incomplete?

复制您之前完成的示例目录。(如果您没有通过以前的练习，创建一个新的目录。, 然后复制 [xhr-basic.html](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/xhr-basic.html)和这四个文件 — [verse1.txt](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/verse1.txt), [verse2.txt](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/verse2.txt), [verse3.txt](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/verse3.txt), and [verse4.txt](https://github.com/mdn/learning-area/blob/master/javascript/apis/fetching-data/verse4.txt).)

![image](https://user-images.githubusercontent.com/41790869/212846361-cf99b046-6bad-4ad0-89e7-8e77d34e3eda.png)

### What did you expect to see?

page not found

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/client-side_web_apis/fetching_data`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/client-side_web_apis/fetching_data/index.md
* Last commit: https://github.com/mdn/translated-content/commit/050ba20cb04305b4c7b1fe299f85454ca7c6a249
* Document last modified: 2023-01-01T01:30:06.000Z

</details>

**Comment by yin1999** [comment]
As a part of #11117, closing this one.
