### ISSUE TITLE
window.navigator

### ISSUE THREAD

**Issue by Waldemar-00** [mdn/translated-content#11175]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/API/Window/navigator

### What specific section or headline is this issue about?

Примеры

### What information was incorrect, unhelpful, or incomplete?

navigator.userAgent.indexOf("Safari") > -1 это условие вернет true  в следующих браузерах: EDGE, CHROME, SAFSRI.
Таким образом код указанный на странице нельзя считать рабочим примером, так как условие выполнится не только в браузере SAFARI, следовательно весь смысл цепочки условий логически ложный.

### What did you expect to see?

Ожидал увидеть способ получения среды запуска.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/ru/docs/Web/API/Window/navigator

### Do you have anything more you want to share?

![Снимок экрана (19)](https://user-images.githubusercontent.com/83595316/213782590-1b96a414-d66b-4b1c-8b48-d01b76def694.png)
![Снимок экрана (20)](https://user-images.githubusercontent.com/83595316/213782767-fca88528-9746-4453-a179-72e2fe978398.png)
![Снимок экрана (21)](https://user-images.githubusercontent.com/83595316/213782917-2404a992-61a0-4d8b-9c8b-e14c65e235b0.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/api/window/navigator`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Window/navigator
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/window/navigator/index.md
* Last commit: https://github.com/mdn/translated-content/commit/23cc4fed3b27b439555e5091e1c4ab02fcad72cc
* Document last modified: 2022-11-07T14:28:57.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17374 :ok_hand: 

Thank you! :+1:
