### ISSUE TITLE
スロットの幅の値として絶対幅（px）が許容されないように読める

### ISSUE THREAD

**Issue by kawaken** [mdn/translated-content#11209]
### MDN URL

https://developer.mozilla.org/ja/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

### What specific section or headline is this issue about?

解像度の切り替え: 様々な寸法

### What information was incorrect, unhelpful, or incomplete?

「解像度の切り替え: 様々な寸法」のスロット幅に関するメモ欄にて

> メモ: スロットの幅は、絶対幅（例: 480px）ではなく、ビューポートからの相対幅（例: 50vw）を提供してください - ただし、パーセントは指定できません。

と翻訳されており `px` ではなく `vw` を指定することが強制されるように読めます。
英語の方では以下のようになっており、`px` も使用できるし `vw` も使用できるといったニュアンスかと思います。

> Note: For the slot width, rather than providing an absolute width (for example, 480px), you can alternatively provide a width relative to the viewport (for example, 50vw) — but not a percentage.

実際にサンプルコードでも `px` を使用しておりサンプルコードと説明に食い違いがあるように感じます。

### What did you expect to see?

英語の方と同じように `px` の使用も許されていることがわかる記述が良いと思います。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/ja/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/learn/html/multimedia_and_embedding/responsive_images/index.md
* Last commit: https://github.com/mdn/translated-content/commit/03a672ec9277f5122f5698444a5fba316b4f6da8
* Document last modified: 2022-10-03T15:10:24.000Z

</details>

**Comment by mfuji09** [comment]
@kawaken さん
ご自身で対応されますか？

**Comment by kawaken** [comment]
@mfuji09 さん、回答ありがとうございます。
翻訳を考えてPRを出したら良いでしょうか？

**Comment by mfuji09** [comment]
はい、PRを出していただければと思います。
PRは日本語で結構です。PRの本文に `Fixes #12209` と入れると、承認後に自動的にクローズします。
