### ISSUE TITLE
Mistake in post about Django sessions

### ISSUE THREAD

**Issue by ilnarkhasanov** [mdn/translated-content#11249]
# Request type

- [x] Correction or update

# Details

![image](https://user-images.githubusercontent.com/37439026/213851713-5d8a6415-ca3f-4713-abff-1d62416bcb66.png)
In Russian it should be: **сайт, который**.

**Comment by bsmth** [comment]
Hi @ilnarkhasanov, I think this is the right place to raise the issue, someone needs to verify the details :)
