### ISSUE TITLE
Translate Classes_in_javascript [ES]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#11258]
- [ ] Traducir/actualizar documento 

https://developer.mozilla.org/es/docs/learn/javascript/objects/classes_in_javascript

**Comment by adairo** [comment]
Hola, me encantaría trabajar en esta tarea. En el issue #9638 se menciona que de preferencia se debería actualizar este documento a la par de traducirlo. ¿Con actualizarlo se refieren a sustituir contenido que podría estar obsoleto, por ejemplo, cambiar el uso de variables declaradas con "var" por "const"? Muchas gracias.

**Comment by Graywolf9** [comment]
Muchas gracias por el interés @adairo !

Si te es posible actualizar todo el documento estaría increíble, se considera un documento actualizado cuando esta a la par de la versión en inglés, para eso puedes hacerlo de la forma que se te haga más sencillo, para artículos muy desactualizados solemos recomendar tomar el [código fuente](https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/objects/classes_in_javascript/index.md?plain=1) del [articulo en inglés](https://developer.mozilla.org/en-US/docs/learn/javascript/objects/classes_in_javascript) y ahí traducir los textos.

Cualquier duda puedes hacernosla saber en [matrix](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org) o [telegram](https://t.me/+Dr6qKQCAepw4MjFj)

Saludos.

**Comment by adairo** [comment]
Muchas gracias @Graywolf9, estaré trabajando en ello, me encargaré de dejarlo completamente actualizado 👍 

Saludos.
