### ISSUE TITLE
add `es` translation of `Community/Contributing/Translated_content`

### ISSUE THREAD

**Issue by EnriqueSource** [mdn/translated-content#11265]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Translated_content

### What specific section or headline is this issue about?

page Not found 

### What information was incorrect, unhelpful, or incomplete?

entire page

### What did you expect to see?

`es` translation of https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Translated_content

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/es/docs/MDN/Community/Contributing/Translated_content

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/contributing/translated_content`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Translated_content
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/community/contributing/translated_content/index.md
* Last commit: https://github.com/mdn/content/commit/4d06fc1379fdb3d032b02e6dcc6e7e7fab72954e
* Document last modified: 2023-01-05T20:15:41.000Z

</details>

**Comment by bsmth** [comment]
Hi @EnriqueSource, thanks for opening the issue. I think this is the right place for it. 

Am I right in that you expect the "translated content" page to be available in the languages we are doing translations for?

**Comment by EnriqueSource** [comment]
Hi @bsmth . Thank you very much for your response. Correct. I hope that page is also available in Spanish language. That's why I think it should be labeled as l10n-es. Maybe I should have labeled it myself when creating the issue, is that right?

**Comment by EnriqueSource** [comment]
Thank you very much @yin1999 for placing the correct label. Best regards.

**Comment by EnriqueSource** [comment]
Me gustaría solucionar este issue. ¿Se me asigna?

**Comment by bsmth** [comment]
Hi @EnriqueSource, have you gotten in touch with anyone on Matrix about this: https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Translated_content#spanish_es

Someone should be able to help out there!

**Comment by Graywolf9** [comment]
Thank you so much for your interests! @EnriqueSource I already assigned to you!

**Comment by EnriqueSource** [comment]
Hello @bsmth . Already assigned. Said and done. Thank you for your interest

**Comment by EnriqueSource** [comment]
Thanks @Graywolf9

**Comment by Graywolf9** [comment]
Done in #11353

**Comment by Graywolf9** [comment]
Done in #11353
