### ISSUE TITLE
javascript的正则表达式替换中的$&不是字串，而整个被查找字符串

### ISSUE THREAD

**Issue by weitaifu** [mdn/translated-content#11387]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/replace

### 哪些信息是错误、无用或不完善的？

原文提到“$&	插入匹配的子串。”。但是我刚刚在edge浏览器控制台里试了好几次，都不是子串，而是整个被查找的字符串，即查找范围。
如：
let hd = '123后盾duome';
undefined
console.log(hd.replace(/后盾/,'$&'));
VM173:1 123后盾duome
undefined
console.log(hd.replace(/后盾/,"$`$&$'"));
VM210:1 123123后盾duomeduome
undefined

### 你期望看到什么？

如果“$&”表示子串，在上文中它就只能表示“后盾”两个字。所以，我认为原文描述不够准确。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/string/replace`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/replace
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/string/replace/index.md
* Last commit: https://github.com/mdn/translated-content/commit/be834e12c589b04c7fe09075802503030642033f
* Document last modified: 2022-11-01T02:12:33.000Z

</details>

**Comment by yin1999** [comment]
原文的描述是正确的，这里的“子串”指的是正则表达式所表示的两个字，而且你说的：

> 如果“$&”表示子串，在上文中它就只能表示“后盾”两个字

的确，它只表示“后盾”两个字，考虑以下示例

```js
const str = '123你好';
console.log(str.replace(/\d+/, 'w$&w')); // w123w你好
```

会输出“w123w你好”，在这里，是不是把子串 `123` 替换为了 `'w' + 子串 + 'w'` 的形式。只是因为你使用“后盾”替换了原来的“后盾“。

注意一点，replace是一个替换匹配的内容的方法，它并不会删去不匹配的内容：

```js
'123'.replace('1', '') // 23，并不会出书空字符串 ""
```

上面只是将纯文本的替换方法改为了正则匹配而已。

你所给出的第二个示例也是类似的，请再理解一下。

如有任何问题，欢迎继续提问

**Comment by weitaifu** [comment]
谢谢老师的指教。没有想到我第一次在GitHub发言，就得到了这么快的回复。在GitHub公开致谢，目前我还不会操作。所以，只能这样回复您了。抱歉。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年2月4日 14:11
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [mdn/translated-content] javascript的正则表达式替换中的$&不是字串，而整个被查找字符串 (Issue #11387)


原文的描述是正确的，这里的“子串”指的是正则表达式所表示的两个字，而且你说的：

如果“$&”表示子串，在上文中它就只能表示“后盾”两个字

的确，它只表示“后盾”两个字，考虑以下示例

const str = '123你好';

console.log(str.replace(/\d+/, 'w$&w')); // w123w你好

会输出“w123w你好”，在这里，是不是把子串 123 替换为了 'w' + 子串 + 'w' 的形式。只是因为你使用“后盾”替换了原来的“后盾“。

注意一点，replace是一个替换匹配的内容的方法，它并不会删去不匹配的内容：

'123'.replace('1', '') // 23，并不会出书空字符串 ""

上面只是将纯文本的替换方法改为了正则匹配而已。

你所给出的第二个示例也是类似的，请再理解一下。

如有任何问题，欢迎继续提问

―
