### ISSUE TITLE
Grid Tracks 翻译修改申请

### ISSUE THREAD

**Issue by Ucely** [mdn/translated-content#11396]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/CSS_layout/Grids

### 与此议题相关的小节或标题？

网格布局

### 哪些信息是错误、无用或不完善的？

Grid Tracks 翻译在本文中不恰当，依据[术语表](https://developer.mozilla.org/zh-CN/docs/Glossary/Grid_Tracks) ，应该翻译成 网格轨道。我申请修改这篇文档。

### 你期望看到什么？

网格轨道

### 你有什么支持的链接、参考或引用？

<https://developer.mozilla.org/zh-CN/docs/Glossary/Grid_Tracks>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/css/css_layout/grids`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/CSS/CSS_layout/Grids
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/css/css_layout/grids/index.md
* Last commit: https://github.com/mdn/translated-content/commit/816b739553db0f6869983930b56614bd5b3f2021
* Document last modified: 2022-12-01T01:59:10.000Z

</details>

**Comment by yin1999** [comment]
同意，若有时间，请点击页面底部的 “Edit the page [on GitHub](https://github.com/mdn/translated-content/edit/main/files/zh-cn/learn/css/css_layout/grids/index.md)” 直接对文档进行修改。

![image](https://user-images.githubusercontent.com/15844309/216771086-c21ef720-a018-4e3e-872f-7b4cd1989256.png)

**Comment by Ucely** [comment]
嗯嗯好的，我会尽快修改😬
