### ISSUE TITLE
An anchor link not work well

### ISSUE THREAD

**Issue by kissjanna** [mdn/translated-content#11434]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener#%E4%BD%BF%E7%94%A8_passive_%E6%94%B9%E5%96%84%E7%9A%84%E6%BB%9A%E5%B1%8F%E6%80%A7%E8%83%BD

### What information was incorrect, unhelpful, or incomplete?

when I first time open this page, it doesn't jumped to the #使用_passive_改善的滚屏性能 area. I have tried it for several times with open a new chrome tab to open it, not jumped correctly.

### What did you expect to see?

when open the url, jumped into the right area

**Comment by yin1999** [comment]
Hi @kissjanna, could you provide the original document that contains the link `https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener#%E4%BD%BF%E7%94%A8_passive_%E6%94%B9%E5%96%84%E7%9A%84%E6%BB%9A%E5%B1%8F%E6%80%A7%E8%83%BD`. As we have removed the section `使用_passive_改善的滚屏性能`, so we sould fix the link in the original document.

**Comment by kissjanna** [comment]
` the original document ` maybe you mean this link (English doc) `https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#improving_scrolling_performance_with_passive_listeners`

English doc behaves the same with Chinese doc.

1.open this link `https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener`
2.ctrl + f → and then find `passive` → click `Improving scrolling performance with passive listeners`
![image](https://user-images.githubusercontent.com/63863023/217167020-cff3982d-aa61-4218-a0ac-abeda32a3634.png)
until now, it's works well.
3. copy the link now in chrome. (my problem is happend in chrome 109.0.5414.74).
4. open a new chrome tab and paste the link in step 3, click enter
5. then you can find the document is in the top, but not in the `#improving_scrolling_performance_with_passive_listeners` place.

**Comment by yin1999** [comment]
Hi @kissjanna, I mean the document which has contains the link to `https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener#%E4%BD%BF%E7%94%A8_passive_%E6%94%B9%E5%96%84%E7%9A%84%E6%BB%9A%E5%B1%8F%E6%80%A7%E8%83%BD`. I just could not find anyone

**Comment by kissjanna** [comment]
if you couldn‘t open the decoded chinese link, see the english link is also ok

**Comment by kissjanna** [comment]
Hi, @yin1999  ,`I just could not find anyone`  means `you couldn't open this link` or `you didn't find the problem in this link's page` ?

**Comment by yin1999** [comment]
> Hi, @yin1999 ,`I just could not find anyone` means `you couldn't open this link` or `you didn't find the problem in this link's page` ?

你是从哪个网页找到这个链接（`https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener#%E4%BD%BF%E7%94%A8_passive_%E6%94%B9%E5%96%84%E7%9A%84%E6%BB%9A%E5%B1%8F%E6%80%A7%E8%83%BD`）的。我们已从MDN文档中删除了这个小节，所以你没法通过上面的链接跳转到指定的小节，而且我在MDN的中文文档中没有找到这个链接，如果上面的链接的确来自MDN，那么请提供包含这个链接的页面。

**Comment by kissjanna** [comment]
oh! It's here in vue3 doc:
![image](https://user-images.githubusercontent.com/63863023/217184027-bf87fc5a-3679-4d37-9c68-b23a30c7ad57.png)

Chinese:
https://cn.vuejs.org/guide/essentials/event-handling.html#event-modifiers

English:
https://vuejs.org//guide/essentials/event-handling.html#event-modifiers

Can @vue3 doc here in github?

**Comment by kissjanna** [comment]
https://github.com/mdn/translated-content/issues/11434

**Comment by kissjanna** [comment]
@yin1999 Thanks for your patience

Orz

**Comment by yin1999** [comment]
> [vuejs/docs#2217](https://github.com/vuejs/docs/issues/2217)

Try to fix this in vuejs-translations/docs-zh-cn#650.
