### ISSUE TITLE
proposal: add translation to translation-guide for zh-CN

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#11456]
We have two common use items that are not listed in [common heading](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E5%B8%B8%E7%94%A8%E6%A0%87%E9%A2%98)s:

- Accessibility concerns
- Technical summary

I'd like to add them in this table, but before doing this. Let's discuess about the translation of them.

My proposal:

| English | translation |
| --- | --- |
| Accessibility concerns | 无障碍考虑 |
| Technical summary | 技术概要 |

Example document: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/hgroup

**Comment by awxiaoxian2020** [comment]
技术概要的翻译我觉得可以。

关于 `Accessibility concerns` ，从用语习惯上来说，其中的 `concerns` 建议翻译成更常见的名词用语。即“无障碍问题”“无障碍相关问题”等等。而且“考量”一词有时我觉得不合语境，比如例子当中的 `<hgroup>` ，原文更倾向这个元素没有什么特别针对无障碍的设计，也没有指出相关讨论或其合理性。我个人认为更像是 ”issue” 和 “problem” 之间的程度。

当然，如果有相关的先例可以参考就更好了。

**Comment by yin1999** [comment]
> 当然，如果有相关的先例可以参考就更好了。

see: https://github.com/search?q=repo%3Amdn%2Fcontent+%22Accessibility+concerns%22&type=code

**Comment by jasonren0403** [comment]
Technical summary主要出自于HTML元素的参考文档中，用于该元素内容分类、允许的内容等特性的总结，翻译成“技术概要”没啥问题。

**Comment by fwqaaq** [comment]
> 关于 `Accessibility concerns` ，从用语习惯上来说，其中的 `concerns` 建议翻译成更常见的名词用语。即“无障碍问题”“无障碍相关问题”等等。而且“考量”一词有时我觉得不合语境，比如例子当中的 `<hgroup>` ，原文更倾向这个元素没有什么特别针对无障碍的设计，也没有指出相关讨论或其合理性。我个人认为更像是 ”issue” 和 “problem” 之间的程度。

https://en.wikipedia.org/w/index.php?title=Concern_(computer_science). wiki 中有对它的单独解释，我觉得名词可能更好一点

**Comment by awxiaoxian2020** [comment]
我的意思是，是否表现出“担忧”“考量”等确切的语义结合上下文来看并不是十分重要的，所以我更倾向于用一个常见词汇代替，以增加可读性。

但是据@fwqaaq wiki 单独列出 `concern`，还是另翻吧。
如果没有找到之前翻译的先例，那我选择暂时不发表相关意见。暂时就翻译成“考量”也行。

**Comment by awxiaoxian2020** [comment]
> > 关于 `Accessibility concerns` ，从用语习惯上来说，其中的 `concerns` 建议翻译成更常见的名词用语。即“无障碍问题”“无障碍相关问题”等等。而且“考量”一词有时我觉得不合语境，比如例子当中的 `<hgroup>` ，原文更倾向这个元素没有什么特别针对无障碍的设计，也没有指出相关讨论或其合理性。我个人认为更像是 ”issue” 和 “problem” 之间的程度。
> 
> * https://en.wikipedia.org/w/index.php?title=Concern_(computer_science)
> * https://en.wikipedia.org/wiki/HCalendar#Accessibility_concerns
> * wiki 中有对它的单独解释，我觉得名词可能更好一点，而且下文的语义是对该元素行为的担忧

你的意思是？考量也可作名词

**Comment by jasonren0403** [comment]
这两段在我更新 `input type` 的时候碰到过，当时在还没有讨论的时候我是分别处理成了“无障碍考虑”和“技术总结”的（[比如这页](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input)），可供参考？

**Comment by awxiaoxian2020** [comment]
Google 的[搜索结果](https://www.google.com/search?q=Accessibility+concerns)显示，直接等价为 issue 了

**Comment by fwqaaq** [comment]
> > > 关于 `Accessibility concerns` ，从用语习惯上来说，其中的 `concerns` 建议翻译成更常见的名词用语。即“无障碍问题”“无障碍相关问题”等等。而且“考量”一词有时我觉得不合语境，比如例子当中的 `<hgroup>` ，原文更倾向这个元素没有什么特别针对无障碍的设计，也没有指出相关讨论或其合理性。我个人认为更像是 ”issue” 和 “problem” 之间的程度。
> > 
> > 
> > 
> > * https://en.wikipedia.org/w/index.php?title=Concern_(computer_science)
> > * https://en.wikipedia.org/wiki/HCalendar#Accessibility_concerns
> > * wiki 中有对它的单独解释，我觉得名词可能更好一点，而且下文的语义是对该元素行为的担忧
> 
> 你的意思是？考量也可作名词

我的意思是应该是一个名词，但是没想到更好的

> Google 的[搜索结果](https://www.google.com/search?q=Accessibility+concerns)显示，直接等价为 issue 了

issue 的意思是对话题有争论，这里应该是「关注点」、「考虑」... 之类

**Comment by awxiaoxian2020** [comment]
我还是觉得我的翻译“无障碍相关问题”较好，因为将其所想表达的关联和一点点偏负态度都表达出来了。

**Comment by yin1999** [comment]
在之前的mdn简体中文文档翻译中，我们常用的翻译有

- 无障碍考虑 https://github.com/mdn/translated-content/search?q=%E6%97%A0%E9%9A%9C%E7%A2%8D%E8%80%83%E8%99%91&type=
- 无障碍问题 https://github.com/mdn/translated-content/search?q=%E6%97%A0%E9%9A%9C%E7%A2%8D%E9%97%AE%E9%A2%98&type=

使用“无障碍的相关问题”这一翻译稍微有一点长。标题应能简洁明了地表达出它的意思。

**Comment by awxiaoxian2020** [comment]
那就译为“问题”？因为没有标准译法，所以我对 `考量` `问题` 等都是可以接受的。建议将这个 issue 也放在翻译指南当中，以供链接和将来可能的讨论。

**Comment by yin1999** [comment]
考虑翻译为“无障碍考虑”，现有的翻译中，“考虑”比“考量”的翻译要多，而且此部分的内容并不完全都是将提出问题的，也有相关的建议。有任何异议吗
