### ISSUE TITLE
(ko) 'setInterval()' needs translation

### ISSUE THREAD

**Issue by yechoi42** [mdn/translated-content#11469]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/setInterval

### What specific section or headline is this issue about?

setInterval()

### What information was incorrect, unhelpful, or incomplete?

not translated in Korean

### What did you expect to see?

translated contents of setInterval()

**Comment by 1ilsang** [comment]
안녕하세요. 해당 문서 작업자 없다면 진행해서 PR 올려보겠습니다.

**Comment by yechoi42** [comment]
번역 완료.
