### ISSUE TITLE
(ko) 'grid-template-columns' needs translation

### ISSUE THREAD

**Issue by yechoi42** [mdn/translated-content#11466]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-columns

### What specific section or headline is this issue about?

grid-template-columns

### What information was incorrect, unhelpful, or incomplete?

not translated in Korean

### What did you expect to see?

translated contents of grid-template-columns

**Comment by sunhpark42** [comment]
작업하시는 분 안계시면 제가 assign 하겠습니다~
