### ISSUE TITLE
(ko) 'Memory Management' needs update

### ISSUE THREAD

**Issue by yechoi42** [mdn/translated-content#11460]
### MDN URL

https://developer.mozilla.org/ko/docs/Web/JavaScript/Memory_Management

### What specific section or headline is this issue about?

자바스크립트의 메모리 관리

### What information was incorrect, unhelpful, or incomplete?

not updated, especially below two sections
- [Configuring engine memory model](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#configuring_engine_memory_model)
- [Data structures aiding memory management](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#data_structures_aiding_memory_management)

### What did you expect to see?

translated contents of Memory Management

**Comment by kadensungbincho** [comment]
WIP

**Comment by SnowMarble** [comment]
@yechoi42 이슈 닫아주실 수 있을까요?
