### ISSUE TITLE
(ko) 'linear-gradient()' needs translation

### ISSUE THREAD

**Issue by yechoi42** [mdn/translated-content#11462]
### MDN URL

http://localhost:3000/en-US/docs/Web/CSS/gradient/linear-gradient

### What specific section or headline is this issue about?

linear-gradient()

### What information was incorrect, unhelpful, or incomplete?

not translated in Korean

### What did you expect to see?

translated contents of linear-gradient()

**Comment by dwywdo** [comment]
Let me handle this issue
