### ISSUE TITLE
(ko) 'translate()' needs translation

### ISSUE THREAD

**Issue by yechoi42** [mdn/translated-content#11470]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translate

### What specific section or headline is this issue about?

translate()

### What information was incorrect, unhelpful, or incomplete?

not translated in Korean

### What did you expect to see?

translated content of translate()

**Comment by swimjiy** [comment]
해당 작업 따로 하시는 분 없으시면 제가 해보겠습니다:)
