### ISSUE TITLE
Web API list can not be displayed except in English.

### ISSUE THREAD

**Issue by imaxue** [mdn/translated-content#11499]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API

### What information was incorrect, unhelpful, or incomplete?

{{ListGroups}} can not be displayed.

### What did you expect to see?

list of all the APIs that are available.

**Comment by yin1999** [comment]
Thanks for reporting this. I'm trying to fix this in mdn/yari#8162 as this should be a platform problem :)
