### ISSUE TITLE
Typo in URL for interactive sample on Object.seal() (fr equivalent of #106)

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#115]
Filed a separated issue to fix the interactive example link in https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Object/seal as per https://github.com/mdn/translated-content/issues/106#issuecomment-761709070

https://interactive-examples.mdn.mozilla.net/pages/js/object-prototype-seal.html is wrong

https://interactive-examples.mdn.mozilla.net/pages/js/object-seal.html is correct

**Comment by tristantheb** [comment]
PR #128 is created concerning this issue for l10n-fr ;)

**Comment by SphinxKnight** [comment]
Closing this one as #128 has been merged.
Keep an eye on [What'sDeployed](https://whatsdeployed.io/s/DLi/mdn/content) if this does not yet appear on the site.
