### ISSUE TITLE
English docs: "Experimental" icon in has title and abbreviation in French

### ISSUE THREAD

**Issue by alina-zaieva** [mdn/translated-content#11538]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/beforematch_event

### What specific section or headline is this issue about?

"Related Topics" section on the left

### What information was incorrect, unhelpful, or incomplete?

When hovering on "Experimental" icon, the tooltip is shown in French while the rest of interface is in English.

### What did you expect to see?

Text in the same language as the rest of the page 🙂

### Do you have anything more you want to share?

Snippet from page's markup:
```html
<li>
    <a href="/en-US/docs/Web/API/Window/showModalDialog">
        <code>showModalDialog()</code>
    </a>
    <abbr class="icon icon-nonstandard" title="Non-standard. Check cross-browser support before using.">
        <span class="visually-hidden">Non-standard</span>
    </abbr>
    <abbr class="icon icon-deprecated" title="Deprecated. Not for use in new websites.">
        <span class="visually-hidden">Deprecated</span>
    </abbr>
</li>
<li>
    <a href="/en-US/docs/Web/API/Window/showOpenFilePicker">
        <code>showOpenFilePicker()</code>
    </a>
    <abbr class="icon icon-experimental" title="Expérimental. Le comportement attendu pourrait évoluer à l'avenir.">
        <span class="visually-hidden">Expérimental</span>
    </abbr>
</li>
``` 
Gif of repro:
![experimental-tooltip-issue](https://user-images.githubusercontent.com/70098623/217798038-548c2531-2daa-4a61-bc7c-ef4db57023a0.gif)

**Comment by SphinxKnight** [comment]
@alina-zaieva hello, sorry for the late reply. I cannot reproduce from here 
![image](https://user-images.githubusercontent.com/2413436/231719012-3e83a4fc-8d18-44dd-a461-1e967d795e90.png)

Can you confirm?

**Comment by alina-zaieva** [comment]
Yes, I am seeing correct label too, closing this as done 🙂

**Comment by SphinxKnight** [comment]
thanks for the swift reply :)
