### ISSUE TITLE
言語が日本の時だけ、Math.atan2()ページの画像が表示されていない

### ISSUE THREAD

**Issue by y-hsgw** [mdn/translated-content#11548]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2

### この問題に関する節や見出しはどこですか。

https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Math/atan2#%E8%A7%A3%E8%AA%AC

### 不完全、不親切、不完全であった情報は何ですか。

言語が日本の時だけ、画像が表示されていない。
![スクリーンショット 2023-02-10 112045](https://user-images.githubusercontent.com/49516827/217984004-dd00315d-d85c-43ed-ab9e-8e43ccba3b7f.png)

### どう表示されるべきだと思いますか。

適切な画像が表示されるべき。

**Comment by manjuu-eater** [comment]
https://github.com/mdn/translated-content/pull/10475
に関連するものだと思います。

mdn.mozillademos.org がもう稼働してないので画像をローカルにコピーしてそれにリンクしようって話だったらしいのですが、何か問題があった？らしく、だいぶ前から画像が非表示のままです。

ポルトガル語版などでは英語版の画像に直リンク張って画像表示していますね。

**Comment by manjuu-eater** [comment]
頑張って修正しました。
（codespacesの使い方がわからなくて四苦八苦しました…）

遅くなりますが、mfuji09さんがレビューしてくれて受理されるかと思います。

**Comment by y-hsgw** [comment]
> 頑張って修正しました。 （codespacesの使い方がわからなくて四苦八苦しました…）
> 
> 遅くなりますが、mfuji09さんがレビューしてくれて受理されるかと思います。

ご対応いただきありがとうございます🙇‍♂️

**Comment by y-hsgw** [comment]
https://github.com/mdn/translated-content/pull/11559
上記PRで解消いただいたのでcloseします！ありがとうございます！
