### ISSUE TITLE
한국어 가이드 수정 제안사항

### ISSUE THREAD

**Issue by SnowMarble** [mdn/translated-content#11555]
현재 번역 지침에 [HTML 소스의 줄 바꿈](https://github.com/mdn/translated-content/blob/main/docs/ko/guides/translation-guide.md#html-%EC%86%8C%EC%8A%A4%EC%9D%98-%EC%A4%84-%EB%B0%94%EA%BF%88) 섹션이 있는데, 이제 모든 파일이 md이니 해당 가이드도 이에 맞춰 수정 혹은 삭제가 필요해 보입니다.

HTML문서 환경에서는 HTML 태그들로 인해 한 줄이 길어지면서 가독성을 위해 줄바꿈이 중간에 삽입되었던것으로 추정하는데, 지금 영어 원문을 보면 가끔씩 줄바꿈이 있는 경우도 있지만, 이는 모두 문장이 완료된 이후에 있는거라 번역에 혼란을 주진 않을거라 생각합니다.

해당 가이드를 md환경에 알맞게 수정해는것을 고려해봤으면 합니다. 오히려 md lint에 관한 짦은 내용으로 교체하는것도 나쁘지 않을것 같네요.

**Comment by hochan222** [comment]
https://github.com/mdn/translated-content/pull/11595 에서 제거되었습니다. 

감사합니다 좋은 하루 보내세요 :)

- https://github.com/mdn/translated-content/pull/11595/files#diff-d99861bb1203a94ae0cc754835514be16821831687cf5afbcdc43cc6d0d00a82
