### ISSUE TITLE
Issue with "HTMLCanvasElement.getContext()": a typo in Chinese doc

### ISSUE THREAD

**Issue by PieNam** [mdn/translated-content#1156]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLCanvasElement/getContext

#### What information was incorrect, unhelpful, or incomplete?

In the Chinese version of the document, about `contextAttributes` of `WebGL`.

'premultipliedAlpha: 表明排版引擎讲假设绘制缓冲区包含预混合alpha通道的boolean值。'

should be:

'premultipliedAlpha: 表明排版引擎【将】假设绘制缓冲区包含预混合alpha通道的boolean值。'

#### Specific section or headline?

语法 - 参数 - 上下文属性 - WebGL 上下文属性

#### What did you expect to see?

`premultipliedAlpha: 表明排版引擎将假设绘制缓冲区包含预混合alpha通道的boolean值。`

#### Did you test this? If so, how?

just a Chinese typo

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/api/htmlcanvaselement/getcontext`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLCanvasElement/getContext
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/htmlcanvaselement/getcontext/index.html
* Last commit: https://github.com/mdn/translated-content/commit/079fefb94cacbc3d34fc5fb4e274877a4339116c
* Document last modified: 2021-05-25T19:51:09.000Z

</details>

**Comment by SphinxKnight** [comment]
@sideshowbarker (+@teoli2003) even if I'm not part of the Chinese team, I'm able to transfer/help assess if transfer is needed. Don't hesitate to ping me (in the issues or on Matrix)

**Comment by sideshowbarker** [comment]
@SphinxKnight 
> @sideshowbarker (+@teoli2003) even if I'm not part of the Chinese team, I'm able to transfer/help assess if transfer is needed. Don't hesitate to ping me (in the issues or on Matrix)

Thanks much! that’s great to know
