### ISSUE TITLE
リンク切れ

### ISSUE THREAD

**Issue by Yukinyaaa** [mdn/translated-content#11575]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Numbers_and_dates

### この問題に関する節や見出しはどこですか。

数値

### 不完全、不親切、不完全であった情報は何ですか。

[64 ビット倍精度浮動小数点数のフォーマットである IEEE 754](https://ja.wikipedia.org/wiki/Double-precision_floating-point_format)のリンク切れ

### どう表示されるべきだと思いますか。

[64 ビット倍精度浮動小数点数のフォーマットである IEEE 754](https://ja.wikipedia.org/wiki/%E5%80%8D%E7%B2%BE%E5%BA%A6%E6%B5%AE%E5%8B%95%E5%B0%8F%E6%95%B0%E7%82%B9%E6%95%B0)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/javascript/guide/numbers_and_dates`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Numbers_and_dates
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/javascript/guide/numbers_and_dates/index.md
* Last commit: https://github.com/mdn/translated-content/commit/da0f483eb3deea46c4397a0748cdc84f8c18e060
* Document last modified: 2022-09-23T12:30:47.000Z

</details>

**Comment by mfuji09** [comment]
@Yukinyaaa さん
ご自分で修正されまか？
