### ISSUE TITLE
缺少翻译 Audio and video manipulation整篇文章

### ISSUE THREAD

**Issue by gxy5202** [mdn/translated-content#11573]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation#see_also

### 哪些信息是错误、无用或不完善的？

这篇文章没有中文翻译

### 你期望看到什么？

添加中文翻译，我可以翻译

**Comment by yin1999** [comment]
> 添加中文翻译，我可以翻译

若有兴趣，请翻译，我会将此议题分配给你

**Comment by gxy5202** [comment]
> > 添加中文翻译，我可以翻译
> 
> 若有兴趣，请翻译，我会将此议题分配给你

好的
