### ISSUE TITLE
Update all browser compat/spec sections

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#11594]
In many translated pages, old-style spec/compat data sections are used, from more recent formats such as calling `{{Compat}}` with an argument to as far back as wiki tables and using the `{{spec}}` macro.  We should check all of the pages for these older-style sections and replace them with a translated version of the following:

```md
### Specifications

{{Specifications}}

### Browser compatibility

{{Compat}}
```

This project involves the following tasks:
- Replace compatibility data tables (markdown and HTML) with `{{Compat}}`
- Remove arguments to `{{Compat}}` calls - #16873
- Remove arguments to `{{Specifications}}` calls - complete
- Replace sections with `{{spec}}`, `{{spec2}}` and `{{SpecName}}` with `{{Specifications}}`
- Replace any Specifications sections stating "there is no spec" or similar with `{{Specifications}}` (if the same applies upstream)
- Remove any notes regarding specific browser versions (especially of SpiderMonkey)

Locales:
- [ ] es
  - #11609
  - #11779
  - #11780
  - #11781
  - #11782
  - #11783
  - #11784
  - #11785
  - #11786
  - #11787
  - #11788
  - #16897
- [x] fr
  - #11791
  - #11793
  - #11794
  - #11795
  - #11796
  - #11797
  - #11798
  - #11799
  - #11800
- [x] ja
- [x] ko #11691
- [x] pt-BR
  - #15989
  - #15991
  - #16377
  - #16379
  - #16453
  - #16454
  - #16610
  - #16582
- [x] ru
  - #16503
  - #16504
  - #16505
  - #16674
- [x] zh-cn
- [x] zh-tw

---

Some examples of old-style compat tables and spec tables include:

```md
{{compat("api.Document.pointerLock")}}

---

| Browser           | Suporte         | Notas                                                          |
| ----------------- | --------------- | -------------------------------------------------------------- |
| Internet Explorer | 8               | (IE8) apenas selectores CSS 2.1                                |
| Firefox (Gecko)   | **3.5** (1.9.1) |                                                                |
| Opera             | 10              |                                                                |
| Chrome            | 1               |                                                                |
| Safari (webkit)   | 3.2 (525.3)     | [webk.it/16587](https://bugs.webkit.org/show_bug.cgi?id=16587) |

--- 

## Especificação

- {{spec("https://www.w3.org/TR/selectors-api/","Selectors API Level 1","rec")}}
- {{spec("https://www.w3.org/TR/selectors-api2/","Selectors API Level 2","wd")}}
- {{spec("http://dev.w3.org/2006/webapi/selectors-api2/","Selectors API Level 2","ed")}}

---

| Характеристики                                                                               | Статус                           | Комментарий           |
| -------------------------------------------------------------------------------------------- | -------------------------------- | --------------------- |
| {{SpecName("DOM WHATWG", "#interface-domtokenlist", "DOMTokenList")}} | {{Spec2("DOM WHATWG")}} | Начальное определение |
```

**Comment by Graywolf9** [comment]
`es` done in #11609 thanks to @queengooborg !

**Comment by queengooborg** [comment]
Actually no, Spanish isn't even done to being finished... 🙃 There are lots, LOTS more entries to work through, and that PR only covers a small amount!

**Comment by SnowMarble** [comment]
ko done in #11691 :)

**Comment by Graywolf9** [comment]
Thank you so much again @queengooborg ! It seems to be done now thanks to you!

**Comment by yin1999** [comment]
Already done this for l10n-zh in #5618, so removing l10n-zh label.

**Comment by yin1999** [comment]
Hey @queengooborg. I've remove all deprecated macros (related with compat/spec section) for ru. Would you like to remove all params of Specifications and Compat macros for `ru` :)

**Comment by queengooborg** [comment]
> Hey @queengooborg. I've remove all deprecated macros (related with compat/spec section) for ru. Would you like to remove all params of Specifications and Compat macros for `ru` :)

Thank you for tackling that, @yin1999!  I'd be happy to work on getting the params removed, I can write a script to scan and fix any such instances in all applicable locales!
