### ISSUE TITLE
Live sample missing in /ru/docs/Web/CSS/clip-path

### ISSUE THREAD

**Issue by Kadavrul** [mdn/translated-content#11605]
URL:https://developer.mozilla.org/ru/docs/Web/CSS/clip-path
Message:
Live sample failed!

An error occurred trying to render this live sample.
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find any live code samples for "clip-path" within /ru/docs/Web/CSS/clip-path

**Comment by myshov** [comment]
Also there is and issue with a section "Живой пример". The demo is not working properly

**Comment by leon-win** [comment]
This issue is fixed in #16931 :sunglasses:
