### ISSUE TITLE
This is a link to an unwritten page

### ISSUE THREAD

**Issue by Mor-All** [mdn/translated-content#11601]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

### О какой части статьи или абзаце идёт речь?

This is a link to an unwritten page

### Какая информация оказалась неверной, бесполезной или неполной?

См. список странностей (list of quirks) и частично стандартный режим для того, чтобы увидеть разницу между режимами.
https://developer.mozilla.org/ru/docs/Mozilla_Quirks_Mode_Behavior
https://developer.mozilla.org/ru/docs/Gecko's_%22Almost_Standards%22_Mode

### Как бы вы исправили?

Проверил доступность страниц и на всякий случай альтернативную ссылку прикрутил.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/html/quirks_mode_and_standards_mode`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/html/quirks_mode_and_standards_mode/index.md
* Last commit: https://github.com/mdn/translated-content/commit/930b27c743c2363ca6ee49c26796dfc5e8886ae7
* Document last modified: 2022-10-24T12:13:36.000Z

</details>

**Comment by myshov** [comment]
Перевод чуть разъехался с оригиналом. В оригинале больше этих страниц нет. Нам нужно будет синхронизировать перевод этой страницы

**Comment by leon-win** [comment]
Fixed in #17373 :ok_hand: 

Thank you! :+1:
