### ISSUE TITLE
Issue with "Plantillas literales (plantillas de cadenas)": There's a comment missing one argument

### ISSUE THREAD

**Issue by abelpita** [mdn/translated-content#1160]
MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Template_literals

#### What information was incorrect, unhelpful, or incomplete?
In the second code block of the "Plantillas etiquetadas" section, there is a comment that represents how a tagged template it's interpreted. In this comment, there's one argument missing:

let t1Closure = plantilla`¡${0}${1}${2}${2}${3}!`;
//let t1Closure = plantilla(["¡","","","","","","!"],0,1,2,3);
t1Closure('H', 'U', 'R', 'A');              // "¡HURRA!"

#### Specific section or headline?
https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Template_literals#plantillas_etiquetadas

#### What did you expect to see?
//let t1Closure = plantilla(["¡","","","","","","!"],0,1,2,2,3);

**Comment by SphinxKnight** [comment]
Sorry, but this locale is currently frozen and changes/fixes are not currently accepted as there is not an active team for this locale. Please see https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ and [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo.
