### ISSUE TITLE
clientHeight改为clientWidth

### ISSUE THREAD

**Issue by ascendho** [mdn/translated-content#11612]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Element/clientWidth

### 哪些信息是错误、无用或不完善的？

中文文档第二段，

> 在根元素（<html> 元素）或怪异模式下的 <body> 元素上使用 clientHeight 时，该属性将返回视口宽度（不包含任何滚动条）。[这是一个 clientWidth 的特例](https://www.w3.org/TR/2016/WD-cssom-view-1-20160317/#dom-element-clientwidth)。

这里的clientHeight应该纠正为clientWidth。

### 你期望看到什么？

纠正就好

### 你有什么支持的链接、参考或引用？

源文档:

- [English page](https://developer.mozilla.org/en-US/docs/web/api/element/clientwidth)
- [Chinese-translated page](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/clientWidth)

### 你还想补充什么内容？

暂无

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/element/clientwidth`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Element/clientWidth
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/element/clientwidth/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c40b47ae767d7f66d4ba8f2f606c7c10a8989912
* Document last modified: 2022-09-21T23:41:19.000Z

</details>

**Comment by ascendho** [comment]
已经merge了我的pr了

**Comment by cw118** [comment]
> 已经merge了我的pr了

Closing this since it was fixed in #11611. Thank you and congratulations for your first contribution here!
