### ISSUE TITLE
typo at description

### ISSUE THREAD

**Issue by Leo-SingleDay** [mdn/translated-content#11643]
### MDN URL

https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/OPTIONS

### What specific section or headline is this issue about?

typo at title

### What information was incorrect, unhelpful, or incomplete?

there's a typo at description

aterisk -> asterisk

### What did you expect to see?

there's typo at description

aterisk -> asterisk

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ko/web/http/methods/options`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/OPTIONS
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/http/methods/options/index.md
* Last commit: https://github.com/mdn/translated-content/commit/2f88ae142f57a30c74bd0783a194620e4b59e975
* Document last modified: 2023-01-07T08:09:08.000Z

</details>

**Comment by yin1999** [comment]
There is actually a star (`*`) in the first paragraph. Isn't it right?

**Comment by Leo-SingleDay** [comment]
I mean there's missing of s between a and t

so 'aterisk' should be changed as 'asterisk'

**Comment by hochan222** [comment]
@Leo-SingleDay 님 안녕하세요.

기여해주셔서 감사합니다. 좋은 하루 보내세요 :) 

@yin1999, Thanks, Have a nice day :)
