### ISSUE TITLE
Drop "in this module" from Learn for l18n pages

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/translated-content#11653]
See https://github.com/mdn/content/issues/24467.

- [x] #11674
- [x] fr #12716
- [x] #11712
- [x] ko #11694
- [x] pt-br #12199
- [ ] ru #17093
- [x] zh
  - [x] zh-tw #11675
  - [x] #11682

**Comment by hochan222** [comment]
Thanks, done for `ko`. Have a nice day :)

**Comment by yin1999** [comment]
Done for `l10n-zh`

**Comment by Graywolf9** [comment]
Done for `es`. Thank you!

**Comment by lucassarcanjo** [comment]
Done for `pt-BR`

**Comment by cw118** [comment]
Done for fr :)

**Comment by leon-win** [comment]
Should be fixed with #17093, but additional checking would not hurt)
