### ISSUE TITLE
es - Drop "in this module" from Learn for l18n pages

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#11674]
Como se menciona en el issue de `content` el apartado "in this module" (en este módulo) será eliminado de la sección "Learn". 

Para tener orden al revisar los PR serán divididos por sección:

- [x] https://github.com/mdn/translated-content/pull/11961
- [x] https://github.com/mdn/translated-content/pull/12058
- [x] https://github.com/mdn/translated-content/pull/12071
- [x] https://github.com/mdn/translated-content/pull/12092
- [x] https://github.com/mdn/translated-content/pull/12075
- [x] https://github.com/mdn/translated-content/pull/12076
- [x] [Performance — Making websites fast and responsive](https://developer.mozilla.org/es/docs/Learn/Performance)
- [x] [MathML — Writing mathematics with MathML](https://developer.mozilla.org/es/docs/Learn/MathML)
- [x] https://github.com/mdn/translated-content/pull/12077
- [x] https://github.com/mdn/translated-content/pull/12079

**Comment by Yareaj** [comment]
Estaré trabajando en este issue haciendo continuación a la pull #12073

**Comment by Yareaj** [comment]
@Graywolf9 no encuentro ninguno en Performance que cuente con la macro, no sé si la pase por alto pero agradezco puedas confirmarme si me equivoco

**Comment by Graywolf9** [comment]
Muchísimas gracias! @Yareaj con esos y [este](https://github.com/mdn/translated-content/pull/12092) PR, queda completado este issue y completamente removido "En este módulo" del contenido en Español

**Comment by Graywolf9** [comment]
Terminado
