### ISSUE TITLE
Приглашаем принять участие в проекте по переводу контента MDN / Call to action: Help us maintain MDN's Russian content

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/translated-content#117]
Нам нужна ваша помощь. Контент нескольких локалей MDN уже
разблокирован (т.е. доступен для редактирования), а его поддержкой
занимается ряд активных пользователей.

Однако есть люди из русскоязычного веб-сообщества, которые
заинтересованы в том, чтобы MDN на русском языке также продолжал
развиваться! Вместе с Алексеем Пыльцыным (@lex111) я работаю над
осуществлением этого.

## Что нужно для участия в проекте?

Мы ищем добровольцев, которые бы активно занимались контентом на
русском языке. От вас потребуется:

* Просматривать пулреквесты, связанные с [русскоязычным контентом
MDN](https://github.com/mdn/translated-content/tree/main/files/ru).
* Решать проблемы, относящиеся к русской версии сайта MDN.

Кроме этого, понадобится обновлять русский перевод в соответствии с
оригиналом на английском языке, а также переводить новые страницы
документации. Мы надеемся, что проекту вы будете уделять несколько
часов в неделю, занимаясь наиболее интересными для вас задачами.

## Как поучаствовать в проекте?

Если вы хотите помочь — отпишитесь в ишью! Также вы можете зайти в
[чат русского перевода MDN /#10n-ru](https://chat.mozilla.org/#/room/#mdn-l10n-ru:mozilla.org) на сервере
[Mozilla Matrix](https://wiki.mozilla.org/Matrix), где можно подробнее
обсудить предстоящую работу и задать вопросы.

---

This is a call for help. A number of MDN locales are already unfrozen (meaning that edits can be made), and have active communities working on maintaining them.

But there are a number of Russian community members who want to see MDN ru content unfrozen too! I'm working with Alexey Pyltsyn (@lex111) to make this happen.

## What would this involve?

We want you to join a ru-locale active maintenance volunteer team. Your responsibilities would involve:

* Doing a share of reviews on pull requests filed against the [MDN ru content](https://github.com/mdn/translated-content/tree/main/files/ru).
* Doing a share of fixing content bug issues filed against the MDN ru content.

There also may be other tasks that come up, such as keeping ru pages in sync with en-US pages when they change, and creating new ru translations if you are interested. We would expect you to devote a few hours per week to these tasks — whatever you are able to handle comfortably.

## How do I get involved?

If you want to help, write a comment in this issue thread to let us know! You can also join the [MDN Russian translation /#mdn-l10n-ru](https://chat.mozilla.org/#/room/#mdn-l10n-ru:mozilla.org) room on the [Mozilla Matrix](https://wiki.mozilla.org/Matrix) server to discuss the work more and ask questions.

**Comment by myshov** [comment]
Hi @chrisdavidmills 
My English is not perfect but I would like to join to this venture

**Comment by armanpwnz** [comment]
Hi @chrisdavidmills 
I also want to help, my English level is intermediate

**Comment by captainspring** [comment]
Hello @chrisdavidmills et al!
This is such an amazing opportunity! I’m fluent in English, I use MDN all the time, and I’d love to give back to the community. However, I’m just beginning my journey as a frontend dev, I hope that’s fine.

**Comment by chrisdavidmills** [comment]
> Hi @chrisdavidmills
> My English is not perfect but I would like to join to this venture

Hi there @myshov , thank you for your interest in helping with this! I don't think you need perfect English to do a good job here. A lot of the work will be fixing Russian language problems, or fixing problems with code examples in JavaScript, HTML, or CSS.

Do you have any questions about the tasks, and are you happy for me to add you to the Russian MDN team? We will probably start setting this all up next week, so you have some time to think about it over the weekend.

**Comment by chrisdavidmills** [comment]
> Hello @chrisdavidmills et al!
> This is such an amazing opportunity! I’m fluent in English, I use MDN all the time, and I’d love to give back to the community. However, I’m just beginning my journey as a frontend dev, I hope that’s fine.

Hi @captainspring , lovely to hear from you, and thank you for your interest!

I don't think your level of experience in front-end development will be a problem. There will still be a lot of work you can handle, and you will probably learn a lot as well.

As I said to the others, we'll be setting up the team, etc. next week, so have a think over the weekend if you have any questions or concerns. 

> **upd.** I’d love to join the chat, but when I’m trying to sign up to be able see it, the website tells me, “Unable to query for supported registration methods.”

Hrm, I don't know why this is. Did you follow the setup instructions at https://wiki.mozilla.org/Matrix? I think maybe you have to do that first before you follow the chat room link, but I'm not too sure.

**Comment by myshov** [comment]
@chrisdavidmills 

> Do you have any questions about the tasks, and are you happy for me to add you to the Russian MDN team?

I don't have any questions :) And yeah you can add me to Russian MDN team!

**Comment by armanpwnz** [comment]
@chrisdavidmills 
> Let me know next week if you are definitely interested in joining the team, and we'll get you signed up.
I don't have any questions, and I'm ready to join the team

**Comment by captainspring** [comment]
@chrisdavidmills 
Learning along the way is my general life strategy, haha. Great!

> As I said to the others, we'll be setting up the team, etc. next week, so have a think over the weekend if you have any questions or concerns.
Ok, feel free to add me to the team.

Is joining the chat essential to volunteering? If so, I’ll do my best to sort out my problem with Matrix over the weekend.

**Comment by mpstv** [comment]
Hi @chrisdavidmills

I would like to help with this work.

My English is not very good, but I saw the message above indicating that this shouldn't be a big problem. 
Hope this is the case :)

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills
> 
> > Let me know next week if you are definitely interested in joining the team, and we'll get you signed up.
> 
> I don't have any questions, and I'm ready to join the team

Great, thank you! I will sort this all out on Monday. Excited to see this coming together.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills
> 
> > Do you have any questions about the tasks, and are you happy for me to add you to the Russian MDN team?
> 
> I don't have any questions :) And yeah you can add me to Russian MDN team!

Awesome, thanks!

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills
> Learning along the way is my general life strategy, haha. Great!

"hacking things together" and "learning through necessity" are my strategies...I think we have similar approaches ;-)

> 
> > As I said to the others, we'll be setting up the team, etc. next week, so have a think over the weekend if you have any questions or concerns.
> 
> Ok, feel free to add me to the team.

Awesome, thanks!

> 
> Is joining the chat essential to volunteering? If so, I’ll do my best to sort out my problem with Matrix over the weekend.

No, I would not say it is essential. It is just useful to have a synchronous way to communicate with other team members, and ask questions. There are other rooms in the Matrix that might be useful as well.

**Comment by chrisdavidmills** [comment]
> Hi @chrisdavidmills
> 
> I would like to help with this work.
> 
> My English is not very good, but I saw the message above indicating that this shouldn't be a big problem.
> Hope this is the case :)

Hi @mpstv, and thanks a lot for your interest in helping out.

Yes, I don't think perfect English is needed to participate. There is still a lot you can do to help out.

**Comment by chrisdavidmills** [comment]
Happy Monday everyone.

I've just created a new [`yari-content-ru`](https://github.com/orgs/mdn/teams/yari-content-ru) team, and invited you all to it, and this repo. Let me know if you don't see these invites, and we'll look into them. The team will also be a good place to post team discussions.

The other two things that need to happen before we can properly get you working on MDN ru content are:

1. Add you folks to the repo README and CODEOWNERS file, so that folks know who you are, and so that you start automatically getting reviews assigned to you when people make PRs against the ru docs. See https://github.com/mdn/translated-content/pull/173
2. Activate the ru locale in the system. See https://github.com/mdn/yari/pull/3241

Once these have been done, you can get started!

Other things to do include working on issues filed about ru content, on the `content` and `translated-content` repos. I usually try to put the `l10n-ru` label on these when I see them, so they are easier to find. Also, you cna work on improving existing translations and creating new ones, as you think makes sense.

**Comment by myshov** [comment]
@chrisdavidmills thanks!
Could you give us the write access to `content` repo also?

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills thanks!
> Could you give us the write access to the `content` repo also please?

What do you think you'll need it for? Sorry to sound all suspicious, but I'm think about whether all `translated-content` reviewers might need write access to the `content` repo too. Is this basically just for admin type tasks like moving issues and closing them, or did you have something else in mind?

**Comment by myshov** [comment]
@chrisdavidmills don't apologize I fully understand you :)
I figured that there will be many cases when we will need to fix some issues (for example usage example of some API, typos etc.) just because we will be reading a lot of source materials. If we will use a collaboration model like forking with the button on the top of the page and creating fixes in our own fork in our own account and creating pull request from there, It creates a lot of friction to fix the issues in the English content (IMO of course)

**Comment by Saionaro** [comment]
@chrisdavidmills Hey! Do you have an extra space for another one volunteer? I'd like to help.

**Comment by sashasushko** [comment]
Hi @chrisdavidmills. I have some "free" time and I want to help you.

I'm author of training programs and I use MDN a lot for my work (especially articles in Russian). Sometimes Russian auto-translate is bad and I'll be glad to fix it.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills don't apologize I fully understand you :)
> My point is there will be many cases when we will need to fix some issues (for example an usage example of some API, typos etc.) just because we will be reading a lot of source materials. It will create a friction to fix the issues in the English content If we use a collaboration model like forking with the button on the top of the page and creating fixes in our own fork in our own account and creating pull request from there (IMO). But the write access is not essential of course.

I think I'd like to keep the write access separate and only for the folks reviewing, merging, etc. on the content repo. You can still make fixes there using the regular fork and PR model, just like other contributors.

The only other use I could imagine you having it for is to transfer issues about ru content over to the translated-content repo. But I tend to do that anyway whenever I see them.

**Comment by chrisdavidmills** [comment]
@Saionaro @sashasushko Hello, and thank you for your interest in helping out.

To give you an idea of what this involves, if you join the `ru` locale maintenance team, you would be added to the `yari-content-ru` GitHub team, which is included in this repo's `CODEOWNERS` file. As a result, you would get assigned to review a share of pull requests that get made against the `ru` content. You would also be expected to take on some of the issues filed agains the ru content. I expect it would take a couple of hours a week of your time.

If you want to help with this, then that's great!

If not, that is still fine, and you could still help out by submitting pull requests to improve and add translations, fix bugs, etc.

So let me know if this sounds good, and if you want to join the team as described above.

**Comment by Saionaro** [comment]
@chrisdavidmills Sounds good to me. I definitely able to find few hours a week for MDN.
Feel free to to add me to the team.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Sounds good to me. I definitely able to find few hours a week for MDN.
> Feel free to to add me to the team.

@Saionaro that's great, thanks! I've added you. You should have received an invite to the team, and to this repo.

**Comment by sashasushko** [comment]
@chrisdavidmills yes, it's ok for me.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills yes, it's ok for me.

Great, I'll get you added too.

**Comment by chrisdavidmills** [comment]
OK folks, we now have a decent core ru team size, and there is great work going on, so I think we can close this one now!
