### ISSUE TITLE
zh-cn: 一个错别字

### ISSUE THREAD

**Issue by Xeler-ync** [mdn/translated-content#11722]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Flexible_Box_Layout/Controlling_Ratios_of_Flex_Items_Along_the_Main_Ax

### 与此议题相关的小节或标题？

正负自由空间的备注

### 哪些信息是错误、无用或不完善的？

为了不翻译**花**了，译者不对positive free space 和 negative free space进行翻译，参考翻译是正向自由空间和反向自由空间

### 你期望看到什么？

为了不翻译**化**了，译者不对positive free space 和 negative free space进行翻译，参考翻译是正向自由空间和反向自由空间

### 你还想补充什么内容？

这可能是一个错别字，因为花和化同音，而后者看起来更加合理

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/css_flexible_box_layout/controlling_ratios_of_flex_items_along_the_main_ax`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Flexible_Box_Layout/Controlling_Ratios_of_Flex_Items_Along_the_Main_Ax
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/css_flexible_box_layout/controlling_ratios_of_flex_items_along_the_main_ax/index.md
* Last commit: https://github.com/mdn/translated-content/commit/75b87aa58ba34b03bc81610537148968c714606e
* Document last modified: 2022-09-29T00:09:53.000Z

</details>

**Comment by jasonren0403** [comment]
这里的“花”应该是“模糊”的意思，原文的 `positive free space` 和 `negative free space` 在中文中确实不太好译，直接翻成“正向自由空间”和“反向自由空间”可能会影响读者理解

**Comment by Xeler-ync** [comment]
"翻译花"的这个说法可能较为方言？我询问了周边的朋友和同学，他们都表示自己没有用过这种表述，您觉得把```为了不翻译化了```换成```为了不影响读者理解```会不会好一些

**Comment by jasonren0403** [comment]
可以的，其实这篇文章的翻译时间也不久了，很可能需要一些表述上的优化和变更

**Comment by yin1999** [comment]
`negative free space` 有些文章根据 MDN 之前的中文翻译，翻译为了“负（向）自由空间”，我觉得新的翻译也应尽可能地接近之前的历史。而对“negative space”一词进行搜索，可以检索到百度百科的[词条](https://baike.baidu.com/item/%E8%B4%9F%E7%A9%BA%E9%97%B4/772388)：

> 负空间是指除字体本身所占用的画面空间之外的空白

因为这个名词可以表达“空间之外的内容”，我觉得可以将其翻译为“负自由空间”，并在第一次出现的正文中附上英文：

> 负自由空间（negative free space）

因为正文部分有详细解释这两个概念，我们不需要再通过外加备注的方式对此进行说明。

**Comment by yin1999** [comment]
> `negative free space` 有些文章根据 MDN 之前的中文翻译，翻译为了“负（向）自由空间”，我觉得新的翻译也应尽可能地接近之前的历史。而对“negative space”一词进行搜索，可以检索到百度百科的[词条](https://baike.baidu.com/item/%E8%B4%9F%E7%A9%BA%E9%97%B4/772388)：
> 
> > 负空间是指除字体本身所占用的画面空间之外的空白
> 
> 因为这个名词可以表达“空间之外的内容”，我觉得可以将其翻译为“负自由空间”，并在第一次出现的正文中附上英文：
> 
> > 负自由空间（negative free space）
> 
> 因为正文部分有详细解释这两个概念，我们不需要再通过外加备注的方式对此进行说明。

最终考虑翻译为“正负可用空间”，这里有我在 #11889 上的[预览](https://pr11889.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/CSS/CSS_Flexible_Box_Layout/Controlling_Ratios_of_Flex_Items_Along_the_Main_Ax)。
