### ISSUE TITLE
页面中示例的CodePen链接失效

### ISSUE THREAD

**Issue by Erica-WX** [mdn/translated-content#11777]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/visibility

### 哪些信息是错误、无用或不完善的？

Visibility页面中示例的CodePen链接失效，点击结果显示404

### 你期望看到什么？

希望可以更新成有效的CodePen链接

### 你还想补充什么内容？

![image](https://user-images.githubusercontent.com/33894666/220117847-77fd4c65-9a20-4f49-ab03-b30ee1d493a6.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/visibility`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/visibility
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/visibility/index.md
* Last commit: https://github.com/mdn/translated-content/commit/77d18a6ab1ec41caf61c155b0d35873a0578a068
* Document last modified: 2022-10-08T09:37:21.000Z

</details>

**Comment by jasonren0403** [comment]
最新的英文版文档已经没有这个链接了，等一下翻译同步吧
