### ISSUE TITLE
Spanish translation error

### ISSUE THREAD

**Issue by CeKa-dev16** [mdn/translated-content#11826]
### MDN URL

https://developer.mozilla.org/es/docs/Web/HTML/Element/br

### What specific section or headline is this issue about?

/html/body/div[1]/div[2]/div[3]/main/article/section[2]/div/div/p/text()[1]

### What information was incorrect, unhelpful, or incomplete?

it says: "Nota: Este atributo está obsoleot en HTML5 y no debe utilizarse por los autores. En su lugar utiliza la propiedad [clear](https://developer.mozilla.org/es/docs/Web/CSS/clear) de CSS."

the error is "obsoleot", the correct translate should be "obsoleto"

![image](https://user-images.githubusercontent.com/106848427/220543734-64fe62c6-12e0-4ec2-a6b2-b3d77715f505.png)

### What did you expect to see?

"Nota: Este atributo está obsoleto en HTML5 y no debe utilizarse por los autores. En su lugar utiliza la propiedad [clear](https://developer.mozilla.org/es/docs/Web/CSS/clear) de CSS."

![image](https://user-images.githubusercontent.com/106848427/220544305-e8945eed-f6b4-4ca4-bcd6-c8ab4aaab883.png)

### Do you have any supporting links, references, or citations?

OS: Windows 10
Resolution: 1920 x 1080 px
Browser: Opera GX
Internet provider: Net Patagonia, Argentina
Internet speed: 100mb/s

**Comment by Graywolf9** [comment]
Hola! @CeKa-dev16 muchas gracias por reportar el error, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)

**Comment by vickvasquez** [comment]
Yo lo tomo @Graywolf9. :)
