### ISSUE TITLE
<gradient>ページ（日本語）のradial gradientのスペル修正のお願い

### ISSUE THREAD

**Issue by reikick** [mdn/translated-content#11830]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/CSS/gradient

### この問題に関する節や見出しはどこですか。

構文

### 不完全、不親切、不完全であった情報は何ですか。

放射グラデーション (radical gradient) は、

-------------------
上記の「radical gradient」となっている箇所がスペルミスであると思います。
細かい点で申し訳ござませんが、ご確認ください。

### どう表示されるべきだと思いますか。

放射グラデーション (radial gradient) は、

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/css/gradient`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/gradient
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/gradient/index.md
* Last commit: https://github.com/mdn/translated-content/commit/5d3e7683e319a31262d168e2b05b9ebc87ddfc33
* Document last modified: 2022-09-28T14:06:13.000Z

</details>

**Comment by mfuji09** [comment]
@reikick さん
MDN Web Docs はオープンソースですので、プルリクエストを出すことで誰でも修正提案することができます。
ご自分で修正されますか？
