### ISSUE TITLE
[ko] 앞뒤가 맞지 않는 문장이 있습니다.

### ISSUE THREAD

**Issue by sckroll** [mdn/translated-content#11873]
### MDN URL

https://developer.mozilla.org/ko/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors

### 이 문제에 관한 특정 섹션 또는 제목은 무엇인가요?

투명도

### 어떤 정보가 부정확하거나 도움이 되지 않거나 불완전했나요?

![image](https://user-images.githubusercontent.com/12196625/221105318-6f618ccf-8254-40bb-8e32-a6bd3c2f2c89.png)

앞에서는 `1.0`이 `완전히 불투명`이라고 되어있는데, 뒤에는 `완전히 투명`이라고 되어있습니다.

### 어떻게 고쳐져야 하나요?

![image](https://user-images.githubusercontent.com/12196625/221105435-27bcbce5-50e5-470c-90e3-22c3204e889d.png)

영어 문서를 보면 위와 같이 앞뒤 모두 `fully opaque`라고 되어있으므로 해당 문장도 `완전히 불투명`이라고 수정되어야 합니다.

> globalAlpha = transparencyValue
> 투명도 값이 설정되면 이후 캔버스에 그려지는 모든 도형들의 투명도가 바뀝니다. 설정하는 값은 0.0(완전히 투명)과 1.0(완전히 불투명) 사이에 있어야 하며, 초기 설정값은 1.0(**_완전히 불투명_**)입니다.

### 지원 링크, 참조 또는 인용구가 있으신가요?

https://developer.mozilla.org/ko/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors#%ED%88%AC%EB%AA%85%EB%8F%84

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ko/web/api/canvas_api/tutorial/applying_styles_and_colors`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/api/canvas_api/tutorial/applying_styles_and_colors/index.md
* Last commit: https://github.com/mdn/translated-content/commit/baaf0062bf82c8ffe9c9f2948833589018c64ddd
* Document last modified: 2022-12-29T04:27:25.000Z

</details>

**Comment by SnowMarble** [comment]
@hochan222 안녕하세요:) 이슈가 꽤 오래 전에 해결됐는데 아직 닫히지 않아있네요. 닫아주실 수 있을까요?
