### ISSUE TITLE
"Ferramental" typo?

### ISSUE THREAD

**Issue by Cavernosa** [mdn/translated-content#11871]
### MDN URL

https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/The_web_and_web_standards

### What specific section or headline is this issue about?

Ferramental (#ferramental)

### What information was incorrect, unhelpful, or incomplete?

The section header "Ferramental"

### What did you expect to see?

The section header "Ferramenta**s**".

### Do you have any supporting links, references, or citations?

The entire section talks about "ferramentas"
And I'm sure "Ferramental" doesn't exist

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `pt-br/learn/getting_started_with_the_web/the_web_and_web_standards`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/The_web_and_web_standards
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/getting_started_with_the_web/the_web_and_web_standards/index.md
* Last commit: https://github.com/mdn/translated-content/commit/17ce5499cc99efcabca45581e2bfb82f41acf9a9
* Document last modified: 2023-02-19T20:54:58.000Z

</details>

**Comment by rohini-ranjanR** [comment]
Through Google search "Ferramental" means "tooling" and "Ferramentas" means "tools". The [en-US](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/The_web_and_web_standards) documentation also talks about tooling. I think it should be changed to tools there too.

**Comment by cw118** [comment]
Gently poking @mdn/yari-content-pt-br to take a look :)

In the meantime, do not hesitate to create a PR and wait for feedback there!
