### ISSUE TITLE
(ko) What is a URL needs translation

### ISSUE THREAD

**Issue by yechoi42** [mdn/translated-content#11911]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL

### 어떤 정보가 부정확하거나 도움이 되지 않거나 불완전했나요?

this document needs Korean translation

### 어떻게 고쳐져야 하나요?

this document needs Korean translation

**Comment by SnowMarble** [comment]
제가하겠습니다~

**Comment by SnowMarble** [comment]
@yechoi42 이슈 닫아주실 수 있을까요?
