### ISSUE TITLE
(ko) Element.setAttribute() needs translation

### ISSUE THREAD

**Issue by yechoi42** [mdn/translated-content#11912]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

### 어떤 정보가 부정확하거나 도움이 되지 않거나 불완전했나요?

not translated in Korean

### 어떻게 고쳐져야 하나요?

This document needs to be translated in Korean

**Comment by SnowMarble** [comment]
제가 하겠습니다:)

**Comment by SnowMarble** [comment]
@yechoi42 이슈 닫아주실 수 있을까요?
