### ISSUE TITLE
Web/HTML/Element: All translated pages are missing table content

### ISSUE THREAD

**Issue by manjuu-eater** [mdn/translated-content#11953]
### MDN URL

https://developer.mozilla.org/docs/Web/HTML/Element

### What specific section or headline is this issue about?

all sections

### What information was incorrect, unhelpful, or incomplete?

Table contents are empty in all translated Web/HTML/Element pages.

This problem is caused by the removed macro `HTMLRefTable`.
Related: https://github.com/mdn/content/pull/24515

This issue is a part of https://github.com/mdn/translated-content/issues/5603 .

### What did you expect to see?

table content

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/es/docs/Web/HTML/Element
https://developer.mozilla.org/fr/docs/Web/HTML/Element
https://developer.mozilla.org/ja/docs/Web/HTML/Element
https://developer.mozilla.org/ko/docs/Web/HTML/Element
https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element
https://developer.mozilla.org/ru/docs/Web/HTML/Element
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element
https://developer.mozilla.org/zh-TW/docs/Web/HTML/Element

### Do you have anything more you want to share?

I made PRs for each page.

- [x] #12015
- [x] #12016
- [x] #11993
- [x] #12017
- [x] #12018
- [ ] #12019
- [x] #12020
- [x] #12021

**Comment by yin1999** [comment]
as a part of: #5603

**Comment by manjuu-eater** [comment]
Where is the translated contents referenced from {{HTMLRefTable("...")}} located?
I want to fix this, but I couldn't find translated contents.

I can use [WayBackMachine](https://web.archive.org/web/20230203235743/https://developer.mozilla.org/ja/docs/Web/HTML/Element) content, but I want to use translated source if exists.

**Comment by yin1999** [comment]
> Where is the translated contents referenced from {{HTMLRefTable("...")}} located? I want to fix this, but I couldn't find translated contents.

See mdn/content#24515. We should replace them with markdown tables

**Comment by manjuu-eater** [comment]
Thank you for comment.

Sorry for the ambiguous text.
I just want to know where the already translated text (e.g. Japanese translated text) is placed.

I think translated Japanese text exists (or existed) somewhere because [WayBackMachine](https://web.archive.org/web/20230203235743/https://developer.mozilla.org/ja/docs/Web/HTML/Element) displays translated Japanese.

**Comment by yin1999** [comment]
The table is loaded by [macro](https://github.com/mdn/yari/blob/d3767b96270f710cfc79157e0b44c0c6118b1840/kumascript/macros/HTMLRefTable.ejs).

If you like, just take a look into this.

**Comment by manjuu-eater** [comment]
Thank you.

I couldn't find Japanese text still, and realized that HTMLRefTable macro was reading each content dynamically from each pages (e.g. Web/HTML/Element/html)

I'll get to work on copying.
