### ISSUE TITLE
The webgl demo is broken in `Animating textures in WebGL` tutorial

### ISSUE THREAD

**Issue by zijid** [mdn/translated-content#11981]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL

### what's wrong in the document

The demo is just broken:

- [ ] [fr](https://developer.mozilla.org/fr/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL) #12006
- [ ] [es](https://developer.mozilla.org/es/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL) #12006
- [ ] [ja](https://developer.mozilla.org/ja/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL) #12006
- [x] [zh-CN](https://developer.mozilla.org/zh-CN/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL) #12004

### expected

Update the demo and the referenced link to GitHub files.

https://github.com/mdn/dom-examples/tree/main/webgl-examples/tutorial/sample8

https://mdn.github.io/dom-examples/webgl-examples/tutorial/sample8/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/webgl_api/tutorial/animating_textures_in_webgl`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/WebGL_API/Tutorial/Animating_textures_in_WebGL
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/webgl_api/tutorial/animating_textures_in_webgl/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b5b4590e12242feaf7ef337171bfb2ef6a68dc35
* Document last modified: 2022-12-08T14:07:47.000Z

</details>

**Comment by jasonren0403** [comment]
This issue occurs not only in zh-CN, but also in `ru`, `ja`, `fr` locale.
