### ISSUE TITLE
Пропала информация в разделе "Новички начинают здесь"

### ISSUE THREAD

**Issue by Farminator** [mdn/translated-content#12029]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web/Publishing_your_website

### О какой части статьи или абзаце идёт речь?

вся статья, точнее несколько тематически связанных страниц

### Какая информация оказалась неверной, бесполезной или неполной?

Пропала вся информация из раздела "Новички начинают здесь" на русском языке. От "Начало работы с Вебом" до "Как работает Веб". 

На английском языке проверил - всё на месте.

### Как бы вы исправили?

Наверное, возможен откат изменений, где всё удалили.

### Есть ли у вас какие-либо подтверждающие ссылки?

https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/getting_started_with_the_web/publishing_your_website`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web/Publishing_your_website
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/getting_started_with_the_web/publishing_your_website/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f0c5f1ed137da2bfa3b0988cd0a10a5a2a6d3973
* Document last modified: 2022-12-15T06:58:58.000Z

</details>

**Comment by myshov** [comment]
Похоже, что эту проблему нужно решать со стороны инфраструктуры. На данный момент всё хорошо. Ошибка была исправлена в https://github.com/mdn/yari/pull/8371. Открыл обсуждение этой проблемы в mdn-content https://github.com/mdn/mdn-community/discussions/346, чтобы решить как предотвратить подобные инциденты в будущем

**Comment by Farminator** [comment]
Благодарю вас за участие, Александр. Я сам не очень понимаю, как с проблемами иметь дело. Но проинформировал сообщество, раз кнопка была для этого.   :)
Желаю успехов.
