### ISSUE TITLE
Баг русскоязычной версии сайта

### ISSUE THREAD

**Issue by sinnderwelt** [mdn/translated-content#12038]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/Variables

### О какой части статьи или абзаце идёт речь?

О целой статье

### Какая информация оказалась неверной, бесполезной или неполной?

![statia](https://user-images.githubusercontent.com/79840665/223075395-cffeb32c-fd45-4bae-85d5-13f2eb2232d1.png)

Исчез контент целой страницы. Проблема только в русском варианте. Проверил на ПК и планшете. До этого материал на сайте был.

### Как бы вы исправили?

Вернул исчезнувший контент.

### Есть ли у вас какие-либо подтверждающие ссылки?

![statia](https://user-images.githubusercontent.com/79840665/223075915-1f851d3e-bd06-47fc-b959-3cd883770043.png)

У меня нет ссылки, но есть кое-что получше, у меня есть картинка 
![statia](https://user-images.githubusercontent.com/79840665/223076076-3ee96401-e146-4872-8dcf-b16f30fe8861.png)

### Хотите добавить что-то ещё?

Я также обнаружил, что нет материала практически во всех разделах предназначенных для новичков. 

https://user-images.githubusercontent.com/79840665/223079471-8143f30d-7350-473f-8f1d-0cbd819fef68.mp4

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/javascript/first_steps/variables`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/Variables
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/javascript/first_steps/variables/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f0c5f1ed137da2bfa3b0988cd0a10a5a2a6d3973
* Document last modified: 2022-12-15T06:58:58.000Z

</details>

**Comment by Mypuk1991** [comment]
Та же история

**Comment by myshov** [comment]
Похоже, что это была временная проблема. Сейчас всё в порядке:
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/2382567/224549698-163ef023-386c-4b79-8550-a4177604f7dc.png">

**Comment by myshov** [comment]
Открыл обсуждение этой проблемы в mdn-content https://github.com/mdn/mdn-community/discussions/346
