### ISSUE TITLE
Animation simple d'un personnage

### ISSUE THREAD

**Issue by dom73** [mdn/translated-content#12080]
### MDN URL

https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics

### What specific section or headline is this issue about?

Animation simple d'un personnage

### What information was incorrect, unhelpful, or incomplete?

Il manque des informations conscernant le background de l'animation. Sinon c'esT très bien.

const canvas = document.querySelector('.myCanvas');
const width = canvas.width = window.innerWidth;
const height = canvas.height = window.innerHeight;
const ctx = canvas.getContext('2d');

ctx.fillStyle = 'rgb(0,0,0)';
ctx.fillRect(0,0,width,height);

### What did you expect to see?

J'ai testé et personalisé l'animation simple d'un personnage. Cela fonctionne bien sauf que je voudrais changer le background de l'animation qui est en noir pour le rendre transparent. J'ai cherché comment faire sur internet mais je n'y arrive pas. Pouvez-vous m'indiquer comment faire?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/javascript/client-side_web_apis/drawing_graphics`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/javascript/client-side_web_apis/drawing_graphics/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f33c697e3e098b97132fe8d2637bd763126fbfc2
* Document last modified: 2022-11-27T04:10:45.000Z

</details>

**Comment by SphinxKnight** [comment]
bonjour @dom73, il faudra pour cela utiliser une composante alpha.

* Pour l'arrière-plan de l'animation : vous pouvez ajouter une composante alpha dans `ctx.fillStyle()` : par exemple `ctx.fillStyle = 'rgba(0,0,0,0.8)';` qui ajoutera un fond noir légèrement transparent (`ctx.fillStyle = 'rgba(0,0,0,0.1)';` sera encore plus transparent).

* Pour le dessin de l'image c'est [`globalAlpha`](https://developer.mozilla.org/fr/docs/Web/API/CanvasRenderingContext2D/globalAlpha) qu'il faudra utiliser :

```
ctx.globalAlpha = 0.3; // 1 étant complètement opaque et 0 totalement transparent
ctx.drawImage(image, (sprite*102), 0, 102, 148, 0+posX, -74, 102, 148);
```

Pour l'exemple du personnage, si on gère la transparence l'arrière plan il faut faire attention à ne pas oublier de redessiner le rectangle de fond pour éviter que les frames "bavent" l'une après l'autre : 
![image](https://user-images.githubusercontent.com/2413436/232030205-5daae447-a524-4c78-b0f7-b2d0442b8e2d.png)

Voici un exemple basé sur celui de l'article : 

Dans `style.css` : 

```css
body {
  margin: 0;
  overflow: hidden;
  background-color: pink;
}
```

Dans `script.js` : 

```js
const canvas = document.querySelector('.myCanvas');
const width = canvas.width = window.innerWidth;
const height = canvas.height = window.innerHeight;
const ctx = canvas.getContext('2d');


ctx.translate(width/2,height/2);

const image = new Image();
image.src = 'walk-right.png';
image.onload = draw;

let sprite = 0;
let posX = 0;

function draw() {
  // On nettoie le canevas pour éviter que ça bave
  ctx.clearRect(-(width/2),-(height/2),width,height);
  // On remet le niveau de transparence générale en opaque pour éviter 
  // de cumuler la transparence de globalAlpha de la dernière itération et de fillStyle
  ctx.globalAlpha = 1;
  ctx.fillStyle = 'rgba(0,0,0,0.2)';
  // on applique notre arrière-plan sur l'ensemble du canevas
  ctx.fillRect(-(width/2),-(height/2),width,height);

  // On choisit la transparence du personnage
  ctx.globalAlpha = 0.4;
  ctx.drawImage(image, (sprite*102), 0, 102, 148, 0+posX, -74, 102, 148);

  if (posX % 13 === 0) {
    if (sprite === 5) {
      sprite = 0;
    } else {
      sprite++;
    }
  }

  if (posX > width/2) {
    let newStartPos = -((width/2) + 102);
    posX = Math.ceil(newStartPos);
    console.log(posX);
  } else {
    posX += 2;
  }

  window.requestAnimationFrame(draw);
};
```
Voici ce que j'obtiens 
![image](https://user-images.githubusercontent.com/2413436/232031237-b1a98d86-82a4-44c3-a26e-4853dfe1e8fb.png)

**Comment by SphinxKnight** [comment]
En revanche vu que l'article est déjà bien dense et que le point n'est pas non plus décrit dans cet article en anglais mais dans https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Applying_styles_and_colors, je vais clore cette demande :) 

N'hésitez pas si ça n'est pas clair ou si vous pensez que les articles https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics et https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics doivent être amendés
