### ISSUE TITLE
[FR] clip-path documentation image link 404.

### ISSUE THREAD

**Issue by jonas-martinez** [mdn/translated-content#12105]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/clip-path

### What specific section or headline is this issue about?

Under "Résultat"

### What information was incorrect, unhelpful, or incomplete?

The MDN logo under the "Résultat" section shows a 404.

### What did you expect to see?

The MDN logo.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/clip-path`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/clip-path
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/clip-path/index.md
* Last commit: https://github.com/mdn/translated-content/commit/79faa1509d68be77f14971a843e43da59dedff2f
* Document last modified: 2022-09-21T09:43:31.000Z

</details>

**Comment by yarusome** [comment]
See https://github.com/mdn/yari/issues/5652 for all translated pages.
