### ISSUE TITLE
No se muestran las imágenes en resultado.

### ISSUE THREAD

**Issue by jhonatan0912** [mdn/translated-content#12130]
### MDN URL

https://developer.mozilla.org/es/docs/Web/CSS/object-fit

### ¿De qué sección específica o titular trata este problema?

Resultado

### ¿Qué información es incorrecta, inútil o incompleta?

Deberían mostrarse las imágenes en la sección de resultados

### ¿Qué esperaba ver?

Los resultados

### ¿Tiene algún enlace de apoyo, referencias o citas?

![Screenshot 2023-03-11 124055](https://user-images.githubusercontent.com/68581196/224503500-4670376f-3ef0-4308-a7d2-5ed17769c5a7.png)

### ¿Tiene algo más que quiera compartir?

no

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/css/object-fit`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/object-fit
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/object-fit/index.md
* Last commit: https://github.com/mdn/translated-content/commit/58ba651fe85a08e3a483a9b50a0b298636461b90
* Document last modified: 2023-02-23T18:24:06.000Z

</details>

**Comment by yin1999** [comment]
Related to mdn/yari#5652. I've made to PR trying to fix this (just still waiting for review from core team)

**Comment by kemilbeltre** [comment]
@Graywolf9 is there any news about this issue?

**Comment by Graywolf9** [comment]
Hi! @kemilbeltre, thanks for being here, this seems to be a bug in Yari the core of MDN that is being tracked [here](https://github.com/mdn/yari/issues/5652), I think we can take the option of copy the image to mitigate this bug meanwhile

**Comment by kemilbeltre** [comment]
> I think we can take the option of copy the image to mitigate this bug meanwhile

Hi @Graywolf9 , agreed. Can we use the full URL of the original version?

**Comment by Graywolf9** [comment]
We do not use absolute or full URL, so the option is to copy the image in the same directory as the article

**Comment by kemilbeltre** [comment]
Hi @Graywolf9, please review the PR. Thanks!
