### ISSUE TITLE
The code example in `@@iterator` is not correct

### ISSUE THREAD

**Issue by gaoting** [mdn/translated-content#12140]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator

### 哪些信息是错误、无用或不完善的？

<img width="575" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/7401170/224520435-f24fd8ef-116a-4ebc-91a0-6a897c15cba9.png">

### 你期望看到什么？

此处应该不报错，并且如文中显示那般 能正常迭代执行

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/array/@@iterator`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/array/@@iterator/index.md
* Last commit: https://github.com/mdn/translated-content/commit/949e1b3c96d9c43051eb96e32fb757b5f3008ecd
* Document last modified: 2022-10-18T06:22:56.000Z

</details>

**Comment by yin1999** [comment]
Yes, we need to update this code example with the english one:

https://github.com/mdn/content/blob/341f51189d530b5f2a313ae9ed9391d04e21ac18/files/en-us/web/javascript/reference/global_objects/array/%40%40iterator/index.md?plain=1#L70-L96
