### ISSUE TITLE
Erreur dans l'exercice

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#12163]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/min-width

### What specific section or headline is this issue about?

https://developer.mozilla.org/fr/docs/Web/CSS/min-width#exemples

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

La page est consacrée à min-width.
Dans le CSS de l'exercice le paramétrage de p comporte du max-width et pas min-width.

### What did you expect to see?

Un exemple avec min-width

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/min-width`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/min-width
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/min-width/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f66954d9bcc9f94b8dab0ba5452395282c5372cd
* Document last modified: 2022-10-01T14:10:29.000Z

</details>

**Comment by DomOBU** [comment]
Si j'avais pu joindre une copie d'écran j'aurais pu joindre l'exemple que je me suis fait.

**Comment by DomOBU** [comment]
J'ai réussi.
![min-width Capture](https://user-images.githubusercontent.com/95876663/224841737-a4aa310f-de13-4414-b39f-de61161f516d.JPG)

**Comment by SphinxKnight** [comment]
merci beaucoup @DomOBU pour tous les éléments :) je vais regarder ça
