### ISSUE TITLE
Опечатка на странице

### ISSUE THREAD

**Issue by CasiCode** [mdn/translated-content#12167]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Expressions_and_Operators

### О какой части статьи или абзаце идёт речь?

Оператор Группировки

### Какая информация оказалась неверной, бесполезной или неполной?

"так чтобы, например, чтобы"

### Как бы вы исправили?

Лишнее "чтобы"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/guide/expressions_and_operators`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Expressions_and_Operators
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/guide/expressions_and_operators/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c9f62a257b15f630759420ce002bdcdb9e90e17c
* Document last modified: 2023-02-11T06:53:49.000Z

</details>

**Comment by myshov** [comment]
@CasiCode hi!
It was fixed in this commit https://github.com/mdn/translated-content/commit/88ca51e23ea2663258738c64fa6eeb13f99b5113 Changes already present on the main site. Thanks for contribution!
