### ISSUE TITLE
snippet code not same as english version

### ISSUE THREAD

**Issue by Franck78** [mdn/translated-content#12231]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/API/File_API/Using_files_from_web_applications

### What information was incorrect, unhelpful, or incomplete?

In 
https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications

https://developer.mozilla.org/fr/docs/Web/API/File_API/Using_files_from_web_applications

not always same code example:
[Example: Showing file(s) size](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#example_showing_files_size)
[Exemple : Afficher la taille d'un ou plusieurs fichiers](https://developer.mozilla.org/fr/docs/Web/API/File_API/Using_files_from_web_applications#exemple_afficher_la_taille_dun_ou_plusieurs_fichiers)

but the most annoying is this one using deprecated call to  **xhr.sendAsBinary**

[Handling the upload process for a file](https://developer.mozilla.org/en-US/docs/Web/API/File_API/Using_files_from_web_applications#handling_the_upload_process_for_a_file)
[Manipuler le processus de téléchargement pour un fichier](https://developer.mozilla.org/fr/docs/Web/API/File_API/Using_files_from_web_applications#manipuler_le_processus_de_t%C3%A9l%C3%A9chargement_pour_un_fichier)

### What did you expect to see?

same code example for each langage.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/file_api/using_files_from_web_applications`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/File_API/Using_files_from_web_applications
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/file_api/using_files_from_web_applications/index.md
* Last commit: https://github.com/mdn/translated-content/commit/463882cfbd1917c6d6103b3111adfe76a96acad3
* Document last modified: 2022-11-28T08:49:59.000Z

</details>

**Comment by SphinxKnight** [comment]
I've opened #12774 but I'm not even quite satisfied with the current English article tbh

**Comment by Franck78** [comment]
I had no idea this 'tr mismatch' would generate such a big patch ;)
I have no knowledge to help you enhance  the article ;) 

Thank you
