### ISSUE TITLE
All uses of $samples URLs are deprecated and need to be replaced

### ISSUE THREAD

**Issue by peterbe** [mdn/translated-content#1231]
For example: See the diff in https://github.com/mdn/translated-content/pull/1230/files

Things like:
```html
<iframe class="live-sample-frame sample-code-frame" frameborder="0" height="180px" id="frame_Live_example" 
 src="https://mdn.mozillademos.org/en-US/docs/Web/API/Element/compositionstart_event$samples/Live_example?revision=1606277" width="100%"
 ></iframe>
```
is deprecated and needs to cleaned up. In `en-US` all instances of these have been replaced with `EmbedLiveSample`. 

Please help hunt these down to upgrade. The output of these URLs will soon stop working because it frees up MDN to stop storing the old WIki revisions from 2019 and older. 

Note; it's not just `<iframes>` there are sometimes links too. Try to replace them with regular links to file attachments.

**Comment by peterbe** [comment]
@mdn/yari-content-fr 
```
▶ rg -i '\$sample'  --count-matches
web/html/element/img/index.html:1
web/svg/attribute/text-anchor/index.html:1
mdn/structures/live_samples/index.html:1
```

@mdn/yari-content-ja 
```
▶ rg -i '\$sample'  --count-matches
web/html/element/img/index.html:1
```

@mdn/yari-content-ru 
```
▶ rg -i '\$sample'  --count-matches
mdn/structures/live_samples/index.html:1
```

@mdn/yari-content-pt-br 
```
▶ rg -i '\$sample'  --count-matches
learn/javascript/first_steps/what_is_javascript/index.html:1
```

@mdn/yari-content-zh 
```
▶ rg -i '\$sample'  --count-matches
web/api/htmlelement/input_event/index.html:1
web/api/htmlelement/beforeinput_event/index.html:1
web/api/mouseevent/screeny/index.html:1
web/api/mouseevent/screenx/index.html:1
web/api/range/selectnodecontents/index.html:1
web/api/range/surroundcontents/index.html:1
web/api/htmlinputelement/setselectionrange/index.html:1
web/api/htmlselectelement/selectedindex/index.html:1
web/api/datatransfer/getdata/index.html:1
web/api/document/readystatechange_event/index.html:1
web/api/domtokenlist/index.html:2
web/api/element/mouseout_event/index.html:1
web/html/element/img/index.html:1
web/html/element/input/index.html:22
learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/index.html:2
orphaned/web/api/detecting_device_orientation/index.html:2
mdn/structures/live_samples/index.html:1
```
```
▶ pwd
/Users/peterbe/dev/MOZILLA/MDN/translated-content/files/zh-tw
▶ rg -i '\$sample'  --count-matches
web/api/canvas_api/tutorial/compositing/index.html:2
```

@mdn/yari-content-ko 
```
▶ rg -i '\$sample'  --count-matches
web/html/element/img/index.html:1
```

**Comment by SphinxKnight** [comment]
@peterbe fr cleared

**Comment by sashasushko** [comment]
@peterbe I see that you fixed files in `ru` directory by yourself. Thank you!

**Comment by hochan222** [comment]
@peterbe ko cleared

**Comment by peterbe** [comment]
Update! Now the only 3 places where it's still used are:

```
▶ rg -i '\$sample'  --count-matches
files/pt-br/learn/javascript/first_steps/what_is_javascript/index.html:1
files/ja/web/html/element/img/index.html:1
files/zh-tw/web/api/canvas_api/tutorial/compositing/index.html:2
```


- [ ] https://github.com/mdn/translated-content/blob/c836bcfa33f859deddb9c2a4afb79e7e106e3d29/files/pt-br/learn/javascript/first_steps/what_is_javascript/index.html#L289
- [ ] https://github.com/mdn/translated-content/blob/c836bcfa33f859deddb9c2a4afb79e7e106e3d29/files/ja/web/html/element/img/index.html#L286
- [ ] https://github.com/mdn/translated-content/blob/c836bcfa33f859deddb9c2a4afb79e7e106e3d29/files/zh-tw/web/api/canvas_api/tutorial/compositing/index.html#L124

**Comment by peterbe** [comment]
That's it!  THANK YOU all involved for your grand and gracious effort!
