### ISSUE TITLE
zh-CN: Sidebar missing on multiple CSS pages

### ISSUE THREAD

**Issue by yarusome** [mdn/translated-content#12323]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/Using_CSS_custom_properties
https://developer.mozilla.org/zh-CN/docs/Web/CSS/border-top-left-radius

### What information was incorrect, unhelpful, or incomplete?

The sidebar is missing.

### What did you expect to see?

A sidebar, like the [en-US version](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) has.

**Comment by yin1999** [comment]
Simply adding some thing like [this line](https://github.com/mdn/content/blob/1b1c7a6ba409d38a94d916d4698fb29398d1031b/files/en-us/web/css/using_css_custom_properties/index.md?plain=1#L7) could resolve this.
