### ISSUE TITLE
Not a good example, it's not work

### ISSUE THREAD

**Issue by DVBels** [mdn/translated-content#12325]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/A_first_splash

### О какой части статьи или абзаце идёт речь?

guessField.value = 'Hello';

### Какая информация оказалась неверной, бесполезной или неполной?

guessField.value = 'Hello'; - it's not work, even in your example 
The specified value "Hello" cannot be parsed, or is out of range.

### Как бы вы исправили?

IDK just learning
The specified value "Hello" cannot be parsed, or is out of range.

### Есть ли у вас какие-либо подтверждающие ссылки?

https://mdn.github.io/learning-area/javascript/introduction-to-js-1/first-splash/number-guessing-game.html

The specified value "Hello" cannot be parsed, or is out of range.

### Хотите добавить что-то ещё?

no)

The specified value "Hello" cannot be parsed, or is out of range.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/javascript/first_steps/a_first_splash`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/A_first_splash
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/javascript/first_steps/a_first_splash/index.md
* Last commit: https://github.com/mdn/translated-content/commit/9f2ae81362acb39ca86e5a9c81c9f298a57a3400
* Document last modified: 2022-10-27T13:52:07.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17372 :ok_hand: 

Thank you! :+1:
