### ISSUE TITLE
webkit-text-stroke ページの内容が古くなっている

### ISSUE THREAD

**Issue by adyobe** [mdn/translated-content#12369]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/CSS/-webkit-text-stroke

### この問題に関する節や見出しはどこですか。

初めの警告

### 不完全、不親切、不完全であった情報は何ですか。

非推奨という情報は古いのではないでしょうか？

### どう表示されるべきだと思いますか。

警告は消した方がいいと思います。

### 補足情報となるリンク、参考資料、引用文献はありますか。

多国語版のmdnとhttps://caniuse.com/?search=text-stroke。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/css/-webkit-text-stroke`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/-webkit-text-stroke
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/-webkit-text-stroke/index.md
* Last commit: https://github.com/mdn/translated-content/commit/5d3e7683e319a31262d168e2b05b9ebc87ddfc33
* Document last modified: 2022-09-28T14:06:13.000Z

</details>

**Comment by potappo** [comment]
情報ありがとうございます。明日かあさってには最新の英語版に合うように更新しておきます。
