### ISSUE TITLE
Infinity is not greater than itself

### ISSUE THREAD

**Issue by Jeremias0901** [mdn/translated-content#12364]
### MDN URL

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Infinity

### ¿De qué sección específica o titular trata este problema?

> El valor de Infinity (infinito positivo) es mayor que cualquier otro numero **incluido el mismo**

Es decir: Infinity > Infinity devuelve true? **supongo** que si...

### ¿Qué información es incorrecta, inútil o incompleta?

Dice que `Infinity > Infinity` devuelve `true`.

### ¿Qué esperaba ver?

`Infinity > Infinity` devuelve `false`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/infinity`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Infinity
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/infinity/index.md
* Last commit: https://github.com/mdn/translated-content/commit/3c08abe996877860f51637042d7849045ba4632d
* Document last modified: 2023-02-14T22:43:17.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! @Jeremias0901 

Muchas gracias por reportar la incidencia, ¿tienes la documentación de donde has obtenido que `Infinity > Infinity` debe ser false?

**Comment by Graywolf9** [comment]
Muchas gracias por reportar el error @Jeremias0901, el párrafo que mencionas junto con otros detalles serán actualizados en https://github.com/mdn/translated-content/pull/12367

De nuevo muchas gracias y siententé libre de seguir colaborando
