### ISSUE TITLE
Updating yari-content-fr to reflect current core contributors

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#1243]
Hello,

Since the beginning of the localization on yari and the creation of the team, @tristantheb and I have been the core contributors to fr.

@Rumyra could you please update the team members to reflect that? This will avoid assigning issues to inactive users and get Tristan and I quicker in the loop for reviews.

I'll submit a PR to update the README and /mdn/contribute/localize to reflect this on the content as well.

**Comment by SphinxKnight** [comment]
@Rumyra what is the current process for this kind of request? Is there anything else I can do?

**Comment by hochan222** [comment]
ko-locale is also not now, but I'm curious about the process for future issues.

**Comment by SphinxKnight** [comment]
I'd like to ask the addition of @audrasjb to the @mdn/yari-content-fr team. He already made numerous PRs and contributions, incl. reviews and accepted my invitation. Having him among Tristan and I will make for a good set.

@Rumyra is there anything I can do regarding this?

**Comment by Rumyra** [comment]
This should be done - apologies for the delay.

I'm currently writing up processes around requests like this - once it's done I will share 👍

**Comment by SphinxKnight** [comment]
https://github.com/orgs/mdn/teams/yari-content-fr is up to date, thanks @Rumyra !
