### ISSUE TITLE
[ko] encoding vs decoding 의 적절한 번역

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#12452]
## What is the new suggestion?

encoding과 decoding의 적절한 번역을 정하고 싶으며, 현재는 아래 2가지가 혼용되어 사용되고 있습니다. 의견 부탁드립니다. (cc. @mdn/yari-content-ko)

(1) 인코딩/디코딩
(2) 부호화/복호화

```
- {{domxref("atob", "Window.atob()")}}
  - : Base64로 인코딩된 문자열 데이터를 디코딩합니다.
- {{domxref("btoa", "Window.btoa()")}}
  - : 이진 데이터 문자열을 Base64로 인코딩한 ASCII 문자열을 생성합니다.

- {{domxref("atob", "Window.atob()")}}
  - : Base64로 부호화된 문자열 데이터를 복호화합니다.
- {{domxref("btoa", "Window.btoa()")}}
  - : 이진 데이터 문자열을 Base64로 부호화한 ASCII 문자열을 생성합니다.
```

## 사용 현황

현재 MDN 한국 문서에서의 사용 현황입니다.

- 인코딩 (281 results in 90 files)
- 디코딩 (69 results in 28 files)
- 부호화 (3 results in 2 files)
- 복호화 (8 results in 6 files)

## 인코딩/디코딩의 의견

- 인코딩/디코딩의 한국어 번역으로 '부호화/복호화'라는 용어가 사용될 수 있지만, 일반적으로는 '인코딩/디코딩'이 가장 널리 사용되고 있는 용어입니다.
  - [Microsoft](https://support.microsoft.com/ko-kr/office/%ED%8C%8C%EC%9D%BC%EC%9D%84-%EC%97%B4%EA%B1%B0%EB%82%98-%EC%A0%80%EC%9E%A5%ED%95%A0-%EB%95%8C-%ED%85%8D%EC%8A%A4%ED%8A%B8-%EC%9D%B8%EC%BD%94%EB%94%A9-%EC%84%A0%ED%83%9D-60d59c21-88b5-4006-831c-d536d42fd861):  부호화/복호화의 용어는 암호 관련에서만 사용되고 모두 인코딩/디코딩 용어를 사용하고 있습니다.
- 아래는 컴퓨터 공학에서 사용되는 예시들입니다. 부호화를 사용해도 어색하진 않지만, 개인적으로는 인코딩을 사용했을 때 익숙해서인지 변환의 의미가 더 가까이 와닿습니다. 
  - 문자열 인코딩 / 문자열 부호화 (예: UTF-8, UTF-16, ASCII 등)
  - URL 인코딩 / URL 부호화
  - 멀티미디어 인코딩 / 멀티미디어 부호화
  - 압축 인코딩 / 압축 부호화
  - 인코딩 / 부호화(암호에서)
  - 파일 인코딩 / 파일 부호화
  
## 부호화/복호화의 의견

- encoding, decoding에 대해 명확하게 대응되는 번역 용어가 있습니다.
- 한글입니다.

## Related PR

https://github.com/mdn/translated-content/pull/12451

**Comment by wisedog** [comment]
저도 인코딩/디코딩에 한 표 던집니다

**Comment by swimjiy** [comment]
저도 인코딩/디코딩으로 사용하는 것이 좋을 것 같습니다👍

**Comment by pje1740** [comment]
encode의 영영 사전적 정의는 
```
convert (information or an instruction) into a particular form
```
인데 한국어의 부호화는 뜻이 의외로 여러가지가 있고 익숙치 않은 문제가 있는 거 같습니다! (꼭 변환을 의미하는 거 같지도 않구요 🤔)

그래서 저도 인코딩/디코딩 한 표입니다!

**Comment by hochan222** [comment]
의견 모두 감사합니다! 디스코드에서 추가적으로 아래 의견을 주셨습니다.

Cor (logic-finder)님은 "제 느낌엔 인코딩이 부호화보다는 자연스러운 거 같아요"
Hatchling님은 "같은 의견입니다! 이슈에서 알려주신 마이크로소프트의 경우처럼, "부호화/복호화"는 암호 관련 문맥에서 사용되는 경우를 더 많이 접했습니다. 일반적인 경우에는 "인코딩/디코딩"을 사용하는 것이 기존의 용례와 일치할 것으로 생각합니다."

encoding/decoding은 인코딩/디코딩으로 번역하는 것으로 안내서에 추가하겠습니다. 추가적인 의견은 issue reopen 후 의견 부탁드립니다.

모두 좋은 하루 보내세요 :)
