### ISSUE TITLE
CSS transition page issue

### ISSUE THREAD

**Issue by Hypocrate-code** [mdn/translated-content#12477]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/transition

### What specific section or headline is this issue about?

CSS transition page

### What information was incorrect, unhelpful, or incomplete?

I was writing code (pure CSS) when i discovered that css "transition" property didn't need coma, in order to separate the different transition properties and duration

### What did you expect to see?

i think that it would be great just to modify the code exposed in the exemple (the demonstration) from "transition: margin-right 2s, color 1s;" to "transition: margin-right 2s color 1s;"

### Do you have any supporting links, references, or citations?

nope sorry

### Do you have anything more you want to share?

no, except that you're doing a great job !

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/transition`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/transition
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/transition/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f66954d9bcc9f94b8dab0ba5452395282c5372cd
* Document last modified: 2022-10-01T14:10:29.000Z

</details>

**Comment by yin1999** [comment]
Actually, we could see the same writing style in en-US, I'm not really sure whether it's used to split different properties (for readability).

**Comment by yarusome** [comment]
It shows to be valid without the comma in the live exmaple. In what environment did you find the comma-less version to work?

---

Per the [CSS Transition](https://w3c.github.io/csswg-drafts/css-transitions/#transition-shorthand-property) spec, the value of `transition` is `<single-transition>#`, where per the [CSS Values and Units](https://w3c.github.io/csswg-drafts/css-values-4/#mult-comma) spec:

> A hash mark (***#***) indicates that the preceding type, word, or group occurs one or more times, separated by comma tokens (which may optionally be surrounded by white space and/or comments). It may optionally be followed by the curly brace forms, above, to indicate precisely how many times the repetition occurs, like `<length>#{1,4}`.

So it's non-conforming for the comma-less version to be valid anyway.

**Comment by yin1999** [comment]
Let's waiting for feedback from the author (maybe 2 weeks) before closing this :)

Thanks for your infomation @yarusome

**Comment by SphinxKnight** [comment]
Thanks @yarusome and @yin1999  🙇 

I also think we should close this as:

- This also occurs on the English version which acts as a reference for the localized content
- The syntax without comma should not be encouraged

**Comment by SphinxKnight** [comment]
Closing this since there has been no comment from the author after two weeks.
