### ISSUE TITLE
Wrong HTML example

### ISSUE THREAD

**Issue by Olfdev** [mdn/translated-content#12542]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/API/Element/getAttribute

### What specific section or headline is this issue about?

https://developer.mozilla.org/fr/docs/Web/API/Element/getAttribute#exemple

### What information was incorrect, unhelpful, or incomplete?

The HTML example is wrong, it displays some javascript instead.

```js
const div1 = document.getElementById("div1");
```

It should be (based on the US page):

```
<!-- exemple de div en HTML -->
<div id="div1">Hi Champ!</div>
```

### What did you expect to see?

```
<!-- exemple de div en HTML -->
<div id="div1">Hi Champ!</div>
```

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/element/getattribute`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Element/getAttribute
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/element/getattribute/index.md
* Last commit: https://github.com/mdn/translated-content/commit/040a7573de416de6d0defcdb706a19924bdd44d6
* Document last modified: 2022-09-21T09:43:04.000Z

</details>

**Comment by w3tsa** [comment]
Hello, @yin1999 I have created a PR for the above fix: https://github.com/mdn/translated-content/pull/12660
