### ISSUE TITLE
Whole page was accidentally untranslated

### ISSUE THREAD

**Issue by jasonren0403** [mdn/translated-content#12545]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/HTML_DOM_API

### 与此议题相关的小节或标题？

整个页面

### 哪些信息是错误、无用或不完善的？

该页面全部没有进行翻译，对于读者来说体验不好

### 你期望看到什么？

翻译完整的页面

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/html_dom_api`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/HTML_DOM_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/html_dom_api/index.md
* Last commit: https://github.com/mdn/translated-content/commit/80dc54bdbf5e25d70e829afe46f5e558e0694af3
* Document last modified: 2022-09-24T08:38:52.000Z

</details>

**Comment by xiamiko** [comment]
I would like to try this job as a starting point for contributing to MDN. I have read the [Chinese contribution guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md), can I start this work? Are there any other important things that I need to know?

@yin1999

**Comment by yin1999** [comment]
> I would like to try this job as a starting point for contributing to MDN. I have read the [Chinese contribution guide](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md), can I start this work? Are there any other important things that I need to know?
> 
> @yin1999 

We've listed the most common problems in translation guide. So, if you want to do this job, just start it!

I'll assign this to you, thanks for your interest  😘
