### ISSUE TITLE
Confusión por la traducción

### ISSUE THREAD

**Issue by evazquezb** [mdn/translated-content#12548]
### MDN URL

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/length

### ¿De qué sección específica o titular trata este problema?

La propiedad length de los string

### ¿Qué información es incorrecta, inútil o incompleta?

La traducción me parece incorrecta y genera confusión.
Me parece que se debe aclarar bien si hay una diferencia entre unidades de codigo o caracteres
ya que la traduccion dice que la propiedad devuelve el numero de caracteres mientras que la version en ingles indica que devuelve la cantidad de unidades de codigo y deja ver que hay una diferencia entre unidades y caracter.

### ¿Qué esperaba ver?

informacion mas coherente

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/string/length`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/length
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/string/length/index.md
* Last commit: https://github.com/mdn/translated-content/commit/3c08abe996877860f51637042d7849045ba4632d
* Document last modified: 2023-02-14T22:43:17.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! @evazquezb he leído varias veces el primer párrafo de la descripción:

```
Esta propiedad devuelve el número de caracteres de una cadena. UTF-16, el formato usado por JavaScript, usa 16-bit para representar los caracteres más comunes, pero necesita usar dos caracteres para otros menos usados, así que es posible que el valor devuelto por length no corresponda al número de caracteres de la cadena.
```

Creo que veo lo que mencionas sin embargo para el uso común de la propiedad lo veo bien, dado que lo que regresa es el número de caracteres, como coloquialmente se maneja y a su vez te explica que algunos caracteres pueden contar por dos dado la codificación UTF-16

En Inglés también lo menciona como caracteres y te dice que los que pueden contar doble son simbolos matemáticos y emoticonos.

Al final el propósito de ese párrafo es hacer notar que hay caracteres que pueden contar doble en caso de que `lenght` no regrese el número esperado.

Así mismo como menciona yarusome, el artículo está un poco desactualizado, con gusto puedes enviar un PR con tu sugerencia o la actualización completa del artículo.

Mientras dado que la confusión no es tan evidente, este issue será cerrado.

Muchas gracias por tus observaciones!
