### ISSUE TITLE
Typo (dans/sans)

### ISSUE THREAD

**Issue by Totogro** [mdn/translated-content#12543]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/HTML/Element/img

### What specific section or headline is this issue about?

no-referrer-when-downgrade

### What information was incorrect, unhelpful, or incomplete?

L'en-tête [Referer](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Referer) ne sera pas envoyé aux origines *dans* TLS/HTTPS.

### What did you expect to see?

L'en-tête [Referer](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Referer) ne sera pas envoyé aux origines ***sans*** TLS/HTTPS.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/html/element/img`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/img
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/html/element/img/index.md
* Last commit: https://github.com/mdn/translated-content/commit/51202a3dc602b2bf038724e07f6879db350acfa4
* Document last modified: 2023-03-12T21:04:19.000Z

</details>

**Comment by SphinxKnight** [comment]
@Totogro est-ce que cela vous intéresserait de proposer une édition/PR pour corriger ce problème ? :) N'hésitez pas à nous dire si vous avez besoin de guidage pour ce faire.

Merci déjà pour le signalement :)
