### ISSUE TITLE
zh-CN: Glossary discussion on "block" and "inline"

### ISSUE THREAD

**Issue by yarusome** [mdn/translated-content#12567]
此议题旨在通过讨论 CSS 术语“block”和“inline”的译法形成标准译法，同时讨论后续操作。

---

首先整理相关事件的大致时间线：

  1. HTML 4 引入了 block 元素和 inline 元素的分类概念。
  2. CSS 2 利用 HTML 4 的 block 和 inline 概念定义了用于布局的各种概念。
  3. CSS 2 之后，CSS 的各个模块继承了 CSS 2 的概念。
  4. HTML 5 废除了 block 元素和 inline 元素的概念。
  5. [CSS 书写模式模块](https://w3c.github.io/csswg-drafts/css-writing-modes/#text-flow)为 block 和 inline 概念赋予了新的内涵。

---

由于 CSS 的各个模块在描述布局时大部分用的是 block 和 inline 的概念，所以在这两者的内涵扩充之后，只需要调整少数明确使用了例如 horizontal 等词语但又需要适应不同的书写模式（writing mode）的属性或值的定义，但是这为中文译法带来了广泛存在的问题。

  1. 中文关于这两个术语及相关术语的最早译法出处已不可考，而“内联”这个译法在 CSS 领域中可能已经存在了十多年的时间。
  2. 推测 inline 译为“内联”是因为编程语言早已有此译法而直接借用，block 译为“块”属于直译。
  3. inline 在编程语言中译为“内联”确实符合“把一小段代码（最初是一行代码，即 in line）嵌入到另一段代码”的本意。
  4. inline 译为“内联”不符合 CSS 书写模式模块中的描述，同时可能暗示 `<img>` 和 `<iframe>` 等替换性元素（replaced element）。

---

我本人在初学 CSS 时觉得“块”这个译法还算将就，但是单字译法组词容易出现奇数字词，而“内联”这个译法纯属让人一头雾水，只有强行记忆。因此在之前 CSS 逻辑模块的翻译工作中，我考虑之后根据规范中的描述选择了如下译法（从上到下匹配）：

| 英文术语 | 中文译法 | 备注 |
| - | - | - |
| block end | 块末 |
| block start | 块首 |
| block-level | 块级 |
| block | 块向 |
| inline end | 行末 |
| inline start | 行首 |
| inline-level | 行级 | ~MDN 英文版尚未出现此术语。~ |
| inline | 行向 |
| end | 末；末侧 | 属性值译为“末”，行文译为“末侧”，类比 top 译为“上”或“上侧”。 |
| start | 首；首侧 | 属性值译为“首”，行文译为“首侧”。 |

样本页面：[`border-block`](https://developer.mozilla.org/zh-CN/docs/Web/CSS/border-block)

---

目前需要形成共识的有两个问题：

  1. 是否保留“内联”这个译法？
  2. 如果不保留，是采取类似上文表格中的译法还是采取其他译法？
  3. 除了在术语表中记录本议题中形成共识的译法外，已有 CSS 页面的相关内容是否需要集中更新译法？

---

另：英文版也正在进行相关概念的[迁移和清理](https://github.com/mdn/content/pull/25891)。

抄送：@fwqaaq @jasonren0403 @yin1999

**Comment by fwqaaq** [comment]
inline-level 在那个 pr 中正在更新：https://github.com/mdn/content/pull/25891/files#diff-a83a14653de4d2d75fb04a21ea3728ac4873578550b87cb55f6bc10c470998da

**Comment by jasonren0403** [comment]
感谢分享有关block和inline的历史信息，我也学到了不少内容

之所以有些人会把inline译为“行内”，我感觉确实是受到了原来代码中“行内”（in line）概念的影响。HTML引入CSS样式的方法之一也包含inline（即直接将css样式写在style属性中），这里译为“内联”应该依然准确。

我也搜了一下词典中inline的含义，它确实具有“作为正文某段的一部分**包含**（included as part of the main text on a page, rather than in a separate section）”和“含有**构成一条直线**的部分（with parts arranged in a line）”的含义。从日常使用经验来看，CSS中的inline更接近后者，它更接近于描述“一行文字的方向”（即你说的“行向”）。翻译成“内联”有些偏移了。

作为一个大型的文档项目来说，能保证各处术语的一致性是必要的，如果能修改最好横向集中修改。对于现有文档中存在的陈旧不准确的翻译也一直有人在更新。

**Comment by yin1999** [comment]
1. 赞成不再采用“内联”的译法
2. 我希望这几个翻译可以得到几位活跃贡献者的赞同
3. 有精力的话最好集中更新一次，以供新的贡献者参考

**Comment by fwqaaq** [comment]
赞成 block -> 区块，inline -> 行内

**Comment by yarusome** [comment]
@jasonren0403 我也赞同将**名词形式**的 block 译为“区块”，不过还有其他几个译法需要对照调整：

| block 相关术语 | 中文译法 | inline 相关术语 | 中文译法 |
| - | - | - | - |
| block end | 块末 | inline end | 行末 |
| block start | 块首 | inline start | 行首 |
| block-level | 块级 | inline-level | 行级 |
| block direction | 区块方向:grey_question: | inline direction | 行向:grey_question: |
| block | 【形】区块（的）:grey_question: | inline | 【形】行向（的）:grey_question: |
| block | 【名】区块 | inline | 【无名词用法】 |

**Comment by yarusome** [comment]
我发现上一条评论的问题其实在于 block 作形容词有两种含义，区分之后应该就没有什么问题了。依然按照偶数字的原则将译法提议更新如下（从上到下匹配）：

| 英文术语 | 中文译法 | 英文术语 | 中文译法 |
| - | - | - | - |
| block direction | 块向 | inline direction | 行向 |
| block end | 块末 | inline end | 行末 |
| block start | 块首 | inline start | 行首 |
| block-level | 块级 | inline-level | 行级 |
| block | 【形】块向（的）（= in the block direction） | inline | 【形】行向的（= in the inline direction） |
| block | 【形】区块（的）（= of the block） |
| block | 【名】区块 |

示例：

| 英文样本 | 中文译法 |
| - | - |
| the block and inline sizes of the block element | 区块元素的块向和行向尺寸 |
| block-formatting context | 区块格式化上下文 |

各位觉得如何？ @fwqaaq @jasonren0403 @yin1999

**Comment by fwqaaq** [comment]
有时间可以统一改了
