### ISSUE TITLE
Translate to German

### ISSUE THREAD

**Issue by DickerPeter** [mdn/translated-content#1257]
Guten Tag,

ich wollte einmal nach Fragen, wie man sich beteiligen kann.
Das eine Übersetzung ins Deutsche statt findet.

Vielen Dank

Good day,

I wanted to ask questions about how to get involved.
That a translation into German takes place.

Many Thanks

**Comment by tristantheb** [comment]
Hello,

Currently the German locale is freeze and does not yet take contributions for the translation of new pages, or the updating of existing ones. Several other locales are still freezing, but they will be unblocked little by little. We have recently welcomed the Brazilian Portuguese locale.

What I can advise you to do is to keep an eye on the Issue section until a member of yari-content-de announces recruitment of proofreaders. Once this recruitment is completed, the locale will be open to translation proposals ;)

You can follow the discussions on the translation of the mdn on the Matrix discussion server: https://chat.mozilla.org/#/room/#mdn:mozilla.org
Locales who are open to suggestions are noted here with the members who validate the translations: https://github.com/mdn/translated-content/blob/main/README.md

---

Actual unfrozen locales: `l10n-ja`, `l10n-zh`, `l10n-fr`, `l10n-ru`, `l10n-ko`, `l10n-pt-br`
Actual frozen locales: `l10n-de`, `l10n-es`, `l10n-pl`

Retired languages: https://github.com/mdn/retired-content

---

If you have questions about other things, we can answer you according to the information we have 😃 

Have a nice day ^^

**Comment by DickerPeter** [comment]
It's a shame, I always enjoyed reading something. But when it is frozen and you don't yet know when it will come again, it is also very sad.
