### ISSUE TITLE
Image tags without src

### ISSUE THREAD

**Issue by caugner** [mdn/translated-content#12579]
While testing out https://github.com/mdn/yari/pull/8571, Sentry collected the following errors regarding `<img>` tags without a `src` attribute.

## es

- [x] `In /es/docs/Web/API/Element/clientTop there's an img tag without src (<img alt="Image:clientTop.png">)`
- [x] `In /es/docs/Web/API/Element/clientLeft there's an img tag without src (<img alt="Image:clientLeft.png">)`
- [x] `In /es/docs/Web/API/Element/clientLeft there's an img tag without src (<img alt="La barra de desplazamiento vertical en el lado izquierdo, aparece cuando la propiedad layout.scrollbar.side tiene el valor 1 o 3">)`

## fr

- [x] `In /fr/docs/Mozilla/Add-ons/WebExtensions/Firefox_differentiators there's an img tag without src (<img alt="containers.png">)` https://github.com/mdn/content/pull/26242
- [ ] `In /fr/docs/Learn/Getting_started_with_the_web/HTML_basics there's an img tag without src (<img src="" alt="Mon image de test">)` https://github.com/mdn/translated-content/pull/12818

## ko

- [ ] `In /ko/docs/Web/SVG/Tutorial/SVG_and_CSS there's an img tag without src (<img alt="SVG demonstration">)`
- [ ] `In /ko/docs/Web/API/Window/toolbar there's an img tag without src (<img alt="Image:Modify_any_open_window_dialog.png">)`
- [ ] `In /ko/docs/orphaned/Web/SVG/SVG_1.1_Support_in_Firefox there's an img tag without src (<img alt="그림:그림-text-fill-stroke.png">)`

**Comment by SphinxKnight** [comment]
https://github.com/mdn/translated-content/pull/12818 has been opened for the two docs in `fr`

**Comment by alattalatta** [comment]
ko's fixed by #12488 and #12648.

**Comment by Graywolf9** [comment]
`es` attended in https://github.com/mdn/translated-content/pull/12964
