### ISSUE TITLE
Faltas de Ortografía en lenguaje Español 

### ISSUE THREAD

**Issue by vtn-hz** [mdn/translated-content#12601]
### MDN URL

https://developer.mozilla.org/es/docs/Glossary/Cross-site_scripting

### ¿De qué sección específica o titular trata este problema?

Cross-site scripting

### ¿Qué información es incorrecta, inútil o incompleta?

Cross-site scripting (XSS) es una vulnerabilidad de seguridad que permite a un atacante inyectar en un sitio web código malicioso del lado del cliente. Este código es ejecutado por las **vícitmas** y permite a los atacante eludir los controles de acceso y **hacerce** pasar por usuarios.

### ¿Qué esperaba ver?

Cross-site scripting (XSS) es una vulnerabilidad de seguridad que permite a un atacante inyectar en un sitio web código malicioso del lado del cliente. Este código es ejecutado por las víctimas y permite a los atacante eludir los controles de acceso y hacerse pasar por usuarios.

### ¿Tiene algún enlace de apoyo, referencias o citas?

- https://www.rae.es/dpd/hacer
- https://www.rae.es/dpd/v%C3%ADctima

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/glossary/cross-site_scripting`
* MDN URL: https://developer.mozilla.org/es/docs/Glossary/Cross-site_scripting
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/glossary/cross-site_scripting/index.md
* Last commit: https://github.com/mdn/translated-content/commit/848cad0c628ee81e28b89acbff4eafa957023050
* Document last modified: 2022-11-30T01:29:11.000Z

</details>

**Comment by yarusome** [comment]
Apart from the spelling issues, a curious thing is that the es version contains much more content than the en-US one.

**Comment by Graywolf9** [comment]
Hola! @vtn-hz, muchas gracias por reportar el error, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)

**Comment by vtn-hz** [comment]
Ahí envie el Pull Request de la correción
https://github.com/mdn/translated-content/pull/12831

**Comment by yarusome** [comment]
@vtn-hz You could leave this issues open until the linked PR gets merged, which would automatically close this issue then.
