### ISSUE TITLE
es: Traducción de array

### ISSUE THREAD

**Issue by frivy** [mdn/translated-content#12623]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/JavaScript/Objects/JSON

### ¿Qué información es incorrecta, inútil o incompleta?

Se utiliza la palabra "arreglo" para array. Esta es una mala traducción usada por algunos desarrolladores de un país de habla hispana. Pero en el resto del mundo se utiliza la palabra original "array", aunque la traducción correcta es vector. Se puede ver la explicación en wikipedia: https://es.wikipedia.org/wiki/Vector_(informática)

### ¿Qué esperaba ver?

Espero que la traducción sea acorde con el lenguaje usado por la mayoría de profesionales o, por lo menos, que sea correcta

### ¿Tiene algún enlace de apoyo, referencias o citas?

https://es.wikipedia.org/wiki/Vector_(informática)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/learn/javascript/objects/json`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/JavaScript/Objects/JSON
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/javascript/objects/json/index.md
* Last commit: https://github.com/mdn/translated-content/commit/fe31656ac766f2bf0b80460b432ad600b7385a5e
* Document last modified: 2022-12-05T20:09:48.000Z

</details>

**Comment by yarusome** [comment]
Related es glossary page: https://developer.mozilla.org/es/docs/Glossary/Array

**Comment by frivy** [comment]
https://developer.mozilla.org/es/docs/Glossary/Array

Esto es incorrecto
Está mal
Quien lo haya escrito es parte de esa gente que usa una palabra incorrecta
Como aclaran en Wikipediia:
https://es.wikipedia.org/wiki/Vector_(informática)
«Vector (informática)
Matriz unidimensional con 10 elementos. Nótese que empieza a contar desde
0. En programación, se le denomina vector, formación, matriz (en inglés
array, del cual surge la mala traducción arreglo)»

**Comment by yarusome** [comment]
@frivy I was trying to say that the wide spread of this word on MDN might be due to this glossary item, and if verified a massive update on es pages might be needed. cc @JuanVqz @Graywolf9 (Hope either of you is not too occupied :)

**Comment by Graywolf9** [comment]
Thank you so much for your attentions! @yarusome 

Hola! @frivy, muchas gracias por la observación, como menciona yarusome, esto podría implicar un cambio general masivo en MDN en español, por lo que necesitará un amplio dialogo al respecto dado que MDN es la base de estas definiciones para muchas personas. Mientras tanto me gustaría comentarte un par de cosas:

- A pesar de ser Wikipedia una excelente fuente de información, para MDN es más una referencia que una base de conocimiento, esta información será considerada como toda la demás que se brinde para la decisión final.
-  El español como todas las lenguas evoluciona y adquiere nuevas palabras esto basado más que nada en la cantidad de personas que las emplea, tal es el caso de palabras como "tuitear" que se han hecho oficiales por ese motivo, así mismo tenemos el uso de la palabra "arreglo" como la palabra más común para referirnos a un _array_ en la mayoría de los canales y sitios de enseñanza de habla hispana
- El equipo de MDN español esta haciendo lo posible por lograr el español más neutro posible para todos los hispano hablantes.
- Para lograr esto utilizamos las palabras más coloquialmente usadas y entendibles para todas las personas más que la que pudiera llegar a ser la palabra con el uso 100% correcto.

Una vez comentado lo anterior será un placer tenerte en nuestro canal para abordar el tema con la comunidad y si es necesario posteriormente agendar alguna reunión virtual para llegar al consenso

Telegram: https://t.me/+Dr6qKQCAepw4MjFj

Matrix: https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org

**Comment by Graywolf9** [comment]
Closed due to inactivity.
