### ISSUE TITLE
The example is not synced with the one in English document

### ISSUE THREAD

**Issue by ZenkieBear** [mdn/translated-content#12664]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/Web_Components/Using_templates_and_slots#%E5%9C%A8_web_components_%E4%B8%AD%E4%BD%BF%E7%94%A8%E6%A8%A1%E6%9D%BF

### 与此议题相关的小节或标题？

在 Web Components 中使用模板

### 哪些信息是错误、无用或不完善的？

这里的第一个示例代码存在错误，见 https://github.com/mdn/translated-content/issues/12664#issuecomment-1501716000：

```js
customElements.define('my-paragraph',
  class extends HTMLElement {
    constructor() {
      super();
      let template = document.getElementById('my-paragraph');
      let templateContent = template.content;

      const shadowRoot = this.attachShadow({mode: 'open'})
        .appendChild(templateContent.cloneNode(true));
  }
})
```

### 你期望看到什么？

或者将这里的简写拆分成两行（[英文文档](https://github.com/mdn/content/blob/2d56200e7f273405a9f97226c503787dfb020d44/files/en-us/web/web_components/using_templates_and_slots/index.md?plain=1#L49-L50)）：

```js
const shadowRoot = this.attachShadow({mode: 'open'});
shadowRoot.appendChild(templateContent.cloneNode(true));
```

### 你有什么支持的链接、参考或引用？

[关于Node.appendChild的文档](https://developer.mozilla.org/zh-CN/docs/Web/API/Node/appendChild)

### 你还想补充什么内容？

人们看到下文所述的`如果只给它添加到一个标准的 DOM 中是不起作用的。`，可能会直接给这里的`shadowRoot`添加style样式了，但是结果却是style标签没有被添加到shadowRoot中。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/web_components/using_templates_and_slots`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Web_Components/Using_templates_and_slots
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/web_components/using_templates_and_slots/index.md
* Last commit: https://github.com/mdn/translated-content/commit/6fc896599121c0b3148e71dfa7b0273f3edcd8b5
* Document last modified: 2023-04-02T00:50:20.000Z

</details>

**Comment by yin1999** [comment]
请注意，这里不是变量命名错误，而是以前的示例代码存在错误，我们需要从[英文文档](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots#using_templates_with_web_components)同步代码，而非简单的修改变量名：

```js
const shadowRoot = this.attachShadow({ mode: "open" });
shadowRoot.appendChild(templateContent.cloneNode(true));
```
