### ISSUE TITLE
Error ortográfico

### ISSUE THREAD

**Issue by SelimBltrn** [mdn/translated-content#12746]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL

### ¿De qué sección específica o titular trata este problema?

Resumen

### ¿Qué información es incorrecta, inútil o incompleta?

Texto

### ¿Qué esperaba ver?

Nada en específico

### ¿Tiene algún enlace de apoyo, referencias o citas?

Propuesta:

publicado en la web.

### ¿Tiene algo más que quiera compartir?

![image](https://user-images.githubusercontent.com/130079857/232140117-08e6775b-07dd-4079-aa14-b7451af54d39.png)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/learn/common_questions/web_mechanics/what_is_a_url`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/common_questions/web_mechanics/what_is_a_url/index.md
* Last commit: https://github.com/mdn/translated-content/commit/4702d27b1336c05bf0d65c6b3a688938c40a8657
* Document last modified: 2023-02-14T18:19:09.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! @SelimBltrn, muchas gracias por reportar el error, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)
