### ISSUE TITLE
Live sample failed! на демонстрации: should be an EmbedInteractiveSample instead

### ISSUE THREAD

**Issue by Dragomire** [mdn/translated-content#12869]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/HTML/Element/input/radio

### О какой части статьи или абзаце идёт речь?

Демонстрация

### Какая информация оказалась неверной, бесполезной или неполной?

Live sample failed!
An error occurred trying to render this live sample.
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find any live code samples for "basic_example" within /ru/docs/Web/HTML/Element/input/radio

### Как бы вы исправили?

Я не волшебник, я только учусь.

### Есть ли у вас какие-либо подтверждающие ссылки?

https://developer.mozilla.org/ru/docs/Web/HTML/Element/input/radio

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/html/element/input/radio`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTML/Element/input/radio
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/html/element/input/radio/index.md
* Last commit: https://github.com/mdn/translated-content/commit/aa64f7fe451dd264e88d7c2e36f1ccda8ca8385b
* Document last modified: 2023-03-02T11:41:04.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #16964 :ok_hand:
