### ISSUE TITLE
[ko] Discord 링크 추가

### ISSUE THREAD

**Issue by alattalatta** [mdn/translated-content#12875]
한국어는 별도 채널도 있는데, 가이드 어딘가에 docs/README.md 어딘가에 초대 링크가 있으면 좋겠어요 아마도.

> 어떻게 시작해야 할지 어려우신가요? [MDN Discord #korean 채널](https://discord.com/channels/1009925603572600863/1070064829466939503)로 오셔서 ...(어쩌구)

정도..?

**Comment by hochan222** [comment]
오! 추가하면 좋을듯합니다.
