### ISSUE TITLE
Error on link https://developer.mozilla.org/pt-BR/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest

### ISSUE THREAD

**Issue by sruinascimento** [mdn/translated-content#12950]
### MDN URL

https://developer.mozilla.org/pt-BR/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest

### What specific section or headline is this issue about?

In the section Analyzing and manipulating the responseXML property, item two of the list.

### What information was incorrect, unhelpful, or incomplete?

It is written:
Using JXON to convert it into a JavaScript Object.
And when I click on the link, I am redirected to the page:
https://developer.mozilla.org/pt-BR/docs/JXON
Which is a route that does not exist.

### What did you expect to see?

I believe the correct wording should be:
Using JSON to convert into a JavaScript Object.
And when clicking on the link, you should be redirected to this route:
https://developer.mozilla.org/pt-BR/docs/Glossary/JSON.

**Comment by yin1999** [comment]
Yes, actually we could remove this line, as this is not in english documation :)

![image](https://user-images.githubusercontent.com/15844309/233915732-bf6d7381-fadb-49f8-94c3-d557992e5660.png)
