### ISSUE TITLE
Неправильная формулировка

### ISSUE THREAD

**Issue by iviWebStudio** [mdn/translated-content#13059]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/HTML/Tables/Basics

### О какой части статьи или абзаце идёт речь?

https://developer.mozilla.org/ru/docs/Learn/HTML/Tables/Basics#%D1%81%D1%82%D0%B8%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F_%D1%81%D1%82%D0%BE%D0%BB%D0%B1%D1%86%D0%BE%D0%B2

### Какая информация оказалась неверной, бесполезной или неполной?

Мы определяем два "стилизующих столбца". Мы не применяем стиль к первому столбцу, но пустой элемент <col> ввести необходимо — иначе к первому столбцу не будет применён стиль.

### Как бы вы исправили?

Мы определяем два "стилизующих столбца". Мы не применяем стиль к первому столбцу, но пустой элемент <col> ввести необходимо — иначе стиль будет применён только к первому столбцу.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/html/tables/basics`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/HTML/Tables/Basics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/html/tables/basics/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1eabec630be7fb92c55745102a58a5cf78fc90da
* Document last modified: 2022-11-07T13:34:02.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17370 :ok_hand: 

Thank you! :+1:
