### ISSUE TITLE
Typo in the parseInt examples page

### ISSUE THREAD

**Issue by YumZax** [mdn/translated-content#13216]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/parseInt

### What specific section or headline is this issue about?

Exemples

### What information was incorrect, unhelpful, or incomplete?

parseInt("015", 10); // attention parseInt(015, 10); renvoie 13

The comment is wrong and misleading : **parseInt(015, 8); renvoie 13** would be correct

### What did you expect to see?

See previous

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/parseint`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/parseInt
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/parseint/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d5befc946d049e52a2a1b49a46cefff26617b918
* Document last modified: 2022-11-28T08:53:19.000Z

</details>

**Comment by SphinxKnight** [comment]
@YumZax je ne pense pas que ça soit correct.
Dans Firefox:
![image](https://github.com/mdn/translated-content/assets/2413436/842ffa5f-93b9-4a97-b199-40167e7f37c9)
Dans Chrome
![image](https://github.com/mdn/translated-content/assets/2413436/076fd700-9a4f-4a94-8bbc-a6071eaf631b)

Pouvez-vous préciser le problème ?

**Comment by SphinxKnight** [comment]
Je ferme ce ticket, nous pourrons le réouvrir sans problème s'il y a plus d'explications.
