### ISSUE TITLE
Issue with "교차 출처 리소스 공유 (CORS)": (short summary here please)

### ISSUE THREAD

**Issue by jhlee910609** [mdn/translated-content#1323]
MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/CORS

#### What information was incorrect, unhelpful, or incomplete?
- Translation is awkward.

#### Specific section or headline?
- search this words > 자격증명 요청 및 와일드카드(Credentialed requests and wildcards)

#### What did you expect to see?
- Korean original phase
  - credentialed request 에 응답할 때 서버는 Access-Control-Allow-Origin 헤더 "*" 와일드카드를 사용하는 대신에 반드시 에 값을 지정해야 합니다.
- english original phase
  - Credentialed requests and wildcards
When responding to a credentialed request, the server must specify an origin in the value of the Access-Control-Allow-Origin header, instead of specifying the "*" wildcard.

- This is an awkward translation. I think remove '에' after word of '반드시'. ('반드시'라는 단어 뒤에 '에'가 없거나 추가 번역이 필요해보입니다. 정확한 건 모르겠습니다.)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ko/web/http/cors`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/http/cors/index.html
* Last commit: https://github.com/mdn/translated-content/commit/52ccdf1f0a1cee3f0659ac78e81c79dae152399b
* Document last modified: 2021-06-23T00:34:06.000Z

</details>

**Comment by hochan222** [comment]
@jhlee910609  기여해주셔서 감사합니다. 좋은 하루 보내세요 :)

**Comment by jhlee910609** [comment]
@hochan222 감사합니다 :) 항상 힘써주셔서 감사합니다.
