### ISSUE TITLE
Discuss extending transferring abilities to other ("core"?) contributors

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#1324]
I'm opening this issue because of comments from @sideshowbarker and @teoli2003 when they triage issues from mdn/content which should be located under mdn/translated-content.

As I understand it, I do have such transferring privileges and I don't mind doing so (whether it's for fr or other locales), it only takes a few seconds to do (and I don't mind being ping-ed for this too :))

However, it seems to me it could be more efficient by granting @sideshowbarker / @teoli2003 or maybe even some locale team leader this privilege.

I don't know the extend of the risk which needs to be taken here (information publicly available on GitHub pages for organisations / repositories is quite sparse :/) but the doc makes it clear that in order to transfer, someone must have write access on both ends (seems a bit overkill vs the "triage" permission :s ) so it's not to be taken lightly either (though I'm pretty sure any core person of MDN can vouch for @teoli2003 and @sideshowbarker :) (if not for other more recent localizers)).

Notes:
GH doc: https://docs.github.com/en/issues/tracking-your-work-with-issues/transferring-an-issue-to-another-repository

**Comment by hochan222** [comment]
I had the same thought, but thanks for mentioning it first. Recently, `ko-locale` also had this issue and tagged yari-content-ko, but we couldn't do anything. (We had to mention SphinxKnight again.) It seems that MDN need to designate a person in charge to transfer the content issue to translated-content.

**Comment by Rumyra** [comment]
Thanks both - Moz are off this week, however I do need to re-evaluate the teams and permissions as I agree, I think more ability for contributors to move these issues is needed - I'll make a note to review this when I get back 👍

**Comment by escattone** [comment]
Thanks @SphinxKnight, @hochan222, and @Rumyra! Sorry for my delayed response. I'm still working my way through a mountain of emails. I'm totally happy with granting @sideshowbarker and @teoli2003 (and perhaps the localizing teams) `write` access to both mdn/content and mdn/translated-content. Just so they can get that power immediately, I'll add @teoli2003 and @sideshowbarker to the mdn/translated-content repo with `write` access. @Rumyra and I can work on any further changes as decided.

**Comment by escattone** [comment]
FYI, @teoli2003 and @sideshowbarker should both have (or have been invited) `write` access to mdn/content and mdn/translated-content.

**Comment by sideshowbarker** [comment]
@escattone Thanks much!

**Comment by teoli2003** [comment]
Thank you @escattone

**Comment by Rumyra** [comment]
Thanks @escattone 👍 I'm going to close this issue, purely because we'll keep everyone individually updated about further changes - if you need any more rights or if anyone's workflow still isn't quite right just let me know
