### ISSUE TITLE
broken image in "Stacking without z-index"

### ISSUE THREAD

**Issue by Elephantino** [mdn/translated-content#13282]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_without_z-index

### О какой части статьи или абзаце идёт речь?

understanding_zindex_01.png

### Какая информация оказалась неверной, бесполезной или неполной?

The understanding_zindex_01.png image is broken

### Как бы вы исправили?

understanding_zindex_01.png

### Есть ли у вас какие-либо подтверждающие ссылки?

https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_without_z-index

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/css/css_positioning/understanding_z_index/stacking_without_z-index`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Positioning/Understanding_z_index/Stacking_without_z-index
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/css_positioning/understanding_z_index/stacking_without_z-index/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f669f38f7705dfeb6ee65a791341942e1be31a88
* Document last modified: 2023-02-14T07:41:55.000Z

</details>

**Comment by Elephantino** [comment]
understanding_zindex_01.png

**Comment by leon-win** [comment]
Fixed :ok_hand:

**Comment by Elephantino** [comment]
I am glad to help :)
