### ISSUE TITLE
Нерабочая ссылка на странице

### ISSUE THREAD

**Issue by viamo-sl** [mdn/translated-content#13334]
### MDN URL

https://developer.mozilla.org/ru/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension

### О какой части статьи или абзаце идёт речь?

applications является обязательным для Firefox, и определяет ID дополнения. Он так же может использоваться для указания минимальной и максимальной версии Firefox, поддерживаемой расширением.

### Какая информация оказалась неверной, бесполезной или неполной?

[applications](https://developer.mozilla.org/ru/docs/Mozilla/Add-ons/WebExtensions/manifest.json/applications)

### Как бы вы исправили?

Исправить ссылку

### Есть ли у вас какие-либо подтверждающие ссылки?

Page not found

Sorry, the page /ru/docs/Mozilla/Add-ons/WebExtensions/manifest.json/applications could not be found.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/mozilla/add-ons/webextensions/your_first_webextension`
* MDN URL: https://developer.mozilla.org/ru/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/mozilla/add-ons/webextensions/your_first_webextension/index.md
* Last commit: https://github.com/mdn/translated-content/commit/672e2fd5a624919c44a1797fbeee5c55ce0b0aa5
* Document last modified: 2022-10-28T14:37:03.000Z

</details>

**Comment by leon-win** [comment]
Создал #16829, хотел сначала просто исправить ссылки (первый коммит), но потом решил, что можно актуализировать и перевод всей страницы))

**Comment by viamo-sl** [comment]
Not working yet! https://developer.mozilla.org/ru/docs/Mozilla/Add-ons/WebExtensions/manifest.json/applications
![2023-12-11_154738](https://github.com/mdn/translated-content/assets/133008458/ec1a766b-1605-4238-8a60-01bb09f97050)
![2023-12-11_154743](https://github.com/mdn/translated-content/assets/133008458/8806af8b-4951-4b3a-8547-07c551d0ae8c)

**Comment by leon-win** [comment]
> Not working yet!

The site is not updated as quickly. Be patient and check tomorrow.
