### ISSUE TITLE
es: Update looping_code

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#13379]
Update english content on looping_code page (https://developer.mozilla.org/es/docs/learn/javascript/building_blocks/looping_code)

**Comment by JuanVqz** [comment]
pinging @ale94lko

**Comment by ale94lko** [comment]
@JuanVqz asignamelo

**Comment by JuanVqz** [comment]
cualquier duda, pregunta, aclaración por aquí estaremos...

**Comment by Graywolf9** [comment]
Hola! @ale94lko espero te encuentres muy bien, ¿hay alguna novedad sobre este issue?

**Comment by ale94lko** [comment]
Hola @Graywolf9, he avanzado pero todavía me falta bastante, casi todo el contenido está desactualizado con respecto a la versión en inglés

**Comment by Graywolf9** [comment]
Wow muchas gracias por responder que bueno saber de ti, tomate tu tiempo y muchas gracias!

**Comment by Graywolf9** [comment]
Hola! @ale94lko espero te encuentres muy bien y recibas mis más cordiales saludos, debido a la duración de este issue he realizado la actualización (https://github.com/mdn/translated-content/pull/16719), una disculpa por los inconvenientes que esto pueda ocasionar, muchas gracias por todo tu tiempo y apoyo

Siéntente libre de seguir ayudando cuando puedas en lo que te sea posible.

Excelente día!
