### ISSUE TITLE
positioned の訳語のゆれ

### ISSUE THREAD

**Issue by shinmili** [mdn/translated-content#13419]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/CSS/position

### この問題に関する節や見出しはどこですか。

値 (absolute)

### 不完全、不親切、不完全であった情報は何ですか。

原文: 

> [...] It is [positioned](https://developer.mozilla.org/en-US/docs/Web/CSS/position#types_of_positioning) relative to its closest positioned ancestor, if any; [...]

現在の訳:

> [...] 直近の配置されている祖先があれば、それに対して相対配置されます。[...]

原文 3 語目の "positioned" は、原語版のリンクが示す通り、同ページの[位置の種類](https://developer.mozilla.org/ja/docs/Web/CSS/position#types_of_positioning)中で定義される「位置指定要素 (positioned element)」のことを指しています。「位置の種類」セクションでは "positioned" を「位置指定」と訳していますが、上記の「値」セクション `absolute` の説明文中では「配置されている」と異なる訳語が使用されており、これらが同一の概念を指していることが分かりづらくなってしまっています。

### どう表示されるべきだと思いますか。

少なくとも "positioned" の訳は「位置指定」に統一すべきであると思います:

> [...] 直近の[位置指定](https://developer.mozilla.org/ja/docs/Web/CSS/position#types_of_positioning)祖先があれば、それに対して相対配置されます。[...]

もうちょっとこなれた日本語にしてもよいかもしれません:

> [...] 祖先に[位置指定要素](https://developer.mozilla.org/ja/docs/Web/CSS/position#types_of_positioning)があれば、そのような要素のうち直近のものに対して相対配置されます。[...]

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/css/position`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/position
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/position/index.md
* Last commit: https://github.com/mdn/translated-content/commit/5d3e7683e319a31262d168e2b05b9ebc87ddfc33
* Document last modified: 2022-09-28T14:06:13.000Z

</details>

**Comment by mfuji09** [comment]
完了しているようなので、クローズします。
