### ISSUE TITLE
错误

### ISSUE THREAD

**Issue by TheZhuKing** [mdn/translated-content#13413]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Classes_in_JavaScript

### 哪些信息是错误、无用或不完善的？

class 中的 #name 外部可以访问

### 你期望看到什么？

1

### 你有什么支持的链接、参考或引用？

1

### 你还想补充什么内容？

1

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/objects/classes_in_javascript`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Classes_in_JavaScript
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/objects/classes_in_javascript/index.md
* Last commit: https://github.com/mdn/translated-content/commit/feda4c4f9eee59abc0ca21360dd07d58c9b571e7
* Document last modified: 2023-02-21T11:18:22.000Z

</details>

**Comment by skyclouds2001** [comment]
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Classes_in_JavaScript

**Comment by yin1999** [comment]
请指出具体的问题，文档中的示例并未将 `name` 属性设置为私有属性，所以该属性当然可以在类的成员函数以外的作用域中访问。我并未在当前文档中搜索到任何有关“`#name` 不能在外部访问”的描述。该文档仅将 `year` 设置为了私有属性，该属性的确不能在类的成员函数作用域外访问。若还有其他疑问，请详细说明相关内容（以及相关内容具体在哪个小节）
