### ISSUE TITLE
Texte incomplet

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#13468]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/background-origin

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

Dans "Définition formelle"/"Type d'animation" il est écrit "une liste répétable de".
Une liste de quoi ?

https://developer.mozilla.org/en-US/docs/Web/CSS/background-origin
La situation est la meme dans la page en-us: "Formal definition"/"Animation type" il est écrit "a repeatable list of"
A list of what?

### What did you expect to see?

compléter la phrase

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/background-origin`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/background-origin
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/background-origin/index.md
* Last commit: https://github.com/mdn/translated-content/commit/79faa1509d68be77f14971a843e43da59dedff2f
* Document last modified: 2022-09-21T09:43:31.000Z

</details>

**Comment by SphinxKnight** [comment]
A fix is intended in https://github.com/mdn/data/pull/671

**Comment by SphinxKnight** [comment]
we should wait a few days before it lands I think :)

**Comment by SphinxKnight** [comment]
Le texte a été modifié et légèrement amélioré.
