### ISSUE TITLE
Sync translation of Heading_elements page with English version

### ISSUE THREAD

**Issue by myshov** [mdn/translated-content#13480]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/HTML/Element/Heading_Elements

### What information was incorrect, unhelpful, or incomplete?

The translation of the page should be syncronized with English version

### What did you expect to see?

Updated version of the article

**Comment by leon-win** [comment]
Done in #17433 :ok_hand: 

Thank you! :+1:
