### ISSUE TITLE
Page titles translation in learn area  (by themselves and sidebar)

### ISSUE THREAD

**Issue by mpstv** [mdn/translated-content#1352]
Ишью создано как часть https://github.com/mdn/translated-content/issues/796 и касается проблемы:
>https://developer.mozilla.org/ru/docs/Learn и др. подстраницы:
В боковой панели навигации <nav id="sidebar-quicklinks" class="sidebar"> у многих уже переведенных статей остались английские заголовки

В сайдбаре на странице https://developer.mozilla.org/ru/docs/Learn необходимо перевести названия ссылкок для которых уже есть русскоязычные версии статей.

1. Название ссылки должно совпадать с заголовком страницы.
2. Для некоторых ссылок и заголовков страниц нужно обновить перевод. Например, встречается такой заголовок страницы как `Стилизирование текста`, который лучше изменить на `Стилизация текста`. Так же встречается перевод `Css layout` -> `Css верстка`, тогда как, согласно [словарю веб-стандартов](https://github.com/web-standards-ru/dictionary), `layout` лучше переводить как `раскладка`.
3. Сайдбар встраивается с помощью максроса. Для перевода ссылок нужно внести изменения в 
https://github.com/mdn/yari/blob/a5f3c4775ffaa100ecbcfedc1b825061d58a05f3/kumascript/macros/LearnSidebar.ejs#L785 (как было указано в https://github.com/mdn/translated-content/issues/796#issuecomment-871557452)

Ишью будет закрыто после того, как будут влиты 2 пулреквеста:
1. PR в этот репозитоий, актуализирующий переводы заголовков страниц из `ru/learn`
2. PR в репозиторий https://github.com/mdn/yari обновляющий переводы ссылок в сайдбаре.

**Comment by MaximP2014** [comment]
Точнее даже отсюда https://github.com/mdn/yari/blob/a5f3c4775ffaa100ecbcfedc1b825061d58a05f3/kumascript/macros/LearnSidebar.ejs#L818 :
`'CSS_first_steps': 'CSS first steps'`
поменять на
`'CSS_first_steps': 'Введение в CSS'`
и т. д.

**Comment by Ganzeroar** [comment]
Беру эту ишью

**Comment by Ganzeroar** [comment]
@mpstv Согласно словарю: embedded content — внедряемое содержимое. Я правильно понимаю, что статью <a href="https://developer.mozilla.org/ru/docs/Learn/HTML/Multimedia_and_embedding">"Мультимедиа и встраивание"</a> следует переименовать в "Мультимедиа и внедрение"?

**Comment by mpstv** [comment]
@Ganzeroar  `Мультимедиа и внедрение` как-то странно звучит) 

Мне кажется, что в данном случае стоит использовать перевод `embedding` -> `встраивание`.

**Comment by MaximP2014** [comment]
> `внедрение` как-то странно звучит)

В кн. Роббинс, Д. HTML5: Карманный справочник, 5-е изд. "Диалектика", 2020 категория [Embedded content](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#embedded_content) переводится как "_Внедренный_ контент".
Но Google считает, что "**встроенный** контент" используется гораздо чаще.

**Comment by Ganzeroar** [comment]
Вопрос с переводом "CSS building blocks". Раздел до этого называется "CSS first steps", и мне кажется не очень логично переводить следующий раздел как "CSS построение блоков". Может быть "CSS продвинутый уровень"? Потому что в этом разделе освящаются многие темы, а не только блоки.

**Comment by MaximP2014** [comment]
> Вопрос с переводом "CSS building blocks"...

Текущий вариант: "_Устройство_ CSS" - не перевод, а толкование.
"**Построение блоков** CSS" - самый точный перевод. 
В конце концов, MDN - это же документация, а не беллетристика.

**Comment by mpstv** [comment]
Статьи с названием `building blocks` есть не только в разделе по CSS, но в разделе по JavaScript и HTML. Для JavaScript есть перевод на русский https://developer.mozilla.org/ru/docs/Learn/JavaScript/Building_blocks , где `building blocks` переводят как `структурные элементы`. Мне кажется, это хороший вариант потому, что тут имеется ввиду не `построение блоков`, а `строительные блоки` - то есть основные или структурные элементы. 

Предлагаю и дальше использовать перевод `building blocks` -> `структурные элементы`.

**Comment by MaximP2014** [comment]
> `building blocks` -> `структурные элементы`

👍️

**Comment by sashasushko** [comment]
@mpstv подскажи статус ишьи, пожалуйста.

**Comment by mpstv** [comment]
@sashasushko 

Сложно точно сказать. Одно ясно наверняка — работа до конца не доведена.

В translated-content исправления вливалась маленькими пулреквестами, поэтому в каком состоянии заголовки стетей будет понять тяжело.

Есть один большой [пулреквест](https://github.com/mdn/yari/pull/4204/files) в репозиторий yari. Наверно, по нему будет проще разобраться на каком этапе находится работа.

**Comment by sashasushko** [comment]
Solved
