### ISSUE TITLE
MDN reduceRight() content issue

### ISSUE THREAD

**Issue by GeraltursW** [mdn/translated-content#13522]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/reduceRight

### What specific section or headline is this issue about?

Array.prototype.reduceRight()

### What information was incorrect, unhelpful, or incomplete?

![MDN issue](https://github.com/mdn/translated-content/assets/90558670/34f66ab0-24df-4e93-804c-b8034e07dbef)

The function name of reduceRight() seems to be wrong. There is an extra e in the function of reduceRight().

### What did you expect to see?

It should be reduceRight().

**Comment by yin1999** [comment]
Thanks for reporting this @GeraltursW, I've created #13523 to fix this ;)
