### ISSUE TITLE
Некорректно сформулирован п.7 в последнем задании, HTML5 по умолчанию не поддерживает атрибут border для столбца

### ISSUE THREAD

**Issue by Barister** [mdn/translated-content#13581]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/HTML/Tables/Basics

### Какая информация оказалась неверной, бесполезной или неполной?

В последнем задании пункт 7 в настоящее время не корректен.
"7.Добавьте другой цвет фона и границу для шестого столбца, чтобы показать, что это особый день и она ведёт новый класс. Значениями атрибута style будут: background-color:#DCC48E; border:4px solid #C1437A;"

Насколько я понял, HTML5 не поддерживает второй атрибут, устанавливающий границу для столбца.
Границы столбца, несмотря на прописанный атрибут, не видно.

https://github.com/mdn/learning-area/issues/219

### Как бы вы исправили?

"7.Добавьте другой цвет фона для шестого столбца, чтобы показать, что это особый день, и она ведёт новый класс. Значением атрибута style будет: background-color:#DCC48E; "

### Есть ли у вас какие-либо подтверждающие ссылки?

https://github.com/mdn/learning-area/issues/219

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/html/tables/basics`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/HTML/Tables/Basics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/html/tables/basics/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1eabec630be7fb92c55745102a58a5cf78fc90da
* Document last modified: 2022-11-07T13:34:02.000Z

</details>

**Comment by leon-win** [comment]
Привет! Я посмотрел описываемую проблему. Но всё правильно ведь работает, есть пример с реализацией: https://mdn.github.io/learning-area/html/tables/basic/timetable-fixed.html

![image](https://github.com/mdn/translated-content/assets/1682136/866e7d39-d462-4fca-9d69-bac8bfd9d350)

У шестого столбца другой фон и граница вокруг. Так что думаю задачу можно закрыть =)
