### ISSUE TITLE
typo in ja/docs/Web/HTML/Element/ul

### ISSUE THREAD

**Issue by KisaragiEffective** [mdn/translated-content#136]
in https://developer.mozilla.org/ja/docs/Web/HTML/Element/ul, 

> この論理属性は、コンパクトなスタイルでリストを秒がするようブラウザーに指示するものです。

should be

> この論理属性は、コンパクトなスタイルでリストを描画するようブラウザーに指示するものです。

**Comment by potappo** [comment]
@KisaragiEffective  ありがとうございました。
