### ISSUE TITLE
About String.split regexp compatibility description?(关于String.split正则兼容性问题的描述)

### ISSUE THREAD

**Issue by AXiLiYa** [mdn/translated-content#13602]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/split

### 与此议题相关的小节或标题？

描述/description

### 哪些信息是错误、无用或不完善的？

文档的“描述”一节中有这么一段关于正则表示式的内容：

> 如果分隔符是包含捕获括号的正则表达式，则每次分隔符匹配时，捕获括号的结果（包括任何未定义的结果）将被拼接到输出数组中。但是，并不是所有浏览器都支持此功能。

我注意到“并不是所有浏览器都支持此功能”，但我不太清楚“此功能”具体指的是什么，是“使用正则表达式作为分隔符”，还是指“将捕获括号的结果拼接到输出数组”；

另外我查看了英文的文档，似乎没有找到对应的内容；

The description section in document has a fragment about regexp: 

> 如果分隔符是包含捕获括号的正则表达式，则每次分隔符匹配时，捕获括号的结果（包括任何未定义的结果）将被拼接到输出数组中。但是，并不是所有浏览器都支持此功能。

I notice "is not all browsers support this feature". I cannot understand about "this feature". It is "use regexp as separator" or "the captured groups are spliced into the output array".

And I read the en-US document, it seems has this content.

### 你期望看到什么？

明确此处的兼容性问题是什么

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/string/split`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/split
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/string/split/index.md
* Last commit: https://github.com/mdn/translated-content/commit/523ca6e8c3eefc50fdbf2209a5e6b6de9ccf4ebc
* Document last modified: 2022-10-01T03:20:40.000Z

</details>

**Comment by yin1999** [comment]
是的，这部分内容已从英文文档中移除。现代浏览器应该不存在这里提到的兼容性问题。https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol/split
