### ISSUE TITLE
link to ad content found in the document

### ISSUE THREAD

**Issue by cuahai** [mdn/translated-content#13640]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/Common_questions/Web_mechanics/What_is_a_web_server

### 与此议题相关的小节或标题？

通过http交流

### 哪些信息是错误、无用或不完善的？

本节最后一个”404错误界面“的演示网址不规范！里面存在广告！(The link(`http://www.404notfound.fr/`) in 'Communicating through HTTP' is pointing to to unrelated content that is not suitable for MDN)

### 你期望看到什么？

一个正规的，适合放在这种严肃教学文档中的演示网址

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/common_questions/web_mechanics/what_is_a_web_server`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Common_questions/Web_mechanics/What_is_a_web_server
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/common_questions/web_mechanics/what_is_a_web_server/index.md
* Last commit: https://github.com/mdn/translated-content/commit/e55d66e1e93f1682d87cc740f5b70363f90548b3
* Document last modified: 2023-02-09T02:32:00.000Z

</details>

**Comment by jasonren0403** [comment]
感谢指出，文章没能跟上英语原版，会尽快更新

**Comment by jasonren0403** [comment]
After a simple check, found that l10n-fr/l10n-ko/l10n-ru/l10n-pt-br/l10n-zh-tw also have this problem, expanding it toward these document

**Comment by yin1999** [comment]
色情内容来自域名托管商的网页，并非网站本身的内容。我将从描述中移除相关的内容。
