### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by Mehrm0** [mdn/translated-content#13669]
### MDN URL

https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data

### What specific section or headline is this issue about?

https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data#une_requ%C3%AAte_ajax_basique

### What information was incorrect, unhelpful, or incomplete?

The [source file](https://github.com/mdn/learning-area/blob/main/javascript/apis/fetching-data/ajax-start.html) of the example does not exist. It leads to *404 page not found* error. 

### What did you expect to see?

The ajax-start.html file.

**Comment by SphinxKnight** [comment]
@Mehrm0 I think it has been fixed with https://github.com/mdn/translated-content/pull/14772

My apologies for
- having seen #13978 before this one, though it was filed before.
- replying late here :( 

Thanks a lot for reporting though!
