### ISSUE TITLE
zh-CN: 学习 Web 开发/Web API接口参考/IndexedDB/使用IndexedDB一处翻译表述有误

### ISSUE THREAD

**Issue by zizxzy** [mdn/translated-content#13717]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/IndexedDB_API/Using_IndexedDB

### 与此议题相关的小节或标题？

使用索引

### 哪些信息是错误、无用或不完善的？

概述：在索引的openKeyCursor方法的success事件中，cursor.value是没有值的，这里cursor.value表述为有值。
###  问题1
在[学习 Web 开发/Web API接口参考/IndexedDB/使用IndexedDB-使用索引](https://developer.mozilla.org/zh-CN/docs/Web/API/IndexedDB_API/Using_IndexedDB#%E4%BD%BF%E7%94%A8%E7%B4%A2%E5%BC%95)的这一节中，列举了一个在索引上使用openKeyCursor的例子，在该例子的注释中，描述游标对象 cursor.value是能够拿到值。`// cursor.key 是一个 name，就像 "Bill", 然后 cursor.value 是那个 SSN。`
而经过尝试，实际上在openKeyCursor的success事件中，游标对象的value是没有值的。同时，[使用键游标](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openKeyCursor#examples)中的例子也是将cursor.value描述为没有值。

### 你期望看到什么？

修改上述翻译
`// cursor.key 是一个 name，就像 "Bill", 然后 cursor.value 是没有值的。`

### 你有什么支持的链接、参考或引用？

[使用键游标](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/openKeyCursor#examples)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/indexeddb_api/using_indexeddb`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/IndexedDB_API/Using_IndexedDB
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/indexeddb_api/using_indexeddb/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f8df8966a905f3bdd7f1bdb8942ab8c298f8797c
* Document last modified: 2023-05-16T09:25:56.000Z

</details>

**Comment by yin1999** [comment]
Thanks for reporting this. I'd like to working on it :)
