### ISSUE TITLE
Les exemples ne fonctionnent pas

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#13716]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/border-image-width

### What specific section or headline is this issue about?

https://developer.mozilla.org/fr/docs/Web/CSS/border-image-width#exemples

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

Les exemples ne fonctionnent pas sur les pages fr et en-us

### What did you expect to see?

Corriger les exemples

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/border-image-width`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/border-image-width
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/border-image-width/index.md
* Last commit: https://github.com/mdn/translated-content/commit/79faa1509d68be77f14971a843e43da59dedff2f
* Document last modified: 2022-09-21T09:43:31.000Z

</details>

**Comment by yin1999** [comment]
Fixed by: mdn/yari#7917.
