### ISSUE TITLE
L'exemple ne fonctionne pas

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#13712]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/border-image-repeat

### What specific section or headline is this issue about?

https://developer.mozilla.org/fr/docs/Web/CSS/border-image-repeat#exemples

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

L'exemple ne fonctionne pas contrairement à la page en-us

### What did you expect to see?

Que l'exemple fonctionne

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/border-image-repeat`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/border-image-repeat
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/border-image-repeat/index.md
* Last commit: https://github.com/mdn/translated-content/commit/79faa1509d68be77f14971a843e43da59dedff2f
* Document last modified: 2022-09-21T09:43:31.000Z

</details>

**Comment by yin1999** [comment]
This issue has been fixed by: mdn/yari#7917 (I think this is about the broken images in live sample :) )
