### ISSUE TITLE
zh-CN: Proofreading and update plan for the JavaScript `Promise` section

### ISSUE THREAD

**Issue by JasonLamv-t** [mdn/translated-content#13733]
I plan to proofread and update the translation of the `Javascript.Promise` section. Anyone is welcome to contribute. If you find any issues with the Simplified Chinese Promise section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

- [x] overview, in #13809.
- [x] constructor, in #13952.
- [x] @@species, in #13767.
- [x] all, in #13841.
- [x] allsettled, in #13871.
- [x] any, in #13872.
- [x] catch, in #13974.
- [x] finally, in #13976, thank to @robert-jx.
- [x] race, in #13904.
- [x] reject, in #13937.
- [x] resolve, in #13936.
- [x] then, in #13963.

**Comment by yin1999** [comment]
Seems all the tasks are done. Thanks @JasonLamv-t :tada:
