### ISSUE TITLE
Except for en-US and Korean, the screenshot of "window.confirm" example cannot be displayed in other languages.

### ISSUE THREAD

**Issue by rubickecho** [mdn/translated-content#13734]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Window/confirm

### What specific section or headline is this issue about?

Window.confirm()

### What information was incorrect, unhelpful, or incomplete?

The examples screenshot did not display.

![image](https://github.com/mdn/translated-content/assets/14804014/24e3f400-d71b-4c04-91b2-14f0eac87bc6)

### What did you expect to see?

like en-US

![image](https://github.com/mdn/translated-content/assets/14804014/4f4e4e70-a82c-4fbb-a4c4-a29cd43fa520)

**Comment by jasonren0403** [comment]
Thank you, I would deal with zh-CN document with an update 👍

**Comment by Graywolf9** [comment]
Thank you `es` should be done by https://github.com/mdn/translated-content/pull/13750
