### ISSUE TITLE
Point de fin de ligne

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#13818]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/direction

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

Lors de l'affichage le point de fin de ligne du source:
- se retrouve en début de ligne (affichage pleine page)
- en début de 2ème ligne (affichage niveau inf.)

![Direction1 Capture](https://github.com/mdn/translated-content/assets/95876663/68dc8490-7a83-4c07-a53c-d2ea7c2bd687)
![Direction2 Capture](https://github.com/mdn/translated-content/assets/95876663/774488f1-f650-413d-97f1-8c2057b09470)

Il en est également ainsi sur les pages fr et en-us.

### What did you expect to see?

Le point de fin de ligne affiché en fin de ligne.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/direction`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/direction
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/direction/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f66954d9bcc9f94b8dab0ba5452395282c5372cd
* Document last modified: 2022-10-01T14:10:29.000Z

</details>

**Comment by SphinxKnight** [comment]
Bonjour,

Tel que je le comprends, c'est la présentation attendue pour une écriture de droite à gauche. On obtient (par exemple) le même effet sur un paragraphe en français pour lequel on aurait utilisé `dir="rtl"`. C'est aussi pour cette raison que l'article anglais fonctionne de la même façon.
![image](https://github.com/mdn/translated-content/assets/2413436/c85ba1a3-e852-41ce-917d-5b9bb52abd6f)

J'essaie de trouver une ressource didactique sur le sujet mais vais fermer ce ticket pour le moment.
