### ISSUE TITLE
There is a link here that does not lead to an existing destination in HTML/Element/script

### ISSUE THREAD

**Issue by chineicho** [mdn/translated-content#13873]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/HTML/Element/script

### この問題に関する節や見出しはどこですか。

See also

### 不完全、不親切、不完全であった情報は何ですか。

In this page in ja 、there is a link '[Ryan Grove's <script> and <link> node event compatibility chart](https://pie.gd/test/script-link-events/)' at See also section (日本語では：関連情報)。
But that link is no active. When accessing that link, it will show the error message 'The page you are looking for isn't here'。

### どう表示されるべきだと思いますか。

may be Same to The page in English, delete the problem link.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/html/element/script`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/HTML/Element/script
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/html/element/script/index.md
* Last commit: https://github.com/mdn/translated-content/commit/3f2426bdc3aecd3fbb06fcb9d50b8a4d06804324
* Document last modified: 2023-05-10T15:06:33.000Z

</details>

**Comment by YujiSoftware** [comment]
Already fixed in 5c496d5e85654a43e0a6d66ee9d0eb7cd3d1156e by @mfuji09.

**Comment by mfuji09** [comment]
Close this issue because it is already resolved.
