### ISSUE TITLE
Symbol#valueOf has inaccurate description of coercion

### ISSUE THREAD

**Issue by Hangggggg** [mdn/translated-content#13941]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol/valueOf

### What specific section or headline is this issue about?

描述

### What information was incorrect, unhelpful, or incomplete?

Object(Symbol("foo")) + "bar";
// TypeError: can't convert symbol object to primitive
// 无法隐式的调用 valueOf() 方法

### What did you expect to see?

It should be changed to
Object(Symbol("foo")) + "bar";
// TypeError: Cannot convert a Symbol value to a string
// 无法隐式的调用 toString() 方法

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mdn/community/issues`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Symbol/valueOf
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/symbol/valueof/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b56ca4857015331cde16aee6c301f12011a4ffa9
* Document last modified: 2023-02-26T18:54:50.000Z

</details>

**Comment by yin1999** [comment]
Hey @Josh-Cena, sorry to bother you. I'm not sure if we can update the zh-CN page now as it's been a long time since this issue was opened.

**Comment by Josh-Cena** [comment]
It's still on my todo list to update the en-US content. Currently it's still blocked.
