### ISSUE TITLE
Syntaxe Error: could not find syntax for this item

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#13942]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/:only-of-type#syntaxe

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

Il y a une erreur d'affichage du paragraphe syntaxe sur plusieurs pages. Par exemple ;
https://developer.mozilla.org/fr/docs/Web/CSS/:only-of-type#syntaxe
https://developer.mozilla.org/fr/docs/Web/CSS/:is#syntaxe
https://developer.mozilla.org/fr/docs/Web/CSS/:where#syntaxe
https://developer.mozilla.org/fr/docs/Web/CSS/:scope#syntaxe

### What did you expect to see?

L'affichage du paragraphe "Syntaxe"

**Comment by SphinxKnight** [comment]
@DomOBU thanks for the report indeed. I've created #14471 to fix the pages you mentioned, except for Web/CSS/gradient/repeating-linear-gradient which has the issue on en-US as well. I'll file an issue over on mdn/content to convey this so that it can be fixed upstream.

**Comment by SphinxKnight** [comment]
https://github.com/mdn/content/issues/18780 already exists
