### ISSUE TITLE
Tipo in ESP doc

### ISSUE THREAD

**Issue by yzeballos** [mdn/translated-content#13955]
### MDN URL

https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Cookie

### ¿Qué información es incorrecta, inútil o incompleta?

<nombre-de-cookie=<valor-de-cookie>
Should be // debe ser:
<nombre-de-cookie>=<valor-de-cookie>

### ¿Qué esperaba ver?

<nombre-de-cookie=<valor-de-cookie>
Should be // debe ser:
<nombre-de-cookie>=<valor-de-cookie>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/http/headers/cookie`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTTP/Headers/Cookie
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/http/headers/cookie/index.md
* Last commit: https://github.com/mdn/translated-content/commit/df7821afcfc03d67510c6f8d3b055201f88b4121
* Document last modified: 2023-02-23T19:23:45.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! muchas gracias por reportar el error, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)
