### ISSUE TITLE
移动端无障碍中对IOS操作的更改

### ISSUE THREAD

**Issue by xiaoxiaoxiaoxiaowu** [mdn/translated-content#13979]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/Accessibility/Mobile

### 与此议题相关的小节或标题？

iOS VoiceOver

### 哪些信息是错误、无用或不完善的？

VoiceOver和IOS VoiceOver

### 你期望看到什么？

旁白模式、旁白

### 你有什么支持的链接、参考或引用？

https://support.apple.com/zh-cn/guide/iphone/iph3e2e415f/ios

### 你还想补充什么内容？

标题因该是叫做IOS 旁白模式，并且，希望能加上apple官方的教程链接（上面的支持链接），且将内容中的VoiceOver翻译成旁白即可

**Comment by yin1999** [comment]
Hi @xiaoxiaoxiaoxiaowu, the document has given the steps to enabling "VoiceOver", and this may need [upstream changes](https://github.com/mdn/content/blob/main/files/en-us/learn/accessibility/mobile/index.md). So I would only translate the term "VoiceOver" in #13984. Thanks for reporting this :)
