### ISSUE TITLE
Incorrect Japanese translation in the JS Remainder operator

### ISSUE THREAD

**Issue by mfuji09** [mdn/translated-content#140]
MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Remainder

**What information was incorrect, unhelpful, or incomplete?**

A sentence in the first praragraph has been translated incorrectly.

The original sentence:

> It always takes the sign of the dividend.

Current:

> これは常に配当のサインを取ります。

This Japanese sentence means "This always takes the signature of the dividend (of a stock)."
(Maybe it was translated using a machine translation.)

**Specific section or headline?**

The second sentence in the first paragraph.

**What did you expect to see?**

これは常に被除数の符号を取ります。

I reported this issue as a reminder, until Japanese translation can be edited.

**Comment by SphinxKnight** [comment]
@mfuji09 hello, I've moved this one over translated-content. Sadly, the link from https://github.com/mdn/translated-content/pull/112 has been lost during the process.

Since the PR has been merged, I think this can be merge. Are you ok with that?

**Comment by mfuji09** [comment]
@SphinxKnight Thank you! I also think here is the best place for this issue.
This issue can be closed, but I am waiting for the result of merge is reflected to the website.

**Comment by SphinxKnight** [comment]
@mfuji09 I'm unsure if this can be of any help and since this is quite new, I wanted to share https://whatsdeployed.io/s/16d/mdn/translated-content to check if commits are in production or not yet.

**Comment by mfuji09** [comment]
@SphinxKnight Oh, thank you! It is very useful.
And I have confirmed that the changes have been reflected on the website!
