### ISSUE TITLE
有个翻译错误

### ISSUE THREAD

**Issue by Oykkkkkc** [mdn/translated-content#14020]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Building_blocks/conditionals

### 与此议题相关的小节或标题？

javascript基础件/在代码中做决定-条件语句/切换语句

### 哪些信息是错误、无用或不完善的？

关键字switch, 后跟一组逗号。

### 你期望看到什么？

关键词switch，后跟一组括号

### 你有什么支持的链接、参考或引用？

无

### 你还想补充什么内容？

无

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/building_blocks/conditionals`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Building_blocks/conditionals
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/building_blocks/conditionals/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f71143259822bffa3f7250c45e2dd7d701fcaa90
* Document last modified: 2023-04-07T16:02:55.000Z

</details>

**Comment by yin1999** [comment]
Hi @Oykkkkkc. I could not find the descripted typo in this document (so I'm going to close this issue). Could you upload a screenshort or provide the line number of it in [source code](https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/building_blocks/conditionals/index.md?plain=1). I'd like to take the feedback and happy to reopen this when we can confirm that :)

![image](https://github.com/mdn/translated-content/assets/15844309/a74bcdd0-8012-40f6-8f26-035b132168cb)

**Comment by Oykkkkkc** [comment]
Thank you for your reply.
&nbsp;I checked it again and found that it was the error of Google automatic Translation. Google Translate translated the page that was already in Chinese again and showed the original parentheses as commas. I'm really sorry for the trouble





kc
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mdn/translated-content"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月3日(星期一) 晚上10:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mdn/translated-content] 有个翻译错误 (Issue #14020)





 
Hi @Oykkkkkc. I could not find the descripted typo in this document (so I'm going to close this issue). Could you upload a screenshort or provide the line number of it in source code. I'd like to take the feedback and happy to reopen this when we can confirm that :)
