### ISSUE TITLE
Неправильный флаг и ссылка на странице Cache

### ISSUE THREAD

**Issue by rustam-mukhametshin** [mdn/translated-content#14028]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/API/Cache

### О какой части статьи или абзаце идёт речь?

Experimental flag

### Какая информация оказалась неверной, бесполезной или неполной?

Этого нет в en версии и также это ведет на неправильную ссылку.

```
Экспериментальная возможность: Это экспериментальная технология
Так как спецификация этой технологии ещё не стабилизировалась, смотрите [таблицу совместимости](https://developer.mozilla.org/ru/docs/Web/API/Cache#browser_compatibility) по поводу использования в различных браузерах. Также заметьте, что синтаксис и поведение экспериментальной технологии может измениться в будущих версиях браузеров, вслед за изменениями спецификации.
```

### Как бы вы исправили?

Просто убрать как в en версии

### Есть ли у вас какие-либо подтверждающие ссылки?

https://developer.mozilla.org/en-US/docs/Web/API/Cache

### Хотите добавить что-то ещё?

Dropdown EN to RU and back.

**Comment by sashasushko** [comment]
Close in https://github.com/mdn/translated-content/pull/14029
