### ISSUE TITLE
:link fonctionne-t-il avec Firefox ?

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#14034]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/:link

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

J'ai exécuté les exemples de ce sujet.

Je constate que `:link` ne semble pas fonctionner avec Firefox alors que cela semble fonctionner avec Edge sur mon PC.
Suis-je un cas particulier ?

[MDN Link.pdf](https://github.com/mdn/translated-content/files/11948888/MDN.Link.pdf)

### What did you expect to see?

Que `:link` fonctionne avec Firefox

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/_colon_link`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/:link
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/_colon_link/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f66954d9bcc9f94b8dab0ba5452395282c5372cd
* Document last modified: 2022-10-01T14:10:29.000Z

</details>

**Comment by SphinxKnight** [comment]
Bonjour,

`:link` fonctionne bien avec Firefox (en tout cas c'est ce qu'indique le tableau de compatibilité et ce que j'ai pu reproduire de mon côté) 
![image](https://github.com/mdn/translated-content/assets/2413436/b9035dd2-6606-4daf-83e0-96396b76aa76)

En revanche, si vous avez paramétré votre Firefox pour ne pas conserver l'historique (ou que vous êtes en navigation privée), cela ne fonctionnera pas car le navigateur n'aura pas conservé l'information. Avez-vous un paramètre particulier ?

**Comment by SphinxKnight** [comment]
N.B. Pas de problème à répondre à la question ici mais cet espace (les *issues* GitHub sur ce dépôt) portent plutôt sur le contenu même de MDN plutôt que sur les questions de compatibilité de Firefox. Dans ce dernier cas, mieux vaudra privilégier https://support.mozilla.org/fr/kb/obtenir-assistance-communaute
