### ISSUE TITLE
zh-CN: The translation of the term-"lone surrogate"

### ISSUE THREAD

**Issue by JasonLamv-t** [mdn/translated-content#14093]
The word "lone surrogate" appears many times in the section of [`JavaScript.String`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters). Its concept has been succinctly explained in the original text, and I want to discuss here is its Chinese translation.

"Lone" may be translated into: 
- “孤” : including "孤立", "孤单", "孤独" and so on
- "单" : such as "单独", "单一", "单个" and more

In my opinion, I prefer the "孤". "Lone" is typically used to refer to an object that should appear in a pair. In the context of a surrogate, I believe "lone" was chosen because it is more appropriate than "single", "unpaired", or "solitary" to emphasize the abnormality and inability to function properly. In the Chinese context, the corresponding choice is "孤". Considering the surrogate's conception in the Unicode stander, “lone surrogate” belong to “单个码元”, the using of "单" may lead to confusion sometimes.

In some PRs(e.g. #14019), I translated "lone surrogate" as "孤项代理". While this may not be the optimal choice, I would like to suggest some alternatives such as "孤代理", "孤立代理", and "孤单代理". I am also open to feedback on using others such as"单独代理". Your thoughts and suggestions on this matter would be greatly appreciated. Thank you!

**Comment by lakejason0** [comment]
since the phrase surrogate pair (代理对) is more frequent and is more widely acknowledged, we could start from pair, and make it like impaired. I’d say 不成对代理字符 (not-in-pair surrogate character).

**Comment by yarusome** [comment]
虽然 Unicode [第 3.8 节](https://www.unicode.org/versions/Unicode15.0.0/UnicodeStandard-15.0.pdf)的标题将 surrogate 作名词用，但是此节所有定义均将 surrogate 作形容词用：high-surrogate code point、high-surrogate code unit、low-surrogate code point、low-surrogate code unit 和 surrogate pair，由此可以反推 surrogate 作名词仅为上述定义**笼统**的合称。而英文版的 [String](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String#utf-16_characters_unicode_code_points_and_grapheme_clusters) 页面也有如下定义：

> A "lone surrogate" is a 16-bit code unit satisfying[…]

因此 lone surrogate = lone surrogate code unit。（但是 code unit 有没有和 code point 对仗的二字译法？）

另：话说现在是不是在要求 MDN 的各个本地化组用英文进行公开交流？但是隔壁日文和西文组又一切照旧 :thinking:

**Comment by JasonLamv-t** [comment]
> 因此 lone surrogate = lone surrogate code unit。（但是 code unit 有没有和 code point 对仗的二字译法？）

有的，code unit 译为“码元”，code point 译为“码位”（在一些 JavaScript 相关的书中也译为“码点”），二者皆在 MDN-Glossary 中有对应条目

> 另：话说现在是不是在要求 MDN 的各个本地化组用英文进行公开交流？但是隔壁日文和西文组又一切照旧 🤔

就我所知没有强制的要求，个人习惯的问题

**Comment by JasonLamv-t** [comment]
> since the phrase surrogate pair (代理对) is more frequent and is more widely acknowledged, we could start from pair, and make it like impaired. I’d say 不成对代理字符 (not-in-pair surrogate character).

“不成对代理” is a pretty good choice.

**Comment by yin1999** [comment]
A reference: https://t.me/mozilla_china/10900

**Comment by yin1999** [comment]
> 话说现在是不是在要求 MDN 的各个本地化组用英文进行公开交流？但是隔壁日文和西文组又一切照旧

MDN 并未作任何规定，但对于那些*可能涉及*其他语言的内容请尽量使用英文

**Comment by yin1999** [comment]
> A reference: https://t.me/mozilla_china/10900

As the translation in [Microsoft document](https://learn.microsoft.com/zh-cn/windows/win32/intl/surrogates-and-supplementary-characters#general-guidelines-for-software-development-using-supplementary-characters) is "单独代理项". Should we just reference the translation by Microsoft?


Is there any other idea?

**Comment by yin1999** [comment]
Hey all. There are no new suggestion or thoughts on this. If we don't have any other thoughts on this by the end of this Sunday, let's use the translation from Microsoft document: "单独代理项".

@JasonLamv-t I will assign you for further work. If you have any trouble on it, please let me know :)

**Comment by JasonLamv-t** [comment]
Ok, I will adjust my previous work.

**Comment by JasonLamv-t** [comment]
String-overview and String-constructor already update.
