### ISSUE TITLE
There is a style bug in the NextPrev button in Japanese Page.

### ISSUE THREAD

**Issue by kazuhitonakayama** [mdn/translated-content#141]
# Overview
There is a style problem with the NextPrev button on Japanese pages.
May I (@kazuhitonakayama) correct that?

# Current
<img width="1156" alt="スクリーンショット 2021-01-03 22 24 45" src="https://user-images.githubusercontent.com/50609459/103479652-96202900-4e12-11eb-856c-5f718aa419dd.png">

# Ideal
<img width="1405" alt="スクリーンショット 2021-01-03 22 26 24" src="https://user-images.githubusercontent.com/50609459/103479687-c1a31380-4e12-11eb-979e-81b0e0bcb43b.png">

**Comment by SphinxKnight** [comment]
@kazuhitonakayama, sorry for the bumpy road :) I've migrated this issue on the right repository. Would you like to contribute and fix it now that localization is opened? :)

**Comment by mfuji09** [comment]
@kazuhitonakayama さん
この問題はサイト移行作業の中で解決したように見えます。もう一度確認してみていただけますか？
This issue appears to have been resolved by the site migration process. Could you please check again?
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Text_formatting

**Comment by kazuhitonakayama** [comment]
@SphinxKnight @mfuji09 
Thank you for your comments🙇‍♂️
And I can notice that this issue is corrected and resolved!
I appreciate you so much🎉
So I close this issue！
