### ISSUE TITLE
“什么是 JavaScript？”页面部分内容没有正确地加粗

### ISSUE THREAD

**Issue by 10ng1000** [mdn/translated-content#14173]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/What_is_JavaScript

### 与此议题相关的小节或标题？

服务器端代码 vs 客户端代码

### 哪些信息是错误、无用或不完善的？

中文页面中，第一段文字没有正确地加粗，而且双*号仍然显示

### 你期望看到什么？

文字正确地加粗，星号不显示

### 你还想补充什么内容？

![图片](https://github.com/mdn/translated-content/assets/64586167/f6c4c5f5-a004-431d-af80-e992e756ea26)

**Comment by jasonren0403** [comment]
感谢反馈，本页不只这一处格式问题，并且页面很久没更新过了。我打算进行一次页面更新

**Comment by szw0407** [comment]
Well I have tried fixing it before I found this issue. Here is my pull request:

https://github.com/mdn/translated-content/pull/14476

I will add the URL of this issue in my PR. Thanks.

**Comment by szw0407** [comment]
The fix by @jasonren0403 is much better than mine, I suppose.

https://github.com/mdn/translated-content/pull/14298
