### ISSUE TITLE
Translation "Send feedback about MDN Web Docs" page

### ISSUE THREAD

**Issue by mpstv** [mdn/translated-content#1420]
Необходимо обновить перевод статьи [Отправить отзыв о MDN](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/feedback/index.html) в соответствии с [англоязычной версией](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/feedback/index.html).

**Comment by Ganzeroar** [comment]
Я возьмусь за обновление перевода
