### ISSUE TITLE
Ensure all local URLs are pointing to proper locale

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#14229]
We should double-check to make sure that we're not pointing to the English locale in translations.  We should be able to perform a simple replacement (ex. `/en-US/docs` -> `/es/docs`) to achieve this.

**Comment by yin1999** [comment]
reference: #7413

**Comment by queengooborg** [comment]
Ha!  I forgot that I had opened an issue for this already!

Closing in favor of the existing issue.
