### ISSUE TITLE
es: Web/Media/DASH_Adaptive_Streaming_for_HTML_5_Video is partially translated

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#14232]
While running through files to format, I found that `Web/Media/DASH_Adaptive_Streaming_for_HTML_5_Video` is barely translated.  It may need resynchronization with upstream content.

**Comment by FerGv** [comment]
Hi @queengooborg, I'd like to work on this. Could you please assign it to me?

**Comment by Graywolf9** [comment]
You are now assinged to this @FerGv Thank you !

**Comment by Graywolf9** [comment]
Closed in https://github.com/mdn/translated-content/pull/15021
