### ISSUE TITLE
zh-tw: Partially translated files

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#14274]
While going through and formatting all files, I ran across the following files that are partially or fully untranslated. These files will probably needed to be resynchronized with upstream, or deleted.

- [ ] Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals
- [ ] Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
- [ ] Web/JavaScript/Reference/Global_Objects/Array/forEach
- [ ] Web/API/Window/location
- [ ] Web/API/setInterval
- [ ] Web/JavaScript/Reference/Errors/Not_defined
- [ ] Web/Media/Formats/Containers
- [ ] Web/Media/Formats (completely untranslated)

**Comment by jasonren0403** [comment]
maybe we should merge these with #13196 😄

**Comment by queengooborg** [comment]
Good idea, merging into #14274!
