### ISSUE TITLE
Issue with "zh-CN/docs/Web/API/DOMParser"

### ISSUE THREAD

**Issue by keke9208** [mdn/translated-content#143]
https://developer.mozilla.org/zh-CN/docs/Web/API/DOMParser#%E8%AF%AD%E6%B3%95
Two hidden chars “​​” in code `let domparser = new DOMParser()​​;` (between ")" and ";").
I copy the code to run but get unexpected character error.

**Comment by SphinxKnight** [comment]
@CreaTorAlexander I've moved this issue over to the repository where localized (incl. Chinese) content lives. I'm assigning it to you, let me know if you need help or if you wish to decline : )

**Comment by CreaTorAlexander** [comment]
I tried to do yarn start in content repo after I made the changes in the translated repo but I receive this error 
`Error: /path/to/translated-content/files does not exist`
