### ISSUE TITLE
Issue with "关键渲染路径": (short summary here please)

### ISSUE THREAD

**Issue by johnnyzhang1992** [mdn/translated-content#1435]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Performance/Critical_rendering_path

#### What information was incorrect, unhelpful, or incomplete?

**绘制**
最后 '**已不'**是将像素绘制在屏幕上。
#### Specific section or headline?
绘制

#### What did you expect to see?
最后 '**一步**' 是将像素绘制在屏幕上。

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/performance/critical_rendering_path`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Performance/Critical_rendering_path
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/performance/critical_rendering_path/index.html
* Last commit: https://github.com/mdn/translated-content/commit/c8a90c7efb53bdf1f1b019a071d9b80e3efb823e
* Document last modified: 2021-07-06T00:36:59.000Z

</details>

**Comment by KevinZonda** [comment]
This issue should be closed, due to the issue has been fixed,

![image](https://user-images.githubusercontent.com/33132228/132074219-aba7c31b-1722-49e0-bab6-43f193518d0c.png)

/cc @SphinxKnight @johnnyzhang1992

**Comment by SphinxKnight** [comment]
Fixed w/ ba279af873fe44f10ffaa5697a73e29001e44834 
Thanks @KevinZonda
