### ISSUE TITLE
ja: Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment partially translated

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#14389]
The Japanese localization for `Learn/Tools_and_testing/Cross_browser_testing/Your_own_automation_environment` is barely translated.  Most likely, it will need resynchronization with upstream.

**Comment by mfuji09** [comment]
It has been completed to translate as b2d669e5425ebdbe19f7455bff8b560e14fe8447.
