### ISSUE TITLE
ja: Learn/Tools_and_testing/Cross_browser_testing/Automated_testing partially translated

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#14388]
The page for `Learn/Tools_and_testing/Cross_browser_testing/Automated_testing` of the Japanese locale is mostly untranslated.  It likely needs to be resynchronized with upstream.

**Comment by mfuji09** [comment]
It has been translated as 2c94ec58790a601a58b568829a908ce842636189 .
