### ISSUE TITLE
Y a-t-il des restrictions/contraintes à l'utilisation de span ?

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#14447]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/grid-column-start

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

J'ai modifié l'exemple de cette page en remplaçant dans .box1 `grid-column-start:` 1;  par `grid-column-start:` span 2; 
La zone s'étend bien de la colonne 2 à la colonne 4.

J'ai remplacé `grid-column-end:` 4; par `grid-column-end:` 3;
Je m'attendais à ce que la zone s'étende de la colonne 2 à la colonne 3, que le span se calcule à partir de la colonne 4.
En fait elle s'étend de la colonne 1 à la colonne 3.

Il semblerait donc que `grid-column-end` s'impose à `grid-column-start.`

### What did you expect to see?

Si possible, une explication sur ce comportement.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/grid-column-start`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/grid-column-start
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/grid-column-start/index.md
* Last commit: https://github.com/mdn/translated-content/commit/9ce928f2ff5729505c87c1da76f114b45e40aea8
* Document last modified: 2022-10-17T09:34:29.000Z

</details>

**Comment by SphinxKnight** [comment]
@DomOBU, pour commencer : je présente mes excuses pour le délai de réponse ici.
Je vais mettre à jour cette page MDN pour (j'espère) clarifier ce point.

En attendant, la compréhension que j'en ai est la suivante.

Si on prend : 

```css
.box1 {
  grid-column-start: 1;
  grid-column-end: 4;
}
```

On aura la cellule de la boîte `box1` qui démarrera depuis le bord de la première colonne et s'étendra jusqu'au bord de la 4e colonne. Autrement dit, on impose deux contraintes "absolues" (N.B. on obtient le même résultat si on indique  `grid-column-start: 4;  grid-column-end: 1;`)

Si on prend : 
```css
.box1 {
  grid-column-start: span 2;
  grid-column-end: 4;
}
```

On aura la cellule de la boîte `box1` qui finira au bord de la 4e colonne et qui s'étend de deux colonnes à partir de cette limite. Autrement dit, on impose d'une part une contrainte absolue (`grid-column-end: 4;`) et d'autre part une contrainte relative (à la fin) (`grid-column-start: span 2;`). 

Dans l'exemple de l'article la grille comporte 3 colonnes (avec des "bords" numérotés de 1 à 4) cela signifie que la cellule s'étalera dans les 2 et 3e colonnes (du bord 2 au bord 4)
![image](https://github.com/mdn/translated-content/assets/2413436/5ab472d6-c2b1-4f8a-bad7-974bc1782ec1)

Par conséquent, quand on écrit 
```css
.box1 {
  grid-column-start: span 2;
  grid-column-end: 3;
}
```
 on impose 
- la contrainte absolue suivante : la boîte doit s'arrêter au bord 3
- la contrainte relative suivante : la boîte doit occuper deux colonnes par rapport à sa fin
Dans notre exemple, cela revient à occuper les deux premières colonnes (ou équivalent : de "s'étaler" du bord 1 au bord 3)

![image](https://github.com/mdn/translated-content/assets/2413436/39621254-3afa-42f1-a370-b692a1f3d855)

**Comment by SphinxKnight** [comment]
Dans l'article actuel, c'est ce qui est décrit par "Un fragment de grille est utilisé pour le placement de l'élément sur la grille afin que le début de la ligne pour l'élément de la grille soit placé à n lignes du bord de fin." (la formulation est peu claire, je le concède)
