### ISSUE TITLE
中文版文档，每个小节的标题级别错误

### ISSUE THREAD

**Issue by hao-kuai** [mdn/translated-content#145]
文章整体是用h2来区分小节的，现在标题很多都是h3标题。比如 继承，是独立的小节，和“创建新对象”并列，应该使用h2的，现在使用h3会造成该内容属于 “创建新对象”的子内容误导。请参考英文版设置

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Working_with_Objects

**Comment by SphinxKnight** [comment]
@roy-tian here you go ;) let me know if you want me to assign the issue to you :)

**Comment by CreaTorAlexander** [comment]
What is the task here in this issue? Updating from h3 to h2 in chinese version?
