### ISSUE TITLE
Plusieurs points avec :visited

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#14552]
### MDN URL

https://developer.mozilla.org/fr/docs/Learn/CSS/Styling_text/Styling_links

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

Ci-après plusieurs points. Je ne sais pas si c'est propre à mon laptop.
J'ai fait les tests avec Edge.

_Exemple : Apprentissage actif : mettez en forme vos propres liens_
Si un lien est visité tous les liens deviennent visités.
Si je remplace les "#" par "#A", "#B" et "#C" le problème disparait, `:visited` fonctionne correctement.

_Exemple : Inclusion d'icônes dans les liens_
Je constate que `a:visited`  ne fonctionne pas avec une icône.
Si j'enlève l'icône `a:visited` fonctionne de nouveau.

### What did you expect to see?

Est-ce que je constate est "normal" ?

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/css/styling_text/styling_links`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/CSS/Styling_text/Styling_links
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/css/styling_text/styling_links/index.md
* Last commit: https://github.com/mdn/translated-content/commit/a8d5ecd53ac1258d9c4107652417eb7085214cc1
* Document last modified: 2023-07-21T11:18:10.000Z

</details>

**Comment by SphinxKnight** [comment]
@DomOBU Pouvez-vous indiquer le contenu de vos essais sur https://codepen.io/ ou https://jsfiddle.net/ pour mieux reproduire/comprendre?

**Comment by SphinxKnight** [comment]
En effet, si tous les liens sont exactement les mêmes, avoir visité un des liens revient à les avoir visité tous.
De mon côté, sur Firefox ou Chromium je ne constate pas de problème particulier avec les icônes (cf. https://codepen.io/SphinxKnight/pen/PoVjNgB comme exemple)

**Comment by SphinxKnight** [comment]
J'espère avoir répondu et ferme l'*issue*, n'hésitez pas à la rouvrir si besoin. Désolé pour le délai de réponse :(
