### ISSUE TITLE
사소한 오타

### ISSUE THREAD

**Issue by gwonhong** [mdn/translated-content#14564]
### MDN URL

https://developer.mozilla.org/ko/docs/Web/API/setTimeout

### 이 문제에 관한 특정 섹션 또는 제목은 무엇인가요?

설명 - 늦은 타임아웃

### 어떤 정보가 부정확하거나 도움이 되지 않거나 불완전했나요?

 타임아웃이 예**쌍**보다 늦게 실행될 수 있습니다

### 어떻게 고쳐져야 하나요?

 타임아웃이 예**상**보다 늦게 실행될 수 있습니다

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ko/web/api/settimeout`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/API/setTimeout
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/api/settimeout/index.md
* Last commit: https://github.com/mdn/translated-content/commit/baaf0062bf82c8ffe9c9f2948833589018c64ddd
* Document last modified: 2022-12-29T04:27:25.000Z

</details>

**Comment by SnowMarble** [comment]
@hochan222 이슈 닫아주실 수 있을까요?

**Comment by hochan222** [comment]
고생 많으셨습니다! 멘션주셔서 감사합니다!
