### ISSUE TITLE
Отображается не достоверный результат применения css стиля

### ISSUE THREAD

**Issue by tonakihan** [mdn/translated-content#14566]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/CSS/First_steps/How_CSS_is_structured

### О какой части статьи или абзаце идёт речь?

#функции

### Какая информация оказалась неверной, бесполезной или неполной?

Первый пример использует свойство 
```css 
transform: rotate(0.8turn);
``` 
Проблема наблючается только в русской версии сайта.

### Как бы вы исправили?

В интерактивном окне, которое окрывается при нажати `Play` в том исходном коде содержится повторное определения `.box`. Для исправления нужно только убрать его и если нужно, то заменить изображение.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/css/first_steps/how_css_is_structured`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/First_steps/How_CSS_is_structured
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/css/first_steps/how_css_is_structured/index.md
* Last commit: https://github.com/mdn/translated-content/commit/e9c14aad573d24cedd2bfe855efe74031106e2dd
* Document last modified: 2023-07-17T16:46:37.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17367 :ok: 
Thank you! :+1:
