### ISSUE TITLE
Issue with "Web 开发技术": (short summary here please)

### ISSUE THREAD

**Issue by sorrosdown** [mdn/translated-content#1459]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ff9ea0cf9f0ea6217deefa7ad0dba35bf7f6c45e
* Document last modified: 2021-07-08T00:34:19.000Z

</details>

**Comment by cw118** [comment]
The entire page has been updated, please see #3386 for details.
