### ISSUE TITLE
The Chinese(Simplified) translations have wrong links

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/translated-content#146]
@CourageLee commented on [Mon Jan 18 2021](https://github.com/mdn/yari/issues/2578)

The page <https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features> could not found,the actual link of this page is <https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/%E5%90%91%E2%80%9C%E5%BC%B9%E8%B7%B3%E7%90%83%E2%80%9D%E6%BC%94%E7%A4%BA%E7%A8%8B%E5%BA%8F%E6%B7%BB%E5%8A%A0%E6%96%B0%E5%8A%9F%E8%83%BD>. 
The last part of the link has been translated too.

**Comment by yin1999** [comment]
@SphinxKnight This issue seems fixed.
