### ISSUE TITLE
Все ссылки с примерами ведут на страницу 404

### ISSUE THREAD

**Issue by magacode** [mdn/translated-content#14602]
### MDN URL

https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous/Introducing

### О какой части статьи или абзаце идёт речь?

Ссылки на примеры

### Какая информация оказалась неверной, бесполезной или неполной?

Все ссылки с примерами ведут на страницу 404

### Как бы вы исправили?

Нужно обновить все ссылки на примеры

### Есть ли у вас какие-либо подтверждающие ссылки?

1. https://github.com/mdn/learning-area/tree/main/javascript/asynchronous/introducing/simple-sync.html
2. https://github.com/mdn/learning-area/blob/main/javascript/asynchronous/introducing/simple-sync-ui-blocking.html

### Хотите добавить что-то ещё?

Нет

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/conflicting/learn/javascript/asynchronous/introducing`
* MDN URL: https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous/Introducing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/conflicting/learn/javascript/asynchronous/introducing/index.md
* Last commit: https://github.com/mdn/translated-content/commit/48ec8467d0c995532d325cafd9b8950d50771b1d
* Document last modified: 2022-12-15T06:22:47.000Z
* 

</details>

**Comment by leon-win** [comment]
Эта страница была упразднена в MDN, сейчас почитать про асинхронный JS можно в разделе https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous
