### ISSUE TITLE
点击线下聚会网址Page not found

### ISSUE THREAD

**Issue by Chaya-Yellow** [mdn/translated-content#14695]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/Learning_and_getting_help

### 哪些信息是错误、无用或不完善的？

当我点击线下聚会的超链接，显示page not found
<img width="1493" alt="image" src="https://github.com/mdn/translated-content/assets/69381752/2af3612f-9968-4d7e-a061-f836fd64fbca">

### 你期望看到什么？

该链接进去能够查看中国内陆是否有类似的交流沙龙活动

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/learning_and_getting_help`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Learning_and_getting_help
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/learning_and_getting_help/index.md
* Last commit: https://github.com/mdn/translated-content/commit/cbed91b9f10136fd0f3230ff53b4f83b59f218c2
* Document last modified: 2023-05-11T03:55:41.000Z

</details>

**Comment by jasonren0403** [comment]
这个链接是损坏的，我修一下
