### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by zhrhipc** [mdn/translated-content#14731]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex

### 与此议题相关的小节或标题？

语法

### 哪些信息是错误、无用或不完善的？

单值语法: 值必须为以下其中之一：

一个无单位数 (<number>): 它会被当作 flex:<number> 1 0; <flex-shrink>的值被假定为 1，然后<flex-basis> 的值被假定为0。

### 你期望看到什么？

单值语法: 值必须为以下其中之一：

一个无单位数 (<number>): 它会被当作 flex:<number> 1 0; <flex-grow>的值被假定为 1，然后<flex-basis> 的值被假定为0。

### 你有什么支持的链接、参考或引用？

https://developer.mozilla.org/en-US/docs/Web/CSS/flex#syntax

One-value syntax: the value must be one of:
a valid value for [<flex-grow>]: then the shorthand expands to flex: <flex-grow> 1 0.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/flex`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/flex/index.md
* Last commit: https://github.com/mdn/translated-content/commit/623c5ce17a3d601e3b83bc97e6842f304708f0c8
* Document last modified: 2023-07-29T03:06:41.000Z

</details>

**Comment by yin1999** [comment]
Duplicate of #14732
