### ISSUE TITLE
Issue with "IDBRequest.result": (short summary here please)

### ISSUE THREAD

**Issue by hharouna** [mdn/translated-content#1475]
hello 

MDN URL: https://developer.mozilla.org/fr/docs/Web/API/IDBRequest/result

#### What information was incorrect, unhelpful, or incomplete?
IDBRequest { source: IDBIndex, transaction: IDBTransaction, readyState: "pending", onsuccess: null, onerror: onerror(Event)

Incorrect onsuccess: null

_ ------------------------------------------------------------------- 
at what moment onsuccess return true?

var result = objectStoreTitleRequest.get (title)

return null if there is no result

always return null even if there is a result

console.log (result)
null

result.result = undefined

result should be defined and not undefined

_

#### Specific section or headline?
return false or null even if there is no result

 updateTitleRequest.onsuccess = function(Event) {
var rs_result = Event.target.result
rs_result must be defined and not defined

rs_result must return either: 
false or null even if there is no result
  };

#### What did you expect to see?

rs_result false or null even if there is no result

#### Did you test this? If so, how?
----------------------------------------------------------------- start 
![no undefined](https://user-images.githubusercontent.com/35904326/125166642-736c2580-e151-11eb-9c23-a7394d389518.png)
![onsuccess true](https://user-images.githubusercontent.com/35904326/125166643-736c2580-e151-11eb-87a9-633bd3b13139.png)
![no undefined](https://user-images.githubusercontent.com/35904326/125166657-80891480-e151-11eb-952a-972fdb4fc11d.png)
![onsuccess true](https://user-images.githubusercontent.com/35904326/125166658-8121ab00-e151-11eb-9983-d5097648cb9f.png)
![no undefined](https://user-images.githubusercontent.com/35904326/125166671-8b43a980-e151-11eb-9054-9dffea8e3adb.png)

       var data_Json = JSON.stringify(data) // 
        var data_parse = JSON.parse(data_Json)
        var data_json_length = data_parse.length
         console.log(data)
        
      
   
        var article=''; 
        var db= index_f.open_indexDB(index_f.db,index_f.Version)
      
         db.onsuccess = function(Event){
         var t_db = Event.target.result
        
         var transaction = t_db.transaction(["Vente"],'readonly')
         var objectStore = transaction.objectStore('Vente')
         var t_getAll = objectStore.getAll(); 
         var t_index = objectStore.index('id_type')
         
         console.log('Tous les enregistrements ont été affichés.');
           
         var i =0; 
         for(i;i<data_json_length;i++){

            var t_get = t_index.get(data_parse[i].id_type)

            t_get.onerror= function(Event){
             location.reload
            }

            var data_i = data_parse[i]
      
            if(t_get.onsuccess==null){
            console.log(t_get.onsuccess)//always null
            var rs_info = {'t_info': data_i, 't_true':false}
            article += compilation.af_button(rs_info)
             
            }else if(t_get.onsuccess==true){ 

            console.log(t_get.onsuccess)//always null instead of true
            console.log(t_get)//

            t_get.onsuccess = function(Event){
            
            var rs_t_get = Event.target.result
            console.log(rs_t_get)
            var l =JSON.stringify(rs_t_get)
            var t = JSON.parse(l) 
            var rs_info = {'t_info':t, 't_true':true}
            article += compilation.af_button(rs_info)
            
            }
          
            }

        }

$('.modal-body').html(article)
     
   
}  
---------------------------------------------------- and

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/api/idbrequest/result`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/IDBRequest/result
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/idbrequest/result/index.html
* Last commit: https://github.com/mdn/translated-content/commit/235c34993c7b14f783fc8259cc237ac09f0d3e57
* Document last modified: 2021-07-09T00:38:08.000Z

</details>

**Comment by SphinxKnight** [comment]
@hharouna Hello, could you tell us how this is related to the *content* of this page https://developer.mozilla.org/fr/docs/Web/API/IDBRequest/result ? I will update the French version but I'm not sure it matches the issue you're describing.

--- 
Bonjour, pouvez-vous nous en dire un peu plus sur le problème dans le *contenu* de la page ? En effet, ce dépôt stocke les documents de MDN mais je ne vois pas comment cette page (https://developer.mozilla.org/fr/docs/Web/API/IDBRequest/result ) est incorrecte par rapport à votre description. Je vais mettre à jour la page française par rapport à son équivalente anglaise.

Merci pour vos retours / précisions.

**Comment by SphinxKnight** [comment]
@hharouna could you please help us understand what's wrong on the page?

I'll close the issue in a few days if there is no other comment.

**Comment by hharouna** [comment]
hello 
désolé pour le retard après votre première réponse, 
j'ai réécris le code.

         
            var db= index_f.open_indexDB(index_f.db,index_f.Version)
            
         
            db.onsuccess = function(Event){
            var t_db = Event.target.result
        // console.log(t_db)
            var transaction = t_db.transaction(["Vente"],'readonly')
            var objectStore = transaction.objectStore('Vente')
            var t_getAll = objectStore.getAll(); 
            var t_index = objectStore.index('id_type')
            console.log('Tous les enregistrements ont été affichés.');
        //  console.log(t_getAll)  

            var p = function(data_mysql,index_get){

            this.result_data = data_mysql
            this.t_get= index_get

            }

            p.prototype.suite = function(data_i,index_get)
           {
               
            this.result_data = data_i
            this.t_get= index_get
            this.r_t_get =this.t_get.get(this.result_data['id_type'])
            var o= JSON.stringify(this.result_data)
            var b= JSON.parse(o)
            //console.log(this.r_t_get.result)
            this.r_t_get.onsuccess=function(Event){
            this.value = Event.target.result
            if(this.result!=undefined){
            console.log(this.value.id_type)
            console.log(this.result)
            var rs_this = this.value.id_type
            return this.result
            }

            if(this.value===undefined){
                var j= JSON.stringify(o)
                var b= JSON.parse(j)
            console.log(b)
            console.log("--------")
         
            return b
            }

            }


            }

            p.prototype.ret =function(){
                this.r_t_get = function(){
                 var rs = this.result
                 console.log(this.result) 
                }
                console.log(this.r_t_get.result) 
            }
          //  console.log(data_parse)
           
       
         var  rs_p = new p(data_parse,t_index)
         var suite_i =""  

            for(i=0;i<data.length;i++){   
             suite_i+=rs_p.suite(data[i],t_index)
        }
       console.log(suite_i)// undefined
        }

**Comment by hharouna** [comment]
je vous reviens en images et plus d'explications sur la première procédure ainsi que la deuxième

**Comment by SphinxKnight** [comment]
@hharouna pouvez-vous nous indiquer en quoi cela est lié à l'article MDN même ? Ce dépôt et ces *issues* portent sur la documentation MDN : pouvez-vous faire référence à un passage de l'article indiqué au début qui serait à corriger ?

**Comment by hharouna** [comment]
Désolé mais j’ai mise une pause sur l’utilisation de INDEXDB que proposes
mes navigateurs
Car les  functions que j’utilise me return toujours undefined

Je resterais avec mes variables des sessions php qui function correctement
avec la même procédure de stockage.

Je vous ferrais  un rapport détails de l’ensemble des erreurs constatées
sur les erreurs.

Cordialement

Harouna
