### ISSUE TITLE
In French version, wrong example for If pages. Version française : un exemple erroné

### ISSUE THREAD

**Issue by Rpnpif** [mdn/translated-content#14769]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/if...else

### What specific section or headline is this issue about?

Affectation de variable dans l'expression conditionnelle

### What information was incorrect, unhelpful, or incomplete?

Les exemples mauvais et bon sont identiques.
Bad and good examples are the same.

### What did you expect to see?

Il semble que le mauvais exemple devrait être :
```
if (x = y) {
  /* exécuter les instructions */
}
```
Avec une seule parenthèse ouvrante.

The bad example should be 
```
if (x = y) {
  /* exécuter les instructions */
}
```
With one opening parenthesis not two.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/if...else

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/statements/if...else`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Statements/if...else
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/statements/if...else/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1a4be8c32441258acc4a8f3cc052b2f58c2ebc68
* Document last modified: 2023-07-28T08:49:33.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour le signalement @Rpnpif, c'est lié à une application récente de Prettier qui a un peu trop amélioré les choses. Je vais repasser sur la page pour coller à la version anglaise qui utilise `nolint` (cf. https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/statements/if...else/index.md?plain=1#L152C12-L152C13) pour éviter ce problème.
