### ISSUE TITLE
const 关键字 和 var 关键字 的 变量提升 问题

### ISSUE THREAD

**Issue by JuStin-Lo-JPDF** [mdn/translated-content#14774]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Functions#%E8%B0%83%E7%94%A8%E5%87%BD%E6%95%B0

### 与此议题相关的小节或标题？

调用函数

### 哪些信息是错误、无用或不完善的？

![image](https://github.com/mdn/translated-content/assets/62563940/d7d5cead-c0fb-4ba6-b4ea-715a9090c7b7)
```
console.log(square); // square is hoisted with an initial value undefined.
console.log(square(5)); // Uncaught TypeError: square is not a function
const square = function (n) {
  return n * n;
};
```
使用 const 关键字声明的变量不会进行 变量提升 处理，所以 const square = 应该改为 var square = ！

### 你期望看到什么？

```
console.log(square); // square is hoisted with an initial value undefined.
console.log(square(5)); // Uncaught TypeError: square is not a function
var square = function (n) {
  return n * n;
};
```

### 你还想补充什么内容？

本来这个 Issues 应该已经提完了，但当我在Chrome开发者工具的控制台里把 const 改为 var 时，又发现了一个困惑我的地方：
![使用let后再把let改为var_(带标注！！)](https://github.com/mdn/translated-content/assets/62563940/9f552a0f-bd7c-49b4-8739-960fdaf2a74f)

从执行VM16490代码片段返回的VM16490:1 Uncaught ReferenceError: square is not defined错误可以确定square没有被定义。
然后执行VM16494代码片段返回的VM16494:1 Uncaught ReferenceError: square is not defined错误的原因就是这个Issues前面所说的 使用 const 关键字声明的变量不会进行 变量提升 处理 。
第一个问题就出在执行VM16510代码片段返回的错误竟然是VM16510:1 Uncaught SyntaxError: Identifier 'square' has already been declared。由于VM16510代码片段和VM16494代码片段的区别只是把VM16494代码片段中的const改成了var，所以在执行VM16510代码片段之前square变量已经进行了 变量提升 处理，所以预期的报错应该像文章中(或第二行后面的注释里)所说的square不是一个函数，也即VM16510:2 Uncaught TypeError: square is not a function，可它就是不按套路出牌啊。。
同时第二个问题又来了：
既然执行VM16510代码片段返回的错误说square已经被声明了，这个声明肯定是VM16494代码片段第三行中的const square = 函数表达式进行声明的，可是JavaScript是即时编译的，而使用 const 关键字声明的变量又不会进行 变量提升 处理，而且执行VM16494代码片段的第一行就已经返回VM16494:1 Uncaught ReferenceError: square is not defined错误了，这说明VM16494代码片段中的第三行根本就没有执行，那么既然没执行又哪里来的声明square呢！？这和执行VM16510代码片段返回的错误说square已经被声明了是矛盾的。
好，既然执行VM16510代码片段返回的错误说square已经被声明了，那我就再发一次square(也即执行VM16529片段，内容和VM16490代码片段完全一样)，可返回的错误VM16529:1 Uncaught ReferenceError: square is not defined说明square还是没有被定义啊。。这就是第三个问题了！
而最后执行的三个代码片段依次为VM16533代码片段(内容和VM16494代码片段完全一样)、VM16542代码片段(内容为将VM16494代码片段的内容注释掉第一行)和没有返回报错信息的代码片段(内容为将VM16494代码片段的内容注释掉第一行和第二行)。
那么最后一个问题来了，在前面的第二个问题中已经说了：既然执行VM16510代码片段返回的错误说square已经被声明了，那么这个声明肯定是VM16494代码片段第三行中的const square = 函数表达式进行声明的，现在假设square就是由VM16494代码片段第三行中的const square = 函数表达式进行声明的，可是最后一个没有返回报错信息的代码片段的内容正是将VM16494代码片段的内容注释掉第一行和第二行，也即执行的也是const square = 函数表达式，这在假设里已经执行过一次了，而const是无法在同一个作用域内对同一个变量square声明两次的，所以说明VM16494代码片段的作用域和最后一个没有返回报错信息的代码片段的作用域是两个不同的作用域，那么同理VM16494代码片段的作用域和VM16510代码片段的作用域也是两个不同的作用域，那么执行VM16510代码片段返回的错误说square已经被声明了又是怎么来的呢！？

希望大佬们能解答一下萌新的疑惑！！

以下是没标注的原图：
![使用let后再把let改为var](https://github.com/mdn/translated-content/assets/62563940/cff6c03c-940a-4daf-9c27-481154e902a0)

以下是直接从Chrome控制台复制出来的文本内容：
```
square
VM16490:1 Uncaught ReferenceError: square is not defined
    at <anonymous>:1:1
(anonymous) @ VM16490:1
console.log(square); // square is hoisted with an initial value undefined.
console.log(square(5)); // Uncaught TypeError: square is not a function
const square = function (n) {
  return n * n;
};
VM16494:1 Uncaught ReferenceError: square is not defined
    at <anonymous>:1:13
(anonymous) @ VM16494:1
console.log(square); // square is hoisted with an initial value undefined.
console.log(square(5)); // Uncaught TypeError: square is not a function
var square = function (n) {
  return n * n;
};
VM16510:1 Uncaught SyntaxError: Identifier 'square' has already been declared
    at <anonymous>:1:1
(anonymous) @ VM16510:1
square
VM16529:1 Uncaught ReferenceError: square is not defined
    at <anonymous>:1:1
(anonymous) @ VM16529:1
console.log(square); // square is hoisted with an initial value undefined.
console.log(square(5)); // Uncaught TypeError: square is not a function
const square = function (n) {
  return n * n;
};
VM16533:1 Uncaught ReferenceError: square is not defined
    at <anonymous>:1:13
(anonymous) @ VM16533:1
//console.log(square); // square is hoisted with an initial value undefined.
console.log(square(5)); // Uncaught TypeError: square is not a function
const square = function (n) {
  return n * n;
};
VM16542:2 Uncaught ReferenceError: square is not defined
    at <anonymous>:2:13
(anonymous) @ VM16542:2
//console.log(square); // square is hoisted with an initial value undefined.
//console.log(square(5)); // Uncaught TypeError: square is not a function
const square = function (n) {
  return n * n;
};
undefined
```

**Comment by yin1999** [comment]
关于你提到的文档中的问题，我们需要对其进行更新，因为变量提升其实并不属于这个文档所需要覆盖的范畴（其属于 `var` 关键字）。[英文文档的示例](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Functions#function_hoisting)也与之不同。

关于你提到的第二个问题，我并不是很了解 V8 引擎，@Josh-Cena 你对这个问题有了解吗

**Comment by Josh-Cena** [comment]
REPL 是个非常特别的执行环境，有很多方便开发的特殊 feature，所以在测试语言本身的行为时不推荐用。具体来说，JavaScript 并不完全是「实时编译」的——在加载代码时，就会预先分析其中所有的 `var`/`let`/`const` 等声明，不然 TDZ 之类的行为就无法实现了。因此，即使 `const square = ...` 这一行并没有真的运行，`square` 的声明也是存在的。

**Comment by BSPR0002** [comment]
使用 const 关键字声明的变量**会**进行变量提升处理。
这个例子中由于在 `console.log(square);` 提前访问了 `square` 变量，但此时 `square` 并未被*初始化*，因此提示“square is not difined”。
与 `var` 不同，`const` 与 `let` 声明的变量，在其被初始化前对其进行访问都会提示“变量 is not difined”。
由于第一次已经使用 `const` 显式声明了 `square` 变量，`square` 变量的类型已经不能再改变，此后必须正确初始化 `square` 变量，`square` 变量才能被正常使用。
> 所以说明VM16494代码片段的作用域和最后一个没有返回报错信息的代码片段的作用域是两个不同的作用域

VM16494代码片段的作用域和最后一个没有返回报错信息的代码片段的作用域**是同一个**作用域。最后一个片段此时对 `square` 变量正确地进行了初始化，因而没有报错，而且此后 `square` 变量可以被正常使用。

**Comment by JuStin-Lo-JPDF** [comment]
> REPL 是个非常特别的执行环境，有很多方便开发的特殊 feature，所以在测试语言本身的行为时不推荐用。
> 具体来说，JavaScript 并不完全是「实时编译」的——在加载代码时，就会预先分析其中所有的 `var`/`let`/`const` 等声明，不然 TDZ 之类的行为就无法实现了。

这两句话真的受益匪浅啊！

> 因此，即使 `const square = ...` 这一行并没有真的运行，`square` 的声明也是存在的。

我理解了，感谢你的评论！

**Comment by BSPR0002** [comment]
@JuStin-Lo-JPDF 
虽然我的说法与现有的文献不符，但这都是我实践得出的结论，或许只是因为我并不知道某些概念应该用什么名词形容。我并不按照你指出的文章的描述去理解这种现象，但也不曾对这个问题有过不解。

你提出的两处说法我是有头绪的。
看过你给出的图片，我又明白了一些事。确实，未初始化时访问应该提示“ReferenceError: Cannot access '[symbol]' before initialization”，但这是在特定的作用域里才有的，例如：由文件加载的代码（顶级作用域）、VM中的块级作用域或函数作用域。然而 REPL 拥有全局作用域，在 REPL 的全局作用域里面由于不明原因，同样的行为只会提示“[symbol] is not defined”。但即便它的提示不同，造成的影响都与其他环境下无异，我推断这是由于 REPL 搜索访问相关变量时穿过了顶级作用域，去搜索全局作用域造成的（let 和 const 只提升到顶级作用域，而不是全局作用域），然而赋值与声明时却又遵循了正确的作用域层级，因而提示不一样。这只是猜想，而且到底为什么不重要。
其实我的印象里这个行为对应的错误也应该是“ReferenceError: Cannot access '[symbol]' before initialization”，但上一次看到这个错误已经不知道是什么时候的事了，毕竟印象里我自己写代码从来没有犯过相关的错误，加上你第一次给出的图写的是“[symbol] is not defined”，我也就懒得查证按照你的图往下说。

第二点，无论 MDN 的文献是如何描述的，仅从表现上看，如果说 `let`、`const` 没有进行声明提升，那么运行引擎无论如何也不会知道要访问的变量是“没有被初始化”而不是“没有被声明”这一状况，也解释不通没有执行相关位置却会有“Identifier '[symbol]' has already been declared”这一提示。更何况这一错误并不是在预分析/编译阶段抛出的，而是在执行到问题所在位置才抛出的。与
```
let i = 1;
let i = 2;
```
这种被判断为 SyntaxError 的情况完全不一样。这就是一种事实上的提升。

最后，我查证了 MDN 英文版的描述，英文版对 let 的描述是：
>`let` declarations can only be accessed after the line of declaration is reached (see [temporal dead zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz)). For this reason, let declarations are commonly regarded as [non-hoisted](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting).

>`let` 声明的变量只能在执行到声明书写处后才能访问（参见[暂时性死区](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/let#%E6%9A%82%E6%97%B6%E6%80%A7%E6%AD%BB%E5%8C%BA)）。因此，`let` 声明通常被视为是[非提升的](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting)。

里面只提到了“被视为”，而不是“等同于”或“实际上是”，而且缺少了一部分其他内容，我质疑其作为参考的有效性。
@yin1999 我认为当前对 let 关键字的中文文档是错误的，而且已经过时！需要更新！

综上，我认为我的结论没有任何错误，完毕。

**Comment by yin1999** [comment]
[`const` 和 `let` 会使用文档中列出的第三种提升](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting)：改变在当前作用域下声明之前的代码的行为，所以使用 `let` 关键字声明并初始化变量的示例会抛出不同的错误。

```js
console.log(a); // ReferenceError: Cannot access 'a' before initialization
let a = 5;
```

```js
console.log(a); // ReferenceError: a is not defined
```

而 `var` 关键字则会将变量赋值为 `undefined`，可以正常引用。所以，我们将 `let` 声明当作是非提升的，我们无法在声明前引用 `let` 声明的变量（但注意，上面的行为我们仍称其为一种“提升”）。“be regarded as”本身就是“被视为“的意思，即，大众都将某一事实作为统一的认同，即使真实的结果与事实相反（这里的 `let` 本身具有提升的行为，而我们将其认作不会提升就是一种结果与事实相反）。

**Comment by BSPR0002** [comment]
@yin1999 您这是是把我这段
> `let` 声明的变量在执行到声明书写处后才能被访问（参见[暂时性死区](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/let#%E6%9A%82%E6%97%B6%E6%80%A7%E6%AD%BB%E5%8C%BA)）。因此，let 声明通常被视为是[非提升的](https://developer.mozilla.org/en-US/docs/Glossary/Hoisting)。

当成目前中文版本的内容了吗？😓如果是的话那很遗憾，因为这是我对英文版本现翻的。中文版本目前相对应的内容是这样的：
> `let` 允许你声明一个作用域被限制在[块](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/block)作用域中的变量、语句或者表达式。与 [`var`](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/var) 关键字不同的是，`var` 声明的变量作用域是全局或者整个函数块的。 `var` 和 `let` 的另一个重要区别，`let` 声明的变量不会在作用域中被提升，它是在编译时才初始化（参考下面的[暂时性死区](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/let#%E6%9A%82%E6%97%B6%E6%80%A7%E6%AD%BB%E5%8C%BA)）。

对 `let` 使用了“不会”这一确定性的表述，后面的表述也十分混乱。而且和当前英文版的内容有明显差别：
![image](https://github.com/mdn/translated-content/assets/42113148/15abb05b-cc91-488a-9319-921ffb1f2155)
其他与目前讨论问题相关的页面也和英文版有明显差别。我认为有必要进行大规模翻新😨。

**Comment by yin1999** [comment]
这个是在2021年引入的错误翻译，当时 `l10n-zh` 团队并无专门负责简体中文文档审核的成员。后面英文文档也多次更新过内容，如果有时间，欢迎参与内容更新。

**Comment by yin1999** [comment]
已创建议题：#15126

**Comment by Josh-Cena** [comment]
我最近刚刚重写了 `let` 文档，所以中文版很可能还没更新（`const`, `var` 等同理）
