### ISSUE TITLE
type に click が含まれてない

### ISSUE THREAD

**Issue by gtk2k** [mdn/translated-content#14798]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/MouseEvent/MouseEvent

### この問題に関する節や見出しはどこですか。

値の type 項目

### 不完全、不親切、不完全であった情報は何ですか。

MouseEvent のページで、サンプルプログラムには click タイプのサンプルを載せてますが、MouseEvent のコンストラクターのページの値の type 項目には click がありません。

### どう表示されるべきだと思いますか。

type の説明に click を含めるべきです。 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/mouseevent/mouseevent`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/MouseEvent/MouseEvent
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/mouseevent/mouseevent/index.md
* Last commit: https://github.com/mdn/translated-content/commit/8f0fbd3a2c5d486cf4f35d0139634c72fb967f6a
* Document last modified: 2022-11-14T13:37:03.000Z

</details>

**Comment by mfuji09** [comment]
最新の仕様書では、 click イベントは MouseEvent から PointerEvent に変更されています（dblclick は現在でも MouseEvent です）。
https://w3c.github.io/uievents/#event-type-click

ですから、ブラウザーが MouseEvent() コンストラクターに設定する値として、 "click" が含まれていないのは（仕様書上では）間違いではないといえます。すなわち、ブラウザーはイベント名に "click" を指定する場合は、 MouseEvent() ではなく PointerEvent() コンストラクターを使うということです。
※ ただし、現時点ではまだこの変更が反映されていないブラウザーがあります。

一方、MouseEvent() のイベント名として、リストに挙げた値以外を使用してはいけないという規則もないので、 MouseEvent インターフェイスの記事に掲載されている例も間違いとはいえません。

ただし、Element インターフェイスの click イベントの記事は、まだイベント型が MouseEvent であると書かれています。英語版の記事は既に更新されているので、日本語訳も更新が必要だと言えます。
https://developer.mozilla.org/ja/docs/Web/API/Element/click_event

**Comment by gtk2k** [comment]
了解しました。
(JSのコーディングに置いていろんな方が見られると思いますので、個人的にはなんか注記等があったほうがいいかなとは思いますが。)
この問題はクローズします。
