### ISSUE TITLE
Erreur typographique

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#14813]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/CSS_grid_layout/Auto-placement_in_grid_layout

### What specific section or headline is this issue about?

https://developer.mozilla.org/fr/docs/Web/CSS/CSS_grid_layout/Auto-placement_in_grid_layout#g%C3%A9rer_les_%C3%A9l%C3%A9ments_qui_s%C3%A9talent_sur_plusieurs_pistes

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

Dans le § "Gérer les éléments qui s'étalent sur plusieurs pistes" il est écrit 
" .... on complète la disposition en indiquant que les éléments 1, 4 et 9 (4n+1) ...".

Il faudrait lire il me semble " ... on complète la disposition en indiquant que les éléments 1, 5 et 9 (4n+1) ...".

Je n'ai pas compris l'intérêt de la propriété `.wrapper div:nth-child(5)` car l'élément 5 est déjà ciblé par `.wrapper div:nth-child(4n + 1)`.

Si c'est pour introduire le § suivant il serait peut-être plus intéressant de choisir un autre élément par exemple le 4.

### What did you expect to see?

remplacer le 4 par 5

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/css_grid_layout/auto-placement_in_grid_layout`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/CSS_grid_layout/Auto-placement_in_grid_layout
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/css_grid_layout/auto-placement_in_grid_layout/index.md
* Last commit: https://github.com/mdn/translated-content/commit/23ea74fe6c9184a71441ee99828b044fca5cce49
* Document last modified: 2023-07-27T06:44:28.000Z

</details>

**Comment by SphinxKnight** [comment]
@DomOBU, j'ai proposé une PR pour l'erreur sur le `4n+1`. Quant au sélecteur `.wrapper div:nth-child(5)` dans l'exemple en question, il rajoute le positionnement "absolu" sur la grille de cet élément-là. La formulation suivante aurait été équivalente :

```
.wrapper div:nth-child(5) {
  grid-column-start: 1;
  grid-row-start: 1;
}
```
