### ISSUE TITLE
contain 条目中 ”尝试一下” 内容出现了翻译错误

### ISSUE THREAD

**Issue by MoShian90s** [mdn/translated-content#14859]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/contain

### 与此议题相关的小节或标题？

# 尝试一下

### 哪些信息是错误、无用或不完善的？

在 “备注： 为此属性使用 layout、paint、strict 或 content 值将创建：...” 的高亮块中，第 1 点，括号内出现了 ”`foxed` 的后代元素“ 的文字

![image](https://github.com/mdn/translated-content/assets/24494673/2eca6757-ce1f-4bcf-9698-5d454cda9899)

### 你期望看到什么？

![image](https://github.com/mdn/translated-content/assets/24494673/af346149-b9c1-4d2b-8f05-7a58ebac7ea1)

### 你有什么支持的链接、参考或引用？

https://developer.mozilla.org/zh-CN/docs/Web/CSS/contain#%E5%B0%9D%E8%AF%95%E4%B8%80%E4%B8%8B

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/contain`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/contain
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/contain/index.md
* Last commit: https://github.com/mdn/translated-content/commit/af62d2b26e16060b53ff17b91a50e8c6cbef3c27
* Document last modified: 2023-07-29T12:02:14.000Z

</details>

**Comment by yin1999** [comment]
这里的说明是正确的，请参见该文档后面的[示例](https://developer.mozilla.org/zh-CN/docs/Web/CSS/contain#%E5%B8%83%E5%B1%80%E5%B1%80%E9%99%90)，以及文档：[布局和包含块](https://developer.mozilla.org/zh-CN/docs/Web/CSS/Containing_block#%E7%A1%AE%E5%AE%9A%E5%8C%85%E5%90%AB%E5%9D%97)。

在示例中，你可以看到，因为“卡片 1”添加了 `contain: layout;` CSS 样式，而导致内部的 `position` 属性为 `fixed` 的元素被包含在了这个 div 内（这里的内部元素就是外面的 div 的后代），所以这里的解释没有问题。
