### ISSUE TITLE
Live sample under OOJS 3 should be removed

### ISSUE THREAD

**Issue by zhankuaiyue** [mdn/translated-content#14904]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Test_your_skills:_Object-oriented_JavaScript

### 哪些信息是错误、无用或不完善的？

[OOJS 3] (https:developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Test_your_skills:_Object-oriented_JavaScript#oojs_3)
Finally, we'd like you to start with the ES Shape class you created in the last task.

We'd like you to create a Square class that inherits from Shape, and adds a calcArea() method that calculates the square's area. Also set up the constructor so that the name property of Square object instances is automatically set to square, and the sides property is automatically set to 4. When invoking the constructor, you should therefore just need to provide the sideLength property.

Create an instance of the Square class called square with appropriate property values, and call its calcPerimeter() and calcArea() methods to show that it works ok.

Try updating the live code below to recreate the finished example:

X

### 你期望看到什么？

Hope to be able to make up the job code

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/objects/test_your_skills_colon__object-oriented_javascript`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Test_your_skills:_Object-oriented_JavaScript
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/objects/test_your_skills_colon__object-oriented_javascript/index.md
* Last commit: https://github.com/mdn/translated-content/commit/184f2b282be54a5c4c76c3184e5d52f20e06ff31
* Document last modified: 2023-08-02T23:52:02.000Z

</details>

**Comment by yin1999** [comment]
“OOJS 3” section has been removed from en-US. We should also remove [this part](https://github.com/mdn/translated-content/blob/b241e0192edcc92b0a6ab595bcb507ce1439d49f/files/zh-cn/learn/javascript/objects/test_your_skills_colon__object-oriented_javascript/index.md?plain=1#L42-L55) from Chinese.
