### ISSUE TITLE
示例网页代码疑惑

### ISSUE THREAD

**Issue by Chaya-Yellow** [mdn/translated-content#14937]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page

### 与此议题相关的小节或标题？

为 further info 的链接添加响应式图片

### 哪些信息是错误、无用或不完善的？

模仿响应式图片根据不同像素进行切换步骤，只能对FirefoxLogo图片起作用

### 你期望看到什么？

我想知道img标签中的srcset和size属性是否存在漏洞/缺陷，或者是否能够完善示例代码中的内容使它们能够更好的符合预期的完成响应式的要求，使得在a标签下的图片都能够在宽度小于480px的情况下都选择120的图片（通过开发者模式也能查看到）

### 你还想补充什么内容？

当我自己尝试srcset与size设置响应式图片的时候发现出现了仅在第一个img标签下的图片FirefoxLogo能够成功完成响应式，其他标签均不可以。想着可以从示例代码得到参考解答，但发现示例代码也存在同样的问题。
<img width="1520" alt="image" src="https://github.com/mdn/translated-content/assets/69381752/dab3a082-e63b-4bd2-9473-3191bd975100">
<img width="1509" alt="image" src="https://github.com/mdn/translated-content/assets/69381752/a8de09c4-30a4-4656-a457-a32c0247d116">
<img width="1507" alt="image" src="https://github.com/mdn/translated-content/assets/69381752/ad1cfe53-4e55-4dd1-8a2c-73fe2140155f">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/html/multimedia_and_embedding/mozilla_splash_page`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Mozilla_splash_page
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/html/multimedia_and_embedding/mozilla_splash_page/index.md
* Last commit: https://github.com/mdn/translated-content/commit/13ea7569d923b4f4b357abfbeff847e6a5e32b74
* Document last modified: 2023-05-23T01:28:50.000Z

</details>

**Comment by yin1999** [comment]
Closing this, as this question has been answered.
