### ISSUE TITLE
Prettier markdown files in GitHub Actions don't show the error

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#14955]
### MDN URL

N/A

### What information was incorrect, unhelpful, or incomplete?

When you have an error in a file in the GitHub Actions you can only see the filename, but nothing about the error, forcing to download the entired environment just to see what is happening

### What did you expect to see?

Details about the error

### Do you have any supporting links, references, or citations?

![imagen](https://github.com/mdn/yari/assets/13079269/6fdf5479-a070-4c28-9b5e-4c2024b22ecb)

**Comment by yin1999** [comment]
Related to [this discuession](https://github.com/orgs/mdn/discussions/428). We have set up [pr-check-lint_content](https://github.com/mdn/content/blob/main/.github/workflows/pr-check-lint_content.yml) workflow in mdn/content, and it could automatically create suggestions for formatting changes. I would like to port this to translated-content repo.

But before I start this work, I want to [further improve the workflow in content](https://github.com/yin1999/content/blob/pr-check/.github/workflows/pr-check-lint_content.yml), let's wait a few days. Sorry for the late.
