### ISSUE TITLE
Issue with "Введение в JavaScript": (short summary here please)

### ISSUE THREAD

**Issue by LexaWin** [mdn/translated-content#1509]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Introduction

#### What information was incorrect, unhelpful, or incomplete?
Error in the Russian translation.
..., чтобы вы могли написать сложное более сложное приложение.

#### Specific section or headline?
https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Introduction#hello_world

#### What did you expect to see?
Скорее всего первое слово "сложное" лишнее.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/javascript/guide/introduction`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Introduction
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/guide/introduction/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1d7af0a4a528dbd725b20e5ee530e4098f4e9106
* Document last modified: 2021-07-11T18:52:58.000Z

</details>

**Comment by mpstv** [comment]
Fixed in https://github.com/mdn/translated-content/pull/1526
