### ISSUE TITLE
Some localized version of "execCommand" page doesn't include deprecation warnings

### ISSUE THREAD

**Issue by Davilink** [mdn/translated-content#151]
Some localized version of https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand (this is the english version), doesn't include the deprecation notice and are missing the notice in the compatibility table too:
- french: https://developer.mozilla.org/fr/docs/Web/API/Document/execCommand
- espanol: https://developer.mozilla.org/es/docs/Web/API/Document/execCommand
- 한국어 (korean) : https://developer.mozilla.org/ko/docs/Web/API/Document/execCommand
- Polski : https://developer.mozilla.org/pl/docs/Web/API/Document/execCommand

**Comment by SphinxKnight** [comment]
I'll take care of the French page in the coming days. However, I think we should close this one afterwards as other locales are currently frozen.

**Comment by hochan222** [comment]
#519
