### ISSUE TITLE
ko: update files `web/glossary`

### ISSUE THREAD

**Issue by IMHOJEONG** [mdn/translated-content#15143]
### MDN URL

https://developer.mozilla.org/en-US/docs/Glossary

### What specific section or headline is this issue about?

web/glossary 파일에 대해서 번역하고자 합니다.

### What information was incorrect, unhelpful, or incomplete?

새로 추가된 파일들이 있고,

최신화 & sourceCommit을 추가하고자 합니다.

### What did you expect to see?

content 파일의 내용과 동일한 내용이 한국어로 보이기를 원합니다.

### Do you have any supporting links, references, or citations?

#14965 
#14968

두 개의 이슈를 참고해  `web/glossary` 폴더를 관리하고자 합니다.

### Do you have anything more you want to share?

sourceCommit 말고는 영어 버전이랑 sync되는 거를 폴더 내에서 찾아서 관리해야 하는 건지 궁금합니다.

계속해서 추적할 수는 없는 상황이 올 거 같아서 궁금해서 여쭈어 봅니다!
```[tasklist]
### `web/glossary` 알파벳 별 작업 정리
- [ ] https://github.com/mdn/translated-content/issues/15583
- [ ] https://github.com/mdn/translated-content/issues/15211
- [ ] https://github.com/mdn/translated-content/issues/15221
- [ ] https://github.com/mdn/translated-content/issues/15222
- [ ] https://github.com/mdn/translated-content/issues/15230
- [ ] https://github.com/mdn/translated-content/issues/15231
- [ ] https://github.com/mdn/translated-content/issues/15232
- [ ] https://github.com/mdn/translated-content/issues/15233
- [ ] https://github.com/mdn/translated-content/issues/15234
- [ ] https://github.com/mdn/translated-content/issues/15235
- [ ] https://github.com/mdn/translated-content/issues/15236
- [ ] https://github.com/mdn/translated-content/issues/15237
- [ ] https://github.com/mdn/translated-content/issues/15238
- [ ] https://github.com/mdn/translated-content/issues/15241
- [ ] https://github.com/mdn/translated-content/issues/15242
- [ ] https://github.com/mdn/translated-content/issues/15243
- [ ] https://github.com/mdn/translated-content/issues/15244
- [ ] https://github.com/mdn/translated-content/issues/15263
- [ ] https://github.com/mdn/translated-content/issues/15264
- [ ] https://github.com/mdn/translated-content/issues/15265
- [ ] https://github.com/mdn/translated-content/issues/15266
- [ ] https://github.com/mdn/translated-content/issues/15267
- [ ] https://github.com/mdn/translated-content/issues/15268
- [ ] https://github.com/mdn/translated-content/issues/15269
```

**Comment by SnowMarble** [comment]
기존 문서 sourceCommit 추가 + 미번역 문서 번역 까지 모두 하시는건가요? 😮

**Comment by IMHOJEONG** [comment]
@SnowMarble 님. 안녕하세요
`web/glossary` 부분은 어떻게 범위를 나누어야 할 지 기준이 안 서서, 양이 좀 많지만..

`기존 문서 sourceCommit 추가 + 미번역 문서 번역 까지 모두 하시는건가요?`
=> 저희가 언제까지 해야 한다는 deadline이 정확히 없어서, 현재 생각으로는 이슈에 정리해두고, 하나씩 번역하고 추가할 생각이었습니다.

혹시 glossary 부분 중 일부분을 하고 싶으신거면, 가져가셔도 괜찮으실 거 같습니다!

**Comment by SnowMarble** [comment]
아, 번역된 파일에서 sourceCommit을 추가하는 적업만 하더라도 양이 만만치 않은데, 이번 기회에 전부 작업하시는 거에 놀라서 여쭤본 거였습니다! 😸 저도 시간이 있을 때마다 힘을 보태보도록 하죠.. :) 🔥

**Comment by SnowMarble** [comment]
용어집은 내용이 많지 않아 한꺼번에 여러 파일을 수정해도 괜찮을 것 같습니다. 
그래서 glossary-a*, glossary-b* 과 같이 사전식으로 PR을 만들거나, 내용인 많은 경우(30개 초과) glossary-a*-1, glossary-a*-2 와 같이 작업하시는걸 제안드려보겠습니다:)

> PR 규칙 중: 사소한 변화 및 일괄적인 작업 PR에 대해서는 30개의 파일을 넘지 않는 것을 권장합니다.

**Comment by IMHOJEONG** [comment]
저도 그렇게 조정하는 게, 더 편할 거 같다고 생각이 듭니다. 

새로 추가된 파일들에 대해선, 번역 PR로 해서 변경사항 1개만 등록하겠습니다.

좋은 수정 사항 알려주셔서 감사합니다.

**Comment by IMHOJEONG** [comment]
현재 진행 상황 공유합니다
glossary-p, glossary-r, glossary-s, glossary-w 빼고 나머지 한국어 파일 최신화 완료하고, 커밋 대기중입니다.

glossary-p => glossary-r => glossary-s => glossary-w 순으로 이미 존재하고 있는 한국어 번역 하고

다시 a부터 한국어에는 없지만, 영어 버전에는 있는 새로운 파일을 만들고 번역 후,

각각 PR를 만들어 진행하는 방식으로 하겠습니다.

**Comment by SnowMarble** [comment]
안녕하세요, API나 Aajx와 같은 줄임말 혹은 고유명사외에 abstraction과 argument 등 번역이 가능한 용어의 페이지 제목을 영어 그대로 쓸지, 번역하여 쓸지 것, 아니면 영어와 번역을 동시에 쓰는것이 좋을지 의견을 구하고 싶습니다.

로케일 마다, 그리고 같은 로케일이더라도 문서마다 통일된 규칙이 없어서 이번에 규칙을 만들었으면 좋을것 같은데, 어떤것이 효과적일까요?
(일본은 가능한 경우 `영어 (일어)` 포멧으로 작성하는 것으로 보입니다!)

**Comment by IMHOJEONG** [comment]
@SnowMarble 님 안녕하세요
제 개인적인 의견으로는, 영어와 번역을 동시에 하는 게 낫다고 생각합니다. 그 이유로는, 영어를 한국어로 번역했을 때, 같은 의미를 가질 수 있지만, 정작 영어 스펠링이 다른 경우가 있고, 상황에 따라 같은 한국어로  다른 영어 단어를 사용하는 경우가 있었습니다. 
네. 저도 `영어(한국어)`로 작성하는 게 좋다고 생각이 듭니다.
@hochan222 님은 어떻게 생각하시는지, 다른 리뷰어 분들은 어떻게 생각하시는지 궁금합니다.

**Comment by IMHOJEONG** [comment]
@SnowMarble 님 안녕하세요
제 개인적인 의견으로는, 영어와 번역을 동시에 하는 게 낫다고 생각합니다. 그 이유로는, 영어를 한국어로 번역했을 때, 같은 의미를 가질 수 있지만, 정작 영어 스펠링이 다른 경우가 있고, 상황에 따라 같은 한국어로  다른 영어 단어를 사용하는 경우가 있었습니다. 
네. 저도 `영어(한국어)`로 작성하는 게 좋다고 생각이 듭니다.
@hochan222 님은 어떻게 생각하시는지, 다른 리뷰어 분들은 어떻게 생각하시는지 궁금합니다.

**Comment by hochan222** [comment]
@SnowMarble 님, @IMHOJEONG 님 안녕하세요.

한국 문서는 `한글(영어)` 형식을 사용하고 있습니다! 답변이 늦어져서 죄송합니다.

**Comment by hochan222** [comment]
+ glossary의 경우 단어에 대한 지침이기 때문에, 번역한 단어도 같이 작성해주는것이 좋아 보입니다.

**Comment by IMHOJEONG** [comment]
현재 진행 상황 공유드립니다.
일단 glossary 번역은 PR을 전부 만들어주었고, 앞으로 피드백 받아서, 추가해 두겠습니다.
