### ISSUE TITLE
ru: too long title on some pages

### ISSUE THREAD

**Issue by SnowMarble** [mdn/translated-content#15309]
I found some pages have too long title, which causes markdown lint to fail.
title must not have more than 120 characters.

![image](https://github.com/mdn/translated-content/assets/69508345/69dfdc87-3641-4924-835e-a20af6a47d0a)

- files/ru/web/javascript/reference/errors/already_has_pragma/index.md
- files/ru/web/javascript/reference/errors/cant_redefine_property/index.md
- files/ru/web/javascript/reference/errors/delete_in_strict_mode/index.md
- files/ru/web/javascript/reference/errors/identifier_after_number/index.md
- files/ru/web/javascript/reference/errors/invalid_for-in_initializer/index.md

**Comment by yin1999** [comment]
Is there any one who could have a look on this @mdn/yari-content-ru. This causes the [Markdownlint auto-fix workflow to fail](https://github.com/mdn/translated-content/actions/runs/5987757460/job/16242254227).
