### ISSUE TITLE
Функционал != Функциональность

### ISSUE THREAD

**Issue by BaranovskiyNE** [mdn/translated-content#15328]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Modules

### О какой части статьи или абзаце идёт речь?

везде

### Какая информация оказалась неверной, бесполезной или неполной?

Функционал != Функциональность, термин используется неправильно по всему тексту

### Как бы вы исправили?

Заменил бы Функционал на Функциональность.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/guide/modules/index.md
* Last commit: https://github.com/mdn/translated-content/commit/87b84697408fe38db03e0a6826e345cf76c6b703
* Document last modified: 2023-08-07T15:08:04.000Z

</details>

**Comment by leon-win** [comment]
@BaranovskiyNE , спасибо за внимательность!

Действительно, на этой странице довольно запутанный перевод понятия `module features`. Однако его сложно перевсти на русский элегантным и корректным способом))

Я заменил в нескольких местах "функционал" на "функциональность", где-то использовал слово "часть" (импортируемого) в #17431.

Но если говорить о слове "функционал" в целом, то думаю, что его использование в значении "функциональность" на данный момент уже можно считать фактической нормой, потому что оно употребляется часто (в сфере ИТ) и является понятным (если есть конктекст). Интересные комментарии попались в обсуждении этого слова)):
https://qna.habr.com/q/14928
https://vc.ru/flood/283778-funkcionalnost-ili-funkcional-obyasnyaem-kak-pisat
