### ISSUE TITLE
[ko] Usage of italics in Korean

### ISSUE THREAD

**Issue by alattalatta** [mdn/translated-content#1537]
한글은 기울임꼴에 적합하지 않습니다. 전용 이탤릭체가 없다는 것이 첫 이유이고, 문자의 조형이 (정)사각형인 것이 두 번째 이유입니다.

> 라틴알파벳의 이탤릭체에서는 그나마 글씨를 쓰는 손의 자연스러운 움직임을 반영하여 세로축이 기울어지는 현상이 차츰 나타난 것이지만, 한글은 글자시스템 자체와 전통적인 서법, 조판방식이 전적으로 다르기 때문에 억지로 기울이면 형태가 불안하고 이질적으로 보이면서, 한층 바람직하지 않은 문제를 일으킨다.

-- 유지원, "[라틴알파벳의 이탤릭체와 한글의 흘림체 비교연구](http://koreantypography.org/wp-content/uploads/thesis/kst_j0_1.pdf)"

특히 한국어에서는 조사가 다른 단어와 띄어쓰기 없이 붙어있으므로, 영어와 동일하게 사용할 경우 이렇게 글자가 글자를 침범하는 모습이 자주 보입니다.

![](https://user-images.githubusercontent.com/9212605/125643580-aace565d-ddfe-4a5b-8f7a-86f101d29390.png)
("문서의" 에서 "서"가 조사 "의"를 침범한 모습)

그래서 위키백과에서는 기울임꼴을 아예 배제합니다.

> 굵은 글씨는 중요한 경우(표제어 및 주요한 넘겨주기 등)에 사용합니다. 기울인 글씨 (이탤릭체)는 한글에 적용하지 않습니다. 또한, 불필요한 시각적 효과도 사용하지 않습니다.

-- "[위키백과:편집 지침](https://ko.wikipedia.org/wiki/%EC%9C%84%ED%82%A4%EB%B0%B1%EA%B3%BC:%ED%8E%B8%EC%A7%91_%EC%A7%80%EC%B9%A8)"

mdn/kuma 일 땐 언어별 스타일 시트가 별도로 존재해서, 한국어의 경우 `<em>`과 `<i>`에 `font-style: normal`이 지정돼있었습니다. 정작 코드블록 안에서도 이탤릭이 안 먹어서 좋은 방법은 아니었는데요...

가장 좋은건 위의 논문에서 말하듯 별도의 흘림체 글꼴로 보여주는 것이겠지만, 제가 찾아봤을 땐 본문에 적합한 글꼴도 없었고, 애초에 이제는 언어별 스타일 시트가 없으니까 곤란하겠구요, 그러니 그 대신 **본문의 `<em>`과 `<i>`를 작은따옴표로 대체하거나, 아예 생략**하는게 어떨까요?

---

> ... more complex than the previous two options, and *starting* each update will be blocked ...

... 앞선 두 개의 선택지보다 더 복잡하고, 각각의 업데이트를 '시작'하는 것 역시 블로킹...

> A pending promise can either be *fulfilled* with a value or *rejected* with a reason.

대기 중인 프로미스는 값과 함께 '이행'하거나, 사유와 함께 '거부'될 수 있습니다.

> Some famous server-side RDBMS are *MySQL*(or *MariaDB* which is a fork of it), *SQL Server*, and *Oracle Database*.

유명한 서버사이드 RDBMS로는 MySQL(또는 그 포크인 MariaDB), SQL Server, Oracle Database 등이 있습니다. [한영 혼용 시에도 이탤릭을 사용하지 않아야 합니다.]

---

주변에 다른 강조가 없을 땐 `<b>`를 쓰는게 더 좋아보이기도 하는데, 마크다운으로 넘어간다면 `<b>`와 `<strong>`을 선택하지 못하니까 안되겠구요. 작은따옴표로 살릴거냐, 아예 생략할거냐 정도는 번역자 재량으로 괜찮지 않을까...

예컨대 위 예시에서 세 번째의 경우, 한글 사이의 영문이라는 것 만으로 충분히 강조가 되므로 따옴표를 굳이 넣지 않았어요.

**Comment by hochan222** [comment]
톡방에만 남기기에는 아까운 내용인것 같기도하고, 빠른 진행을 위해서 톡방에서 오갔던 내용을 정리해보았습니다. @cos18 @pje1740 @GwangYeol-Im @yechoi42 

- **개인적으로는 기울임꼴을 글에서 많이 쓰기도 해서  이게 한국어를 사용하는 대부분의 사람들이 자주 쓰는 글형식이라고 생각하는데 혹시 이거에 대해서는 어떻게 생각하시나요?**
  > - 저도 이 이슈 보기 전까진 딱히 부자연스럽단 생각 없이 종종 사용해오긴 했습니다!
  > - 개인적으로 예전에 번역할 때는 가끔 이탤릭을 그냥 따옴표로 바꿨던 기억이 있어서 그런가 이슈에서 제안주신 방법이 맘에 들긴하네요! 
  
- **영어 본문에서는 어떤 의도로 이탤릭체를 쓰는 걸까요?🤔**
  > - 특정 단어를 강조하나, 볼드를 쓰기 애매한 경우에 사용하는 것으로 알고있습니다.
  > - 영어 이탤릭이 보통 강조하는 경우에 쓰이던데 가끔 동사 같은 데 해두면 번역문에는 그 강조를 적용하기 되게 어려운 경우가 많았던 기억도 있습니당.

- **이 규칙이 적용되면 이 규칙을 적용되지 않는 PR에 대해 모두 언급해야 하는게 좀 걱정되기도 합니다.**
  > - 이 부분은 저희가 앞으로 처리할 PR에 대해서만 처리를 하면 된다고 생각합니다. 문서는 방대하니까요.
  > - 점진적으로 적용해도 되지 않을까요 ㅎㅎ 피알 컨벤션에 남겨 놓아서 앞으로의 문서부터 수정하는 것도 좋을 듯해요.
  > - 일괄 적용이 애매하면 아예 생략하는 방향이 좋을 거 같긴하네요…!
  
- **그 외**
  > - 작은 따옴표로 대체하자는 의견 괜찮아보입니다.
  > - 피알 예시를 보니 아예 생략도 괜찮을 듯 하네요..!

**Comment by hochan222** [comment]
- 1. bold
> 주변에 다른 강조가 없을 땐 <b>를 쓰는게 더 좋아보이기도 하는데, 마크다운으로 넘어간다면 <b>와 <strong>을 선택하지 못하니까 안되겠구요. 

`<strong>`: 굉장히 중요한 요소를 표현(그 내용 강한 중요성, 심각성, 또는 긴급 성을 가지고 있음을 나타냅니다.)
`<b>`: 여분의 중요성없이 굵은 텍스트를 지정

markdown에도 `__text__` 와 `**text**` 가 있지만 bold로 표현하는데는 아무래도 힘들겠죠..?

- 2. `''`

저는 `''`를 사용하기보다 아에 생략하는게 좋아보입니다. 나중에 혹시.. 그럴일은 없겠지만 일괄적으로 변경해야될때 구분할수가 없어서 레거시로 남을 확률이 높다고 생각합니다. 하지만, 미래는 모르니까요!

- 3. '생략'
 
 결국 남은 방법은 생략.. 그래서 저는 생략이 좋다고 생각합니다.

**Comment by hochan222** [comment]
@alattalatta @mdn/yari-content-ko 아래 두가지 중 하나를 선택해야합니다. 의견 주실 수 있나요?

- 1. 생략한다.
- 2. 아래 두가지 규칙을 따른다.
  > - 한글일 경우 '' 를 <em> tag 대신에 기입한다.
  > - 한글이 아닐 경우 생략한다.

**Comment by alattalatta** [comment]
@hochan222 생략해서 곤란한 경우가 그렇게 많을 것 같지는 않지만 이런 경우는 있어요.

> PUT과 DELETE 메서드는 '안전'하지만 멱등성을 갖지는 않습니다. (HTTP Safe)

...다행히 위와 같은 경우에는 `{{Glossary('Safe', '안전')}}`을 할테니 괜찮겠네요. 다만 진짜 강조를 해야 하는 상황이면 아예 없지는 않을 것 같은데, 따옴표로 강조하고 PR로 소명하면 되지 않을까 함당.

결론은

> 1. 생략한다.
> 2. 아래 두 가지 규칙을 따른다.
>    - 한글일 경우 '' 를 <em> tag 대신에 기입한다.
>    - 한글이 아닐 경우 생략한다.

중 하나만 넣지 않고 둘 다 넣으면 되지 않을까요? 기본 방침은 생략

**Comment by hochan222** [comment]
늦게 답변드려서 죄송합니다.

좋습니다! 가이드 라인에 반영 후 해당 이슈 닫도록 하겠습니다.
