### ISSUE TITLE
не правильное отображение в русскоязычной документации

### ISSUE THREAD

**Issue by HeroOfSocks** [mdn/translated-content#15561]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error

### О какой части статьи или абзаце идёт речь?

Экземпляры объекта Error

### Какая информация оказалась неверной, бесполезной или неполной?

[Экземпляры объекта Error]
{{page('/ru/docs/Web/JavaScript/Reference/Global_Objects/Error/prototype', 'Description')}}
[Свойства]
{{page('/ru/docs/Web/JavaScript/Reference/Global_Objects/Error/prototype', 'Properties')}}
[Методы]
{{page('/ru/docs/Web/JavaScript/Reference/Global_Objects/Error/prototype', 'Methods')}}

### Как бы вы исправили?

оно должно отображать какие-то примеры или обьяснения, но по какой-то причине отображает эти строки

### Есть ли у вас какие-либо подтверждающие ссылки?

![image](https://github.com/mdn/translated-content/assets/141829579/6e95d1b7-df09-489c-a307-53d26f041df8)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/global_objects/error`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/global_objects/error/index.md
* Last commit: https://github.com/mdn/translated-content/commit/bbeb5398c2ab57da8445d441805d4dc4ff591766
* Document last modified: 2023-08-07T15:09:52.000Z

</details>

**Comment by HeroOfSocks** [comment]
возможно это просто незаконченная статья и это что-то типа заглушки, не знаю

**Comment by yin1999** [comment]
duplicate of #5715. We need to replace this macro with normal markdown content.
