### ISSUE TITLE
Issue with "<fieldset>: The Field Set element": (short summary here please)

### ISSUE THREAD

**Issue by Trigonometric** [mdn/translated-content#1557]
MDN URL: https://developer.mozilla.org/ru/docs/Web/HTML/Element/fieldset

#### What information was incorrect, unhelpful, or incomplete?

The pic is missing 
![image](https://user-images.githubusercontent.com/28106907/125880518-6a950759-eafc-43e7-9c34-06c87e8b0f1c.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/html/element/fieldset`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTML/Element/fieldset
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/html/element/fieldset/index.html
* Last commit: https://github.com/mdn/translated-content/commit/e90e80856baf145c1c677d1afda14ca103a3beb9
* Document last modified: 2021-07-14T15:05:08.000Z

</details>

**Comment by sashasushko** [comment]
It is not a picture. It's live code example:
![изображение](https://user-images.githubusercontent.com/4469056/129069656-621673f3-1164-48c6-a2e0-5ecc7b4b69b8.png)

Can you check it again? Maybe you had some network problems last time.

If problem still exist, please, add info about your location, internet provider and browser. And reopen this issue.

Thank you!
