### ISSUE TITLE
PNG est exclusivement sans perte

### ISSUE THREAD

**Issue by Rpnpif** [mdn/translated-content#15843]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/Media/Formats/Image_types

### What specific section or headline is this issue about?

png_portable_network_graphics

### What information was incorrect, unhelpful, or incomplete?

« _Le [PNG](https://developer.mozilla.org/fr/docs/Glossary/PNG) (prononcé "png") utilise une compression sans perte ou avec perte afin de fournir une compression plus efficace_ »

### What did you expect to see?

Le [PNG](https://developer.mozilla.org/fr/docs/Glossary/PNG) (prononcé "png") utilise une **compression sans perte**.

### Do you have any supporting links, references, or citations?

La version anglaise de cette page et
https://www.w3.org/TR/png/

### Do you have anything more you want to share?

Même problème sur https://developer.mozilla.org/fr/docs/Web/HTML/Element/Img#formats_dimage_pris_en_charge

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/media/formats/image_types`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/Media/Formats/Image_types
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/media/formats/image_types/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour le signalement @Rpnpif ! 
@BenjaminLesne a déjà ouvert une PR pour corriger tout ça :)
