### ISSUE TITLE
Орфографическая ошибка

### ISSUE THREAD

**Issue by wintermute28** [mdn/translated-content#15920]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/API/Element/classList

### О какой части статьи или абзаце идёт речь?

Описание toggle (String [,Boolean]) 

### Какая информация оказалась неверной, бесполезной или неполной?

Если заданный класс у элемента отсутствует, то он добавляется, если такой класс есть, то класс удаляется. Когда вторым параметром передаётся false указанный класс удаляется, при передаче true - добавляется. Если вторым аргументом **_переданётся_** undefined или переменная с typeof == 'undefined', поведение будет аналогичным вызову toggle с одним аргументом.

### Как бы вы исправили?

Если заданный класс у элемента отсутствует, то он добавляется, если такой класс есть, то класс удаляется. Когда вторым параметром передаётся false указанный класс удаляется, при передаче true - добавляется. Если вторым аргументом **_передаётся_** undefined или переменная с typeof == 'undefined', поведение будет аналогичным вызову toggle с одним аргументом.

### Хотите добавить что-то ещё?

Хочу выразить огромную благодарность создателям ресурса!

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/api/element/classlist`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Element/classList
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/element/classlist/index.md
* Last commit: https://github.com/mdn/translated-content/commit/8618c001ae354b8ae1a0f74e60e6fc95e0521bd9
* Document last modified: 2023-08-03T22:32:15.000Z

</details>

**Comment by leon-win** [comment]
Актуализировал перевод этой страницы (#16788). Получилось, что теперь этого текста совсем нет))) а описание методов можно найти на отдельных страницах или посмотреть примеры использования.
