### ISSUE TITLE
Can we build the site for a local live preview like `mdn/content`?

### ISSUE THREAD

**Issue by codersjj** [mdn/translated-content#16034]
see: https://github.com/mdn/content#build-the-site

**Comment by JasonLamv-t** [comment]
If you want to preview the localizations, refer to the [guide](https://github.com/mdn/translated-content/blob/997a6edd6f512ab83eaa99d8303d906130974eb3/CONTRIBUTING.md#link-translated-content).

**Comment by yin1999** [comment]
Please check the guide pointed by @JasonLamv-t. I think this would help (and going to close this issue).

If you have any other question, welcome to [contact us](https://developer.mozilla.org/en-US/docs/MDN/Community/Communication_channels).

**Comment by codersjj** [comment]
Okay, thanks!
