### ISSUE TITLE
Issue with "<tr> : l'élément de ligne d'un tableau": wrong closing tags

### ISSUE THREAD

**Issue by emeryro** [mdn/translated-content#1604]
MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/tr

#### What information was incorrect, unhelpful, or incomplete?

Code example uses wrong closing html tags (`</td>` instead of `</th>`). That's the case for most of the code example on the page

#### Specific section or headline?

```
<th>Margaret Nguyen</td>
(...)
<th>Edvard Galinski</td>
(...)
<th>Hoshi Nakamura</td>
```

#### What did you expect to see?

```
<th>Margaret Nguyen</th>
(...)
<th>Edvard Galinski</th>
(...)
<th>Hoshi Nakamura</th>
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/html/element/tr`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/tr
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/html/element/tr/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a202cd53d99359a85256c72dceb5c05d0f270f48
* Document last modified: 2021-07-16T00:36:29.000Z

</details>

**Comment by m4thieulavoie** [comment]
@SphinxKnight I hope it's fine I took the liberty to contribute a fix for this issue in https://github.com/mdn/translated-content/pull/1696 :+1: As per documentation I couldn't see anything preventing one to contribute a fix to an open issue.
Let me know :pray:

**Comment by SphinxKnight** [comment]
@emeryro Thanks for the report.
@m4thieulavoie Thanks a lot for the PR (I'll follow up there for the review) and that's no problem at all, I intended to tackle this one in the coming days but I'm glad you helped :)
