### ISSUE TITLE
HAY UN PEQUEÑO ERROR DE REDACTACIÓN EN EL CURSO DE HTML SUTIL PERO ESTA

### ISSUE THREAD

**Issue by Abraham0191** [mdn/translated-content#16211]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/HTML/Introduction_to_HTML/Getting_started

### ¿De qué sección específica o titular trata este problema?

Introducción a HTML

### ¿Qué información es incorrecta, inútil o incompleta?

deberías poder escribir algunos elementos y atributos. También deberías poder escribir algunos elementos y atributos.

### ¿Qué esperaba ver?

estaba haciendo el curso de html no espera ver ningun error, pero lo vi y quize comentalo para que no se quede ahí

### ¿Tiene algo más que quiera compartir?

no

**Comment by Graywolf9** [comment]
Hola! muchas gracias por reportar el error, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)
