### ISSUE TITLE
Aligner des éléments dans un conteneur flexible: typos

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#16226]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container

### What information was incorrect, unhelpful, or incomplete?

Bonjour,

§Aligner le contenu sur l'axe principal
§§L'alignement et les modes d'écriture
Il est écrit (3ème paragraphe):
"Dans l'exemple qui suit, on indique explicitement la valeur `rtl `pour la propriété `display `afin de forcer un mode d'écriture de droite à gauche."
Ne faudrait-il pas lire:
"Dans l'exemple qui suit, on indique explicitement la valeur `rtl `pour la propriété `direction `afin de forcer un mode d'écriture de droite à gauche.

A la dernière ligne de la page il y a un lien " Box Alignment Cheatsheet" qui ne fonctionne pas.

### What did you expect to see?

Ces points corrigés.

**Comment by tristantheb** [comment]
Bonjour,

Effectivement il y a eu un cafouillage à l'époque, possiblement dans des copier/coller, ça m'arrivait aussi ! Je vois pour caler une petite remise à jour de la page durant le week-end ;)
