### ISSUE TITLE
Maîtriser le passage à la ligne des éléments flexibles - paragraphe à réécrire

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#16279]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/CSS/CSS_flexible_box_layout/Mastering_wrapping_of_flex_items

### Sur quelle section/titre porte ce problème ?

https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Flexible_Box_Layout/Mastering_Wrapping_of_Flex_Items#cr%C3%A9er_des_goutti%C3%A8res_entre_les_%C3%A9l%C3%A9ments

### Quelle information était incorrecte, inutile ou incomplète ?

Bonjour,

Dans le §"Créer des gouttières entre les éléments" 
il est écrit:
- À l'avenir, nous pourrons utiliser row-gap et column-gap pour les boîtes flexibles, ..."
- ... nécessite l'utilisation de marges négatives sur le conteneur flexible ...

L'exemple n'utilise pas de marges négatives et utilise la propriété `gap`.

Le § correspondant de la page en-us est en phase avec l'example. Il serait nécessaire de le reprendre.

### Que vous attendiez-vous à voir ?

Corriger le §

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/css_flexible_box_layout/mastering_wrapping_of_flex_items`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/CSS_flexible_box_layout/Mastering_wrapping_of_flex_items
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/css_flexible_box_layout/mastering_wrapping_of_flex_items/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by tristantheb** [comment]
Bonjour,

Je vais lier cette page à #16226 pour la PR de correction, les deux étant de la même branche `/Web/CSS/CSS_Flexible_Box_Layout`, je regarderai les modifications nécessaires sur celle-ci plus en profondeur en même temps ;)

Merci pour la remontée !
