### ISSUE TITLE
Cas d'utilisation classiques de flexbox : utilité de la classe .flipped?

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#16299]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/CSS/CSS_flexible_box_layout/Typical_use_cases_of_flexbox

### Sur quelle section/titre porte ce problème ?

https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Flexible_Box_Layout/Typical_Use_Cases_of_Flexbox#inverser_la_position_de_lobjet_m%C3%A9dia

### Quelle information était incorrecte, inutile ou incomplète ?

Bonjour,

§Les objets média
§§Inverser la position de l'objet média

Qu'elle est l'utilité d'introduire la classe .flipped. ?
Si on ajoute la propriété `flex-direction: row-reverse;` dans la classe .media le résultat souhaité est obtenu.

Ai-je loupé quelque chose ?

### Que vous attendiez-vous à voir ?

Utilité ou inutilité de la classe .flipped ?

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/css_flexible_box_layout/typical_use_cases_of_flexbox`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/CSS_flexible_box_layout/Typical_use_cases_of_flexbox
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/css_flexible_box_layout/typical_use_cases_of_flexbox/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by tristantheb** [comment]
Salut !

La classe `.flipped` introduite ici est présentée comme un ajout à effectuer sur la classe `.media` pour inverser le sens de la ligne gérée avec la propriété Flex Box. Elle ne rappelle pas [comment utiliser des classes CSS](https://developer.mozilla.org/fr/docs/Web/CSS/Class_selectors) à l'écrit mais introduit le fait qu'on peut avoir plusieurs blocs `.media` (comme le veulent les classes sur leur usage) dont certains utilisent en complément `.flipped`.

Dans l'usage normal il serait bien d'utiliser des pseudos classes comme [`:nth-child()`](https://developer.mozilla.org/fr/docs/Web/CSS/:nth-child) sur le parent quand ça se répète comme l'exemple ci-dessous, mais dans l'idée, voilà ce que ça veut introduire quant à la réutilisation du CSS.

Exemple :
```html
<div class="media">
  <div class="image"><img src="MDN.svg" alt="MDN logo"></div>
    <div class="content">This is the content of my media object. Items directly inside the flex container will be aligned to flex-start.</div>
</div>
<div class="media flipped">
  <div class="image"><img src="MDN.svg" alt="MDN logo"></div>
    <div class="content">This is the content of my media object. Items directly inside the flex container will be aligned to flex-start.</div>
</div>
<div class="media">
  <div class="image"><img src="MDN.svg" alt="MDN logo"></div>
    <div class="content">This is the content of my media object. Items directly inside the flex container will be aligned to flex-start.</div>
</div>
<div class="media flipped">
  <div class="image"><img src="MDN.svg" alt="MDN logo"></div>
    <div class="content">This is the content of my media object. Items directly inside the flex container will be aligned to flex-start.</div>
</div>
<div class="media">
  <div class="image"><img src="MDN.svg" alt="MDN logo"></div>
    <div class="content">This is the content of my media object. Items directly inside the flex container will be aligned to flex-start.</div>
</div>
<div class="media flipped">
  <div class="image"><img src="MDN.svg" alt="MDN logo"></div>
    <div class="content">This is the content of my media object. Items directly inside the flex container will be aligned to flex-start.</div>
</div>
```

En espérant que mon explication soit plus claires et t'aide à comprendre pourquoi cette classe est introduite ici :)

**Comment by tristantheb** [comment]
Pas de soucis !

Bon codage ;)
