### ISSUE TITLE
Broken exemple on "Dialog" in French version

### ISSUE THREAD

**Issue by sizvix** [mdn/translated-content#16297]
### What information was incorrect, unhelpful, or incomplete?

The second exemple of the page https://developer.mozilla.org/fr/docs/Web/HTML/Element/dialog

### What did you expect to see?

The second dialog exemple doesn't work . It should open a dialog layout

**Comment by tristantheb** [comment]
Hello 👋🏻 / Bonjour 👋🏻 

Effectivement le contenu de l'exemple ne fonctionne pas correctement sur la version Française, il semblerait même que cette page requiert une mise à jour plus large.

Merci pour ce signalement !

---
Indeed, the content of the example doesn't work properly on the French version, and it seems that this page requires a larger update.

Thanks for reporting this!
