### ISSUE TITLE
Using_multiple_backgrounds example doesn't exist in Russian translation

### ISSUE THREAD

**Issue by clicman** [mdn/translated-content#1629]
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds

Example doen't work
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/1079535/126446159-72f7469c-07fc-4b69-b40f-8100a0a9bd97.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/css/css_backgrounds_and_borders/using_multiple_backgrounds`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Backgrounds_and_Borders/Using_multiple_backgrounds
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/css_backgrounds_and_borders/using_multiple_backgrounds/index.html
* Last commit: https://github.com/mdn/translated-content/commit/9f9acdf5611518844c9e2ed9281ad594f4459850
* Document last modified: 2021-07-19T20:59:29.000Z

</details>

**Comment by clicman** [comment]
Still an error. 
![Uploading 11E0B5EC-A197-4CF8-8DB5-02B41A12115F.png…]()

**Comment by clicman** [comment]
![C5B37888-DD0F-4D3F-BE80-135E539B4104](https://user-images.githubusercontent.com/1079535/128405419-31aabef8-e399-495c-9a01-af533a8e40be.png)

**Comment by mpstv** [comment]
@clicman i think this update is not in production yet.

More details: https://github.com/mdn/content#when-will-my-change-show-up-on-the-production-mdn-site
