### ISSUE TITLE
[ko] Markdown Guildline 만들기

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#1637]
이번에 새로 추가된 Markdown 에 대해 가이드라인을 작성하기 위한 이슈입니다. 공유해주실 경험이 있으시면 댓글로 해주세요 :)

나중에 가이드라인 작성시 PR에 해당 내용과 함께 Co-authored로 같이 commit하겠습니다!

**Comment by wisedog** [comment]
평소부터 궁금했던건데 `translation_of`은 반드시 붙여야할까요? md 파일에는 없는데 이게 어떤 용도로 쓰는지 정확하게 모르겠네요.

**Comment by hochan222** [comment]
> 평소부터 궁금했던건데 translation_of은 반드시 붙여야할까요? md 파일에는 없는데 이게 어떤 용도로 쓰는지 정확하게 모르겠네요.

@wisedog 문서화는 안되어있나봐요.ㅠ 찾아보니 https://github.com/mdn/yari/blob/main/content/document.js#L91 해당 부분에서 메타데이터로 쓰이고있습니다. 

https://github.com/mdn/yari/issues/2173#issuecomment-747494226 로 보아 리다이렉션과 관련이 있어보입니다.

**Comment by hochan222** [comment]
https://github.com/mdn/translated-content/pull/1773 와 https://github.com/mdn/translated-content/pull/2074 를 통해 Markdown 가이드가 완성되어서 해당 PR을 close 하겠습니다.
