### ISSUE TITLE
La traducción habla de :any, -moz-any etc... en vez de :is 

### ISSUE THREAD

**Issue by AlfonsoML** [mdn/translated-content#16406]
### MDN URL

https://developer.mozilla.org/es/docs/Web/CSS/:is

### ¿De qué sección específica o titular trata este problema?

Todo el contenido traducido está desactualizado

### ¿Qué información es incorrecta, inútil o incompleta?

Hay que quitar todo lo de :any y usar :is

### ¿Qué esperaba ver?

:is

### ¿Tiene algún enlace de apoyo, referencias o citas?

https://developer.mozilla.org/en-US/docs/Web/CSS/:is

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/css/_colon_is`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/:is
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/_colon_is/index.md
* Last commit: https://github.com/mdn/translated-content/commit/dc517b92f97675cfc5337b414eb19d27c3cb7ea4
* Document last modified: 2023-08-05T13:12:24.000Z

</details>

**Comment by Graywolf9** [comment]
Muchísimas gracias por el issue @AlfonsoML , era una actualización importante y necesaria de ver y hacer, esto debería quedar resuelto en: https://github.com/mdn/translated-content/pull/16536
