### ISSUE TITLE
zh-CN: Proofreading and update plan for the JavaScript `Set` section

### ISSUE THREAD

**Issue by JasonLamv-t** [mdn/translated-content#16465]
I plan to proofread and update the translation of the Javascript.Set section. Just so you know, anyone is welcome to contribute. If you find any issues with the Simplified Chinese Set section or have already submitted a PR, please mention me so that I can add your work to the progress list below:

- [x] overview, already synced with upstream.
- [x] constructor, in #16466.
- [x] @@iterator, in #16466.
- [x] @@species, in #16466.
- [x] add, in #16479.
- [x] clear, in #16479.
- [x] delete, in #16479.
- [x] entries, in #16502.
- [x] foreach, in #16716.
- [x] has, in #16479.
- [x] keys, in #16502.
- [x] size, in #16716.
- [x] values, in #16502.

**Comment by yin1999** [comment]
I'm going to close this issue as all the documents have been updated. Thanks @JasonLamv-t :tada:
