### ISSUE TITLE
Sélecteurs d'attribut: rédaction à modifier ?

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#16474]
### URL MDN

https://developer.mozilla.org/fr/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors

### Quelle information était incorrecte, inutile ou incomplète ?

Bonjour,

Dans §Sélecteur de présence et de valeur,
il est écrit "`li[class~="a"]` cible tout élément `<li>` dont l'attribut class contient a dans sa liste de valeurs (séparées par des espaces)."
Pour être plus factuel, la rédaction ne pourrait-elle pas être "`li[class~="a"]` cible tout élément `<li>` dont l'attribut class vaut a ou tout élément qui contient l’attribut class a dans sa liste de valeurs séparées par des espaces."

Dans §Sensibilité à la casse,
il est écrit "Sans le drapeau i, les valeurs seront identifiées selon la sensibilité à la casse de la langue du document — HTML est sensible à la casse."
Or HTML est insensible à la casse (https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Getting_started).
La rédaction de la fin de la phrase est-elle incomplète ou est-ce que le flag i rendrait HTML sensible à la casse ?

### Que vous attendiez-vous à voir ?

un retour sur ces points

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/css/building_blocks/selectors/attribute_selectors`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/CSS/Building_blocks/Selectors/Attribute_selectors
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/css/building_blocks/selectors/attribute_selectors/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by tristantheb** [comment]
Bonjour,

Il faudra que je me penche plus en profondeur sur ces questions, je reviens avec une réponse prochainement ;)

**Comment by SphinxKnight** [comment]
J'ai poussé une proposition de mise à jour avec #24127.
Si je suis d'accord que le passage sur la sensibilité à la casse de HTML était peu clair, je ne suis pas d'accord avec la première assertion. Si on édite l'exemple pour inclure `<p class="a">`, celui ne sera pas ciblé par `li[class~="a"]` et on ne peut donc pas dire "_tout élément qui contient l’attribut class_ a dans sa liste de valeurs séparées par des espaces"
