### ISSUE TITLE
error in the training container

### ISSUE THREAD

**Issue by Xxening** [mdn/translated-content#16486]
- [ ] Correction or update
there is an error in the code writing example on this page in the russian translation:
https://developer.mozilla.org/ru/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals

![image](https://user-images.githubusercontent.com/126268387/228848356-b3decab0-10c6-4a4b-82c4-a74df7bcf154.png)

The word "опаздывай" should be placed between <span></span> elements.

you should do something like this:

<p>Я рассчитываю на тебя. <strong>Не опаздывай!</strong></p>

**Comment by leon-win** [comment]
Fixed in #17371 :ok_hand: 

Thank you! :+1:
