### ISSUE TITLE
Image not loading

### ISSUE THREAD

**Issue by deipanema** [mdn/translated-content#16492]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
![image](https://user-images.githubusercontent.com/97335934/174730496-65e00cd3-b241-478e-8a56-5194f56c007b.png)

https://developer.mozilla.org/ko/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

**Comment by caugner** [comment]
FYI @mdn/yari-content-ko
