### ISSUE TITLE
 [ ] Correction or update

### ISSUE THREAD

**Issue by Kostya-x-pro** [mdn/translated-content#16494]
Change the typo in the article on the page:
https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Flexible_Box_Layout/Aligning_Items_in_a_Flex_Container
in line 426 of index.html there is a typo in the property **align-items** (for first:child) and it should have been **align-self**
![image](https://user-images.githubusercontent.com/104271118/201195678-41861a72-fd08-4cf0-9c58-77822a549601.png)

**Comment by leon-win** [comment]
Fixed in #17384 :ok_hand: 

Thank you! :+1:
