### ISSUE TITLE
Error en link

### ISSUE THREAD

**Issue by jorge2985** [mdn/translated-content#16493]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

Buenas tardes, en la página de [tutoriales](https://developer.mozilla.org/es/docs/Web/Tutorials#tutoriales_de_javascript) el acceso de [Programar - Los fundamentos](http://docs.webplatform.org/wiki/concepts/programming/programming_basics) no funciona

**Comment by caugner** [comment]
Verified that this is still an issue:

<img width="793" alt="image" src="https://github.com/mdn/translated-content/assets/495429/e969582e-a11d-4844-89cf-23c101311a1d">

<img width="1048" alt="image" src="https://github.com/mdn/translated-content/assets/495429/076c3ef2-4b25-4b9e-a691-9a89c73868f3">

The same applies to the "Introducción a HTML" link. in the [Nivel introductorio](https://developer.mozilla.org/es/docs/Web/Tutorials#nivel_introductorio) section.

Note that the [`en-US` locale version](https://developer.mozilla.org/en-US/docs/Web/Tutorials#introductory_level) links to corresponding sections on MDN, for example:

https://github.com/mdn/content/blob/6fa75c683af3831c0e988a9270e3b870852dc9a1/files/en-us/web/tutorials/index.md#L20
