### ISSUE TITLE
Sélecteurs de voisins généraux: un détail bizarre

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#16496]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/CSS/Subsequent-sibling_combinator

### Quelle information était incorrecte, inutile ou incomplète ?

Bonjour,

La date de mise à jour de la page est le 15 octobre 2020. Surprenant.

La date précédente de mise à jour était le 1er octobre 2022.

### Que vous attendiez-vous à voir ?

La mise à jour de la date

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/subsequent-sibling_combinator`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/Subsequent-sibling_combinator
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/subsequent-sibling_combinator/index.md
* Last commit: https://github.com/mdn/translated-content/commit/null
* Document last modified: 2020-10-15T21:04:26.332Z

</details>

**Comment by tristantheb** [comment]
Bonjour,

Les dates de mises à jour ne sont pas de notre ressort direct mais de l'actualisation de données effectuée par un algorithme. Les dates ne concordent pas obligatoirement à la réalité et c'est pour cela que nous utilisons d'autre méthode pour suivre les mises à jour des pages ;)

Cette page ayant besoin d'une mise à jour de contenu elle sera modifiée prochaienement !
