### ISSUE TITLE
link to arguments object, page not found

### ISSUE THREAD

**Issue by sanchezdev-1906** [mdn/translated-content#16490]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details

The link to *arguments* object in the page [developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments) redirects to [developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Function/es/Referencia_de_JavaScript_1.5/Funciones/arguments](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Function/es/Referencia_de_JavaScript_1.5/Funciones/arguments), the page doesn't exist.

The correct page is: [developer.mozilla.org/es/docs/Web/JavaScript/Reference/Functions/arguments](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Functions/arguments)

**Comment by caugner** [comment]
Verified that this is still an issue, see: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments#descripci%C3%B3n

<img width="1065" alt="image" src="https://github.com/mdn/translated-content/assets/495429/95694f3a-52f4-48da-b58b-e816f66c74d9">
