### ISSUE TITLE
mdn英文文档中说明let,const变量存在某种提升，中文文档还没有即时更新

### ISSUE THREAD

**Issue by cszhjh** [mdn/translated-content#16609]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/let

### 哪些信息是错误、无用或不完善的？

let 声明的变量只能在执行到声明所在的位置之后才能被访问。因此，let 声明通常被视为是非提升的。

### 你期望看到什么？

Some prefer to see let, const, and class as non-hoisting, because the [temporal dead zone](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/let#temporal_dead_zone_tdz) strictly forbids any use of the variable before its declaration. This dissent is fine, since hoisting is not a universally-agreed term. However, the temporal dead zone can cause other observable changes in its scope, which suggests there's some form of hoisting

### 你有什么支持的链接、参考或引用？

https://developer.mozilla.org/en-US/docs/Glossary/Hoisting

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/statements/let`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/let
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/statements/let/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d9fda438357b7ce1371db8141d650a8490f0018c
* Document last modified: 2023-09-02T01:06:52.000Z

</details>

**Comment by yin1999** [comment]
Hey @cszhjh. Can you tell what is wrong with the document? AFAIK, the Chinese translation you given above is correct.

**Comment by cszhjh** [comment]
> Hey @cszhjh. Can you tell what is wrong with the document? AFAIK, the Chinese translation you given above is correct.

你好，中文文档中在对let和var进行比较时，其中第二条表示let是被视为“非提升的”。我在英文文档中对于“提升”的描述中看到对于let、const提升的解释是存在某种提升，并在解释下方举例说明:
```javascript
const x = 1;
{
  console.log(x); // ReferenceError
  const x = 2;
}
```
如果 const x = 2 声明没有被提升，那么console.log(x)应该能够从外部作用域(const x = 1)读取到x。
对此我理解为这是变量提升，但由于暂时性死区导致该变量在其作用域内不能被访问。

**Comment by yin1999** [comment]
注意，文档中说的是“被**视为**是非提升的”，即它本质上的确是一种“提升”，但这种有别于将其值初始化为 `undefine` 的提升（暂时性死区）：

```js
console.log(x); // undefined
var x = 1;
```

所以，我们在这里写的是：*视为*是非提升的，视为说明的是“其与事实相反，但被大众所普遍接受”。

我们在此前的议题中有相关的讨论：mdn/translated-content#14774

**Comment by cszhjh** [comment]
> 注意，文档中说的是“被**视为**是非提升的”，即它本质上的确是一种“提升”，但这种有别于将其值初始化为 `undefine` 的提升（暂时性死区）：
> 
> ```js
> console.log(x); // undefined
> var x = 1;
> ```
> 
> 所以，我们在这里写的是：_视为_是非提升的，视为说明的是“其与事实相反，但被大众所普遍接受”。
> 
> 我们在此前的议题中有相关的讨论：#14774

我理解了，感谢您的评论！
