### ISSUE TITLE
when I use setRemoteDescription()  it occur error: uncaught (in promise) TypeError: Failed to execute 'setRemoteDescription' on 'RTCPeerConnection': cannot convert to dictionary.

### ISSUE THREAD

**Issue by ZRe-K** [mdn/translated-content#1660]
I use two client. One(control) to control the other(puppet).And the control side can send offer and candidate to the puppet,and the puppet can receive normally.The puppet can send its candidate to control,but when it send answer to control,the error occur.
Control side can receive the answer,but can't setRemoteDescription normally.
I can't get help from other place,so I try to get help from there.I'm sorry to disturb you.
Below are my code.
control:https://paste.ubuntu.com/p/JgN6SbJGhQ/
puppet:https://paste.ubuntu.com/p/Ny9q33wNJ3/
If you could give me a hand,thank you sincerely

**Comment by SphinxKnight** [comment]
@ZRe-K This repo is intended for the content of the documentation of APIs on [MDN](https://developer.mozilla.org/) and especially the localization/translation of this content.
I'm sorry but this is not the right place to ask for help regarding this. Maybe a forum or a site like StackOverflow would be better indicated.
