### ISSUE TITLE
Code de la fonction factorielle incomplet

### ISSUE THREAD

**Issue by aDjaffy** [mdn/translated-content#16622]
### URL MDN

https://developer.mozilla.org/fr/docs/Learn/JavaScript/Building_blocks/Return_values

### Sur quelle section/titre porte ce problème ?

Apprentissage actif: notre propre fonction avec valeur de retour

### Quelle information était incorrecte, inutile ou incomplète ?

Au paragraphe 2 : 
function factorial(num) {
  let x = num - 1;
  while (x > 1) {
    num *= x;
    x--;
  }
  return num;
}

### Que vous attendiez-vous à voir ?

Au point 2, le code de la fonction factorielle est faux. 
En effet : 0! = 1, et ce code retourne 0!=0. Dplus, la factorielle n'est possible que sur les postifs. Il faudrait ainsi ajouter :

  if (num < 0) return undefined;
  if (num === 0) return 1;

### Avez-vous des liens, références ou citations sur ce sujet ?

https://fr.wikipedia.org/wiki/Factorielle

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/javascript/building_blocks/return_values`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Building_blocks/Return_values
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/javascript/building_blocks/return_values/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by tristantheb** [comment]
Bonjour,

Merci pour la remontée, le contenu a besoin d'un petit rafraîchissement, je passerai dessus prochainement !
