### ISSUE TITLE
Lien cassé vers MSDN - Broken link to MSDN

### ISSUE THREAD

**Issue by NJullienSweet** [mdn/translated-content#16623]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/API/Element/scrollWidth

### Sur quelle section/titre porte ce problème ?

Références

### Quelle information était incorrecte, inutile ou incomplète ?

Le lien "scrollWidth sur MSDN" est cassé et nous redirige sur la page d'accueil de Microsoft Learn.
The link "scrollWidth sur MSDN" is broken and redirect us to the home page of the Microsoft Learn.

### Que vous attendiez-vous à voir ?

Je m'attendais à voir la documentation de Microsoft sur le sujet.
I expected to see Microsoft's documentation about this subject.

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/element/scrollwidth`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Element/scrollWidth
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/element/scrollwidth/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by tristantheb** [comment]
Bonjour,

Merci pour la remontée, la page aura le droit à un petit rafrachissement de son contenu !
