### ISSUE TITLE
Incorrect link to 'Other CSS tools'

### ISSUE THREAD

**Issue by timkovik** [mdn/translated-content#16652]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/CSS

### О какой части статьи или абзаце идёт речь?

https://developer.mozilla.org/ru/docs/Web/CSS#%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_%D0%B4%D0%BB%D1%8F_%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8_css

### Какая информация оказалась неверной, бесполезной или неполной?

Link in last list item incorrect

### Как бы вы исправили?

Find correct url or remove list item

### Есть ли у вас какие-либо подтверждающие ссылки?

https://developer.mozilla.org/ru/docs/Web/CSS#:~:text=%D0%9F%D1%80%D0%BE%D1%87%D0%B8%D0%B5%20%D0%B8%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B%20CSS.%20(en%2DUS)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/css`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/index.md
* Last commit: https://github.com/mdn/translated-content/commit/221da776300f714bb9107ba2b0195af3a2b7a45d
* Document last modified: 2023-08-03T23:06:17.000Z

</details>

**Comment by leon-win** [comment]
Действительно была непонятная ссылка сама на себя)) и вообще на этой странице сейчас 35 неправильных ссылок.
Поэтому создал #16787 с исправлением всех ссылок на странице, также актуализироал несколько блоков, привёл в соответствие с английской версией страницы.
