### ISSUE TITLE
exemples

### ISSUE THREAD

**Issue by jpv-1** [mdn/translated-content#16823]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/API/Device_orientation_events/Orientation_and_motion_data_explained

### Sur quelle section/titre porte ce problème ?

exemples html

### Quelle information était incorrecte, inutile ou incomplète ?

Bonjour. Serait il possible de mettre des liens vers des exemples. Je cherchais ce lien : https://mdn.mozillademos.org/en-US/docs/Web/API/Detecting_device_orientation$samples/Orientation_example?revision=1247741
mais il ne fonctionne plus (exemple de script détection de l’accéléromètre) . Merci

### Que vous attendiez-vous à voir ?

lien vers exemple de script détection de l’accéléromètre

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/device_orientation_events/orientation_and_motion_data_explained`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Device_orientation_events/Orientation_and_motion_data_explained
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/device_orientation_events/orientation_and_motion_data_explained/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by SphinxKnight** [comment]
@jpv-1 merci pour le rapport :) toutefois, je viens de passer sur la page https://developer.mozilla.org/fr/docs/Web/API/Device_orientation_events/Orientation_and_motion_data_explained pour l'améliorer/corriger et ne vois pas de référence aux exemples que vous mentionné. Est-ce bien la bonne URL ?

**Comment by jpv-1** [comment]
Bonjour,je suis désolé, j'ai beaucoup de mal avec en vrac : l'anglais, la programmation et github que je frequente tres rarement.En fait je suis tombé sur la mention de l'exemple par hasard sur une page de recherche. Mais en essayant de remonter sur l'origine, il semble qu'elle n'existe plus. En fait, à postériori, je ne suis même pas sûr que cet exemple soit issu de cette page ou bien des pages des propositions d'interface dans la colonne à gauche :  mes notions de programmation sont super anciennes j'ai du mal à comprendre ce qui est lié à la page ou aux  pages des interface. 
DeviceMotionEvent :Dans ces pages, je ne sais pas la différence entre "constructeur" et "proprietés" je ne sais pas si c'est la même instruction ou des instructions dérivées... je suis vraiment au niveau zero...

ce n'est peut être pas utile d'adapter ces pages aux débutants, ça semble s'adresser à un bon niveau, je ne sais pas...par contre, essayer de clarifier ou mettre des exemples de code, ce serait peut être utile. Je crois en avoir vu sur certaines pages 
mais en fait le poisson est trop gros pour moi, je vais lacher l'affaire.
Je vous remercie de m'avoir prêté attention. Si vous avez le temps de mettre des exemples pour d'autres plus patients que moi ou un peu plus avancé ou moi un jour où j'aurai progressé ce sera tres bien :-)
Merci encore
Bonne semaine.
JP
PS : mon projet etait de programmer une récup de points donnés par l'accélérometre d'un smartphone, le mettre dans un fichier et l'afficher sur un graphique. Si vous avez quelque chose de tout pret, le mettre en exemple serait un bonne chose, me l'envoyer aussi :-)




    Le mercredi 8 novembre 2023 à 12:37:48 UTC+1, SphinxKnight ***@***.***> a écrit :  
 
 


@jpv-1 merci pour le rapport :) toutefois, je viens de passer sur la page https://developer.mozilla.org/fr/docs/Web/API/Device_orientation_events/Orientation_and_motion_data_explained pour l'améliorer/corriger et ne vois pas de référence aux exemples que vous mentionné. Est-ce bien la bonne URL ?

**Comment by SphinxKnight** [comment]
Je réponds plus largement plus tard, mais dans le doute j'ai déjà proposé #16874 pour traduire l'ensemble des pages "guide" :)

**Comment by jpv-1** [comment]
Du coup j'y vois un peu plus clair ("ecouter" un "évenement" ça me parle) (https://pr16874.content.dev.mdn.mozit.cloud/fr/docs/Web/API/Device_orientation_events/Detecting_device_orientation)mais ça reste tres costaud pour moi.merci beaucoup!bonne soirée

    Le mercredi 8 novembre 2023 à 16:50:15 UTC+1, SphinxKnight ***@***.***> a écrit :  
 
 


Je réponds plus largement plus tard, mais dans le doute j'ai déjà proposé #16874 pour traduire l'ensemble des pages "guide" :)

**Comment by SphinxKnight** [comment]
Je me permets de fermer cette *issue*. En effet, pour traiter exactement la demande, il faudrait construire un tutoriel complet, d'abord en anglais, avant de le traduire en français, ce qui représente une tâche conséquente : / 
Pour vous aiguiller, je peux vous conseiller de lire : 

- https://developer.mozilla.org/fr/docs/Web/API/DeviceMotionEvent 
- https://developer.mozilla.org/fr/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API pour la partie du stockage côté client
- https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics pour la partie graphisme, mais une bibliothèque comme https://d3js.org/ vous aidera sans doute beaucoup

La logique devrait ressembler à : 

1. Surveiller les évènements DeviceMotionEvent avec un gestionnaire pour `devicemotion`
2. Enregistrer les données localement dans localStorage
3. Les afficher à l'écran dans un graphique (ex. en utilisant un modèle d3.js)

**Comment by jpv-1** [comment]
merci encore pour tout ça. Je vois nettement plus clair maintenant, merci de votre aide.Merci d'avoir clot l'issue.
Bonne fin de semaine à vous.
JP

    Le vendredi 10 novembre 2023 à 21:35:39 UTC+1, SphinxKnight ***@***.***> a écrit :  
 
 


Je me permets de fermer cette issue. En effet, pour traiter exactement la demande, il faudrait construire un tutoriel complet, d'abord en anglais, avant de le traduire en français, ce qui représente une tâche conséquente : /
Pour vous aiguiller, je peux vous conseiller de lire :
   
   - https://developer.mozilla.org/fr/docs/Web/API/DeviceMotionEvent
   - https://developer.mozilla.org/fr/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API pour la partie du stockage côté client
   - https://developer.mozilla.org/fr/docs/Learn/JavaScript/Client-side_web_APIs/Drawing_graphics pour la partie graphisme, mais une bibliothèque comme https://d3js.org/ vous aidera sans doute beaucoup

La logique devrait ressembler à :
   
   - Surveiller les évènements DeviceMotionEvent avec un gestionnaire pour devicemotion
   - Enregistrer les données localement dans localStorage
   - Les afficher à l'écran dans un graphique (ex. en utilisant un modèle d3.js)
