### ISSUE TITLE
“转义字符串中的字符”这部分最后的一个拓展链接“转义符号”链接到的内容不对

### ISSUE THREAD

**Issue by MonkeyDCang** [mdn/translated-content#16820]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/Strings

### 与此议题相关的小节或标题？

“转义字符串中的字符”

### 哪些信息是错误、无用或不完善的？

“转义字符串中的字符”这部分最后的一个拓展链接“转义符号”链接到的内容不对，是链接到了“字符串String”。

### 你期望看到什么？

同步英文文档翻译，移除过时/错误内容。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/first_steps/strings`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/Strings
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/first_steps/strings/index.md
* Last commit: https://github.com/mdn/translated-content/commit/3bd22c6a65f9a77e4cdd95ed4825330df9ddd710
* Document last modified: 2023-09-19T06:05:04.000Z

</details>

**Comment by yin1999** [comment]
英文文档已移除这部分内容
