### ISSUE TITLE
[Ko] Korean document about Promise.all() is not fully translated

### ISSUE THREAD

**Issue by broccolism** [mdn/translated-content#1684]
## What page(s) did you find the problem on?

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

## Specific page section or heading?
**Description**

![image](https://user-images.githubusercontent.com/45515332/126875876-e18593a9-8d6b-46d4-93b9-ff53dcd773eb.png)

## What is the problem?

As you might see above, Korean document about Promise.all method's description does not contain all content that is in english document. For example, there's no hyperlink to `Promise.allSettled` method.

## What did you expect to see?

Fully translated "description" section in Korean documentation.

## Did you test this? If so, how?

no test needed.

**Comment by hochan222** [comment]
@broccolism 님 안녕하세요!

이슈 주셔서 감사합니다. 많은 분들이 PR을 보내주시지만, 아직도 MDN에는 많은 레거시들이 남아 있습니다. 혹시, 직접 해당 이슈를 수정하는것에 관심 있으신가요? 있으시다면 다음 [(가이드 라인)](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md)을 참고해서 직접 수정하실 수도 있습니다..!

다시 한번 이슈 주셔서 감사합니다.

좋은 하루 보내세요 :)

**Comment by broccolism** [comment]
@hochan222 
안녕하세요! 코멘트 확인이 늦었네요 죄송합니다.
주말에 시간이 나면 가이드라인 참고해서 작업해보겠습니다.
알려주셔서 감사합니다!ㅎㅎ

**Comment by broccolism** [comment]
@hochan222 
안녕하세요. 이슈 관련된 풀리퀘 넣었습니다.
첫 PR이라 부족함이 많을 것 같습니다. 한번 확인 부탁드립니다!
