### ISSUE TITLE
新手跟做笑话生成器

### ISSUE THREAD

**Issue by id-daijiyu** [mdn/translated-content#16862]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/Silly_story_generator

### 与此议题相关的小节或标题？

醉了

### 哪些信息是错误、无用或不完善的？

我就想说下我遇到的问题。笑话生成器：列出来的步骤没有问题，但是对newStory字符串使用两次replace对我这个新手来说不太理解，以为两次replace都会做用于第一个占位符。前面教程没说，也许没看到。！！重点是！！我做到最后点击笑话生成按钮，却没反应，检查了几遍。最后去对源码，改了下replace，又对了好几遍，点击生成还是没反应，后面直接复制粘贴源码也没反应。醉了。原因：我是将js单独写在一个文件，然后在html头部src，导致先执行的js对html还没有加载出来的元素进行监听而导致报错。
md，*****，**，*****。浪费我的大好青春****。

### 你期望看到什么？

教程做的可以，但是章节最后代码实操，练习这块这个代码看上去很不舒服，代码字体很细。哦可以放大，那当我没说。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/first_steps/silly_story_generator`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/Silly_story_generator
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/first_steps/silly_story_generator/index.md
* Last commit: https://github.com/mdn/translated-content/commit/3bd22c6a65f9a77e4cdd95ed4825330df9ddd710
* Document last modified: 2023-09-19T06:05:04.000Z

</details>

**Comment by yin1999** [comment]
别有那么大火气，我们都是用爱发电。别人花费很多时间帮助翻译文档，你又是感叹号又是浪费你时间的，贡献者被你否定了会很高兴吗。建议你先看一下[开源礼节](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Open_source_etiquette)。

注意，提供的源码里面[有一个 defer 关键字](https://github.com/roy-tian/learning-area/blob/0b8fda3003f324c310b6cc09c0e4eab49a4976e4/javascript/introduction-to-js-1/assessment-finished/index.html#L11)。这保证了 js 代码会在 html完全加载后再执行。
