### ISSUE TITLE
Broken example link

### ISSUE THREAD

**Issue by gom59** [mdn/translated-content#16967]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Re-engageable_Notifications_Push

### Sur quelle section/titre porte ce problème ?

Link to "les exemples du livre de recettes des service workers"

### Quelle information était incorrecte, inutile ou incomplète ?

This link is broken:

https://github.com/mdn/serviceworker-cookbook/push-payload.html

### Que vous attendiez-vous à voir ?

I believe the proper link is:

https://github.com/mdn/serviceworker-cookbook/tree/master/push-payload

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/progressive_web_apps/tutorials/js13kgames/re-engageable_notifications_push`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/Progressive_web_apps/Tutorials/js13kGames/Re-engageable_Notifications_Push
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/progressive_web_apps/tutorials/js13kgames/re-engageable_notifications_push/index.md
* Last commit: https://github.com/mdn/translated-content/commit/0195096f9e13c74b97d7228b1ef9359e039fbbeb
* Document last modified: 2023-10-18T13:17:20.000Z

</details>

**Comment by cw118** [comment]
Thanks for the report! Now fixed by #16982 :)
