### ISSUE TITLE
Issue with "Array": (short summary here please)

### ISSUE THREAD

**Issue by FreezeNow** [mdn/translated-content#1697]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array

#### What information was incorrect, unhelpful, or incomplete?
数组实例的属性与方法的内容未正确渲染，页面显示如下内容
![image](https://user-images.githubusercontent.com/44660045/126925684-d26001a7-ea64-4300-a808-15588fd16da9.png)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/array/index.html
* Last commit: https://github.com/mdn/translated-content/commit/7d85c26efde01171c019905bc905140e952fe46a
* Document last modified: 2021-07-24T11:25:38.000Z

</details>

**Comment by yin1999** [comment]
@hochan222 This issue has been fixed in pr #2291. We should close this issue.
