### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by fast95** [mdn/translated-content#17017]
### URL MDN

https://developer.mozilla.org/fr/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web

### Sur quelle section/titre porte ce problème ?

Comment inclure une image SVG directement dans le code du document

### Quelle information était incorrecte, inutile ou incomplète ?

Le lien vers SVG Optimiser (http://petercollingridge.appspot.com/svg_optimiser) abouti vers une page en erreur.

### Que vous attendiez-vous à voir ?

Une page fonctionnelle.

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci @fast95 pour le signalement, j'en ai profité pour proposer une mise à jour globale sur #17043
