### ISSUE TITLE
Embed Live Sample without title attribute

### ISSUE THREAD

**Issue by ByronMike** [mdn/translated-content#17040]
### URL MDN

https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

### Sur quelle section/titre porte ce problème ?

Ajouter des informations d'assistance avec l'attribut title

### Quelle information était incorrecte, inutile ou incomplète ?

Le lien d'illustration ci-dessous ne dispose pas de l'attribut"title" et ne permet donc pas de visualiser le résultat : 

> Je suis en train de créer un lien vers [la page d'accueil de Mozilla](https://www.mozilla.org/fr/)

### Que vous attendiez-vous à voir ?

Le contenu de title apparaît dans une info-bulle quand le pointeur de souris passe sur le lien).

### Avez-vous des liens, références ou citations sur ce sujet ?

N/A

### Souhaitez-vous ajouter autre chose ?

N/A

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/html/introduction_to_html/creating_hyperlinks`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/html/introduction_to_html/creating_hyperlinks/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by tristantheb** [comment]
`chore:` refreshing content with live example and current en_US content

**Comment by Kvngfrizzy** [comment]
Nice
