### ISSUE TITLE
Chore: team maintenance, add new member to `ru` team

### ISSUE THREAD

**Issue by leon-win** [mdn/translated-content#17071]
Hello @mdn/mdn-community-engagement!

Recently I have had the opportunity to pay attention to open source projects, and I decided to devote it to MDN -- a project that gave me a lot of knowledge!
Therefore, I ask to be included in the list of contributors to the Russian version of MDN.
I will continue to improve translations and do reviews to `ru` locale.

**Comment by sashasushko** [comment]
@yin1999 I can approve it. @leon-win is helping a lot right now, and we need fresh blood too.

**Comment by Rumyra** [comment]
Hi @leon-win - you should have an invite to the team now 👍

**Comment by leon-win** [comment]
> Hi @leon-win - you should have an invite to the team now 👍

Hello @Rumyra!

I received and accepted the invitation, thank you :+1: 

I will continue to contribute to this wonderful and useful project!
