### ISSUE TITLE
 timetable-fixed.html有问题

### ISSUE THREAD

**Issue by teeery** [mdn/translated-content#17113]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Tables/Basics

### 与此议题相关的小节或标题？

动手练习：colgroup 和 col

### 哪些信息是错误、无用或不完善的？

 timetable-fixed.html有问题，在网页上没有背景颜色

### 你期望看到什么？

哪里出问题了

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/html/tables/basics`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Tables/Basics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/html/tables/basics/index.md
* Last commit: https://github.com/mdn/translated-content/commit/915795b21704a238855ff07a8a502c8f49054d8e
* Document last modified: 2023-09-12T08:12:08.000Z

</details>

**Comment by yin1999** [comment]
close in favour of #17148
