### ISSUE TITLE
这是上次问题的截图，请指教

### ISSUE THREAD

**Issue by teeery** [mdn/translated-content#17148]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/First_steps/How_CSS_is_structured

### 哪些信息是错误、无用或不完善的？

没有颜色改变

### 你期望看到什么？

有颜色改变

### 你有什么支持的链接、参考或引用？

<img width="646" alt="屏幕截图 2023-11-28 084428" src="https://github.com/mdn/translated-content/assets/141226684/9e721727-58a1-4e3f-ab3d-d93c6de794be">
<img width="498" alt="屏幕截图 2023-11-28 084645" src="https://github.com/mdn/translated-content/assets/141226684/b88b931a-afc0-495b-9d4c-b7db2192a3f1">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/css/first_steps/how_css_is_structured`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/CSS/First_steps/How_CSS_is_structured
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/css/first_steps/how_css_is_structured/index.md
* Last commit: https://github.com/mdn/translated-content/commit/448483b937d5ee30f6ed8d849c42d4d57454e6ad
* Document last modified: 2023-07-22T10:36:22.000Z

</details>

**Comment by yin1999** [comment]
请在[原议题](https://github.com/mdn/translated-content/issues/17113)中回复，而不是新开一个议题。

根据文章内容以及你的示例，这里是需要给 `<p>` 标签指定一个类，你需要这样写：

```html
<p class="special">将 <code>special</code> 类的样式应用到这个段落。</p>
```

你在截图中给出的是给 `<p>` 标签指定了一个布尔属性 `special`，当然无法应用 css 的类样式。

**Comment by yin1999** [comment]
问题已解决，我将关闭该议题。若有知识点方面的问题欢迎前往 [MDN 的 discord 频道](https://developer.mozilla.org/discord) 提问。
