### ISSUE TITLE
zh-CN: Proofreading and update plan for the JavaScript `SharedArrayBuffer` and `Atomics` sections

### ISSUE THREAD

**Issue by JasonLamv-t** [mdn/translated-content#17175]
As the continuance of my preceding work about the `ArrayBuffer` section in JavaScript, I am going to proofread and add/update the translations about the `SharedArrayBuffer` and `Atomics` sections.

```[tasklist]
### Tasks about the `SharedArrayBuffer` section
- [x] overview, in #17226.
- [x] constructor, in #17246.
- [x] `@@species`, in #17315.
- [x] byteLength, in #17334.
- [x] grow, in #17380
- [x] growable, in #17380
- [x] maxByteLength, in #17419
- [x] slice, in #17427
```

```[tasklist]
### Tasks about the `Atomics` section
- [x] overview, in #17575
- [x] add, in #17626
- [x] and, in #17628
- [x] compareExchange, in #17636
- [x] exchange, in #17636
- [x] isLockFree, in #17642
- [x] load, in #17640
- [x] notify, in #17650
- [x] or, in #17628
- [x] store, in #17640
- [x] sub, in #17626
- [x] wait, in #17650
- [x] waitAsync, in #17650
- [x] xor, in #17628
```

**Comment by JasonLamv-t** [comment]
@yin1999 Pls assign this issue to me, thank you!

**Comment by JasonLamv-t** [comment]
@jasonren0403, Thank you!

**Comment by JasonLamv-t** [comment]
Sorry for the late, I've been quite busy in the past two weeks. I will complete all the tasks in this issue this year.

**Comment by yin1999** [comment]
> Sorry for the late, I've been quite busy in the past two weeks. I will complete all the tasks in this issue this year.

Please don't apologize for this and thank you for your contribution to MDN :heart:

**Comment by yin1999** [comment]
This project is done. Thank you @JasonLamv-t
