### ISSUE TITLE
写错了单词

### ISSUE THREAD

**Issue by cainiao778** [mdn/translated-content#17307]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/null

### 与此议题相关的小节或标题？

第一内容段，简介部分

### 哪些信息是错误、无用或不完善的？

值 特指对象的值未设置。它是 JavaScript [基本类型](https://developer.mozilla.org/zh-CN/docs/Glossary/Primitive) 之一，在布尔运算中被认为是[falsy](https://developer.mozilla.org/zh-CN/docs/Glossary/Falsy)。null

### 你期望看到什么？

应该是被认为是false

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/operators/null`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/null
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/operators/null/index.md
* Last commit: https://github.com/mdn/translated-content/commit/bc729df0195047ad8943b6d852557581157cd9ed
* Document last modified: 2023-08-02T22:55:18.000Z

</details>

**Comment by yin1999** [comment]
可以更新一下中文文档，我们在其他文档中将 falsy 翻译为“假值”，这里更新内容翻译即可。
