### ISSUE TITLE
Función Callback Deprecated Content

### ISSUE THREAD

**Issue by dr1602** [mdn/translated-content#17418]
### MDN URL

https://developer.mozilla.org/es/docs/Glossary/Callback_function

### ¿De qué sección específica o titular trata este problema?

La sección que muestra el texto " or ejemplo, nuestro sencillo ejemplo de maps-example.html (ver en vivo) utiliza la API de Google Maps y la API de geolocalización para mostrar un mapa de la ubicación actual de su dispositivo. "

### ¿Qué información es incorrecta, inútil o incompleta?

La dar click a los hipervínculos en los textos: [maps-example.html](https://github.com/mdn/learning-area/blob/master/javascript/apis/introduction/maps-example.html) y [ver en vivo](https://mdn.github.io/learning-area/javascript/apis/introduction/maps-example.html) te redirigen pero a una página con el error 404.

### ¿Qué esperaba ver?

Más detalles sobre las funciones descritas en el párrafo, incluso un video esplicativo.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/glossary/callback_function`
* MDN URL: https://developer.mozilla.org/es/docs/Glossary/Callback_function
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/glossary/callback_function/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d690e82916e68b1d7576be2bd691c5c43c66b132
* Document last modified: 2023-11-13T20:51:35.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! muchas gracias por reportar el error. Como bien mencionas esa oración esta obsoleta y tendría que ser eliminada, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios.

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)
