### ISSUE TITLE
[ru] JS code example is not working

### ISSUE THREAD

**Issue by Vallek** [mdn/translated-content#17614]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/What_is_JavaScript

### О какой части статьи или абзаце идёт речь?

https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/What_is_JavaScript#sect1

### Какая информация оказалась неверной, бесполезной или неполной?

First example with "Player 1: Chris" is not working. Nothing is happening on click.

### Как бы вы исправили?

I tried looking into source but there's just some include that looks identical to en version. Also when I opened it on github or mdn.github.io it is working.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/javascript/first_steps/what_is_javascript`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/What_is_JavaScript
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/javascript/first_steps/what_is_javascript/index.md
* Last commit: https://github.com/mdn/translated-content/commit/62fca5df0172a34ad01dc659f29528d4bf5fa25d
* Document last modified: 2023-12-03T17:05:16.000Z

</details>

**Comment by leon-win** [comment]
Thanks, @Vallek !

Fixed in #17708
