### ISSUE TITLE
how to import a remote image

### ISSUE THREAD

**Issue by yuwangjuan** [mdn/translated-content#1761]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/import

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/statements/import`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/import
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/statements/import/index.html
* Last commit: https://github.com/mdn/translated-content/commit/f2c560577fe17103e74314e60d20472a757100c3
* Document last modified: 2021-07-28T00:49:01.000Z

</details>

**Comment by yuwangjuan** [comment]
I need to import image from another server or online link.

**Comment by yin1999** [comment]
ECMAScript module dose not support this. I think you are looking for [this](https://webpack.js.org/guides/asset-modules/).

**Comment by yin1999** [comment]
If you want to import a module with native ESM, please try `importmap`:

```html
<script type="importmap">
{"imports": {
	"vue": "//cdn.jsdelivr.net/npm/vue@3/dist/vue.esm-browser.prod.js",
	"element-plus": "//cdn.jsdelivr.net/npm/element-plus/dist/index.full.mjs",
	"firebase/app": "//www.gstatic.com/firebasejs/9.6.6/firebase-app.js",
	"firebase/analytics": "//www.gstatic.com/firebasejs/9.6.6/firebase-analytics.js",
	"firebase/messaging": "//www.gstatic.com/firebasejs/9.6.6/firebase-messaging.js"
}}
</script>
```

and then you can import a module in `javascript`:

```js
import { createApp } from 'vue'
import ElementPlus from 'element-plus'
```

**Comment by yin1999** [comment]
I'm going to close this issue, for not related to document problem.
