### ISSUE TITLE
use `flex 布局` and `grid 布局` instead of translating entirely in zh-CN  

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/translated-content#17672]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/CSS_layout/Flexbox

### 哪些信息是错误、无用或不完善的？

`Flexbox` 在标题中被翻译为“弹性盒子”，但是在后续内容中极少提及这个中文翻译，完全译成中文似乎是没有必要的。“flex 布局”似乎是更常见的说法。

我们即使要完全翻译，也建议将“弹性盒子”“网格”加上“布局”二字，这样比较完整。

### 你期望看到什么？

合适的翻译处理方式。

### 你有什么支持的链接、参考或引用？

https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox

这里又使用了 `flex 布局`。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/css/css_layout/flexbox`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/CSS/CSS_layout/Flexbox
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/css/css_layout/flexbox/index.md
* Last commit: https://github.com/mdn/translated-content/commit/38c1ebed2e4862e414cae7d534506931fdea688d
* Document last modified: 2023-11-30T02:35:32.000Z

</details>

**Comment by yin1999** [comment]
“Flex layout”其实是“Flexible layout”的简写，如果直接使用谷歌搜索相关的网页的话，也可以看到直接将其翻译为“弹性布局”的条目并不占少数。该文档正文部分的翻译仍来自于从前的 wiki 时代，需要完整更新并与其他文档的翻译保持一致。

我的建议是对它们进行翻译，这目前并不存在歧义。
