### ISSUE TITLE
为何与英文版差异那么大?

### ISSUE THREAD

**Issue by hezedu** [mdn/translated-content#17687]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Attr

### 哪些信息是错误、无用或不完善的？

[废弃的属性和方法](https://developer.mozilla.org/zh-CN/docs/Web/API/Attr#%E5%BA%9F%E5%BC%83%E7%9A%84%E5%B1%9E%E6%80%A7%E5%92%8C%E6%96%B9%E6%B3%95)英文版没有

### 你期望看到什么？

令人困惑，比如 `attributes` 说是废了，但查看 `Element.attributes` 又是好好的， 希望删除，和英文版保持一致。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/attr`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Attr
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/attr/index.md
* Last commit: https://github.com/mdn/translated-content/commit/0bb0afdd32ea4a78f05324bca6b47f963e7cff83
* Document last modified: 2023-11-19T16:18:59.000Z

</details>

**Comment by skyclouds2001** [comment]
主要是因为文档过多而且维护者数量也不是很多，所以很难做到翻译的文档完全与英文文档的同步
