### ISSUE TITLE
hover疑似クラスについてのページのBasic_exampleにCSSが入っておらず、動作していない

### ISSUE THREAD

**Issue by takayamaki** [mdn/translated-content#17680]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/CSS/:hover

### この問題に関する節や見出しはどこですか。

例→基本的な例→結果

### 不完全、不親切、不完全であった情報は何ですか。

EmbedLiveSampleマクロで生成されるLiveSampleにCSSが適用されておらず動作していません

### どう表示されるべきだと思いますか。

https://developer.mozilla.org/en-US/docs/Web/CSS/:hover のLiveSampleと同様

### 他に共有したいことはありますか。

related https://github.com/mdn/translated-content/issues/17651

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/css/_colon_hover`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/:hover
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/_colon_hover/index.md
* Last commit: https://github.com/mdn/translated-content/commit/a6becf78e84b5ec749d43b07a8e5179786971107
* Document last modified: 2023-10-23T12:19:07.000Z

</details>

**Comment by YujiSoftware** [comment]
調査しました。

```html
<section aria-labelledby="基本的な例">
    <h3 id="基本的な例"><a href="#基本的な例">基本的な例</a></h3>
    <div class="section-content">
        <h4 id="html">HTML</h4>
        <div class="code-example">（中略）</div>
        <h4 id="css">CSS</h4>
        <div class="code-example">（中略）</div>
        <h4 id="結果">結果</h4>
        <div class="code-example" id="sect2">
            <div class="example-header play-sample" id="sect3">（中略）</div>
            <iframe class="sample-code-frame" title="基本的な例" id="frame_basic_example" src="https://live.mdnplay.dev/ja/docs/Web/CSS/:hover/runner.html?id=basic_example" loading="lazy"></iframe>
        </div>
    </div>
</section>
```

`EmbedLiveSample` の第一引数には、サンプルコードを含むヘッダの id を指定します。
https://github.com/mdn/yari/blob/5376a5683ea632fe5f33bcb247d34240b3e56f71/kumascript/macros/EmbedLiveSample.ejs#L5

今回の場合、この第一引数に `Basic_example` を指定しています。
https://github.com/mdn/translated-content/blob/c25b23cc238c4d84bd5868d20c392a1fd6e97d1f/files/ja/web/css/_colon_hover/index.md?plain=1#L51

ただ、英語版では `<h3 id="basic_example">` があるのですが、日本語では翻訳していてる関係で `<h3 id="基本的な例">` となってしまっているため、ヘッダを見つけられません。

その場合、フォールバックを行っています。
https://github.com/mdn/yari/blob/5376a5683ea632fe5f33bcb247d34240b3e56f71/client/src/document/code/playground.ts?#L259

このフォールバックでは、 **親要素の直下にあるヘッダ（h1〜h5）を取得します。**
つまり、今回のページの場合は ** `<h4 id="html">HTML</h4>` を取得します。**
（英語版と異なる要素を取得してしまっています）
https://github.com/mdn/yari/blob/5376a5683ea632fe5f33bcb247d34240b3e56f71/client/src/document/code/playground.ts#L37-L46

その後、取得したヘッダ要素から次のヘッダ要素までの間にある <pre> の中身を取得します。
本来であれば、ここで h3 の次の div の中にある HTML/CSS を取得できるのですが、今回だと h4 の次の div の中にある HTML しか取得できません。

結果、HTML だけが適用された中途半端なライブサンプルになってしまっていました。

この挙動が、バグなのか仕様なのかは微妙なところです。
ちょっと、mdn/yari の方で対応できないかどうか聞いてみようと思います。

**Comment by YujiSoftware** [comment]
mdn/yari の方で経緯を調べたのですが、厄介そうです。
翻訳の問題があるので `EmbedLiveSample` の引数を省略したり、指定の要素がなかった場合に自動でコードを拾うようにしたかったようですが、h2 の下にある場合と h3 の下にある場合で DOM の構造が異なり、挙動を変えると壊れる恐れがあり保留になってるようです。

* mdn/yari#5005
* mdn/yari#4971

そのため、現状だと `EmbedLiveSample`  の引数を変えるしかなさそうです。

ただ、個人的には `Compat` マクロや `Specifications` マクロのように引数を省略できたほうがいいと思うので、なんとかしたいです…。

**Comment by YujiSoftware** [comment]
related #15814

**Comment by YujiSoftware** [comment]
related  #19209

**Comment by YujiSoftware** [comment]
refs #19012
