### ISSUE TITLE
Примеры кода без подсветки синтаксиса

### ISSUE THREAD

**Issue by Frostbite-time** [mdn/translated-content#17704]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Styling_tables

### О какой части статьи или абзаце идёт речь?

Графика и цвета

### Какая информация оказалась неверной, бесполезной или неполной?

Примеры кода без подсветки синтаксиса

### Как бы вы исправили?

Исправьте его стиль, чтобы он синтаксически выделялся правильно

### Есть ли у вас какие-либо подтверждающие ссылки?

https://github.com/mdn/translated-content/blob/main/files/ru/learn/css/building_blocks/styling_tables/index.md

**Comment by leon-win** [comment]
@Frostbite-time , благодарю!

Исправил в #17707 :ok_hand:
