### ISSUE TITLE
Issue with "SyntaxError: redeclaration of formal parameter "x"": (short summary here please)

### ISSUE THREAD

**Issue by ahmed00E** [mdn/translated-content#1789]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Errors/Redeclared_parameter

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/reference/errors/redeclared_parameter`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Errors/Redeclared_parameter
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/errors/redeclared_parameter/index.html
* Last commit: https://github.com/mdn/translated-content/commit/95d95574d926e04d95b5a1008f7c895ca68f5d9d
* Document last modified: 2021-07-28T23:54:49.000Z

</details>

**Comment by SphinxKnight** [comment]
@ahmed00E could you please add some more details? If this is not done in a timely manner, I'll have to close this one due to the lack of information.

**Comment by SphinxKnight** [comment]
@ahmed00E ?
