### ISSUE TITLE
Exemple interactif non fonctionnel: NoSuchKeyThe specified key does not exist.

### ISSUE THREAD

**Issue by JeromeDeBoysere** [mdn/translated-content#17920]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment

### Sur quelle section/titre porte ce problème ?

Exemple interactif

### Quelle information était incorrecte, inutile ou incomplète ?

L'exemple indique: NoSuchKeyThe specified key does not exist.

### Que vous attendiez-vous à voir ?

Un exemple fonctionnel

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/operators/nullish_coalescing_assignment`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/operators/nullish_coalescing_assignment/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1a4be8c32441258acc4a8f3cc052b2f58c2ebc68
* Document last modified: 2023-07-28T08:49:33.000Z

</details>

**Comment by yin1999** [comment]
Replace [this line](https://github.com/mdn/translated-content/blob/6d526d2526f73238140b4a8c0ea71dd327607084/files/fr/web/javascript/reference/operators/nullish_coalescing_assignment/index.md?plain=1#L10) with the [line in en-US](https://github.com/mdn/content/blob/30a4f025c986109509d5f71d7a221581dd8aed9f/files/en-us/web/javascript/reference/operators/nullish_coalescing_assignment/index.md?plain=1#L12) could resolve this.
