### ISSUE TITLE
[fr] Learn - HTML - Getting started : error in example "Single or double quotes?"

### ISSUE THREAD

**Issue by synchronicma** [mdn/translated-content#17954]
### MDN URL

- upstream: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#single_or_double_quotes
- fr: https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Getting_started#guillemets_simples_ou_doubles

### What specific section or headline is this issue about?

Single or double quotes?

### What information was incorrect, unhelpful, or incomplete?

The 2nd example must use single quote instead of double quote like this :
`<a href='https://www.example.com'>A link to my example.</a>`

Same error in french version.

### What did you expect to see?

Two examples like this :
`<a href="https://www.example.com">A link to my example.</a>`
`<a href='https://www.example.com'>A link to my example.</a>`

**Comment by yin1999** [comment]
Hey @synchronicma. The content in en-US seems to be right:

![image](https://github.com/mdn/translated-content/assets/15844309/63482dfc-9c8f-407c-a6e2-90292df1033b)

While in fr locale, I found the example is not correct (This has been modified by the prettier format tool: #14469). The solution is using `html-nolint` language code and modify the first row of [this code example](https://github.com/mdn/translated-content/blob/fb2c73820ecdc6ccadb9eeb193f995f9add2753e/files/fr/learn/html/introduction_to_html/getting_started/index.md?plain=1#L465-L469) (we may also replace the `http` schema to `https`):

````md
```html-nolint
<a href='https://www.exemple.com'>Un lien vers mon exemple.</a>

<a href="https://www.example.com">Un lien vers mon exemple</a>
```
````

**Comment by SphinxKnight** [comment]
thanks @synchronicma for the report, @yin1999 for pointing to the fix and @tirthrami02 for the fix :)
