### ISSUE TITLE
[fr] Valeur par défault de browser_action.default_area différente de la documentation en anglais

### ISSUE THREAD

**Issue by pthebaul** [mdn/translated-content#17994]
### URL MDN

https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action

### Sur quelle section/titre porte ce problème ?

https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action#syntaxe

### Quelle information était incorrecte, inutile ou incomplète ?

Sur la version anglais de la page browser_action, la valeur par défault de default_area semble être "menupanel", tandis qu'en français, elle semble être "navbar".

### Que vous attendiez-vous à voir ?

La même valeur par défaut en anglais et en français.

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/mozilla/add-ons/webextensions/manifest.json/browser_action`
* MDN URL: https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_action
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/mozilla/add-ons/webextensions/manifest.json/browser_action/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by quentin-rey** [comment]
Trouvé sur le repo d'origine :

- Issue : mdn/content#23797
- PR : mdn/content#24086

La valeur par défaut semble être menupanel depuis Firefox 109 :

> Firefox 109 changed this default to the Extensions button drop-down or, if the user has set [extensions.unifiedExtensions.enabled](url) to false, the overflow menu. In effect, the default now behaves the same as "menupanel".
See: [bug 1799947](https://bugzilla.mozilla.org/show_bug.cgi?id=1799947).
