### ISSUE TITLE
Irrelevant information

### ISSUE THREAD

**Issue by StepanovAndrii** [mdn/translated-content#18030]
> Note: There is also a newer value [revert](https://developer.mozilla.org/ru/docs/Web/CSS/revert), which has limited browser support.

As far as I understand, it already has enough support

**Comment by yin1999** [comment]
Hey @StepanovAndrii. Could you tell where did you find this sentence? Is it on MDN website?

**Comment by yin1999** [comment]
As there is no feedback within two weeks, I'm going to close the issue for now. Feel free to append information and I will reopen the issue :)
