### ISSUE TITLE
chore(zh): Invite new member to l10n-zh team

### ISSUE THREAD

**Issue by jasonren0403** [mdn/translated-content#18047]
Hello @mdn/yari-content-zh,

@JasonLamv-t has done a lot of great job in contributing JavaScript content in `zh-CN` locale, let's add him to localization team to make content better.

**Comment by yin1999** [comment]
I agree with this :)

**Comment by bsmth** [comment]
Welcome @JasonLamv-t - ✅ you should have an invite to join `@mdn/yari-content-zh` now.

It's great to have you on board! 🙌🏻

**Comment by JasonLamv-t** [comment]
Hi, @bsmth. I still have not received an invite. Should I check my inbox of GitHub and Email?

**Comment by awxiaoxian2020** [comment]
@JasonLamv-t I think you can check that @mdn/yari-content-zh is visible for you.

**Comment by JasonLamv-t** [comment]
> @JasonLamv-t I think you can check that @mdn/yari-content-zh is visible for you.

Oops. I am afraid not. I can't see @mdn/yari-content-zh as a user, repo, or other thing else for me.

**Comment by bsmth** [comment]
> Hi, @bsmth. I still have not received an invite. Should I check my inbox of GitHub and Email?

You should have received an email. Can you check again, I can confirm I see a pending invite to join the team.

**Comment by JasonLamv-t** [comment]
> You should have received an email. Can you check again, I can confirm I see a pending invite to join the team.

Thank you very much! I have newly received the invite and have already accepted it. Thank you all.
