### ISSUE TITLE
ソースコードに書かれている画像ファイルのサンプルがない

### ISSUE THREAD

**Issue by educator-art** [mdn/translated-content#18059]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations

### この問題に関する節や見出しはどこですか。

アニメーションする太陽系

### 不完全、不親切、不完全であった情報は何ですか。

ソースコード書かれている太陽と月と地球の画像ファイルが見当たらないので試すことが出来ない
sun.src = "canvas_sun.png";
moon.src = "canvas_moon.png";
earth.src = "canvas_earth.png";

### どう表示されるべきだと思いますか。

サンプルを試せる画像ファイルのリンクを提示するべきである。
もしくは、著作権、ライセンスの関係で画像ファイルを提示しない場合は理由を示すべきである。

### 補足情報となるリンク、参考資料、引用文献はありますか。

なし

### 他に共有したいことはありますか。

サンプルの画像ファイルがあるか他のページを探したが見つけられなかった。
必要な情報が他のページに書かれている場合は一言引用とリンクがあるだけでもわかりやすい。
検索者はtopページから読むとは限らない。ユーザーのPCで試せないコードを載せておくのに意味はあるのだろうか？

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/canvas_api/tutorial/basic_animations`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/canvas_api/tutorial/basic_animations/index.md
* Last commit: https://github.com/mdn/translated-content/commit/2ede30d2ddd8f86d3383615b524375181dd8c01c
* Document last modified: 2023-08-24T14:52:09.000Z

</details>

**Comment by YujiSoftware** [comment]
@educator-art 
今、私の方でページを開いたら画像が表示されました。
（Ubuntu の Firefox 121.0.1 で確認）

それぞれの画像の URL は、以下のとおりです。
* https://live.mdnplay.dev/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_sun.png
* https://live.mdnplay.dev/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_moon.png
* https://live.mdnplay.dev/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_earth.png

切り分けのために確認したいのですが、今でも表示されませんか。
また、英語版（https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_animations）でも同様でしょうか。

**Comment by educator-art** [comment]
@YujiSoftware 

ご返信ありがとうございます、頂いたURLで開くことができました。
> それぞれの画像の URL は、以下のとおりです。
https://live.mdnplay.dev/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_sun.png
https://live.mdnplay.dev/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_moon.png
https://live.mdnplay.dev/ja/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_earth.png

また、英語版でも画像ファイルは開けました。
>https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_sun.png
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_moon.png
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Basic_animations/canvas_earth.png

ドキュメントのURLの末尾に画像ファイル名を追加すると開くことが出来るのですね。
基本的なことなのかもしれませんがドキュメントから読み解くことが出来ずに困っておりました。ありがとうございます。

**Comment by mfuji09** [comment]
解決したようですので、クローズします。
