### ISSUE TITLE
Неверное значение this в одном из примеров

### ISSUE THREAD

**Issue by MaxIV20** [mdn/translated-content#18073]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/this

### О какой части статьи или абзаце идёт речь?

Раздел "Стрелочные функции"

### Какая информация оказалась неверной, бесполезной или неполной?

Третий блок кода с примером, а именно:

// Но будьте осторожны, если вы ссылаетесь на метод obj, не вызывая его
var fn2 = obj.bar;
// Вызов this стрелочной функции изнутри метода bar вернёт теперь window,
// потому что он следует за this из fn2.
console.log(fn2()() == window); // true

В данном случае значение this будет зависеть от режима исполнения.
В нестрогом да, this === window, но в строгом будет undefined (т.к. это обычный вызов функции). 

### Как бы вы исправили?

Написать, что this будет как при простом вызове функции, т.е. зависеть от режима исполнения и написать следующий пример:
console.log(fn2()()) // window в нестрогом режиме, undefined в "use strict".

### Есть ли у вас какие-либо подтверждающие ссылки?

Это указывается в самой статье выше.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/operators/this`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/this
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/operators/this/index.md
* Last commit: https://github.com/mdn/translated-content/commit/ea84746aa880c3e7f5076dc4d7e4e94af171c348
* Document last modified: 2024-01-06T23:57:34.000Z

</details>

**Comment by leon-win** [comment]
Привет, @MaxIV20!

Благодарю за желание улушить MDN и подробное описание ошибки :+1: 

Я решил обновить перевод этого подраздела, чтобы исправить неточность и привести его в соответствие с английской версией: #18092

Посмотри, пожалуйста, изменения. Некоторые обороты очень трудно переводить, но они и в оригинале перегруженно читаются))

**Comment by MaxIV20** [comment]
Привет, @leon-win.
Сейчас стало понятнее, особенно аналогия замыкания для this хороша.
Спасибо!
