### ISSUE TITLE
ja: typo in ウェブストレージ API の使用 page

### ISSUE THREAD

**Issue by KKamishima** [mdn/translated-content#18178]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API

### 不完全、不親切、不完全であった情報は何ですか。

> > **メモ:** ウェブストレージ API (`setItem`, `getItem`, `removeItem`, `key`, `length`) の使用が推奨されているのは、単純なオブジェクトをキーと値の格納崎として使うという[落とし穴](https://2ality.com/2012/01/objects-as-maps.html)を防ぐためです。

### どう表示されるべきだと思いますか。

typo: 格納崎 -> 格納先

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/web_storage_api/using_the_web_storage_api`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Web_Storage_API/Using_the_Web_Storage_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/web_storage_api/using_the_web_storage_api/index.md
* Last commit: https://github.com/mdn/translated-content/commit/bb060dd49d972958c18befd2745a9a9db7203214
* Document last modified: 2023-09-08T14:01:59.000Z

</details>

**Comment by Ryoga-exe** [comment]
https://github.com/mdn/translated-content/commit/cb813f1e58101301486f9ed93e5cab0cccc6d3a9 で修正済みなように見えます
