### ISSUE TITLE
fetchpriority在简体中文标注错误

### ISSUE THREAD

**Issue by bddjr** [mdn/translated-content#18208]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/link

### 哪些信息是错误、无用或不完善的？

importance 可能是错误的

### 你期望看到什么？

应当改为 fetchpriority

### 你有什么支持的链接、参考或引用？

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#fetchpriority

### 简体中文：

![image](https://github.com/mdn/translated-content/assets/109646559/fbc8e3c0-9bd0-4ab7-9969-da180a444b29)

***
### en-US:

![image](https://github.com/mdn/translated-content/assets/109646559/896a7168-71be-4fee-8987-1334a97a060e)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/html/element/link`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/link
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/html/element/link/index.md
* Last commit: https://github.com/mdn/translated-content/commit/97fd5e22b6af3a33db4f99cb8dd075e43717e46b
* Document last modified: 2024-01-31T04:43:26.000Z

</details>

**Comment by skyclouds2001** [comment]
估计是文档长时间没更新的锅
