### ISSUE TITLE
如何成为 mdn content 的中文贡献者

### ISSUE THREAD

**Issue by familyboat** [mdn/translated-content#18204]
哈喽，我是 mdn content 的受益者。我希望将 mdn content 的优质内容带给中文世界。我曾经尝试过独自对部分内容进行翻译，但是在过程中，难免会遇到阻碍，导致翻译工作无法坚持下去。
在翻译过程中，让我感到无法正确处理的事有：专有名词的翻译（整个中文文档中对相同的专有名词存在不同的翻译，会让我感到很疑惑）；中文的译文过于直译，不太符合中文的语言习惯。
我需要借助社区的力量，帮助我进入翻译这个领域。
谢谢。

**Comment by yin1999** [comment]
MDN 是开放的社区，任何人都可以*直接*为 MDN 的文档做出贡献。MDN 文档的贡献流程其实很简单：

1. 修改对应文档的 markdown 内容（要找到对应的 markdown 内容，最简单的方法是点击每个文档页面最下方的“Edit the page on GitHub”链接。
2. 修改内容并提交 PR

详细的流程可参阅文档：[拉取请求的提交和审查指南](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Pull_requests)。

MDN 使用了许多专有的宏和内容格式，这一块内容相对较为复杂，我建议首先查看[我们的翻译指南](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md)，其中相对简单地介绍了常见的问题和排版格式。

有关更加详尽的贡献指南，欢迎访问 [MDN 有关贡献的指南部分](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Contributing)。

**Comment by yin1999** [comment]
Closed this issue as this is not a content issue. Feel free to [ask for help](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Communication_channels).
