### ISSUE TITLE
[zh-cn]: 向翻译指引中增加新的术语

### ISSUE THREAD

**Issue by skyclouds2001** [mdn/translated-content#18211]
向翻译指引中增加新的术语

在翻译 web/api 部分时候，有一些片段标题术语的翻译并没有决定，比如说：

- constructor
  - *构造函数* 和 *构造方法* 都有在使用，建议统一为 *构造方法*，与常见的 *静态方法/实例方法* 一致
- value
  - 常见翻译为 *值*
- syntax
  - 常见翻译为 *语法* （与 Formal syntax 的翻译 *形式语法* 一致）
- return value
  - 常见翻译为 *返回值*
- event type
  - 常见翻译为 *事件类型*
- description
  - 翻译为 *描述*？
- concepts and usage
  - 翻译为 *概念和用法*？
- handler
  - 一般翻译为 *处理器*

参见 https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types

**Comment by yin1999** [comment]
有关第一点——constructor，我倾向于翻译为构造函数。根据维基百科的描述，我们翻译为构造函数和构造方法均可。但站在历史的角度上看，我们应该选择大部分人选择的翻译——“构造函数”，MDN 中目前仅有 20 多处使用的翻译为“构造方法”，其他均为“构造函数”。本身对于其他的静态方法和实例方法，英文文档均会使用“method”后缀，于该词汇仍有不同之处。

关于其他几个词汇的翻译我基本赞同，只是大部分词汇的翻译大家应该都可以达成共识，我们也许暂时不会考虑将其中的一部分收纳入词汇表中（如“value”、“return value”等）。

**Comment by skyclouds2001** [comment]
> 有关第一点——constructor，我倾向于翻译为构造函数。根据维基百科的描述，我们翻译为构造函数和构造方法均可。但站在历史的角度上看，我们应该选择大部分人选择的翻译——“构造函数”，MDN 中目前仅有 20 多处使用的翻译为“构造方法”，其他均为“构造函数”。本身对于其他的静态方法和实例方法，英文文档均会使用“method”后缀，于该词汇仍有不同之处。

确实，就历史使用频率来说，“构造函数” 使用的更多

> 关于其他几个词汇的翻译我基本赞同，只是大部分词汇的翻译大家应该都可以达成共识，我们也许暂时不会考虑将其中的一部分收纳入词汇表中（如“value”、“return value”等）。

一些基本上不会出现争议的词汇确实不需要收入到词汇表中

**Comment by awxiaoxian2020** [comment]
关于 constructor 一词的翻译，基于历史原因，我赞同使用“构造函数”这一说法。

但是就个人意见而言，英文原文并没有出现 function 或者是 method——而仅仅是一个单词 constructor，所以个人更喜欢“构造器”这一译法，毕竟 constructor 有一些函数或者方法没有的行为。

但是鉴于 web 社区使用已久的译法，这一意见可能并不合适。只作为一项记录放在这里。

**Comment by yin1999** [comment]
根据过去的内容变更审查情况，我提议可以增加“constructor”以及“handler”的翻译。前者来源于不同的社区对其翻译的不一致，我倾向于保留我们过去主要采用的翻译“构造函数”。后者来源于我们对 `.then(() => { /*...*/ })` 以及 `.addEventListener((evt) => { 
/*...*/ })` 中的函数/方法的翻译的不一致（我们在过去的审查中，一般将其统一为“处理器”）。
