### ISSUE TITLE
Error en la cantidad de propiedades de "Shape.call(this, x, y, 20, 20, exists);"

### ISSUE THREAD

**Issue by Ignorancio** [mdn/translated-content#18274]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features

### ¿De qué sección específica o titular trata este problema?

Definiendo EvilCircle()

### ¿Qué información es incorrecta, inútil o incompleta?

Shape.call(this, x, y, 20, 20, exists);

### ¿Qué esperaba ver?

Esperaba ver "super(x, y, 20, 20);"
la informacion que presente en "informacion incorrecta" me parece como tal ya que la propiedad exists es un propiedad de la clase ball y no una propiedad de la clase shape.
como se menciona en el articulo en ingles, shape solo define las propiedades x, y, velX, velY. MAS NO LA PROPIEDAD EXISTS. COMO LO HACE EL ARTICULO EN ESPAÑOL, EL ARTICULO EN INGLES MENCIONA QUE EXISTS EN UNA NUEVO PROPIEDAD DE Ball.

### ¿Tiene algún enlace de apoyo, referencias o citas?

![image](https://github.com/mdn/translated-content/assets/58248360/9e19ba03-5c10-4066-8d7d-0cd228f8ff22)
![image](https://github.com/mdn/translated-content/assets/58248360/5973ebe7-d774-4782-92a6-4148b87bb007)
![image](https://github.com/mdn/translated-content/assets/58248360/86a7c493-99e4-4c5e-abab-2736a1ddad1f)

### ¿Tiene algo más que quiera compartir?

Me parece un curso excelente

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/learn/javascript/objects/adding_bouncing_balls_features`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/JavaScript/Objects/Adding_bouncing_balls_features
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/javascript/objects/adding_bouncing_balls_features/index.md
* Last commit: https://github.com/mdn/translated-content/commit/8a305c82f9ac565ae71947179844e082474c1b63
* Document last modified: 2023-07-22T04:06:46.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! muchas gracias por reportar el error, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en "View this page on GitHub", te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://github.com/mdn/translated-content/assets/13079269/998bb38b-a884-41e2-8839-77af4366bc4b)
