### ISSUE TITLE
Need more translation in page Private_properties 

### ISSUE THREAD

**Issue by illusory-dream** [mdn/translated-content#18280]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties

### 与此议题相关的小节或标题？

Syntax / Examples / Description

### 哪些信息是错误、无用或不完善的？

需要修改翻译（英文版已变更） - 主标题 `Private properties` 下的描述
需要修改翻译（英文版已变更） - 小节 [Syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties#syntax)
需要修改翻译（英文版已变更） - 小节 [Examples](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties#examples)
内容缺失（英文版存在，中文版没有） - 小节 [Description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties#description)

### 你期望看到什么？

同步英文版中已修改的部分
增加缺失的内容

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/classes/private_properties`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Classes/Private_properties
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/classes/private_properties/index.md
* Last commit: https://github.com/mdn/translated-content/commit/38a2d4036475e1b3c63e1b58d9056a9b47c3b358
* Document last modified: 2023-11-09T10:36:31.000Z

</details>

**Comment by JasonLamv-t** [comment]
I will update the reference of the class section in JavaScript
