### ISSUE TITLE
[zh-cn]:live example crashed

### ISSUE THREAD

**Issue by yoophoon** [mdn/translated-content#18417]
https://github.com/mdn/translated-content/blob/5006bccbbd62344c06ca16b85ca8f3adbcccc665/files/zh-cn/web/css/font/index.md?plain=1#L439C1-L442C2 (doc: https://developer.mozilla.org/zh-CN/docs/Web/CSS/font)
a live example in this page is crashed when presented in zh-cn but normal when presented in English(US)
```javascript
function setCss() {
  getProperties();
  injectCss(shortText);      //message fron console :ReferenceError: shortText is not defined
}
```
i've changed the code above like bellow and tha live example works correctly
```javascript
function setCss() {
  let shortText=getProperties();
  injectCss(shortText);    //injectCss(getProperties()) is the source code form the page presented in English(US) and without the line above
}
```

**Comment by jasonren0403** [comment]
The document should be synced, it's probably outdated.

**Comment by yoophoon** [comment]
thanks for providing such perfect resources for beginners
