### ISSUE TITLE
Use inclusive language in french translation

### ISSUE THREAD

**Issue by touti** [mdn/translated-content#18473]
## What is the new suggestion?

Please use inclusive language in french translation for the Mozilla documentation website. 

## Why is it important or useful?

In all french pages translated, you write 'auteur' everywhere for 'author', that's a bad idea if you wish to have more women or people not identify to men in WWW to develop greats ideas and codes. Not only for women day (today we're the 8 of march) but for everyday, we need and try to keep women in informatic !
You should use instead "l'auteur" an epicene language like "la personne".

All pages are likely to be needed
How much time do you think this work should take? All your life, every second
Will the work enable learners or professionals to achieve their goals better? Yes of course, open the door, just a littlen and try to accept women …
Does it address critical needs in the web industry? Absolutely, we need more representative construction of the world
Is the work an operational necessity, i.e. is not having it a security risk? Perhaps, some men will say NOOOOOO
Does the content help make the web more ethical? YES Absolutely

## Other supporting information

Example of auteur partout justice nulle part
https://developer.mozilla.org/fr/docs/Web/HTML/Element/meta

Écriture inclusive : question de genre, et de valeurs!
https://www.ecrirepourleweb.com/ecriture-inclusive-langage-non-sexiste

**Comment by touti** [comment]
> Plus simplement on pourrait utiliser auteur(e)

Concernant le langage inclusif, ce n'est pas si simple et la formulation `(e) ` reste problématique (cela équivaut à mettre les femmes entre parenthèses) et si besoin, le terme exact qui préexistait avant sa disparition est _autrice_ Cf Eliane Viennot, historienne dans "Non le masculin ne l'emporte pas sur le féminin" http://www.elianeviennot.fr/Livres/Langue-2014.html

Voici un texte récent du CNRS qui explique assez bien les tenants et aboutissants du langage inclusif dont voici un extrait.
https://lejournal.cnrs.fr/articles/lecriture-inclusive-par-dela-le-point-median

>  Le langage inclusif en pratique
> 
> De fait, le français met à notre disposition différentes stratégies permettant une meilleure représentation des femmes et des minorités de genre dans ses usages. Il est possible de distinguer deux types de stratégies.
> 
> D’une part, les stratégies dites « neutralisantes ». « Il s’agit, non pas d’utiliser du neutre tel qu’il est présent dans la langue aujourd’hui – puisque ce neutre est pensé comme masculin, mais de retrouver du neutre, de retrouver du commun », expose Eliane Viennot. Cela passe notamment par le recours à des termes épicènes, c’est-à-dire des termes qui ne varient pas en fonction du genre comme « scientifique », « architecte », « artiste »… ou encore le pronom « iel » qui est employé pour définir une personne quel que soit son genre (« les architectes ont reçu des appels à projet auxquels iels peuvent répondre »).
> (…)
> Cela passe aussi par l’usage de mots génériques tels que « personnes » ou « individus ». Également par des formules englobantes avec des singuliers collectifs : « l’équipe » (plutôt que « les salariés »), « l’orchestre » (plutôt que « les musiciens »), « la population étudiante » (plutôt que « les étudiants »), « bonjour tout le monde » (plutôt que « bonjour à tous »). Ou encore par des tournures en apostrophe (« Vous qui lisez cet article » au lieu de « Chers lecteurs ») et autres reformulations, avec, par exemple, le recours à des formulations passives : « L’accès à la bibliothèque est libre » plutôt que « Les utilisateurs ont librement accès à la bibliothèque »).

Ou encore

https://www.haut-conseil-egalite.gouv.fr/IMG/pdf/guide_egacom_sans_stereotypes-2022-versionpublique-min-2.pdf

> « Pour une communication publique sans stéréotype de sexe », publié en 2022, le Haut conseil à l’égalité entre les femmes et les hommes (HCE) définit ainsi le langage_égalitaire (ou non sexiste, ou inclusif) comme « l’ensemble des attentions discursives, c’est-à-dire lexicales, syntaxiques et graphiques qui permettent d’assurer une égalité de représentation des individus ».

**Sources concernant le web et l'accessibilité du langage inclusif**

- Écriture inclusive et accessibilité font-elles bon ménage ? par Sylvie Duchateau
https://access42.net/langage-non-genre-accessibilite/
- Abréviations inclusives : oui, mais comment ?
https://vincent-valentin.name/articles/abreviations-inclusives-oui-mais-comment
- Point médian final : point d’hyphénation ‧
https://matti-sg-fr.medium.com/point-m%C3%A9dian-final-point-dhyph%C3%A9nation-3f749c32b659

**Comment by SphinxKnight** [comment]
Bonjour @touti, merci d'avoir renseigné cette <i lang="en">issue</i> et d'avoir fourni les ressources associées. Nous visons à utiliser un langage le plus inclusif qui soit, en privilégiant des tournures épicènes (voir https://github.com/mozfr/besogne/wiki/Guide-stylistique-pour-la-traduction#sadresser-%C3%A0-lutilisateur-ou-lutilisatrice et certaines des PR depuis plusieurs mois).

Bien entendu, certaines pages ne sont pas encore alignées avec ces tournures et il convient de les corriger.

Je note que https://developer.mozilla.org/fr/docs/Web/HTML/Element/meta en fait partie et vais proposer une PR de mise à jour / correction à cet égard. N'hésitez pas, si vous avez le temps et la motivation, à proposer directement des PR pour corriger les autres occurrences que vous rencontriez.
