### ISSUE TITLE
Content bug: Missing  "#promoting-an-inactive-locale-to-tier-1"

### ISSUE THREAD

**Issue by JuanGaray93** [mdn/translated-content#1853]
## What page(s) did you find the problem on?

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Promise
https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1

## Specific page section or heading?

The yellow warn in the MDN site + the README in this repo

## What is the problem?

There is no element that the URL hash leads to. I can't find a way to contribute to the Spanish translation.

## What did you expect to see?

A text describing how the community can contribute to translating inactive locales.

## Did you test this? If so, how?

I entered the MDN site and clicked on the link.

**Comment by peterbe** [comment]
@Rumyra We need to change the link to some anchor in https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md
Should it be to https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#activating-a-locale ??

**Comment by Rumyra** [comment]
Absolutely @peterbe and apologies I was wondering what those changes would highlight.

@JuanGaray93 Spanish is currently not one of our active locales, however I have been approached by someone else who would like to work on it. Would you be willing for me to put you in touch? Locales require multiple participants https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#activating-a-locale

I'd be happy to intro if you'd like ☺️

**Comment by JuanVqz** [comment]
@Rumyra Hi! I'd like to be part of the Spanish community, would you put me in touch with those you know, please?

**Comment by Rumyra** [comment]
Hi all - unfortunately I haven't had a response from the other interested parties. There are three of you in this thread, so I'm open to discussing the unfreezing of the spanish locale if you are all still interested. Let me know - thank you!

**Comment by JuanVqz** [comment]
:hand:

**Comment by Rumyra** [comment]
Thanks both! I'm actually off for a week now, but I'm going to check this first thing when I get back and probably move it into a discussion so we can talk further 👍

**Comment by sergiogval** [comment]
Hi, everybody.

I would love to participate in this as well. I'm not sure how the workflow
is. Can any of you give me a clue?

Regards.
*Sergio G. Valadez Rivera*

**Comment by Rumyra** [comment]
Discussion for unfreezing Spanish locale https://github.com/mdn/translated-content/discussions/3370

**Comment by Graywolf9** [comment]
Hi! I think this issue could be already closed

There is how to activate a innactive locale: https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#activating-a-locale

es locale has already unfreezed, we are in:
https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org
https://t.me/+Dr6qKQCAepw4MjFj

**Comment by Graywolf9** [comment]
Hi! I think this issue could be already closed

There is how to activate an innactive locale: https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#activating-a-locale

es locale has already unfreezed, we are in:
https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org
https://t.me/+Dr6qKQCAepw4MjFj
