### ISSUE TITLE
第二个按钮展示结果有误

### ISSUE THREAD

**Issue by cy01** [mdn/translated-content#18641]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/:not

### 哪些信息是错误、无用或不完善的？

div:not(:is(.foo, .bar)) {
  border-bottom: dotted thin currentcolor;
}
这块的去点击 play 展示了两行 dot, 和 预期结果不同， 查结果，是页面同一html 里面 body外面有一个div

### 你期望看到什么？

这块的去点击 play 展示了一行 dot

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/_colon_not`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/:not
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/_colon_not/index.md
* Last commit: https://github.com/mdn/translated-content/commit/e0888e7b1423e205122612cb37ca13b4e22ef91c
* Document last modified: 2023-07-28T00:50:34.000Z

</details>

**Comment by yin1999** [comment]
有两行点线的原因是：第二个 `div` 会匹配 `p:not(:is(.foo, :invalid-pseudo-class))` 选择器，因此在该 `div` 的*上方*会有点线；第三个 `div` 会匹配 `div:not(:is(.foo, .bar))` 选择器，因此在该 `div` 的*下方*会有点线。请查看浏览器的开发者工具，确定实际引用的 CSS 样式。

由于示例内容正确，我将关闭该议题。

**Comment by cy01** [comment]
今天刚查看邮箱。当时提出这个问题是，div:not(:is(.foo, .bar)) 匹配了第三个和最后一个 div,  在 :not 页面展示和 play 里面都有，并且在 chrome 和 edge 不同的浏览器都有， 查看实际的样式， 发现是 body 外面有一个 div 影响的。我现在是换了一个电脑，是没有了错误的样式，也许那个电脑有点问题？我也不确定，晚上回去查看一下旧电脑。
![微信图片_20240401094019](https://github.com/mdn/translated-content/assets/5217788/78612451-fd3c-45fd-9fef-b034f4e07707)

**Comment by yin1999** [comment]
> 今天刚查看邮箱。当时提出这个问题是，div:not(:is(.foo, .bar)) 匹配了第三个和最后一个 div, 在 :not 页面展示和 play 里面都有，并且在 chrome 和 edge 不同的浏览器都有， 查看实际的样式， 发现是 body 外面有一个 div 影响的。我现在是换了一个电脑，是没有了错误的样式，也许那个电脑有点问题？我也不确定，晚上回去查看一下旧电脑。 ![微信图片_20240401094019](https://private-user-images.githubusercontent.com/5217788/318317267-78612451-fd3c-45fd-9fef-b034f4e07707.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5MzcwMzYsIm5iZiI6MTcxMTkzNjczNiwicGF0aCI6Ii81MjE3Nzg4LzMxODMxNzI2Ny03ODYxMjQ1MS1mZDNjLTQ1ZmQtOWZlZi1iMDM0ZjRlMDc3MDcuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDFUMDE1ODU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ0ZTQ3ZjhmMDQ3ZTk1OTkwOWJkOTYxYzQ2NDc3NDY3ODkyYThjODYyNWI2NmM4ODI1NGZmNjlkNjE1ODNiNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fD17bjkox6ERhEiTH19N1D7Lk-8zcRbSXU4MpwDslCg)

请确认浏览器版本（是否兼容示例中使用到的所有 CSS 语法）。
