### ISSUE TITLE
示例代码因缺少 `return` 语句而难以区分前后示例的差异

### ISSUE THREAD

**Issue by lmy668** [mdn/translated-content#18745]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Using_promises

### 哪些信息是错误、无用或不完善的？

文章讲到每个promise都要有对应的返回，但是实例这段代码，也没有返回
`
const listOfIngredients = [];

doSomething()
  .then((url) =>
    fetch(url)
      .then((res) => res.json())
      .then((data) => {
        listOfIngredients.push(data);
      }),
  )
  .then(() => {
    console.log(listOfIngredients);
  });

// 或

doSomething()
  .then((url) => fetch(url))
  .then((res) => res.json())
  .then((data) => {
    listOfIngredients.push(data);
  })
  .then(() => {
    console.log(listOfIngredients);
  });

`
上面一段是嵌套调用，有一个返回，但是下面是扁平化调用，这段`.then((data) => {
    listOfIngredients.push(data);
  })`貌似就没有返回

### 你期望看到什么？

修改为
`.then((data) => 
    listOfIngredients.push(data);
  )`

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/guide/using_promises/index.md
* Last commit: https://github.com/mdn/translated-content/commit/02d2069a2f8b185c4ac42f33707eba49d0c0c307
* Document last modified: 2023-10-21T02:15:48.000Z

</details>

**Comment by yin1999** [comment]
这一段代码可能并不是非常容易理解（应该是以前使用 prettier 格式化后出现的问题），问题并不出现在你说的地方。因为这些“同步调用”默认会返回 `undefined`，这是没有问题的。因为同步调用并不需要让 promise 链继续等待任何其他调用的完成（其本身已经完成了调用，并返回一个 `undefined`。

问题在于，上方的 `fetch` 调用，它是一个异步函数而调用 `fetch` 的部分在错误示例中并未返回 `fetch` 最后返回的 Promise，这会造成外层的 Promise 在不等待 `fetch` 最终兑现的情况下直接调用下一个 `then()` 传入的箭头函数，从而造成结果为空。

---

## 错误示例

```js
const listOfIngredients = [];

doSomething()
  .then((url) => {
    // 缺少 `return fetch` 这一表达式，使得外层的 promis 链并不会等待内层 fetch 调用的返回的 promise 的最终兑现
    // 从而造成外层的 promise 会直接去执行下一个 `then` 语句，而此时内层的 fetch 调用并未最终完成。
    fetch(url)
      .then((res) => res.json())
      .then((data) => {
        listOfIngredients.push(data); // 该箭头函数本身是同步调用，可保证其完成调用后，由 fetch 组成的 promise 链才最终兑现
      });
    // 这里隐式地返回了 `undefined` 从而使得下一个 then 调用并不会等待 `fetch` Promise 链的兑现。
  })
  .then(() => {
    console.log(listOfIngredients);
    // listOfIngredients will always be [], because the fetch request hasn't completed yet.
  });
```

## 正确示例

```js
const listOfIngredients = [];

doSomething()
  // 下面的 箭头函数直接返回了 fetch 的返回值，使得下一个 then 调用会等待 fetch 的兑现，所以正确
  // 但因为之前代码格式化的原因，`return` 语句被简化了，不好和前者对比
  .then((url) =>
    fetch(url)
      .then((res) => res.json())
      .then((data) => {
        listOfIngredients.push(data);
      }),
  )
  .then(() => {
    console.log(listOfIngredients);
  });

// 或

doSomething()
  .then((url) => fetch(url))
  .then((res) => res.json())
  .then((data) => {
    listOfIngredients.push(data);
  })
  .then(() => {
    console.log(listOfIngredients);
  });
```

---

英文文档已对该处进行更新，以帮助读者正确理解该处的示例。中文文档作同步更新即可。

**Comment by lmy668** [comment]
谢谢作者的解答,。
“同步调用”默认会返回 `undefined`，`.then(() => {
    console.log(listOfIngredients);
  });`这句确实也不依靠上个promise的返回结果。
根据箭头函数的语法，单句可以省略`return`，这么看中文文档没有问题，仅仅只是不好与前者对比。

**Comment by JasonLamv-t** [comment]
I am going to fix this.
