### ISSUE TITLE
:scope 中文简体页面出现 Error: could not find syntax for this item

### ISSUE THREAD

**Issue by T34-active** [mdn/translated-content#18760]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/:scope

### 哪些信息是错误、无用或不完善的？

在页面中的 [用法](https://developer.mozilla.org/zh-CN/docs/Web/CSS/:scope#%E7%94%A8%E6%B3%95) 报了一个错误 Error: could not find syntax for this item

### 你期望看到什么？

希望与en-US [Syntax](https://developer.mozilla.org/en-US/docs/Web/CSS/:scope#syntax) 页面进行同步

### MDN metadata

1. Folder: zh-CN/docs/Web/CSS/:scope
2. MDN URL: [https://developer.mozilla.org/zh-CN/docs/Web/CSS/:scope](https://developer.mozilla.org/zh-CN/docs/Web/CSS/:scope)
3. GitHub URL: [https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/_colon_scope/index.md](https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/_colon_scope/index.md)
4. Last commit: [eff0b9a](https://github.com/mdn/translated-content/pull/18367/commits/eff0b9aecfeed2720d7681eab0662853e9302ed3)

**Comment by yin1999** [comment]
Good catch. I've created #18772 to fix it.
