### ISSUE TITLE
firefox agent error

### ISSUE THREAD

**Issue by luxiaoxia722** [mdn/translated-content#18790]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/User-Agent/Firefox

### 与此议题相关的小节或标题？

#Windows

### 哪些信息是错误、无用或不完善的？

Windows NT, WOW64   Mozilla/5.0 (Windows NT x.y; WOW64; rv:10.0) Gecko/20100101 Firefox/10.0

### 你期望看到什么？

Firefox 69版本已经不使用WOW64

### 你有什么支持的链接、参考或引用？

https://www.ghacks.net/2019/06/22/mozilla-omits-cpu-architecture-information-from-firefoxs-user-agent/

### 你还想补充什么内容？

编辑useragent 的不同阶段变化

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/http/headers/user-agent/firefox`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/User-Agent/Firefox
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/http/headers/user-agent/firefox/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f873c44624a9ca26f187f0f44e504f5386d55ca3
* Document last modified: 2023-08-31T02:11:59.000Z

</details>

**Comment by jasonren0403** [comment]
内容过期，简体中文文档需要作同步
