### ISSUE TITLE
[FR] fit-content() - mélimélo

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#18932]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/CSS/fit-content

### Quelle information était incorrecte, inutile ou incomplète ?

Bonjour,

Quand je suis sur cette page fr de fit-content() le lien est le suivant [pas de () dans le lien]:
"https://developer.mozilla.org/fr/docs/Web/CSS/fit-content"

Si je choisis de visualiser la page en-us correspondante j'arrive sur cette page:
"https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content"
qui ne correspond pas à fit-content() en-us mais à fit-content.

Depuis cette page si je veux visualiser la page fr équivalente j'aboutis à la page:
"https://developer.mozilla.org/fr/docs/Web/CSS/fit-content"
qui correspond bien à fit-content() fr.

Quand je visualise la page en-us de fit-content() je suis sur la page:
"https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content_function"
Si je veux visualiser la page fr de fit-content() depuis cette page la page fr n'existe pas.

Cordialement

### Que vous attendiez-vous à voir ?

Une clarification des liens

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/fit-content`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/fit-content
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/fit-content/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by quentin-rey** [comment]
Bonjour,
En effet, il y a un mélimélo !

Je n'ai pas encore connaissance de tous les fonctionnements, mais j'aurais tendance à dire qu'il faut mettre à jour :
`slug: Web/CSS/fit-content`
par
`slug: Web/CSS/fit-content_function`
pour corriger ce problème. Si quelqu'un peut me confirmer.

Il restera également la traduction de la page [fit-content](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content) en-us, qui elle n'existe pas.

**Comment by quentin-rey** [comment]
To-Do:

- [ ] `fit-content()`
  - [ ] Rename folder name from `fit-content` to `fit-content_function`
  - [ ] Change slug from `Web/CSS/fit-content` to `Web/CSS/fit-content_function`
- [ ] `fit-content`
  - [ ] Add the french translation
