### ISSUE TITLE
Description 能否添加到术语添加表里面

### ISSUE THREAD

**Issue by T34-active** [mdn/translated-content#18946]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/block#%E6%8F%8F%E8%BF%B0

### 哪些信息是错误、无用或不完善的？

希望完善简体中文 web 术语翻译对照表

### 你期望看到什么？

我希望在[简体中文 web 术语翻译对照表](https://github.com/mdn/translated-content/blob/main/docs/zh-cn/glossary.md)中加入这一个 Description 单词 在英文文档中这个单词频繁出现 我希望翻译为描述

### 你有什么支持的链接、参考或引用？

[zh-CN](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/block#%E6%8F%8F%E8%BF%B0)
[en-US](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/block#description)

**Comment by yin1999** [comment]
已在 #18211 中讨论，考虑到我们对该标题的关键词没有异议（且我们通常都将其翻译为“描述”），我们暂时不会将其添加到术语表中。

**Comment by yin1999** [comment]
暂不考虑添加，其实我们还有一些标题常用的术语没有添加到表格中。但我们希望让这个表格能够相对精简，在遇到有些模糊不定且在英文文档中出现的次数较多的词语时，贡献者可以快速地从表格中查询到相关的词汇。
