### ISSUE TITLE
chore: remove the `{{DOMAttributeMethods}}` macro from translated-content

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#19009]
The [`{{DOMAttributeMethods}}` macro has been deprecated](https://github.com/mdn/yari/blob/a21d7024f3e28922a43336af52bd289903c7a6d6/kumascript/macros/DOMAttributeMethods.ejs#L3) and should be removed from this repo:

```[tasklist]
### Macro removal
- [ ] #22056
- [ ] #19044
- [x] ja #23462
- [x] ko #23462
- [ ] https://github.com/mdn/translated-content/pull/19621
- [ ] https://github.com/mdn/translated-content/issues/19231
- [ ] https://github.com/mdn/translated-content/issues/19010
```

**Comment by leon-win** [comment]
Done for `ru` :ok_hand:

**Comment by leon-win** [comment]
Before this there was a false start, but now it’s definitely ready for `ru` =))
