### ISSUE TITLE
Error 404 en links de la página.

### ISSUE THREAD

**Issue by DG9022** [mdn/translated-content#19014]
### MDN URL

https://developer.mozilla.org/es/docs/Web/API/Web_Storage_API

### ¿De qué sección específica o titular trata este problema?

Falla en los links de ejemplos (x3)

### ¿Qué información es incorrecta, inútil o incompleta?

Error **404** en 3 links.

Link 1: https://github.com/mdn/web-storage-demo
Link 2: https://mdn.github.io/web-storage-demo/
Link 3: https://mdn.github.io/web-storage-demo/event.html

### ¿Qué esperaba ver?

Simplemente el contenido de los links, pero desconozco cual es.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/api/web_storage_api`
* MDN URL: https://developer.mozilla.org/es/docs/Web/API/Web_Storage_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/api/web_storage_api/index.md
* Last commit: https://github.com/mdn/translated-content/commit/53a7cce2ebf946219ec448239ea90022eec477d7
* Document last modified: 2023-08-02T21:43:50.000Z

</details>

**Comment by Graywolf9** [comment]
Muchas gracias por reportar el error, este debería quedar resuelto en el PR #22021

Siententé libre de seguir colaborando y

Bienvenido a MDN!
