### ISSUE TITLE
Issue with "Array": (short summary here please)

### ISSUE THREAD

**Issue by Luxcium** [mdn/translated-content#1905]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array

#### What information was incorrect, unhelpful, or incomplete?
![Screenshot_20210804_214929](https://user-images.githubusercontent.com/42672814/128278331-db7e18ed-e65a-4b37-84d6-b75066b4683a.png)

#### Specific section or headline?
[Array#instances_darray](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array#instances_darray)

#### What did you expect to see?
the actual content in french 

#### Did you test this? If so, how?
 - Firefox 90.0.2 (64 bits)
 - Google Chrome
    Version 92.0.4515.131 (Build officiel) (64 bits)

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/array`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/array/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d4b97cd8ba7c9b71d5e3ccb119103047da3b44a8
* Document last modified: 2021-08-03T17:30:29.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour ce rapport @Luxcium, une migration du contenu JavaScript est prévue prochainement (cf. https://github.com/mdn/translated-content/pull/1835 ) mais nous traiterons ce point dès que possible.
