### ISSUE TITLE
CSS not attached on playground

### ISSUE THREAD

**Issue by StephaneVa** [mdn/translated-content#19079]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/CSS/column-gap

### Sur quelle section/titre porte ce problème ?

https://developer.mozilla.org/fr/docs/Web/CSS/gap#exemples

### Quelle information était incorrecte, inutile ou incomplète ?

On FR page, playground result looks blank
![image](https://github.com/mdn/translated-content/assets/38727471/52d749da-3e49-4670-b6d3-3d2e81dadecd)

When opening button "Play", we can see that CSS part is missing

### Que vous attendiez-vous à voir ?

result with CSS applied, like https://developer.mozilla.org/en-US/docs/Web/CSS/column-gap#examples

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/column-gap`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/column-gap
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/column-gap/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by quentin-rey** [comment]
**Fix:**
Add section ids as parameters

**Example:**
`{{EmbedLiveSample("","auto","130px")}}`
to
`{{EmbedLiveSample("disposition_flexible","auto","130px")}}`

**Comment by tristantheb** [comment]
Bonsoir,

La correction à ce problème est poussée pour la prochaine mise à jour de la documentation ! Les exemples seront de nouveau triés grâce à leur titre et ne se marcherons plus sur les pieds !

Merci pour ce signalement, et merci à @quentin-rey pour la correction :)
