### ISSUE TITLE
Issue with "Date.prototype.toLocaleTimeString()": incorrect reference to nested doc (french page)

### ISSUE THREAD

**Issue by Fred-MabS** [mdn/translated-content#1919]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString

#### What information was incorrect, unhelpful, or incomplete?

` {{page('fr/docs/Web/JavaScript/Reference/Objets_globaux/DateTimeFormat','Param.C3.A8tres')}} `

#### Specific section or headline?

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString#:~:text=toLocaleTimeString(%5Blocales%20%5B%2C%20options%5D%5D)-,Param%C3%A8tres,-Voir%20le%20tableau

#### What did you expect to see?

Content of the specified doc instead of its reference.
Maybe the code should be:
` {{page('fr/docs/Web/JavaScript/Reference/Objets_globaux/DateTimeFormat','Paramètres')}} `
(as it is in https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/date/tolocaledatestring/index.html)

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/date/tolocaletimestring`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleTimeString
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/date/tolocaletimestring/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d899a920d4b27f75c572c031434baa5fdf82124c
* Document last modified: 2021-08-04T20:22:33.000Z

</details>

**Comment by SphinxKnight** [comment]
Thanks for the report @Fred-MabS! 
A quick note: we'll be waiting for https://github.com/mdn/translated-content/pull/1835 to be merged before tackling this one.
