### ISSUE TITLE
[ru] remove the `{{DOMAttributeMethods}}` macros

### ISSUE THREAD

**Issue by leon-win** [mdn/translated-content#19231]
```[tasklist]
### Tasks
- [ ] #19232
- [ ] https://github.com/mdn/translated-content/pull/19555
- [ ] #19254
- [ ] https://github.com/mdn/translated-content/pull/19553
```

**Comment by leon-win** [comment]
Done :heavy_check_mark:

**Comment by yin1999** [comment]
Hey @leon-win. Looks like there are two missed:

- `files/ru/web/api/element/getattribute/index.md`
- `files/ru/web/api/element/removeattribute/index.md`

**Comment by leon-win** [comment]
> Hey @leon-win. Looks like there are two missed:
> 
>     * `files/ru/web/api/element/getattribute/index.md`
> 
>     * `files/ru/web/api/element/removeattribute/index.md`

My mistake!
I didn't find it because I was looking for `{{DOMAttributeMethods}}` =(((
Thank you, @yin1999! I will do it :ok_hand:

**Comment by leon-win** [comment]
Now it's definitely ready :ok_hand:)))
