### ISSUE TITLE
Why aren't 'object-fit' and 'object-position' in the same subdirectory

### ISSUE THREAD

**Issue by strawberryforme** [mdn/translated-content#19296]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/object-fit

### 哪些信息是错误、无用或不完善的？

无

### 你期望看到什么？

'object-fit' 和   'object-position' 都在object侧边栏下面

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/object-fit`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/object-fit
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/object-fit/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f873c44624a9ca26f187f0f44e504f5386d55ca3
* Document last modified: 2023-08-31T02:11:59.000Z

</details>

**Comment by yin1999** [comment]
见 https://github.com/mdn/yari/blob/ee7f9d50914124d7563c6c61bcee9f1b22928616/kumascript/macros/CSSRef.ejs#L1085-L1092

当一个组别中的项目数量小于3时，其中的项目会直接列出，而不会被分组到单独的组别中。

**Comment by yin1999** [comment]
我将关闭该议题。若有任何疑问或建议，欢迎继续补充内容，或创建新的议题/讨论。
