### ISSUE TITLE
关于 requestAnimationFrame 文档说明的问题

### ISSUE THREAD

**Issue by kiner-tang** [mdn/translated-content#19408]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/window/requestAnimationFrame

### 哪些信息是错误、无用或不完善的？

![image](https://github.com/mdn/translated-content/assets/10286961/4ef7b412-1787-41c7-9c5a-e7bdc3c93766)
在 js 当中，并没有 “长整型” 这个概念，并且在 `typescript` 当中， `requestAnimationFrame` 返回类型是 `number`的，
<img width="860" alt="image" src="https://github.com/mdn/translated-content/assets/10286961/3e702d7b-6202-4259-be3e-4a4653c55595">
是否应该调整一下呢？

### 你期望看到什么？

改成 “整型” 即可

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/window/requestanimationframe`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/window/requestAnimationFrame
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/window/requestanimationframe/index.md
* Last commit: https://github.com/mdn/translated-content/commit/a4cb89c4c8c7c7b6ad239ea261eb0aa83138d501
* Document last modified: 2023-04-10T14:26:47.000Z

</details>

**Comment by skyclouds2001** [comment]
补充，英文文档原文如下： 

![image](https://github.com/mdn/translated-content/assets/95597335/fb6c53a1-24a9-4c2e-8b85-ac268929ca2b)

**Comment by yin1999** [comment]
关于用“整型”还是“整数”，我们没有明确的规范。是的，JavaScript 类型系统中并没有其他的整数类型，与数值相关的只有 `number` 和 `BigInt`。原文想要描述的应该是 JavaScript 引擎最终返回的数值类型，参见 [WebKit WebIDL](https://github.com/WebKit/WebKit/blob/2dc674ade9a440ea454fd5e535aa8b63cdc3b64c/Source/WebCore/Modules/webxr/WebXRSession.idl#L45)。

**Comment by kiner-tang** [comment]
> 关于用“整型”还是“整数”，我们没有明确的规范。是的，JavaScript 类型系统中并没有其他的整数类型，与数值相关的只有 `number` 和 `BigInt`。原文想要描述的应该是 JavaScript 引擎最终返回的数值类型，参见 [WebKit WebIDL](https://github.com/WebKit/WebKit/blob/2dc674ade9a440ea454fd5e535aa8b63cdc3b64c/Source/WebCore/Modules/webxr/WebXRSession.idl#L45)。

就是在 js 这个知识领域来说，确实没有所谓的“长整型”概念，这个描述，可能对一些刚接触 js 的同学会有一些误导，看看要不要加一些描述或者是换一个说法会好一点呢？

**Comment by yin1999** [comment]
> > 关于用“整型”还是“整数”，我们没有明确的规范。是的，JavaScript 类型系统中并没有其他的整数类型，与数值相关的只有 `number` 和 `BigInt`。原文想要描述的应该是 JavaScript 引擎最终返回的数值类型，参见 [WebKit WebIDL](https://github.com/WebKit/WebKit/blob/2dc674ade9a440ea454fd5e535aa8b63cdc3b64c/Source/WebCore/Modules/webxr/WebXRSession.idl#L45)。
> 
> 就是在 js 这个知识领域来说，确实没有所谓的“长整型”概念，这个描述，可能对一些刚接触 js 的同学会有一些误导，看看要不要加一些描述或者是换一个说法会好一点呢？

我可能倾向于不修改这里的说法，正是因为 JavaScript 只有两种与数值有关的类型，而在通常使用的过程中用到的又是 `number` 类型，所以在对 JS 中的数值进行处理等操作时，我们就必须确保相关的操作不会影响[精度](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number#number_%E7%BC%96%E7%A0%81)。所以站在我的角度，保留有关实际类型的说明可能是有必要的。

补充一点：英文文档中记录了大量有关具体返回值类型的说明，用到了类似上面的这种格式。如果真要对格式说明进行修改，应该需要首先更新英文文档。

**Comment by kiner-tang** [comment]
> > > 关于用“整型”还是“整数”，我们没有明确的规范。是的，JavaScript 类型系统中并没有其他的整数类型，与数值相关的只有 `number` 和 `BigInt`。原文想要描述的应该是 JavaScript 引擎最终返回的数值类型，参见 [WebKit WebIDL](https://github.com/WebKit/WebKit/blob/2dc674ade9a440ea454fd5e535aa8b63cdc3b64c/Source/WebCore/Modules/webxr/WebXRSession.idl#L45)。
> > 
> > 
> > 就是在 js 这个知识领域来说，确实没有所谓的“长整型”概念，这个描述，可能对一些刚接触 js 的同学会有一些误导，看看要不要加一些描述或者是换一个说法会好一点呢？
> 
> 我可能倾向于不修改这里的说法，正是因为 JavaScript 只有两种与数值有关的类型，而在通常使用的过程中用到的又是 `number` 类型，所以在对 JS 中的数值进行处理等操作时，我们就必须确保相关的操作不会影响[精度](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Number#number_%E7%BC%96%E7%A0%81)。所以站在我的角度，保留有关实际类型的说明可能是有必要的。
> 
> 补充一点：英文文档中记录了大量有关具体返回值类型的说明，用到了类似上面的这种格式。如果真要对格式说明进行修改，应该需要首先更新英文文档。

好的，那这个问题就先关了吧
