### ISSUE TITLE
wrong parameter options.passive

### ISSUE THREAD

**Issue by ninjakuro** [mdn/translated-content#19427]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/API/EventTarget/removeEventListener

### О какой части статьи или абзаце идёт речь?

Синтаксис - Параметры

### Какая информация оказалась неверной, бесполезной или неполной?

у параметра options нет поля passive

### Как бы вы исправили?

нужно удалить упоминание passive в параметре options

### Есть ли у вас какие-либо подтверждающие ссылки?

например английская версия этой же страницы https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener

### Хотите добавить что-то ещё?

такая же ошибка не только в русской версии, но и во французкой.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/api/eventtarget/removeeventlistener`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/EventTarget/removeEventListener
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/eventtarget/removeeventlistener/index.md
* Last commit: https://github.com/mdn/translated-content/commit/ea84746aa880c3e7f5076dc4d7e4e94af171c348
* Document last modified: 2024-01-06T23:57:34.000Z

</details>

**Comment by leon-win** [comment]
Исправил также в 'fr`: 19620 :ok_hand:

**Comment by ninjakuro** [comment]
@leon-win в примерах всё ещё осталось упоминание passive у removeEventListener
![image](https://github.com/mdn/translated-content/assets/1157856/53d2bf40-e9db-4af9-8217-0746f84a0e49)

**Comment by leon-win** [comment]
> @leon-win в примерах всё ещё осталось упоминание passive у removeEventListener ![image](https://private-user-images.githubusercontent.com/1157856/328114502-53d2bf40-e9db-4af9-8217-0746f84a0e49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5ODQ3MTcsIm5iZiI6MTcxNDk4NDQxNywicGF0aCI6Ii8xMTU3ODU2LzMyODExNDUwMi01M2QyYmY0MC1lOWRiLTRhZjktODIxNy0wNzQ2Zjg0YTBlNDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDZUMDgzMzM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzVlZmY3MTg1OTFjMTM1M2Q0ODRhZTg3ZTk5Y2M5NDY2YWNkODUxYzE5ODJmZDI2MjU5ZGRlYWY3YTcyY2JmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UWAr_InJ8Q_RIDSjkpbksqIsrLy5cw2lTKX5ioULB3s)

В примерах да, пока осталось. Нужно внести изменения в английскую версию (https://github.com/mdn/content), переписать их.
Есть есть возможность это сделать, будет здорово :+1:
