### ISSUE TITLE
Issue with "Инициализация фреймворка": (short summary here please)

### ISSUE THREAD

**Issue by ghost** [mdn/translated-content#1946]
MDN URL: https://developer.mozilla.org/ru/docs/Games/Tutorials/2D_breakout_game_Phaser/Initialize_the_framework

#### What information was incorrect, unhelpful, or incomplete?

there is no image with example code at the very bottom of the page

#### Specific section or headline?

at the end of the article

#### What did you expect to see?

picture with code

#### Did you test this? If so, how?

opened in different browsers

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/games/tutorials/2d_breakout_game_phaser/initialize_the_framework`
* MDN URL: https://developer.mozilla.org/ru/docs/Games/Tutorials/2D_breakout_game_Phaser/Initialize_the_framework
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/games/tutorials/2d_breakout_game_phaser/initialize_the_framework/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d899a920d4b27f75c572c031434baa5fdf82124c
* Document last modified: 2021-08-04T20:22:33.000Z

</details>

**Comment by sashasushko** [comment]
Fixed
