### ISSUE TITLE
[zh-CN] Mainland's community has been disbanled.

### ISSUE THREAD

**Issue by fwqaaq** [mdn/translated-content#19534]
### MDN URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Contributing/Translated_content#chinese_zh-cn_zh-tw

### 哪些信息是错误、无用或不完善的？

@yin1999 群主被请🍵了

### 你期望看到什么？

我们是否需要一个新的（Telegram、discord 等更自由的平台），而不是使用 WeChat。

**Comment by yin1999** [comment]
We are discussing the solutions, please be patient.

**Comment by yin1999** [comment]
> We are discussing the solutions, please be patient.

Discussed with @jasonren0403, @JasonLamv-t, @irvin, and @fwqaaq. We finally considered creating localization channels (`zh-CN` and `zh-TW`) on the [MDN official discord server](https://developer.mozilla.org/discord).
