### ISSUE TITLE
It seems that the Chinese and English documents are not synchronized

### ISSUE THREAD

**Issue by kiner-tang** [mdn/translated-content#19548]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Values_and_units

### 哪些信息是错误、无用或不完善的？

It seems that the Chinese and English documents are not synchronized.
![image](https://github.com/mdn/translated-content/assets/10286961/da35b07b-4a6c-4435-8719-c7d5c40a1ef9)
The table about "Relative length units" is missing!
![image](https://github.com/mdn/translated-content/assets/10286961/c097328f-eb9a-481c-a507-2279f6e521a4)
****

### 你期望看到什么？

Just need to synchronize the English and Chinese documents

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/css/building_blocks/values_and_units`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Values_and_units
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/css/building_blocks/values_and_units/index.md
* Last commit: https://github.com/mdn/translated-content/commit/38c1ebed2e4862e414cae7d534506931fdea688d
* Document last modified: 2023-11-30T02:35:32.000Z

</details>

**Comment by kiner-tang** [comment]
@yin1999 我们这个需要怎么同步呢？是以英文文档作为基准还是以中文文档作为基准呢？这个没有同学处理的话，要不我来处理一下。

**Comment by yin1999** [comment]
> @yin1999 我们这个需要怎么同步呢？是以英文文档作为基准还是以中文文档作为基准呢？这个没有同学处理的话，要不我来处理一下。

以英文文档作为基准来同步。具体的翻译指南请参考：

- https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md
- https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN

有问题欢迎继续咨询[我们](https://developer.mozilla.org/discord)（discord `#zh-cn` 频道）。

**Comment by kiner-tang** [comment]
> > @yin1999 我们这个需要怎么同步呢？是以英文文档作为基准还是以中文文档作为基准呢？这个没有同学处理的话，要不我来处理一下。
> 
> 以英文文档作为基准来同步。具体的翻译指南请参考：
> 
> * https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md
> * https://developer.mozilla.org/zh-CN/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN
> 
> 有问题欢迎继续咨询[我们](https://developer.mozilla.org/discord)（discord `#zh-cn` 频道）。

好的
