### ISSUE TITLE
Issue with "Связь Grid позиционирования с другими методами поз…": (short summary here please)

### ISSUE THREAD

**Issue by studentJSreactVueHELP** [mdn/translated-content#1957]
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout

#### What information was incorrect, unhelpful, or incomplete?

Live sample failed!
An error occurred trying to render this live sample.
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find an HTML element with an "id" of "With_a_grid_area_as_the_parent" within /ru/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/css/css_grid_layout/relationship_of_grid_layout`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/css_grid_layout/relationship_of_grid_layout/index.html
* Last commit: https://github.com/mdn/translated-content/commit/64dc758c4deb7abc004ad2e4cdf4f1e8e2c00fc1
* Document last modified: 2021-08-06T23:03:42.000Z

</details>

**Comment by sashasushko** [comment]
Solution #1888
