### ISSUE TITLE
dir 属性の説明に古い情報が含まれます。

### ISSUE THREAD

**Issue by 8810hayate** [mdn/translated-content#19712]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/dir

### この問題に関する節や見出しはどこですか。

試してみましょう

### 不完全、不親切、不完全であった情報は何ですか。

ブラウザが提供する書字方向の変更方法に関する Note の情報が古くなっているようです。
en-US 版のページでは、「Edge」 ではなく、「Legacy Edge」 と区別されています。
https://developer.mozilla.org/en-US/docs/web/html/global_attributes/dir

### どう表示されるべきだと思いますか。

<p><strong>メモ:</strong> ブラウザーではユーザーが <a href="[/ja/docs/Web/HTML/Element/input](https://developer.mozilla.org/ja/docs/Web/HTML/Element/input)"><code>&lt;input&gt;</code></a> や <a href="[/ja/docs/Web/HTML/Element/textarea](https://developer.mozilla.org/ja/docs/Web/HTML/Element/textarea)"><code>&lt;textarea&gt;</code></a> の書字方向を変更することを許可して、コンテンツの執筆を支援していることがあります。 Chrome と Safari は入力フィールドのコンテキストメニューに書字方向のオプションを提供している一方、 Legacy Edge はキーバインド <kbd>Ctrl</kbd> + <kbd>Left Shift</kbd> および <kbd>Ctrl</kbd> + <kbd>Right Shift</kbd> を使用します。 Firefox は <kbd>Ctrl</kbd>/<kbd>Cmd</kbd> + <kbd>Shift</kbd> + <kbd>X</kbd> を使用しますが、 <strong><code>dir</code></strong> 属性の値は変更しません。</p>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/html/global_attributes/dir`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/HTML/Global_attributes/dir
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/html/global_attributes/dir/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f9f38005fed81ee8b8b9fa3bd09b135740028b46
* Document last modified: 2023-03-02T15:20:34.000Z

</details>

**Comment by mfuji09** [comment]
該当部分（Edgeへの言及）が英語版では既に削除されていますので、日本語訳でも削除しました。

**Comment by mfuji09** [comment]
修正完了しました。
