### ISSUE TITLE
[fr] Missing compatibility

### ISSUE THREAD

**Issue by fradureauisagri** [mdn/translated-content#19856]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/API/Notifications_API/Using_the_Notifications_API

### Sur quelle section/titre porte ce problème ?

compatibility

### Quelle information était incorrecte, inutile ou incomplète ?

Il manque la compatibilité avec les navugateurs

### Que vous attendiez-vous à voir ?

Il manque la compatibilité avec les navugateurs

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/notifications_api/using_the_notifications_api`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Notifications_API/Using_the_Notifications_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/notifications_api/using_the_notifications_api/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by quentin-rey** [comment]
La page anglaise semble ne pas afficher le tableau de compatibilité, celui-ci n'existe peut-être pas (plus).
A noter également l'absence de l'image utilisée en début d'article
`fr/docs/Web/API/Notifications_API/Using_the_Notifications_API/android-notification.png`

**Comment by SphinxKnight** [comment]
@fradureauisagri je seconde l'avis de @quentin-rey, les pages de "guide" n'ont généralement pas de tableaux de compatibilité. En revanche, pour les notifications, le tableau est bien présent sur https://developer.mozilla.org/fr/docs/Web/API/Notifications_API (y compris en anglais).

De façon générale, c'est la version anglaise qui sert de référence à la version française (ce qui ne signifie pas qu'elle est exempte de bug non plus, mais dans ce cas, ça permet de confirmer).

Bref, je suis d'avis de fermer cette <i lang="en">issue</i>, mais aussi d'en profiter pour mettre à jour ces deux pages en français (la page https://developer.mozilla.org/fr/docs/Web/API/Notifications_API et celle liée ici), ça ne fera pas de mal et permettra de corriger les autres problèmes (merci @quentin-rey d'avoir regardé :) )

**Comment by SphinxKnight** [comment]
Je proposerai une mise à jour des pages, mais https://developer.mozilla.org/fr/docs/Web/API/Notifications_API/Using_the_Notifications_API se basant sur son homologue anglaise qui n'a pas de tableau, nous n'allons a priori pas l'y ajouter.
