### ISSUE TITLE
transform 章节内存在错误的超链接

### ISSUE THREAD

**Issue by FI-GGG** [mdn/translated-content#19889]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/transform

### 哪些信息是错误、无用或不完善的？

[transform 章节 ](https://developer.mozilla.org/zh-CN/docs/Web/CSS/transform#%E7%A4%BA%E4%BE%8B)
"有关更多示例，请参阅使用 CSS 变换和<transform-function>。" 中的**CSS 变换**超链接实际上是[ css过渡](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_transitions)

### 你期望看到什么？

将链接改为[使用 CSS 变换]( https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_transforms/Using_CSS_transforms)

### 你还想补充什么内容？

![1](https://github.com/mdn/translated-content/assets/58102634/2399c731-9ef1-4619-b68e-9bfc1b77ee84)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/transform`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/transform
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/transform/index.md
* Last commit: https://github.com/mdn/translated-content/commit/881e54e12075b75078d992cae56efd1c83de0e75
* Document last modified: 2023-07-28T01:11:37.000Z

</details>

**Comment by PassionPenguin** [comment]
will take it:)

the content needs a sync
