### ISSUE TITLE
Ejemplos Visuales en Conceptos Básicos de Flexbox no pueden ser visualizados

### ISSUE THREAD

**Issue by Balbi01** [mdn/translated-content#20017]
### MDN URL

https://developer.mozilla.org/es/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox

### ¿De qué sección específica o titular trata este problema?

Conceptos Básicos de Flexbox

### ¿Qué información es incorrecta, inútil o incompleta?

![image](https://github.com/mdn/translated-content/assets/133147942/009c0f84-8b02-401a-aab8-6130730a8f70)

### ¿Qué esperaba ver?

Los ejemplos visuales que antes se encontraban en el uso de FLexbox

### ¿Tiene algún enlace de apoyo, referencias o citas?

https://developer.mozilla.org/es/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox

### ¿Tiene algo más que quiera compartir?

El error aparece inmediatamente al entrar a la página. Agradezco mucho su trabajo y creí que lo correcto era reportarlo.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/css/css_flexible_box_layout/basic_concepts_of_flexbox`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/css_flexible_box_layout/basic_concepts_of_flexbox/index.md
* Last commit: https://github.com/mdn/translated-content/commit/53a7cce2ebf946219ec448239ea90022eec477d7
* Document last modified: 2023-08-02T21:43:50.000Z

</details>

**Comment by Graywolf9** [comment]
Muchas gracias por reportar el error, este debería quedar resuelto en el PR #22019

Siententé libre de seguir colaborando y 

Bienvenido a MDN!
