### ISSUE TITLE
Issue with "Element: mouseenter event": incorrect usage of notions (mouseenter/mouseover)

### ISSUE THREAD

**Issue by 123enot** [mdn/translated-content#2009]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Element/mouseenter_event

It seems, that translation into russian is incorrect, since `mouseover`/`mouseenter` words were mistakenly replaced. In english variant we have such text: 
`With deep hierarchies, the number of mouseover events sent can be quite huge and cause significant performance problems. In such cases, it is better to listen for mouseenter events.
`
#### What information was incorrect, unhelpful, or incomplete?
"При наличии глубокой иерархии количество отправляемых событий **mouseenter** может быть довольно большим и вызывать значительные проблемы с производительностью. В таких случаях лучше обрабатывать события **mouseover**."

#### Specific section or headline?
https://developer.mozilla.org/ru/docs/Web/API/Element/mouseenter_event#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BF%D0%BE_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8E

#### What did you expect to see?
"При наличии глубокой иерархии количество отправляемых событий **mouseover** может быть довольно большим и вызывать значительные проблемы с производительностью. В таких случаях лучше обрабатывать события **mouseenter**."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/api/element/mouseenter_event`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Element/mouseenter_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/element/mouseenter_event/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d2e4c961e3fb6042656a62269374efc64144a709
* Document last modified: 2021-08-10T00:49:13.000Z

</details>

**Comment by sashasushko** [comment]
@123enot спасибо, закрыли
