### ISSUE TITLE
Spanish Description of every is kind of misleading

### ISSUE THREAD

**Issue by Ulisesuarez** [mdn/translated-content#20181]
### MDN URL

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/every

### ¿De qué sección específica o titular trata este problema?

Descripción

### ¿Qué información es incorrecta, inútil o incompleta?

El método every ejecuta la función callback dada una vez por cada elemento presente en el arreglo hasta encontrar uno que haga retornar un valor falso a callback (un valor que resulte falso cuando se convierta a booleano). Si **no** se encuentra tal elemento, el método every de inmediato retorna false. 

### ¿Qué esperaba ver?

El método every ejecuta la función callback dada una vez por cada elemento presente en el arreglo hasta encontrar uno que haga retornar un valor falso a callback (un valor que resulte falso cuando se convierta a booleano). Si se encuentra tal elemento, el método every de inmediato retorna false. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/array/every`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Array/every
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/array/every/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52db6587903d7b53285af87e4eaa3da782096231
* Document last modified: 2023-08-05T13:14:12.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! muchas gracias por reportar el error, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en "View this page on GitHub", te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://github.com/mdn/translated-content/assets/13079269/998bb38b-a884-41e2-8839-77af4366bc4b)

**Comment by Graywolf9** [comment]
Esto quedará resuelto en https://github.com/mdn/translated-content/pull/22150
