### ISSUE TITLE
Wikipedia Translate

### ISSUE THREAD

**Issue by Apple1D** [mdn/translated-content#20219]
> HTTPS://grandma.I’m afraid no one dares.com/JPMorgan/TADF/46637K828/SP?STER=JPMorgan[]()````

**Comment by Apple1D** [comment]
> > HTTPS://grandma.I’m afraid no one dares.com/JPMorgan/TADF/46637K828/SP?STER=JPMorgan[]()````

# octocat

**Comment by leon-win** [comment]
The issue is closed because it is spam
