### ISSUE TITLE
Content bug: Web/CSS/flex-shrinkでLive sampleが動作していない

### ISSUE THREAD

**Issue by tachibanayu24** [mdn/translated-content#2029]
## What page(s) did you find the problem on?

https://developer.mozilla.org/ja/docs/Web/CSS/flex-shrink#examples

## Specific page section or heading?

「結果」部分
en-US版では正常に動作しているようです
https://developer.mozilla.org/en-US/docs/Web/CSS/flex-shrink#examples

## What is the problem?

以下の画像のような表示になっています
![Screen Shot 2021-08-12 at 10 35 21](https://user-images.githubusercontent.com/23476543/129124816-64efc260-6829-457a-a4b2-f5a15fd45a00.png)

**Comment by itta611** [comment]
こちらでも確認できました↓
https://developer.mozilla.org/ja/docs/Web/API/CanvasRenderingContext2D/setLineDash

**Comment by mfuji09** [comment]
前身の Kuma プラットフォームで、見出しの id が自動的に変わってしまう問題が原因です。
#2100 のように修正すれば直りますが、大量に存在しますので、気が付いたときには自分で修正してみていただけると幸いです。

**Comment by itta611** [comment]
了解ですー！
