### ISSUE TITLE
リンク が w3c.github.io ではなく rawgit.com のものになっている為 404 になっている

### ISSUE THREAD

**Issue by juner** [mdn/translated-content#20365]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/InputEvent/inputType

### この問題に関する節や見出しはどこですか。

値

### 不完全、不親切、不完全であった情報は何ですか。

[Input Events Level 1 仕様の Attributes の章](https://rawgit.com/w3c/input-events/v1/index.html#interface-InputEvent-Attributes) 

### どう表示されるべきだと思いますか。

[Input Events Level 2 仕様の Attributes の章](https://w3c.github.io/input-events/#interface-InputEvent-Attributes)

### 補足情報となるリンク、参考資料、引用文献はありますか。

https://rawgit.com/w3c/input-events/v1/index.html#interface-InputEvent-Attributes
https://w3c.github.io/input-events/#interface-InputEvent-Attributes

### 他に共有したいことはありますか。

`Input Events Level 1 仕様の Attributes の章` のリンクが https://rawgit.com/w3c/input-events/v1/index.html#interface-InputEvent-Attributes になっている為 404 となる。
正しくは https://w3c.github.io/input-events/#interface-InputEvent-Attributes だと思われる。

ただし、github の markdown のソースでは次の様になっている為 原因は不明。
```md
[Input Events Level 2 仕様の Attributes の章](https://w3c.github.io/input-events/#interface-InputEvent-Attributes)
```
https://github.com/mdn/translated-content/blob/cc4abe7d2d4540b0567f0ae30074aeca92aa6b3d/files/ja/web/api/inputevent/inputtype/index.md?plain=1#L15C159-L15C228

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/inputevent/inputtype`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/InputEvent/inputType
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/inputevent/inputtype/index.md
* Last commit: https://github.com/mdn/translated-content/commit/403baa266373ec3959fa208963e6f44fd175047c
* Document last modified: 2023-11-18T07:20:20.000Z

</details>

**Comment by mikecat** [comment]
ソースの修正がページに反映されるまでにはタイムラグがあります。

> **It can be up to 48 hours** for merged pull requests to have their changes published to [MDN Web Docs](https://developer.mozilla.org).

([content/CONTRIBUTING.md](https://github.com/mdn/content/blob/c9e9f9f4faf2e8a5985e5834d9424557341f33c9/CONTRIBUTING.md#pull-request-etiquette))

現在は反映されているようです。
