### ISSUE TITLE
It should be a translation error

### ISSUE THREAD

**Issue by ailefun** [mdn/translated-content#2047]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Text_formatting

#### What information was incorrect, unhelpful, or incomplete?

The text reads as follows:
const firstString = '2 + 2'; //创建一个字符串字面量
const secondString = new String('2 + 2'); // 创建一个字符串对象
eval(firstString); // 返回数字 4
eval(secondString); // 返回字符串 "2 + 2"

The comment on the last line should be changed：//返回对象 [String: '2 + 2']

#### Specific section or headline?
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Text_formatting#%E5%AD%97%E7%AC%A6%E4%B8%B2%E5%AF%B9%E8%B1%A1

Web 开发技术->JavaScript->JavaScript 指南->Text formatting

#### What did you expect to see?
The comment on the last line should be changed：//返回对象 [String: '2 + 2']

#### Did you test this? If so, how?
Yes,This is the result of the code running on Node:

> const firstString = '2 + 2'; //创建一个字符串字面量
undefined
> const secondString = new String('2 + 2'); // 创建一个字符串对象
undefined
> eval(firstString); // 返回数字 4
4
> eval(secondString); // 返回字符串 "2 + 2"
[String: '2 + 2']

![image-20210813152538116](https://user-images.githubusercontent.com/37016479/129320380-05ba1e7c-ec5a-468e-b7a0-ce2766884c29.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/guide/text_formatting`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Text_formatting
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/guide/text_formatting/index.html
* Last commit: https://github.com/mdn/translated-content/commit/88a0fb5f5447955f55b4e7679c788f92aa320af3
* Document last modified: 2021-08-12T14:29:03.000Z

</details>

**Comment by KevinZonda** [comment]
I don't think this will be an issue. Cuz this just demonstrates it is a String instance.

**Comment by zhoushengdao** [comment]
[mdn/content #7909](https://github.com/mdn/content/pull/7909) 修复了这个错误，刚刚我进行了同步（#2189）。
