### ISSUE TITLE
resolved value の訳語を「解析値」から「解決値」に修正

### ISSUE THREAD

**Issue by mfuji09** [mdn/translated-content#205]
https://developer.mozilla.org/ja/docs/Web/CSS/resolved_value

このページでは、タイトル以下で resolved value を「解析値」と訳しています。
しかし、 resolved value を「解析値」と訳す例は他に見当たらず、また一般に使われている「解析値」とも意味が懸け離れていると思われますので、この名前を直訳に近い「解決値」に修正したほうが良いと思います。

**Comment by harukitosa** [comment]
修正しました！
https://github.com/mdn/translated-content/pull/278
