### ISSUE TITLE
Issue with "TypeError: can't access dead object": (short summary here please)

### ISSUE THREAD

**Issue by adamentch** [mdn/translated-content#2063]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Errors/Dead_object

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/reference/errors/dead_object`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Errors/Dead_object
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/errors/dead_object/index.html
* Last commit: https://github.com/mdn/translated-content/commit/964fd2ab882af4a09c92363c1c675d5d2918a79d
* Document last modified: 2021-08-14T00:43:17.000Z

</details>

**Comment by SphinxKnight** [comment]
@adamentch what's the issue with the page please?

**Comment by SphinxKnight** [comment]
I'm closing this one, if you have more details to share, feel free to do so and reopen.
