### ISSUE TITLE
zh-CN: content syntax rule of making definition in glossary

### ISSUE THREAD

**Issue by PassionPenguin** [mdn/translated-content#20679]
## 讨论主题：是否必须定语前置

是否对所有包含定语成分的做出术语定义的句子，都必须采用**定语前置**的形式**作出定义**。

### 例一 [^4]

```markdown
**文档对象模型**是一个 API，用于表示和交互任何基于 HTML 或 XML 的标记语言文档。
```

是否必须变换为

```markdown
**文档对象模型**是一个用于表示和交互任何基于 HTML 或 XML 的标记语言文档 API。
```

### 例二 [^5]

```markdown
JavaScript 的全局环境是**文档环境**，如果它是一个窗口或一个 iframe。
```

是否必须把定语前置（我没想到可以怎么前置），大概 @yin1999 的意思是

```markdown
如果 JavaScript 的全局环境是一个窗口或一个 iframe，那么它是一个**文档环境**
```

### 不是所有成分都与术语本质有关：
 
术语定义里面有很多定语，但是并非所有的定语都有重要意义，甚至有部分定语与术语定义本身**毫无关联**，比如例句一中的用法从句。

用法是随时间而变化的，**与术语的本质毫无关联**。将用法前置，语法功能上发生变化：**强调只有拥有这个用法的，才能叫做XXX**。

### 日常使用大量非前置语句

新华社关于菠萝蜜的定义[^1]、新高考关于历史地理学的定义[^2]、课本关于图的定义[^3]。

### A是xxx的B可以保证B不特定于A

> 韭黄是一种蔬菜，如果韭黄是不受光照长出来的韭菜。

难道这句话意味着**蔬菜**只能是韭黄？（[@yin1999 意见一](https://github.com/mdn/translated-content/pull/20467#discussion_r1605674867)）

### 团队成员个人要求

译文为什么要必须和团队成员其中一人的审美相匹配（[想要的效果](https://github.com/mdn/translated-content/pull/20467#discussion_r1605920301)）？

如果真的有必要，请开启投票，在一定基数的有效选票下确定风格，并**写入中文译文指南**。

### 部分修饰成分字数较长

部分修饰成分较长，如参考句[^2]，全部前置或部分长成分前置，会使单句冗长，提高阅读困难程度。
 
### 术语定义的文章最开始，应当非常明确地指出**要定义的术语**是什么：

术语定义是一个作出肯定表述的语句，语句关键强调部分在于定义本身（种概念是个**属概念**），基于 MDN Glossary 的本意

> Web technologies contain long lists of jargon and abbreviations that are used in documentation and coding. This glossary provides definitions of words and abbreviations you need to know to successfully understand and build for the web.

这一系列术语文章/页面是为提供**词语、缩写**的**定义**而生的，首先就应该指出词语、缩写。

## 参考意见

询问了 27 名朋友，涵盖物理、历史选科刚参加完高考、研究生、互联网从业者，只有 **1/27** 选择前置用法。下面是其中 8 个不支持的理由：

![9297442c5c7f14851bf382798688a756](https://github.com/mdn/translated-content/assets/41184947/9892b265-bb27-498e-9b0b-13e5a08bef6b)
![222ea097d03a970213a6753938874c04](https://github.com/mdn/translated-content/assets/41184947/1311ccc1-890f-45ad-a0f1-e973612d3fd8)
![0ca790e8bff8ba0a1ad9b89ecf2fbc85](https://github.com/mdn/translated-content/assets/41184947/2de1695b-ab75-41af-a8bf-18009b3fba58)
![6dea109a4750d4c48271d68060915e01](https://github.com/mdn/translated-content/assets/41184947/d0674a6a-6727-4fde-a763-0e710a6709c7)
![9da3c79cdd194da9b44742cedab94c5d](https://github.com/mdn/translated-content/assets/41184947/63dc2553-d015-4c91-868e-a76486d586b1)
![ee59fb361df7430cfc07726c766c9776](https://github.com/mdn/translated-content/assets/41184947/7db2821f-dde8-4ce4-8ffd-a2d635dae41a)
![5da616a49976434548570ca150e75860](https://github.com/mdn/translated-content/assets/41184947/b86485d1-e5bb-4577-befe-e0a1f48229aa)
![7bc8904fd6db7ac3cd93aa72bed73313](https://github.com/mdn/translated-content/assets/41184947/8b943474-ae80-42e0-a9c3-84d353f855fc)

## 参考非前置例句

[^1]: 新华社：`菠蘿蜜是熱帶水果，也叫木菠蘿，原産于印度南部，我國引入菠蘿蜜已經有一千多年的歷史了。`
[^2]: 2022 年新高考 I 卷语文（4）：`历史地理学是现代地理学的分支学科，具有时空结合的特征，以自然和人文地理现象的产生，形成及其演化的过程为研究对象，探寻这些现象产生、形成及其演化背后的原因和规律。`
[^3]: 刚好手边有一本课本，**随便翻了一页**就是连续几个非前置的定义（离散数学，王义和，哈尔滨工业大学出版社，9-787-5603-1443-3）（针对 @yin1999 的[异议](https://github.com/mdn/translated-content/pull/20468#discussion_r1606583379)）

    设 G=(V, E) 是一个无向图，V 的子集 S 是分离图 G，**如果 G-S 是不连通的**。（p259）

    p302 定义10.2.1

[^4]: https://github.com/mdn/translated-content/pull/20468#discussion_r1606583379
[^5]: https://github.com/mdn/translated-content/pull/20467#discussion_r1605674867

**Comment by yin1999** [comment]
首先，[请保持友善的态度](https://developer.mozilla.org/zh-CN/docs/MDN/Community/Open_source_etiquette#%E8%AF%B7%E4%BF%9D%E6%8C%81%E7%A4%BC%E8%B2%8C%E5%92%8C%E5%8F%8B%E5%A5%BD%EF%BC%8C%E9%81%BF%E5%85%8D%E4%BD%BF%E7%94%A8%E7%85%BD%E5%8A%A8%E6%80%A7%E6%88%96%E5%86%92%E7%8A%AF%E6%80%A7%E8%AF%AD%E8%A8%80)，大家都是志愿为 MDN Web 文档做出贡献；其次，我说我还在和其他两位维护者探讨相关的内容，而且为没有进一步要求你先对这些内容进行修改（但我还是需要指出这几个地方，避免合并后又定下了冲突的规则而造成内容的再次修改）。所以你反问“译文为什么要必须和团队成员其中一人的审美相匹配”并不合适（我并没有冒犯你）。

**Comment by skyclouds2001** [comment]
> 是否对所有包含定语成分的做出术语定义的句子，都必须采用**定语前置**的形式**作出定义**。

个人观点：感觉不需要硬性规定，真要说的话，如果整个句子过长可以考虑定语前置，反之不需要

PS：上面的两个例子我都认同不使用定语前置的形式更好

**Comment by yin1999** [comment]
关于上面的两处举例，我同意例二的原有写法（而非我后面给出的建议）。正如 @PassionPenguin 所指出的，文档应该先写出当前文档本身所表述的术语、特性。所以在之前审查有关事件的文档时，我一般会建议：

> `xxx` 事件在 xxx 发生时/之前/之后触发。

而不是

> 在 xxx 发生时/之前/之后会触发 `xxx` 事件。

有关第二个例子的审查确实是我的失误。

---

而关于第一个例子，我考虑的核心内容是，其实 MDN 文档所涉及的绝大多数介绍术语的文档，**其第一句话都是对特定术语/特性的定义**（而非单纯的介绍）。关于术语定义的语法格式等，其实无论是每次都按照英文的先后顺序翻译，或是按照自己的想法翻译，本身并无特别大的问题（大部分熟悉中文的读者都应能理解其意思）。

但是，我仍然希望我们能够尽可能统一这类术语定义的格式，因为相对统一的格式可以让经常查阅相关文档的人能够快速阅读文档的内容——这也是文档相对于视频的最大优势，用户可以仅通过略读就了解全文的大致内容。MDN 的内容团队为此制定了一系列关于 JavaScript API、HTML 和 CSS 的[模板](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Page_types#page_templates)——每一个模板都定义了整体的上下文格式，以及第一句话应如何开头。通过这些努力，读者都能够很快地找到他要阅读的东西在哪里，以及应该读到哪里即可停止。

有关定义前置还是后置这一点，我目前在内部的讨论中给出的建议是：

> 对于特别长的句子，我们应在宾语并不能明确地限定术语的意思的情况下，尽可能地将一些可以明确限定其意思的定语前置（参考《[科技报告编号规则](https://www.most.gov.cn/ztzl/jlkjbg/kjbgxxjl/201409/P020140915541371250765.pdf)》、《[网络教育技术标准](http://www.celtsc.org/upload_files/file/20210616/1623820448826061897.pdf)》、《[汉语信息处理词汇](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/12/20150112162349265.pdf)》、《[标准的类别](https://www.cnis.ac.cn/bzhzs/jczs/201904/t20190425_36698.html)》 等国内政府机构、高校编写的文档中所使用的术语定义格式），例如：“The Table Grid Box is a block level box which contains all of the table internal boxes, excluding the caption.”，这里的“block level box”本身并不能完全限定“Table Grid Box”，我会将其翻译为“表网格盒子（Table Grid Box）是一种包含表格中所有的内部盒子而不包含表格标题的块级盒子。”。将其翻译为“表网格盒子（Table Grid Box）是一种块级盒子，其包含表格中所有的内部盒子而不包含表格标题。”本身也无问题，能正确表示其意。
>
> 而在遇到英文版使用的后置定语嵌套、或无法在易于理解且不改变原文意思的前提下前置定语的情况，则可以将不重要/作补充说明的部分后置（可能需要变换表达的方式），这种情况一般需要添加“其”来对后置的部分进行主语限定，并以此表面这部分为补充说明。

**Comment by PassionPenguin** [comment]
> 关于上面的两处举例，……

that's good explanations with grounded points

考虑到，我们最先存在分歧的点，为什么我很反感你的建议，是因为你希望前置一个“用于……”的定语，而这在绝大多数情况下是与定义本身无关的（视频可以观看得到知识和视频的定义没有什么关系吧？）参考其他地方给出的定义

> 文档对象模型（英语：Document Object Model，缩写DOM），是W3C组织推荐的处理可扩展置标语言和超文本标记语言的标准编程接口。

>  DOM（Document Object Model，文档对象模型）是一个跨平台和语言独立的接口，它允许程序和脚本能够动态地访问和更新文档的内容、结构和样式。

个人意见，这玩意的核心定义，人家就是个接口而已……因此，我会选择把“用于……”扔到后面去

**Comment by PassionPenguin** [comment]
当然，考虑到中文没有类似于英语中的各种复杂句子，以及，有可能英语的主次关系没有中文明显（也有可能不是native speaker的原因），我们大概率会把（可能带有主次关系的）

> XXX is a interface, mainly used in Web.

给翻译成

> XXX 是一个主要用于 Web 的接口。

翻译着就容易把主次关系给丢掉了，

**Comment by yin1999** [comment]
我并不要求其他句子必须按照这一格式定义，这个说到底都是带点个人喜好的。我说的是术语表第一句的翻译，若并不复杂，请使用定语前置的写法（参考我给出的文献资料）。我相信术语定义不会有这样一句话——XXX is a interface, mainly used in Web. 因为这并不是术语定义（xxx 到底用来干了什么）。

**Comment by PassionPenguin** [comment]
> 我并不要求其他句子必须按照这一格式定义，这个说到底都是带点个人喜好的。我说的是术语表第一句的翻译，若并不复杂，请使用定语前置的写法（参考我给出的文献资料）。我相信术语定义不会有这样一句话——XXX is a interface, mainly used in Web. 因为这并不是术语定义（xxx 到底用来干了什么）。

well，dom的定义就是（that represent and interact…）

上面的回复（https://github.com/mdn/translated-content/issues/20679#issuecomment-2131300391），

在glossary里面，dom是展示与交互html/xml树状结构的，

然而在web/api/dom里面，

> even though modeling HTML, SVG, or XML documents as objects

dom是可以展示html、xml文档、**svg**的（可以展示的东西会有更新，dom是这类东西的统称，这是我扔到后面的一个原因了）

**Comment by yin1999** [comment]
对，但 [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) 文档的第一句话在我看来并不适合用于我们所涉及的科技术语的定义形式，科技术语定义本身应是对术语本身的说明，核心为 xxx 是什么，而非描述性的话语。论文《[关于科技术语定义的基本问题](https://www.term.org.cn/CN/abstract/abstract11256.shtml)》表述了这一点。

**Comment by PassionPenguin** [comment]
> 对，但 [DOM](https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model) 文档的第一句话在我看来并不适合用于我们所涉及的科技术语的定义形式，科技术语定义本身应是对术语本身的说明，核心为 xxx 是什么，而非描述性的话语。论文《[关于科技术语定义的基本问题](https://www.term.org.cn/CN/abstract/abstract11256.shtml)》表述了这一点。

这里确实不是定义。我引用是希望指出，"用于"这种定语与定义本身关联性不强。这里例子是说明在多个关于DOM的说明中，用于……的内容是变化的（术语这里是HTML&XML文档，API那里是HTML&XML&SVG）。

也许，除了规范定义的语法外，我们也应该规范上流的定义，让其*更*贴合术语本身（i.e. 独立句子，抽离其他修饰语）。

**Comment by awxiaoxian2020** [comment]
关于该问题，个人更倾向于在不影响可读性的前提下，需要所谓的“定语前置”。
将“条件”“定语”放在后面是典型的英语语法。定语前置是典型的现代汉语习惯。

在这个 issue 中，你列举的这些后置的例子，都只是对于该事物的描述性补充，而并非是刻意采用“后置”。

比如“菠蘿蜜是熱帶水果，也叫木菠蘿，原産于印度南部，我國引入菠蘿蜜已經有一千多年的歷史了。”，第一个分句已经完全交代了其热带水果的性质，后面是对它的补充。这并不是定义而是描述，是给大众看的一种描述。

但是，如果在 web 文档中生硬地直译，比如你提到的例子：

“**文档对象模型**是一个 API，用于表示和交互任何基于 HTML 或 XML 的标记语言文档。”，“是一个 API”给的具体信息过少，没有必要这样去写。如果有补充内容，那是可以断句并往后放的，比如“**文档对象模型**是一个W3C组织推荐的处理可扩展置标语言的 API，它用于表示和交互任何基于 HTML 或 XML 的标记语言文档。”或者“**文档对象模型**是一个处理可扩展置标语言的 API，它由W3C推荐，用于表示和交互任何基于 HTML 或 XML 的标记语言文档。”总而言之，除了我们（受众）特别不熟悉的事物，一般不会采用无定语的直接描述。因为“**文档对象模型**是一个 API”，这句话我认为对于需要阅读它的受众，信息量极少。但是“猹是一种动物，出现于鲁迅小说《故乡》”，这是可以接受的。至于你所说的，丧失重点，这种将名词置前强调重要性正是英语的特色。至于你所说的离散课本的例子，我个人凭空猜测，也是编者自己直译外文文献的结果。条件置前是现代汉语书面语需要遵循的一般规则，也就是“如果”一般不会放在后面，这是因为现代汉语书面语关联词是成套的。

对于“韭黄是一种蔬菜，如果韭黄是不受光照长出来的韭菜。”这句话的问题不在于放后面还是放前面，而是“如果”在这里很像英文直译，可调整为“韭黄其实也是一种蔬菜，它其实就是不受光照长出来的韭菜”，或者“韭黄实际上就是不受光照长出来的韭菜，它也是一种蔬菜”，都是可以接受的。

问题不在于前或者后，最重要的是符合现代汉语的习惯~

**Comment by Josh-Cena** [comment]
我一般觉得定语后置更好，我不大喜欢汉语句子头重脚轻（[符合余光中的理论](https://zhuanlan.zhihu.com/p/482197354?utm_psn=1788510630208208896) ^^）但同时，我不觉得我们应该纠结定语前置还是后置的规范，如果 zh-CN 团队需要文字规范，那么要么精确到每一个词（就像 en-US 的页面模板一样），要么就就事论事。

> **文档对象模型**是一个用于表示和交互任何基于 HTML 或 XML 的标记语言文档 API。

我觉得这个可以接受，因为定语不是过长，但它的可扩展性更差一点，如果想要添加更多信息，就得重写句子。

> **文档对象模型**是一个 API，用于表示和交互任何基于 HTML 或 XML 的标记语言文档。

我觉得这个也 OK，但主句太弱，没有信息。不过这个写法更通用——因为中文没有从句结构，要么就得定语嵌套，要么就重写成复合句。但是，为什么一定要拘泥于英文的一字一句翻译呢？我作为 en-US 的作者，如果我来写 zh-CN 的原创文档，我会这么写：

> **文档对象模型** API 用于表示和交互任何基于 HTML 或 XML 的标记语言文档。

每个语言都有自己的表达习惯，我觉得不用做到字句对应，只要能传达一样的信息即可。

> JavaScript 的全局环境是**文档环境**，如果它是一个窗口或一个 iframe。

我觉得这不符合汉语习惯。数学书会这么写（就像你引用的教科书），但作为面向开发者的文档，还是应该更加日常一点。

> 如果 JavaScript 的全局环境是一个窗口或一个 iframe，那么它是一个**文档环境**

我觉得这个更好，符合汉语习惯。中文不是一个 topic-first 的语言（其实有倒装结构，但不是非常书面），没有必要贴近 en-US 的句式结构。

其实最符合表达习惯的中文不会使用很多逻辑连词（我自己写文章时也会有这个问题，会比较翻译腔），所以这里这么写也可以：

> **文档环境**是一种 JavaScript 全局环境，特指它是一个窗口或一个 iframe 的情况。

总地来说，我觉得很多句子是否自然，只需读一遍就可以了，「A，如果 B」 一般都不符合中文习惯，「如果 A，那么 B」，或者「A，但仅在 B 的情况下」才更加通顺（一般如果想调整语序，都需要加很多字，我觉得不是大问题）。但是 zh-CN 团队完全不需囿于原文的逻辑，因为原文也是像我们这样的普通作者写的，也不一定有细微的斟酌 ^^

> 那么，这句话是否应该改成：
>
> > 一组代码，用于标识科学技术报告创建者。

这两个句子对我是完全等价的。
