### ISSUE TITLE
这个ArrayBuffer的内容似乎是错误的

### ISSUE THREAD

**Issue by XIAO-RUI-RUI** [mdn/translated-content#20723]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Typed_arrays

### 与此议题相关的小节或标题？

示例/相同数据上的多个视图

### 哪些信息是错误、无用或不完善的？

这句话：”这次的输出是 "32 位数组的索引 0 处数据是：32"。也就是，这 2 个数组都是同一数据的以不同格式展示出来的视图。“
下面的二进制演示中，这里似乎是错误的：
Int16Array  |  32  |  0   |   2  |  0   |   4  |  0   |   6  |  0   |
Int32Array  |     32      |      2      |      4      |      6      |
ArrayBuffer | 00 02 00 00 | 02 00 00 00 | 04 00 00 00 | 06 00 00 00 |
—————————↑

应该是
ArrayBuffer | 20 00 00 00 | 02 00 00 00 | 04 00 00 00 | 06 00 00 00 |
———————↑

因为0d32(00 20），以小端的方式，转换出来是20 00。

### 你期望看到什么？

ArrayBuffer | 20 00 00 00 | 02 00 00 00 | 04 00 00 00 | 06 00 00 00 |
———————↑

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/guide/typed_arrays`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Typed_arrays
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/guide/typed_arrays/index.md
* Last commit: https://github.com/mdn/translated-content/commit/0e0687ae26847a3da005b0d330868c31b021ddb9
* Document last modified: 2023-11-02T04:27:46.000Z

</details>

**Comment by yin1999** [comment]
以[小端序](https://zh.wikipedia.org/wiki/%E5%AD%97%E8%8A%82%E5%BA%8F#%E5%B0%8F%E7%AB%AF%E5%BA%8F)存储时，二进制表示的高8位存储在低8位的后面文档中的描述是对的。

32 用十六位二进制表示时，其值始终为 `0x0200`，在转换为底层的 8 位一组的形式存储时，高八位 `0x02` 存储在低八位 `0x00` 之后，因此写法为 `00 02`。

**Comment by XIAO-RUI-RUI** [comment]
32用十六位二进制表示，不是0x00 20吗？0x0200是512了。

**Comment by XIAO-RUI-RUI** [comment]
![image](https://github.com/mdn/translated-content/assets/62062993/21e17d76-fad3-4805-b0b7-01395ec72411)

**Comment by yin1999** [comment]
对的对的，我搞错了。上游的英文文档也有问题，我会跟进修复。
