### ISSUE TITLE
[zh-cn]: Translate `Audio Output Devices API`

### ISSUE THREAD

**Issue by tianyeeT** [mdn/translated-content#20744]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Audio_Output_Devices_API#browser_compatibility

### What information was incorrect, unhelpful, or incomplete?

The `Audio Output Devices API` needs to be translated into Chinese.

### What did you expect to see?

Translation

**Comment by skyclouds2001** [comment]
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/Audio_Output_Devices_API
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/sinkId
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/selectAudioOutput

**Comment by yin1999** [comment]
Done
