### ISSUE TITLE
proofread and update `Web APIs/Background Fetch API` section of `ja/ko/ru/pt-br/zh`

### ISSUE THREAD

**Issue by tianyeeT** [mdn/translated-content#20745]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Background_Fetch_API

### What information was incorrect, unhelpful, or incomplete?

We need to start the translation for the `zh` version.
Updates are needed for `ja/ko/ru/pt-br`.

### What did you expect to see?

```[tasklist]
### Tasks
- [x] #20886
- [ ] `zh-tw`
- [ ] `ja`
- [ ] `ko`
- [ ] `ru`
- [ ] `pt-br`
```

**Comment by skyclouds2001** [comment]
呃这个是打算所有语言都翻译一遍么

**Comment by PassionPenguin** [comment]
> 呃这个是打算所有语言都翻译一遍么

有点……强悍（汗流浃背了）

**Comment by skyclouds2001** [comment]
而且如果真是这样的话放在 [MDN translated-content l10n-zh](https://github.com/orgs/mdn/projects/43) 也不太合适

**Comment by yin1999** [comment]
我感觉这类议题的意义不大。应由相关的有兴趣参与对应语言的贡献者来创建对应语言的更新追踪议题更为合适。不然相关的议题只会长时间堆积。我会暂时关闭该议题。
