### ISSUE TITLE
problemes de liens

### ISSUE THREAD

**Issue by jfalycee** [mdn/translated-content#2095]
Bonjour,
les liens  en bas de page
 Structure de Site Web et de document
Qu'y-a-t-il dans l'en-tête ? Métadonnées en HTML
Fondamentaux du texte HTML
Création d'hyperliens
Formatage avancé du texte
Déboguer de l'HTML

ne sont pas valides
cordialement
JFA

**Comment by SphinxKnight** [comment]
Bonjour @jfalycee, merci beaucoup pour ce rapport, j'ai a priori corrigé le problème dans #2337.

Si vous rencontrez de telles erreurs, n'hésitez pas à indiquer les liens des pages problématiques, cela simplifie / accélère d'autant la correction.
