### ISSUE TITLE
[zh-cn] reverse descriptive semantics

### ISSUE THREAD

**Issue by pilipala233** [mdn/translated-content#20957]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Equality

### 哪些信息是错误、无用或不完善的？

"Number to String：使用..."

### 你期望看到什么？

String to Number：使用...

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/operators/equality`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Equality
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/operators/equality/index.md
* Last commit: https://github.com/mdn/translated-content/commit/523ca6e8c3eefc50fdbf2209a5e6b6de9ccf4ebc
* Document last modified: 2022-10-01T03:20:40.000Z

</details>

**Comment by yin1999** [comment]
英文文档也有相同的问题，需要更新

**Comment by PassionPenguin** [comment]
@pilipala233 you may refer to mdn/content#34003's discussions

**Comment by yin1999** [comment]
It is still worthwhile to correct the translation of the Chinese documentation. Created #21395.
