### ISSUE TITLE
Issue with "WeakMap": Sections failed to generate

### ISSUE THREAD

**Issue by Ragnar-Oock** [mdn/translated-content#2127]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

#### What information was incorrect, unhelpful, or incomplete?
the Properties (Propriétés) and Methods (Méthodes) sections failed to generate and showed template code instead :
```
Propriétés
{{page('fr/docs/Web/JavaScript/Reference/Objets_globaux/WeakMap/prototype','Properties')}}

Méthodes
{{page('fr/docs/Web/JavaScript/Reference/Objets_globaux/WeakMap/prototype','Methods')}}
```

#### Specific section or headline?
[Properties](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#propri%C3%A9t%C3%A9s_2)
[Methods](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#m%C3%A9thodes)

#### What did you expect to see?
Two sections with the list of properties and methods respectively (like on the en-US version of the page)

#### Did you test this? If so, how?
load the page in french [link](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/WeakMap)
=> content is broken
load the page in english [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap)
=> content is fine

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/weakmap`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/weakmap/index.html
* Last commit: https://github.com/mdn/translated-content/commit/08e8e32fe3a76627b6bb27ff014ea517105634e7
* Document last modified: 2021-08-18T00:47:06.000Z

</details>

**Comment by SphinxKnight** [comment]
Thanks a lot for the detailed report @Ragnar-Oock ! There is a pending migration PR (https://github.com/mdn/translated-content/pull/1835) for the JavaScript section but we'll make sure to fix this after it has been merged.
