### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by synchronicma** [mdn/translated-content#21286]
### URL MDN

https://developer.mozilla.org/fr/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL

### Sur quelle section/titre porte ce problème ?

Toute la page

### Quelle information était incorrecte, inutile ou incomplète ?

Les images ne s'affichent pas en français

### Que vous attendiez-vous à voir ?

Les images comme dans https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/common_questions/web_mechanics/what_is_a_url`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/common_questions/web_mechanics/what_is_a_url/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by quentin-rey** [comment]
Même constat que pour #21014, toute la page est à revoir.

**Comment by SphinxKnight** [comment]
Merci @synchronicma et @quentin-rey, je propose une mise à jour prochainement
