### ISSUE TITLE
这两个链接怎么是赌博网站？

### ISSUE THREAD

**Issue by XIAO-RUI-RUI** [mdn/translated-content#21319]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/Performance/Multimedia

### 哪些信息是错误、无用或不完善的？

1. https://images.guide。
2. 参阅将以前的图像格式转换为 AVIF 的在线工具。

### 你期望看到什么？

正确的内容。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/performance/multimedia`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Performance/Multimedia
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/performance/multimedia/index.md
* Last commit: https://github.com/mdn/translated-content/commit/fdd01d372363fbc6416dc930ae9ab2eeacf30f69
* Document last modified: 2023-09-29T10:39:31.000Z

</details>

**Comment by jasonren0403** [comment]
* `images.guide` 英文文档已移除，需要更新
* 我这边检查了下，`avif.io` 确实链入有些问题，可以给上游 mdn/content 仓库提 PR 要求更新。 @yin1999 可以验证下

```bash
curl -I https://avif.io
HTTP/1.1 301 Moved Permanently
Server: nginx/1.20.1
Date: Wed, 05 Jun 2024 10:17:59 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Location: https://startdee.com/
Strict-Transport-Security: max-age=63072000
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Frame-Options: SAMEORIGIN
X-Cache-Status: HIT
```

**Comment by yin1999** [comment]
可以验证，需要从英文文档中移除

**Comment by yin1999** [comment]
Created mdn/content#33936 to remove the link to `avif.io`.
