### ISSUE TITLE
:has bug in safari

### ISSUE THREAD

**Issue by dh20156** [mdn/translated-content#21416]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/:has

### 哪些信息是错误、无用或不完善的？

:has bug in safari:
------------------
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Shadow DOM Input Display Example</title>
</head>
<body>

<kube-chat></kube-chat>

<script>
  class kubeChat extends HTMLElement {
    constructor() {
      super();
      const shadow = this.attachShadow({ mode: 'open' });

      shadow.innerHTML = `
        <style>
            .send{
                display:none;
            }
    
            .tool:has(+.ask input:valid) .send{
                display: block;
            }
        </style>

        <div class="tool"><span class="send">Send</span></div>
        <div class="ask">
            <input type="text" class="input" required="required" />
        </div>
      `;
    }
  }

  customElements.define('kube-chat', kubeChat);
</script>

</body>
</html>

-------------
workaround:
-------------

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Shadow DOM Input Display Example</title>
</head>
<body>

<kube-chat></kube-chat>

<script>
  class kubeChat extends HTMLElement {
    constructor() {
      super();
      const shadow = this.attachShadow({ mode: 'open' });

      shadow.innerHTML = `
        <style>
          :host{
            --send-display:none;
          }
          .tool:has(+.ask input:valid) {
            --send-display: inline-flex;
          }
          .send {
            display: var(--send-display);
          }
        </style>
        <div class="tool"><span class="send">Send</span></div>
        <div class="ask">
            <input type="text" class="input" required="required" />
        </div>
      `;
    }
  }

  customElements.define('kube-chat', kubeChat);
</script>

</body>
</html>

### 你期望看到什么？

note this issue

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/_colon_has`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/:has
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/_colon_has/index.md
* Last commit: https://github.com/mdn/translated-content/commit/ec3c277902a9cb91c2c5c707ed6f51dee2f471d9
* Document last modified: 2023-10-08T02:49:03.000Z

</details>

**Comment by yin1999** [comment]
Hey @dh20156. Please describe the problem of the documentation in detail, instead of just pasting _code that is not in the documentation_.

**Comment by yin1999** [comment]
I'll close this issue if there is no any response within a week

**Comment by yin1999** [comment]
I'm going to close this. Welcome to reopen this, if you can provide the details :)
