### ISSUE TITLE
有关 margin-block-start 属性中不恰当取值的建议

### ISSUE THREAD

**Issue by Elon-fast** [mdn/translated-content#21650]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/margin-block-start

### 与此议题相关的小节或标题？

取值

### 哪些信息是错误、无用或不完善的？

margin-block-start 属性的取值与 [margin-left](https://developer.mozilla.org/zh-CN/docs/Web/CSS/margin-left) 属性相同。

### 你期望看到什么？

margin-block-start属性的取值与margin-top属性相同

### 你有什么支持的链接、参考或引用？

在浏览器默认样式中，即不使用css属性writing-mode: vertical-lr时，margin-block-start属性的取值与margin-top属性相同，只有在使用了writing-mode: vertical-lr后margin-block-start属性的取值才与margin-left属性相同。希望可以修改一下谢谢！

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/margin-block-start`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/margin-block-start
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/margin-block-start/index.md
* Last commit: https://github.com/mdn/translated-content/commit/4e111b0f73a4dd15a9bf1f4c8675c8dc27c00c55
* Document last modified: 2023-05-30T04:00:39.000Z

</details>

**Comment by yin1999** [comment]
这句话的意思应该是，`margin-block-start` 属性可用的值与 `margin-left` 是相同的。我认为这个说法并不存在问题。

- https://drafts.csswg.org/css-logical/#margin-properties
- https://drafts.csswg.org/css-box-4/#margin-physical

**Comment by Elon-fast** [comment]
> 这句话的意思应该是，`margin-block-start` 属性可用的值与 `margin-left` 是相同的。我认为这个说法并不存在问题。
> 
> * https://drafts.csswg.org/css-logical/#margin-properties
> * https://drafts.csswg.org/css-box-4/#margin-physical

好的谢谢是我理解错了麻烦您了
