### ISSUE TITLE
Vocabulary error in French translation: we don't say "registraire"

### ISSUE THREAD

**Issue by nolliug** [mdn/translated-content#21983]
### URL MDN

https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web/Publishing_your_website

### Sur quelle section/titre porte ce problème ?

"registraire de nom domaine"

### Quelle information était incorrecte, inutile ou incomplète ?

Dans "[Trouver un hébergement et un nom de domaine](https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web/Publishing_your_website#trouver_un_h%C3%A9bergement_et_un_nom_de_domaine)", il est écrit "registraire de nom domaine". 

### Que vous attendiez-vous à voir ?

"registrar de noms domaine", "registrar" ou mieux encore "bureau d'enregistrement accrédité
".

### Avez-vous des liens, références ou citations sur ce sujet ?

https://www.axenet.fr/definition-registrar/

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/getting_started_with_the_web/publishing_your_website`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web/Publishing_your_website
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/getting_started_with_the_web/publishing_your_website/index.md
* Last commit: https://github.com/mdn/translated-content/commit/058a2d8d277e140e1129054d31d790f5188d6057
* Document last modified: 2024-05-13T08:40:22.000Z

</details>

**Comment by quentin-rey** [comment]
Bonjour,

Registraire me semble correct :
- https://www.culture.fr/franceterme/terme/TELE456
- https://fr.wikipedia.org/wiki/Registraire_de_nom_de_domaine
