### ISSUE TITLE
[ko] Using CSS nesting 페이지 내 번역 오류

### ISSUE THREAD

**Issue by biniruu** [mdn/translated-content#22071]
### MDN URL

https://developer.mozilla.org/ko/docs/Web/CSS/CSS_nesting/Using_CSS_nesting

### 이 문제에 관한 특정 섹션 또는 제목은 무엇인가요?

자식 선택자

### 어떤 정보가 부정확하거나 도움이 되지 않거나 불완전했나요?

 '자식 선택자' 항목 내 '중첩 선택자를 사용하는 경우'와 '중첩 선택자를 사용하지 않는 경우' 헤딩 번역이 잘못되었습니다. 'Without nesting selector'가 '중첩 선택자를 사용하는 경우'로, 'With nesting selector'가 '중첩 선택자를 사용하지 않는 경우'로 각각 번역되었습니다.

### 어떻게 고쳐져야 하나요?

현재 '중첩 선택자를 사용하는 경우'로 번역된 헤딩은 '중첩 선택자를 사용하지 않는 경우'로, '중첩 선택자를 사용하지 않는 경우'는 '중첩 선택자를 사용하는 경우'로 각각 변경되어야 합니다.

### 지원 링크, 참조 또는 인용구가 있으신가요?

'중첩 선택자를 사용하는 경우'로 변역된 부분
- https://developer.mozilla.org/ko/docs/Web/CSS/CSS_nesting/Using_CSS_nesting#중첩_선택자를_사용하는_경우
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting#without_nesting_selector

'중첩 선택자를 사용하지 않는 경우'로 번역된 부분
- https://developer.mozilla.org/ko/docs/Web/CSS/CSS_nesting/Using_CSS_nesting#중첩_선택자를_사용하지_않는_경우
- https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting/Using_CSS_nesting#with_nesting_selector

**Comment by wisedog** [comment]
이슈 제기해주시고 직접 PR 까지 올려주셔서 감사합니다.
