### ISSUE TITLE
[ko] OPTIONS HTTP 요청 메소드 페이지 상태코드 오타

### ISSUE THREAD

**Issue by NewfolderGames** [mdn/translated-content#22101]
### MDN URL

https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/OPTIONS

### 이 문제에 관한 특정 섹션 또는 제목은 무엇인가요?

OPTIONS

### 어떤 정보가 부정확하거나 도움이 되지 않거나 불완전했나요?

[예제](https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/OPTIONS#%EC%98%88%EC%A0%9C)
예제 응답에 있는 상태코드에 오타가 있습니다. 204가 아니라 200 상태코드로 적혀있습니다.

```
HTTP/1.1 200 No Content
Allow: OPTIONS, GET, HEAD, POST
Cache-Control: max-age=604800
Date: Thu, 13 Oct 2016 11:45:00 GMT
Server: EOS (lax004/2813)
```

### 어떻게 고쳐져야 하나요?

```
HTTP/1.1 204 No Content
```

### 더 공유하고 싶은게 있으신가요?

![image](https://github.com/mdn/translated-content/assets/23236291/a318117b-f61e-4823-8d7b-bdca582f6776)

**Comment by NewfolderGames** [comment]
![image](https://github.com/mdn/translated-content/assets/23236291/09d945f8-9fde-4cd0-b36b-e42a0505d9d8)
페이지 아래쪽에 있는 예제는 `200 OK`로 적여야 합니다. 영문 문서에는 `200 OK`로 되어있습니다.

**Comment by NewfolderGames** [comment]
넵 알겠습니다. 혹시 모르니 영문 문서와 비교해서 다른 오타도 찾아보고 PR 올리겠습니다.

**Comment by wisedog** [comment]
제일 좋은건 해당 페이지 전체를 최신화하는건데요, 처음 하신다면 조금 어려울 수도 있고 그렇습니다 : )

**Comment by yin1999** [comment]
Fixed in #22475. Closing this issue.
