### ISSUE TITLE
[ru] Broken "Browser compatibility" section

### ISSUE THREAD

**Issue by intelrug** [mdn/translated-content#22112]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/API/Web_Workers_API/Using_web_workers

### О какой части статьи или абзаце идёт речь?

Browser compatibility / Совместимость с браузерами

### Какая информация оказалась неверной, бесполезной или неполной?

Broken section

### Как бы вы исправили?

I think we need to remove this section, since it does not exist on the English version of the page.

### Хотите добавить что-то ещё?

![изображение](https://github.com/mdn/translated-content/assets/18365200/c0d7d28b-87bb-4ff5-b18c-4814357a6974)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/api/web_workers_api/using_web_workers`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Web_Workers_API/Using_web_workers
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/web_workers_api/using_web_workers/index.md
* Last commit: https://github.com/mdn/translated-content/commit/3d2a4e80605c3cb59164b23cd716970c9a9da4f7
* Document last modified: 2023-11-27T20:54:48.000Z

</details>

**Comment by leon-win** [comment]
Привет, @intelrug !

Спасибо за указание на ошибку! :+1: 

Убрал секцию совместимости с браузерами в https://github.com/mdn/translated-content/pull/22114 :ok_hand:
