### ISSUE TITLE
Issue with "Document.importNode()": deepの注釈がおかしい

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/translated-content#2214]
MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Document/importNode

#### What information was incorrect, unhelpful, or incomplete?
注釈の漢字変換に誤りがある。
また、「おすすめの方法」の内容は7年前のもので、現在必要な情報ではないと思われる。

#### Specific section or headline?
https://developer.mozilla.org/ja/docs/Web/API/Document/importNode#parameters

#### What did you expect to see?
注: DOM4 仕様書では、 `deep` はオプションの引数で、既定値は `true` でした。

最新の仕様書ではこの既定値が変更されました。新しい既定値は `false` になりました。

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ja/web/api/document/importnode`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Document/importNode
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/document/importnode/index.html
* Last commit: https://github.com/mdn/translated-content/commit/57b7a0c468a45877134bcbfa64ee9b1741794b0b
* Document last modified: 2021-08-22T17:10:24.000Z

</details>

**Comment by mfuji09** [comment]
翻訳が古くなっていることが原因ですので、最新の英語版の更新を反映させました。
