### ISSUE TITLE
Images are not loading in `Web/HTTP/Overview`

### ISSUE THREAD

**Issue by artyomevsyukov** [mdn/translated-content#22170]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/HTTP/Overview

### What information was incorrect, unhelpful, or incomplete?

images are not loading

### What did you expect to see?

Fix image loading

### Do you have any supporting links, references, or citations?

![Screenshot 2024-07-05 180105](https://github.com/mdn/translated-content/assets/110418644/3b809a06-02a6-4021-adff-70ec4a70d98c)
![Screenshot 2024-07-05 180058](https://github.com/mdn/translated-content/assets/110418644/e44478d7-e46b-4929-9878-bf09bf64f39e)
![Screenshot 2024-07-05 180050](https://github.com/mdn/translated-content/assets/110418644/08213314-f03a-4c89-8225-07e3516b6cab)

```[tasklist]
### Tasks
```

**Comment by leon-win** [comment]
Привет, @artyomevsyukov !

Thank you for your help with the MDN!

I have fixed the display of images in this document for all languages ​​where the problem occurred :ok_hand: 

Now we will wait for a review of the PRs.

**Comment by artyomevsyukov** [comment]
It doesn't work anyway
https://developer.mozilla.org/ru/docs/Web/HTTP/Overview
![Screenshot 2024-07-13 115219](https://github.com/user-attachments/assets/f372d48d-d6f1-4efa-bc7b-65b4350adb9f)

**Comment by Graywolf9** [comment]
Hi! @artyomevsyukov 

Before all, thank you so much for your time

The problem its going to be solved in `ru` once this PR https://github.com/mdn/translated-content/pull/22303 has been merged

**Comment by leon-win** [comment]
Now done for all locales :ok_hand:
