### ISSUE TITLE
issue in mobile H5 application 

### ISSUE THREAD

**Issue by fbzcmk** [mdn/translated-content#22191]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API

### 哪些信息是错误、无用或不完善的？

the speech recognition works well on pc , when applied on mobile ,it can recognize only one sentence . then it didn't response anymore,it seems the microphone access has been blocked after one sentence has finished ,although I granted microphone access when recognition.start() 
Is it possible to provide microphone access API to apply for  mobile microphone access authorization during whole application life cycle ? 

### 你期望看到什么？

a guide or demo for application on mobile h5 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/web_speech_api/using_the_web_speech_api`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/web_speech_api/using_the_web_speech_api/index.md
* Last commit: https://github.com/mdn/translated-content/commit/e005be662421aee99588a6134318f2a1fee7d549
* Document last modified: 2024-06-06T12:39:52.000Z

</details>

**Comment by yin1999** [comment]
Hey @fbzcmk. Sorry for the delay. I tried the example on my Android phone (oneplus ace 2 pro, Android 14) and I could not get this example to work properly the first time I ran it. I'm not sure if the capabilities of this API is affected by the speech recognition provider (it seems that Chromium itself does not provide speech recognition services, it just uses the speech recognition provider provided by the Android device).

/cc @mdn/mdn-community-engagement

**Comment by bsmth** [comment]
Tanks for reporting and for tagging us! Could you provide some more information about the mobile operating system and browser version?

You can also try this page which checks support: https://www.google.com/intl/en/chrome/demos/speech.html

**Comment by yin1999** [comment]
> Could you provide some more information about the mobile operating system and browser version?

```plain
OS: ColorOS 14 (based on Android 14)
Browser Version: Chrome 128.0.66.13.127
```

> You can also try this page which checks support: https://www.google.com/intl/en/chrome/demos/speech.html

I could not get this demo work on my phone, and I woud get some errors:

![image](https://github.com/user-attachments/assets/ab04609b-6e5b-4d0d-8e31-1f2dd357694a)

**Comment by caugner** [comment]
Closing as stale.
