### ISSUE TITLE
Programmable Web API directory网站已关闭

### ISSUE THREAD

**Issue by Twinblade-i** [mdn/translated-content#22344]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Introduction

### 与此议题相关的小节或标题？

什么是 API?#常见第三方 API

### 哪些信息是错误、无用或不完善的？

备注中 "http://www.programmableweb.com/category/all/apis" 网站已关闭

### 你期望看到什么？

none

### 你有什么支持的链接、参考或引用？

https://www.mulesoft.com/programmableweb

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/client-side_web_apis/introduction`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Introduction
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/client-side_web_apis/introduction/index.md
* Last commit: https://github.com/mdn/translated-content/commit/bbb747e62dfc7aec394a9292fbef2f2157567251
* Document last modified: 2024-03-01T12:00:00.000Z

</details>

**Comment by tianyeeT** [comment]
文档需要更新，欢迎PR。
