### ISSUE TITLE
[pt-br] mouseover_event page without side menu

### ISSUE THREAD

**Issue by ProTankerAlfa** [mdn/translated-content#22434]
### MDN URL

https://developer.mozilla.org/pt-BR/docs/Web/API/Element/mouseover_event

### What information was incorrect, unhelpful, or incomplete?

The page is missing the side menu

### What did you expect to see?

The side menu

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/api/element/mouseover_event`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/API/Element/mouseover_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/api/element/mouseover_event/index.md
* Last commit: https://github.com/mdn/translated-content/commit/942fd64b21d84f01051983cc86bac12c9768c5d4
* Document last modified: 2023-08-04T02:17:52.000Z

</details>

**Comment by leon-win** [comment]
I added a sidebar and synchronized the content with the `en-US` version in #22435.
