### ISSUE TITLE
Window.length翻译问题

### ISSUE THREAD

**Issue by l1yolo** [mdn/translated-content#22433]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Window

### 哪些信息是错误、无用或不完善的？

`Window.length` 的解释，翻译成`帧数`恐怕不合适，这里`frame`并不是`帧`的含义吧，直接翻译成`帧数`，恐怕会误导读者。
![image](https://github.com/user-attachments/assets/e36651f6-cfc3-41c8-9285-abd6d190862f)

### 你期望看到什么？

希望有更恰当的翻译，或者这个frame直接不译、保留，也比把`Windowo.length`的解释翻译成`帧数`好一点。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/window`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Window
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/window/index.md
* Last commit: https://github.com/mdn/translated-content/commit/fa9e65a3feb729b5b7a474a55799a508f1b9b2a1
* Document last modified: 2024-06-04T06:21:20.000Z

</details>

**Comment by yin1999** [comment]
应该翻译成“框架（frame）数”
