### ISSUE TITLE
所有"MDN Web 文档术语表：Web 相关术语的定义"目录下缩小窗口后文章高度异常问题

### ISSUE THREAD

**Issue by Elon-fast** [mdn/translated-content#22482]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Glossary/Abstraction

### 与此议题相关的小节或标题？

抽象编程（Abstraction）

### 哪些信息是错误、无用或不完善的？

缩小窗口后底部出现大量空白，高度异常，但是调出控制台后高度就恢复正常了

### 你期望看到什么？

文章底部不出现大量空白

### 你还想补充什么内容？

<img width="728" alt="屏幕截图 2024-07-19 105707" src="https://github.com/user-attachments/assets/6898f1fb-ef72-4e07-97f4-110bc3f6f4d9">
<img width="727" alt="屏幕截图 2024-07-19 105757" src="https://github.com/user-attachments/assets/d655d6fe-c0d9-46d2-87ae-ea759010de52">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/glossary/abstraction`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Glossary/Abstraction
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/glossary/abstraction/index.md
* Last commit: https://github.com/mdn/translated-content/commit/cc5053a3dc80dbaf5749d862aec12fe2d83ee288
* Document last modified: 2024-04-10T02:11:54.000Z

</details>

**Comment by hanyujie2002** [comment]
Please publish your issue in https://github.com/mdn/yari

**Comment by hanyujie2002** [comment]
By the way, I met the problem months ago as well. But I forgot to report it. Thank you for your issue. 👍

**Comment by hanyujie2002** [comment]
This bug emerges in every short article, not only in this one.

**Comment by Elon-fast** [comment]
I have already reported on the corresponding website, thank you！

**Comment by yin1999** [comment]
Reported in mdn/yari#11501. Closing this issue.
