### ISSUE TITLE
educational example throws error in console

### ISSUE THREAD

**Issue by iamAxilles** [mdn/translated-content#22499]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/async_function

### О какой части статьи или абзаце идёт речь?

last

### Какая информация оказалась неверной, бесполезной или неполной?

async function getProcessedData(url) {
  let v;
  try {
    v = await downloadData(url);
  } catch (e) {
    v = await downloadFallbackData(url);
  }
  return processDataInWorker(v);
}

### Как бы вы исправили?

i dont know 

### Есть ли у вас какие-либо подтверждающие ссылки?

https://hkar.ru/193Hy

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/statements/async_function`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/async_function
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/statements/async_function/index.md
* Last commit: https://github.com/mdn/translated-content/commit/ea84746aa880c3e7f5076dc4d7e4e94af171c348
* Document last modified: 2024-01-06T23:57:34.000Z

</details>

**Comment by VBasko** [comment]
Уважаемый пользователь!

Это **вымышленный** пример, показывающий пример рефакторинга кода с целью улучшения его читаемости.

Предполагается, что где-то ранее в коде были определены функции `downloadData`, `downloadFallbackData` и `processDataInWorker`.

Без них код не должен работать)

**Comment by leon-win** [comment]
Всё именно так, как объяснила @VBasko ! :+1: 

Хотя этому документу и не помешало бы обновление в соответствии с оригиналом)), именно эта его часть корректна.
