### ISSUE TITLE
[ko] 조사 오타 & 설명 오류

### ISSUE THREAD

**Issue by rami0617** [mdn/translated-content#22555]
### MDN URL

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

### 이 문제에 관한 특정 섹션 또는 제목은 무엇인가요?

매개변수

### 어떤 정보가 부정확하거나 도움이 되지 않거나 불완전했나요?

1) 매개변수를 설명하는 부분 중 target에 
정수 변환 후 target이 start 보**디** 뒤에 위치하면, array.length의 끝부분까지만 복사가 수행됩니다(즉, copyWithin()은 배열을 확장하지 않습니다). 라고 되어있는데 '보디' -> '보다'로 오타가 있었습니다.

2) 밑에 start부분에 target을 기준으로 작성되어있습니다.
영어문서에는 start가 0보다 작을 경우~ 이런식으로 작성되어있습니다.

3) end도 target으로 작성되어있는 곳이 있습니다.

### 어떻게 고쳐져야 하나요?

1) 정수 변환 후 target이 start 보다 뒤에 위치하면, array.length의 끝부분까지만 복사가 수행됩니다(즉, copyWithin()은 배열을 확장하지 않습니다).

2) target -> start로 변경되어야 합니다.

3) target -> end로 변경되어야 합니다.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ko/web/javascript/reference/global_objects/array/copywithin`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/javascript/reference/global_objects/array/copywithin/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1b881e4f5668bffe5c45b2bc12bebc9ed6cb7b76
* Document last modified: 2023-09-09T04:34:52.000Z

</details>

**Comment by rami0617** [comment]
영어문서
<img width="831" alt="image" src="https://github.com/user-attachments/assets/7c90e115-96ac-42bd-87df-64947e2f6c16">

한글문서
<img width="831" alt="image" src="https://github.com/user-attachments/assets/58e4c3f3-4a44-4928-88d0-c7b1f4040c83">

**Comment by wisedog** [comment]
@rami0617 이슈 제기 감사합니다! 

안그래도 해당 이슈 발견해서 #22447  에서 리뷰 대기 중입니다. 괜찮으시다면 해당 😊PR에서 잘못된 점 한 번 살펴봐주시면 어떨까요?

**Comment by wisedog** [comment]
아니면 개발자이시니 직접 PR을 날려보는 것도 큰 경험이 됩니다. PR 잘못 올리셔도 친절히 알려드리니 겁내지마시고 PR 주시면 좋겠습니다. : >
(잠수만 타지 않으시면 됩니다 🥲)

**Comment by rami0617** [comment]
@wisedog 네! 감사합니다!
직접 pr을 날린다는 말씀은 제가 직접 pr을 올려봐도 된다는 말씀이실까요?

**Comment by wisedog** [comment]
그렇습니다. 특히 JavaScript - Statement, Expression 중에서 해석 안된 부분이 많고 CSS, HTML, HTTP 도 마찬가지입니다.
지금 올린 이슈 외 다른 문제가 있으면 언제든지 수정 PR 주시기 바랍니다. 어떤걸 해야할지 모른다면, 다시 말씀주시면 몇 개 추천해드리겠습니다. 

혹시 제가 언급한 PR에 @rami0617 님이 언급한 이슈가 다 해결했을까요?

**Comment by rami0617** [comment]
@wisedog 얘기해주신 pr(https://github.com/mdn/translated-content/pull/22447) 확인했고, 적절하게 수정된 것으로 보입니다.

혹시 추천해 주실 수 있으실까요? 추천해주신다면 시간이 나는대로 pr올려보도록 하겠습니다.

**Comment by wisedog** [comment]
몇 가지 추천드립니다. 제가 프론트엔드쪽 지식이 없어, CSS쪽은 잘 몰라서 JavaScript 쪽만 추천드립니다. 또한 개발자들이 자주 사용하는 메서드는 상대적으로 내용이 긴 편이라서, 좀 짧은 것 위주로 찾아봅니다. 상대적으로 중요도는 덜하지만 번역은 수월하리라 생각합니다.

- [`delete` 연산자](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete): 신규 번역. 조금 길긴 하지만 내용이 어렵지는 않습니다.
- String.prototype.padEnd() : 짧은 편입니다. 기존 문서가 있지만 너무 오래 돼서 싹 다 지우고 다시 번역하시는 걸 추천드립니다. 
- Math.sign(), Math.tan(): 짧은 편입니다. 기존 문서가 있지만 너무 오래 돼서 싹 다 지우고 다시 번역하시는 걸 추천드립니다. 
- String.prototype.repeat(): 짧은 편입니다. 기존 문서가 있지만 너무 오래 돼서 싹 다 지우고 다시 번역하시는 걸 추천드립니다. 

1개의 연산자와 3개의 전역 객체를 추천해드렸습니다. 

그 외에 [연산자](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators)로는 Bitwise_OR, Bitwise_XOR, import 등이 번역이 안되있으면서 그 외에 많은 수가 현재 en-US의 최신에 못따라가고 있어서 마음에 드시는거 붙잡고 하셔도 좋겠습니다. ㅎㅎ 

@rami0617

**Comment by rami0617** [comment]
추천해주셔서 감사합니다.

하나씩 작업하여 pr 올려보도록 하겠습니다. 감사합니다!

**Comment by wisedog** [comment]
넵 궁금한거 있으면 언제든지 물어보시기 바랍니다. 여기든 제 메일이든 괜찮습니다. 

해당 이슈는 닫도록 하겠습니다. 감사합니다.
