### ISSUE TITLE
zh-cn: 点号表示法 数字字面量使用方法示例, 同步英文文档

### ISSUE THREAD

**Issue by codelo-99** [mdn/translated-content#22641]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Property_accessors

### 与此议题相关的小节或标题？

点号表示法 数字字面量使用方法示例

### 哪些信息是错误、无用或不完善的？

以下是中文文档中的内容, 前4个例子是重复的, 且第5个例子与英文文档不一致.
```js
(77).toExponential();
// 或
(77).toExponential();
// 或
(77).toExponential();
// 或
(77).toExponential();
// 或
(77.0).toExponential();
// 因为 77. === 77.0，没有歧义（no ambiguity）
```

### 你期望看到什么？

我期望看到与英文文档一致的例子
```js
77 .toExponential();
// or
77
.toExponential();
// or
(77).toExponential();
// or
77..toExponential();
// or
77.0.toExponential();
// because 77. === 77.0, no ambiguity
```

### 你有什么支持的链接、参考或引用？

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Property_accessors#dot_notation

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/operators/property_accessors`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Property_accessors
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/operators/property_accessors/index.md
* Last commit: https://github.com/mdn/translated-content/commit/a4e5c12ef1d642a6d91639580432f308f70e489a
* Document last modified: 2023-07-29T11:36:24.000Z

</details>

**Comment by yin1999** [comment]
Fixed in #22642
