### ISSUE TITLE
Added explanation of `touchcancel` to "TouchEvent: changedTouches"

### ISSUE THREAD

**Issue by AXT-AyaKoto** [mdn/translated-content#22718]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/changedTouches

### What information was incorrect, unhelpful, or incomplete?

For the [touchend](https://developer.mozilla.org/en-US/docs/Web/API/Element/touchend_event) event, it is a list of the touch points that have been removed from the surface (that is, the set of touch points corresponding to fingers no longer touching the surface).

### What did you expect to see?

For the [touchend](https://developer.mozilla.org/en-US/docs/Web/API/Element/touchend_event) **and [touchcancel](https://developer.mozilla.org/en-US/docs/Web/API/Element/touchcancel_event) events**, it is a list of the touch points that have been removed from the surface (that is, the set of touch points corresponding to fingers no longer touching the surface).

### Do you have any supporting links, references, or citations?

https://w3c.github.io/touch-events/#dom-touchevent-changedtouches

**Comment by AXT-AyaKoto** [comment]
I tried. Is this correct?
https://github.com/mdn/content/issues/35194

**Comment by yin1999** [comment]
Correct. Next time, you'd better to click the link at the bottom of the page:

![image](https://github.com/user-attachments/assets/e28e819d-cdf5-46a5-a4bf-ab633b4318f4)

I'm going to close this issue.
