### ISSUE TITLE
翻译不准确,"注释"翻译为"笔记"更好

### ISSUE THREAD

**Issue by thinkerhui** [mdn/translated-content#22799]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

### 与此议题相关的小节或标题？

存储复杂数据 — IndexedDB

### 哪些信息是错误、无用或不完善的？

2、浏览这些文件。你将看到 HTML 非常简单：具有页眉和页脚的网站，以及包含显示注释的位置的主内容区域，以及用于在数据库中输入新注释的表单。CSS 提供了一些简单的样式，使其更清晰。JavaScript 文件包含五个声明的常量，其中包含对将显示注释的 [<ul>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/ul) 元素的引用，标题和正文 [<input>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/input) 元素，[<form>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/form)本身，以及[<button>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/button)。

### 你期望看到什么？

上面这段话的“注释”应该翻译为“笔记”。
其实现在大模型翻译的效果已经比较好了，我尝试把这段话的英文原文给大模型能够得到恰当的翻译。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/javascript/client-side_web_apis/client-side_storage`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/client-side_web_apis/client-side_storage/index.md
* Last commit: https://github.com/mdn/translated-content/commit/6ec5a237611743b565003deb101b9edcb2f3135e
* Document last modified: 2024-07-27T03:21:20.000Z

</details>

**Comment by yin1999** [comment]
目前，该文档的“机翻味儿”太重了。现有的 PR 仅针对当前议题中提及的问题进行了更新。后面还需要有人对文档进行完整的更新 :)
