### ISSUE TITLE
[fr] Syntax typo ?

### ISSUE THREAD

**Issue by fredmelka** [mdn/translated-content#22831]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct

### Sur quelle section/titre porte ce problème ?

Syntax

### Quelle information était incorrecte, inutile ou incomplète ?

Reflect.construct(cible, listeArguments[, newCible]) ==> Syntax has a typo with array brackets!

### Que vous attendiez-vous à voir ?

Reflect.construct(cible, listeArguments [], newCible)

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/reflect/construct`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Reflect/construct
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/reflect/construct/index.md
* Last commit: https://github.com/mdn/translated-content/commit/52deaed202f45ae90108b9bd2e050084e2cd7179
* Document last modified: 2023-08-03T22:25:27.000Z

</details>

**Comment by ratala321** [comment]
The squared brackets are used to indicate that `newCible` is an optional parameter.
In the English version of the docs, there are no squared brackets : `Reflect.construct(target, argumentsList, newTarget)`.

**Comment by fredmelka** [comment]
Brackets mean optional argument for the french translation, alright. Many thanks for prompt reply.

**Comment by SphinxKnight** [comment]
Thanks for the report @fredmelka, I've finally pushed https://github.com/mdn/translated-content/pull/23985 to align with the English version which get rid of the somehow implicit notation for optional parameters.

If you have any feedback on the PR, please join :)
