### ISSUE TITLE
[NEW FEATURE] Add script to support auto translate some fixed content

### ISSUE THREAD

**Issue by fuchunhui** [mdn/translated-content#22834]
As everyone knows, the translation work of the MDN open source community is done by volunteers, a very time-consuming work. In order to improve the translation efficiency, we can use some tools to assist the translation work.

## Practice sharing
At the beginning of the translation process, I can only complete the translation of a single file at one time. As I become familiar with the process, I can batch process some files, but I find it a painful thing.

When operating a single file, first process the header content, then the body title, and finally the body content.

When operating multiple files, I need to open multiple files, then process them one by one. Later, I thought of using the folder search and replace function by `vscode`, update and replace the keywords.

When the next batch translation, I need to search and replace in batch through `shift + command + f`, case by case processing, unfortunately, there will still be omissions.

| files | ## Specifications  | ## Browser compatibility |
| :----: | :----: | :----: |
| ![screenshot_166](https://github.com/user-attachments/assets/f1eff700-e05c-4486-aac2-ad6ed005f4fe) | ![screenshot_167](https://github.com/user-attachments/assets/28aa3f15-1d97-4830-ae23-24c42bda2022) | ![screenshot_168](https://github.com/user-attachments/assets/4bd2b2c1-796b-439e-814c-57a7f6982b9f) |

I don't want to spend time doing these repetitive things anymore, I want a better way.

## Any better way? 

Perhaps scripts can be used to solve this problem.

This script will not solve all the problems, it currently has the ability to cover:
- Handler header information, delete invalid content, replace the `title` with translation.
- Keep `slug` and `title`, create `l10n` content template.
- Process the body title, replace the title.
- Process the link, replace the link.

| before command | example one  | example two |
| :----: | :----: | :----: |
| ![screenshot_169](https://github.com/user-attachments/assets/35f400e2-7e6f-41b2-b5a0-4997e3180f56) | ![screenshot_170](https://github.com/user-attachments/assets/b33ae46a-b919-47d8-9959-46c065763996) | ![screenshot_171](https://github.com/user-attachments/assets/57699bf2-9971-4bd1-aca5-983d8147671a) |

## How to use the script

![image](https://github.com/user-attachments/assets/cfb0e045-0a03-4b93-a3da-57ea943f86f5)

```
npm run auto:translate file-path
```
The principle is very simple, it scan the directory content, match through regular expressions, and replace the fixed content.

## The advantages of the script

- No language restrictions, the configuration content can be customized.
- Focus on the core content, reduce repetitive labor.

**Comment by PassionPenguin** [comment]
any link or detailed code to the script you created?

but indeed, *translating the title **could** be the easiest things over the whole file*, so...This could be useful, but the _efforts to maintain_ such a script may not be worthy enough.

**Comment by fuchunhui** [comment]
> any link or detailed code to the script you created?
> 
> but indeed, _translating the title **could** be the easiest things over the whole file_, so...This could be useful, but the _efforts to maintain_ such a script may not be worthy enough.

Thanks for your attention. yes, I will submit the code later, so that we can understand it better.

Precisely because this is the simplest content, I chose to start from here, first solve the basic problems, and ensure that the translation process is always correct. And the content is the most important part, the quality of machine-translated content is quite good, but most of it still has a lot of room for improvement, the calibration process is also a time-consuming thing. Here I am very grateful and admire the persons who often code review. their workload is very large.

As of now, I have used this tool to complete 15 commits, and the experience is very smooth, worth a try.

**Comment by fuchunhui** [comment]
A draft version of the code.

If your fils path is `files/zh-cn/web/api/htmlselectelement`, then you can do like this:
```
node scripts/auto-translate.js files/zh-cn/web/api/htmlselectelement
```

**Comment by yin1999** [comment]
I don't have a clear opinion on introducing this script.

But as @PassionPenguin said, translating headings is the simplest task. We may not need to introduce special tools for this. There are many maintainers of `mdn/content` having their own tools to help themselves maintain the English documents. But they have not introduced these tools into the `mdn/content` repository yet.

I believe people has their own habits of contributing to translated-content. Specific tools may not help most people.

**Comment by fuchunhui** [comment]
> I believe people has their own habits of contributing to translated-content

As you said, I agree with this viewpoint. I will keep the code locally, and if anyone wants to try this, that would be great.
