### ISSUE TITLE
Broken examples in translations of /en-US/docs/MDN/Contribute/Howto/Create_an_interactive_exercise_to_help_learning_the_web

### ISSUE THREAD

**Issue by escattone** [mdn/translated-content#23]
@fiji-flo Discovered the following broken translated content:

https://developer.mozilla.org/en-US/docs/MDN/Contribute/Howto/Create_an_interactive_exercise_to_help_learning_the_web

Switch language (`fr`, `ja`, ...) scroll down to the bottom. The `EmbedDistLiveSample`  live samples are broken (the link to `EmbedDistLiveSample` , too).

**Comment by escattone** [comment]
What a mess, but I don't blame the translations. The way our `EmbedLiveSample` macro works, and the fact that many translations translate the slug, makes for a fragile system. This will be easier to fix once we move to all English slugs, although it may not be worth our time given the un-importance of the page and how much work it will be to fix every locale.

There are several problems here:
1. The `EmbedDistLiveSample` macro was deleted over 3 years ago (sometime in the second half of 2017).
2. The English document needs to be fixed (see https://github.com/mdn/content/pull/1958).
3. The last `EmbedLiveSample` macro call on the `/en-US/docs/MDN/Contribute/Howto/Create_an_interactive_exercise_to_help_learning_the_web` page (and its translations), tries to extract a live sample from the `/{locale}/docs/MDN/Contribute/Howto/Create_an_interactive_exercise_to_help_learning_the_web/distant_example` page, which for most (all?) translations doesn't exist, so that last live sample is broken. The fix is not complicated, but it's not simple either. For each locale, we'd have to copy the `/en-US/docs/MDN/Contribute/Howto/Create_an_interactive_exercise_to_help_learning_the_web/distant_example` page into `/{locale}/docs/MDN/Contribute/Howto/Create_an_interactive_exercise_to_help_learning_the_web/distant_example`. Also, the sentence that contains the link to the `EmbedDistLiveSample` macro will have to be translated to match the new English sentence from https://github.com/mdn/content/pull/1958.

**Comment by escattone** [comment]
@fiji-flo I don't think it's worth fixing the translations of `/en-US/docs/MDN/Contribute/Howto/Create_an_interactive_exercise_to_help_learning_the_web` for now. We should at least wait until we move to all English slugs.

**Comment by escattone** [comment]
@fiji-flo After some further thought, I think we should modify the EmbedLiveSample macro. When it's passed the slug of a different page to extract the live sample from, I think we should first look for that other page in the locale of the current document (as it does now) but if that other page doesn't exist, fall back to using the English version of that other page.

**Comment by escattone** [comment]
@fiji-flo I've created a draft PR that I think would improve these kinds of cases: https://github.com/mdn/yari/pull/2777

**Comment by SphinxKnight** [comment]
@escattone bonjour :) it seems to me the examples are (now) working as intended (I'm not seeing major differences between en-US content and fr/ja/zh-cn on that matter.

Shall we close this one?

**Comment by escattone** [comment]
@SphinxKnight Bonjour! Hope all is well! Let me say again, merci beaucoup for all your generous and excellent work on MDN over the years! You're right on, let's close this one.
