### ISSUE TITLE
Issue with "Введение в web APIs": Broken links

### ISSUE THREAD

**Issue by IcEWaRRiOr01** [mdn/translated-content#2306]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/Client-side_web_APIs/Introduction

Broken links in russian language on Client-side_web_APIs/Introduction page

In the topic "Как работает API?"

#### What did you expect to see?
Expected: links "maps-example.html" and (see it live also) are on the page. Actually: links lead to Page 404 (Not Found)

![maps-example-link](https://user-images.githubusercontent.com/73989561/131951055-47268a2d-af77-40d0-889f-c97fa1f5149c.png)

![live-maps-example-link](https://user-images.githubusercontent.com/73989561/131951106-b212c951-ec0f-4a7a-bbde-5cbe0a53c062.png)

![page-maps-example](https://user-images.githubusercontent.com/73989561/131951358-fa438c44-2e48-42ce-95d2-a68f8b0cc83a.png)

![live-page-maps-example](https://user-images.githubusercontent.com/73989561/131951396-b4ab4882-6a5a-4124-84d0-407379dcb7bb.png)

#### Did you test this? If so, how?

Links lead to Page 404 (Not Found)
Screenshots attached above

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/learn/javascript/client-side_web_apis/introduction`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/Client-side_web_APIs/Introduction
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/javascript/client-side_web_apis/introduction/index.html
* Last commit: https://github.com/mdn/translated-content/commit/dda635dd6182e36ba9ac07810014cf15cf47e50a
* Document last modified: 2021-09-02T00:46:31.000Z

</details>

**Comment by sashasushko** [comment]
Дело в том, что в англоязычной версии заменили пример с API геолокации на пример с API аудиоконтента. Когда актуализируем перевод эта проблема уйдёт.
