### ISSUE TITLE
Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox_basics_fix

### ISSUE THREAD

**Issue by PJW980921** [mdn/translated-content#23077]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox

### 이 문제에 관한 특정 섹션 또는 제목은 무엇인가요?

Basic_concepts_of_flexbox basics.png 엑박 문제

### 어떤 정보가 부정확하거나 도움이 되지 않거나 불완전했나요?

ko, fr, pt-br, ru/docs/Web/CSS/CSS_flexible_box_layout/Basic_concepts_of_flexbox  에 basics 이미지들 확장자가 png로 되어있어서 그런지 엑박인 상태로 화면에 보여집니다. 

<img width="478" alt="스크린샷 2024-08-15 오후 7 07 16" src="https://github.com/user-attachments/assets/1c2bdbed-7c5d-40b8-b27e-5b991f98b6dc">

### 어떻게 고쳐져야 하나요?

basics.png 확장자를 svg로 변경했습니다.

### 지원 링크, 참조 또는 인용구가 있으신가요?

없습니다.

### 더 공유하고 싶은게 있으신가요?

없습니다.

**Comment by leon-win** [comment]
Was fixed in #23078 :heavy_check_mark:
