### ISSUE TITLE
[zh-cn]: 参考链接无法跳转到正确的小节

### ISSUE THREAD

**Issue by xionkq** [mdn/translated-content#23203]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/setInterval

### 与此议题相关的小节或标题？

#延迟限制

### 哪些信息是错误、无用或不完善的？

此处的链接无法跳转到正确的小节
![image](https://github.com/user-attachments/assets/b2dc246c-a023-48f2-8949-64f27b706a0b)

### 你期望看到什么？

实际上应该为此链接
![image](https://github.com/user-attachments/assets/f47b6435-7fc4-41e8-9249-d59f3044bbe1)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/setinterval`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/setInterval
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/setinterval/index.md
* Last commit: https://github.com/mdn/translated-content/commit/2dabca915c30b9412fdc83854597df387ad36eda
* Document last modified: 2024-07-28T01:05:09.000Z

</details>

**Comment by khan11291** [comment]
786
