### ISSUE TITLE
Разные ссылки в статье

### ISSUE THREAD

**Issue by device0117** [mdn/translated-content#23268]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/HTML/Tables/Advanced

### О какой части статьи или абзаце идёт речь?

Упражнение: Добавление заголовка

### Какая информация оказалась неверной, бесполезной или неполной?

Под разделом [Упражнение: Добавление заголовка](https://developer.mozilla.org/ru/docs/Learn/HTML/Tables/Advanced#%D1%83%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%B0%D0%B3%D0%BE%D0%BB%D0%BE%D0%B2%D0%BA%D0%B0), есть абзац с примечанием, в котором есть ссылка на пример разметки таблицы в GitHub и на его "живой пример" - таблицы разные (разметка на GitHub - разметка школьного расписания учителя, а вот "живой пример" совсем другой таблицы.

### Как бы вы исправили?

Предлагаю для "живого примера" вставить ссылку именно таблицы школьного расписания учителя, так как ссылка на разметку, ведет на таблицу школьного расписания, а "живой пример" - нет. Это не сильно критично, но сбивает с толку читателя, так по смыслу контекста, ожидалась ссылка на "живой пример" таблицы школьного расписания учителя.

### Есть ли у вас какие-либо подтверждающие ссылки?

Разметка: https://github.com/mdn/learning-area/blob/main/html/tables/advanced/timetable-caption.html
"Живой пример": https://mdn.github.io/learning-area/html/tables/advanced/spending-record-finished.html

### Хотите добавить что-то ещё?

Вставил скрин
![Снимок экрана 2024-08-26 225611](https://github.com/user-attachments/assets/c2f0d942-87ff-4e9c-99ef-2d510ad157bf)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/html/tables/advanced`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/HTML/Tables/Advanced
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/html/tables/advanced/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c442fded8d5d9f2612160711e6432d493e43618f
* Document last modified: 2024-07-28T20:55:04.000Z

</details>

**Comment by leon-win** [comment]
Привет, @device0117 !

Спасибо за хорошее замечание! :+1: 

Я сделал исправление, #23270 (+ исправил некоторые другие ссылки). После того, как этот PR будет влит, изменения появятся на сайте MDN :ok_hand:
