### ISSUE TITLE
关键渲染路径章节的翻译错误

### ISSUE THREAD

**Issue by MusherM** [mdn/translated-content#23319]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/Performance/Critical_rendering_path

### 与此议题相关的小节或标题？

关键渲染路径

### 哪些信息是错误、无用或不完善的？

在解析 HTML 时会创建文档对象模型。HTML 可以请求 JavaScript，而 JavaScript 反过来，又可以更改 DOM。HTML 包含或请求样式，**依次**来构建 CSS 对象模型。浏览器引擎将两者结合起来以创建渲染树。布局确定页面上所有内容的大小和位置。确定布局后，将像素绘制到屏幕上。

### 你期望看到什么？

在解析 HTML 时会创建文档对象模型。HTML 可以请求 JavaScript，而 JavaScript 反过来，又可以更改 DOM。HTML 包含或请求样式，**以此**来构建 CSS 对象模型。浏览器引擎将两者结合起来以创建渲染树。布局确定页面上所有内容的大小和位置。确定布局后，将像素绘制到屏幕上。

### 你有什么支持的链接、参考或引用？

in turn，应该翻译为“以此”，这里应该是敲错了

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/performance/critical_rendering_path`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Performance/Critical_rendering_path
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/performance/critical_rendering_path/index.md
* Last commit: https://github.com/mdn/translated-content/commit/e005be662421aee99588a6134318f2a1fee7d549
* Document last modified: 2024-06-06T12:39:52.000Z

</details>

**Comment by yin1999** [comment]
这里的连接词为“which in turn”，意味“这反过来”（而非以此/依次）。

**Comment by PassionPenguin** [comment]
> 这里的连接词为“which in turn”，意味“这反过来”（而非以此/依次）。

“进而”、“而这又”
