### ISSUE TITLE
We want to know why marquee is obsolete deprecated and so on. Why is there no alternatives ? Some specific use cases like a music player might need it.

### ISSUE THREAD

**Issue by antoninadert** [mdn/translated-content#23330]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/HTML/Element/marquee

### Sur quelle section/titre porte ce problème ?

Deprecation

### Quelle information était incorrecte, inutile ou incomplète ?

We don't know why it was deprecated and left without any viable alternative. 

### Que vous attendiez-vous à voir ?

I want to know why it is deprecated and if so, what is the most viable alternative.

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/html/element/marquee`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/marquee
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/html/element/marquee/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b0cdd99f96eb0de66e0ff5b3bb2751a2fa2f6e30
* Document last modified: 2023-11-16T10:14:03.000Z

</details>

**Comment by yin1999** [comment]
Hey @antoninadert. I'm going to close this issue as the question has been answered. If you have any other questions, welcome to [ask for help in Communication channels](https://developer.mozilla.org/docs/MDN/Community/Communication_channels).
