### ISSUE TITLE
翻译为“静默逃逸的NaN值“更为贴切

### ISSUE THREAD

**Issue by MerielVaren** [mdn/translated-content#23444]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/NaN

### 与此议题相关的小节或标题？

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/NaN#silently_escaping_nan

### 哪些信息是错误、无用或不完善的？

简体中文标题的翻译“默默逃离NaN”，英译为escape from NaN silently，与实际要表达的原意"Silently escaping NaN"有很大出入，不便于简中读者理解

### 你期望看到什么？

建议修改为"静默逃逸的NaN值"，这与正文实际内容所表达的意思更为贴切

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/nan`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/NaN
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/nan/index.md
* Last commit: https://github.com/mdn/translated-content/commit/bff0d2bf12b7cafc4d2bfb9eb0b759419f660324
* Document last modified: 2023-11-30T01:14:28.000Z

</details>

**Comment by khan11291** [comment]
# A first-level heading
## A second-level heading
### A third-level heading

**Comment by khan11291** [comment]
# A first-level heading
## A second-level heading
### A third-level heading
#
### @
