### ISSUE TITLE
关于 box-sizing 的文章中的译者注颇具误导性

### ISSUE THREAD

**Issue by YiQuSi** [mdn/translated-content#23489]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-sizing

### 与此议题相关的小节或标题？

尝试一下

### 哪些信息是错误、无用或不完善的？

> <strong>译者注：</strong> <code>border-box</code>不包含<code>margin</code>

对于初学者而言，这样的说法可能会让他们误以为 margin 属性对 border-box 不可用

### 你期望看到什么？

删除译者注，或者让其更完善

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/box-sizing`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/box-sizing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/box-sizing/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b726c693552541650226d1b42f3fe585d0c057be
* Document last modified: 2024-07-28T11:41:21.000Z

</details>

**Comment by yin1999** [comment]
“译者注”是 wiki 时代的产物（当时并没有审核机制），现在我们并不建议贡献者在内容中添加“译者注”，对于英文表述不清晰的内容，应首先更新英文文档。

对于当前文档的问题，直接移除“译者注”的内容即可。
