### ISSUE TITLE
HTMLElement.click() 页面不正确

### ISSUE THREAD

**Issue by minecraftfen** [mdn/translated-content#23602]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/click

### 与此议题相关的小节或标题？

HTMLElement.click()

### 哪些信息是错误、无用或不完善的？

HTMLElement构造器上不存在click方法，英文内容中使用了HTMLElement: click() Method作为标题，不太明显，但确实表示了这是一个实例方法，但中文内容里使用的这种标题容易让人误以为这是一个静态方法，即直接作为HTMLElement构造器的属性存在的方法。

### 你期望看到什么？

建议使用和英文内容类似的方式，或者直接使用HTMLElement.prototype.click()作为标题。

### 你还想补充什么内容？

![image](https://github.com/user-attachments/assets/2599fbde-62da-4dfc-b50a-a6b21c7f3520)
HTMLElement.click的值未定义，而HTMLElement.prototype.click的值是一个内建方法。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/htmlelement/click`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement/click
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/htmlelement/click/index.md
* Last commit: https://github.com/mdn/translated-content/commit/2d279a6eeea344d0f9ab61adc4d71efb68066f22
* Document last modified: 2023-07-29T05:47:44.000Z

</details>

**Comment by yin1999** [comment]
按照 MDN 现在的规则，如果一个方法为静态方法，那么我们将在标题中使用类似这样的写法：“Notification：requestPermission() 静态方法”，如果为实例方法，我们会使用类似这样的写法：“HTMLElement：click() 方法”。即，如果没有强调“静态”两字，即为实例方法。目前的标题确实可以更新（使用最新的英文文档的格式），但本身的表达也是没有问题的。

**Comment by familyboat** [comment]
> 按照 MDN 现在的规则，如果一个方法为静态方法，那么我们将在标题中使用类似这样的写法：“Notification：requestPermission() 静态方法”，如果为实例方法，我们会使用类似这样的写法：“HTMLElement：click() 方法”。即，如果没有强调“静态”两字，即为实例方法。目前的标题确实可以更新（使用最新的英文文档的格式），但本身的表达也是没有问题的。

你说的没问题的表达用的是冒号，但现在的文档上用的是小数点。按照你的说法是需要更新的。

**Comment by yin1999** [comment]
> > 按照 MDN 现在的规则，如果一个方法为静态方法，那么我们将在标题中使用类似这样的写法：“Notification：requestPermission() 静态方法”，如果为实例方法，我们会使用类似这样的写法：“HTMLElement：click() 方法”。即，如果没有强调“静态”两字，即为实例方法。目前的标题确实可以更新（使用最新的英文文档的格式），但本身的表达也是没有问题的。
> 
> 你说的没问题的表达用的是冒号，但现在的文档上用的是小数点。按照你的说法是需要更新的。

我知道，我在我提的 PR 中已经更新了这一点，我表达的是，这本身并不是错误，而是容易引起混淆。可以参考我们之前的讨论：https://github.com/orgs/mdn/discussions/248

**Comment by familyboat** [comment]
我对照了`HTMLElement`的中英版的相关内容：https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement 和 https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLElement ，在一些术语上已经有了截然不同的表达。看英文版我不会觉得`HTMLElement.click()`表达的是实例方法有什么问题，因为在 https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement 已经用`instance method`表达了这一层含义，但中文版的没有相关的表达，这会更容易产生误解。我建议中文版的内容应该跟上英文版的内容。

**Comment by familyboat** [comment]
补充的一点：`HTMLElement.click`表达实例方法是可以接受的，只需要明确的表明是实例方法而不是静态方法。因为，你无法用`htmlElement.click`这种形式去表达一个实例方法，除非人为的将`htmlElement`和`HTMLElement`关联起来或者以其他方式关联起来。

**Comment by familyboat** [comment]
> 按照 MDN 现在的规则，如果一个方法为静态方法，那么我们将在标题中使用类似这样的写法：“Notification：requestPermission() 静态方法”，如果为实例方法，我们会使用类似这样的写法：“HTMLElement：click() 方法”。即，如果没有强调“静态”两字，即为实例方法。目前的标题确实可以更新（使用最新的英文文档的格式），但本身的表达也是没有问题的。

所以，我也赞同你这里的说法。

**Comment by yin1999** [comment]
> 目前的中文页面使用的是`HTMLElement.click()`作为标题，按照你说的方法的话，应该把`HTMLElement：click() 方法`对吧？

是的，我已经提了[修复的 PR](https://github.com/mdn/translated-content/pull/23634)，这里的有些讨论偏离了主题（请忽略）。后面我们会规划更新所有相关的标题。
