### ISSUE TITLE
Не отображается верхний и нижний индекс в примерах

### ISSUE THREAD

**Issue by xix0one** [mdn/translated-content#23739]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

### О какой части статьи или абзаце идёт речь?

Верхний и нижний индекс

### Какая информация оказалась неверной, бесполезной или неполной?

Что-то мне подсказывает, что результат должен выглядеть иначе:
![Снимок](https://github.com/user-attachments/assets/2e078421-213b-4ae7-9982-d2534225a2a5)

### Как бы вы исправили?

<p>Я просыпаюсь в 6<sup>35</sup> часов утра.</p>
<p>
  Химическая формула кофеина:
  C<sub>8</sub>H<sub>10</sub>N<sub>4</sub>O<sub>2</sub>.
</p>
<p>Если x<sup>2</sup> равно 9, x должен равняться 3 или -3.</p>

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/html/introduction_to_html/advanced_text_formatting/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c442fded8d5d9f2612160711e6432d493e43618f
* Document last modified: 2024-07-28T20:55:04.000Z

</details>

**Comment by leon-win** [comment]
Привет, @xix0one !

Спасибо за внимательность и указание на проблему в переводе и разметке этой странице!

Я обновил перевод страницы в #24296

**Comment by leon-win** [comment]
Задача закрылась бы автоатически после влитя PR))

Но он ещё не влит, подождём пока, чтобы кто-нибудь ещё посмотрел)
