### ISSUE TITLE
In the french translation, Array.prototype.group is still displayed instead of Object.groupBy

### ISSUE THREAD

**Issue by julienw** [mdn/translated-content#23755]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy

### Sur quelle section/titre porte ce problème ?

All

### Quelle information était incorrecte, inutile ou incomplète ?

The function got renamed in browsers, so the information is now deeply inaccurate.

### Que vous attendiez-vous à voir ?

The right name of function.

### Avez-vous des liens, références ou citations sur ce sujet ?

See the same page in english.

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/object/groupby`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Object/groupBy
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/object/groupby/index.md
* Last commit: https://github.com/mdn/translated-content/commit/53b2624681b9871b27425718a334f9144f3011fb
* Document last modified: 2024-08-08T12:12:16.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci du signalement @julienw :)
