### ISSUE TITLE
Content bug: Redirection to bitcoin website

### ISSUE THREAD

**Issue by hyptos** [mdn/translated-content#2377]
## What page(s) did you find the problem on?

https://developer.mozilla.org/fr/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

## Specific page section or heading?

![image](https://user-images.githubusercontent.com/1622722/132317742-5da8e3e2-041c-46e3-9fa3-d7920608b8bf.png)

## What is the problem?

There is a redirection to bitcoin website.

## What did you expect to see?

Maybe we should remove those ?

## Did you test this? If so, how?

With Firefox on ubuntu on the french version.

**Comment by SphinxKnight** [comment]
@hyptos Merci beaucoup pour ce retour et l'analyse détaillée. je m'en occupe immédiatement (il pourra y avoir un délai entre la PR et le déploiement), j'en profiterai pour retirer les éventuels autres liens vers ce(s) domaine(s)

**Comment by hyptos** [comment]
pas de soucis, merci pour ton travail :)
