### ISSUE TITLE
a link herf error

### ISSUE THREAD

**Issue by suwu369** [mdn/translated-content#23835]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/Express_Nodejs/development_environment

### 哪些信息是错误、无用或不完善的？

![image](https://github.com/user-attachments/assets/dbdd2623-0b5c-4dd1-aa56-46206223f687)

### 你期望看到什么？

a链接指向正确

### 你有什么支持的链接、参考或引用？

https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/Express_Nodejs/development_environment

### 你还想补充什么内容？

![image](https://github.com/user-attachments/assets/7831af4d-233b-45d8-ab45-740d79b8187c)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/server-side/express_nodejs/development_environment`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/Express_Nodejs/development_environment
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/server-side/express_nodejs/development_environment/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c242b0f6a019ff4cc8489dabdddd46b1d9149983
* Document last modified: 2024-09-07T05:41:08.000Z

</details>

**Comment by yin1999** [comment]
应该改成

```md
`http://127.0.0.1:3000`
```
