### ISSUE TITLE
Issue with "WeakMap": (内容未渲染)

### ISSUE THREAD

**Issue by 314857493** [mdn/translated-content#2392]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakMap

#### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/34772902/132436006-c31e0aac-bae8-4c7e-adcf-34a1ec303844.png)

#### Specific section or headline?

属性 方法

#### What did you expect to see?

未正确展示内容

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/weakmap`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakMap
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/weakmap/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ad9ea64ce997fb0bf4e8bef04605ec4b1cff1147
* Document last modified: 2021-09-06T15:43:38.000Z

</details>

**Comment by yin1999** [comment]
@SphinxKnight This issue has been fixed in pr #3553
