### ISSUE TITLE
Issue with "Utiliser une cartographie de code source": Missing space

### ISSUE THREAD

**Issue by ivellios-meliamne** [mdn/translated-content#2395]
MDN URL: https://developer.mozilla.org/fr/docs/Tools/Debugger/How_to/Use_a_source_map

#### What information was incorrect, unhelpful, or incomplete?
A space is missing after the start comment :  
`//# sourceMappingURL=main.js.map` => `// # sourceMappingURL=main.js.map`

#### Specific section or headline?
Code example

#### What did you expect to see?
`// # sourceMappingURL=main.js.map` or `/* # sourceMappingURL=main.js.map */`

#### Did you test this? If so, how?
Yes with a Firefox browser in the css file => no more error in the console

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/tools/debugger/how_to/use_a_source_map`
* MDN URL: https://developer.mozilla.org/fr/docs/Tools/Debugger/How_to/Use_a_source_map
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/tools/debugger/how_to/use_a_source_map/index.html
* Last commit: https://github.com/mdn/translated-content/commit/09972c2ea21cefc72017cf98554bbb82dd2edf58
* Document last modified: 2021-09-07T13:50:36.000Z

</details>

**Comment by SphinxKnight** [comment]
@ivellios-meliamne, en reprenant l'exemple de la page sur https://mdn.github.io/devtools-examples/sourcemaps-in-console/index.html, je n'ai pas de problème pour reproduire.
Je ne vois pas non plus d'erreur dans la console pour l'article.

Pouvez-vous nous fournir plus d'informations s'il vous plaît ?

**Comment by ivellios-meliamne** [comment]
Bonjour,

Je n'ai pas été assez précis, l'erreur se produit dans les fichiers css

avec par exemple un fichier `style.min.css` et un `fichier style.css`  
dans lequel je rajoute : `//# sourceMappingURL=style.css` => ça ne fonctionne pas  
mais si je met un espace : `// # sourceMappingURL=style.css` => le fichier source est reconnu  
j'obtient la même chose en utilisant le commentaire multiligne : `/*# sourceMappingURL=style.css */`

Merci.

**Comment by SphinxKnight** [comment]
Sorry for the very late reply.
@ivellios-meliamne `//` should not be used to write comment in CSS. Only `/* ... */` is recognized by standards.

- https://developer.mozilla.org/fr/docs/Web/CSS/Comments
- https://drafts.csswg.org/css2/#comments%E2%91%A0
- https://twitter.com/DasSurma/status/1462735743399432204

I'll open a PR in mdn/content as well as in this repository to add some more details regarding the "CSS case" in this article (at the moment, it implicitly is JS-oriented).

**Comment by FredericFremat** [comment]
Hello,
The documentation is well done now.
You can close the issue.
Best regards.
