### ISSUE TITLE
Issue with "Array.prototype.reduce()": (unnecessary parentheses)

### ISSUE THREAD

**Issue by renatozr** [mdn/translated-content#2410]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

#### What information was incorrect, unhelpful, or incomplete?
array.reduce(callback( acumulador, valorAtual[, index[, array]] )[, valorInicial]))

#### Specific section or headline?
Sintaxe

#### What did you expect to see?
array.reduce(callback( acumulador, valorAtual[, index[, array]] )[, valorInicial])

#### Did you test this? If so, how?
It makes no difference but it is wrong.

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/javascript/reference/global_objects/array/reduce/index.html
* Last commit: https://github.com/mdn/translated-content/commit/fdc77da2ba02ff78b23fc129ec7ee20c0fa28afb
* Document last modified: 2021-09-09T00:49:39.000Z

</details>

**Comment by josielrocha** [comment]
Fixed in #9221
