### ISSUE TITLE
Issue with "::before (:before)": (short summary here please)

### ISSUE THREAD

**Issue by Hans-Oliveira** [mdn/translated-content#2411]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/::before

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/css/_doublecolon_before`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/::before
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/css/_doublecolon_before/index.html
* Last commit: https://github.com/mdn/translated-content/commit/fdc77da2ba02ff78b23fc129ec7ee20c0fa28afb
* Document last modified: 2021-09-09T00:49:39.000Z

</details>

**Comment by Rumyra** [comment]
Hi @Hans-Oliveira can you provide some information as to the issue on this page please - thank you :)
