### ISSUE TITLE
Promise静态方法中resolve函数命名错误

### ISSUE THREAD

**Issue by 2002XiaoYu** [mdn/translated-content#24165]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve

### What specific section or headline is this issue about?

Promise.resolve描述部分

### What information was incorrect, unhelpful, or incomplete?

在Promise.resolve静态方法的描述中，说明的resolver函数命名错误

### What did you expect to see?

正确命名为resolve函数，多了一个r，这才能够正确对应上跳转界面的内容，将尾部的r删除

### Do you have any supporting links, references, or citations?

错误位置：![image-20241021020650687](https://github.com/user-attachments/assets/9772e551-0709-4ae9-b5e7-91a51f01d7b2)

正确命名：![image-20241021015202239](https://github.com/user-attachments/assets/52e64660-5ab1-4d26-8c9c-11db107ee622)

**Comment by skyclouds2001** [comment]
比较了下英文文档，英文文档是正确的

**Comment by 2002XiaoYu** [comment]
![image](https://github.com/user-attachments/assets/1c988435-6978-4057-a9e3-1415bdd3903e)
在同一页面的最后一个案例中，也存在相应问题(中文简体版本)。(英文文档为正确内容，未存在该问题)
