### ISSUE TITLE
更正小节链接

### ISSUE THREAD

**Issue by appleliushiqiD** [mdn/translated-content#24173]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Styling_tables

### 与此议题相关的小节或标题？

高级区块效果、调试CSS

### 哪些信息是错误、无用或不完善的？

需要更正小节“样式化表格”的“下一页”，小节“调试CSS”的“上一页”跳转链接。

按左侧目录显示，小节“样式化表格”下一页应该跳转至小节“高级区块效果”，并且小节“调试CSS”前一页应跳转至小节“高级区块效果”。

![488e7f70-2d41-49a7-bfc7-8601d54d4c7d](https://github.com/user-attachments/assets/a3dfeb00-1bcf-4e28-980c-46ad916100ad)

### 你期望看到什么？

可以更正小节“样式化表格”的“下一页”与“调试CSS”的“上一页”跳转链接。

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/css/building_blocks/styling_tables`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Styling_tables
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/css/building_blocks/styling_tables/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d1f2add8153e0c0af6149649d90f3562d21a6532
* Document last modified: 2024-01-03T14:20:13.000Z

</details>

**Comment by yin1999** [comment]
下一页的链接应该是 `Learn/CSS/Building_blocks/Advanced_styling_effects`
