### ISSUE TITLE
Issue with "JavaScript 中的继承": incomplete translation

### ISSUE THREAD

**Issue by koushouto** [mdn/translated-content#2418]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Inheritance

#### Specific section or headline?
- [设置 Teacher() 的原型和构造器引用](https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Inheritance#setting_teachers_prototype_and_constructor_reference)
- [ECMAScript 2015 Classes](https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Inheritance#ecmascript_2015_classes)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/learn/javascript/objects/inheritance`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Objects/Inheritance
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/javascript/objects/inheritance/index.html
* Last commit: https://github.com/mdn/translated-content/commit/7b6563499aa6148b859b4ee88a1d3f1751c547ca
* Document last modified: 2021-09-09T12:23:43.000Z

</details>

**Comment by yin1999** [comment]
Fixed in #5756
