### ISSUE TITLE
Typofix needed for Notions de base en HTML

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#24212]
### MDN URL

https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web/HTML_basics

### What specific section or headline is this issue about?

[Images](https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web/HTML_basics#images)

### What information was incorrect, unhelpful, or incomplete?

Spelling error on [line 125, Notions de base en HTML](https://github.com/mdn/translated-content/blob/main/files/fr/learn/getting_started_with_the_web/html_basics/index.md?plain=1#L125): **Comment mentionné auparavant** should be **Comme mentionné auparavant**.

(Reported on Matrix.)

### What did you expect to see?

**Comment mentionné auparavant** should be **Comme mentionné auparavant**.

### Do you have any supporting links, references, or citations?

Reported by a user on Matrix

**Comment by Piyush-r-bhaskar** [comment]
Hi @cw118 

Can you plz assign this to me?

**Comment by cw118** [comment]
> Hi @cw118 
> 
> Can you plz assign this to me?

Hi @Piyush-r-bhaskar, there is already a PR created to fix this, but thank you for your interest!
