### ISSUE TITLE
About "Task queues vs. microtasks"

### ISSUE THREAD

**Issue by 161043261** [mdn/translated-content#24213]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Using_promises

### 与此议题相关的小节或标题？

Task queues vs. microtasks

### 哪些信息是错误、无用或不完善的？

Expected output (just like what is documented):

```text
Promise callback
Promise (pending) Promise {<pending>}
Promise callback (.then)
event-loop cycle: Promise (fulfilled) Promise {<fulfilled>}
```

### 你期望看到什么？

Actual output

```text
Promise callback
Promise (pending) Promise { <pending> }
Promise callback (.then)
event-loop cycle: Promise (fulfilled) Promise { undefined }
```

### 你有什么支持的链接、参考或引用？

Here's my source code

```js
const promise = new Promise((resolve, reject) => {
    console.log("Promise callback");
    resolve();
}).then((result) => {
    console.log("Promise callback (.then)");
});
setTimeout(() => {
    console.log("Event loop: Promise (fulfilled)", promise);
}, 0);
console.log("Promise (pending)", promise);
```

### 你还想补充什么内容？

Sorry, I am a beginner in javascript, please forgive me if there are any low-level mistakes.    :)

Here is my screenshot.
<img width="515" alt="Screenshot" src="https://github.com/user-attachments/assets/eb9cdc5f-7766-4420-88a8-2710950cdc6f">

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/guide/using_promises/index.md
* Last commit: https://github.com/mdn/translated-content/commit/9ce80bfea141b0a765556e9a825599b0505db2ee
* Document last modified: 2024-10-08T11:46:54.000Z

</details>

**Comment by yin1999** [comment]
Node.js 运行时的输出可能会与 Chromium 的 V8 引擎的输出有一些小的偏差，以下是我使用浏览器的控制台所输出的内容（与文档中的类似）：

![image](https://github.com/user-attachments/assets/3d3f0281-2b41-4fb3-bbb4-ba6155b70f92)

但其实文档中所展示的输出更多的是要去展示这些部分被调用的顺序，而不是实际输出的对象都是如何去“字符串化”的（如果没有明确的现行标准，字符串化的形式将完全取决于运行时环境）。

我将关闭这个议题，如有疑问可以继续在这里添加评论。

**Comment by 161043261** [comment]
> Node.js 运行时的输出可能会与 Chromium 的 V8 引擎的输出有一些小的偏差，以下是我使用浏览器的控制台所输出的内容（与文档中的类似）：
> 
> ![image](https://private-user-images.githubusercontent.com/15844309/379977173-3d3f0281-2b41-4fb3-bbb4-ba6155b70f92.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NTQ5OTAsIm5iZiI6MTcyOTg1NDY5MCwicGF0aCI6Ii8xNTg0NDMwOS8zNzk5NzcxNzMtM2QzZjAyODEtMmI0MS00ZmIzLWJiYjQtYmE2MTU1YjcwZjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI1VDExMTEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3OTk3NWJmODQyYTlmNTVhYzQ5OTljM2ZiMjgxNjNlMjZmODc1MDU5ODU1MWZjOTJjMGY3ZDQ4ZjJiNTllMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OrQJTl-2KSoTpUEHgWq5fBzx6yh_sr4v7cB0bF1vrPk)
> 
> 但其实文档中所展示的输出更多的是要去展示这些部分被调用的顺序，而不是实际输出的对象都是如何去“字符串化”的（如果没有明确的现行标准，字符串化的形式将完全取决于运行时环境）。
> 
> 我将关闭这个议题，如有疑问可以继续在这里添加评论。

衷心感谢!
