### ISSUE TITLE
404

### ISSUE THREAD

**Issue by Riribouldingue** [mdn/translated-content#2432]
Bonjour,
Dans la page :
https://support.mozilla.org/fr/kb/firefox-consomme-trop-memoire-ram-y-remedier#w_reduire-la-limite-de-processus-de-contenu
Vers le milieu :
about:memory aboutit sur un 404
Merci pour tout

**Comment by SphinxKnight** [comment]
Bonjour,

J'ai édité cette page sur le site support.mozilla.org afin de corriger le lien https://support.mozilla.org/fr/kb/firefox-consomme-trop-memoire-ram-y-remedier/revision/228995 

La documentation de Firefox de MDN a été en partie déplacée et archivée. Pour ce cas, vous pourrez voir les informations sur https://firefox-source-docs.mozilla.org/performance/memory/about_colon_memory.html

**Comment by Riribouldingue** [comment]
Merci beaucoup
Yves

----- Mail original -----
De: "SphinxKnight" ***@***.***>
À: "mdn/translated-content" ***@***.***>
Cc: "Riribouldingue" ***@***.***>, "Author" ***@***.***>
Envoyé: Mardi 14 Septembre 2021 09:01:55
Objet: Re: [mdn/translated-content] 404 (#2432)





Bonjour, 

J'ai édité cette page sur le site support.mozilla.org afin de corriger le lien https://support.mozilla.org/fr/kb/firefox-consomme-trop-memoire-ram-y-remedier/revision/228995 

La documentation de Firefox de MDN a été en partie déplacée et archivée. Pour ce cas, vous pourrez voir les informations sur https://firefox-source-docs.mozilla.org/performance/memory/about_colon_memory.html 

— 
You are receiving this because you authored the thread. 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .
