### ISSUE TITLE
Traduction française attribut "alt" de la balise "<img>"

### ISSUE THREAD

**Issue by marieholzer** [mdn/translated-content#24376]
### URL MDN

https://developer.mozilla.org/fr/docs/Web/HTML/Element/img

### Sur quelle section/titre porte ce problème ?

La partie "Exemple interactif"

### Quelle information était incorrecte, inutile ou incomplète ?

"L'attribut alt contient une description textuelle de l'image, ce qui n'est pas obligatoire mais extrêmement utile pour l'accessibilité." pose un problème parce que sans attribut "alt" dans les images, le code HTML n'est pas valide au niveau du W3C.

Le paragraphe qui suit, dans la section "Attributs" est assez contradictoire par ailleurs : 
"L'absence totale d'attribut alt indique que l'image n'est pas importante pour le contenu et qu'aucun équivalent textuel n'est disponible. Utiliser la chaîne de caractères vide comme valeur pour cet attribut (alt="") indique que cette image n'est pas importante pour le contenu (par exemple une décoration ou un pixel de pistage), dans ce cas, les navigateurs non-visuels peuvent ne pas la traiter pour le rendu. Les navigateurs visuels masqueront l'icône de l'image cassée si alt est vide et que le chargement de l'image a échoué." J'en retiens que si l'image n'est ouvertement pas importante, on peut juste mettre une chaîne vide et que c'est la bonne solution.

La version anglaise du site semble correcte et il s'agit sûrement d'une erreur de traduction : 
"The alt attribute holds a textual replacement for the image, which is mandatory and incredibly useful for accessibility" (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img)

La section "Attributes" en anglais est plus concise et plus claire : "Setting this attribute to an empty string (alt="") indicates that this image is not a key part of the content (it's decoration or a tracking pixel), and that non-visual browsers may omit it from [rendering](https://developer.mozilla.org/en-US/docs/Glossary/Engine/Rendering). Visual browsers will also hide the broken image icon if the alt attribute is empty and the image failed to display."

### Que vous attendiez-vous à voir ?

Je propose pour la section "Exemple interactif" de la version française :
""L'attribut alt est obligatoire et contient une description textuelle de l'image, ce qui est extrêmement utile pour l'accessibilité.""

Et pour la section "Attributes", propose d'enlever la première phrase : ""L'absence totale d'attribut alt indique que l'image n'est pas importante pour le contenu et qu'aucun équivalent textuel n'est disponible. "

### Avez-vous des liens, références ou citations sur ce sujet ?

J'ai utilisé le service de validation en ligne : https://validator.w3.org/nu/#textarea qui précise bien "Error: An img element must have an alt attribute, except under certain conditions." lorsqu'on lui donne du HTML sans alt dans les images.
Et je me suis référée à la documentation en anglais comme précédemment précisé : https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img

### Souhaitez-vous ajouter autre chose ?

Pour la petite histoire, je suis enseignante au lycée et j'ai découvert ce problème parce que mes élèves ont tous répondu faux à une question posée sur l'obligation de cet attribut. J'utilise personnellement spontanément la version anglais et je n'avais donc pas remarqué le souci avant.

### Métadonnées MDN

<details>
<summary>Page report details</summary>

* Folder: `fr/web/html/element/img`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTML/Element/img
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/html/element/img/index.md
* Last commit: https://github.com/mdn/translated-content/commit/fe03ae53896ba7a47cb2dd322e1bb8030dd0a3bc
* Document last modified: 2024-07-28T09:52:10.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour le rapport détaillé @marieholzer et les suggestions, j'ai soumis #24669
