### ISSUE TITLE
[ru] Error in `WebAssembly/C_to_Wasm` example 

### ISSUE THREAD

**Issue by diadiavova** [mdn/translated-content#24371]
### MDN URL

https://developer.mozilla.org/ru/docs/WebAssembly/C_to_Wasm

### О какой части статьи или абзаце идёт речь?

Вызов пользовательской функции, определённой в Си

### Какая информация оказалась неверной, бесполезной или неполной?

Команда компиляции примера
**emcc -o hello3.html hello3.c -O3 -s WASM=1 --shell-file html_template/shell_minimal.html -s NO_EXIT_RUNTIME=1  -s EXTRA_EXPORTED_RUNTIME_METHODS='["ccall"]'**
Здесь кавычка перемещена и в таком виде не компилируется.

### Как бы вы исправили?

В англоязычной версии рабочий код
**emcc -o hello3.html hello3.c --shell-file html_template/shell_minimal.html -s NO_EXIT_RUNTIME=1 -s "EXPORTED_RUNTIME_METHODS=['ccall']"**

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/webassembly/c_to_wasm`
* MDN URL: https://developer.mozilla.org/ru/docs/WebAssembly/C_to_Wasm
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/webassembly/c_to_wasm/index.md
* Last commit: https://github.com/mdn/translated-content/commit/dd24e1f757d6ab1a94f0561a71a59a5d28bef0dd
* Document last modified: 2024-08-08T12:26:15.000Z

</details>

**Comment by leon-win** [comment]
Привет, @diadiavova!

Спасибо за внимательность и указание на ошибку!

Я обновил перевод этой страницы, там было много других устаревших примеров, после влития #24392 страница обновится на сайте.
