### ISSUE TITLE
[ru] typo in `Web/HTTP/Overview`

### ISSUE THREAD

**Issue by xcc33333** [mdn/translated-content#24386]
https://developer.mozilla.org/ru/docs/Web/HTTP/Overview#http_%D0%BF%D0%BE%D1%82%D0%BE%D0%BA

bad version - HTTP — это [протокол](https://developer.mozilla.org/ru/docs/Glossary/Protocol), для получения различных ресурсов, например, HTML-документов.

good - HTTP — это [протокол](https://developer.mozilla.org/ru/docs/Glossary/Protocol) для получения различных ресурсов, например, HTML-документов.

**Comment by leon-win** [comment]
@xcc33333 , привет!

Непонятно, в чём проблема. Требуется более понятное описание.

**Comment by xcc33333** [comment]
Правила пунктуации как описание подойдет?

сб, 16 нояб. 2024 г., 23:11 Leonid Vinogradov ***@***.***>:

**Comment by leon-win** [comment]
> Правила пунктуации как описание подойдет?

Нет, это тоже плохое описание.

Но я смог понять, что имелась в виду лишняя запятая. Соответственно хорошим описанием было примерно такое:

```
В первом абзаце после слова "протокол" лишняя запятая, её следует убрать.
```

Я обновил полностью перевод этого документа в #24580.
