### ISSUE TITLE
关于`DataView.prototype.getInt32`是否应该被标记为`long`的讨论

### ISSUE THREAD

**Issue by jerry4718** [mdn/translated-content#24393]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/DataView

### 与此议题相关的小节或标题？

实例方法

### 哪些信息是错误、无用或不完善的？

```
DataView.prototype.getInt32()
从视图开始的指定字节偏移处获取一个带符号 32 位整数（long）。

DataView.prototype.getUint32()
从视图开始的指定字节偏移处获取一个无符号 32 位整数（unsigned long）。

DataView.prototype.setInt32()
在视图开始的指定字节偏移处存储一个带符号 32 位整数（long）。

DataView.prototype.setUint32()
在视图开始的指定字节偏移处存储一个无符号 32 位整数（unsigned long）。
```

这些内容中的``long``或者``unsigned long``标注似乎存在歧义，整个段落中的标注看起来更像是c的风格，但是``getInt32``返回值为long只在Web IDL中存在，我们明确的知道，这里getInt32只会固定读取32个bits

```
DataView.prototype.getBigInt64()
从视图开始的指定字节偏移处获取一个带符号 64 位整数（long long）。

DataView.prototype.getBigUint64()
从视图开始的指定字节偏移处获取一个无符号 64 位整数（unsigned long long）。

DataView.prototype.setBigInt64()
在视图开始的指定字节偏移处存储一个带符号 64 位 BigInt（long long）。

DataView.prototype.setBigUint64()
在视图开始的指定字节偏移处存储一个无符号 64 位 BigInt（unsigned long long）。
```

如果说``getInt32``的``long``还勉强可以解释，这里的``getBigInt64()``也同样出现了奇怪的效果，在Web IDL中，它的类型或许是``bigint``？而``long long``和``unsigned long long``只会让人联想到c

### 你期望看到什么？

我期望移除掉不明确的类型标注，或者在标注处同时标注出他们的来源，以免造成歧义

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/dataview`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/DataView
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/dataview/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1c76a73c1a2931b8a83d223aa40364306c09a382
* Document last modified: 2024-07-16T08:41:13.000Z

</details>

**Comment by skyclouds2001** [comment]
![image](https://github.com/user-attachments/assets/d8206c5f-e30a-4534-af43-744710aa38bc)

![image](https://github.com/user-attachments/assets/e347121a-b97b-4560-a0ba-69f14b258a9d)

英文原文只提到返回或设置一个64位的（无符号）整数，并没有提到 BigInt 的内容

另外严格来说， ECMA 中没 webidl 的内容

**Comment by jerry4718** [comment]
> 英文原文只提到返回或设置一个64位的（无符号）整数，并没有提到 BigInt 的内容
> 
> 另外严格来说， ECMA 中没 webidl 的内容

![image](https://github.com/user-attachments/assets/1face0ff-c317-4910-97ce-5452285fb732)

是的，TypedArray这里有提到bigint，但是这个似乎是另外的问题，我只是觉得``long``或者``long long``被这样无从考究的标记出来非常奇怪，谁也不知道它源自哪里

**Comment by skyclouds2001** [comment]
> 是的，TypedArray这里有提到bigint，但是这个似乎是另外的问题，我只是觉得`long`或者`long long`被这样无从考究的标记出来非常奇怪，谁也不知道它源自哪里

这点同意，英文原文就没这样的问题，可能是译者添加的
