### ISSUE TITLE
Contextmenu interface should be PointerEvent

### ISSUE THREAD

**Issue by joybee007** [mdn/translated-content#24407]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Element/contextmenu_event

### 哪些信息是错误、无用或不完善的？

通过addEventListener绑定的contextmenu事件处理函数，接收到的事件对象应该是一个PointerEvent，而不是MouseEvent。
![image](https://github.com/user-attachments/assets/682239a0-1640-41ac-915a-0dd2ad9cd881)

### 你期望看到什么？

引文中表格第三行：Interface应该是PointerEvent

### 你有什么支持的链接、参考或引用？

https://w3c.github.io/uievents/#event-type-contextmenu
![image](https://github.com/user-attachments/assets/90f5bce4-5318-42de-b090-8162fffb1892)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/element/contextmenu_event`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Element/contextmenu_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/element/contextmenu_event/index.md
* Last commit: https://github.com/mdn/translated-content/commit/2748fdf6b9cac93e9fd97ca2c1d6d9fa272faaab
* Document last modified: 2023-07-30T02:54:27.000Z

</details>

**Comment by PassionPenguin** [comment]
PointerEvent inherits from MouseEvent

![image](https://github.com/user-attachments/assets/5d0a257f-d337-4416-ad8f-931263658603)

![image](https://github.com/user-attachments/assets/9c82fee6-e517-4c9f-96ae-7bf9bb1d7253)
