### ISSUE TITLE
[es] flex-direction issue

### ISSUE THREAD

**Issue by NeonKobra** [mdn/translated-content#2457]
Content can't be displayed.

This is the error:
KumascriptError: unable to find any live code samples for "Example" within /es/docs/Web/CSS/flex-direction

Thanks!

**Comment by Graywolf9** [comment]
Hi! I look into https://developer.mozilla.org/es/docs/Web/CSS/flex-direction and everything seems to be working

**Comment by JuanVqz** [comment]
You are right! it seems like all it's working correctly.
@NeonKobra do you have any updates? If not we will close it soon

**Comment by JuanVqz** [comment]
Since @NeonKobra haven't updated more info about the issue we will close it, if you still having issues please open another issue, Also you can join us to the [Spanish Community](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org)

@Graywolf9 this was the last old open issue :+1:
