### ISSUE TITLE
Не хватает параметра options.signal

### ISSUE THREAD

**Issue by ninjakuro** [mdn/translated-content#24658]
### MDN URL

https://developer.mozilla.org/ru/docs/Web/API/EventTarget/addEventListener

### О какой части статьи или абзаце идёт речь?

Параметры

### Какая информация оказалась неверной, бесполезной или неполной?

У options не хватает параметра signal, который уже давно появился и есть в английской версии.

### Как бы вы исправили?

Надо добавить параметр signal и описание к нему

### Есть ли у вас какие-либо подтверждающие ссылки?

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

### Хотите добавить что-то ещё?

Во французской версии как и в русской тоже нет параметра signal.

В испанской, как и в португальской версии даже не слышали, что третий аргумент может быть объектом.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/web/api/eventtarget/addeventlistener`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/EventTarget/addEventListener
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/eventtarget/addeventlistener/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1aecac62424a8b70fcc3364eb52b1c82adb08e2c
* Document last modified: 2024-11-18T13:07:10.000Z

</details>

**Comment by leon-win** [comment]
Привет, @ninjakuro !

Благодарю за внимательность и желание помочь MDN! :+1: 

Я обновил перевод части этой страницы, вкулючая раздел с параметрами. После влития #24686 `signal` появится =)
