### ISSUE TITLE
Link to Microsoft VM's is no longer working

### ISSUE THREAD

**Issue by agausachs** [mdn/translated-content#24834]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/CSS/CSS_layout/Supporting_Older_Browsers

### ¿De qué sección específica o titular trata este problema?

Link

### ¿Qué información es incorrecta, inútil o incompleta?

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/  is no longer working. Accessing it gets you to a page where this message: 'We are sorry, the page you requested cannot be found.'

### ¿Qué esperaba ver?

List of Microsoft VM's to try older browsers

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/learn/css/css_layout/supporting_older_browsers`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/CSS/CSS_layout/Supporting_Older_Browsers
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/css/css_layout/supporting_older_browsers/index.md
* Last commit: https://github.com/mdn/translated-content/commit/fd4d27205d2e0669e83b1eee1ab611080179787f
* Document last modified: 2024-07-28T21:09:09.000Z

</details>

**Comment by PassionPenguin** [comment]
FYI: https://github.com/mdn/content/commit/dceb195d25764f4cd911dfce73c4bd676b4557e4 link was removed in here

lots of broken links are removed in en-us. I *tried* to have part of them removed in several languages but the workload is really heavy :(

**Comment by agausachs** [comment]
Sure! I just forked and corrected it. Pull request also done.
