### ISSUE TITLE
Chinese translation of Element.prepend() page

### ISSUE THREAD

**Issue by KoltZhang** [mdn/translated-content#25117]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Element/prepend

### 与此议题相关的小节或标题？

The question is at the top of the page, about the location of Element.prepend

### 哪些信息是错误、无用或不完善的？

"Element.prepend 方法可以在父节点的第一个子节点之前插入一系列Node对象或者DOMString对象。"

### 你期望看到什么？

"Element.prepend() 方法在当前 Element 的第一个子节点之前插入一组 Node 对象或 DOMString 对象。";
The main thing is to replace "父节点" with "当前 Element".

### 你有什么支持的链接、参考或引用？

Original:
"The Element.prepend() method inserts a set of [Node](https://developer.mozilla.org/en-US/docs/Web/API/Node) objects or strings before the first child of the [Element](https://developer.mozilla.org/en-US/docs/Web/API/Element)."

### 你还想补充什么内容？

This problem only occurs when the page language is Chinese.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/element/prepend`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Element/prepend
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/element/prepend/index.md
* Last commit: https://github.com/mdn/translated-content/commit/8685568b0b9e49d49937c3405d8633b3065dc897
* Document last modified: 2023-12-29T05:55:11.000Z

</details>

**Comment by yin1999** [comment]
说“父节点”本身是没问题的，但这里并未说明是将哪个节点作为“父节点”，我认为写成“当前节点”会更好些

**Comment by KoltZhang** [comment]
> 说“父节点”本身是没问题的，但这里的倾向说明了哪个作为节点“父节点”，我认为写成“当前节点”会更好一些 [object HTMLCollection]

是的，修改是很有必有的。
一般意义上讲父节点，默认指定的是调用prepend方法的节点的父节点。
另外，在节点的after()和before()方法中，它是为父节点插入子节点，这里讲“在父节点的子节点插入...”是正确且没有歧义的。
