### ISSUE TITLE
Ошибка отображения "png" файлов

### ISSUE THREAD

**Issue by PsychoAny** [mdn/translated-content#25138]
На странице - https://developer.mozilla.org/ru/docs/Learn/Common_questions/Web_mechanics/How_does_the_Internet_work
выявлена ошибка отображения всех файлов формата png
Браузер - Chrome, Версия 131.0.6778.140
![Снимок экрана 2024-12-18 013204](https://github.com/user-attachments/assets/900a38b8-1c07-4304-a2e3-933894fbcf30)

**Comment by leon-win** [comment]
Привет, @PsychoAny!

Благодарю за внимательность и желание помочь MDN! :+1: 

Судя по всему изображения перестали отображаться на всех переведённых страницах (для всех языков).
Я думаю, что это связано с переходом на новую систему сборки документов (rari).

Но зато я обновил перевод указанной страницы в #25160 :sunglasses:

**Comment by leon-win** [comment]
Проблему с изображениями исправили
