### ISSUE TITLE
Issue with "Связь Grid позиционирования с другими методами поз…": (short summary here please)

### ISSUE THREAD

**Issue by Kaelns** [mdn/translated-content#2573]
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/67708215/134771658-f70b7996-2cf2-4ade-8a7c-6b34e896f65d.png)
![image](https://user-images.githubusercontent.com/67708215/134771675-1661a1e2-8d8c-4d38-9b6b-c17d8cef6375.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/css/css_grid_layout/relationship_of_grid_layout`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/css_grid_layout/relationship_of_grid_layout/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1ebe847839b1d7476c1690db2a3f500af99a6e27
* Document last modified: 2021-09-24T00:49:15.000Z

</details>

**Comment by sashasushko** [comment]
Will be fix at #1888

**Comment by captainspring** [comment]
It seems like this has been fixed in #2774 so I’m closing the issue.
