### ISSUE TITLE
Issue with "paint-order": localised example missing

### ISSUE THREAD

**Issue by olegshilov** [mdn/translated-content#2594]
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/paint-order

![image](https://user-images.githubusercontent.com/930121/134926757-cb0bbc23-3f81-45f3-b591-32bb9a055e96.png)

#### What information was incorrect, unhelpful, or incomplete?
Iframe with example has failed to load.
Same page on en locale has working example. Suggest iframe need a fallback url if localised example is missing.

#### What did you expect to see?
Expect to see working example.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/css/paint-order`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/paint-order
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/paint-order/index.html
* Last commit: https://github.com/mdn/translated-content/commit/f8f3ea7a5dc31743409d63058cf2ff7222914f34
* Document last modified: 2021-09-27T00:37:51.000Z

</details>

**Comment by mpstv** [comment]
Проверил результат - исправлено в https://github.com/mdn/translated-content/pull/2633 .
