### ISSUE TITLE
Issue with "L'empilement de couches": (short summary here please)

### ISSUE THREAD

**Issue by hawa029** [mdn/translated-content#2598]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context

#### Did you test this? If so, how?

i've tested this with PHPStorm. It seemed to be a mistake: <div3> was not closed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/css/css_positioning/understanding_z_index/the_stacking_context`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/css_positioning/understanding_z_index/the_stacking_context/index.html
* Last commit: https://github.com/mdn/translated-content/commit/f8f3ea7a5dc31743409d63058cf2ff7222914f34
* Document last modified: 2021-09-27T00:37:51.000Z

</details>

**Comment by SphinxKnight** [comment]
bonjour @hawa029, pouvez-vous expliciter le problème rencontré sur cette page ?

**Comment by hawa029** [comment]
Juste pour tester le code, je l'ai copié et collé dans VSCode. il était signalé que la div3 n'était pas fermée. voilà! rien d'anormal dans le code. :-)

**Comment by SphinxKnight** [comment]
@hawa029 merci pour ce retour rapide et bien vu ! Le contenu de la doc CSS va bientôt être converti en Markdown, une fois que ces changements seront passés, je corrigerai :)
