### ISSUE TITLE
Horizontal scrolling page on desktop

### ISSUE THREAD

**Issue by vgschevchenko** [mdn/translated-content#2618]
On this page table creates a horizontal scroll.

https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness

![image](https://user-images.githubusercontent.com/89163314/133771036-d0f6d14b-0a32-4e46-b7c2-f5656a392a8b.png)

**Comment by sashasushko** [comment]
Fixed
