### ISSUE TITLE
Error in the JS lerning FR page : How do you add JavaScript to your page?

### ISSUE THREAD

**Issue by Riwat** [mdn/translated-content#2646]
EN is ok :
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/What_is_JavaScript#how_do_you_add_javascript_to_your_page

But in FR :
https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/What_is_JavaScript#comment_ajouter_du_javascript_à_votre_page

> Le JavaScript est appliqué à votre page HTML un peu comme le CSS. Les éléments < link > permettent d'appliquer des feuilles de style externes au HTML, les feuilles de styles internes utilisent les éléments < link >. Pour ajouter du JavaScript à un document HTML il y a une seule façon, avec l’élément <script>. Voyons cela sur un exemple.

The second < link > shoud be a <style> tag

**Comment by m4thieulavoie** [comment]
@SphinxKnight I would be happy to contribute a fix for this one 👍

**Comment by SphinxKnight** [comment]
Hello @m4thieulavoie, thanks :) I'm assigning this one to you, please let me know if you need any help :)

**Comment by m4thieulavoie** [comment]
> Hello @m4thieulavoie, thanks :) I'm assigning this one to you, please let me know if you need any help :)

I think I'm good, the PR is [here](https://github.com/mdn/translated-content/pull/2650) 😄
