### ISSUE TITLE
Misspelled

### ISSUE THREAD

**Issue by mattbike** [mdn/translated-content#2647]
Misspelled in Polish translation
https://developer.mozilla.org/pl/docs/Learn/JavaScript/First_steps/What_is_JavaScript#co_mo%C5%BCna_zrobi%C4%87

![odpowdz](https://user-images.githubusercontent.com/20409084/135834952-73f5596d-6f2a-4164-852c-50f1482550a9.png)

**Comment by SphinxKnight** [comment]
Sorry, but this locale is currently frozen and changes/fixes are not currently accepted. Please see https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ and [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo.
