### ISSUE TITLE
Issue with "scroll-behavior": (short summary here please)

### ISSUE THREAD

**Issue by EbenauDev** [mdn/translated-content#2662]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/scroll-behavior

#### Specific section or headline?
Output

#### What did you expect to see?
Smooth scrool not working in Google Chrome version 94.0.4606.61

#### Did you test this? If so, how?
I`m try test in same page in section output

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/css/scroll-behavior`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/scroll-behavior
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/css/scroll-behavior/index.html
* Last commit: https://github.com/mdn/translated-content/commit/e1c520dc746ffd0f03a8671b9d36257b7d713e2d
* Document last modified: 2021-10-04T19:50:02.000Z

</details>

**Comment by josielrocha** [comment]
Smooth scroll is working now.
I think it was happening in an outdated version.

Im am closing this issue now. Please let me know if you find this problema again.
