### ISSUE TITLE
Issue with "Date": コンストラクターを英語版に合わせる

### ISSUE THREAD

**Issue by NagayamaToshiaki** [mdn/translated-content#2665]
MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date

#### What information was incorrect, unhelpful, or incomplete?
英語版ではコンストラクターが2種（関数として読み込まれた場合とnewした場合）が掲載されているが、日本語版ではnewの方（しかもnewが付いていない）しか無い。

#### Specific section or headline?
コンストラクター

#### What did you expect to see?
両方のコンストラクターの説明。
`Date()`
関数として読み込まれた場合、‘new Date().toString()` とした時と同様に、現在の日時を表した文字列を返します。

`new Date()`
コンストラクターとして読み込まれた場合、新しい `Date` オブジェクトを返します。

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ja/web/javascript/reference/global_objects/date`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/javascript/reference/global_objects/date/index.html
* Last commit: https://github.com/mdn/translated-content/commit/e1c520dc746ffd0f03a8671b9d36257b7d713e2d
* Document last modified: 2021-10-04T19:50:02.000Z

</details>

**Comment by mfuji09** [comment]
誤字や英語版の更新の未反映など、修正が必要なことが客観的に見て明らかな場合は、Issueを立てるのではなく、直接ファイルを修正してプルリクエストすることを検討していただけるとありがたいです。
