### ISSUE TITLE
Issue with "429 Too Many Requests": (short summary here please)

### ISSUE THREAD

**Issue by Diogodiogo** [mdn/translated-content#2685]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/429

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/http/status/429`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/429
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/http/status/429/index.html
* Last commit: https://github.com/mdn/translated-content/commit/7185a386bee72299ec9ccae6b633ae15a2b1f5f2
* Document last modified: 2021-10-07T17:03:52.000Z

</details>

**Comment by cw118** [comment]
@Diogodiogo could you please provide more details about the issue(s) you're facing?

**Comment by cw118** [comment]
Closing since no information was provided. We can reopen if details on the issue are given :)
