### ISSUE TITLE
Issue with "content": (bug with iframe content)

### ISSUE THREAD

**Issue by arthursiq5** [mdn/translated-content#2693]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/content

#### What information was incorrect, unhelpful, or incomplete?

Live samples are wrong:

![Live sample message](https://user-images.githubusercontent.com/43865533/136662031-9932a6ad-2b4b-4925-b046-30dec48b3b0f.png)

#### Specific section or headline?

All live samples loaded with iframe

#### What did you expect to see?

A live sample

#### Did you test this? If so, how?

I reloaded the page several times with multiple navigators (Firefox, Chrome and Midori) and deleting the cache and the content was wrong all of times

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/css/content`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/content
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/css/content/index.html
* Last commit: https://github.com/mdn/translated-content/commit/7185a386bee72299ec9ccae6b633ae15a2b1f5f2
* Document last modified: 2021-10-07T17:03:52.000Z

</details>

**Comment by GuiCoutoSt** [comment]
Hello @ Arthur Q5, how are you? 

I looked at the live samples and they seem to be working now. Can you access it again and confirm this?

**Comment by cw118** [comment]
I checked the page using several browsers and all the examples seem fine. Closing at least for now, we can reopen if necessary.
