### ISSUE TITLE
How to truncate brazilian portuguese decimal numbers separators? Issue with "Math.trunc()": (short summary here please)

### ISSUE THREAD

**Issue by luismendes070** [mdn/translated-content#2726]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/javascript/reference/global_objects/math/trunc`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/javascript/reference/global_objects/math/trunc/index.html
* Last commit: https://github.com/mdn/translated-content/commit/faa42f59fe323aa6c5da07ab099ce903ab955cc5
* Document last modified: 2021-10-12T17:20:14.000Z

</details>

**Comment by luismendes070** [comment]
Decimal Separators
https://en.wikipedia.org/wiki/Decimal_separator

**Comment by cw118** [comment]
Closing since there isn't enough information. 

@luismendes070 if there is still an issue with the MDN page <https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Math/trunc>, please provide more details and we can reopen this.
