### ISSUE TITLE
Issue with "CSS layout": (wrong grid russian page)

### ISSUE THREAD

**Issue by ithrforu** [mdn/translated-content#2741]
Hello! 
In russian version of [grid page](https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Grids) loading page with [legacy layout methods](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods). 

In [english version](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Grids) it works right.

**Comment by sashasushko** [comment]
Привет @ithrforu, спасибо за ишью. Это не ошибка, просто пока в русской версии MDN нет такой страницы, поэтому вместо её содержимого выводится предложение перейти в английскую версию:
![изображение](https://user-images.githubusercontent.com/4469056/138042536-bd143f20-34a9-44d1-9369-5aec62159097.png)

Как только перевод будет готов, страница появится в русской версии MDN.
