### ISSUE TITLE
Перевод MDN на русский язык

### ISSUE THREAD

**Issue by lex111** [mdn/translated-content#276]
Это основная тема, где вы можете предложить свою помощь, задать вопросы или поделиться предложениями.

Для некоторых разделов созданы отдельные ишью со списком страниц для перевода, где вы можете выбрать, что перевести, только перед этим отпишитесь, чтобы другие знали о вашей работе, а мы отметили вас в списке.

Если вы хотите перевести страницу из раздела, для которого нет отдельного ишью, отпишитесь об этом здесь. Также о крупных изменениях желательно оповещать заранее.
 
И, конечно, перед началом работы обязательно ознакомьтесь с [руководством по переводу](https://github.com/mdn/translated-content/blob/main/docs/ru/translation-guide.md).

- Перевод [глосария](https://github.com/mdn/translated-content/issues/274)
- Перевод раздела [Изучение веб-разработки](https://github.com/mdn/translated-content/issues/275)
- Перевод раздела о [HTML](https://github.com/mdn/translated-content/issues/277)
- Перевод раздела [MDN](https://github.com/mdn/translated-content/issues/292)

**Comment by mirexdoors** [comment]
Привет! Я начал переводить страницы из подраздела [API/HTMLCanvasElement ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/) и, наверное, хотел бы пока продолжить в нём.

**Comment by captainspring** [comment]
Привет!
Предлагаю выбрать и унифицировать перевод `Browser compatibility` (в статьях сейчас гуляет два варианта: «Поддержка браузерами» или «Совместимость с браузерами», не знаю, какой чаще) и закрепить его потом [в рекомендациях](https://github.com/mdn/translated-content/blob/main/docs/ru/translation-guide.md). 
Я думаю, что «поддержка браузерами» ближе к правде, чем «совместимость», но не настаиваю.
Если кто-нибудь расскажет мне, как сделать автозамену в большом количестве файлов — могу заняться этим (я пока что умею разве что руками, но это займет вечность). Либо это может сделать кто-то, кто уже умеет в автозамену.

Как и говорила ранее, я пойду заниматься потеряшками и начну с [полифила](https://github.com/mdn/translated-content/tree/main/files/ru/orphaned/glossary/polifill). :)

**Comment by lex111** [comment]
@captainspring конечно, чаще будет второй, потому что он ближе к оригиналу, но, думаю, никто не будет против использовать более понятный и привычный вариант. Просто в редакторе глобально сделать замену, ничего сложного на самом деле, только включить учет регистра, чтобы лишнего ничего не задеть.

**Comment by captainspring** [comment]
> Просто в редакторе глобально сделать замену

Так, я погуглила и вроде разобралась, как это делается, поэтому на днях унифицирую в «Поддержка браузерами»)

**Comment by myshov** [comment]
Я хочу начать работу над https://developer.mozilla.org/en-US/docs/MDN и всеми вложенными страницами

**Comment by lex111** [comment]
@myshov создать отдельную ишью для этого раздела?

**Comment by myshov** [comment]
@lex111 Да, буду благодарен. Если что могу сам сделать, но только попозже

**Comment by lex111** [comment]
@myshov готово https://github.com/mdn/translated-content/issues/292, отметь только страницы, над которыми работаешь, мало ли кто ещё подхватит, чтобы не пересекались.

**Comment by myshov** [comment]
@lex111 спасибо!

**Comment by captainspring** [comment]
В ишью #329 неправильные референсы к англоязычной странице — там очень старый перевод страницы [SharedArrayBuffer](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer). Я обновлю перевод, если никто не претендует.

**Comment by IzoldaV** [comment]
Привет! Я возьмусь за перевод [client-side_javascript_frameworks/svelte_getting_started](https://github.com/mdn/content/blob/main/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/index.html)

**Comment by warsan** [comment]
Выдернул из браузера содержимое `<aside class="metadata">`,  _(присутствует на каждой странице MDN)_, вставил в песочницу и [сделал приблизительный перевод](https://codepen.io/warsan/pen/LYWgzyY?editors=1100). Если эта `<aside class="metadata">` генерируется скриптом, необходимо найти репо, в которой лежит этот скрипт. (или шаблон), и завершить начатое... 
_(помогите найти этот репозиторий, а то в чате не отвечают)_

**Comment by myshov** [comment]
@warsan эти строки находятся в [программном коде](https://github.com/mdn/yari/blob/ce67d66ecd57752801745e9e4d77944925a85c5e/client/src/document/on-github.tsx#L5-L27) yari (движок сайта)
На данный момент нет возможности добавить перевод для этих строк https://github.com/mdn/yari/issues/1197

**Comment by warsan** [comment]
— Спасибо, надо хотя бы "временный костыль" вставить вместо этого `<aside class="metadata">`

**Comment by dkoltovich** [comment]
Всем привет.

Недавно столкнулся с проблемой перевода блока "Примечание" с использованием Markdown (#2586).
Как выяснилось нужно добавить "magic words", которые будут помогать движку [yari](https://github.com/mdn/yari) правильно отрисовывать [блоки "Note", "Warning" и "Callout"](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#notes_warnings_and_callouts) на русском языке.

Далее цитата из #1236:

> Since this magic word is both an instruction to Yari and appears in the rendered output, it needs to be locale-sensitive. This means that each locale will need to decide which words they want to use for these page elements, and file an issue or PR on mdn/yari with the words they have chosen, so Yari can properly process the markup in that locale.

Было бы неплохо решить, что за "волшебные" слова это будут и открыть PR или issue в [yari](https://github.com/mdn/yari).

**Comment by cypma5** [comment]
Добрый день. Готов занятся переводом https://developer.mozilla.org/ru/docs/Web/Security.
@lex111 Можете для него отдельный создать ишью?

**Comment by leon-win** [comment]
Всем привет!

Я хочу занятся переводом Глоссария, точнее уже начал)) (https://github.com/mdn/translated-content/pull/16722).
В связи с этим возникло несколько вопросов. Помогите, пожалуйста, разобраться:

1. Насколько я понимаю, пречисленные в этой теме задачи уже неактуальны (#274, #275, #277, #292) и теперь не нужно заводить отдельную задачу на перевод каждой страницы, можно сразу создавать PR?
2. Описание к PR лучше писать на русском или английском? Я в первый раз сделал на английском, для унификации и чтобы было понятно как можно большему количеству людей из сообщества. Но потом подумал, что описание сделанного возможно логичнее составлять на языке перевода, то есть русском, потому что так можно будет лучше объяснять некоторые нюансы перевода. Кто что думает по этому поводу?
3. Обратил внимание, что на русских страницах [Глоссария](https://developer.mozilla.org/ru/docs/Glossary) отсутствует сайдбар со списком терминов. Вот для этого кажется можно завести отдельную задачу и добавить его везде сразу. Или есть какая-то причина почему его нет на русских страницах?
4. В локально запущенной версии MDN у меня отображается такое сообщение: ![image](https://github.com/mdn/translated-content/assets/1682136/5026f33d-ac65-49bd-8733-ade7b41fb79b) Это глобальная проблема или может быть связано с тем, что я что-то не донастроил?)

**Comment by leon-win** [comment]
Что-то у нас тут с активностью не очень(((
А как узнать у кого есть права на ревью и влитие кода? И потом выяснить кто из них остался в числе активных?))
На данный момент я заметил только одного @sashasushko

**Comment by sashasushko** [comment]
> Это глобальная проблема или может быть связано с тем, что я что-то не донастроил?)

У меня так же.

> Обратил внимание, что на русских страницах [Глоссария](https://developer.mozilla.org/ru/docs/Glossary) отсутствует сайдбар со списком терминов. Вот для этого кажется можно завести отдельную задачу и добавить его везде сразу. Или есть какая-то причина почему его нет на русских страницах?

Нужно проверить исходники, возможно, поменялся виджет.

> Описание к PR лучше писать на русском или английском? Я в первый раз сделал на английском, для унификации и чтобы было понятно как можно большему количеству людей из сообщества. Но потом подумал, что описание сделанного возможно логичнее составлять на языке перевода, то есть русском, потому что так можно будет лучше объяснять некоторые нюансы перевода. Кто что думает по этому поводу?

Английский для истории лучше, а вообще мы рады ПР с изменениями на любом языке.

> теперь не нужно заводить отдельную задачу на перевод каждой страницы, можно сразу создавать PR?

Да, сразу с ПР.

> А как узнать у кого есть права на ревью и влитие кода? И потом выяснить кто из них остался в числе активных?))

Мейнтейнера с правом мержа назначит бот. Активные пока я и @Saionaro
