### ISSUE TITLE
Issue with "CSS layout": links to lessons on CSS layout page

### ISSUE THREAD

**Issue by ithrforu** [mdn/translated-content#2831]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout

Hello! In russian version of [CSS layout lessons](https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout) links to [Responsive design Beginner's guide](https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Responsive_Design) and [Beginner's guide to media queries](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Media_queries) is absent. 

Russian verison:
![image](https://user-images.githubusercontent.com/81531000/138488808-4c3f2b04-80e5-4737-8c22-dc0614a33d32.png)

English:
![image](https://user-images.githubusercontent.com/81531000/138488916-ec449451-0110-470d-ba6e-7a002c2c04c3.png)

**Comment by Techi-Dev** [comment]
Try this link https://developer.mozilla.org/ru/docs/Web/CSS/Media_Queries/Using_media_queries
