### ISSUE TITLE
All Japanese pages with an EmbedLiveSample error

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#2843]
After a local crawl of the docset (as of today), it seems all of the following pages have an EmbedLiveSample/MacroLiveSampleError.

Filing this as an issue to help fix this all at once rather than from reports from readers:

- https://developer.mozilla.org/ja/docs/web/html/element/ul
- https://developer.mozilla.org/ja/docs/web/html/element/rtc
- https://developer.mozilla.org/ja/docs/web/html/element/input/datetime-local
- https://developer.mozilla.org/ja/docs/web/css/css_grid_layout/relationship_of_grid_layout
- https://developer.mozilla.org/ja/docs/web/css/css_grid_layout/layout_using_named_grid_lines
- https://developer.mozilla.org/ja/docs/web/css/_doublecolon_-moz-range-track
- https://developer.mozilla.org/ja/docs/web/css/appearance
- https://developer.mozilla.org/ja/docs/web/css/_colon_lang
- https://developer.mozilla.org/ja/docs/web/css/align-content
- https://developer.mozilla.org/ja/docs/web/css/transform-function/matrix3d%28%29
- https://developer.mozilla.org/ja/docs/web/css/-webkit-text-fill-color
- https://developer.mozilla.org/ja/docs/web/css/_doublecolon_-webkit-progress-value
- https://developer.mozilla.org/ja/docs/web/css/_colon_visited
- https://developer.mozilla.org/ja/docs/web/css/border
- https://developer.mozilla.org/ja/docs/web/css/resize
- https://developer.mozilla.org/ja/docs/web/css/touch-action
- https://developer.mozilla.org/ja/docs/web/css/_colon_nth-last-child
- https://developer.mozilla.org/ja/docs/web/css/_colon_-moz-drag-over
- https://developer.mozilla.org/ja/docs/web/css/_colon_-moz-focusring
- https://developer.mozilla.org/ja/docs/web/css/empty-cells
- https://developer.mozilla.org/ja/docs/web/css/@media/prefers-contrast
- https://developer.mozilla.org/ja/docs/web/css/@media/-webkit-device-pixel-ratio
- https://developer.mozilla.org/ja/docs/web/css/css_images/using_css_gradients
- https://developer.mozilla.org/ja/docs/web/svg/element/mpath
- https://developer.mozilla.org/ja/docs/web/svg/element/script
- https://developer.mozilla.org/ja/docs/web/api/mediatracksupportedconstraints/noisesuppression
- https://developer.mozilla.org/ja/docs/web/api/mediatracksupportedconstraints/autogaincontrol
- https://developer.mozilla.org/ja/docs/web/api/htmlinputelement/setrangetext
- https://developer.mozilla.org/ja/docs/web/api/htmlinputelement/select
- https://developer.mozilla.org/ja/docs/web/api/canvasrenderingcontext2d/linecap
- https://developer.mozilla.org/ja/docs/web/api/canvasrenderingcontext2d/arcto
- https://developer.mozilla.org/ja/docs/web/api/canvasrenderingcontext2d/fillstyle
- https://developer.mozilla.org/ja/docs/web/api/window/pageshow_event
- https://developer.mozilla.org/ja/docs/web/api/window/devicepixelratio
- https://developer.mozilla.org/ja/docs/web/api/eventlistener
- https://developer.mozilla.org/ja/docs/web/api/range/commonancestorcontainer
- https://developer.mozilla.org/ja/docs/web/api/element/mouseout_event
- https://developer.mozilla.org/ja/docs/web/api/document/caretpositionfrompoint
- https://developer.mozilla.org/ja/docs/web/api/blob
- https://developer.mozilla.org/ja/docs/web/api/path2d/addpath
- https://developer.mozilla.org/ja/docs/web/api/canvas_api/tutorial/advanced_animations
- https://developer.mozilla.org/ja/docs/web/api/globaleventhandlers/onmouseout
- https://developer.mozilla.org/ja/docs/web/api/globaleventhandlers/onmousemove
- https://developer.mozilla.org/ja/docs/web/api/globaleventhandlers/onmouseover
- https://developer.mozilla.org/ja/docs/web/api/globaleventhandlers/onwheel
- https://developer.mozilla.org/ja/docs/web/guide/css/block_formatting_context
- https://developer.mozilla.org/ja/docs/learn/forms/form_validation
- https://developer.mozilla.org/ja/docs/learn/javascript/first_steps/what_is_javascript

**Comment by mfuji09** [comment]
The all error seem resolved.
