### ISSUE TITLE
All Russian pages with an EmbedLiveSample error

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#2844]
After a local crawl of the docset (as of today), it seems all of the following pages have an EmbedLiveSample/MacroLiveSampleError.

Filing this as an issue to help fix this all at once rather than from reports from readers:

- https://developer.mozilla.org/ru/docs/web/html/element/input/range
- https://developer.mozilla.org/ru/docs/web/css/css_grid_layout/line-based_placement_with_css_grid
- https://developer.mozilla.org/ru/docs/web/css/appearance
- https://developer.mozilla.org/ru/docs/web/css/_colon_focus-visible
- https://developer.mozilla.org/ru/docs/web/css/used_value
- https://developer.mozilla.org/ru/docs/web/css/clear
- https://developer.mozilla.org/ru/docs/web/css/@media/scripting
- https://developer.mozilla.org/ru/docs/web/css/@media/inverted-colors
- https://developer.mozilla.org/ru/docs/web/css/height
- https://developer.mozilla.org/ru/docs/web/css/_colon_indeterminate
- https://developer.mozilla.org/ru/docs/web/javascript/reference/global_objects/array/some
- https://developer.mozilla.org/ru/docs/web/svg/element/ellipse
- https://developer.mozilla.org/ru/docs/web/svg/attribute/text-anchor
- https://developer.mozilla.org/ru/docs/web/svg/attribute/stroke
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/save
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/getimagedata
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/linecap
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/drawimage
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/closepath
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/getlinedash
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/globalalpha
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/fillstyle
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/ellipse
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/linejoin
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/textbaseline
- https://developer.mozilla.org/ru/docs/web/api/canvasrenderingcontext2d/currenttransform
- https://developer.mozilla.org/ru/docs/web/api/css_object_model/managing_screen_orientation
- https://developer.mozilla.org/ru/docs/web/api/element/keydown_event
- https://developer.mozilla.org/ru/docs/web/api/document/url
- https://developer.mozilla.org/ru/docs/web/api/document/cookie
- https://developer.mozilla.org/ru/docs/web/api/canvas_api/tutorial/using_images
- https://developer.mozilla.org/ru/docs/web/api/canvas_api/tutorial/pixel_manipulation_with_canvas
- https://developer.mozilla.org/ru/docs/web/api/canvas_api/tutorial/basic_usage
- https://developer.mozilla.org/ru/docs/web/api/canvas_api/tutorial/drawing_shapes

**Comment by sashasushko** [comment]
@SphinxKnight I think this issue isn't more actual
