### ISSUE TITLE
All Korean pages with an EmbedLiveSample error

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#2848]
After a local crawl of the docset (as of today), it seems all of the following pages have an EmbedLiveSample/MacroLiveSampleError.

Filing this as an issue to help fix this all at once rather than from reports from readers:
- [x] https://developer.mozilla.org/ko/docs/web/html/inline_elements
- [x] https://developer.mozilla.org/ko/docs/web/html/applying_color
- [x] https://developer.mozilla.org/ko/docs/web/html/element/label
- [x] https://developer.mozilla.org/ko/docs/web/html/element/var
- [ ] https://developer.mozilla.org/ko/docs/web/html/element/style
- [ ] https://developer.mozilla.org/ko/docs/web/html/element/u
- [ ] https://developer.mozilla.org/ko/docs/web/html/element/input/radio
- [x] https://developer.mozilla.org/ko/docs/web/html/element/div
- https://developer.mozilla.org/ko/docs/web/css/css_grid_layout/relationship_of_grid_layout
- https://developer.mozilla.org/ko/docs/web/css/css_grid_layout/layout_using_named_grid_lines
- https://developer.mozilla.org/ko/docs/web/css/css_grid_layout/basic_concepts_of_grid_layout
- https://developer.mozilla.org/ko/docs/web/css/css_grid_layout/grid_template_areas
- https://developer.mozilla.org/ko/docs/web/css/vertical-align
- https://developer.mozilla.org/ko/docs/web/css/display-internal
- https://developer.mozilla.org/ko/docs/web/css/order
- https://developer.mozilla.org/ko/docs/web/css/text-shadow
- https://developer.mozilla.org/ko/docs/web/css/overflow-wrap
- https://developer.mozilla.org/ko/docs/web/css/using_css_custom_properties
- https://developer.mozilla.org/ko/docs/web/css/text-decoration
- https://developer.mozilla.org/ko/docs/web/css/id_selectors
- https://developer.mozilla.org/ko/docs/web/css/revert
- https://developer.mozilla.org/ko/docs/web/css/box-sizing
- https://developer.mozilla.org/ko/docs/web/svg/attribute/keytimes
- https://developer.mozilla.org/ko/docs/web/svg/tutorial/patterns
- https://developer.mozilla.org/ko/docs/web/api/filereader/readasdataurl
- https://developer.mozilla.org/ko/docs/web/api/eventlistener
- https://developer.mozilla.org/ko/docs/web/api/element/blur_event
- https://developer.mozilla.org/ko/docs/web/api/notifications_api/using_the_notifications_api
- https://developer.mozilla.org/ko/docs/web/api/document/keyup_event
- https://developer.mozilla.org/ko/docs/web/api/htmlelement/input_event
- https://developer.mozilla.org/ko/docs/web/api/settimeout
- https://developer.mozilla.org/ko/docs/web/api/canvas_api/tutorial/using_images
- https://developer.mozilla.org/ko/docs/web/api/canvas_api/tutorial/advanced_animations
- https://developer.mozilla.org/ko/docs/web/api/canvas_api/tutorial/basic_animations
- https://developer.mozilla.org/ko/docs/web/api/canvas_api/tutorial/transformations
- https://developer.mozilla.org/ko/docs/web/api/canvas_api/tutorial/applying_styles_and_colors
- https://developer.mozilla.org/ko/docs/web/api/canvas_api/tutorial/drawing_text
- https://developer.mozilla.org/ko/docs/web/api/canvas_api/tutorial/basic_usage
- https://developer.mozilla.org/ko/docs/web/api/canvas_api/tutorial/drawing_shapes
- https://developer.mozilla.org/ko/docs/web/api/file/using_files_from_web_applications
- https://developer.mozilla.org/ko/docs/web/api/globaleventhandlers/onkeydown
- https://developer.mozilla.org/ko/docs/web/api/svgrect
- https://developer.mozilla.org/ko/docs/learn/html/introduction_to_html/getting_started
- https://developer.mozilla.org/ko/docs/learn/html/introduction_to_html/advanced_text_formatting
- https://developer.mozilla.org/ko/docs/learn/css/styling_text/fundamentals
- https://developer.mozilla.org/ko/docs/learn/css/first_steps/how_css_works
- https://developer.mozilla.org/ko/docs/learn/css/css_layout/floats
- https://developer.mozilla.org/ko/docs/learn/javascript/first_steps/strings
- https://developer.mozilla.org/ko/docs/learn/javascript/first_steps/variables

**Comment by hochan222** [comment]
@SphinxKnight  It seems to have been resolved a lot now, so I think I need to crawl again. Is there a way to check the current error page? Please let me know how, and I'll check it periodically. Thank you. Have a nice day :) (cc. @schalkneethling )

**Comment by SphinxKnight** [comment]
@hochan222 I'll try to find what I did in the days and run it this week on an updated repo. I will update the issue accordingly

**Comment by hochan222** [comment]
@SphinxKnight, Ah.. It was a separate script, not a feature of yari. Yes, thank you. I will proceed after checking. :)

**Comment by hochan222** [comment]
2023.01.25 기준

http://localhost:5042/ko/docs/web/svg/element/rect
http://localhost:5042/ko/docs/web/svg/element/a
http://localhost:5042/ko/docs/web/svg/element/circle
http://localhost:5042/ko/docs/web/svg/element/ellipse
http://localhost:5042/ko/docs/web/css/animation
http://localhost:5042/ko/docs/web/css/css_positioning/understanding_z_index/adding_z-index
http://localhost:5042/ko/docs/web/api/webgl_api/by_example/textures_from_code
http://localhost:5042/ko/docs/web/api/webgl_api/by_example/detect_webgl
http://localhost:5042/ko/docs/web/api/webgl_api/by_example/hello_vertex_attributes
http://localhost:5042/ko/docs/web/api/webgl_api/by_example/simple_color_animation
http://localhost:5042/ko/docs/web/api/webgl_api/by_example/clearing_by_clicking
http://localhost:5042/ko/docs/web/api/webgl_api/by_example/scissor_animation
http://localhost:5042/ko/docs/web/api/webgl_api/by_example/hello_glsl

**Comment by nnnnoel** [comment]
안녕하세요 @hochan222 
해당 이슈 complete된 것 같아 노티 드립니다.

**Comment by hochan222** [comment]
@nnnnoel 님 멘션주셔서 감사합니다. 

이슈 해결해주셔서 정말 감사해요. 고생 많으셨습니다. 좋은 주말 보내세요 :) 

@SphinxKnight, Thank you again.
