### ISSUE TITLE
[ko] Remove `summary` and `seoSummary` classes, web/javascript

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#2895]
관련 이슈: https://github.com/mdn/translated-content/issues/2894 

**목적: `web/javascript` 폴더 문서에서 모든 `summary` 와 `seoSummary` class를 삭제해야합니다.**

## 세부 내용 [참고 링크](https://github.com/mdn/translated-content/discussions/2474)

* Remove `summary` and `seoSummary` classes
  * They won't be carried over in Markdown and the first paragraph of a page is used for SEO/summary anyway.
  * Feel free to rephrase / reorganize the existing blocks so that the first paragraph makes sense on its own and is not too long. If you're not sure, check the English state of things (cf. below).
  * In the end, checking `class=".*?summary.*?"` should not report any match

## 원활한 리뷰를 위해 다음 사항을 지켜주세요.

- 한 PR당 최대 변경 파일의 개수는 20개를 넘지 않게 해주세요.

**Comment by kraccoon-dev** [comment]
@hochan222  안녕하세요, 이슈를 해결하기 위해 `summary`클래스를 가진 파일을 검색해보니 총 35개의 파일이 나왔습니다. 개인적인 생각이지만, 리뷰시에도 정규식을 이용해 검토한다면 많은 시간이 들지 않을것 같습니다. 그러니, pr규칙을 존중하지만, 이 이슈만 예외적으로 pr시 변경 파일의 개수를 제한하지 않거나 늘려주실 수 있는지 검토해주실 수 있을까요? 감사합니다:)

**Comment by hochan222** [comment]
@kraccoon-dev 님 안녕하세요. 먼저 기여해주셔서 감사합니다. 

35개 파일 한번에 PR 주셔도 괜찮을듯합니다. 

먼저, 20개로 정한 이유는 하기와 같습니다.

- diff를 볼 때 렉 방지
  - 이전에 100개 이상의 파일을 리뷰를 했었는데 코드 로딩 시 렉이 많이 걸렸습니다.
- 리뷰어가 빠른 시간 내에 리뷰를 드릴 수 있는 단위
- 여러 리뷰어 분이 해당 이슈에 대해 인지

[번역가이드](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md)와 달리 의무적인 부분으로 적어 놓은 건 아니여서 @kraccoon-dev 님 재량에 따라 PR 주시면 좋을듯 합니다.

감사합니다 :)

**Comment by kraccoon-dev** [comment]
@hochan222 확인해주셔서 감사합니다. 다음번엔 웬만해선 규칙을 꼭 지키겠습니다ㅠ 좋은밤 되세요😋
