### ISSUE TITLE
[ko] Remove `<span>`s around content, web/javascript

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#2898]
관련 이슈: https://github.com/mdn/translated-content/issues/2894 

**목적: `web/javascript` 폴더 문서에서 모든 `<span>`태그 삭제. [참고 링크](https://github.com/mdn/translated-content/pull/1574/commits/71776e76b5b7146930804e5715fce23149b159f7#diff-faed0605ac1a85ce73a04b27e03254e78ca8abbbe5051f6aa554a77cd7d8ae33)**

## 세부 내용 [참고 링크](https://github.com/mdn/translated-content/discussions/2474)

   * Remove `<span>`s around content
     * I'm using this regexp `<span.*?>([\s\S\r]*?)</span>` (replacing the content with `$1`)

## 원활한 리뷰를 위해 다음 사항을 지켜주세요.

- 한 PR당 최대 변경 파일의 개수는 20개를 넘지 않게 해주세요.

**Comment by yechoi42** [comment]
@kraccoon-dev 님, 두 번에 걸쳐서 기여해주셨는데 모두 해결된 것일까요? 닫아도 될까요?

**Comment by kraccoon-dev** [comment]
@yechoi42 네, 닫아주세요.

**Comment by yechoi42** [comment]
@kraccoon-dev 넵 감사합니다 닫겠습니다:)
