### ISSUE TITLE
[ko] Remove elements with the `hidden` class, except for `<pre>`s, web/javascript

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#2899]
관련 이슈: https://github.com/mdn/translated-content/issues/2894 

**목적: `web/javascript` 폴더 문서에서 `<pre>` 태그를 제외한 `hidden` class를 삭제해야합니다.**

## 세부 내용 [참고 링크1](https://github.com/mdn/translated-content/pull/1574/commits/8e5fef4bdebd242267fe3ee5dd842355250addd7#diff-8d2a67c61d6d421784d5becca52980aae15c5b4441abe76008ce0f9fb913e48f), [참고 링크2](https://github.com/mdn/translated-content/pull/1574/commits/1c6031ef89ff0f3ffbc60383b42d989e419de053)

* Remove elements with the `hidden` class, except for `<pre>`s
  * If the hidden block is a `<div>` which encloses several `<pre>`, you should remove the `<div>` and "propagate" the `hidden` class to the `<pre>` block. Also, you should use your best judgement to assess if this part actually needs to be hidden
  * You're most likely to find `<div>`s and `<p>`s with this class
  * In the end, checking `class=".*?hidden.*?"` should only report `<pre>` elements

## 원활한 리뷰를 위해 다음 사항을 지켜주세요.

- 한 PR당 최대 변경 파일의 개수는 20개를 넘지 않게 해주세요.

**Comment by kraccoon-dev** [comment]
![image](https://user-images.githubusercontent.com/69508345/152481587-9594390a-e856-4396-ae7a-999afc2ea0b1.png)
`class="[^"]*hidden[^"]*"`으로 검색했을 때 `hidden` 클래스를 가진 태그가 하나도 없습니다. 확인 후 이슈를 닫아주시면 될것 같습니다!

**Comment by hochan222** [comment]
@kraccoon-dev 님 확인 감사드립니다. 좋은 하루 보내세요 :)
