### ISSUE TITLE
Issue with "流程控制与错误处理": The section about Promises should be removed. (中文版本Chinese version)

### ISSUE THREAD

**Issue by BENCJL** [mdn/translated-content#2918]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Control_flow_and_error_handling

#### What information was incorrect, unhelpful, or incomplete?
There is a single page about Promises. So the section about Promises is unnecessary on this page. Actually, there is no such section about Promises on the same page in English version. I suggest that the Chinese version should keep the same with the English version.

#### Specific section or headline?
The section about Promise. (https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Control_flow_and_error_handling#promises)

#### What did you expect to see?
Remove the section about Promise in this page.

#### Did you test this? If so, how?
No need.

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/guide/control_flow_and_error_handling`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Control_flow_and_error_handling
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/guide/control_flow_and_error_handling/index.html
* Last commit: https://github.com/mdn/translated-content/commit/5fe5348d14d1a6e8d07fe282f866aaa870aad240
* Document last modified: 2021-10-29T20:30:13.000Z

</details>

**Comment by kaichii** [comment]
异步流程控制没什么不妥
