### ISSUE TITLE
Перевод раздела MDN

### ISSUE THREAD

**Issue by lex111** [mdn/translated-content#292]
## Как помочь с переводом

1. Проверьте в чеклисте или в комментариях ниже, что никто другой не взял страницу
2. Отпишитесь, какую страницу вы хотите перевести (не более одну за один раз)

Рядом с 🌐 находится ссылка с уже переведённой страницей, которая скорее всего нуждается в актуализации. 

## 📂 __[The MDN project](https://github.com/mdn/content/blob/main/files/en-us/mdn/index.html)__ (🌐 [Проект MDN](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/index.html))
   - [ ] 📄 [About MDN Web Docs](https://github.com/mdn/content/blob/main/files/en-us/mdn/about/index.html) (🌐 [О MDN](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/about/index.html))
   - [ ] 📂 __[MDN at 10](https://github.com/mdn/content/blob/main/files/en-us/mdn/at_ten/index.html)__ (🌐 [10\-летие MDN](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/at_ten/index.html))
     - [ ] 📄 [The History of MDN](https://github.com/mdn/content/blob/main/files/en-us/mdn/at_ten/history_of_mdn/index.html)
   - [x] 📂 __[Contributing to MDN](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/index.html)__ (🌐 [Сотрудничество с MDN](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/index.html))
     - [ ] 📄 [MDN contribution changelog](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/changelog/index.html)
     - [ ] 📄 [MDN documentation priority list](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/documentation_priorities/index.html)
     - [ ] 📄 [Send feedback about MDN Web Docs](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/feedback/index.html) (🌐 [Отправить отзыв об MDN](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/feedback/index.html))
     - [ ] 📄 [Fixing MDN content bugs](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/fixing_mdn_content_bugs/index.html)
     - [x] 📄 [Getting started on MDN](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/getting_started/index.html) (🌐 [Mozilla \- Быстрый старт\!](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/getting_started/index.html))
     - [ ] 📄 [GitHub for complete beginners](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/github_beginners/index.html)
     - [ ] 📄 [GitHub best practices for MDN](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/github_best_practices/index.html)
     - [ ] 📄 [GitHub cheatsheet](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/github_cheatsheet/index.html)
     - [ ] 📄 [Help beginners to learn on MDN\!](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/help_beginners/index.html)
     - [ ] 📂 __['MDN web docs: How\-to guides'](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/index.html)__ (🌐 [Руководства "Как сделать"](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/howto/index.html))
       - [ ] 📄 [How to add or update browser compatibility data](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/add_or_update_browser_compatibility_data/index.html) (🌐 [Как добавить или обновить данные о браузерной совместимости](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/howto/add_or_update_browser_compatibility_data/index.html))
       - [ ] 📄 [How to convert code samples to be "live"](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/convert_code_samples_to_be_live/index.html) (🌐 [Как "оживить" примеры кода](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/howto/convert_code_samples_to_be_live/index.html))
       - [ ] 📂 __[How to create an interactive learning exercise](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/create_an_interactive_exercise_to_help_learning_the_web/index.html)__ (🌐 [Как создать интерактивное обучающее упражнение](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/howto/create_an_interactive_exercise_to_help_learning_the_web/index.html))
         - [ ] 📄 [distant example](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/create_an_interactive_exercise_to_help_learning_the_web/distant_example/index.html)
       - [ ] 📄 [How to create and edit pages](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/create_and_edit_pages/index.html) (🌐 [Как создавать и редактировать страницы](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/howto/create_and_edit_pages/index.html))
       - [ ] 📄 [How to document a CSS property](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/document_a_css_property/index.html)
       - [ ] 📄 [How to document an HTTP header](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/document_an_http_header/index.html)
       - [ ] 📄 [How to document web errors](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/document_web_errors/index.html)
       - [ ] 📄 [How to migrate external content to MDN Web Docs](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/migrate_external_content_to_mdn/index.html)
       - [ ] 📄 [How to report a problem on MDN](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/report_a_problem/index.html) (🌐 [Как сообщить о проблеме в MDN](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/howto/report_a_problem/index.html))
       - [ ] 📄 [How to properly tag pages](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/tag/index.html)
       - [ ] 📄 [How to update the CSS JSON DB](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/update_the_css_json_db/index.html)
       - [ ] 📄 [How to write and reference an entry in the glossary](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/write_a_new_entry_in_the_glossary/index.html) (🌐 [Как создавать записи в глоссарии и как на них ссылаться](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/howto/write_a_new_entry_in_the_glossary/index.html))
       - [ ] 📂 __[How to write an API reference](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/write_an_api_reference/index.html)__
         - [ ] 📄 [Information contained in a WebIDL file](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/write_an_api_reference/information_contained_in_a_webidl_file/index.html)
         - [ ] 📄 [API reference sidebars](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/write_an_api_reference/sidebars/index.html)
       - [ ] 📄 [How to write with SEO in mind on MDN Web Docs](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/howto/write_for_seo/index.html)
     - [ ] 📄 [Localizing MDN](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/localize/index.html)
     - [ ] 📄 [Basic etiquette for open source projects](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/open_source_etiquette/index.html)
     - [ ] 📂 __[Documentation processes](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/processes/index.html)__ (🌐 [Процессы документирования](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/contribute/processes/index.html))
       - [ ] 📄 [Triage process for MDN content bugs](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/processes/content_bug_triage/index.html)
       - [ ] 📄 [Matching web features to browser release version numbers](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/processes/matching_features_to_browser_version/index.html)
       - [ ] 📄 [MDN Workstream assessment and project setup process](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/processes/workstream_assessment_project/index.html)
     - [ ] 📄 [Where is everything on MDN? A guide to our repos](https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/where_is_everything/index.html)
   - [ ] 📂 __[Guidelines](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/index.html)__ (🌐 [Руководства](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/guidelines/index.html))
     - [ ] 📂 __[Code example guidelines](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/code_guidelines/index.html)__
       - [ ] 📄 [CSS guidelines](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/code_guidelines/css/index.html)
       - [ ] 📄 [General guidelines for all code](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/code_guidelines/general/index.html)
       - [ ] 📄 [HTML guidelines](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/code_guidelines/html/index.html)
       - [ ] 📄 [JavaScript guidelines](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/code_guidelines/javascript/index.html)
       - [ ] 📄 [Shell prompt guidelines](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/code_guidelines/shell/index.html)
     - [ ] 📄 [MDN conventions and definitions](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/conventions_definitions/index.html)
     - [ ] 📄 [Guide to classes and styles used in MDN content](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/css_style_guide/index.html)
     - [ ] 📄 [Does this belong on MDN Web Docs?](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/does_this_belong_on_mdn/index.html)
     - [ ] 📄 [Editorial policies](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/editorial/index.html)
     - [ ] 📄 [Video content on MDN](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/video/index.html)
     - [ ] 📄 [Writing style guide](https://github.com/mdn/content/blob/main/files/en-us/mdn/guidelines/writing_style_guide/index.html)
   - [ ] 📄 [The MDN Content Kitchensink](https://github.com/mdn/content/blob/main/files/en-us/mdn/kitchensink/index.html)
   - [ ] 📂 __[MDN Product Advisory Board](https://github.com/mdn/content/blob/main/files/en-us/mdn/mdn_product_advisory_board/index.html)__
     - [ ] 📄 [Product Advisory Board Members](https://github.com/mdn/content/blob/main/files/en-us/mdn/mdn_product_advisory_board/members/index.html)
     - [ ] 📄 [Product Advisory Board Charter & Membership](https://github.com/mdn/content/blob/main/files/en-us/mdn/mdn_product_advisory_board/membership/index.html)
   - [ ] 📂 __[Document structures](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/index.html)__ (🌐 [Структуры документов](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/structures/index.html))
     - [ ] 📄 [Banners and notices](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/banners_and_notices/index.html)
     - [ ] 📄 [Code examples](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/code_examples/index.html)
     - [ ] 📄 [Compatibility tables and the browser compatibility data repository \(BCD\)](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/compatibility_tables/index.html)
     - [ ] 📄 [Live samples](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/live_samples/index.html) (🌐 [Live samples](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/structures/live_samples/index.html))
     - [ ] 📂 __[Using macros](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/macros/index.html)__
       - [ ] 📄 [Commonly\-used macros](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/macros/commonly-used_macros/index.html)
       - [ ] 📄 [Other macros](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/macros/other/index.html)
     - [ ] 📂 __[Page types](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/index.html)__
       - [ ] 📄 [API constructor subpage template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/api_constructor_subpage_template/index.html)
       - [ ] 📄 [API event handler subpage template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/api_event_handler_subpage_template/index.html)
       - [ ] 📄 [API event subpage template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/api_event_subpage_template/index.html)
       - [ ] 📄 [API landing page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/api_landing_page_template/index.html)
       - [ ] 📄 [API method subpage template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/api_method_subpage_template/index.html)
       - [ ] 📄 [API property subpage template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/api_property_subpage_template/index.html)
       - [ ] 📄 [API reference page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/api_reference_page_template/index.html)
       - [ ] 📄 [ARIA page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/aria_page_template/index.html)
       - [ ] 📄 [CSS property page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/css_property_page_template/index.html)
       - [ ] 📄 [CSS selector page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/css_selector_page_template/index.html)
       - [ ] 📄 [Glossary page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/glossary_page_template/index.html)
       - [ ] 📄 [HTML element page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/html_element_page_template/index.html)
       - [ ] 📄 [HTTP header page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/http_header_page_template/index.html)
       - [ ] 📄 [SVG element page template](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/page_types/svg_element_page_template/index.html)
     - [ ] 📄 [Quicklinks](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/quicklinks/index.html)
     - [ ] 📄 [Specification tables](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/specification_tables/index.html)
     - [ ] 📄 [Syntax sections](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/syntax_sections/index.html)
   - [ ] 📂 __[MDN tools](https://github.com/mdn/content/blob/main/files/en-us/mdn/tools/index.html)__ (🌐 [MDN tools](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/tools/index.html))
     - [ ] 📂 __[KumaScript](https://github.com/mdn/content/blob/main/files/en-us/mdn/tools/kumascript/index.html)__
       - [ ] 📄 [Troubleshooting KumaScript errors](https://github.com/mdn/content/blob/main/files/en-us/mdn/tools/kumascript/troubleshooting/index.html) (🌐 [Решение проблем с ошибками в KumaScript](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/tools/kumascript/troubleshooting/index.html))
     - [ ] 📄 [The MDN sample server](https://github.com/mdn/content/blob/main/files/en-us/mdn/tools/sample_server/index.html)
     - [ ] 📄 [Unsupported GET API](https://github.com/mdn/content/blob/main/files/en-us/mdn/tools/unsupported_get_api/index.html) (🌐 [URL\-суффиксы](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/tools/unsupported_get_api/index.html))
   - [ ] 📄 ["Yari: MDN's rendering platform"](https://github.com/mdn/content/blob/main/files/en-us/mdn/yari/index.html) (🌐 ['Kuma: вики\-платформа MDN'](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/yari/index.html))

**Comment by sashasushko** [comment]
Потихоньку начну сабж с первой страницы "About MDN Web Docs"

**Comment by sashasushko** [comment]
@myshov или ты уже начал?

**Comment by mpstv** [comment]
Я хотел бы начать актуализировать перевод подраздела "Contributing to MDN", если никто не против.
Начну со страницы "Getting started on MDN".

**Comment by myshov** [comment]
@sashasushko ох, сорян за паузу с ответом. Я повредил левую руку и сейчас не так продуктивен так как хотелось бы и поэтому не очень тут активен. Без проблем берите то, что хочется :)

**Comment by sashasushko** [comment]
@myshov да без б, поправляйтесь!

**Comment by SphinxKnight** [comment]
The MDN section was reorganized a while ago and the aforementioned tree has changed a lot.
As written in other PRs, I think using the dashboard to track would be more efficient:
![image](https://user-images.githubusercontent.com/2413436/235847587-e8fa28f1-27bd-483d-b414-cd43337836f8.png)
