### ISSUE TITLE
[ko] Issue with 'a' for Typo in translation, http/caching

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#296]
English 'a' typing was not deleted during translation.

#### origin

```html
<li>오류 응답: a {{HTTPStatus(404)}} (Not Found) 결과 페이지.</li>
```

---

#### change
```html
<li>오류 응답: {{HTTPStatus(404)}} (Not Found) 결과 페이지.</li>
```

**Comment by SphinxKnight** [comment]
Sorry, but this locale is currently frozen and changes/fixes are not currently accepted. Please see https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ and [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo.

**Comment by hochan222** [comment]
#519
