### ISSUE TITLE
Issue with "padding": Broken Link

### ISSUE THREAD

**Issue by vitortamberlini** [mdn/translated-content#2965]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/padding

The link of the 'Amostra' section in the Brazilian version is broken:

![image](https://user-images.githubusercontent.com/22197659/140325264-e740b73c-4391-4f59-9efc-2684554ac1b5.png)

![image](https://user-images.githubusercontent.com/22197659/140325303-e7291ae4-2aa4-4039-b89f-11a715d14b6e.png)

Link of the above image: 
`/pt-BR/docs/Web/CSS/padding/_sample_.Live_Sample.html`

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/css/padding`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS/padding
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/css/padding/index.html
* Last commit: https://github.com/mdn/translated-content/commit/db721fb507ce6855783e31af7ea84920f7af8ea1
* Document last modified: 2021-11-02T18:06:43.000Z

</details>

**Comment by Agexandro** [comment]
The same thing happens with hispanic and russian versions. Could I try to fix it in one commit?
