### ISSUE TITLE
Remove all mentions of EmbedTest262ReportResultsTable

### ISSUE THREAD

**Issue by peterbe** [mdn/translated-content#297]
See https://github.com/mdn/content/pull/3375/files

We need to replicate this on the translated content. Examples:

- [x] [ja](https://github.com/mdn/translated-content/blob/a4f49f9a14007bf65efdbe671d6383e8b233ac5b/files/ja/web/javascript/reference/global_objects/bigint/index.html#L286-L290)
- [x] [es](https://github.com/mdn/translated-content/blob/a4f49f9a14007bf65efdbe671d6383e8b233ac5b/files/es/web/javascript/reference/lexical_grammar/index.html#L647-L651)
- [x] [de](https://github.com/mdn/translated-content/blob/a4f49f9a14007bf65efdbe671d6383e8b233ac5b/files/de/web/javascript/reference/global_objects/globalthis/index.html#L86-L90)
- [x] [fr](https://github.com/mdn/translated-content/blob/a4f49f9a14007bf65efdbe671d6383e8b233ac5b/files/fr/web/javascript/reference/operators/nullish_coalescing_operator/index.html#L139-L143)
- [x] [zh-CN](https://github.com/mdn/translated-content/blob/a4f49f9a14007bf65efdbe671d6383e8b233ac5b/files/zh-cn/web/javascript/reference/statements/import.meta/index.html#L93-L97)

**Comment by peterbe** [comment]
Note that this shows up in inactive locales (e.g. Ukranien) too. So any help appreciated!

At the time of writing, I'm seeing 45 of these:
```
MOZILLA/MDN/translated-content  main ✔
▶ rg EmbedTest262ReportResultsTable | wc -l
      45
```

**Comment by tristantheb** [comment]
Hi @peterbe,

Do I also do the others locales in my PR?
The French, in any case, it's good, VSCode has only detected 4 pages ^^
