### ISSUE TITLE
unable to find any live code samples for "Examples" within /zh-CN/docs/Web/CSS/flex-wrap

### ISSUE THREAD

**Issue by zzz6519003** [mdn/translated-content#2976]
Live sample failed!

An error occurred trying to render this live sample. 
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find any live code samples for "Examples" within /zh-CN/docs/Web/CSS/flex-wrap

**Comment by SphinxKnight** [comment]
cf. https://github.com/mdn/translated-content/issues/2846
