### ISSUE TITLE
Issue with "Générateur de box-shadow": generator doesn't work with the french version of the site

### ISSUE THREAD

**Issue by tfleurant** [mdn/translated-content#2979]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Backgrounds_and_Borders/Box-shadow_generator

#### What information was incorrect, unhelpful, or incomplete?

The box-shadow generator doesn't work
![image](https://user-images.githubusercontent.com/77610437/140513201-7bf4ad47-061f-45b1-8728-b46a0a4309e5.png)

#### Specific section or headline?
None

#### What did you expect to see?
The box-shadow generator (it works correctly on the english version on the site)
 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/css/css_backgrounds_and_borders/box-shadow_generator`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/CSS_Backgrounds_and_Borders/Box-shadow_generator
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/css_backgrounds_and_borders/box-shadow_generator/index.md
* Last commit: https://github.com/mdn/translated-content/commit/675d0fa6cff42ff21f49b2fcd75a406aa27ef74c
* Document last modified: 2021-11-04T16:41:38.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour le rapport @tfleurant . Ce point va être réglé avec #2842. 
Je vais fusionner cette dernière afin de résoudre ce point et d'autres.
