### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by edwinm** [mdn/translated-content#3]
Page: https://developer.mozilla.org/nl/docs/Glossary/TCP

Misspelled word: belanrijk

Right word: belangrijk

**Comment by peterbe** [comment]
Localization efforts are currently in a "freeze" at the moment. https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/

**Comment by SphinxKnight** [comment]
Sorry, but Dutch is currently a frozen locale, and changes/fixes are not currently accepted. Please refer to the [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo.
