### ISSUE TITLE
Issue with "503 Service Unavailable": (short summary here please)

### ISSUE THREAD

**Issue by g-hakobyan** [mdn/translated-content#3044]
MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Status/503

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/http/status/503`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Status/503
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/http/status/503/index.html
* Last commit: https://github.com/mdn/translated-content/commit/3c104650ad548685155f19a10c1c4ff62d42ff14
* Document last modified: 2021-11-09T00:50:07.000Z

</details>

**Comment by SphinxKnight** [comment]
@g-hakobyan could you please give more details about the issue you are facing?
