### ISSUE TITLE
Issue with "Array.prototype.forEach()"

### ISSUE THREAD

**Issue by z4x3** [mdn/translated-content#3110]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

**Quote**
Modifying the array during iteration
forEach() does not make a copy of the array before iterating

```js
let words = ['one', 'two', 'three', 'four']
words.forEach(function(word) {
  console.log(word)
  if (word === 'two') {
    words.shift() //'one' will delete from array
  }
}) // one // two // four

console.log(words);  //['two', 'three', 'four']
```

however, when i was running those code below，i was a little confused about  "
forEach() does not make a copy of the array before iterating"
copy here means deep copy?

```js

var words = ['one', 'two', 'three', 'four'];
words.forEach(function(word) {
// Not 'one', 'two', 'three', 'four', 'five' But got 'one', 'two', 'three', 'four'
  console.log(word);  //  'one',  'two',  'three', 'four'
  if (word === 'two') {
    words.push('five');
  }
});
```

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/array/foreach`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/array/foreach/index.html
* Last commit: https://github.com/mdn/translated-content/commit/555ecf9a9ca12b13e2d0ea9b94037a608037bec7
* Document last modified: 2021-11-15T21:45:00.000Z

</details>

**Comment by joacycode** [comment]
I seem to understand that this description is still a little confusing.

'Foreach' Instead of creating a copy of the array, the original array is queried.

Note that changing the array in the loop changes the output, but adding elements does not change the print length.

The array length is copied by value before the loop, so the loop length does not change and the added elements are not looped in, but changing elements within the original length can cause side effects.

**Comment by yin1999** [comment]
> I seem to understand that this description is still a little confusing.
> 
> 'Foreach' Instead of creating a copy of the array, the original array is queried.
> 
> Note that changing the array in the loop changes the output, but adding elements does not change the print length.
> 
> The array length is copied by value before the loop, so the loop length does not change and the added elements are not looped in, but changing elements within the original length can cause side effects.

The **original** array is used for `forEach` function. The reason why the _callback_ is only called for 4 times is that the number of elements to visit is determined before the first call of _callback_ . Reference: [array.prototype.foreach](https://262.ecma-international.org/6.0/#sec-array.prototype.foreach).

You can try the following code:

```js
let arr = [1,2,3,4,5]

arr.forEach(value => {
	console.log(value)  // 1, 2, 6, 4, 5
	if (value == 2) {
		arr[2] = 6
	}
})
```
