### ISSUE TITLE
“Using_templates_and_slots” live example dead in French translation

### ISSUE THREAD

**Issue by Zlitus** [mdn/translated-content#3117]
MDN URL: https://developer.mozilla.org/fr/docs/Web/Web_Components/Using_templates_and_slots

#### What information was incorrect, unhelpful, or incomplete?
Live sample failed!

#### Specific section or headline?
Utiliser l'élément element-details avec les emplacements nommés

#### What did you expect to see?
A live-code example of `<template>` and `slots`

#### What did you get?
> Live sample failed!
> An error occurred trying to render this live sample. 
> Consider filing an issue or trying your hands at a fix of your own.
> Error details:
> KumascriptError: unable to find any live code samples for "exemple_complet" within /fr/docs/Web/Web_Components/Using_templates_and_slots

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/web_components/using_templates_and_slots`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/Web_Components/Using_templates_and_slots
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/web_components/using_templates_and_slots/index.md
* Last commit: https://github.com/mdn/translated-content/commit/a80467971851f86156df1e858cab699804ba235b
* Document last modified: 2021-11-14T16:41:16.000Z

</details>

**Comment by SphinxKnight** [comment]
@Zlitus thanks for the report. This should be fixed by https://github.com/mdn/translated-content/pull/3115
