### ISSUE TITLE
Issue with "Closures (Fermetures)": 404 error on jsfiddle iframe

### ISSUE THREAD

**Issue by houd** [mdn/translated-content#3127]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Closures

#### What information was incorrect, unhelpful, or incomplete?
One of the jsfiddle iframe doesn't exist anaymore: https://jsfiddle.net/vnkuZ/7726embedded/js,result/
404 error displayed

#### Specific section or headline?
"Les fermetures en pratique"

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/closures`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Closures
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/closures/index.md
* Last commit: https://github.com/mdn/translated-content/commit/555ecf9a9ca12b13e2d0ea9b94037a608037bec7
* Document last modified: 2021-11-15T21:45:00.000Z

</details>

**Comment by houd** [comment]
The english page has a direct link (https://jsfiddle.net/vnkuZ/7726/) instead of an iframe
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures

**Comment by SphinxKnight** [comment]
Thanks for the report @houd, this should be fixed w/ #3130
