### ISSUE TITLE
× Unhandled Rejection (TypeError): Converting circular structure to JSON     --> starting at object with constructor 'HTMLImageElement'     |     property '__reactFiber$4oc26ipys13' -> object with constructor 'FiberNode'     --- property 'stateNode' closes the circle

### ISSUE THREAD

**Issue by Vira-Svirgun** [mdn/translated-content#3138]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/javascript/reference/errors/cyclic_object_value`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/errors/cyclic_object_value/index.html
* Last commit: https://github.com/mdn/translated-content/commit/cdb7f553ec9ac8ed2734be6b155171e3ffb98cf4
* Document last modified: 2021-11-17T21:30:54.000Z

</details>

**Comment by SphinxKnight** [comment]
@Vira-Svirgun hello, could you please give some more details about what is wrong with the content of this page?
