### ISSUE TITLE
Content suggestion: <I want to create JP page of https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/javascript>

### ISSUE THREAD

**Issue by yukitomeow** [mdn/translated-content#3141]
## What is the new suggestion?
 I will create Japanese  translation of this page.  (https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/javascript)

## Why is it important or useful?
 This is one single page project and it will take few weeks.

**Comment by SphinxKnight** [comment]
@yukitomeow I'm closing this one since it's not active. Do not hesitate to provide a pull request :)
