### ISSUE TITLE
一个小小的疑问

### ISSUE THREAD

**Issue by dqh78** [mdn/translated-content#3152]
例如，要读取图片中位于第50行，第200列的像素的蓝色部份，你会写以下代码：

blueComponent = imageData.data[((50 * (imageData.width * 4)) + (200 * 4)) + 2];

就这边是50还是49啊 !(・∀・(・∀・(・∀・*)

**Comment by SphinxKnight** [comment]
Hello @dqh78, could you please give the link of the page where you encountered this issue?

**Comment by dqh78** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas

**Comment by dqh78** [comment]
> Hello @dqh78, could you please give the link of the page where you encountered this issue?
https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/Tutorial/Pixel_manipulation_with_canvas

**Comment by btea** [comment]
@dqh78 应该是49

**Comment by fish-404** [comment]
> If given a set of coordinates (X and Y), you may end up doing something like this:
按照英文的此段后面给的公式，这里应该是指坐标吧

**Comment by CG-lightyear** [comment]
> dqh78

为什么我也觉得是49，谁能给我解释一下。
