### ISSUE TITLE
Issue with "drop-shadow()": (obsolete thus misleading warning about browser incompatibility)

### ISSUE THREAD

**Issue by anarkhya** [mdn/translated-content#3154]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/filter-function/drop-shadow()

#### What information was incorrect, unhelpful, or incomplete?
Incorrect. The EN source mentions almost full browser compatibility (except IE) for this function while the FR translation specifies that only Firefox can handle it.

#### Specific section or headline?
Browser compatibility

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/css/filter-function/drop-shadow()`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/filter-function/drop-shadow()
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/filter-function/drop-shadow()/index.md
* Last commit: https://github.com/mdn/translated-content/commit/a5b09a061d027cfb68ccf3ff2454e319f9bb9903
* Document last modified: 2021-11-19T23:56:01.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour ce rapport @anarkhya ! Je vais pousser une PR qui remet à jour l'ensemble des sous pages de filter-function. En effet toutes celles-ci semblent manquer à l'appel pour ce qui est des tableaux de compatibilité et de spécifications à jour.
