### ISSUE TITLE
Issue with "Element : évènement mousemove": the example gives an incorrect result !

### ISSUE THREAD

**Issue by 1produdev** [mdn/translated-content#3196]
MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Element/mousemove_event

#### What information was incorrect, unhelpful, or incomplete?
Since yesterday, the example gives an incorrect result on Firefox and work with Edge. 
I have some programs who have the same issue.

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/api/element/mousemove_event`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Element/mousemove_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/element/mousemove_event/index.md
* Last commit: https://github.com/mdn/translated-content/commit/4ebead42b03a8b0846acba93ebbffc125cf6295e
* Document last modified: 2021-11-22T15:21:05.000Z

</details>

**Comment by SphinxKnight** [comment]
@1produdev what is the exact issue you're facing and is it only happening for the French page's example?
I'm using Firefox release on Windows and don't have any issue here.

**Comment by 1produdev** [comment]
Sorry I changed the browser zoom, there no issue.
