### ISSUE TITLE
Issue with "HTTP/Headers/Cache-Controlの翻訳"

### ISSUE THREAD

**Issue by sakit0** [mdn/translated-content#3200]
## What information was incorrect, unhelpful, or incomplete?
次のPRでHTTP/Headers/Cache-Controlのページが大幅に更新されたので、日本語訳をする
https://github.com/mdn/content/pull/10027

## Specific section or headline?
Cache-Control

## What did you expect to see?
英語の翻訳

**Comment by sakito21** [comment]
よければ翻訳させていただきたいです

**Comment by Jxck** [comment]
Cool 👍 It's so wonderful to have up-to-date translate.
I'm author of original english content and happy to review it !

**Comment by SphinxKnight** [comment]
seems fixed w/ https://github.com/mdn/translated-content/pull/3478, let me know if I should reopen it.

**Comment by mfuji09** [comment]
完了しているようなので、閉じます。
