### ISSUE TITLE
Issue with "Array.prototype.concat()": (short summary here please)

### ISSUE THREAD

**Issue by EnzoParis** [mdn/translated-content#3205]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/concat#paramètres

#### What information was incorrect, unhelpful, or incomplete?
Si tous les arguments valeurN valent undefined, concat renverra une copie superficielle du tableau sur lequel elle est appelée. Voir ci-après pour plus de détails.

#### Specific section or headline?
Syntaxe > Paramètres > valeurNFacultatif

#### What did you expect to see?
Si aucun argument valeurN n'est passé, concat renverra une copie superficielle du tableau sur lequel elle est appelée. Voir ci-après pour plus de détails.

#### Did you test this? If so, how?
[1].concat(undefined) return [1, undefined] and not [1]
[1].concat() return [1]

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/array/concat`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/concat
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/array/concat/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b83337c7cf726c88a5909433b1a996f6b571ae75
* Document last modified: 2021-11-25T11:11:19.000Z

</details>

**Comment by SphinxKnight** [comment]
@EnzoParis Merci pour ce retour, souhaitez-vous corriger en apportant une pull request sur ce dépôt ? https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/array/concat/index.md 

(il s'agit d'une simple proposition, je m'occuperai d'une telle PR si besoin :))

**Comment by Groangfr** [comment]
> URL MDN: [https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/concat#paramètres](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/concat#param%C3%A8tres)
> 
> #### Thông tin nào không chính xác, không hữu ích hoặc không đầy đủ?
> Si tous les đối số valeurN valent undefined, concat renverra une copie super inheritelle du tableau sur lequel elle est appelée. Voir ci-après pour cộng với de détails.
> 
> #### Phần cụ thể hoặc tiêu đề?
> Cú pháp> Paramètres> valeurNFacultatif
> 
> #### Bạn đã mong đợi để xem những gì?
> Si aucun lập luận valeur Voir ci-après pour cộng với de détails.
> 
> #### Bạn đã kiểm tra điều này? Nếu vậy, làm thế nào?
> [1] .concat (không xác định) trả về [1, không xác định] và không phải [1] [1] .concat () trả về [1]
> 
> MDN Chi tiết báo cáo trang nội dung
