### ISSUE TITLE
Issue with "Типы данных JavaScript и структуры данных": (short summary here please)

### ISSUE THREAD

**Issue by Nichon4** [mdn/translated-content#3226]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Data_structures

#### What information was incorrect, unhelpful, or incomplete?

Количество типов не сходится с английской версией страницы. Информация кажется более полной, но где правда?

#### Specific section or headline?

https://developer.mozilla.org/ru/docs/Web/JavaScript/Data_structures#%D1%82%D0%B8%D0%BF%D1%8B_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#javascript_types

**Comment by myshov** [comment]
@Nichon4 спасибо! Проблема была исправлена здесь https://github.com/mdn/translated-content/pull/3924
