### ISSUE TITLE
Issue with "Unsigned right shift (>>>)": (short summary here please)

### ISSUE THREAD

**Issue by guoxuemei** [mdn/translated-content#3228]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Unsigned_right_shift

#### What information was incorrect, unhelpful, or incomplete?
const c = -5;         // -00000000000000000000000000000101
the Binary representation of -5 maybe not correct
it should be 11111111111111111111111111111010
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/operators/unsigned_right_shift`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Unsigned_right_shift
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/operators/unsigned_right_shift/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d897f0858d3fbe6d46a69481c604b58476d83597
* Document last modified: 2021-11-29T15:47:48.000Z

</details>

**Comment by yin1999** [comment]
Related to another mdn repo, you can report a issue with this [live-sample](https://github.com/mdn/interactive-examples/blob/main/live-examples/js-examples/expressions/expressions-unsigned-right-shift-assignment.js).

**Comment by yin1999** [comment]
@SphinxKnight This issue has been fixed via: mdn/interactive-examples#2059
