### ISSUE TITLE
Issue with "Firefox 开发者工具": (short summary here please)

### ISSUE THREAD

**Issue by anders-sm** [mdn/translated-content#3232]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Tools

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/tools`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Tools
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/tools/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d897f0858d3fbe6d46a69481c604b58476d83597
* Document last modified: 2021-11-29T15:47:48.000Z

</details>

**Comment by SphinxKnight** [comment]
@anders-sm please give more details about the issue
