### ISSUE TITLE
Issue with "浏览器的同源策略": (localStorage link not found)

### ISSUE THREAD

**Issue by yuanqihang-123** [mdn/translated-content#3247]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Security/Same-origin_policy

#### What information was incorrect, unhelpful, or incomplete?
localStorage link not found.

#### Specific section or headline?
this is the link to highLight: https://developer.mozilla.org/zh-CN/docs/Web/Security/Same-origin_policy#:~:text=%E8%AE%BF%E9%97%AE%E5%AD%98%E5%82%A8%E5%9C%A8%E6%B5%8F%E8%A7%88%E5%99%A8%E4%B8%AD%E7%9A%84%E6%95%B0%E6%8D%AE%EF%BC%8C%E5%A6%82%C2%A0localStorage%C2%A0%E5%92%8C%C2%A0IndexedDB%EF%BC%8C%E6%98%AF%E4%BB%A5%E6%BA%90%E8%BF%9B%E8%A1%8C%E5%88%86%E5%89%B2%E3%80%82%E6%AF%8F%E4%B8%AA%E6%BA%90%E9%83%BD%E6%8B%A5%E6%9C%89%E8%87%AA%E5%B7%B1%E5%8D%95%E7%8B%AC%E7%9A%84%E5%AD%98%E5%82%A8%E7%A9%BA%E9%97%B4%EF%BC%8C%E4%B8%80%E4%B8%AA%E6%BA%90%E4%B8%AD%E7%9A%84%20JavaScript%20%E8%84%9A%E6%9C%AC%E4%B8%8D%E8%83%BD%E5%AF%B9%E5%B1%9E%E4%BA%8E%E5%85%B6%E5%AE%83%E6%BA%90%E7%9A%84%E6%95%B0%E6%8D%AE%E8%BF%9B%E8%A1%8C%E8%AF%BB%E5%86%99%E6%93%8D%E4%BD%9C%E3%80%82

#### What did you expect to see?
The correct content of localStorage introduction.

#### Did you test this? If so, how?
No.

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/security/same-origin_policy`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Security/Same-origin_policy
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/security/same-origin_policy/index.html
* Last commit: https://github.com/mdn/translated-content/commit/10bd926d9da3c32a9cb4442d5e8a8157fc6d1d75
* Document last modified: 2021-12-02T00:11:03.000Z

</details>

**Comment by yin1999** [comment]
@cw118 It seems fixed.
