### ISSUE TITLE
Issue with "Débogueur": French translation states that debugger can edit code. Should be state.

### ISSUE THREAD

**Issue by Altrue** [mdn/translated-content#3269]
MDN URL: https://developer.mozilla.org/fr/docs/Tools/Debugger

#### What information was incorrect, unhelpful, or incomplete?
The first sentence of the french translation is: "Le débogueur JavaScript permet d'avancer pas à pas dans du code JavaScript **et de l’examiner ou de le modifier**, afin de retrouver et de corriger les bugs."

Whereas the english original is: "The JavaScript Debugger enables you to step through JavaScript code and **examine or modify its state** to help track down bugs."

The notion of "state" is completely absent from the french version, which says: "... in JavaScript code and examine or modify it, in order to...". Without this notion of state, the subject of "examine" and, more importantly "modify" is the JavaScript code itself, which is incorrect.

#### Specific section or headline?
The first sentence of the page.

#### What did you expect to see?
In french, I expected to see that the JavaScript Debugger only allows to act on the *state* and not the *code* itself.

#### Did you test this? If so, how?
By pressing F12 and going into the debugger tab, then finding a JavaScript file, it's quickly obvious that the file is in read-only.

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/tools/debugger`
* MDN URL: https://developer.mozilla.org/fr/docs/Tools/Debugger
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/tools/debugger/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a81cea7d8b08d1765dcc5ea62e6238dd1d596a05
* Document last modified: 2021-12-03T18:38:15.000Z

</details>

**Comment by SphinxKnight** [comment]
fixed w/ #3277
