### ISSUE TITLE
Images missing or not displaying on French pages

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3288]
## La page *Flexbox - Apprendre le développement web*

La version française de la page sur Flexbox n'affiche pas les images (on ne voit que le texte alternatif). Cette erreur se retrouve également dans toutes les versions non-anglaises avec l'image **flex_terms.png** (celle-ci a été transférée à #3294).

- Aucune image n'est affichée ici : https://developer.mozilla.org/fr/docs/Learn/CSS/CSS_layout/Flexbox

Par ailleurs, quelques images ont été ajoutées à la page sur Flexbox en anglais (https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox) depuis la dernière révision de la version française, dont les suivantes si je ne me trompe pas :
- bih741v.png
- flexbox_center_space-around.png
- flexbox_first-child_flex-end.png
- flexbox-example7.png (je crois que ce fichier devrait être nommé flexbox-example**6**.png, au moins en anglais)

Il y a aussi deux images avec le même attribut `src`, **Exemple_flexbox_1.png**

**Comment by cw118** [comment]
Même problème ici avec **grille.png** (le texte alt est *Schéma du quadrillage*) : https://developer.mozilla.org/fr/docs/Learn/CSS/CSS_layout/Grids

**Comment by SphinxKnight** [comment]
> Présentement je ne connais pas très bien le fonctionnement des dépôts _content_ et _translated-content_ (je suis en train de l'apprendre), alors je ne sais pas trop comment aborder le problème, mais je serais ravie de vous aider avec cette issue. Serait-il suffisant d'ajouter les images manquantes aux dossiers correspondants et, au besoin, de modifier les noms de fichiers ? En tout cas, merci pour votre temps et votre travail acharné !

Pour réutiliser les images qui sont présentes dans l'article anglophone, il suffit d'avoir un lien qui pointe vers le même fichier. Si on veut avoir la même image qu'en en-US, il n'est pas nécessaire d'avoir le fichier dans le répertoire de la page dans le dépôt mdn/translated-content (cela évite de dupliquer les fichiers dans les différentes locales :) )

Si on veut avoir des images différentes (par exemple une version localisée), alors dans ce cas, il faudra bien le fichier dans le répertoire de la page.
En espérant que ça réponde aux questions :) 
J'ai rédigé #3330 pour corriger tout ça !

**Comment by cw118** [comment]
> En espérant que ça réponde aux questions :) J'ai rédigé #3330 pour corriger tout ça !

Ah, je vois. Merci pour tout @SphinxKnight !
