### ISSUE TITLE
Typo and missed translation on Russian TypeError page

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3333]
## What page(s) did you find the problem on?

The Russian "TypeError: cyclic object value" page: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Errors/Cyclic_object_value

## What is the problem?

- I believe the page title is meant to be "TypeError: cyclic object value". It is currently the following:

  > TypeError: cyclic object value(TypeError: циклическое значение объекта)

- The "Что не так?" section has not been translated from English.

**Comment by unsky559** [comment]
Closed your issue at #4828. Thank you @cw118
