### ISSUE TITLE
Issue with "Métodos úteis de string": (has an grammar error in portuguese translation)

### ISSUE THREAD

**Issue by lord-kraze** [mdn/translated-content#3364]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Useful_string_methods

Headline in portuguese: "Encontrando uma substring dentro de uma string e extraindo-a"

in the paragraph, in portuguese has an simple error:
"Às vezes você quer **sabe** se"
it's an "r" letter missing in the end of this word above in bold.

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/learn/javascript/first_steps/useful_string_methods`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/First_steps/Useful_string_methods
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/javascript/first_steps/useful_string_methods/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b70e1c5047a716aa587abd786a6aa1d197140f5d
* Document last modified: 2021-12-14T00:54:59.000Z

</details>

**Comment by cw118** [comment]
Thanks for reporting! This was fixed in #3610 :)
