### ISSUE TITLE
Issue with "<blend-mode>": no examples

### ISSUE THREAD

**Issue by MikeCley** [mdn/translated-content#3366]
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/blend-mode

#### What information was incorrect, unhelpful, or incomplete?
Examples are empty.

#### Specific section or headline?
https://yari-demos.prod.mdn.mozit.cloud/ru/docs/Web/CSS/blend-mode/_sample_.hard-light.html
that loaded in iframe on the page 
has no elements in body.

#### What did you expect to see?
Something like <div> or so.

#### Did you test this? If so, how?
No, just open in Chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/css/blend-mode`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/blend-mode
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/blend-mode/index.html
* Last commit: https://github.com/mdn/translated-content/commit/7a5b783d12cf1ef9553c06c3401155dfd6e67099
* Document last modified: 2021-12-14T12:48:52.000Z

</details>

**Comment by MikeCley** [comment]
Post form stole my "<div>". Is it allowed <> angle brackets in text?

**Comment by sashasushko** [comment]
Fixed https://developer.mozilla.org/en-US/docs/Web/CSS/blend-mode
