### ISSUE TITLE
Issue with "JavaScript": broken link to Async guide

### ISSUE THREAD

**Issue by titus0039** [mdn/translated-content#338]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript

#### What information was incorrect, unhelpful, or incomplete?

The link on "La programmation asynchrone en JavaScript" is broken (Sorry for french words).
The targeted page is showing this :
Page not found
Sorry, the page /fr/docs/Apprendre/JavaScript/Asynchrone could not be found.

Thanks, 

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/index.html
* Last commit: https://github.com/mdn/translated-content/commit/2a00cabaa3ac0f8ca257564858e72daed67e425d
* Document last modified: 2021-03-26T02:16:19.000Z

</details>

**Comment by tristantheb** [comment]
Hello @titus0039,

I take your issue to update all links of this page and create the missing sub-page :)
