### ISSUE TITLE
Fix \*\* occurrences after Markdown conversion in French

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#3389]
371 results in 179 files so far. An example: 
![image](https://user-images.githubusercontent.com/2413436/146632176-9a800460-4de1-460f-bf0f-d76790c74041.png)
Spotted by @cw118 https://github.com/mdn/translated-content/pull/3330#issuecomment-996435576

**Comment by cw118** [comment]
@SphinxKnight Is there any way I can help with this or with EmbedLiveSample errors?

**Comment by SphinxKnight** [comment]
> @SphinxKnight Is there any way I can help with this or with EmbedLiveSample errors?

If you have any idea on how to detect embedded pictures in EmbedLiveSample (I can think of a few ways but didn't take proper time so far), please do :)

Regarding this issue, I'll be opening a PR shortly.

**Comment by cw118** [comment]
> If you have any idea on how to detect embedded pictures in EmbedLiveSample (I can think of a few ways but didn't take proper time so far), please do :)

I'm unfortunately not the most familiar with how that works, but I'd still like to help in any way possible—is there anything I can read/learn to work on this?
