### ISSUE TITLE
Display issues in browsers other than Firefox

### ISSUE THREAD

**Issue by hiw-homepage** [mdn/translated-content#3395]
When _**content-box**_ is specified in the _**clip-path**_ property, it does not work in browsers other than **Firefox** (**Edge** and **Chrome**). The browser compatibility table only specifies fill-box and stroke-box, but shouldn't this be included as well? If the same thing happens outside of my environment, please fix it.

_By Google Translate_

**Comment by SphinxKnight** [comment]
@hiw-homepage could you indicate on which page you found this?

**Comment by hiw-homepage** [comment]
> @hiw-homepage could you indicate on which page you found this?

Below is the code.

[https://github.com/hiw-homepage/Display-issues-in-browsers-other-than-Firefox](url)

In my environment, I was able to clip with 25%, 50%, 25% in Firefox, but in Edge and Chrome it was displayed from end to end.

**Comment by SphinxKnight** [comment]
I was referring to the MDN page where you found the compatibility data (since this repository is about MDN content and not CSS implementations ^^)

**Comment by hiw-homepage** [comment]
The syntax was incorrect. I will correct it below.

[GitHub repository](https://github.com/hiw-homepage/Display-issues-in-browsers-other-than-Firefox)

**Comment by hiw-homepage** [comment]
Do you mean the table below? (Image)

[Google Drive](https://drive.google.com/file/d/14yd5WO_rpMHn8R0E7uWxjHdGXalNhXDz/view?usp=sharing)

[MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path)

**Comment by cw118** [comment]
@hiw-homepage Looking at the browser compatibility table, there is a row with compatibility data for `fill-box` and `stroke-box` (cf. the last row of the table in the image below).

![](https://user-images.githubusercontent.com/87150472/176771463-cc561ebc-b3e4-4f02-a08b-f4b0db4a2190.png)

In the future, if you find issues on English MDN pages (en-US), please open an issue on the [`mdn/content`](https://github.com/mdn/content) repository, or on [`mdn/browser-compat-data`](https://github.com/mdn/browser-compat-data) if there are problems with compatibility data.

Thanks for reporting :)
