### ISSUE TITLE
Learning Area - Flexbox layout article needs typofixes and update (French)

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#3397]
As noted by @cw118, there are a bunch of issues on this page

- Typofix/language:
  - çad (instead of « c'est-à-dire ») 
    - https://github.com/mdn/translated-content/blob/main/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L91
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L156
  - Triple curly brackets `}}}` on
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L93
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L156
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L186
  - Typo (conjugation)
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L323
  - Canonical "English" slugs for `PreviousMenuNext`
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L348https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L348

- Content update needed (vs en-US)
  - Code samples with `flex: 1` (out of date in fr) instead of `flex: 1 auto` (in en-US)
  -  https://github.com/mdn/content/blob/05e13479df2f318cc5a02ed0a817dff914803beb/files/en-us/learn/css/css_layout/flexbox/index.md?plain=1#L329-L336 vs https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/flexbox/index.md?plain=1#L325-L332
  - Missing "Test your skills" part
    -  https://github.com/mdn/content/blob/05e13479df2f318cc5a02ed0a817dff914803beb/files/en-us/learn/css/css_layout/flexbox/index.md?plain=1#L348-L350 (N.B. since this depends on another page, feel free to open another issue if needed)

- I'm not counting asterisk escaping markdown conversion bug since it's adressed in #3394

**Comment by SphinxKnight** [comment]
@cw118 if you want to tackle this one, please do :) if you can't / don't want to or need help doing so, let me know

**Comment by cw118** [comment]
> @cw118 if you want to tackle this one, please do :)

I'd love to :)
