### ISSUE TITLE
Learning Area - Grid layout article needs typofixes and update (French)

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#3398]
As noted by @cw118 on #3330, there a bunch of issues on https://github.com/mdn/translated-content/blob/main/files/fr/learn/css/css_layout/grids/index.md

- Typofix:
  - links with "French" slugs
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/grids/index.md?plain=1#L25-L46
  - duplicate code block
    -  https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/grids/index.md?plain=1#L113-L118 (already appears in L76-L81)
  - non hidden HTML fragment (vs en-US counterpart)
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/grids/index.md?plain=1#L221-L231
  - Missing dash and backticks
    -  https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/grids/index.md?plain=1#L235 for "_`-\*gap`_ properties"
  - Extra spaces
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/grids/index.md?plain=1#L262
  - Typo "cahine" > "chaîne"
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/grids/index.md?plain=1#L262

- Content update
  - obsolete properties mentioned in "Espaces entre pistes" 
    - https://github.com/mdn/translated-content/blob/9efbf5afbf1239289f43a9939f07005aff58ea6d/files/fr/learn/css/css_layout/grids/index.md?plain=1#L184-L187

**Comment by cw118** [comment]
I'd be happy to work on this, though I'm assuming I should wait for #3330 to be merged first to avoid conflicts? 

And a few notes to self (or to whoever may end up working on the issue):
- I didn't get to scan the entire page/file, so I may have missed some typos/needed updates further down
- There are a few missing and extra spaces here and there that I hadn't felt the need to comment on at the time, but it'd probably be best if these were all corrected in the same PR
