### ISSUE TITLE
Issue with "Tools and testing": (short summary here please)

### ISSUE THREAD

**Issue by Ultras82** [mdn/translated-content#3409]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/Tools_and_testing

#### What information was incorrect, unhelpful, or incomplete?
Russian translation does not work

#### Specific section or headline?
The entire section "Tools and Testing"

#### What did you expect to see?
After clicking the "change language" button and choosing the Russian language, the text of the "Tools and Testing" section should be displayed in Russian.

#### Did you test this? If so, how?
After clicking the "change language" button and choosing the Russian language, the text of the "Tools and Testing" section remains in English.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/learn/tools_and_testing`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/Tools_and_testing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/tools_and_testing/index.html
* Last commit: https://github.com/mdn/translated-content/commit/aee22e976f8a4b66388c689c0e9b1bb873209e2b
* Document last modified: 2021-12-20T00:28:12.000Z

</details>

**Comment by AnilSeervi** [comment]
I'm guessing the content of the page needs to translated
It's still in english - https://github.com/mdn/translated-content/blob/main/files/ru/learn/tools_and_testing/index.html

**Comment by sashasushko** [comment]
Yep, this page not translated yet.
