### ISSUE TITLE
Issue with "CSSStyleDeclaration.setProperty()": (short summary here please)

### ISSUE THREAD

**Issue by BuslikDrev** [mdn/translated-content#3438]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleDeclaration/setProperty

Chrome 96
```
<style>
body {
	content: 'blue';
}
</style>
<script>
window.addEventListener('load', function() {
	var element = document.styleSheets[0].cssRules[0].style;
	console.log(element.cssText);
	//element.removeProperty('content');          // working
	//element.setProperty('content', 'url(red)'); // working
	element.setProperty('content', 'red');        // does not work
	element.setProperty('color', 'red');          // working
	console.log(element.cssText);

	console.log(1 + ' ' + element.getPropertyValue('content'));
	/* fix */
	element.setProperty('content', 'url(fixredfix)');
	element.cssText = element.cssText.replace(/\burl\(\"fix(.[^\)]*?)fix\"\)/, '"$1"');
	/* fix */
	console.log(element.cssText);
	console.log(2 + ' ' + element.getPropertyValue('content'));
});
</script>
```

**Comment by SphinxKnight** [comment]
@BuslikDrev could you please give some more details about the issue you are facing?

**Comment by BuslikDrev** [comment]
> @BuslikDrev could you please give some more details about the issue you are facing?
element.setProperty('content', 'url(...)'); accepts only url(...), but does not accept text.
For example, you cannot replace the font-awesome icon .fa-cloud-sun: before {content: "\f6c4"}

In the case of the icon, the second problem also arises, instead of "\f6c4" the symbol will be displayed.

**Comment by SphinxKnight** [comment]
This repository is about MDN content itself, could you point to an MDN page / URL where the documentation is misleading?

**Comment by SphinxKnight** [comment]
how is this related to the content of the MDN page? I'm not sure I understand if this is an error in the MDN page or not? (if not, this should be closed)

**Comment by yin1999** [comment]
It seems working, but we need to add qoutes (as `'"123"'`) see below:

![image](https://user-images.githubusercontent.com/15844309/212306048-8a1c5d07-4264-4e35-830b-2c0a0c507ecc.png)

I'm going to close this issue. And if you have any other problem, feel free to append in this thread :)
