### ISSUE TITLE
Перевод термина "media feature"

### ISSUE THREAD

**Issue by myshov** [mdn/translated-content#344]
Пока делал правки в https://github.com/mdn/translated-content/pull/343, понял, что надо также нужно унифицировать перевод "media feature". Сейчас оно иногда переводится как "медиа-функция" или иногда оставлюят без перевода, возможно, что еще есть варианты (не нашёл).

При этом мы договорились использовать глоссарий веб-стандартов там "media feature" переводится как "характеристика устройства". Мне кажется это не очень корректным переводом, так как характеристикой устройства может быть всё что угодно и вес, и тип корпуса, что не имеет никакого отношения к CSS :)

Также мы вроде бы договорились использовать перевод "feature" как "возможность", но имхо "медиавозможность" звучит не очень привычно.

@lex111 @Saionaro @sashasushko @captainspring @mpstv @mirexdoors на каком переводе остановимся?

* хараткеристика устройства
* медиавозможность
* медифича
* медиафункция
* другое (предложить в комментариях)

**Comment by Saionaro** [comment]
Медиапараметр?

Ведь технически, каждая **media feature** - это некое свойство (чаще всего) экрана устройства. Иными словами, параметр (или таки характеристика).

`Медиазапрос может состоять из необязательного _типа устройства_ и/или набора медиапараметров.`

Однако при таком подходе придется также менять и перевод **media type**, так как будет выбиваться из строя:
- медиазапрос
- _тип устройства_
- медиапараметр

**Comment by mpstv** [comment]
Сложный вопрос. 

Вариант веб-стандартов "характеристика устройства" хорошо отражает суть, но от огигинального названия "media feature" он достаточно сильно отличается.

Я бы предложил либо придерживаться варианта веб-стандартов, либо использовать англицизм "медиафича", чтобы не увеличивать количество терминов.

**Comment by lex111** [comment]
Хорошо бы привести пример, где используется этот термин, чтобы лучше понять. Вообще можно "медиахарактеристика" использовать.

**Comment by myshov** [comment]
Несколько примеров использования. Нашёл [тут]()

> Media features describe the specific characteristics of a given user agent, output device, or environment

> Many media features are range features, which means they can be prefixed with "min-" or "max-" to express "minimum condition" or "maximum condition" constraints

> If a feature doesn't apply to the device on which the browser is running, expressions involving that media feature are always false

**Comment by myshov** [comment]
Мне на данный момент нравятся три варианта

* медиапараметр
* медиахарактеристика
* медиавозможность

**Comment by myshov** [comment]
@Saionaro 

> Однако при таком подходе придется также менять и перевод media type, так как будет выбиваться из строя

Имхо тогда можно использовать "медиатип"

**Comment by lex111** [comment]
> Имхо тогда можно его переводить как "медиатип

Да, лучше так, и тогда "медиахарактеристика", чтобы быть ближе к оригиналу.

**Comment by captainspring** [comment]
Мне и параметр, и характеристика ок звучат.

А мы все их пишем в одно слово, без дефиса?
Гугл вот говорит мне, что по запросу «медиа-запрос» ~6млн результатов, а по запросу «медиазапрос» — ~1млн. 
Да и если брать характеристику, то _медиахарактеристика_ — очень длинное слово, сложно читается и воспринимается. Если разбить его дефисом, как составное сложное слово: медиа-характеристика — будет попроще читать.

**Comment by myshov** [comment]
Нашёл много статей, которые говорят о том, что дефис после "медиа" исопльзовать не нужно

**Comment by sashasushko** [comment]
Мне ок "характеристика устройства", потому что слово "медиа" ни о чём не говорит. Да,  характеристикой устройства может быть всё что угодно: и вес, и тип корпуса. Но замена слова "устройсво" на "медиа" ближе это определение к CSS не делает.

**Comment by myshov** [comment]
Я не думаю, что кто-то использует перевод в реальной жизни. Например, я никогда не сылшал, чтобы его использовали в разговорах. Например, можно придумать такой разговор:

— У меня что-то медиавыражение не срабатывает. В чём может может быть проблема
— А у тебя правильные характеристики устройства?

Согласитесь же, что это звучит непонятно? Это устройство, на котором я проверяю сайт? Если оставлять этот перевод, то надо будет везде добавлять пометку, что речь идёт про CSS, чтобы исключить двойственность. Имхо, это будет выглядеть как костыль 😄

**Comment by sashasushko** [comment]
Да, согласен. Тогда можно остановиться, а ещё закинуть Веб-стандартам пулл реквест.

**Comment by myshov** [comment]
Закреплю тут тогда переводы:

* media query — медиавыражение
* media feature — медиахарактеристика
* media type — медиатип

**Comment by myshov** [comment]
Не стал открывать пр, но завёл issue

**Comment by myshov** [comment]
Вадим [предлагает](https://github.com/web-standards-ru/dictionary/issues/427#issuecomment-810666768) использовать перевод "медифича", он говорит про то, чтобы перевод был узнаваем. В принципе мне ок такой вариант. @lex111 @sashasushko @Saionaro что думаете?

**Comment by sashasushko** [comment]
Согласен, отписался там.

**Comment by myshov** [comment]
Ждём ответа от @lex111

**Comment by lex111** [comment]
Я согласен на любой вариант, который будет одобрен сообществом, так что конечно используем его.

**Comment by myshov** [comment]
Сделал пулл-реквест в словари веб-стандартов https://github.com/web-standards-ru/dictionary/pull/428. Ишью нужно будет закрыть после слияния изменений

**Comment by sashasushko** [comment]
Вадим смержил. Закрываю ишью.
