### ISSUE TITLE
Issue with "contenteditable": (文档说明有误)

### ISSUE THREAD

**Issue by ctrlwin** [mdn/translated-content#3441]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/contenteditable

#### What information was incorrect, unhelpful, or incomplete?
关于 contenteditable 属性的使用，文档中说到contenteditable属性必须设置默认值，不允许简写。但是实际上简写也是可以的。

#### Specific section or headline?
contenteditable

#### What did you expect to see?
为了不产生误解，希望可以更新下说明

#### Did you test this? If so, how?
经过测试，确实如此，简写也可以正常使用contenteditable 属性，标签变为可编辑状态。

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/html/global_attributes/contenteditable`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/contenteditable
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/html/global_attributes/contenteditable/index.html
* Last commit: https://github.com/mdn/translated-content/commit/75855172b4187f20db9f0550dd54bf9fbc6a68e1
* Document last modified: 2021-12-23T07:44:46.000Z

</details>

**Comment by kaichii** [comment]
[这里](https://html.spec.whatwg.org/multipage/interaction.html#:~:text=The%20contentEditable%20IDL%20attribute%2C%20on%20getting%2C%20must%20return%20the%20string%20%22true%22%20if%20the%20content%20attribute%20is%20set%20to%20the%20true%20state%2C%20%22false%22%20if%20the%20content%20attribute%20is%20set%20to%20the%20false%20state%2C%20and%20%22inherit%22%20otherwise.)有详细说明，的确可以简写。
