### ISSUE TITLE
Update needed for pages on CSS -gap properties

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3450]
For the ~Chinese (simplified)~, Russian and Korean locales, some or all of the pages on CSS `-gap` properties (`column-gap`, `row-gap`, `gap`) would benefit from an update.

Some issues that I noticed were the following:
- Unneeded `{{SeeCompatTable}}` warning
- Broken `{{EmbedInteractiveExample}}` at the top
- Extra (and broken) `{{EmbedInteractiveExample}}` at the top
- Outdated specs table
- Outdated/extra compatibility table(s)
- Missing `border: 1px solid green;` CSS declaration(s)
- Missing `-gap: revert;` property in syntax code block (e.g. `column-gap: revert;`)

**Comment by hochan222** [comment]
@mdn/yari-content-ko complete :)

**Comment by sashasushko** [comment]
I'll figure with it for `ru` locale

**Comment by hochan222** [comment]
done for 'ko-locale' :)

**Comment by sashasushko** [comment]
Sorry for delay 🙄 Here is PR for `ru` locale – https://github.com/mdn/translated-content/pull/14133
