### ISSUE TITLE
Issue with "Модель коробки": (short summary here please)

### ISSUE THREAD

**Issue by Vera-Mart** [mdn/translated-content#346]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/The_box_model

#### What information was incorrect, unhelpful, or incomplete?
Test your skills: The Box Model - the link is incorrect, it leads to a non-existent page in Russian (Page not found) https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Selectors/Box_Model_Tasks . When you select English, the link in English opens correctly (https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Box_Model_Tasks) .

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/css/building_blocks/the_box_model/index.html
* Last commit: https://github.com/mdn/translated-content/commit/78e852ea827ba179e2db61b82a58b41cf729fa52
* Document last modified: 2021-03-27T20:39:05.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Should it link in the russian version to the english page as well?

**Comment by myshov** [comment]
I think it should link to the English page until we translate it into Russian

**Comment by captainspring** [comment]
Agreed. That’s the way it works with all the other pages that aren’t yet translated that I’ve seen so far.
Plus it makes sense. I’d rather have people google-translate an English page into Russian and get what they came looking for (albeit terribly translated) than think that there is no information at all.
