### ISSUE TITLE
Issue with "Operator precedence": different precedence table in different language version

### ISSUE THREAD

**Issue by KokonutTree** [mdn/translated-content#3470]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?

Precedence table varies from different language version. There are 19 levels in English version while 21 levels in Chinese version.

#### Specific section or headline?

Table

#### What did you expect to see?

Same dividing in different language version.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/operators/operator_precedence/index.md
* Last commit: https://github.com/mdn/content/commit/bc8e14e1dc2bd39c4d445614b46fbf6d384ff6c7
* Document last modified: 2021-11-19T06:49:25.000Z

</details>

**Comment by cw118** [comment]
This issue seems to affect most locales. Out of those that are active:
- ru, pt-BR. and zh-TW have 20 items
- ko, zh-CN, and ja have 21 items
- fr has a slightly different issue, where the "Precedence" column has its values reversed (from 0-19 rather than 19-0)

**Comment by yin1999** [comment]
`zh-TW` has been fixed in #4799.

**Comment by cw118** [comment]
ru has been taken care of in #5422.

**Comment by cw118** [comment]
`es` done in #6062

**Comment by cw118** [comment]
This issue is becoming quite "old" and there is only `pt-br` that remains, so I am closing this one to keep #6520 (a new issue for the portuguese locale) open.
