### ISSUE TITLE
Issue with "RegExp": error when loading sections

### ISSUE THREAD

**Issue by loglinn05** [mdn/translated-content#3484]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp

#### What information was incorrect, unhelpful, or incomplete?
An error occurred when loading the information. Screenshot attached.

#### Specific section or headline?
[RegExp Prototype Objects And Instances](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp#regexp_prototype_objects_and_instances): [Properties](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp#properties_of_regexp_instance) and [Methods](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp#methods_of_regexp_instance).

#### Screenshot
![{87024D26-406E-4C60-8883-BE2DA33972F1}](https://user-images.githubusercontent.com/78077184/147683825-daf7b318-16f6-49d0-9c0d-21de8a64cc81.png)

## All the best!

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/javascript/reference/global_objects/regexp`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/global_objects/regexp/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1a429bb492407e98dce1765a6dce06397531bad4
* Document last modified: 2021-12-28T13:03:46.000Z

</details>

**Comment by myshov** [comment]
I think it was deployment bug or something because now everything is ok on this page. Feel free to reopen the issue in any case

**Comment by myshov** [comment]
Just after the closing the issue I stumbled upon on this bug

![image](https://user-images.githubusercontent.com/2382567/150494257-6c0235d1-c3d0-4022-a262-561cd36dd096.png)
