### ISSUE TITLE
Issue with "Interagir avec le presse-papier": (short summary here please)

### ISSUE THREAD

**Issue by Raf-sns** [mdn/translated-content#3548]
MDN URL: https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard

#### What information was incorrect, unhelpful, or incomplete?
-> Document.execCommand()
Deprecated: This feature is no longer recommended.

#### Specific section or headline?
should not be mentioned and explained in this section

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/mozilla/add-ons/webextensions/interact_with_the_clipboard`
* MDN URL: https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/mozilla/add-ons/webextensions/interact_with_the_clipboard/index.md
* Last commit: https://github.com/mdn/translated-content/commit/5619eb75de9672cde9a22d13ef49815ebd6f8164
* Document last modified: 2022-01-03T19:02:03.000Z

</details>

**Comment by SphinxKnight** [comment]
@Raf-sns could you please confirm this issue also applies to the current English page: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Interact_with_the_clipboard ?

**Comment by Raf-sns** [comment]
Hi,
yes i confirm the presence of execCommand() function on the english 
page.

"
-> Using execCommand()
The "cut" and "copy" commands of the document.execCommand() method are 
used to replace the clipboard's content with the selected material. 
These commands can be used without any special permission in short-lived 
event handlers for a user action (for example, a click handler).
"

Regards,
Raf

Le 2022-01-05 19:04, SphinxKnight a écrit :
