### ISSUE TITLE
Updating yari-content-ko to reflect current core contributors

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#3557]
Hello,

Since the beginning of the localization on yari and the creation of the team, @cos18 and I have been the core contributors to ko.

https://github.com/mdn/translated-content/pull/2525 @cos18 enlisted in the army. However, at the moment, we request a change in the circumstances where he is possible to contribute.

@Rumyra could you please update the team members to reflect that? 

I'll submit a PR to update the README and /mdn/contribute/localize to reflect this on the content as well.

Thank you :)

**Comment by hochan222** [comment]
Hi. Yes please invite @cos18 back to the team. Thanks :)

**Comment by Rumyra** [comment]
All done - thanks @hochan222 👍
