### ISSUE TITLE
Content suggestion: How to be maintener for l10n-es

### ISSUE THREAD

**Issue by soymgomez** [mdn/translated-content#3564]
## What is the new suggestion?
Hello, I would like to know what is necessary to be the maintener to see the Spanish version of the documentation. Since I see that it is marked as not active and I have seen several translation errors and missing references in the Spanish documentation.

## Why is it important or useful?

I would like to help to adapt the Spanish version of the documentation and adapt it with the changes of the original version.

**Comment by soymgomez** [comment]
I hope you do not mind who I mentioned and I see that you are the most active people in this repository.

@peterbe @mfuji09 @fiji-flo

**Comment by fiji-flo** [comment]
https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md#activating-a-locale

That's about it.

**Comment by SphinxKnight** [comment]
@soymgomez the Spanish locale has now been "unfrozen" and @mdn/yari-content-es has been created to organize localization/maintenance work. Does this answer your question(s)?

**Comment by sergiogval** [comment]
@soymgomez  actually your PR back in September triggered this unfrozen, so you are already working on it. If you also wan to do  some code review, translate oversight, comment on the PR, ask for changes on them, etc, etc, etc,,.. I believe @Rumyra is  the person who you should ask for.

**Comment by Rumyra** [comment]
Hi all - yes @soymgomez we've unfrozen `es` - there's a discussion here https://github.com/mdn/translated-content/discussions/3370

Everything should be up and running and can be worked on. There's a matrix room in the above discussion where the community chats about things that are going on, so probably worth joining that. If you want to be a part of the `es` team (with write privileges meaning you can review & merge contributors prs) let me know 👍

**Comment by soymgomez** [comment]
Hi all! 

@Rumyra Yes, I would like to be part of the team! What would be necessary on my part?

**Comment by Graywolf9** [comment]
Hi! I think this issue could be already closed

es locale has already unfreezed, we are in:
https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org
https://t.me/+Dr6qKQCAepw4MjFj

**Comment by JuanVqz** [comment]
@Graywolf9 I agree, closing it

**Comment by Rumyra** [comment]
> Hi all!
> 
> @Rumyra Yes, I would like to be part of the team! What would be necessary on my part?

@soymgomez join the matrix chat & let the team know - then open an issue here asking to be added to the team. Mention me and I'll get it done :)
