### ISSUE TITLE
Issue with "CSS アニメーションの使用": (short summary here please)

### ISSUE THREAD

**Issue by mendelssohnbach** [mdn/translated-content#3586]
MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Animations/Using_CSS_animations

#### What information was incorrect, unhelpful, or incomplete?

Japanese translation version
No animation is drawn.

The English(US) version is rendered correctly.

#### Specific section or headline?

Japanese translation version
https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Animations/Using_CSS_animations#%E3%82%A2%E3%83%8B%E3%83%A1%E3%83%BC%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%A4%E3%83%99%E3%83%B3%E3%83%88%E3%81%AE%E5%88%A9%E7%94%A8

#### What did you expect to see?

I want to know the operation code which is not omitted.

#### Did you test this? If so, how?

I checked by switching between Japanese and English.
Firebox and Chrome.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ja/web/css/css_animations/using_css_animations`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/CSS_Animations/Using_CSS_animations
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/css_animations/using_css_animations/index.md
* Last commit: https://github.com/mdn/translated-content/commit/95bf5d4c3e7513c56cd1908986d74fd52914566c
* Document last modified: 2022-01-07T01:14:01.000Z

</details>

**Comment by mfuji09** [comment]
例を動作させるための `{{EmbedLiveSample}}` マクロが、ローカライズ版の場合は独立した見出しの配下に置かないと誤動作するのが原因です。対策として、英語版にない見出しを1つ加えました。

なお、日本語版の記事に対する Issue は日本語で結構です。
日本語翻訳者しか読みませんので。

**Comment by mendelssohnbach** [comment]
@mfuji09 

動作することを確認しました。

Verified that it works.
