### ISSUE TITLE
Content bug: Event.isTrusted typo err

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#3600]
## What page(s) did you find the problem on?

https://developer.mozilla.org/ko/docs/web/api/event/istrusted

## Specific page section or heading?

Event.isTrusted

## What is the problem?

`ture` 오타 발생했습니다.

![image](https://user-images.githubusercontent.com/22424891/148653841-9abdb51b-20fd-4e68-b658-eba747400071.png)

## What did you expect to see?

true

## Did you test this? If so, how?

no

**Comment by yechoi42** [comment]
해결되었으므로 닫습니다
