### ISSUE TITLE
Issue with "Promise.prototype.then()": (translation error)

### ISSUE THREAD

**Issue by Evelynzzz** [mdn/translated-content#361]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/then

#### What information was incorrect, unhelpful, or incomplete?
下面是一个演示 then 方法的**同步性**（❌）的例子。
In English, "Following, an example to demonstrate the **asynchronicity** of the then method."

#### Specific section or headline?

返回值 section

#### What did you expect to see?

下面是一个演示 then 方法的异步性的例子。

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/promise/then`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/then
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/promise/then/index.html
* Last commit: https://github.com/mdn/translated-content/commit/f3af7db28fef073578fe2d432ac976ed993faa5f
* Document last modified: 2021-03-28T17:28:29.000Z

</details>

**Comment by CreaTorAlexander** [comment]
Thanks for catching this, I have created #382 to fix this issue.
