### ISSUE TITLE
live sample error: cannot show live sample when using `zh-CN` id

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#3618]
## What page(s) did you find the problem on?

live sample in:

- <https://pr3617.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/API/DataTransfer/clearData>
- <https://pr3589.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/API/SpeechSynthesis/getVoices>

## What is the problem?

cannot show live sample with network error: "Refused to display in a frame because it set 'X-Frame-Options' to 'deny'.", but the live sample file is actually in [`Artifacts`](https://github.com/mdn/translated-content/suites/4880394935/artifacts/139622759). I have no idea about this.

## Reference

- #3589
- #3617

**Comment by SphinxKnight** [comment]
poking @mdn/core-yari-dev just in case

**Comment by SphinxKnight** [comment]
@yin1999 from what I can test on my side, live samples do work on a local instance of the server (doing `yarn start` from mdn/content). Are you able to confirm that?

**Comment by yin1999** [comment]
> @yin1999 from what I can test on my side, live samples do work on a local instance of the server (doing `yarn start` from mdn/content). Are you able to confirm that?

Yes, it workes locally.

**Comment by fiji-flo** [comment]
https://pr3617.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/API/DataTransfer/clearData/_sample_.%D1%87%D0%B4%E2%95%91%D1%84%E2%95%9B%D0%BB.html

I guess that's the live sample. The URL is wrong. I'll look into it :/

**Comment by fiji-flo** [comment]
https://github.com/mdn/translated-content/runs/4765419677?check_suite_focus=true#step:3:179

That's what's wrong. I have no clue how that happens the `build.zip` looks fine.

That looks like an horrible LOCALE issue on this action. I do see issues with that file and using `unzip`. Something to fix in yari. @yin1999 did this ever work?

**Comment by yin1999** [comment]
@fiji-flo It seems like `unzip` cannot resolve Chinese characters correctly. I have tried `7z` which is included in [virtual-environments](https://github.com/actions/virtual-environments/blob/ubuntu20/20211219.1/images/linux/Ubuntu2004-README.md), it could resolve Chinese characters correctly: <https://github.com/yin1999/test-7z/runs/4769707978?check_suite_focus=true#step:3:191>.

Should we consider using `7z` to replace `unzip` ?

## Command

```bash
7z x build.zip -obuild -bb1
```

## Output

![image](https://user-images.githubusercontent.com/15844309/148865900-ef283328-3389-44c4-96ec-a59320dca995.png)

**Comment by yin1999** [comment]
Reproduced on:

```
Linux 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64
```

Locale Env:

```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

## Output of unzip

```
build/zh-cn/docs/web/api/datatransfer/cleardata/_sample_.'$'\376\361\246\365\245\357''.html
```

**Comment by yin1999** [comment]
@fiji-flo fixed, thanks for help.
