### ISSUE TITLE
Issue with "Set-Cookie": Typos / Coquilles

### ISSUE THREAD

**Issue by jer-sen** [mdn/translated-content#362]
MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Set-Cookie

#### What information was incorrect, unhelpful, or incomplete?
croos-site => cross-site

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/http/headers/set-cookie`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Set-Cookie
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/http/headers/set-cookie/index.html
* Last commit: https://github.com/mdn/translated-content/commit/98084a76e07b91d69f5741f69c13730a8cbf7507
* Document last modified: 2021-03-29T03:23:20.000Z

</details>

**Comment by SphinxKnight** [comment]
@jer-sen thanks for reporting! this seems like a task which could be handled by a first-time contributor: would you be interested in contributing fixing this? :)

**Comment by Yoplala** [comment]
En relisant la page concernée j'ai repéré une flopée d'autres coquilles :
- "Plusieurs directives sont aussi pussibles"
- "de n'importe que caractères"
- "peut éventuellement être entouré de doubles guillemets et inclut tout les caractères"
- "le tiret fait partit du préfixe"
- "doivent être définit" (x2)
- "Si un cookie est doit être envoyé en cross-site"
- "le cookies permanent expirent à une date spécifique"
- "les cookies avec le préfixe __Host- doivent avoir doivent avoir un path valant / (donc tout les chemins de l'hôte) et ne doit pas avoir d'attribut Domain."

Je ne critique pas le travail de traduction déjà effectué mais étant relecteur sur d'autres projets, je sais que c'est un travail collaboratif et de longue haleine. Il faut que je relise la documentation et que je prenne le temps de participer... ><

**Comment by SphinxKnight** [comment]
@Yoplala je confirme que ce n'est pas la seule :) (merci Grammalecte)
Si vous avez l'occasion et les moyens (dont le temps) de contribuer, ce sera avec plaisir :)

Si besoin, il y a cet article avec quelques explications : https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer

**Comment by CreaTorAlexander** [comment]
Thanks for catching this up, I raised #406 to fix it.

**Comment by CreaTorAlexander** [comment]
What are the other grammatical issues that should be updated in the document?
