### ISSUE TITLE
fr - Update contribution content to reflect new workflow/tools/tasks

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#363]
[This page](https://developer.mozilla.org/fr/docs/MDN/Contribute) needs update and should include pointers to new resources regarding Yari (including but not limited to:

* [README of this repo](https://github.com/mdn/translated-content/blob/main/README.md#making-contributions)
* [French blog post for contributor setup](https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer)

**Comment by tristantheb** [comment]
Déjà dans les rouages de ma to-do list, j'en profiterai pour ajouter les liens 👀 https://github.com/tristantheb/translated-content/issues/3
