### ISSUE TITLE
Content bug: X-Frame-Options pages are missing translation for the note about it being obsolete due to frame-ancestors in newer browsers

### ISSUE THREAD

**Issue by deryni** [mdn/translated-content#3684]
## What page(s) did you find the problem on?

https://developer.mozilla.org/es/docs/Web/HTTP/Headers/X-Frame-Options
https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/X-Frame-Options
https://developer.mozilla.org/zh-TW/docs/Web/HTTP/Headers/X-Frame-Options

This page has the information (it looks like) but doesn't have it formatted as a Note in the same way.
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/X-Frame-Options

## Specific page section or heading?

Main section

## What is the problem?

A note about the obsolete status of the header is missing from the translated pages but appears on the English page.

## What did you expect to see?

Content parity in the translations.

**Comment by JuanVqz** [comment]
We as (es) community already did the change, and I'm going to remove the `I10n-es` label.

**Comment by yin1999** [comment]
`l10n-zh` is resolved: #5098 and #5397

**Comment by hochan222** [comment]
`l10n-ko` is resolved: https://github.com/mdn/translated-content/pull/3872

Have a nice day :)
