### ISSUE TITLE
Issue with "Reason: CORS request did not succeed": (Issue on GoFundMe)

### ISSUE THREAD

**Issue by Rosssyvonne** [mdn/translated-content#3696]
MDN URL: https://developer.mozilla.org/es/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

https://www.gofundme.com/

#### What information was incorrect, unhelpful, or incomplete?
Solicitud de origen cruzado bloqueada: La misma política de origen no permite la lectura de recursos remotos en https://api.amplitude.com/. (Razón: Solicitud CORS sin éxito). Código de estado: (null).

#### Specific section or headline?
Solicitud de origen cruzado bloqueada: La misma política de origen no permite la lectura de recursos remotos en https://api.amplitude.com/. (Razón: Solicitud CORS sin éxito). Código de estado: (null).

#### What did you expect to see?
I'm expecting to do a successful donation on GoFundMe

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/http/cors/errors/corsdidnotsucceed`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/http/cors/errors/corsdidnotsucceed/index.html
* Last commit: https://github.com/mdn/translated-content/commit/78fadee3cb122d5843eff5e2d466473688cb9c77
* Document last modified: 2022-01-14T21:49:57.000Z

</details>

**Comment by Graywolf9** [comment]
Hi! @Rosssyvonne, the issue is with MDN content or with GoFundMe web page? (if you are more confortable with Spanish we can see it in Spanish)

**Comment by Rosssyvonne** [comment]
The issue is with GoFundMe

**Comment by Graywolf9** [comment]
Unfortunately GoFundMe has nothing related to MDN, the link you found from MDN is a help to GoFundMe develeopers to solve their error. Also this is the GoFundMe github account: https://github.com/gofundme

I think this issue could be closed

@JuanVqz @sergiogval
