### ISSUE TITLE
Issue with "Element.querySelectorAll()": Code error in French translation

### ISSUE THREAD

**Issue by Dyrudis** [mdn/translated-content#3730]
MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Element/querySelectorAll

#### What information was incorrect, unhelpful, or incomplete?
In a code example, there's an incorrect line : `container.querySelectorAll("li[data-active=1]")`.

#### Specific section or headline?
In this section (5th example) : https://developer.mozilla.org/fr/docs/Web/API/Element/querySelectorAll#obtention_dune_liste_de_correspondances

#### What did you expect to see?
Instead of `container.querySelectorAll("li[data-active=1]")` there should be  `container.querySelectorAll("li[data-active='1']")`.

#### Did you test this? If so, how?
Yes, it is easy to test in the browser console. When you type `document.querySelectorAll("li[data-active=1]")`, it returns an error : `'li[data-active=1]' is not a valid selector.`
When you type `document.querySelectorAll("li[data-active='1']")` it returns the expected NodeList.

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/api/element/queryselectorall`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Element/querySelectorAll
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/element/queryselectorall/index.md
* Last commit: https://github.com/mdn/translated-content/commit/149b599368b4e27cf7d05f270a43519f599372fd
* Document last modified: 2022-01-18T00:57:02.000Z

</details>

**Comment by SphinxKnight** [comment]
Thanks @Dyrudis for the report, this should be solved with #3733 which should be pushed live in a few hours
