### ISSUE TITLE
Issue with "Object": Why is this page layout inconsistent with the others?

### ISSUE THREAD

**Issue by ChenKun1997** [mdn/translated-content#3734]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object

#### What information was incorrect, unhelpful, or incomplete?
The "Object" page layout inconsistent with the Array or others?

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/object`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/object/index.html
* Last commit: https://github.com/mdn/translated-content/commit/149b599368b4e27cf7d05f270a43519f599372fd
* Document last modified: 2022-01-18T00:57:02.000Z

</details>

**Comment by ChenKun1997** [comment]
Object:
![image](https://user-images.githubusercontent.com/24249578/150057670-96efb7e5-5018-4fcc-8205-10491c07c16e.png)
Aray:
![image](https://user-images.githubusercontent.com/24249578/150057783-fcc37697-67f6-4cce-b99c-e1190794fb6d.png)

**Comment by yin1999** [comment]
Maybe network problem, it's ok in my computer. Could you provide more details?

![image](https://user-images.githubusercontent.com/15844309/150349330-ce3af846-f624-4903-be69-4c3999a00984.png)

**Comment by cw118** [comment]
Looks like this is related to mdn/yari#5180, which was fixed recently and should now be reflected in production — @ChenKun1997 could you confirm whether the issue is still present?

**Comment by ChenKun1997** [comment]
It works fine now @yin1999 @cw118

**Comment by cw118** [comment]
Great! In that case, I'd say this issue can be closed now?

**Comment by ChenKun1997** [comment]
@cw118 Yes,Thank you.
