### ISSUE TITLE
Issue with "PUT": (the page is loaded without the layout style)

### ISSUE THREAD

**Issue by Wolfergest** [mdn/translated-content#3741]
MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Methods/PUT

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/http/methods/put`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Methods/PUT
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/http/methods/put/index.html
* Last commit: https://github.com/mdn/translated-content/commit/149b599368b4e27cf7d05f270a43519f599372fd
* Document last modified: 2022-01-18T00:57:02.000Z

</details>

**Comment by myshov** [comment]
@Wolfergest приветствую!
Напишите пожалуйства, в чём имено заключается проблема на странице. Посмотрел и не нашёл каких-либо проблем, есть только отличие в ссылке на спецификацию

**Comment by Wolfergest** [comment]
@myshov Приветствую, была похожая проблема: https://github.com/mdn/yari/issues/5197 и уже исправили. Спасибо за отклик
