### ISSUE TITLE
Want to be added to the l10n-es team

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#3742]
Hi! @Rumyra I see that I need to open an issue for requesting to you to be part of the team in github, I'm already working with @JuanVqz and the rest of the team.

Thanks a lot and best reggards.

**Comment by JuanVqz** [comment]
@Rumyra, I agree with the request, please!

**Comment by Rumyra** [comment]
Hi @Graywolf9 👋  - you should have an invite now 👍

**Comment by Graywolf9** [comment]
Thank you so much @Rumyra !
