### ISSUE TITLE
Issue with "Liste des requêtes réseau": (short summary here please)

### ISSUE THREAD

**Issue by mhabsaoui** [mdn/translated-content#3749]
MDN URL: https://developer.mozilla.org/fr/docs/Tools/Network_Monitor/request_list

#### What information was incorrect, unhelpful, or incomplete?
We don't information about how to enable Devtools' network tab, to display requests from a web extension's injected script !

#### Specific section or headline?
Network Tab.

#### What did you expect to see?
HTTP requests.

#### Did you test this? If so, how?
Load or install any Firefox web extension that has injected a Content script which makes Http Fetch calls.
Open Devtools and check on network tab if those requests are displayed.

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/tools/network_monitor/request_list`
* MDN URL: https://developer.mozilla.org/fr/docs/Tools/Network_Monitor/request_list
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/tools/network_monitor/request_list/index.html
* Last commit: https://github.com/mdn/translated-content/commit/fb769838d655c3e6d28afdb3236ab9f3d9712d10
* Document last modified: 2022-01-20T00:58:58.000Z

</details>

**Comment by SphinxKnight** [comment]
@mhabsaoui bonjour, pouvez-vous s'il vous plaît préciser votre problème ? je ne suis pas sûr d'avoir compris ce dont il s'agissait. Est-ce que ce problème est également présent sur la page en anglais ? (https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_list )

**Comment by mhabsaoui** [comment]
Bonjour et merci de votre réponse 🙂

Non, l'information que je recherche en vain n'est disponible nulle part sur MDN 😕

Pour être clair :  On n'arrive pas à avoir dans l'onglet Réseau du Devtools, l'affichage des requêtes émises par le Content-Script qui est injecté par l'extension Firefox dans une page web !

On a uniquement les appels Http "normaux" correspondants aux chargement de la page web.
Une fois la page chargée, notre extension Firefox injecte un Content-Script effectuant des requêtes Fetch, mais ces dernières n'apparaissent pas dans l'onglet Réseau du Devtools.

N.B.: Pourtant sous Chrome, elles sont bien affichéese...

N'hésitez si besoin de précisions !

**Comment by SphinxKnight** [comment]
@mhabsaoui Merci pour votre retour, il s'agit à mon sens d'un sujet plutôt lié aux webextensions dont le débogage dans Firefox est documenté ici https://extensionworkshop.com/documentation/develop/debugging/ et pas dans MDN

En utilisant la page `about:debugging` et en manipulant l'extension (j'ai pris https://addons.mozilla.org/fr/firefox/addon/click-and-read/ et j'ai ouvert la page de réglages avec l'icône), j'arrive à voir passer les requêtes réseau : 
![image](https://user-images.githubusercontent.com/2413436/151662794-d9f11b99-60d6-4848-b836-673e3f24764c.png)

Pouvez-vous me dire si c'est OK pour vous ?

**Comment by mhabsaoui** [comment]
Merci de prendre la peine de tester et nous aider :+1: 

En fait, j'avais bien parcouru toute la Doc MDN+ Ext-Workshop...  Et le mieux que j'ai trouvé c'est justement le fameux bouton "Examiner" qui permet de suivre uniquement la background-script : sur votre image et la mienne, on voit simplement l'appel Fetch de la page Options ne faisant pas partie du Content-Script !

![image](https://user-images.githubusercontent.com/18755135/151663942-dea00a6b-15e5-468d-9bf9-b7a245e9c2a7.png)

Ce qu'on cherche à avoir, ce sont les appels Fetch du Content-Script lorsqu'on est sur une page web "normale" (https://...), c'est là que notre extension émet les requêtes http qui nous interessent et qu'on arrive pas à voir :-/

Sur les images suivantes Chrome Vs Firefox, plus parlant...

![image](https://user-images.githubusercontent.com/18755135/151664111-a029701d-002a-41e2-ab9d-07234fd095f0.png)

![image](https://user-images.githubusercontent.com/18755135/151664124-cdd1c269-2745-490d-b5c2-6a4016f67598.png)


J’espère que vous comprenez mieux notre blocage et que vous avez la solution.

**Comment by SphinxKnight** [comment]
Je comprends mieux le blocage, merci pour les informations (et je suis en train de regarder de mon côté depuis tout à l'heure), je renseignerai ici une solution ou des éléments (ex. bug ouvert sur Firefox) si j'en trouve…
J'ai bien compris le sujet 

Après il faudra voir comment intégrer ces informations à MDN (dont il est sujet dans ce dépôt).

**Comment by mhabsaoui** [comment]
Pour information, 

- j'avais tenté de demander l'aide ici aussi, ne savant pas trop où demander...

https://github.com/mozilla/addons/issues/1381#issuecomment-1017993479

- J'ai même demandé sur Twitter, mais sans succès.

https://twitter.com/mhabsaoui/status/1481248952590770179

Merci beaucoup pour votre aide et support :-)

**Comment by SphinxKnight** [comment]
@mhabsaoui y a-t-il un dépôt open source pour l'extension en question?

**Comment by mhabsaoui** [comment]
> @mhabsaoui y a-t-il un dépôt open source pour l'extension en question?

Non, pas pour l'instant. A venir bientôt...

**Comment by SphinxKnight** [comment]
@mhabsaoui oui j'ai minimisé le cas de mon côté avec une webext minimaliste.
Après plusieurs heures je suis tombé sur https://bugzilla.mozilla.org/show_bug.cgi?id=1442488 :/

**Comment by SphinxKnight** [comment]
@mhabsaoui je propose d'ajouter une mention de ce bug dans la documentation de MDN (à défaut de mieux à faire pour le dépôt pour lequel cette issue est renseigné), OK pour vous ?

**Comment by mhabsaoui** [comment]
Je viens de remarquer que ce bug a été "Opened 4 years ago" !

Comment font les développeurs d'extension Firefox pour développer et vérifier que les content script fonctionnent bien du coup actuellement ?

**Comment by SphinxKnight** [comment]
La documentation des outils de développement a été déplacée vers https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/request_list/index.html et n'est plus localisable en l'état. 
J'ai transféré la demande sur le bug 1442488 et je clos cette *issue*.

Désolé de ne pas pouvoir faire mieux @mhabsaoui
