### ISSUE TITLE
Issue with "CSS 에서 항목 크기 조정" 페이지 오타.

### ISSUE THREAD

**Issue by in-seul** [mdn/translated-content#3758]
MDN URL: https://developer.mozilla.org/ko/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS

### Specific page section or heading? 
- - -
종회비

### What did you expect to see?
- - -
문서에서 먼저  
> "이미지 및 비디오와 같은 특정 대체 요소도 종횡비 (aspect ratio) 를 갖는 것으로 설명됩니다."

로 기술되어 있으므로, `종횡비`로 수정해야 합니다.

매번 감사드립니다.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ko/learn/css/building_blocks/sizing_items_in_css`
* MDN URL: https://developer.mozilla.org/ko/docs/Learn/CSS/Building_blocks/Sizing_items_in_CSS
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/learn/css/building_blocks/sizing_items_in_css/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d3dbfce79ad140b58898518250a5a75195692550
* Document last modified: 2022-01-20T18:15:19.000Z

</details>

**Comment by kraccoon-dev** [comment]
해당 문제가 해결된 것으로 보입니다! 문제가 없다면 이슈를 닫아주세요:)

<img src="https://i.ibb.co/yfJXBNR/fixed.png" alt="fixed" border="0">

**Comment by yechoi42** [comment]
@kraccoon-dev 넵 닫겠습니다!
