### ISSUE TITLE
Issue with "자바스크립트 문제해결": 페이지 오타

### ISSUE THREAD

**Issue by in-seul** [mdn/translated-content#3786]
MDN URL: https://developer.mozilla.org/ko/docs/Learn/JavaScript/First_steps/What_went_wrong

#### Specific section or headline?
- - -

- 난중 

-  나둬도

- 첫번재
#### What did you expect to see?
- - -
원문:
>You can delete your console.log() line now, or keep it to reference later on — your choice.

번역:
> console.log()를 지금 제거해도 되고 난중을 위해 나둬도 되니 알아서 하자.

- `나중`으로 수정해야 합니다.

- `놔두어도` 또는 `놔둬도`로 수정해야 합니다.

> 위의 첫번재 에러를 살펴보면
- `첫 번째`로 수정해야 합니다.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ko/learn/javascript/first_steps/what_went_wrong`
* MDN URL: https://developer.mozilla.org/ko/docs/Learn/JavaScript/First_steps/What_went_wrong
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/learn/javascript/first_steps/what_went_wrong/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d3dbfce79ad140b58898518250a5a75195692550
* Document last modified: 2022-01-20T18:15:19.000Z

</details>

**Comment by yechoi42** [comment]
해결되었으므로 닫습니다
