### ISSUE TITLE
中文页面下的一个错误

### ISSUE THREAD

**Issue by printforscanf** [mdn/translated-content#384]
在介绍    #使用break退出循环   时，使用的例子中有个明显的逻辑错误。
btn.addEventListener('click', function(){
  var searchName = input.value;
  input.value = '';
  input.focus();
  for (var i = 0; i < contacts.length; i++) {
    var splitContact = contacts[i].split(':');
    if (splitContact[0] === searchName) {
      para.textContent = splitContact[0] + '\'s number is ' + splitContact[1] + '.';
      break;
    }
**//这里少了一个条件 if(i === contacts.length - 1)，**

 else {
      para.textContent = 'Contact not found.';} }
});

**Comment by CreaTorAlexander** [comment]
What is the problem in the code example above?

**Comment by iigmir** [comment]
> 
> 
> What is the problem in the code example above?

I will to translate his comment and format the code here...

```js
// When introducing how to quit for loop by using the break statement,
// there's an obvious logical error in the usage example:
btn.addEventListener('click', function(){
    var searchName = input.value;
    input.value = '';
    input.focus();
    for (var i = 0; i < contacts.length; i++) {
        var splitContact = contacts[i].split(':');
        if (splitContact[0] === searchName) {
            para.textContent = splitContact[0] + '\'s number is ' + splitContact[1] + '.';
            break;
        }
        // Here, (the article) loses a conditional statement: if(i === contacts.length - 1)
        else {
        para.textContent = 'Contact not found.';}
    }
});
```

I guess he's referring the [循环吧代码#使用break退出循环](https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/Building_blocks/Looping_code#使用break退出循环) page, while the corresponding English page [Looping code#Exiting loops with break](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code#exiting_loops_with_break) has fixed the error.
