### ISSUE TITLE
I want to join the i10n-es team

### ISSUE THREAD

**Issue by davbrito** [mdn/translated-content#3845]
Hello @Rumyra! I want to be part of the team for `i10n-es` 🇪🇸 , I've already made some contributions and have been collaborating with @JuanVqz and the rest of the team.

Thanks in advance.

**Comment by JuanVqz** [comment]
@Rumyra, I agree with the request, please!

**Comment by Graywolf9** [comment]
I agree too. Thank you!

**Comment by Rumyra** [comment]
You should have an invite now @davbrito :)

**Comment by davbrito** [comment]
Thank you @Rumyra! <3
