### ISSUE TITLE
Información desactualizada "Usando gradientes con CSS": [es]

### ISSUE THREAD

**Issue by rociogp99** [mdn/translated-content#3855]
MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/CSS_Images/Using_CSS_gradients

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/css/css_images/using_css_gradients`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/CSS_Images/Using_CSS_gradients
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/css_images/using_css_gradients/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ab2378b07699fea292480f1c1620586ddaebd1c6
* Document last modified: 2022-01-26T01:00:54.000Z

</details>

**Comment by JuanVqz** [comment]
Hola @rociogp99, tengo algunas preguntas para ti: 
¿Que información es incorrecta o incompleta?
¿De que sección estas hablando?
¿Que esperas ver?
¿Lo probaste? si lo probaste, como lo probaste?

Si quieres abundar los detalles puedes unirte al [chat en español](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org)
