### ISSUE TITLE
Issue with "Moniteur Réseau": (short summary here please)

### ISSUE THREAD

**Issue by jesterli60570** [mdn/translated-content#3856]
MDN URL: https://developer.mozilla.org/fr/docs/Tools/Network_Monitor

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/tools/network_monitor`
* MDN URL: https://developer.mozilla.org/fr/docs/Tools/Network_Monitor
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/tools/network_monitor/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ab2378b07699fea292480f1c1620586ddaebd1c6
* Document last modified: 2022-01-26T01:00:54.000Z

</details>

**Comment by cw118** [comment]
Hi @jesterli60570, could you please specify what issue(s) you found in this page?

**Comment by SphinxKnight** [comment]
@jesterli60570 I'm closing this one due to the absence of specific information on a particular issue about this page. Please, feel free to open a new one with more info.
