### ISSUE TITLE
Content bug: Content not translated in CSS zoom page [es]

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#3864]
## What page(s) did you find the problem on?

https://developer.mozilla.org/es/docs/Web/CSS/zoom

## Specific page section or heading?

*No estandard* warning

## What is the problem?

The content is not translated

## What did you expect to see?

Content translated in `es` locale

## Did you test this? If so, how?

visiting: https://developer.mozilla.org/es/docs/Web/CSS/zoom

**Comment by marcelozarate** [comment]
@Graywolf9 I believe most of this issue was adressed in PR #3716

**Comment by cw118** [comment]
@marcelozarate Based on the [English file](https://github.com/mdn/content/blob/main/files/en-us/web/css/zoom/index.md?plain=1), the Spanish one still seems to be slightly out-of-date (e.g. the "See also" links at the end, the `{{EmbedLiveSample}}` arguments are also incorrect). 

I'm not on the `es` team, but I think you could create a PR to fix these problems (and any others in the same file) and close this issue in said pull request if you're interested :)

**Comment by marcelozarate** [comment]
Thanks a lot @cw118 you're right, I'm submitting a PR to adress this, I couldn't find the issue with the {{EmbedLiveSample}} though.
