### ISSUE TITLE
Issue with "Imágenes adaptables" [es]

### ISSUE THREAD

**Issue by ghost** [mdn/translated-content#3866]
MDN URL: https://developer.mozilla.org/es/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/learn/html/multimedia_and_embedding/responsive_images`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/html/multimedia_and_embedding/responsive_images/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ab2378b07699fea292480f1c1620586ddaebd1c6
* Document last modified: 2022-01-26T01:00:54.000Z

</details>

**Comment by marcelozarate** [comment]
No feedback given after several months. Closing this issue.
