### ISSUE TITLE
ошибки и опечатки

### ISSUE THREAD

**Issue by rmaksim** [mdn/translated-content#3876]
https://github.com/mdn/translated-content/blob/b9ea89d87d177efe9b4e1610d4916f2e1146bbd7/files/ru/web/api/atob/index.html#L9

Вы можете использовать метод {{domxref("WindowOrWorkerGlobalScope.btoa","btoa()")}}, чтобы **декодировать** и передать данные

наверное надо -> btoa чтобы **ЗАкодировать**

----
и использовать метод <code>atob()</code> чтобы декодировать **даны** снова.

**пропущена буква** Н и Е в слове **данНыЕ**

**Comment by unsky559** [comment]
Closed your issue in #4825. Waiting for review, thank you @rmaksim!
