### ISSUE TITLE
{{page}} macro removal for French pages - Meta

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#3881]
The old transclusion macro `{{page}}` has been removed and is not working anymore. However, it does appear in some localized pages such as spotted by @nhoizey (https://mamot.fr/@nhoizey/107694225381352679 )

I'm filing this issue as a first step before making a corrective PR.

**Comment by SphinxKnight** [comment]
"Raw" list of affected pages (as of 1dbea82)
- glossary/denial_of_service/index.md
- glossary/second-level_domain/index.md
- learn/server-side/django/generic_views/index.md
- web/api/audiobuffersourcenode/buffer/index.md
- web/api/audiolistener/index.md
- web/api/batterymanager/index.md
- web/api/biquadfilternode/index.md
- web/api/customevent/index.md
- web/api/datatransfer/cleardata/index.md
- web/api/deviceorientationevent/absolute/index.md
- web/api/document/index.md
- web/api/element/animate/index.md
- web/api/element/error_event/index.md
- web/api/element/mousedown_event/index.md
- web/api/element/mouseup_event/index.md
- web/api/gainnode/index.md
- web/api/gamepad_api/using_the_gamepad_api/index.md
- web/api/geolocation_api/index.md
- web/api/mediastreamaudiosourcenode/index.md
- web/api/navigator/getusermedia/index.md
- web/api/periodicwave/index.md
- web/api/webglrenderingcontext/index.md
- web/css/@media/index.md
- web/css/css_transforms/using_css_transforms/index.md
- web/css/max-block-size/index.md
- web/html/element/img/index.md
- web/html/element/input/date/index.md
- web/html/element/input/datetime-local/index.md
- web/html/element/input/email/index.md
- web/html/element/input/month/index.md
- web/html/element/input/number/index.md
- web/html/element/input/password/index.md
- web/html/element/input/range/index.md
- web/html/element/input/search/index.md
- web/html/element/input/tel/index.md
- web/html/element/input/time/index.md
- web/html/element/input/url/index.md
- web/html/element/input/week/index.md
- web/html/element/track/index.md
- web/http/headers/content-security-policy/base-uri/index.md
- web/http/headers/content-security-policy/child-src/index.md
- web/http/headers/content-security-policy/connect-src/index.md
- web/http/headers/content-security-policy/font-src/index.md
- web/http/headers/content-security-policy/form-action/index.md
- web/http/headers/content-security-policy/frame-src/index.md
- web/http/headers/content-security-policy/img-src/index.md
- web/http/headers/content-security-policy/manifest-src/index.md
- web/http/headers/content-security-policy/media-src/index.md
- web/http/headers/content-security-policy/navigate-to/index.md
- web/http/headers/content-security-policy/object-src/index.md
- web/http/headers/content-security-policy/prefetch-src/index.md
- web/http/headers/content-security-policy/script-src/index.md
- web/http/headers/content-security-policy/script-src-attr/index.md
- web/http/headers/content-security-policy/script-src-elem/index.md
- web/http/headers/content-security-policy/style-src/index.md
- web/http/headers/content-security-policy/style-src-attr/index.md
- web/http/headers/content-security-policy/style-src-elem/index.md
- web/http/headers/content-security-policy/worker-src/index.md
- web/http/headers/feature-policy/index.md
- web/http/headers/feature-policy/accelerometer/index.md
- web/javascript/data_structures/index.md
- web/javascript/guide/indexed_collections/index.md
- web/javascript/reference/index.md
- web/javascript/reference/global_objects/arraybuffer/index.md
- web/javascript/reference/global_objects/asyncfunction/index.md
- web/javascript/reference/global_objects/bigint/index.md
- web/javascript/reference/global_objects/boolean/index.md
- web/javascript/reference/global_objects/dataview/index.md
- web/javascript/reference/global_objects/date/tolocaledatestring/index.md
- web/javascript/reference/global_objects/date/tolocalestring/index.md
- web/javascript/reference/global_objects/error/index.md
- web/javascript/reference/global_objects/evalerror/index.md
- web/javascript/reference/global_objects/function/index.md
- web/javascript/reference/global_objects/generatorfunction/index.md
- web/javascript/reference/global_objects/internalerror/index.md
- web/javascript/reference/global_objects/intl/collator/index.md
- web/javascript/reference/global_objects/intl/datetimeformat/index.md
- web/javascript/reference/global_objects/intl/datetimeformat/formatrange/index.md
- web/javascript/reference/global_objects/intl/listformat/index.md
- web/javascript/reference/global_objects/intl/numberformat/index.md
- web/javascript/reference/global_objects/intl/pluralrules/index.md
- web/javascript/reference/global_objects/intl/relativetimeformat/index.md
- web/javascript/reference/global_objects/map/index.md
- web/javascript/reference/global_objects/number/tolocalestring/index.md
- web/javascript/reference/global_objects/object/index.md
- web/javascript/reference/global_objects/promise/index.md
- web/javascript/reference/global_objects/proxy/index.md
- web/javascript/reference/global_objects/proxy/revocable/index.md
- web/javascript/reference/global_objects/referenceerror/index.md
- web/javascript/reference/global_objects/regexp/index.md
- web/javascript/reference/global_objects/set/index.md
- web/javascript/reference/global_objects/sharedarraybuffer/index.md
- web/javascript/reference/global_objects/string/localecompare/index.md
- web/javascript/reference/global_objects/symbol/index.md
- web/javascript/reference/global_objects/syntaxerror/index.md
- web/javascript/reference/global_objects/typedarray/index.md
- web/javascript/reference/global_objects/typedarray/tolocalestring/index.md
- web/javascript/reference/global_objects/typeerror/index.md
- web/javascript/reference/global_objects/urierror/index.md
- web/javascript/reference/global_objects/weakset/index.md
- web/javascript/reference/global_objects/webassembly/global/index.md
- web/javascript/reference/global_objects/webassembly/instance/index.md
- web/javascript/reference/global_objects/webassembly/module/index.md
- web/javascript/typed_arrays/index.md
- web/svg/attribute/accent-height/index.md
- web/svg/attribute/height/index.md
- web/svg/attribute/width/index.md
- web/svg/attribute/x/index.md
- tools/eyedropper/index.html
- tools/style_editor/index.html
- tools/tools_toolbox/index.html
- tools/web_console/the_command_line_interpreter/index.html

**Comment by cw118** [comment]
@SphinxKnight hope you don't mind me pinging — are there any sections of this that I could help with? (And just to confirm, should/can these macros be replaced with links?)

**Comment by SphinxKnight** [comment]
No problem at all : ) I'm assigning myself when I start working on a given issue, so feel free to tackle any other :)

This macro should be replaced with the corresponding content of the English page. This was not a "link" macro but a "transclusion" macro which injected the content of a whole page/section onto the current page. So the target is to have parity w/ en-US (sometimes it's trivial… sometimes it's not ^ ^)

That being written, thanks a lot for filing the issues for the other locales! :)

**Comment by cw118** [comment]
There is now 0 `{{page}}` macros for `l10n-fr`, thank you again @SphinxKnight :)

**Comment by SphinxKnight** [comment]
> There is now 0 `{{page}}` macros for `l10n-fr`, thank you again @SphinxKnight :)

Wooot, thanks for all the eagle-eyed reviews 🙇
