### ISSUE TITLE
Issue with "WebSocket": (short summary here please)

### ISSUE THREAD

**Issue by nerrevar** [mdn/translated-content#389]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/WebSocket

#### What information was incorrect, unhelpful, or incomplete?
Битая ссылка на MessageEvent

#### Specific section or headline?
Атрибуты

#### What did you expect to see?
Битая ссылка на MessageEvent

#### Did you test this? If so, how?
Битая ссылка на MessageEvent

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/api/websocket`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/WebSocket
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/websocket/index.html
* Last commit: https://github.com/mdn/translated-content/commit/507ad4b86adf1c7c8f78d61f1e58cb9b054c12f3
* Document last modified: 2021-03-31T14:55:25.000Z

</details>

**Comment by CreaTorAlexander** [comment]
The close event link also doesn't seems to work either. I think it should link to */en-us/web/api/websocket/message_event/*

Why does the link path includes the */en/* ?

**Comment by captainspring** [comment]
@CreaTorAlexander these links lead to English pages because there are no translations for them yet. 🙂

**Comment by CreaTorAlexander** [comment]
@captainspring I was unclear, what I have mean is: Why does it link to */en* and not to */en-Us/* 

In the html it is
`   <td><code><a href="/en/unsigned_long" title="en/unsigned long">unsigned long</a></code></td>
`
But as I have seen you have already corrected this in your Pull Request :smile:

**Comment by chrisdavidmills** [comment]
@CreaTorAlexander MDN used to use `/en/` for English docs, a long time ago, but then we changed our Englsh slug to `en-US`. Any URLs that still use `en` are just very old and out-of-date.
