### ISSUE TITLE
{{page}} macro calls on Russian pages

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3892]
Quoting **SphinxKnight**:
> The old transclusion macro {{page}} has been removed and is not working anymore.

This problem has also been reported several times (e.g. #3484 and #2973, though the latter has been "fixed" as the macros were removed in a PR), thought I'd file an issue with all occurrences. Found 127 results in 81 files:

<details>
<summary>29 pages in Web/API:</summary>

- web/api/batterymanager/index.html
- web/api/document/index.html
- web/api/element/animate/index.html
- web/api/element/error_event/index.html
- web/api/element/mouseup_event/index.html
- web/api/file/index.html
- web/api/filereader/readasdataurl/index.html
- web/api/geolocation_api/index.html
- web/api/globaleventhandlers/onanimationend/index.html
- web/api/htmlformelement/elements/index.html
- web/api/htmlformelement/length/index.html
- web/api/mediaelementaudiosourcenode/index.html
- web/api/mediaerror/index.html
- web/api/navigator/battery/index.html
- web/api/navigator/getusermedia/index.html
- web/api/navigator/getvrdisplays/index.html
- web/api/pannernode/index.html
- web/api/rtcpeerconnection/connectionstate/index.html
- web/api/rtcpeerconnection/rtcpeerconnection/index.html
- web/api/screen/index.html
- web/api/vrdisplaycapabilities/hasposition/index.html
- web/api/vrdisplayevent/display/index.html
- web/api/vrframedata/index.html
- web/api/vrpose/index.html
- web/api/vrpose/position/index.html
- web/api/vrstageparameters/sittingtostandingtransform/index.html
- web/api/vrstageparameters/sizex/index.html
- web/api/vrstageparameters/sizey/index.html
- web/api/window/ondeviceorientation/index.html
</details>

<details>
<summary>35 pages in Web/JavaScript:</summary>

- web/javascript/data_structures/index.html
- web/javascript/guide/indexed_collections/index.html
- web/javascript/reference/index.html
- web/javascript/reference/global_objects/array/index.html
- web/javascript/reference/global_objects/asyncfunction/index.html
- web/javascript/reference/global_objects/boolean/index.html
- web/javascript/reference/global_objects/dataview/index.html
- web/javascript/reference/global_objects/date/index.html
- web/javascript/reference/global_objects/date/tolocaledatestring/index.html
- web/javascript/reference/global_objects/date/tolocalestring/index.html
- web/javascript/reference/global_objects/date/tolocaletimestring/index.html
- web/javascript/reference/global_objects/error/index.html
- web/javascript/reference/global_objects/evalerror/index.html
- web/javascript/reference/global_objects/generatorfunction/index.html
- web/javascript/reference/global_objects/internalerror/index.html
- web/javascript/reference/global_objects/intl/collator/index.html
- web/javascript/reference/global_objects/intl/datetimeformat/index.html
- web/javascript/reference/global_objects/intl/numberformat/index.html
- web/javascript/reference/global_objects/number/index.html
- web/javascript/reference/global_objects/number/tolocalestring/index.html
- web/javascript/reference/global_objects/object/index.html
- web/javascript/reference/global_objects/proxy/revocable/index.html
- web/javascript/reference/global_objects/rangeerror/index.html
- web/javascript/reference/global_objects/referenceerror/index.html
- web/javascript/reference/global_objects/regexp/index.html
- web/javascript/reference/global_objects/set/index.html
- web/javascript/reference/global_objects/string/localecompare/index.html
- web/javascript/reference/global_objects/symbol/index.html
- web/javascript/reference/global_objects/syntaxerror/index.html
- web/javascript/reference/global_objects/typedarray/index.html
- web/javascript/reference/global_objects/typeerror/index.html
- web/javascript/reference/global_objects/urierror/index.html
- web/javascript/reference/global_objects/weakmap/index.html
- web/javascript/reference/global_objects/weakset/index.html
- web/javascript/typed_arrays/index.html
</details>

<details>
<summary>Misc, 14 pages in Web/HTTP, Web/HTML and Web/SVG (please see #4822 for dealing with the Tools section):</summary>

- web/http/basics_of_http/mime_types/index.html
- web/html/element/input/date/index.html
- web/html/element/input/number/index.html
- web/html/element/input/range/index.html
- web/html/element/input/search/index.html
- web/html/element/input/tel/index.html
- web/html/element/track/index.html
- web/svg/attribute/class/index.html
- web/svg/attribute/cx/index.html
- web/svg/attribute/cy/index.html
- web/svg/attribute/letter-spacing/index.html
- web/svg/attribute/repeatcount/index.html
- web/svg/attribute/x/index.html
- web/svg/attribute/y/index.html
</details>

**Comment by sashasushko** [comment]
I'll figure with it

**Comment by leon-win** [comment]
Done :ok:
