### ISSUE TITLE
{{page}} macro calls on simplified Chinese pages

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3893]
Quoting **SphinxKnight**:
> The old transclusion macro {{page}} has been removed and is not working anymore.

This problem has also been reported several times (e.g. #3680, #3325, #4445 and #1697, the latter seems to have been fixed), thought I'd file an issue with all occurrences. Found 218 results in 135 files:

<details>
<summary>65 pages in Web/API:</summary>

- web/api/audiobuffersourcenode/buffer/index.html
- web/api/audiolistener/index.html
- web/api/audioparamdescriptor/index.html
- web/api/audiotrack/index.html
- web/api/batterymanager/index.html
- web/api/biquadfilternode/index.html
- web/api/channelmergernode/index.html
- web/api/customevent/index.html
- web/api/datatransfer/dropeffect/index.html
- web/api/datatransfer/effectallowed/index.html
- web/api/datatransfer/getdata/index.html
- web/api/datatransfer/items/index.html
- web/api/datatransfer/setdata/index.html
- web/api/datatransfer/setdragimage/index.html
- web/api/datatransfer/types/index.html
- web/api/datatransferitem/kind/index.html
- web/api/document/index.html
- web/api/document/dragend_event/index.html
- web/api/document/dragenter_event/index.html
- web/api/document/dragleave_event/index.html
- web/api/document/dragover_event/index.html
- web/api/document/drop_event/index.html
- web/api/dynamicscompressornode/index.html
- web/api/element/animate/index.html
- web/api/element/mouseup_event/index.html
- web/api/element/wheel_event/index.html
- web/api/filereader/readystate/index.html
- web/api/filerequest/index.html
- web/api/filesystemdirectoryreader/readentries/index.html
- web/api/gainnode/index.html
- web/api/gainnode/gain/index.html
- web/api/geolocation_api/index.html
- web/api/globaleventhandlers/onanimationend/index.html
- web/api/idbfactory/open/index.html
- web/api/mediaelementaudiosourcenode/index.html
- web/api/mediastreamaudiosourcenode/index.html
- web/api/notification/index.html
- web/api/notification/actions/index.html
- web/api/notification/body/index.html
- web/api/notification/dir/index.html
- web/api/notification/notification/index.html
- web/api/notification/onclick/index.html
- web/api/notification/onclose/index.html
- web/api/notification/onerror/index.html
- web/api/notification/onshow/index.html
- web/api/notification/permission/index.html
- web/api/periodicwave/index.html
- web/api/rtcpeerconnection/connectionstate/index.html
- web/api/rtcpeerconnection/icegatheringstate/index.html
- web/api/rtcpeerconnection/rtcpeerconnection/index.html
- web/api/rtcrtptransceiver/direction/index.html
- web/api/rtcstatsreport/index.html
- web/api/rtctrackevent/rtctrackevent/index.html
- web/api/screen/index.html
- web/api/scriptprocessornode/index.html
- web/api/waveshapernode/index.html
- web/api/waveshapernode/curve/index.html
- web/api/waveshapernode/oversample/index.html
- web/api/webgl_api/using_extensions/index.html
- web/api/webglrenderingcontext/index.html
- web/api/webglrenderingcontext/getextension/index.html
- web/api/webglrenderingcontext/getsupportedextensions/index.html
- web/api/window/ondevicemotion/index.html
- web/api/window/ondeviceorientation/index.html
- web/api/xmlhttprequest/response/index.html
</details>

<details>
<summary>36 pages in Web/JavaScript:</summary>

- web/javascript/data_structures/index.html
- web/javascript/guide/indexed_collections/index.html
- web/javascript/reference/global_objects/arraybuffer/index.html
- web/javascript/reference/global_objects/asyncfunction/index.html
- web/javascript/reference/global_objects/bigint/tolocalestring/index.html
- web/javascript/reference/global_objects/dataview/index.html
- web/javascript/reference/global_objects/date/index.html
- web/javascript/reference/global_objects/date/tolocaledatestring/index.html
- web/javascript/reference/global_objects/date/tolocalestring/index.html
- web/javascript/reference/global_objects/date/tolocaletimestring/index.html
- web/javascript/reference/global_objects/error/index.html
- web/javascript/reference/global_objects/evalerror/index.html
- web/javascript/reference/global_objects/function/index.html
- web/javascript/reference/global_objects/generatorfunction/index.html
- web/javascript/reference/global_objects/internalerror/index.html
- web/javascript/reference/global_objects/intl/collator/index.html
- web/javascript/reference/global_objects/intl/datetimeformat/index.html
- web/javascript/reference/global_objects/intl/listformat/index.html
- web/javascript/reference/global_objects/intl/numberformat/index.html
- web/javascript/reference/global_objects/intl/pluralrules/index.html
- web/javascript/reference/global_objects/intl/relativetimeformat/index.html
- web/javascript/reference/global_objects/number/index.html
- web/javascript/reference/global_objects/number/parseint/index.html
- web/javascript/reference/global_objects/number/tolocalestring/index.html
- web/javascript/reference/global_objects/rangeerror/index.html
- web/javascript/reference/global_objects/referenceerror/index.html
- web/javascript/reference/global_objects/sharedarraybuffer/index.html
- web/javascript/reference/global_objects/string/index.html
- web/javascript/reference/global_objects/syntaxerror/index.html
- web/javascript/reference/global_objects/typedarray/index.html
- web/javascript/reference/global_objects/typedarray/tolocalestring/index.html
- web/javascript/reference/global_objects/typeerror/index.html
- web/javascript/reference/global_objects/urierror/index.html
- web/javascript/reference/global_objects/weakset/index.html
- web/javascript/reference/global_objects/webassembly/module/index.html
- web/javascript/typed_arrays/index.html
</details>

<details>
<summary>Misc, 30 pages in Web/CSS, Web/HTML, Web/SVG, MDN and Mozilla:</summary>

- web/css/@media/index.html
- web/css/css_transforms/using_css_transforms/index.html
- web/css/display/index.html
- web/css/reference/index.html
- web/css/shorthand_properties/index.html
- web/html/element/img/index.html
- web/html/element/input/month/index.html
- web/html/element/input/range/index.html
- web/html/element/input/search/index.html
- web/html/element/input/time/index.html
- web/html/element/input/url/index.html
- web/html/element/input/week/index.html
- web/http/headers/content-security-policy/base-uri/index.html
- web/http/headers/content-security-policy/child-src/index.html
- web/http/headers/content-security-policy/connect-src/index.html
- web/http/headers/content-security-policy/font-src/index.html
- web/http/headers/content-security-policy/script-src-elem/index.html
- web/http/headers/content-security-policy/worker-src/index.html
- web/http/headers/feature-policy/autoplay/index.html
- web/http/headers/feature-policy/camera/index.html
- web/svg/attribute/accent-height/index.html
- web/svg/attribute/fy/index.html
- web/svg/attribute/height/index.html
- web/svg/attribute/repeatcount/index.html
- web/svg/attribute/stddeviation/index.html
- web/svg/attribute/width/index.html
- web/svg/attribute/x/index.html
- web/svg/attribute/y/index.html
- *(mdn/structures/macros/other/index.html — looks like occurrences were found here because the page shows examples of the macro in use, so it seems that this file can be "ignored" for now)*
- mozilla/add-ons/webextensions/native_messaging/index.html
</details>

**Comment by yin1999** [comment]
Web/API:

- Web/API/AudioBufferSourceNode/buffer #6623

**Comment by fwqaaq** [comment]
* files/zh-cn/web/api/document/dragenter_event/index.md
* files/zh-cn/web/api/document/dragleave_event/index.md
... The documents about drag... should have been removed from `document` directory.

**Comment by yin1999** [comment]
Done
