### ISSUE TITLE
{{page}} macro calls on Japanese pages

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3895]
Quoting **SphinxKnight**:
> The old transclusion macro {{page}} has been removed and is not working anymore.

Filing this issue for all `{{page}}` macro calls in `ja`, found 135 results in 89 files:

<details>
<summary>47 pages in Web/API:</summary>

- web/api/audiolistener/index.html
- web/api/audioprocessingevent/index.html
- web/api/audiotrack/index.html
- web/api/baseaudiocontext/createscriptprocessor/index.html
- web/api/channelmergernode/index.html
- web/api/convolvernode/index.html
- web/api/customevent/index.html
- web/api/datatransfer/cleardata/index.html
- web/api/datatransfer/dropeffect/index.html
- web/api/datatransfer/effectallowed/index.html
- web/api/datatransfer/getdata/index.html
- web/api/datatransfer/items/index.html
- web/api/datatransfer/setdata/index.html
- web/api/datatransfer/setdragimage/index.html
- web/api/datatransfer/types/index.html
- web/api/delaynode/index.html
- web/api/delaynode/delaytime/index.html
- web/api/dragevent/index.html
- web/api/filereadersync/readasbinarystring/index.html
- web/api/filereadersync/readasdataurl/index.html
- web/api/filereadersync/readastext/index.html
- web/api/geolocation_api/index.html
- web/api/navigator/getusermedia/index.html
- web/api/navigator/getvrdisplays/index.html
- web/api/notification/notification/index.html
- web/api/notifications_api/using_the_notifications_api/index.html
- web/api/pannernode/index.html
- web/api/pannernode/coneinnerangle/index.html
- web/api/pannernode/coneouterangle/index.html
- web/api/screen/index.html
- web/api/scriptprocessornode/index.html
- web/api/stereopannernode/index.html
- web/api/vrdisplay/capabilities/index.html
- web/api/vrdisplay/displayid/index.html
- web/api/vrdisplay/stageparameters/index.html
- web/api/vrframedata/index.html
- web/api/vrframedata/leftprojectionmatrix/index.html
- web/api/vrframedata/leftviewmatrix/index.html
- web/api/vrframedata/vrframedata/index.html
- web/api/vrlayerinit/rightbounds/index.html
- web/api/vrlayerinit/source/index.html
- web/api/webgl_api/using_extensions/index.html
- web/api/webglrenderingcontext/index.html
- web/api/webxr_device_api/geometry/index.html
- web/api/xmlhttprequest/response/index.html
- web/api/xmlhttprequest/responsetype/index.html
- web/api/xrreferencespace/index.html
</details>

<details>
<summary>28 pages in Web/HTML and Web/HTTP:</summary>

- web/html/element/img/index.html
- web/html/element/input/index.html
- web/html/element/input/date/index.html
- web/html/element/input/datetime-local/index.html
- web/html/element/input/email/index.html
- web/html/element/input/month/index.html
- web/html/element/input/number/index.html
- web/html/element/input/password/index.html
- web/html/element/input/range/index.html
- web/html/element/input/search/index.html
- web/html/element/input/tel/index.html
- web/html/element/input/time/index.html
- web/html/element/input/url/index.html
- web/html/element/input/week/index.html
- web/html/element/track/index.html
- web/http/basics_of_http/mime_types/index.html
- web/http/headers/content-security-policy/base-uri/index.html
- web/http/headers/content-security-policy/connect-src/index.html
- web/http/headers/content-security-policy/frame-src/index.html
- web/http/headers/content-security-policy/img-src/index.html
- web/http/headers/content-security-policy/manifest-src/index.html
- web/http/headers/content-security-policy/media-src/index.html
- web/http/headers/content-security-policy/object-src/index.html
- web/http/headers/content-security-policy/prefetch-src/index.html
- web/http/headers/content-security-policy/script-src/index.html
- web/http/headers/content-security-policy/script-src-elem/index.html
- web/http/headers/content-security-policy/style-src/index.html
- web/http/headers/content-security-policy/worker-src/index.html
</details>

<details>
<summary>Misc, 14 pages in Glossary, Mozilla, Web/CSS, Web/SVG and Web/XPath (edit: please see #4822 for dealing with the Tools section):</summary>

- glossary/denial_of_service/index.html
- mozilla/add-ons/webextensions/native_messaging/index.html
- mozilla/firefox/releases/44/index.html
- mozilla/firefox/releases/45/index.html
- mozilla/firefox/releases/46/index.html
- web/css/css_transforms/using_css_transforms/index.md
- web/css/max-block-size/index.md
- web/svg/attribute/x/index.html
- web/svg/attribute/y/index.html
- web/xpath/comparison_with_css_selectors/index.html
- tools/eyedropper/index.html
- tools/style_editor/index.html
- tools/tools_toolbox/index.html
- tools/web_console/the_command_line_interpreter/index.html
</details>

**Comment by mfuji09** [comment]
Completed!
