### ISSUE TITLE
{{page}} macro calls on Spanish pages [es]

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3898]
Quoting **SphinxKnight**:
> The old transclusion macro {{page}} has been removed and is not working anymore.

The `{{page}}` macro must be replaced by the **content** it was meant to transclude, with the ultimate goal being to match locale files with the en-US pages.

As with searches conducted in all other locales, I've excluded the `conflicting` and `orphaned` folders since they require "special handling". There are 108 results in 56 files for `es` so far:

<details>
<summary>25 pages in Web/API:</summary>

- web/api/battery_status_api/index.html
- web/api/batterymanager/index.html
- web/api/batterymanager/charging/index.html
- web/api/batterymanager/chargingtime/index.html
- web/api/batterymanager/dischargingtime/index.html
- web/api/batterymanager/level/index.html
- web/api/batterymanager/onchargingchange/index.html
- web/api/batterymanager/onlevelchange/index.html
- web/api/customevent/index.html
- web/api/document/index.html
- web/api/dragevent/index.html
- web/api/element/animate/index.html
- web/api/element/wheel_event/index.html
- web/api/filereader/readasarraybuffer/index.html
- web/api/filereader/readasdataurl/index.html
- web/api/geolocation_api/index.html
- web/api/mediastreamaudiosourcenode/index.html
- web/api/notification/body/index.html
- web/api/notification/dir/index.html
- web/api/notification/icon/index.html
- web/api/notification/onclick/index.html
- web/api/notification/permission/index.html
- web/api/notification/requestpermission/index.html
- web/api/notifications_api/using_the_notifications_api/index.html
- web/api/screen/index.html
</details>

<details>
<summary>19 pages in Web/JavaScript:</summary>

- web/javascript/reference/index.html
- web/javascript/reference/global_objects/arraybuffer/index.html
- web/javascript/reference/global_objects/asyncfunction/index.html
- web/javascript/reference/global_objects/date/index.html
- web/javascript/reference/global_objects/date/tolocaledatestring/index.html
- web/javascript/reference/global_objects/evalerror/index.html
- web/javascript/reference/global_objects/intl/numberformat/index.html
- web/javascript/reference/global_objects/number/parsefloat/index.html
- web/javascript/reference/global_objects/object/index.html
- web/javascript/reference/global_objects/promise/index.html
- web/javascript/reference/global_objects/proxy/index.html
- web/javascript/reference/global_objects/rangeerror/index.html
- web/javascript/reference/global_objects/set/index.html
- web/javascript/reference/global_objects/string/localecompare/index.html
- web/javascript/reference/global_objects/symbol/index.html
- web/javascript/reference/global_objects/syntaxerror/index.html
- web/javascript/reference/global_objects/urierror/index.html
- web/javascript/reference/global_objects/weakmap/index.html
- web/javascript/reference/global_objects/weakset/index.html
</details>

<details>
<summary>Misc, Web/CSS, Web/HTML and MDN (edit: please see #4822 for dealing with the Tools section):</summary>

- web/css/max-block-size/index.html
- web/css/shorthand_properties/index.html
- web/html/element/input/date/index.html
- web/html/element/input/email/index.html
- web/html/element/input/number/index.html
- web/html/element/track/index.html
- *(mdn/structures/macros/other/index.html — looks like occurrences were found here because the page shows examples of the macro in use, so it seems that this file can be "ignored" for now)*
</details>

Dividimos este Issue:
- [x] #3927 
- [x] #3936
- [x] #3937

**Comment by JuanVqz** [comment]
I didn't find how to search per page, at the end I find by match.

<details>
<summary>I have counted  36 matches in Web/API</summary>
files/es/web/api/filereader/readasarraybuffer/index.html:27:<p>{{page("/es-ES/docs/Web/API/FileReader","Specifications")}}</p>
files/es/web/api/filereader/readasarraybuffer/index.html:31:<p>{{page("/es-ES/docs/Web/API/FileReader","Browser compatibility")}}</p>
files/es/web/api/filereader/readasdataurl/index.html:58:<p>{{page("/en-US/docs/Web/API/FileReader","Specifications")}}</p>
files/es/web/api/filereader/readasdataurl/index.html:62:<p>{{page("/en-US/docs/Web/API/FileReader","Browser compatibility")}}</p>
files/es/web/api/notifications_api/using_the_notifications_api/index.html:287:<p>{{page("/en-US/Web/API/Notification","Browser compatibility")}}</p>
files/es/web/api/mediastreamaudiosourcenode/index.html:51:<p>{{page("/en-US/docs/Web/API/AudioContext.createMediaStreamSource","Example")}}</p>
files/es/web/api/document/index.html:79:<p>{{page("/en-US/docs/Web/API/ParentNode","Properties")}}</p>
files/es/web/api/geolocation_api/index.html:67:<p>{{page("/en-US/docs/DOM/window.navigator.geolocation.getCurrentPosition","PositionOptions")}}</p>
files/es/web/api/geolocation_api/index.html:94:<p>{{page("/en-US/docs/DOM/window.navigator.geolocation.getCurrentPosition","Position")}}</p>
files/es/web/api/geolocation_api/index.html:96:<p>{{page("/en-US/docs/DOM/window.navigator.geolocation.getCurrentPosition","Coordinates")}}</p>
files/es/web/api/geolocation_api/index.html:107:<p>{{page("/en-US/docs/DOM/window.navigator.geolocation.getCurrentPosition","PositionError")}}</p>
files/es/web/api/screen/index.html:61:<p>{{page("/en-US/docs/Web/API/EventTarget","Methods")}}</p>
files/es/web/api/battery_status_api/index.html:32:<p>{{page("/en-US/docs/Web/API/BatteryManager","Specifications")}}</p>
files/es/web/api/battery_status_api/index.html:34:<p>{{page("/en-US/docs/Web/API/BatteryManager","Browser_compatibility")}}</p>
files/es/web/api/element/wheel_event/index.html:33:<p>{{page("/en-US/docs/Web/API/WheelEvent", "Properties")}}</p>
files/es/web/api/element/wheel_event/index.html:37:<p>{{page("/en-US/docs/Web/API/MouseEvent", "Properties")}}</p>
files/es/web/api/element/wheel_event/index.html:41:<p>{{page("/en-US/docs/Web/API/UIEvent", "Properties")}}</p>
files/es/web/api/element/wheel_event/index.html:45:<p>{{page("/en-US/docs/Web/API/Event", "Properties")}}</p>
files/es/web/api/element/wheel_event/index.html:53:<p>{{page("/en-US/docs/Web/API/WheelEvent", "Methods")}}</p>
files/es/web/api/element/wheel_event/index.html:57:<p>{{page("/en-US/docs/Web/API/MouseEvent", "Methods")}}</p>
files/es/web/api/element/wheel_event/index.html:61:<p>{{page("/en-US/docs/Web/API/UIEvent", "Methods")}}</p>
files/es/web/api/element/wheel_event/index.html:65:<p>{{page("/en-US/docs/Web/API/Event", "Methods")}}</p>
files/es/web/api/dragevent/index.html:110:<p>{{page("/en-US/docs/Web/API/DataTransfer", "Ver también")}}</p>
files/es/web/api/batterymanager/chargingtime/index.html:19:<p>{{page("/en-US/docs/Web/API/BatteryManager","Specifications")}}</p>
files/es/web/api/batterymanager/chargingtime/index.html:21:<p>{{page("/en-US/docs/Web/API/BatteryManager","Browser_compatibility")}}</p>
files/es/web/api/batterymanager/charging/index.html:21:<p>{{page("/en-US/docs/Web/API/BatteryManager","Specifications")}}</p>
files/es/web/api/batterymanager/charging/index.html:23:<p>{{page("/en-US/docs/Web/API/BatteryManager","Browser_compatibility")}}</p>
files/es/web/api/batterymanager/onlevelchange/index.html:13:<p>{{page("/en-US/docs/Web/API/BatteryManager","Specifications")}}</p>
files/es/web/api/batterymanager/onlevelchange/index.html:15:<p>{{page("/en-US/docs/Web/API/BatteryManager","Browser_compatibility")}}</p>
files/es/web/api/batterymanager/onchargingchange/index.html:13:<p>{{page("/en-US/docs/Web/API/BatteryManager","Specifications")}}</p>
files/es/web/api/batterymanager/onchargingchange/index.html:15:<p>{{page("/en-US/docs/Web/API/BatteryManager","Browser_compatibility")}}</p>
files/es/web/api/batterymanager/level/index.html:15:<p>{{page("/es/docs/Web/API/BatteryManager","Especificaciones")}}</p>
files/es/web/api/batterymanager/level/index.html:17:<p>{{page("/es/docs/Web/API/BatteryManager","Compatibilidad")}}</p>
files/es/web/api/batterymanager/index.html:50:<p>{{page("/en-US/docs/Web/API/EventTarget","Methods")}}</p>
files/es/web/api/batterymanager/dischargingtime/index.html:22:<p>{{page("/en-US/docs/Web/API/BatteryManager","Specifications")}}</p>
files/es/web/api/batterymanager/dischargingtime/index.html:24:<p>{{page("/en-US/docs/Web/API/BatteryManager","Browser_compatibility")}}</p>

</details>

<details>
<summary>I have counted  34 matches in Web/Javascript</summary>
files/es/web/javascript/reference/global_objects/syntaxerror/index.html:50:<div>{{page('/es/docs/Web/JavaScript/Referencia/Objetos_globales/SyntaxError/prototype', 'Propiedades')}}</div>
files/es/web/javascript/reference/global_objects/syntaxerror/index.html:54:<div>{{page('/es/docs/Web/JavaScript/Referencia/Objetos_globales/SyntaxError/prototype', 'Metodos')}}</div>
files/es/web/javascript/reference/global_objects/intl/numberformat/index.html:87:<div>{{page('en-US/docs/JavaScript/Reference/Global_Objects/NumberFormat/prototype','Properties')}}</div>
files/es/web/javascript/reference/global_objects/intl/numberformat/index.html:93:{{page('en-US/docs/JavaScript/Reference/Global_Objects/NumberFormat/prototype','Methods')}}</div>
files/es/web/javascript/reference/global_objects/intl/numberformat/index.html:189:<p>{{page('en-US/docs/JavaScript/Reference/Global_Objects/Intl','See_also')}}</p>
files/es/web/javascript/reference/global_objects/proxy/index.html:49:<div>{{page('/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler', 'Methods') }}</div>
files/es/web/javascript/reference/global_objects/asyncfunction/index.html:58:<div>{{page('/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction/prototype', 'Properties')}}</div>
files/es/web/javascript/reference/global_objects/urierror/index.html:50:<div>{{page('/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError/prototype', 'Properties')}}</div>
files/es/web/javascript/reference/global_objects/urierror/index.html:54:<div>{{page('/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError/prototype', 'Methods')}}</div>
files/es/web/javascript/reference/global_objects/number/parsefloat/index.html:27:<p>{{page("en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat", "Parameters")}}</p>
files/es/web/javascript/reference/global_objects/number/parsefloat/index.html:31:<p>{{page("en-US/docs/Web/JavaScript/Reference/Global_Objects/parseFloat", "Return value")}}</p>
files/es/web/javascript/reference/global_objects/weakmap/index.html:52:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/WeakMap/prototype','Properties')}}</p>
files/es/web/javascript/reference/global_objects/weakmap/index.html:56:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/WeakMap/prototype','Methods')}}</p>
files/es/web/javascript/reference/global_objects/string/localecompare/index.html:26:<div>{{page('/en-US/docs/Web/JavaScript/Reference/Global_Objects/Collator', 'Parameters')}}</div>
files/es/web/javascript/reference/global_objects/date/tolocaledatestring/index.html:32:<div>{{page('/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat', 'Parameters')}}</div>
files/es/web/javascript/reference/global_objects/rangeerror/index.html:49:<div>{{page('/es/docs/Web/JavaScript/Reference/Global_Objects/RangeError/prototype', 'Propiedades')}}</div>
files/es/web/javascript/reference/global_objects/rangeerror/index.html:53:<div>{{page('/es/docs/Web/JavaScript/Reference/Global_Objects/RangeError/prototype', 'Métodos')}}</div>
files/es/web/javascript/reference/global_objects/symbol/index.html:124:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/Symbol/prototype','Properties')}}</p>
files/es/web/javascript/reference/global_objects/symbol/index.html:128:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/Symbol/prototype','Methods')}}</p>
files/es/web/javascript/reference/global_objects/arraybuffer/index.html:77:<p>{{page('es/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/prototype','Propiedades')}}</p>
files/es/web/javascript/reference/global_objects/arraybuffer/index.html:81:<p>{{page('es/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/prototype','Métodos')}}</p>
files/es/web/javascript/reference/global_objects/weakset/index.html:50:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/WeakSet/prototype','Properties')}}</p>
files/es/web/javascript/reference/global_objects/weakset/index.html:54:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/WeakSet/prototype','Methods')}}</p>
files/es/web/javascript/reference/global_objects/object/index.html:107:<div>{{page('/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype', 'Properties') }}</div>
files/es/web/javascript/reference/global_objects/object/index.html:111:<div>{{page('/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/prototype', 'Methods') }}</div>
files/es/web/javascript/reference/global_objects/set/index.html:58:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/Set/prototype','Properties')}}</p>
files/es/web/javascript/reference/global_objects/set/index.html:62:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/Set/prototype','Methods')}}</p>
files/es/web/javascript/reference/global_objects/evalerror/index.html:49:<div>{{page('/es/docs/Web/JavaScript/Referencia/Objetos_globales/Error/prototype', 'Properties')}}</div>
files/es/web/javascript/reference/global_objects/evalerror/index.html:53:<div>{{page('/es/docs/Web/JavaScript/Referencia/Objetos_globales/Error/prototype', 'Métodos')}}</div>
files/es/web/javascript/reference/global_objects/promise/index.html:86:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/Promise/prototype','Properties')}}</p>
files/es/web/javascript/reference/global_objects/promise/index.html:90:<p>{{page('en-US/Web/JavaScript/Reference/Global_Objects/Promise/prototype','Methods')}}</p>
files/es/web/javascript/reference/index.html:13:<div>{{page('/es/docs/Web/JavaScript/Referencia/Objetos_globales', 'Objetos_est.C3.A1ndar_(por_categor.C3.ADa)')}}</div>
files/es/web/javascript/reference/index.html:17:<p>{{page('/es/docs/Web/JavaScript/Referencia/Sentencias', 'Statements_and_declarations_by_category')}}</p>
files/es/web/javascript/reference/index.html:21:<p>{{page('/es/docs/Web/JavaScript/Referencia/Operadores', 'Expressions_and_operators_by_category')}}</p>

</details>


<details>
<summary>I have counted  13 matches in Web/CSS and Web/HTML</summary>
files/es/web/css/max-block-size/index.html:48:<p>{{page("/en-US/docs/Web/CSS/max-width", "Values")}}</p>
files/es/web/css/shorthand_properties/index.html:145:<p>{{page("/en-US/docs/Learn/CSS/Introduction_to_CSS/Cascade_and_inheritance", "Controlling_inheritance")}}</p>
files/es/web/html/element/input/number/index.html:98:<p id="htmlattrdeflist">{{page("/en-US/docs/Web/HTML/Element/input/text", "list", 0, 1, 2)}}</p>
files/es/web/html/element/input/number/index.html:112:<p>{{page("/en-US/docs/Web/HTML/Element/input/text", "placeholder", 0, 1, 2)}}</p>
files/es/web/html/element/input/number/index.html:114:<p>{{page("/en-US/docs/Web/HTML/Element/input/text", "readonly", 0, 1, 2)}}</p>
files/es/web/html/element/input/date/index.html:85:<p>{{page("/en-US/docs/Web/HTML/Element/input/number", "step-include")}}</p>
files/es/web/html/element/input/date/index.html:136:<p>{{page("/en-US/docs/Web/HTML/Element/input/number", "step-include")}}</p>
files/es/web/html/element/input/email/index.html:112:<p id="htmlattrdeflist">{{page("/es/docs/Web/HTML/Element/input/text", "list", 0, 1, 2)}}</p>
files/es/web/html/element/input/email/index.html:136:<p>{{page("/es/docs/Web/HTML/Element/input/text", "pattern-include")}}</p>
files/es/web/html/element/input/email/index.html:140:<p>{{page("/es/docs/Web/HTML/Element/input/text", "placeholder", 0, 1, 2)}}</p>
files/es/web/html/element/input/email/index.html:142:<p>{{page("/es/docs/Web/HTML/Element/input/text", "readonly", 0, 1, 2)}}</p>
files/es/web/html/element/input/email/index.html:144:<p>{{page("/es/docs/Web/HTML/Element/input/text", "size", 0, 1, 2)}}</p>
files/es/web/html/element/track/index.html:120:<p>{{page("/es/docs/Web/API/TextTrack/cuechange_event", "En el elemento track")}}</p>

</details>

Then I did MND and Tools folders manually. :disappointed: 




<details>
<summary>@cw118 Also, I found 13 more matches on WebAPI/notification, Web/API/customevent and Web/API/emenent.</summary>

files/es/web/api/notification/onclick/index.html:54:<p>{{Page("/en-US/docs/Web/API/Notification","Browser compatibility")}}</p>
files/es/web/api/notification/permission/index.html:176:<p>{{Page("/en-US/docs/Web/API/Notifications_API", "Firefox OS notes")}}</p>
files/es/web/api/notification/permission/index.html:180:<p>{{Page("/en-US/docs/Web/API/Notifications_API", "Chrome notes")}}</p>
files/es/web/api/notification/permission/index.html:184:<p>{{Page("/en-US/docs/Web/API/Notifications_API", "Safari notes")}}</p>
files/es/web/api/notification/body/index.html:56:<p>{{Page("/en-US/docs/Web/API/Notification","Browser compatibility")}}</p>
files/es/web/api/notification/icon/index.html:51:<p>{{Page("/en-US/docs/Web/API/Notification","Browser compatibility")}}</p>
files/es/web/api/notification/dir/index.html:52:<p>{{Page("/en-US/docs/Web/API/Notification","Browser compatibility")}}</p>
files/es/web/api/notification/requestpermission/index.html:129:<p>{{Page("/en-US/docs/Web/API/Notifications_API", "Firefox OS notes")}}</p>
files/es/web/api/notification/requestpermission/index.html:133:<p>{{Page("/en-US/docs/Web/API/Notifications_API", "Chrome notes")}}</p>
files/es/web/api/notification/requestpermission/index.html:137:<p>{{Page("/en-US/docs/Web/API/Notifications_API", "Safari notes")}}</p>
files/es/web/api/customevent/index.html:33:<p>{{Page("/es/docs/Web/API/Event", "Propiedades")}}</p>
files/es/web/api/customevent/index.html:46:<p>{{Page("/es/docs/Web/API/Event", "Métodos")}}</p>
files/es/web/api/element/animate/index.html:39: {{Page("/en-US/docs/Web/API/Web_Animations_API/Animation_timing_properties", "Properties")}}</dd>
</details>

**Comment by cw118** [comment]
@JuanVqz I believe <kbd>Ctrl + F</kbd> is a universal "search shortcut" that you can try in a file in your code editor, but I'm not entirely sure. 

Just for reference, I used the regexp `\{\{\s*[pP]age\s*\(` to search for occurrences of this macro since it's not always written as `{{page}}` (e.g. `{{ Page }}`), so I tried to ensure various "styles" of this macro would be detected.

While I don't speak Spanish myself, I think removing these macros (and it'd likely be best to replace them with links as well) is simple enough that I could get by — please let me know if I can help with this :)

**Comment by cw118** [comment]
And feel free to split the effort across multiple PRs, or possibly even create more issues to keep track of specific sections!

**Comment by JuanVqz** [comment]
> And feel free to split the effort across multiple PRs, or possibly even create more issues to keep track of specific sections!

you are right, that sounds reasonable

**Comment by SphinxKnight** [comment]
@JuanVqz for what it's worth, I'm using VS Code and looking for the following regexp across the mdn/translated-content folders:
`\{\{[ ]?page`
An example of such a search in fr/web/html: 
![image](https://user-images.githubusercontent.com/2413436/151696630-bdafd644-dbe0-4963-a0ec-56bb09e17ba9.png)

**Comment by JuanVqz** [comment]
Dividimos este Issue:
- [ ] #3927 
- [ ] #3936
- [ ] #3937

**Comment by Graywolf9** [comment]
Finally done! Updating pages and macro removed
