### ISSUE TITLE
Issue with "Операторы сравнения": (short summary here please)

### ISSUE THREAD

**Issue by ilyapishchulin** [mdn/translated-content#3900]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness

#### What information was incorrect, unhelpful, or incomplete?
Block outside the layout

#### Specific section or headline?
Table of contents

<img width="1218" alt="Screenshot 2022-01-30 at 00 39 20" src="https://user-images.githubusercontent.com/45998835/151678364-992290cc-b513-4879-8ee5-7265af71a3f6.png">

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/javascript/equality_comparisons_and_sameness`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Equality_comparisons_and_sameness
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/equality_comparisons_and_sameness/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b9ea89d87d177efe9b4e1610d4916f2e1146bbd7
* Document last modified: 2022-01-28T20:19:48.000Z

</details>

**Comment by sashasushko** [comment]
Fixed after redesign
