### ISSUE TITLE
Issue with "mask-image": (short summary here please)

### ISSUE THREAD

**Issue by ssssgs** [mdn/translated-content#3902]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/mask-image

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/css/mask-image`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/mask-image
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/mask-image/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b9ea89d87d177efe9b4e1610d4916f2e1146bbd7
* Document last modified: 2022-01-28T20:19:48.000Z

</details>

**Comment by SphinxKnight** [comment]
@ssssgs please provide more information about the issue you're facing.
