### ISSUE TITLE
Issue with "backdrop-filter": lorempixel.com is down, no background image on live sample

### ISSUE THREAD

**Issue by egorantonov** [mdn/translated-content#3930]
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/backdrop-filter#результат

#### What information was incorrect, unhelpful, or incomplete?
[lorempixel.com](lorempixel.com) site is down for now (31.01.2021 17:00 UTC), background image is empty in the example section for russian version

#### Specific section or headline?
example for 'ru' (Russian) language is obsolete, site [lorempixel.com](lorempixel.com) is down

#### What did you expect to see?
background image in the example section

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/css/backdrop-filter`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/backdrop-filter#результат
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/backdrop-filter/index.html
* Last commit: https://github.com/mdn/translated-content/commit/509c3fd223e0370e1ae2adc937c67b336d85df87
* Document last modified: 2022-01-30T16:28:58.000Z

</details>

**Comment by cw118** [comment]
The same issue is on the pages of the `fr`, `pt-BR` and `zh-CN` locales as well.

Some also have an "incorrect" `{{SeeCompatTable}}` and are missing `backdrop-filter: revert;` in the CSS example code block at the top.

**Comment by yin1999** [comment]
`l10n-zh` is resolved in #4801 (haven't been deployed for now).

**Comment by c0ncentus** [comment]
https://developer.mozilla.org/fr/docs/Web/CSS/filter
(I suppose english content)
no background image on live sample on all the page !
![image](https://user-images.githubusercontent.com/25374826/165820158-9c3697f5-4885-4d69-a325-2a43f95a4bf8.png)

**Comment by Graywolf9** [comment]
The whole article was updated for `es` in  #11256

Thanks for the ping @cw118

**Comment by sashasushko** [comment]
As I'm seeing, the other locales pull requests were merged. In `ru` locale, this example also was fixed. @egorantonov thanks for report 🙏
