### ISSUE TITLE
{{page}} macro calls on Spanish pages | 19 pages in Web/Javascript: [es]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#3936]
@mdn/yari-content-es  podriamos asignar por página en lugar de que una persona haga todas (por que si esta pesado).

Hola, todo mundo es bienvenido para traducir una o más paginas, solo por favor,
1. comenta en este issue que página deseas traducir tomando como base la versión  en inglés y te la asignaremos,
2. una vez concluido abre un PR, y cuando se apruebe,
3. chequearemos la página como hecha. saludos!

- [x] #4108 @Vallejoanderson
- [x] #4126 @Vallejoanderson
- [x] #4163 @Vallejoanderson
- [x] #4177 @Vallejoanderson (In progress)
- [x] #4319
- [x] #4357
- [x] #4154 @JuanVqz 
- [x] #4245 @JuanVqz 
- [x] #4366
- [x] #4391 
- [x] #4164
- [x] #4361
- [x] #4168
- [x] #4320
- [x] #4618
- [x] #4532
- [x] #4322
- [x] #4180 @JuanVqz 
- [x] #4136 @JuanVqz 
- [x] #6607

https://github.com/mdn/translated-content/issues/3898 es el issue principal y esté issue es 2/3

**Comment by JuanVqz** [comment]
@Graywolf9 que pasa?

**Comment by JuanVqz** [comment]
> 

Gracias @Graywolf9, Bien ahi!

**Comment by JuanVqz** [comment]
ya podemos cerrar esto entonces @Graywolf9 vdd?

**Comment by Graywolf9** [comment]
Sí, muchas gracias a todos por su trabajo!

**Comment by JuanVqz** [comment]
yey!!! se siente genial terminar algo :muscle: bien equipo!!
