### ISSUE TITLE
{{page}} macro calls on Spanish pages | 12 pages in Web/CSS, Web/HTML, MDN and Tools: [es]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#3937]
@mdn/yari-content-es  podriamos asignar por página en lugar de que una persona haga todas (por que si esta pesado).

Hola, todo mundo es bienvenido para traducir una o más paginas, solo por favor,
1. comenta en este issue que página deseas traducir tomando como base la versión  en inglés y te la asignaremos,
2. una vez concluido abre un PR, y cuando se apruebe,
3. chequearemos la página como hecha. saludos!

- [x] #5220
- [x] #6216
- [x] #4903
- [x] #5008  (@hectormoba)
- [x] https://github.com/mdn/translated-content/issues/6193 (@hectormoba)
- [x] #6217
- [x] 7. *(mdn/structures/macros/other/index.html — looks like occurrences were found here because the page shows examples of the macro in use, so it seems that this file can be "ignored" for now)*
- [x] ~~8. tools/page_inspector/index.html~~
- [x] ~~9. tools/style_editor/index.html~~
- [x] ~~10. tools/tools_toolbox/index.html~~
- [x] ~~#4601~~
- [x] ~~#4716~~

> Desde 8 al 12 se omiten por: https://github.com/mdn/translated-content/issues/3937#issuecomment-1081443683

https://github.com/mdn/translated-content/issues/3898 es el issue principal y esté issue es 3/3

**Comment by SphinxKnight** [comment]
Tools pages may be removed from the scope here :) (#4822)

**Comment by Eschiclers** [comment]
Me gustaría traducir el 1. web/css/max-block-size/index.html

**Comment by hectormoba** [comment]
El punto 3 ya se completó y el pull request está merged #4903. El punto 4 lo mando esta semana @JuanVqz

**Comment by JuanVqz** [comment]
> El punto 3 ya se completó y el pull request está merged #4903. El punto 4 lo mando esta semana @JuanVqz 

Gracias @hectormoba! En cuánto alguien del @mdn/yari-content-es tenga un tiempo lo revisamos, saludos!

**Comment by Graywolf9** [comment]
Completado! Muchas gracias a todos los que lo hicieron posible!

**Comment by JuanVqz** [comment]
Genial!!!
