### ISSUE TITLE
I would like to be added to the l10n-es team.

### ISSUE THREAD

**Issue by Vallejoanderson** [mdn/translated-content#3938]
Hi! @Rumyra I see that I need to open an issue for requesting to you to be part of the team in Github, I'm already working with @JuanVqz and the rest of the team.

Thank you in advance.

**Comment by Rumyra** [comment]
Hi @Vallejoanderson 👋 - you should have an invite 👍

**Comment by Vallejoanderson** [comment]
Thank you, @Rumyra !
