### ISSUE TITLE
Update codeowners to include Spanish (es) team

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#3952]
The `CODEOWNERS` file currently does not include the **mdn/yari-content-es** team as the code owner of `es` files (`/files/es/`).

Updating `CODEOWNERS` would also set up automatic review requests so that it doesn't have to be done manually.

**Comment by JuanVqz** [comment]
Hi! @cw118 we really appreciate your help, thank you!

**Comment by cw118** [comment]
Happy to help where I can :) I'm not really an expert, though I am learning more and more about MDN and their repo structures as I go, and these are some of the things I've noticed based on the files or configurations I saw for other locales. 

Aside from #3651, which is waiting to be merged (and could maybe use an update since new team members have joined?), this is everything that I've thought of so far.

**Comment by JuanVqz** [comment]
> Happy to help where I can :) I'm not really an expert, though I am learning more and more about MDN and their repo structures as I go, and these are some of the things I've noticed based on the files or configurations I saw for other locales.

Well, to me it means you have learned a lot, even better, you have been shared your knowledge with us as the newest in the `translated-content` community, you are always welcomed here, I know you won't translate the content to Spanish but you can help us doing several another things. (and you have been doing it, thank you)  

> Aside from #3651, which is waiting to be merged (and could maybe use an update since new team members have joined?), this is everything that I've thought of so far.

You are right! I'll add them. 

what do you think?, should I add a commit or ask Rumyra to do it? (I don't want to be disrespectful)

**Comment by cw118** [comment]
> what do you think?, should I add a commit or ask Rumyra to do it? (I don't want to be disrespectful)

In that case, I think the "safest" option would be to leave a comment or review?

**Comment by cw118** [comment]
Addressed in #3954.
