### ISSUE TITLE
fIssue with "initial": (short summary here please)

### ISSUE THREAD

**Issue by wewrgegtyj** [mdn/translated-content#3976]
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/initial

#### What information was incorrect, unhelpful, or incomplete?
![Screenshot from 2022-02-03 21-30-40](https://user-images.githubusercontent.com/77306153/152417939-e2347e1a-b093-4938-a9f4-a891b58640a7.png)
 
---

![image](https://user-images.githubusercontent.com/77306153/152418625-3e6efd05-c6f8-4beb-bd67-bd13802059ef.png)

Article paragraph.

#### Specific section or headline?

Article paragraph.

#### What did you expect to see?

Article paragraph.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/css/initial`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/initial
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/initial/index.html
* Last commit: https://github.com/mdn/translated-content/commit/10e4813adf44f94014e55c39f5af87adc9551ab8
* Document last modified: 2022-02-02T19:51:51.000Z

</details>

**Comment by myshov** [comment]
@wewrgegtyj спасибо! Исправили скролл
