### ISSUE TITLE
codeowners seems to don't be workiing for Spanish files, [es]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#3985]
Hi! I'm from the Spanish community, part of the @mdn/yari-content-es team, 
@cw118 helped me, letting me know that we could have filled the reviewer's section out automatically by adding a piece of code in the CODEOWNERS file. 

But it seems that it is not working, we are wondering if you know what we can do, in order to get it working.

Also, I don't know who correspond to solve this issue, so I'm going to ping the people I have seen who changed the CODEOWNERS file if I'm pinging wrong, sorry.

@fiji-flo (because I saw your name in the CODEOWNERS file)
@Rumyra (because you are my hero)

https://github.com/mdn/translated-content/blob/main/.github/CODEOWNERS#L50-L53

This is what we can see so far

![image](https://user-images.githubusercontent.com/7331511/152472661-2e3acf39-6d0e-444e-9201-6082b5ecc19e.png)

btw, @cw118 has done a great suggestion (at least I think that), what about to updated the CODEOWNERS file in order to pointing out to a maintainer, even another community, only to test it. 

Thank you in advance!

**Comment by Rumyra** [comment]
OK I think I figured it out - I hadn't set the team to auto assign prs - I have now, so someone from the team should be assigned for review automatically. I'll check back later to see if it's worked 👍

**Comment by cw118** [comment]
If I may, looks like automatic review requests are working now :) Thank you so much for looking into this **Rumyra** (didn't want to ping here)!

<details>
<summary>Before (it stops at `requested a review from as a code owner`):</summary>

![review-request-before](https://user-images.githubusercontent.com/87150472/152650627-9318a359-8695-4b85-911f-6b05d25d7e16.png)
</details>

<details>
<summary>Now/after (it goes on to `requested review from <reviewer-github-handle> (assigned from mdn/yari-content-es) and removed request for`):</summary>

![review-request-now](https://user-images.githubusercontent.com/87150472/152650678-ebfd3c09-6473-422c-b0d0-2e53f18e7e2a.png)
</details>
