### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by zhangran1** [mdn/translated-content#4]
The following section contains typo errors:

使用 JavaScript 开发交互
学习用时: 135–185 小时

预备知识
学习 CSS 前需要有基础的 HTML 知识，请至少学习完 HTML 介绍 再开始。

Original Reference: [MDN web learning page](https://developer.mozilla.org/zh-CN/docs/learn/Front-end_web_developer#%E5%AD%A6%E4%B9%A0%E8%B7%AF%E7%BA%BF%E5%9B%BE) 

Content to be corrected: replace CSS to JavaScript.

使用 JavaScript 开发交互
学习用时: 135–185 小时

预备知识
学习 JavaScript 前需要有基础的 HTML 知识，请至少学习完 HTML 介绍 再开始。

**Comment by CreaTorAlexander** [comment]
I have created #266  to fix this typo
