### ISSUE TITLE
Issue with "Режим совместимости (Quirks Mode) и стандартный ре…": (short summary here please)

### ISSUE THREAD

**Issue by mrumjancev** [mdn/translated-content#4008]
MDN URL: https://developer.mozilla.org/ru/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/html/quirks_mode_and_standards_mode`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/html/quirks_mode_and_standards_mode/index.html
* Last commit: https://github.com/mdn/translated-content/commit/6db6ef520b9f6246233f637f7c9b9b3ff282859a
* Document last modified: 2022-02-05T00:44:51.000Z

</details>

**Comment by myshov** [comment]
@mrumjancev привет! Подскажи, что именно не так с документацией?

**Comment by cw118** [comment]
Closing since no information was provided.
