### ISSUE TITLE
Content bug: <encodeURIComponent> encodeURIComponent

### ISSUE THREAD

**Issue by EthanGD** [mdn/translated-content#4024]
## What is the problem?

**encodeURIComponent("http://localhost/moa/Intranet/FileManagement/FMS/IT/test%20rename/error/frontend/%")
return 
Uncaught URIError: malformed URI sequence**

**Comment by SphinxKnight** [comment]
@EthanGD could you please provide the page of https://developer.mozilla.org that would need to be fixed?
