### ISSUE TITLE
Issue with "Push API": suspicious link in Examples section

### ISSUE THREAD

**Issue by alfem** [mdn/translated-content#4081]
MDN URL: https://developer.mozilla.org/es/docs/Web/API/Push_API

#### What information was incorrect, unhelpful, or incomplete?

"ServiceWorker Cookbook" links to serviceworke.rs which is unsafe.

#### Specific section or headline?

Examples

#### What did you expect to see?

A link to a secure page with examples.

#### Did you test this? If so, how?

Yes. When I click that link my browser alert of SSL_ERROR_BAD_CERT_DOMAIN.  Certificate is assigned to _buregdzinicasarajevo.com_ 

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/api/push_api`
* MDN URL: https://developer.mozilla.org/es/docs/Web/API/Push_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/api/push_api/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b0485d7a479d4e9e64283c12f17c91f68f7b0361
* Document last modified: 2022-02-10T00:54:14.000Z

</details>

**Comment by Vallejoanderson** [comment]
Hola, @alfem. Gracias por animarte a colaborar con MDN. :tada:  En efecto, al parecer el enlace esta caducado. En ese caso, podriamos usar el utilizado por la version [en ingles](https://developer.mozilla.org/en-US/docs/Web/API/Push_API). De igual forma te facilito el enlace: `https://github.com/mdn/serviceworker-cookbook`. Te animarias a realizar la modificacion en un PR? Si necesitas algun tipo de ayuda avisanos o puedes contactarnos a traves de [Matrix](https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org).

**Comment by alfem** [comment]
Aquí tienes el PR. Espero que sirva de ayuda.

**Comment by JuanVqz** [comment]
@alfem gracias por tu contribución!

Por cierto, si deseas seguir apoyando puedes:

* [Actualizar el contenido con la versión en inglés](https://github.com/mdn/translated-content/discussions/4029)
* [Revisar issues](https://github.com/mdn/translated-content/issues?q=is%3Aopen+is%3Aissue+label%3Al10n-es)
* [Unirte a nuestro equipo](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.
