### ISSUE TITLE
Issue with "Символ": (отсутствующая страница в Wikipedia)

### ISSUE THREAD

**Issue by it4joy** [mdn/translated-content#4084]
MDN URL: https://developer.mozilla.org/ru/docs/Glossary/Character

#### What information was incorrect, unhelpful, or incomplete?
В блоке "Связанные темы" первая по счету ссылка ( 'Character (computing)' ). При переходе видим: "В Википедии нет статьи с таким названием."

#### Specific section or headline?
В качестве возможной ссылки предлагается [эта](https://ru.wikipedia.org/wiki/Управляющие_символы). Не знаю, насколько релевантной вы ее посчитаете.

#### What did you expect to see?
Предполагал, что будет переход на действующую страницу.

#### Did you test this? If so, how?
См. выше.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/glossary/character`
* MDN URL: https://developer.mozilla.org/ru/docs/Glossary/Character
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/glossary/character/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b0485d7a479d4e9e64283c12f17c91f68f7b0361
* Document last modified: 2022-02-10T00:54:14.000Z

</details>

**Comment by sashasushko** [comment]
Fixed
