### ISSUE TITLE
fr - Lint / translate missing parts of /docs/Web/API/IntersectionObserver

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#409]
Following #408, I'm filing this so that https://developer.mozilla.org/fr/docs/Web/API/IntersectionObserver / https://github.com/mdn/translated-content/blob/main/files/fr/web/api/intersectionobserver/index.html does not lag behind and is properly linted/translated.

**Comment by tristantheb** [comment]
An update and translation of content, here we go! 👀

**Comment by SphinxKnight** [comment]
Je parlais "juste" de la page :] (où en fait il n'y a que le commentaire de tableau de compat et l'en-tête des specs en anglais ^ ^)

**Comment by tristantheb** [comment]
Je rajoute aussi le français dans le bloc d'exemple `chargerÉléments()`...
