### ISSUE TITLE
Issue with "교차 출처 리소스 공유 (CORS)": (KO-KR / CORS Preflight Description)

### ISSUE THREAD

**Issue by sckimynwa** [mdn/translated-content#4097]
MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/CORS

#### What information was incorrect, unhelpful, or incomplete?

CORS Preflight Request시에 Cross-Origin이 아닌 Cross-Site로 잘못 번역이 들어가있는 것 같습니다.

#### Specific section or headline?

[[프리플라이트 요청](https://developer.mozilla.org/ko/docs/Web/HTTP/CORS#%ED%94%84%EB%A6%AC%ED%94%8C%EB%9D%BC%EC%9D%B4%ED%8A%B8_%EC%9A%94%EC%B2%AD)] 부분입니다.

#### What did you expect to see?

해당 섹션의 텍스트 중 
```
Cross-site 요청은 유저 데이터에 영향을 줄 수 있기 때문에 이와같이 미리 전송(preflighted)합니다.
```
해당 부분이 아래와 같이 변경되어야 할 것 같습니다.
```
Cross-origin 요청은 유저 데이터에 영향을 줄 수 있기 때문에 이와같이 미리 전송(preflighted)합니다.
```

#### Did you test this? If so, how?

실제로 Site와 Origin의 정의상 Origin의 개념이 맞으며, [Web.dev]
[[영문 번역](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#preflighted_requests)]의 경우 Cross-Origin으로 표기하고 있습니다.

![image](https://user-images.githubusercontent.com/30401400/153520109-bdfb5f61-6f6f-4535-bb39-faee44ddb275.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `ko/web/http/cors`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/CORS
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/http/cors/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b0485d7a479d4e9e64283c12f17c91f68f7b0361
* Document last modified: 2022-02-10T00:54:14.000Z

</details>

**Comment by hochan222** [comment]
@kraccoon-dev @yechoi42 안녕하세요! #4103 에서 해결된것같은데, 해당 이슈 closed 해도 괜찮을까요?

**Comment by yechoi42** [comment]
@hochan222 네 닫아주세요!
