### ISSUE TITLE
Issue with "Les modules JavaScript": "ceux-ci sont automatiquement chargés à la demande."

### ISSUE THREAD

**Issue by DegrangeM** [mdn/translated-content#4113]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules

#### What information was incorrect, unhelpful, or incomplete?
La page française indique

> Il n'est pas nécessaire d'utiliser l'attribut defer (voir [les attributs de <script>](https://developer.mozilla.org/fr/docs/Web/HTML/Element/script#attributs)) lors du chargement d'un module, ceux-ci sont automatiquement chargés à la demande.

La page anglais indique

> There is no need to use the defer attribute (see [<script> attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attributes)) when loading a module script; modules are deferred automatically.

Les deux textes ne signifient pas la même chose. En anglais on dit que le chargement des scripts est différée à la fin du chargement du DOM, alors qu'en français on indique les les modules ceux chargés à la demande.

#### Specific section or headline?
https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules#diff%C3%A9rences_entre_les_modules_et_les_scripts_%C2%AB_classiques_%C2%BB

#### What did you expect to see?
Quelque chose du genre ?
> > Il n'est pas nécessaire d'utiliser l'attribut defer (voir [les attributs de <script>](https://developer.mozilla.org/fr/docs/Web/HTML/Element/script#attributs)) lors du chargement d'un module, celui-ci étant automatiquement différé.

#### Did you test this? If so, how?
Je n'ai pas fait la modification moi même car je ne suis pas sûr a 100% que les modules ne sont pas chargés à la demande. J'ai par contre fait un test sur chrome en incluant un script en mode module qui contenait simplement le code `alert(42)` et l'alerte s'est affiché sans que je n'essaye d'importer le module. Il ne me semble donc pas que les modules soient chargés à la demande.

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/guide/modules/index.md
* Last commit: https://github.com/mdn/translated-content/commit/4873c5f1122ac800cf3c916a52df07e05ddc9dcf
* Document last modified: 2022-02-11T00:58:37.000Z

</details>

**Comment by cw118** [comment]
@DegrangeM merci pour ce retour, vous avez absolument raison ! Je vous invite à apporter la correction via une pull request sur ce dépôt (https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/guide/modules/index.md). N'hésitez pas si vous avez besoin d'aide :)
