### ISSUE TITLE
La documentación no existe [ES]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#4135]
Esta tarea puede ser dividida en Issues por checkbox y esta abierta para todos los contribuidores que deseen participar en MDN.

Páginas detectadas en #4107
- [x] #6273
- [x] #6274
- [x] #6275
- [x] #6276

Páginas detectadas en #4140
- [ ] /es/docs/Web/JavaScript/Reference/Objetos_globales/String/match
- [ ] /es/docs/Web/JavaScript/Reference/Objetos_globales/String/matchAll

**Comment by Graywolf9** [comment]
Veo que `match` y `matchAll` sí existen pero están mal escritas

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/match
https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/String/matchAll

**Comment by Graywolf9** [comment]
Closed due to https://github.com/mdn/translated-content/issues/4135#issuecomment-1169098078
