### ISSUE TITLE
Issue with "並行モデルとイベントループ": (broken link to image)

### ISSUE THREAD

**Issue by Wintus** [mdn/translated-content#4139]
MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/EventLoop

#### What information was incorrect, unhelpful, or incomplete?

Unlike the other languages, the image (alt: Stack, heap, queue) has a broken link and disappears:

https://github.com/mdn/translated-content/blob/a901ccf2b7747322b75d9f81014d7d88426bea8a/files/ja/web/javascript/eventloop/index.html#L19

The English version shows with this image: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop/the_javascript_runtime_environment_example.svg

#### Specific section or headline?

The section is 「視覚表示」.

#### What did you expect to see?

It should shows the image like this: https://developer.mozilla.org/en-US/docs/Web/JavaScript/EventLoop/the_javascript_runtime_environment_example.svg

Or like other languages: https://github.com/mdn/translated-content/search?q=the_javascript_runtime_environment_example

#### Did you test this? If so, how?

By browsing the page.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ja/web/javascript/eventloop`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/EventLoop
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/javascript/eventloop/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a69836c420c06922cc657992d0c4dadec297d061
* Document last modified: 2022-02-13T19:09:38.000Z

</details>

**Comment by NaincyKumariKnoldus** [comment]
Hey @Wintus Can I fix this?

**Comment by cw118** [comment]
Hi @NaincyKumariKnoldus, this is quite a simple fix (the image source `/files/4617/default.svg` should instead be `the_javascript_runtime_environment_example.svg`), feel free to open a pull request making the change and link it to this issue :)
