### ISSUE TITLE
Issue with "La sécurité d'un site Web": erreur de saisie

### ISSUE THREAD

**Issue by vikbic78** [mdn/translated-content#4155]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/Server-side/First_steps/Website_security

#### What information was incorrect, unhelpful, or incomplete?
Hello, it's Text error.

#### Specific section or headline?

In  french translate :  [Falsification de requête inter-sites (CSRF)](https://developer.mozilla.org/fr/docs/Learn/Server-side/First_steps/Website_security#falsification_de_requ%C3%AAte_inter-sites_csrf)

in <p>
Les attaques CSRF permettent à un utilisateur malveillant d'éxécuter des actions à l'a ide des identifiants d'un autre utilisateur sans que cet utilisateur ne soit informé ou consentant.

#### What did you expect to see?

" à l'a ide "    ??? it's religious fest 
correct : à l'aide.
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/server-side/first_steps/website_security`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/Server-side/First_steps/Website_security
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/server-side/first_steps/website_security/index.md
* Last commit: https://github.com/mdn/translated-content/commit/e7754b8a0961a10a33c34819dbded4147c8aa1cc
* Document last modified: 2022-02-15T01:01:01.000Z

</details>

**Comment by cw118** [comment]
Thanks for reporting! This has been fixed by #4317

**Comment by cw118** [comment]
Thanks for reporting! This has been fixed by #4317 :)
