### ISSUE TITLE
Issue with "El modelo de caja": [ES]

### ISSUE THREAD

**Issue by Agalara** [mdn/translated-content#4193]
MDN URL: https://developer.mozilla.org/es/docs/Learn/CSS/Building_blocks/The_box_model

#### What information was incorrect, unhelpful, or incomplete?

The link to : **Test your skills-The Box Model** ,  doesn't work when switching the language to Spanish.

_Broken/incorrect link_(from Spanish version): [https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Box_Model_Tasks](url) 

_Working link_  ( from US-english version):  [https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Box_Model_Tasks](url)

#### Specific section or headline?
Pon a prueba tus habilidades ( Test your skills!)
[https://developer.mozilla.org/es/docs/Learn/CSS/Building_blocks/The_box_model#pon_a_prueba_tus_habilidades](url)

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/learn/css/building_blocks/the_box_model`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/CSS/Building_blocks/The_box_model
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/css/building_blocks/the_box_model/index.html
* Last commit: https://github.com/mdn/translated-content/commit/177052e69595330579f7b0ee80caabb1ec54d2d9
* Document last modified: 2022-02-18T00:23:54.000Z

</details>

**Comment by JuanVqz** [comment]
Hola @Agalara! Muchas gracias por abrir el issue!

Este enlace falla por que la dirección cambio 

```
// Antes
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors/Box_Model_Tasks
// Ahoira
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Box_Model_Tasks
```
Abri un PR #4197  para solucionarlo, pero me doy cuenta que la version en español no existe, @Agalara te gustaria traducirlo?



------------------------------------
En estos momentos estamos trabajando en poner al día la traducción al Español.

Si deseas seguir apoyando puedes:
* [Actualizar el contenido con la versión en inglés](https://github.com/mdn/translated-content/discussions/4029)
* [Revisar issues](https://github.com/mdn/translated-content/issues?q=is%3Aopen+is%3Aissue+label%3Al10n-es)
* [Unirte a nuestro equipo](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.

**Comment by Agalara** [comment]
Buenos días.

Me gustaría traducirlo al español,si.
Voy a informarme mejor sobre cómo hacerlo con los enlaces que me envió en
el anterior email.
Reciba un cordial saludo!

**Comment by JuanVqz** [comment]
@Agalara Una disculpa por que no vi que querías trabajar en este issue, el problema con la URL ya quedo solucionado, sin embargo seria genial si pudieras actualizar la traducción de todo el archivo y cambiar al formato a markdown, el cual es usado en la versión en inglés.

Te comparto ambos enlaces.

Este es el documento que debes actualizar
https://github.com/mdn/translated-content/blob/main/files/es/learn/css/building_blocks/the_box_model/index.html

y debe quedar lo más parecido (identico de ser posible) a esté 
https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/the_box_model/index.md

Te dejo unos enlaces que pueden ser útiles al iniciar a traducir, si tienes dudas no dudes en escribir/preguntar por este medio.

* [Actualizar el contenido con la versión en inglés](https://github.com/mdn/translated-content/discussions/4029)
* [Unirte a nuestro equipo](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.

**Comment by Agalara** [comment]
@JuanVqz Buenos dias, estoy revisando/actualizando las diferencias que encuentro con el original.
En cuánto a la estuctura, por el momento ,estoy respetando la que ya tiene el propio documento a actualizar puesto que es idéntica al original.

**Comment by Agalara** [comment]
Es esto algo que deberia de cambiar?
<p>{{EmbedGHLiveSample("css-examples/learn/box-model/block.html", '100%', 1000)}} </p> -- Version traducida

{{EmbedGHLiveSample("css-examples/learn/box-model/block.html", '100%', 1050)}} --Version en-US ( El valor son 1050 en lugar de 1000)

**Comment by JuanVqz** [comment]
> Es esto algo que deberia de cambiar?
> 
> {{EmbedGHLiveSample("css-examples/learn/box-model/block.html", '100%', 1000)}} 
> 
> -- Version traducida
> {{EmbedGHLiveSample("css-examples/learn/box-model/block.html", '100%', 1050)}} --Version en-US ( El valor son 1050 en lugar de 1000)

Si, deberia ser **1050**, como en ingles.

Tienes configurado MDN en tu entorno local?
[Aquí tienes la guia para configurarlo en tu PC](https://github.com/mdn/yari#quickstart), de esta forma podras visualizar cada cambio que haces y verlo en tiempo real (es lo recomendado), si no lo tienes no pasa nada (de momento).

PD. [Hice un video de como configurarlo](https://www.youtube.com/watch?v=pFeW0vUYbkg), igual por si lo quieres ver.

**Comment by Agalara** [comment]
Bien, terminé de revisar el texto. He de avisar que hay una gran cantidad de cambios en la primera mitad de documento que son simplemente por haber separado lineas de texto muy largas en varias lineas distintas, para poder leerlo todo sin tener que hacer scroll lateralmente.
De ahí en adelante he dejado de hacerlo por que no se si vale la pena realmente y simplemente he estado revisando. 
Haré el pull request en un momento.

PD: intenté configurar MDN, pero lo voy a dejar para mas adelante cuando entienda Ubuntu un poco mejor.
Un saludo!

**Comment by JuanVqz** [comment]
> Bien, terminé de revisar el texto. He de avisar que hay una gran cantidad de cambios en la primera mitad de documento que son simplemente por haber separado lineas de texto muy largas en varias lineas distintas, para poder leerlo todo sin tener que hacer scroll lateralmente. De ahí en adelante he dejado de hacerlo por que no se si vale la pena realmente y simplemente he estado revisando. Haré el pull request en un momento.
> 
> PD: intenté configurar MDN, pero lo voy a dejar para mas adelante cuando entienda Ubuntu un poco mejor. Un saludo!

Claro! Eres bienvenid@ cuando gustes contribuir en MDN, de antemano gracias por tu tiempo y apoyo actualizando la documentación. Quedamos a espera de tu PR.

PD. Puedes instalarlo en windows tambien :+1:

**Comment by Graywolf9** [comment]
Hola a todos!

Espero se encuentren muy bien.

Veo que el asunto principal de este _issue_ fue resuelto en #4197 y veo la confirmación de lo mismo [aquí](https://github.com/mdn/translated-content/issues/4193#issuecomment-1047256460), así que doy por resuelto este _issue_.

Por otra parte puedes enviar los avances que llevas en un nuevo PR directamente, @Agalara, muchas gracias por todo!
