### ISSUE TITLE
Issue with "Как использовать GitHub Pages?": (short summary here please)

### ISSUE THREAD

**Issue by savkivvi** [mdn/translated-content#4209]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/Common_questions/Using_Github_pages

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/learn/common_questions/using_github_pages`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/Common_questions/Using_Github_pages
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/common_questions/using_github_pages/index.html
* Last commit: https://github.com/mdn/translated-content/commit/177052e69595330579f7b0ee80caabb1ec54d2d9
* Document last modified: 2022-02-18T00:23:54.000Z

</details>

**Comment by SphinxKnight** [comment]
@savkivvi What is the issue you're facing on this page please?

**Comment by myshov** [comment]
@savkivvi feel free to reopen issue if problem is still there
