### ISSUE TITLE
The link is broken, but I don't know how to fix it.

### ISSUE THREAD

**Issue by teruteru128** [mdn/translated-content#4250]
MDN link: https://developer.mozilla.org/ja/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data

`Fetch のコードでは何が起きている?` 直下の `fetch()` リンクが切れています。
https://developer.mozilla.org/ja/docs/Web/API/fetch
にリンクを張り直そうと考えたのですが、リンクをつなぎ直すべきページのURL形式が変わってしまっていて domxref マクロ形式のリンクを使うべきなのか、 a タグ形式のリンクを使うべきなのかがよくわからなかったのでissueを立てました。

**Comment by teruteru128** [comment]
https://github.com/mdn/translated-content/blob/371ce8c594401c866e65445e9215522666bc6a10/files/ja/learn/javascript/client-side_web_apis/fetching_data/index.html#L202

**Comment by cw118** [comment]
Judging by what's in the [English file](https://github.com/mdn/content/blob/main/files/en-us/learn/javascript/client-side_web_apis/fetching_data/index.md?plain=1#L207), the `{{domxref("WorkerOrWindowGlobalScope.fetch()","fetch()")}}` macro should simply be replaced with `{{domxref("fetch()")}}`.

**Comment by teruteru128** [comment]
Thank you! I will submit it as a pull request from now on.
