### ISSUE TITLE
Issue with "background-repeat": ("cobrir" is incorrect for spanish translate, that's "cubrir")

### ISSUE THREAD

**Issue by AndyGlz01** [mdn/translated-content#4253]
MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/background-repeat

#### What information was incorrect, unhelpful, or incomplete?
"cobrir" is incorrect.

#### Specific section or headline?
Sintaxis, definition of  repeat value

#### What did you expect to see?
La imagen se repite hasta "cubrir" todo el fondo existente. La última imagen debe ser recortada si no encaja.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/css/background-repeat`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/background-repeat
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/background-repeat/index.html
* Last commit: https://github.com/mdn/translated-content/commit/6acf87987baea4675dbd1d5586663959e742cc03
* Document last modified: 2022-02-22T00:12:14.000Z

</details>

**Comment by JuanVqz** [comment]
Hola @AndyGlz01, Muchas gracias por reportar el error ortografico!

Te gustaria solucionarlo, abriendo un pull request?
En el siguiente enlace podras ver una serie de pasos para que puedas corregir el texto y abrir el pull request
https://github.com/mdn/translated-content/issues/4096#issuecomment-1035886101

[Si tienes dudas o te gustaria unirte a la comunidad, aquí puedes unirte](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.

**Comment by sergiogval** [comment]
This content wasn't translated before. It was created intentionally with a typo in order to ask for a PR and add malicius content directly into the repo.
![Screenshot from 2022-02-23 12-00-24](https://user-images.githubusercontent.com/67393791/155385236-3f0eb0c7-28ff-420a-8004-4f8b5376316c.png)

**Comment by sergiogval** [comment]
@AndyGlz01 all clear for closing this issue. Will you be so kind to be the one that closes it?
