### ISSUE TITLE
Issue with "建立超链接": Chinese typo

### ISSUE THREAD

**Issue by Eridani117** [mdn/translated-content#4273]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks

#### What information was incorrect, unhelpful, or incomplete?
In the content"
以 BBC 的主页为例，里面就包含了非常多的<strong>连结</strong>，各自连到不同新闻、网站的其它地方（导览功能），或者登入/注册页面等等。"

The 连结 sholud be 链接

#### What did you expect to see?
``` HTML
<span>以 BBC 的主页为例，里面就包含了非常多的连结，各自连到不同新闻、网站的其它地方（导览功能），或者登入/注册页面等等。</span>
```
change to 
``` HTML
<span>以 BBC 的主页为例，里面就包含了非常多的链接，各自连到不同新闻、网站的其它地方（导览功能），或者登入/注册页面等等。</span>
```

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/learn/html/introduction_to_html/creating_hyperlinks`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/html/introduction_to_html/creating_hyperlinks/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b06c41e08f5ebd84cb02bcbcbe35a5be6a756c31
* Document last modified: 2022-02-23T17:52:30.000Z

</details>

**Comment by yin1999** [comment]
@cw118 fixed in: #4606
