### ISSUE TITLE
Update @mdn/yari-content-fr to add @cw118

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#4275]
@Rumyra hello, could you please add @cw118 to the @mdn/yari-content-fr team?

Carolyn has already made numerous PRs of high quality on the French content. Of equal (if not superior) importance, she helped/guided other contributors from other locales on this repository on numerous occasions.

This issue is accompanied with:

- https://github.com/mdn/translated-content/pull/4276
- https://github.com/mdn/content/pull/13270

**Comment by Rumyra** [comment]
Sorry for the delay @SphinxKnight - this is now done 👍

**Comment by SphinxKnight** [comment]
np, thanks! 🙇‍♂️

**Comment by JuanVqz** [comment]
Congrats @cw118 :1st_place_medal: :partying_face:
