### ISSUE TITLE
Initiate "core" translated-content team with localizers

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#4278]
Rationale: https://github.com/mdn/translated-content/pull/3490#issuecomment-1046782593

I would like to ask the creation of a reviewing team for files out of `files/<locale>` trees and out of `docs/<locale>` trees, including workflows and the like. This team would "complete" current reviewers from @mdn/core-yari-dev and @mdn/core-yari-content with other community members "experienced" with MDN.

I think @alattalatta, @mfuji09 and myself (@SphinxKnight) would make for a good starting point.
Later on, this could be opened/enlarged with other members (I conceive this team more as a "long-term" set of reviewers)

@mdn/core-yari-dev, @mdn/core-yari-content : please let me know what you think.

@alattalatta, @mfuji09: should I be wrong, wanting to include you or would you want to add something, please do :)

**Comment by alattalatta** [comment]
> I would like to ask the creation of a reviewing team for files out of files/<locale> trees and out of docs/<locale> trees, including workflows and the like.

Glad to be a help, but I've little experience with GitHub Actions. If it's okay, no objection from me 😅

**Comment by sergiogval** [comment]
Seems interesting. @SphinxKnight that said, can we have a brief videocall? It is regarding the issue I raised this week and new findings that confirms my statements.

**Comment by mfuji09** [comment]
I'm glad you invited me. I'm still learning about GitHub Actions, but I'm happy to help.

**Comment by SphinxKnight** [comment]
@alattalatta @mfuji09 thanks for your feedback :)
To me, the scope of such reviews/verification would not be "GitHub Actions" only (though technically, this is the most prominent aspect so far)

**Comment by schalkneethling** [comment]
@SphinxKnight Is this still a need?

**Comment by SphinxKnight** [comment]
I'd think that yes, without any further info, it still is needed.

**Comment by schalkneethling** [comment]
Hey @SphinxKnight, the team has been set- up and is @mdn/localization-team-leads

**Comment by SphinxKnight** [comment]
@schalkneethling is it possible to add @alattalatta as well?

**Comment by schalkneethling** [comment]
> @alattalatta

Done.

**Comment by SphinxKnight** [comment]
Thanks :)
