### ISSUE TITLE
Deadlink on "Primeros pasos en MDN" regarding account creation

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#4282]
MDN URL: https://developer.mozilla.org/es/docs/MDN/Contribute/Getting_started

#### What information was incorrect, unhelpful, or incomplete?
The page is out of date and includes dead links 
Cf https://twitter.com/jairyara/status/1497250410628792321

#### Specific section or headline?

https://developer.mozilla.org/es/docs/MDN/Contribute/Getting_started#paso_1_crea_una_cuenta_en_mdn

#### What did you expect to see?

Same as en-US

#### Did you test this? If so, how?

Clicked on the link, got a 404 on https://developer.mozilla.org/es/docs/MDN/Contribute/Howto/Crear_cuenta_MDN

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/mdn/contribute/getting_started`
* MDN URL: https://developer.mozilla.org/es/docs/MDN/Contribute/Getting_started
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/mdn/contribute/getting_started/index.html
* Last commit: https://github.com/mdn/translated-content/commit/47c5261af62999b661642eecb447aeb04d623ffc
* Document last modified: 2022-02-24T22:14:23.000Z

</details>

**Comment by sergiogval** [comment]
I have this cross script attack. It build, stock and rendered ja files.
thing using webpack in production when I try to get to the Mozilla webchat
in element. Who I need to report this to be alerted asap? I got more than
this.  Also, you should check your system logs. Since you click on a page
that may be a vector.

**Comment by stripTM** [comment]
My suggestions https://github.com/mdn/translated-content/pull/4283

**Comment by SphinxKnight** [comment]
@stripTM I have nothing against the PR you mention but to me, this issue is about another document: https://github.com/mdn/translated-content/blob/main/files/es/mdn/contribute/getting_started/index.html#L26-L28

**Comment by stripTM** [comment]
Ups, sorry.

Not only the link had to be corrected.
I have migrated the html to md and also updated the whole document. The current one refers to the old MDN as Wiki.

Then this would be my PR https://github.com/mdn/translated-content/pull/4288

**Comment by sergiogval** [comment]
Stop the censorship.

**Comment by sergiogval** [comment]
Stop the censorship. 
 @stripTM may I ask why is my token exposed in the comment that you minimized? Alexander I told you @SphinxKnight @Graywolf9 to leave me alone. @JuanVqz no tienes madre.

**Comment by sergiogval** [comment]
> Ups, sorry.
> 
> Not only the link had to be corrected.
> I have migrated the html to md and also updated the whole document. The current one refers to the old MDN as Wiki.
> 
> Then this would be my PR https://github.com/mdn/translated-content/pull/4288

=================

So if you have 10 years programming I got 20. If you were more skilled than me you should know what a honeypot is. And if you were Mexican your social engineering would be way better than this.

**Comment by sergiogval** [comment]
@Rumyra I really need some help with these guys. They are exposing my tokens. Check out mi minimized content. They are clearly disrespecting the rules of the comunnity and doing  a felony since they have the guts to do a conspiracy to get my private data exposed and therefore my digital and physical integrity in danger.

**Comment by JuanVqz** [comment]
> Stop the censorship. @stripTM may I ask why is my token exposed in the comment that you minimized? Alexander I told you @SphinxKnight @Graywolf9 to leave me alone. @JuanVqz no tienes madre.

Hi @sergiogval your comment was minimized because it's not related to the issue, there are places where you can report them.
Do you know who minimized your comment? and lastly but not least, please don't be rude.

**Comment by sergiogval** [comment]
Each one of you will fall. And will suffer  tree times what you made to me.

**Comment by sergiogval** [comment]
Each one of you will fall. And will suffer  tree times what you made to me


@SphinxKnight I'm sorry, but what does a 'franchise speaker' that doesn't speak Spanish correcting Spanish documentation? You are welcome for suggestion. But as far as I know any of us does changes into the main branch of your community....

**Comment by sergiogval** [comment]
I'm not sure if we can take this issue as closed. I will do my part and you yourncorresponding one. Can you be so kind and give me an  update?
