### ISSUE TITLE
@Rumyra I really need some help with these guys. They are exposing my tokens. Check out mi minimized content. They are clearly disrespecting the rules of the comunnity and doing  a felony since they have the guts to do a conspiracy to get my private data exposed and therefore my digital and physical integrity in danger.

### ISSUE THREAD

**Issue by sergiogval** [mdn/translated-content#4297]
@Rumyra I really need some help with these guys. They are exposing my tokens. Check out mi minimized content. They are clearly disrespecting the rules of the comunnity and doing  a felony since they have the guts to do a conspiracy to get my private data exposed and therefore my digital and physical integrity in danger.

_Originally posted by @sergiogval in https://github.com/mdn/translated-content/issues/4282#issuecomment-1053579906_

**Comment by sergiogval** [comment]
@mdn/yari-content-pt-br @mdn/yari-content-mdn @Rumyra @mdn/core-dev  S.O.S

**Comment by sergiogval** [comment]
These guys have total control of my devices. no way I can report them.

**Comment by Rumyra** [comment]
Please be aware that I am currently investigating this issue - thanks

**Comment by sergiogval** [comment]
Hi, I appreciate that, Ruth.

Let me give a quick update. I was able to have a dialogue with the
community and we all agreed that the best is to found out a solution where
each part is satisfied. That said, It would be great to know what is your
opinion regarding this, and confirm to me that we all are ok with it. My
will is to leave this behind, I hope yours goes in the same way.

Looking forward to hearing from you.

Sergio Valadez
