### ISSUE TITLE
[GER] JavaScript Array find spelling error

### ISSUE THREAD

**Issue by xDreamCoding** [mdn/translated-content#4331]
https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Array/find

array Optional
Das Array, welches mit find() durlaufen wird.

array Optional
Das Array, welches mit find() durchlaufen* wird.

**Comment by SphinxKnight** [comment]
Sorry, but this locale is currently frozen and changes/fixes are not currently accepted. Please see https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ and [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo.
