### ISSUE TITLE
Update: "Modo Quirks y Modo Estándar" [es]

### ISSUE THREAD

**Issue by jacquelinecarrillo** [mdn/translated-content#4365]
MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/html/quirks_mode_and_standards_mode`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/html/quirks_mode_and_standards_mode/index.html
* Last commit: https://github.com/mdn/translated-content/commit/96c4513c7db7a275193742e73a7d3cd8feb401bc
* Document last modified: 2022-03-01T23:14:13.000Z

</details>

**Comment by JuanVqz** [comment]
Hola @jacquelinecarrillo!

Disculpa, que estas reportartando?
Quisieras resolver el problema?


Si quieres hablar más del tema [unirte al chat](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.

**Comment by JuanVqz** [comment]
hola @jacquelinecarrillo, solo para darle seguimiento al issue que abriste, nos gustaría saber que viste en dicha pagina que desees reportar, seria de mucha utilidad tener mas detalles.

Puedes colocar un comentario explicando o unirte al chat https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org 

Saludos!

**Comment by Yareaj** [comment]
@JuanVqz podríamos cerrar este issue por el tiempo que lleva inactivo sin especificaciones del problema?

**Comment by Graywolf9** [comment]
Por cierto @Vallejoanderson habías comentado en el chat sobre este issue, ¿tienes interés en actualizar este artículo para que quede solucionado?
