### ISSUE TITLE
9. web/javascript/reference/global_objects/object/index.html [es]

### ISSUE THREAD

**Issue by hectormoba** [mdn/translated-content#4366]
Translating parts of this page that they aren't translated and fix {{page}} macro calls #3936

**Comment by JuanVqz** [comment]
Hola @hectormoba, gracias por tomar este issue! si necesitas ayuda con gusto te ayudamos, deja un comentario aquí o en el chat

**Comment by hectormoba** [comment]
Opened a pull request #4430
