### ISSUE TITLE
scrollHeight page show 

### ISSUE THREAD

**Issue by accpdyk** [mdn/translated-content#4367]
## chrome  96.0.4664.110（正式版本） （64 位） 
 - 页面示例显示有问题
 - 链接地址：https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollHeight

**Comment by cw118** [comment]
@sideshowbarker hello, I see that one of the `scrollHeight` examples on the simplified Chinese page is problematic as described in the issue here, just wondering if there's a reason why this is already closed?

**Comment by sideshowbarker** [comment]
> @sideshowbarker hello, I see that one of the `scrollHeight` examples on the simplified Chinese page is problematic as described in the issue here, just wondering if there's a reason why this is already closed?

Thanks, re-opened

**Comment by UESTCzhouyuchuan** [comment]
hello see #4858

**Comment by yin1999** [comment]
Hi @cw118, it has been resolved in #4858 🙂.
