### ISSUE TITLE
Issue with "网络视频编解码器指南": (short summary here please)

### ISSUE THREAD

**Issue by Yuushigure** [mdn/translated-content#4368]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Media/Formats/Video_codecs

#### What information was incorrect, unhelpful, or incomplete?

only old Edge supports HEVC on devices with a hardware codec,the new Edge based on Chromium not supported

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/media/formats/video_codecs`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Media/Formats/Video_codecs
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/media/formats/video_codecs/index.html
* Last commit: https://github.com/mdn/translated-content/commit/96c4513c7db7a275193742e73a7d3cd8feb401bc
* Document last modified: 2022-03-01T23:14:13.000Z

</details>

**Comment by awxiaoxian2020** [comment]
Could you please give a specific section or headline in the doc about what you said?

**Comment by jiwangyihao** [comment]
Are you saying that the new version of edge no longer supports HEVC encoding after switching to the chromium kernel?
你是说新版edge在换用chromium内核后已经不再支持HEVC编码了吗？
![A screenshot of the English version](https://user-images.githubusercontent.com/51940778/173354144-87dae95a-6bf9-4fa4-8988-e928376bcd66.png)
But now the English document is still written like this, maybe you can post an issue first in [mdn/content]（https://github.com/mdn/content)
但是现在英文文档仍然是这样写的，或许你可以先在[mdn/content](https://github.com/mdn/content)中提出此问题
