### ISSUE TITLE
Issue with "HTML表单指南": (short summary here please)

### ISSUE THREAD

**Issue by RhyThmTI** [mdn/translated-content#4379]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Forms

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/learn/forms`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Forms
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/forms/index.html
* Last commit: https://github.com/mdn/translated-content/commit/60e68bc9b4fc796aaea41a8c56ec02ad3b6ee618
* Document last modified: 2022-03-03T00:14:36.000Z

</details>

**Comment by yin1999** [comment]
Issues:

- link to the website [Thimble](https://thimble.mozilla.org/) that doesn't exist anymore.
- reference to `HTML forms element` is not correct, anchor should be `#表单` not `#forms`

This article is also out-of-date.
