### ISSUE TITLE
How browsers work: text is difficult to see in dark mode (zh-CN)

### ISSUE THREAD

**Issue by arctichotpot** [mdn/translated-content#4385]
# Summary

When I browse articles in dark mode, I found that the font color of some articles became the same as the background color, making it difficult to find

## Where did you spot the bug?

https://developer.mozilla.org/zh-CN/docs/Web/Performance/How_browsers_work#%E6%A6%82%E8%BF%B0

## What is the problem?

When I browse articles in dark mode, I found that the font color of some articles became the same as the background color, making it difficult to find.

But when I switch to the English display, the display is normal, but in the Chinese translation interface will have this problem

## What did you expect to happen?

I hope to change the color of the text to the same as other areas

## Steps to reproduce the issue

1. Open   https://developer.mozilla.org/zh-CN/docs/Web/Performance/How_browsers_work#%E6%A6%82%E8%BF%B0
  in Chrome
2. Switching to dark mode
3. Scroll to "[构建CSSOM树](https://developer.mozilla.org/zh-CN/docs/Web/Performance/How_browsers_work#%E6%9E%84%E5%BB%BAcssom%E6%A0%91)"

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [x] Chrome:  99.0.4844.51
- [ ] Firefox: (what version?)
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [x] Windows: Windows 11
- [ ] Mac OS: (what version?)
- [ ] Linux: (what distribution / version?)

## Screenshots

Chinese interface
![image](https://user-images.githubusercontent.com/36844445/156484308-c8cee415-d9e5-4d93-a707-3d302154430f.png)

English Interface
![image](https://user-images.githubusercontent.com/36844445/156484622-d3910803-ad2a-4f49-83af-9cff6c7222b3.png)

**Comment by cw118** [comment]
Thanks for the report! 

I see the same issue is on the Korean page (cf. [Building the CSSOM](https://developer.mozilla.org/ko/docs/Web/Performance/How_browsers_work#building_the_cssom)) due to [some inline CSS here](https://github.com/mdn/translated-content/blob/main/files/ko/web/performance/how_browsers_work/index.html#L131) (apart from it not being translated)

**Comment by cw118** [comment]
(Korean page was dealt with in #4453)
