### ISSUE TITLE
Content bug: French File.name page content is outdated

### ISSUE THREAD

**Issue by atchisson** [mdn/translated-content#4399]
## What page(s) did you find the problem on?
French [File.name](https://developer.mozilla.org/fr/docs/Web/API/File/name) API documentation .

## Specific page section or heading?
The whole page

## What is the problem?
French [File.name](https://developer.mozilla.org/fr/docs/Web/API/File/name) API documentation does not match intended content. 
It is talking about the old deprecated fileName property, instead of File.name. 
The 'see also' section references itself.

## What did you expect to see?
An actual translation of the [File.name english page](https://developer.mozilla.org/en-US/docs/Web/API/File/name)

**Comment by SphinxKnight** [comment]
Thanks @atchisson for the notice
