### ISSUE TITLE
a translation issue that make chinese confused easily in 'Responsive Image' page

### ISSUE THREAD

**Issue by jinsayhi** [mdn/translated-content#440]
Link: https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images
让人迷惑的内容：”srcset定义了我们允许浏览器选择的图像集，以及每个图像的大小。在每个逗号之前，我们写：
一个文件名 (elva-fairy-480w.jpg.)；
一个空格；
**图像的固有宽度（以像素为单位）（480w）——注意到这里使用w单位，而不是你预计的px。**这是图像的真实大小，可以通过检查你电脑上的图片文件找到（例如，在Mac上，你可以在Finder上选择这个图像，然后按 Cmd + I 来显示信息）。“
我的问题（issue):  
建议将
**"注意到这里使用w单位，而不是你预计的px。“** 
修改为 
**”注意到这里使用w单位，而不是你预计的px。（‘w'表示宽度：width，其单位实际上仍是px-像素。）“** 
原因如下：
英文中，没有“w"代表“万”的语境，这样写不会让英语读者有歧义；但中文中经常有“500w像素”的情景，此处容易让人误解为：’w'代表“万像素“的意思。
虽然现在想来这么误解有点可笑，但我刚读的时候真的以为是一万像素，希望可以根据中文语境更好的翻译吧，谢谢。麻烦了。
感谢你们的翻译工作。

**Comment by yin1999** [comment]
根据[英文文档](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset)和[中文文档](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/img#attr-srcset)给出的有关 `w` 的描述，考虑将此处更改为：

```
注意，这里使用宽度描述符 `w`，而非你可能期望的 `px`。
```
