### ISSUE TITLE
Issue with "渲染页面：浏览器的工作原理": The links cannot be accessed correctly

### ISSUE THREAD

**Issue by Malaaaa** [mdn/translated-content#4431]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Performance/How_browsers_work

#### What information was incorrect, unhelpful, or incomplete?
The url in sections are not work.

#### Specific section or headline?
the url with index.html does not work

#### What did you expect to see?
the right page

#### Did you test this? If so, how?
I test the url in the doc and the real url
https://developer.mozilla.org/zh-CN/docs/web/performance/how_browsers_work/index.html 
--->this one is in the doc and didn't work.
https://developer.mozilla.org/zh-CN/docs/Web/Performance/How_browsers_work
--->this one is real address and worked well

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/performance/how_browsers_work`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/Performance/How_browsers_work
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/performance/how_browsers_work/index.html
* Last commit: https://github.com/mdn/translated-content/commit/5fab7a350aae684ba816f4caa8ed1453687e461f
* Document last modified: 2022-03-04T19:49:55.000Z

</details>

**Comment by cw118** [comment]
Thank you for reporting! Closing since this was addressed in #4432.
