### ISSUE TITLE
Page bugs

### ISSUE THREAD

**Issue by Bitter-LY** [mdn/translated-content#4445]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Document

#### What information was incorrect, unhelpful, or incomplete?
<img width="498" alt="bugs" src="https://user-images.githubusercontent.com/61288607/156932446-4ebeff1b-3005-42ba-8545-9a4680611326.png">

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/api/document`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Document
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/document/index.html
* Last commit: https://github.com/mdn/translated-content/commit/8e8d92a50f74b5370984259dc963dac56cc5902b
* Document last modified: 2022-03-06T00:13:06.000Z

</details>

**Comment by cw118** [comment]
Thank you for the report, this is related/due to #3893
