### ISSUE TITLE
pt-br CSS cursor page uses wrong image filepaths and specs/compat data

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#4448]
## What page(s) did you find the problem on?

The brazilian portuguese `cursor` - CSS page (https://developer.mozilla.org/pt-br/docs/Web/CSS/cursor)

## Specific page section(s) or heading(s)?

- Under the [Valores](https://developer.mozilla.org/pt-BR/docs/Web/CSS/cursor#valores) heading, more specifically the table with cursor type demos: all `/@api/deki` and `/files/` image sources (filepaths) should be corrected (see #3934 for an example) so that the pictures show

- The [specifications section](https://developer.mozilla.org/pt-BR/docs/Web/CSS/cursor#especifica%C3%A7%C3%B5es) should use the `{{Specifications}}` macro

- The [compatibility table](https://developer.mozilla.org/pt-BR/docs/Web/CSS/cursor#compatibilidade) should be converted to use the `{{Compat}}` macro

**Comment by victor0x16** [comment]
@cw118 , may I fix it?

**Comment by cw118** [comment]
@victor0x16 of course! I'll assign this to you to (hopefully) avoid duplicates.

Honestly, it might be easier to just update the entire page to match it with the current English version, but I'll let you decide the scope of your PR. While I won't be able to help with the portuguese/translation aspect, let me know if you need help with the images, macros, etc. and I'll do what I can :)

**Comment by victor0x16** [comment]
I'm working on it.
