### ISSUE TITLE
Issue with "::before (:before)": (向img标签添加伪类，在ios15系统下，长按图片会使伪类生效)

### ISSUE THREAD

**Issue by soullhj** [mdn/translated-content#4455]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/::before

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/css/_doublecolon_before`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/::before
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/_doublecolon_before/index.html
* Last commit: https://github.com/mdn/translated-content/commit/8e8d92a50f74b5370984259dc963dac56cc5902b
* Document last modified: 2022-03-06T00:13:06.000Z

</details>

**Comment by awxiaoxian2020** [comment]
Please give us more details.

**Comment by yin1999** [comment]
Hi @soullhj, please provide more information about it, so we can try to fix it. I'm going to close this issue for now.

If you could provide more info, we can reopen it. Feel free to discuss with us.
