### ISSUE TITLE
Issue with "Utiliser les objets": (short summary here please)

### ISSUE THREAD

**Issue by bnthp16** [mdn/translated-content#4462]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Working_with_Objects

#### What information was incorrect, unhelpful, or incomplete?
The variable "résultat" in function afficheVoiture is misspelling

#### Specific section or headline?

Définir des méthodes; function afficheVoiture()

#### What did you expect to see?

function afficheVoiture() {

  let resultat = `Une belle ${this.modele}, fabriquée en ${this.annee} par ${this.fabricant}`;
  console.log(resultat); //  ("e" without accent)
}

#### Did you test this? If so, how?
I've tested the code in my IDE and the variable  _resultat_ is unread 

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/javascript/guide/working_with_objects`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Working_with_Objects
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/guide/working_with_objects/index.md
* Last commit: https://github.com/mdn/translated-content/commit/beff76e80538728c83865aa5d1af2f073fd83831
* Document last modified: 2022-03-06T16:52:45.000Z

</details>

**Comment by serotonyn** [comment]
Je souhaiterais apporter ma contribution, je peux ?
