### ISSUE TITLE
Issue with "La mise en page avec le CSS": (short summary here please)

### ISSUE THREAD

**Issue by tonyjohndo** [mdn/translated-content#447]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/CSS/CSS_layout

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/css/css_layout`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/CSS/CSS_layout
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/css/css_layout/index.html
* Last commit: https://github.com/mdn/translated-content/commit/6b573086c2fcb48632430e1a4730ca8cc32c65a4
* Document last modified: 2021-04-07T00:11:12.000Z

</details>

**Comment by SphinxKnight** [comment]
@tonyjohndo bonjour, pouvez-nous dire ce qui ne va pas sur cette page ?

**Comment by tristantheb** [comment]
Bonjour,

J'ai regardé rapidement le fichier de cette page, ainsi que la version anglaise. Je n'ai pas trouvé grand chose à part un mot manquant et des liens en français ou qui n'avaient pas été changés en `/fr/`.
Si ce sont les liens qui vous ont posé problème, cela sera corrigé sous peu.

Cependant, je vous demande de faire attention lorsque vous remplissez les tickets, nous avons besoin d'informations sur ce qui ne va pas avec les pages, donc un formulaire est créé lorsque vous signalez une page.

Si vous ne savez pas comment le dire en anglais, vous pouvez utiliser Deepl, ou l'écrire en français sous les titres correspondants.

Merci à vous 🙂

---
Hello,

I quickly looked at the file on this page, as well as the English version. I didn't find much apart from a missing word and links in French or that had not been changed to `/fr/`.
If it was the links that caused you problems, this will be corrected shortly.

However, I would ask you to be careful when filling in the tickets, we need information about what is wrong with the pages, so a form is created when you report a page.

If you don't know how to say it in English, you can use Deepl, or write it in French under the corresponding titles.

Thank you 🙂
