### ISSUE TITLE
Issue with "Number.prototype.toLocaleString()": (short summary here please)

### ISSUE THREAD

**Issue by miguel-misstipsi** [mdn/translated-content#4476]
MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

#### What information was incorrect, unhelpful, or incomplete?
Browsers compatibility table don't show

#### Specific section or headline?
Browsers compatibility

#### What did you expect to see?
The browsers compatibility table should be showed

#### Did you test this? If so, how?
No

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/number/tolocalestring`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/number/tolocalestring/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d53bae971e455859229bcb3246e29bcbc85179d2
* Document last modified: 2022-03-08T00:12:08.000Z

</details>

**Comment by JuanVqz** [comment]
Hola @miguel-misstipsi Muchas gracias por abrir un issue!

Veo que la tabla de compatibilidad si se puede ver en el enlace que colocas en la descripción.

O es algo más que no me he caido en cuenta? Por favor, haznos saber.

![image](https://user-images.githubusercontent.com/7331511/157248031-8ca9f72a-d557-4475-86e1-0dec4f06dc58.png)


Si deseas seguir apoyando puedes:
* [Actualizar el contenido con la versión en inglés](https://github.com/mdn/translated-content/discussions/4029)
* [Revisar issues](https://github.com/mdn/translated-content/issues?q=is%3Aopen+is%3Aissue+label%3Al10n-es)
* [Unirte a nuestro equipo](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.

**Comment by Vallejoanderson** [comment]
No parece ser un tema de compatibilidad con el navegador. :thinking: 
![image](https://user-images.githubusercontent.com/48649209/157356499-439a47f4-a283-4440-8c37-6f535d0ab6a5.png)

**Comment by miguel-misstipsi** [comment]
Que interesante @Vallejoanderson, ahora yo también lo veo correctamente con Chrome. 
![image](https://user-images.githubusercontent.com/12932346/157433015-bc10aecc-21a3-4677-aa6c-96d09d09dec5.png)
Perfecto entonces.
Muchas gracias @JuanVqz y @Vallejoanderson por vuestra atención.
