### ISSUE TITLE
Issue with "Array.prototype.reduce()": (Parameter Description Exception )

### ISSUE THREAD

**Issue by xjy-1999** [mdn/translated-content#4478]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

#### What information was incorrect, unhelpful, or incomplete?
开头说【reduce接收4个参数】，然后把这四个参数罗列了出来：【累加器（acc）、当前值 (cur)、当前指数 (idx) 、Source Array (src)】，但是实际上reduce只有两个参数，一个是回调函数，一个是初始值，后文也是这么描述的。这四个应该是reduce的回调函数的参数，而不是reduce的参数。 

#### Specific section or headline?
在一开始的例子下面，第一个标题【语法】的上面。 

#### What did you expect to see?
reduc函数接收两个参数： 
1、回调函数（callback） 
2、初始值（initialValue） 

#### Did you test this? If so, how?
毫无疑问。 

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/array/reduce/index.html
* Last commit: https://github.com/mdn/translated-content/commit/beff76e80538728c83865aa5d1af2f073fd83831
* Document last modified: 2022-03-06T16:52:45.000Z

</details>

**Comment by yin1999** [comment]
原文中的描述是正确的，开头说的是 【reducer 函数接收4个参数】，这里的 **reducer** 指的是 **Array.reduce()** 中的 **callback** 函数。

可参照英文版的：https://github.com/mdn/content/blob/d12c465dcb8021d2e29595662edf2c9662962a32/files/en-us/web/javascript/reference/global_objects/array/reduce/index.md?plain=1#L31-L66

但 `zh-CN` 的中文版本已经长期没有同步更新了，我会抽时间将其同步翻译到最近的 `en-US` 版本。
