### ISSUE TITLE
Polish articles have unreadable white boxes on dark mode 

### ISSUE THREAD

**Issue by AdamKniec** [mdn/translated-content#4486]
# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

<img width="912" alt="image" src="https://user-images.githubusercontent.com/20644432/156255565-d4901a78-1906-4941-affe-6ecc00c57659.png">

https://developer.mozilla.org/pl/docs/Learn/CSS/First_steps/How_CSS_works.

**Comment by cw118** [comment]
Hi @AdamKniec, thanks for the report.

Unfortunately, the Polish (`pl`) locale is currently frozen and changes/fixes to Polish content are not accepted. Please see [this MDN article on localization](https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/) and the [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo for more information.
