### ISSUE TITLE
Issue with "Outils et tests": (short summary here please)

### ISSUE THREAD

**Issue by maryam2002-N** [mdn/translated-content#4496]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/Tools_and_testing

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/tools_and_testing`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/Tools_and_testing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/tools_and_testing/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1d5ed016a73e4cbb6f5ddb27a5ff04161be33c67
* Document last modified: 2022-03-08T08:19:10.000Z

</details>

**Comment by SphinxKnight** [comment]
@maryam2002-N could you please provide more details about the issue you are facing?

**Comment by SphinxKnight** [comment]
À rouvrir si plus d'informations disponibles.
