### ISSUE TITLE
Add Persian translation

### ISSUE THREAD

**Issue by mmdbalkhi** [mdn/translated-content#4503]
Hello. The community of Persian users in the world is increasing and I think these documents need to be translated into Persian as well. Of course, I do not know exactly where to start and where I should have made this request. I apologize if I made this request in the wrong place.

**Comment by cw118** [comment]
Hi @mmdbalkhi, thank you for the request/suggestion. Unfortunately the Persian locale is "retired", meaning it will no longer be displayed on MDN Web Docs, because it wasn't active enough and didn't have enough translations to be considered "tier 1".

Please see [this discussion](https://github.com/mdn/translated-content/discussions/1321) for a more detailed explanation.

**Comment by mmdbalkhi** [comment]
> Hi @mmdbalkhi, thank you for the request/suggestion. Unfortunately the Persian locale is "retired", meaning it will no longer be displayed on MDN Web Docs, because it wasn't active enough and didn't have enough translations to be considered "tier 1".
> 
> Please see [this discussion](https://github.com/mdn/translated-content/discussions/1321) for a more detailed explanation.

Hi @cw118 thanks. Is it possible to exclude Persian language from retirement?

**Comment by cw118** [comment]
Unfortunately, as stated in [this MDN article on localization](https://hacks.mozilla.org/2021/03/mdn-localization-in-march-tier-1-locales-unfrozen-and-future-plans/), retired locales such as Persian will not be unfrozen (and thus will never be "unretired"):

> After this point, we won’t revive anything — the journey to retirement is one way. This may sound harsh, but we are taking determined steps to clean up MDN and get rid of out-of-date and out-of-remit content that has been around for years in some cases.

I hope that clarifies things, best wishes :)

**Comment by mmdbalkhi** [comment]
Thank you for your help :)
