### ISSUE TITLE
Issue with "Tutoriel SVG": Broken link

### ISSUE THREAD

**Issue by jrd10** [mdn/translated-content#451]
MDN URL: https://developer.mozilla.org/fr/docs/Web/SVG/Tutorial (In French)

At the beginning, second line,
In this sentence: "... est un langage basé sur le **XML** ... " 

The "XML" link is broken :).
https://developer.mozilla.org/fr/XML

Error message:
```
Page not found

Sorry, the page /fr/XML could not be found.
```

Take care,
jrd10 from France

**Comment by tristantheb** [comment]
Hello @jrd10 !

Thanks for reporting this dead link! I'll take care of it so the page can get a little update of the other elements that need it!

If you also want to contribute to the DND, you can follow the following article to set up your working environment and correct typos/links errors or bigger things!
https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer

Don't hesitate ;)

**Comment by jrd10** [comment]
Hi @tristantheb thank you for this proposal :)

I did a Pull Request... but I not sure about my solution!

> <a href="/fr/SVG" title="fr/SVG">SVG</a>
Please, note the previous (broken) link was href="/fr/XML"
I proposed href="/fr/docs/Web/XML"
But I not sure as the href="/fr/SVG" works fine.
Please, check this.
