### ISSUE TITLE
Issue with "Les bases du HTML": (pictures of code missing)

### ISSUE THREAD

**Issue by stormygirl64** [mdn/translated-content#4522]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web/HTML_basics

#### What information was incorrect, unhelpful, or incomplete? 

3 pictures in the beginning of the explanaition, showing the code are missing. (i'm not english native speaking so i hope what i'm saying make sense).

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/getting_started_with_the_web/html_basics`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/Getting_started_with_the_web/HTML_basics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/getting_started_with_the_web/html_basics/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c04a0d2274c4d4a9519744f89d305f11a860e2dd
* Document last modified: 2022-03-09T13:49:50.000Z

</details>

**Comment by cw118** [comment]
Merci pour ce rapport @stormygirl64, on va régler tout ça :)
