### ISSUE TITLE
Issue with Error Page: Links are not working

### ISSUE THREAD

**Issue by SaidkhojaIftikhor** [mdn/translated-content#4523]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error#error_instances

#### What information was incorrect, unhelpful, or incomplete?
I think these `{{ page(.....) }}` should be links.   

![Uploading image.png…]()

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/javascript/reference/global_objects/error`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Error
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/global_objects/error/index.html
* Last commit: https://github.com/mdn/translated-content/commit/c04a0d2274c4d4a9519744f89d305f11a860e2dd
* Document last modified: 2022-03-09T13:49:50.000Z

</details>

**Comment by leon-win** [comment]
Duplicates #3892
