### ISSUE TITLE
Issue with "Feature-Policy": Bad Portuguese

### ISSUE THREAD

**Issue by pepBR** [mdn/translated-content#4530]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers/Feature-Policy

#### What information was incorrect, unhelpful, or incomplete?
2nd line of text - "O cabeçalho HTTP Feature-Policy provém um mecanismo para permitir ou proibir o uso de"
The verb "provém" has another meaning.

#### Specific section or headline?
The word "provém" is bad placed.

#### What did you expect to see?
The word "provém" should be replaced by "provê".

#### Did you test this? If so, how?
As this is only text, no test is required.

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/http/headers/feature-policy`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Headers/Feature-Policy
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/http/headers/feature-policy/index.html
* Last commit: https://github.com/mdn/translated-content/commit/48fc140678926d51b14411105262c87301860575
* Document last modified: 2022-03-09T00:13:03.000Z

</details>

**Comment by victor0x16** [comment]
That page also lacks of the  {{SeeCompatTable}} macro. [#See.](https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/feature-policy/index.md)

**Comment by NRLacerda** [comment]
I approve the change is a detail, but it's wrong.
