### ISSUE TITLE
Duplicated mdn/content images/assets files should be removed from the tree (ja)

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#4544]
Since https://github.com/mdn/yari/pull/5215 has been merged, there is no apparent reason to have duplicated files from mdn/content in mdn/translated-content. After fiddling [a small script](https://gist.github.com/SphinxKnight/60d766b8d6cd970b42eaf967b8dac3ff) (adapted for ja), I was able to identify the following files under the tree which are identical and should be removed.

- `translated-content/files/ja/tools/page_inspector/ui_tour/animation_detail.png`
- `translated-content/files/ja/glossary/sql_injection/sql_inj_xss.gif`
- `translated-content/files/ja/glossary/sql_injection/updates_loginscreen.png`
- `translated-content/files/ja/web/html/element/meta/name/theme-color/theme-color.png`
- `translated-content/files/ja/web/css/vertical-align/star.png`
- `translated-content/files/ja/web/css/border-image-slice/border-diamonds.png`
- `translated-content/files/ja/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/align7.png`
- `translated-content/files/ja/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/align2.png`
- `translated-content/files/ja/web/css/css_flexible_box_layout/aligning_items_in_a_flex_container/align3.png`
- `translated-content/files/ja/web/css/image-rendering/blumen.jpg`
- `translated-content/files/ja/web/css/background-repeat/starsolid.gif`
- `translated-content/files/ja/web/css/object-position/mdn.svg`
- `translated-content/files/ja/web/css/css_transforms/using_css_transforms/logo.png`
- `translated-content/files/ja/web/css/blend-mode/br.png`
- `translated-content/files/ja/web/css/blend-mode/tr.png`
- `translated-content/files/ja/web/css/cross-fade()/br.png`
- `translated-content/files/ja/web/css/cross-fade()/tr.png`
- `translated-content/files/ja/web/css/css_box_alignment/align-container-subjects.png`
- `translated-content/files/ja/web/css/css_box_alignment/justify-content-start.png`
- `translated-content/files/ja/web/css/css_box_alignment/writing-mode-start.png`
- `translated-content/files/ja/web/css/css_box_alignment/justify-content-space-between.png`
- `translated-content/files/ja/web/css/url()/star.gif`
- `translated-content/files/ja/web/css/forced-color-adjust/windows-high-contrast.jpg`
- `translated-content/files/ja/web/css/object-fit/mdn_logo_only_color.png`
- `translated-content/files/ja/web/css/background-position/catfront.png`
- `translated-content/files/ja/web/css/background-position/startransparent.gif`
- `translated-content/files/ja/web/css/border-image-repeat/border.png`
- `translated-content/files/ja/web/css/-moz-image-rect/firefox.png`
- `translated-content/files/ja/web/css/css_backgrounds_and_borders/using_multiple_backgrounds/firefox.png`
- `translated-content/files/ja/web/css/css_backgrounds_and_borders/using_multiple_backgrounds/bubbles.png`
- `translated-content/files/ja/web/css/border-image-width/border.png`
- `translated-content/files/ja/web/events/orientation_and_motion_data_explained/gamma.png`
- `translated-content/files/ja/web/events/orientation_and_motion_data_explained/alpha.png`
- `translated-content/files/ja/web/events/orientation_and_motion_data_explained/axes.png`
- `translated-content/files/ja/web/events/orientation_and_motion_data_explained/beta2.png`

This weighs 268kB

**Comment by mfuji09** [comment]
@SphinxKnight 
I have created a PR for this issue. Thank you!
