### ISSUE TITLE
[ko] Duplicated mdn/content images/assets files should be removed from the tree

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#4545]
Since https://github.com/mdn/yari/pull/5215 has been merged, there is no apparent reason to have duplicated files from mdn/content in mdn/translated-content. After fiddling [a small script](https://gist.github.com/SphinxKnight/60d766b8d6cd970b42eaf967b8dac3ff) (adapted for ko), I was able to identify the following files under the tree which are identical and should be removed.

- `translated-content/files/ko/web/html/element/img/favicon72.png`
- `translated-content/files/ko/web/html/element/img/clock-demo-400px.png`
- `translated-content/files/ko/web/html/element/img/favicon144.png`
- `translated-content/files/ko/web/media/formats/audio_concepts/human-hearing-range.svg`
- `translated-content/files/ko/web/media/formats/audio_concepts/audio-waveform.svg`
- `translated-content/files/ko/web/media/formats/audio_concepts/audio-waveform-samples1.svg`
- `translated-content/files/ko/web/api/web_audio_api/audio-context_.png`
- `translated-content/files/ko/web/api/web_audio_api/advanced_techniques/sequencer.png`
- `translated-content/files/ko/web/api/web_audio_api/using_iir_filters/iir-filter-demo.png`
- `translated-content/files/ko/web/api/web_audio_api/visualizations_with_web_audio_api/wave.png`
- `translated-content/files/ko/web/api/web_audio_api/visualizations_with_web_audio_api/bar-graph.png`
- `translated-content/files/ko/web/api/web_audio_api/controlling_multiple_parameters_with_constantsourcenode/customsourcenode-as-splitter.svg`
- `translated-content/files/ko/web/api/web_audio_api/web_audio_spatialization_basics/web-audio-spatialization.png`
- `translated-content/files/ko/web/api/analysernode/fttaudiodata_en.svg`
- `translated-content/files/ko/web/api/element/getboundingclientrect/element-box-diagram.png`
- `translated-content/files/ko/web/web_components/using_shadow_dom/dom-screenshot.png`
- `translated-content/files/ko/web/web_components/using_shadow_dom/shadowdom.svg`
- `translated-content/files/ko/learn/css/first_steps/what_is_css/html-example.png`
- `translated-content/files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_todo_list_beginning/unstyled-app.png`
- `translated-content/files/ko/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/default-create-react-app.png`
- `translated-content/files/ko/learn/javascript/building_blocks/image_gallery/gallery.png`
- `translated-content/files/ko/learn/javascript/building_blocks/events/mdn-mozilla-events-runway.png`
- `translated-content/files/ko/learn/javascript/building_blocks/events/bubbling-capturing.png`

This weighs 589kB

**Comment by hochan222** [comment]
Currently, there are 4 remaining.

- `translated-content/files/ko/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/raster-vector-default-size.png`
- `translated-content/files/ko/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/raster-vector-zoomed.png`
- `translated-content/files/ko/glossary/cross_axis/basics4.png`
- `translated-content/files/ko/glossary/cross_axis/basics3.png`

**Comment by hochan222** [comment]
The issue has been resolved and we will close it. Thank you all for your hard work.

Have a good day :)
