### ISSUE TITLE
Duplicated mdn/content images/assets files should be removed from the tree (zh-CN)

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#4547]
Since https://github.com/mdn/yari/pull/5215 has been merged, there is no apparent reason to have duplicated files from mdn/content in mdn/translated-content. After fiddling [a small script](https://gist.github.com/SphinxKnight/60d766b8d6cd970b42eaf967b8dac3ff) (adapted for zh-CN), I was able to identify the following files under the tree which are identical and should be removed.

- `translated-content/files/zh-cn/web/html/element/meta/name/theme-color/theme-color.png`
- `translated-content/files/zh-cn/web/html/element/img/favicon72.png`
- `translated-content/files/zh-cn/web/html/element/img/clock-demo-400px.png`
- `translated-content/files/zh-cn/web/html/element/img/favicon144.png`

This weighs 124kB

**Comment by yin1999** [comment]
Done in #10485
