### ISSUE TITLE
Duplicated mdn/content images/assets files should be removed from the tree (zh-TW)

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#4548]
Since https://github.com/mdn/yari/pull/5215 has been merged, there is no apparent reason to have duplicated files from mdn/content in mdn/translated-content. After fiddling [a small script](https://gist.github.com/SphinxKnight/60d766b8d6cd970b42eaf967b8dac3ff) (adapted for zh-TW), I was able to identify the following files under the tree which are identical and should be removed.

- `translated-content/files/zh-tw/web/javascript/eventloop/the_javascript_runtime_environment_example.svg`
- `translated-content/files/zh-tw/web/api/canvas_api/tutorial/compositing/canvas_clipping_path.png`
- `translated-content/files/zh-tw/web/api/canvas_api/tutorial/compositing/canvas_clip.png`
- `translated-content/files/zh-tw/learn/css/first_steps/what_is_css/html-example.png`
- `translated-content/files/zh-tw/learn/css/first_steps/how_css_works/rendering.svg`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/03-unstyled-todo-app.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/05-styled-todo-app.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/02-todos-component-rendered.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/01-todo-list-app.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_todo_list_beginning/04-svelte-accessibility-support.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_getting_started/vue-default-app.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/vue_first_component/rendered-todoitem.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/01-svelte-starter-app.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/02-svelte-component-scoped-styles.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/svelte_getting_started/03-svelte-repl-in-action.png`
- `translated-content/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/react_getting_started/default-create-react-app.png`
- `translated-content/files/zh-tw/learn/javascript/first_steps/what_went_wrong/not-a-function.png`
- `translated-content/files/zh-tw/learn/javascript/first_steps/what_went_wrong/variable-is-null.png`
- `translated-content/files/zh-tw/learn/javascript/first_steps/what_went_wrong/console-log-output.png`

This weighs 443kB

**Comment by yin1999** [comment]
Done in #10485
