### ISSUE TITLE
Issue with "Object": [es]

### ISSUE THREAD

**Issue by telara2801** [mdn/translated-content#4558]
MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object

#### What information was incorrect, unhelpful, or incomplete? 

there are a lot information pending to traslate to spanish and son of the are with mistake

<details>
<summary>Some examples of pages documenting `Object` for JS that have issues:</summary>
<br>

- [Métodos del constructor Object](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object#métodos_del_constructor_object) (a section of the [Global_Objects/Object page](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object))
- *suggested translation/correction (?) for* [Object.defineProperties()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties):
Agrega las propiedades nombradas descritas por los descriptores dados a un objeto.
- [Object.entries()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)
Returns an array containing all of the [key, value] pairs of a given object's own enumerable string properties.
- [Object.freeze()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze)
Freezes an object: other code can't delete or change any properties.
- [Object.fromEntries()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/fromEntries)
Returns a new object from an iterable of key-value pairs (reverses [Object.entries](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/entries)).
- [Object.getOwnPropertyDescriptor()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor)
Returns a property descriptor for a named property on an object.
- [Object.getOwnPropertyDescriptors()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptors)
Returns an object containing all own property descriptors for an object.
- [Object.getOwnPropertyNames()](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames)
Returns an array containing the names of all of the given object's own enumerable and non-

</details>

#### Specific section or headline? 

Metodos del constructor, esta una poarte en espanol y muchas en ingles, existe un mix de ambos idiomas.

#### What did you expect to see? 

all in spanish but there are mix of Spanish and english 

#### Did you test this? If so, how? 

Iam studing the matial from the web page

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/object`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Object
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/object/index.html
* Last commit: https://github.com/mdn/translated-content/commit/3f5025eba18d07c319fee9d28e215d315ef5d1b2
* Document last modified: 2022-03-11T00:14:44.000Z

</details>

**Comment by JuanVqz** [comment]
Hola @telara2801 muchas gracias por abrir un issue!

Disculpa, no me queda claro que estas reportando, podrias abundar por favor?

Si deseas apoyar a la comuinidad en español puedes:
* [Actualizar el contenido con la versión en inglés](https://github.com/mdn/translated-content/discussions/4029)
* [Revisar issues](https://github.com/mdn/translated-content/issues?q=is%3Aopen+is%3Aissue+label%3Al10n-es)
* [Unirte a nuestro equipo](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

Saludos.

**Comment by cw118** [comment]
I reformatted the original issue a bit to improve readability (I hope that's okay), looks like the main issue is that there's some text on certain Spanish pages that hasn't been translated and is still in English. I do agree that some further clarification would be helpful though

**Comment by JuanVqz** [comment]
> 

@cw118 thank you :rock:

**Comment by JuanVqz** [comment]
Hola @telara2801, si gustas podemos hablar en español para que sea más fácil para ambos.

Como comentó cw118, al parecer te diste cuenta que la documentación en Español esta bastante incompleta y es cierto, nos gustaría agregar más documentación en español, seguramente con tu ayuda podremos lograrlo, te gustaría ayudar?

Si no sabes por donde comenzar, únete al chat en español donde te podemos ayudar y tu a nosotros, te esperamos :+1: 

https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org

Saludos!
