### ISSUE TITLE
Issue with "@media": any-hover の説明文が不自然です

### ISSUE THREAD

**Issue by k08045kk** [mdn/translated-content#4572]
MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/@media

#### What information was incorrect, unhelpful, or incomplete?
> any-hover
> 入力メカニズムで、ユーザーが要素上でのホバーを使用することができるものあるか。

「・・・使用することができるものあるか。」は、あまりにも言い回しが不自然です。

#### Specific section or headline?
メディア特性
https://developer.mozilla.org/ja/docs/Web/CSS/@media#メディア特性

#### What did you expect to see?
> any-hover
> 入力メカニズムで、ユーザーが要素上でのホバーを使用することができるか。

「・・・使用することができるものあるか。」→「・・・使用することができるか。」

any-hover と hover の原文がほぼ同じであるため、 hover の翻訳に合わせました。

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ja/web/css/@media`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/@media
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/@media/index.md
* Last commit: https://github.com/mdn/translated-content/commit/3f5025eba18d07c319fee9d28e215d315ef5d1b2
* Document last modified: 2022-03-11T00:14:44.000Z

</details>

**Comment by mfuji09** [comment]
any-hover と hover は意味が異なります。
any-hover は複数のポインティングデバイスのうち、ホバーが有効なものが 1 つでもあるかどうかを検査するのに対し、 hover はメインのポインティングデバイスに対して検査をします。
ですから、「～使用することができるものがあるか」という翻訳は妥当だと思います。逆に、「～使用することができるか」では意味が失われます。

**Comment by mfuji09** [comment]
@k08045kk 

any-hover と hover は意味が異なります。
any-hover は複数のポインティングデバイスのうち、ホバーが有効なものが 1 つでもあるかどうかを検査するのに対し、 hover はメインのポインティングデバイスに対して検査をします。
ですから、「～使用することができるものがあるか」という翻訳は妥当だと思います。逆に、「～使用することができるか」では意味が失われます。

**Comment by k08045kk** [comment]
確かに、その通りです。 `hover`の翻訳をそのまま適用するのは乱暴でした。

#### What did you expect to see?
> any-hover
> 入力メカニズムで、ユーザーが要素上でのホバーを使用することができるものがあるか。

「・・・使用することができるものあるか。」→「・・・使用することができるもの**が**あるか。」

**Comment by mfuji09** [comment]
@k08045kk さん
それならよいと思います。
これは簡単な修正ですので、できれば、ご自分でプルリクエストを作るか、GitHub上から直接編集するかしてみてください。
