### ISSUE TITLE
Remove unwanted macros

### ISSUE THREAD

**Issue by escattone** [mdn/translated-content#4579]
We'd like to remove the following macros from all documents (English, non-English, and archived):

- [x] `fx_minversion_header`
- [x] `fx_minversion_inline`
- [ ] `gecko_minversion_header`
- [ ] `gecko_minversion_inline`
- [x] https://github.com/mdn/translated-content/issues/5170
- [x] `languages`

**Comment by SphinxKnight** [comment]
Tagging all active locales "for reach", if macros are already absent from any, please let me know so that I can remove the right tags.

**Comment by yin1999** [comment]
@SphinxKnight removed all those macros in `l10n-zh` via #4728 #4729

**Comment by SphinxKnight** [comment]
Tbh, #5603 arrived later than this one (2021 ;))

**Comment by mfuji09** [comment]
The all macros have been removed in the `ja` locale.

**Comment by yin1999** [comment]
Done for `ko` in #8096.

**Comment by Graywolf9** [comment]
I think this is done in `es`

doing: 
````
rg -i "\{\{\s?(fx_minversion_header|fx_minversion_inline|gecko_minversion_header|gecko_minversion_inline|IncludeSubnav|languages)"```
throws 0 results
