### ISSUE TITLE
Content bug: Different operator precedence in russian and english versions

### ISSUE THREAD

**Issue by aleksanderantropov** [mdn/translated-content#4589]
## What page(s) did you find the problem on?

English version: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table
Russian version: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table

## Specific page section or heading?

[Table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table)

## What is the problem?

Precedence values are different. For instance yield and assignment operators

## What did you expect to see?

Tables are the same

## Did you test this? If so, how?

No

**Comment by teoli2003** [comment]
Yes, the Russian translation is likely behind. Transferring…

**Comment by cw118** [comment]
@aleksanderantropov thanks for reporting! I'll be closing since this issue is being tracked in/is a "duplicate" of #3470.
