### ISSUE TITLE
Replace {{anch}} macro with Markdown links

### ISSUE THREAD

**Issue by wbamberg** [mdn/translated-content#4614]
Over in https://github.com/mdn/content/pull/13802 , @queengooborg replaced all usages of the [`{{anch}}`](https://github.com/mdn/yari/blob/main/kumascript/macros/anch.ejs) macro with Markdown links.

If we could remove it from translated-content as well, we could remove the macro code from Yari.

@queengooborg used a script to do this which you can see at https://github.com/mdn/content/pull/13802 (I think this is the latest version isn't it?) and which I think should work with translated content?

**Comment by cw118** [comment]
Thank you @wbamberg! We'll get to work on this :)

**Comment by cw118** [comment]
Should this be done for frozen locales as well? (@SphinxKnight hope it's OK to tag you)

**Comment by SphinxKnight** [comment]
I don't think it should be done to frozen locales, as I understand it, they're not maintained. The only exception (which I can test locally later on) is that not doing anything would break the build once the macro is removed.

@wbamberg + @Rumyra  let us know if you think otherwise or if you have any other input.

**Comment by wbamberg** [comment]
It's a good question. Another related question is: "is it OK for us to delete macros from Yari, if they are still used in frozen locales". If it is OK, then if/when we unfreeze a locale we can expect a lot of cleanup before the locale is even buildable again. On the other hand, as you say, if the locale is unmaintained, (a) who would do the work and (b) it's hard for it to block platform improvements (I would guess that it's very hard for a locale to be unmaintained for very long without the unfreezing effort being quite daunting anyway).

I'd prefer if the existence of macro calls in frozen locales did *not* prevent us from removing the macros. But it would be good to have an explicit policy about this.

**Comment by Rumyra** [comment]
OK I had a little think - this really highlights the problem we are still serving a couple of frozen locales even if they aren't maintained... however I also think as long as the build doesn't break we should not update macros in frozen locales (maybe @schalkneethling can advise more on that).

It does put us in a tricky situation with the frozen locales we have, as they will be incredibly out of date now with all the platform changes that have happened. But I think that's out of scope for the answer to whether we replace macros (something we can address separately)

**Comment by schalkneethling** [comment]
> however I also think as long as the build doesn't break we should not update macros in frozen locales (maybe @schalkneethling can advise more on that).

I will have to double check whether we actually still build these. If they reference macros that no longer exist, it might:

1. Just break the build or,
2. Trigger a flaw

**Comment by yin1999** [comment]
> Thank you @wbamberg! We'll get to work on this :)
> 
> edit: the script works quite nicely, I ended up using the regexp
> 
> ```
> /([\w"]+>[\w\s]*)?(`)?(?<!\\){{[ ]?[aA]nch[ ]?\("([^"]*)"(?:, "([^"]*)")?\)[ ]?}}(?:`)?/g
> ```
> 
> for french, then I used `\{\{[ ]?anch` to check manually and found just a few anch macros left :)
> 
> N.B. something I noticed is that anchors may have to be translated after running the script because the macro had an English argument

using `[ ]?` to replace the space after the comma may works better.

```js
/([\w"]+>[\w\s]*)?(`)?(?<!\\){{[ ]?[aA]nch[ ]?\("([^"]*)"(?:,[ ]?"([^"]*)")?\)[ ]?}}(?:`)?/g
```

**Comment by cw118** [comment]
Thank you @yin1999, I've edited the regexp in my original comment

**Comment by yin1999** [comment]
Removed all the `anch` macro in `l10-zh` with pr: #4668 #4705 #4708

**Comment by queengooborg** [comment]
Thanks @cw118 and @yin1999 for the updated regex!  I've used it to perform a rerun on the English content as well, as there were a lot of instances I embarrassingly missed (I searched for `{{anch(` when I should've searched for `anch(`).

I tweaked the regex once again to catch single quotes and used named capture groups.  An updated version of the script can be found on [my new PR](https://github.com/mdn/content/pull/14063)!

**Comment by SphinxKnight** [comment]
fr `{{anch}}`s out thanks to @cw118 on https://github.com/mdn/translated-content/pull/4617 :metal:

**Comment by victor0x16** [comment]
pt-BR is almost done on [#4614](https://github.com/mdn/translated-content/issues/4614) 🚀 !

Thanks @cw118 and @queengooborg, the ```regexp``` and the ```script``` worked just fine 👌 !

**Comment by victor0x16** [comment]
PR [#4946](https://github.com/mdn/translated-content/pull/4946) replaced {{anch}} macros for pt-BR 🎉 🚀 !

**Comment by queengooborg** [comment]
Whoo, thank you!  All that remains now is `pt-br`!

**Comment by cw118** [comment]
I did another search using `\{[ ]?anch` and I found a few `{{anch}}` macros left, so I have created PRs for each locale that will hopefully remove all uses and mentions of `{{anch}}` from `translated-content` :)

**Comment by cw118** [comment]
I believe all `{{anch}}` and `{{manch}}` macros have been removed from `translated-content` :)
