### ISSUE TITLE
Issue with "Introduction au JavaScript asynchrone": Broken links to GitHub examples

### ISSUE THREAD

**Issue by StephaneRegnie** [mdn/translated-content#4646]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Asynchronous/Introducing

#### What information was incorrect, unhelpful, or incomplete?
All links to examples files are broken (404 error).

#### Specific section or headline?
All sections.

#### What did you expect to see?
The files to check on GitHub or example pages as for other pages of this tutorial.

#### Did you test this? If so, how?
Yes for all links.

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/learn/javascript/asynchronous/introducing`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/Asynchronous/Introducing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/javascript/asynchronous/introducing/index.md
* Last commit: https://github.com/mdn/translated-content/commit/a1bec3ff365a7dbb2a28524a5b4cb4cc20e742e7
* Document last modified: 2021-12-12T17:03:24.000Z

</details>

**Comment by cw118** [comment]
Merci pour ce rapport, je vais jeter un œil

**Comment by StephaneRegnie** [comment]
👍
