### ISSUE TITLE
Issue with "Technologies web pour développeurs": (short summary here please)

### ISSUE THREAD

**Issue by mikybwoy** [mdn/translated-content#4667]
MDN URL: https://developer.mozilla.org/fr/docs/Web

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web`
* MDN URL: https://developer.mozilla.org/fr/docs/Web
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/index.md
* Last commit: https://github.com/mdn/translated-content/commit/2f1c304fd325abbbd625b5ec9e8f8e72d818653a
* Document last modified: 2021-11-16T06:45:02.000Z

</details>

**Comment by JuanVqz** [comment]
@cw118 I didn't know if remove it or assign it to fr, I know you know what to do :)

**Comment by SphinxKnight** [comment]
@mikybwoy please provide us with more details so that we can help. I'm closing this issue as of now as the description is empty. We can reopen it if necessary.
