### ISSUE TITLE
{{manch}} macros on Spanish pages

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#4685]
This is related/very similar to issue 4614. The `{{manch}}` macro has also been deprecated (credit goes to **SphinxKnight** for finding it) and should be removed from these Spanish files (excludes `orphaned` and `conflicting`):

- [ ] mdn/structures/macros/other/index.html
- [ ] web/api/blobbuilder/index.html
- [ ] web/api/eventlistener/index.html
- [ ] web/api/websocket/index.html

**Comment by Graywolf9** [comment]
Hi! @cw118 I see that `mdn/structures/macros/other/index.html` has a list of replaced macros, that's why it appears, should we remove it anyways?

**Comment by cw118** [comment]
@Graywolf9 based on the [en-US version of the file](https://github.com/mdn/content/blob/main/files/en-us/mdn/structures/macros/other/index.md?plain=1), updating the es "Other macros" page would remove the mention of `manch` as well as several other deprecated macros (e.g. `{{TemplateLink}}`).

There isn't any need to reopen this issue, but updating that page as part of "deprecated macro removal" would be great :)
