### ISSUE TITLE
{{manch}} macros on Chinese pages

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#4690]
This is related/very similar to issue 4614. The `{{manch}}` macro has also been deprecated (credit goes to **SphinxKnight** for finding it) and should be removed from these simplified Chinese files (excludes `orphaned` and `conflicting`):

- [ ] mdn/structures/macros/other/index.html
- [ ] web/api/blobbuilder/index.html
- [ ] web/api/websocket/bufferedamount/index.html

And also from this traditional Chinese file:

- [ ] web/api/websocket/index.html

**Comment by yin1999** [comment]
I'll working on it (after merging #4668 ).
