### ISSUE TITLE
Image links broken

### ISSUE THREAD

**Issue by isaacbatst** [mdn/translated-content#4694]
Hello guys! The image links on [theses](https://developer.mozilla.org/pt-BR/docs/Web/HTML/Element/figura#exemplos) examples are broken.

![Captura de tela de 2021-02-23 14-43-36](https://user-images.githubusercontent.com/18752045/108884689-a4561e80-75e5-11eb-8166-3cd5fdc92243.png)

**Comment by Techi-Dev** [comment]
if the issue is still insist refer to this page https://stackoverflow.com/questions/1694937/firefox-show-broken-images

**Comment by cw118** [comment]
@Techi-Dev thank you for looking into this, however the issue is not caused by a problem with Firefox but instead by wrong image sources.

I'm not 100% sure, but I believe the correct one to use here is `favicon-192x192.png`.
