### ISSUE TITLE
Change to Firefox sidebar requires new translations

### ISSUE THREAD

**Issue by schalkneethling** [mdn/translated-content#4707]
Please see the following announcement discussion regarding new translations needed for the Firefox sidebar macro 🙏 
https://github.com/mdn/translated-content/discussions/4706

**Comment by yin1999** [comment]
Suggestions for `zh-CN`:

```js
"zh-CN": {
  "Firefox_releases": "Firefox 发行说明",
    "Firefox_release_notes_developer": "面向开发者的 Firefox 发行说明",
    "Experimental_features_firefox": "Firefox 中的实验性功能",
  "Firefox_documentation": "Firefox 文档",
}
```

@irvin Any advice ?

**Comment by irvin** [comment]
"zh-TW": {
    "Firefox_releases": "Firefox 版本資訊",
      "Firefox_release_notes_developer": "開發者的 Firefox 版本資訊",
      "Experimental_features_firefox": "Firefox 中的實驗性功能",
    "Add-ons": "附加元件",
      "Browser_extensions": "擴充套件",
      "Themes": "佈景主題",
    "Firefox_documentation": "Firefox 文件",
  }

**Comment by yin1999** [comment]
@cw118 added `l10n-zh` translation via mdn/yari#5697

**Comment by myshov** [comment]
l10n-ru done in https://github.com/mdn/yari/pull/5699

**Comment by coding-Alice** [comment]
ko is done in [mdn/yari#7971](https://github.com/mdn/yari/pull/7971)

**Comment by hochan222** [comment]
All issues have been resolved and the issue will be closed! 

Happy new year :)
