### ISSUE TITLE
Content bug: incorrect example in "<head>标签里有什么? Metadata-HTML中的元数据"

### ISSUE THREAD

**Issue by yuantingyuezhi** [mdn/translated-content#4724]
## What page(s) did you find the problem on?

https://developer.mozilla.org/zh-CN/docs/learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML

## Specific page section or heading?

[指定你的文档中字符的编码](https://developer.mozilla.org/zh-CN/docs/learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML#%E6%8C%87%E5%AE%9A%E4%BD%A0%E7%9A%84%E6%96%87%E6%A1%A3%E4%B8%AD%E5%AD%97%E7%AC%A6%E7%9A%84%E7%BC%96%E7%A0%81)

## What is the problem?

On this page it says:
![image](https://user-images.githubusercontent.com/78637243/159106136-8a3a4627-5d81-461e-a09e-5d2d82951162.png)
but in fact,if you change the charset to "GBK",you would get a page like this:
![image](https://user-images.githubusercontent.com/78637243/159106261-3476c10b-a6f9-409e-9ec1-223896189e05.png)
The original example may mislead beginners who are not familiar with character encoding.The example image on the page above seems like missing fonts,not a problem of encoding.
## Did you test this? If so, how?
Yes.Download the  html on https://github.com/roy-tian/learning-area/blob/master/html/introduction-to-html/the-html-head/meta-example.html ,change meta charset to "GBK" and browse it with firefox.

**Comment by catlair** [comment]
文件的编码格式错误。虽然在 html 中使用了 `<meta charset="GBK" />` ，但是 html 文件是 `utf-8` 的。

![image](https://user-images.githubusercontent.com/44313800/159109943-8c9e7d93-62b0-4cfe-97ec-2a29a5b4f361.png)
![image](https://user-images.githubusercontent.com/44313800/159109954-73939660-3716-4fc8-be48-5da98ed65c78.png)

如果将，html 文件编码改成 `gbk`，就能看到想要的结果了。

**Comment by yuantingyuezhi** [comment]
@catlair 我的意思是指按照https://developer.mozilla.org/zh-CN/docs/learn/HTML/Introduction_to_HTML/The_head_metadata_in_HTML 这个页面的指引操作（该操作就是要显示出乱码，所以故意将字符编码改成不正确的），应该整个页面的非ASCII字符都变成乱码，但是页面上的示例图片中只有藏文是乱码，“元数据示例”“藏语示例”等字符仍然正常显示，这是不可能的，原因正如你所说的那样。
所以这个图片会误导初学者。
而如果需要先将下载的html页面转换成gbk编码，然后再粘帖藏文文本，再修改meta charset的值这样的操作，则与该页面所表达的初衷应该是不符的。

**Comment by yin1999** [comment]
赞同你的观点

**Comment by catlair** [comment]
有道理，原文使用的是英文和日文举例，英文是没有这种问题的，我想应该是翻译的时候没有考虑到这个问题。 

不过我很好奇，他的编辑器是 GBK 编码的吗，为啥会截出这种图 😝
