### ISSUE TITLE
Content bug: The code example of apply method on Function.prototype in zh-CN is incorrect/confusing

### ISSUE THREAD

**Issue by jeff-zhenz** [mdn/translated-content#4730]
## What page(s) did you find the problem on?

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Function/apply#using_apply_to_chain_constructors

## Specific page section or heading?

"使用示例：" code example

## What is the problem?

`var myInstance = new MyConstructor(myArray); //Fix MyConstructor.construct is not a function` line is different from the content in en-US, which directly call the `construct` method, and second,  I don't understand the comment of line, seems it doesn't make sense to me

## What did you expect to see?

Maybe just the same code with en-US

## Did you test this? If so, how?

Yes, no error but confuses readers

**Comment by awxiaoxian2020** [comment]
I couldn't find what you said now. Pleasen give the line number :)

**Comment by jiwangyihao** [comment]
> > If you try to run the sample code in the English version of the documentation in the browser console, you will see that it does not work properly. 如果你尝试在浏览器控制台中运行英文版本文档中的示例代码，你就会发现它无法正常运行。 ![A screenshot of the running result of the English version's sample code](https://user-images.githubusercontent.com/51940778/173350697-30b64b54-0f93-47eb-b6d3-14e468f3ed4e.png) The simplified Chinese version of the documentation makes changes to the sample code to solve this problem. 而简体中文文档对示例代码作出的修改正是为了解决这一问题。 ![A screenshot of the running result of the simplified Chinese version's sample code](https://user-images.githubusercontent.com/51940778/173351851-96286a0e-3945-4f25-8748-2336c3d6aa6a.png) As for the meaning of the comment, I believe that everyone who has seen the error message after running the English example can understand what it means: fix the error in the English documentation. 至于注释的含义，我相信每个看过英文版示例运行后的错误信息的人都能明白它的意思：修正了英文版文档中的这个错误。
> 
> Thanks for your reply. I don't know whether the English version fixed the problem. If not, Why not post an issue in content repo?

Thanks for reminding.
感谢提醒。
I actually found it after seeing this issue, the issue has been posted into the English repository.
我其实是在看到这个 issue 后才发现的，英文仓库那里 issue 已提

**Comment by jiwangyihao** [comment]
> > If you try to run the sample code in the English version of the documentation in the browser console, you will see that it does not work properly. 如果你尝试在浏览器控制台中运行英文版本文档中的示例代码，你就会发现它无法正常运行。 ![A screenshot of the running result of the English version's sample code](https://user-images.githubusercontent.com/51940778/173350697-30b64b54-0f93-47eb-b6d3-14e468f3ed4e.png) The simplified Chinese version of the documentation makes changes to the sample code to solve this problem. 而简体中文文档对示例代码作出的修改正是为了解决这一问题。 ![A screenshot of the running result of the simplified Chinese version's sample code](https://user-images.githubusercontent.com/51940778/173351851-96286a0e-3945-4f25-8748-2336c3d6aa6a.png) As for the meaning of the comment, I believe that everyone who has seen the error message after running the English example can understand what it means: fix the error in the English documentation. 至于注释的含义，我相信每个看过英文版示例运行后的错误信息的人都能明白它的意思：修正了英文版文档中的这个错误。
> 
> Thanks for your reply. I don't know whether the English version fixed the problem. If not, Why not post an issue in content repo?

It seems that there is a problem with the Chinese version here.
这里中文版好像确实是有问题的。
![Snipaste_2022-06-13_20-55-19](https://user-images.githubusercontent.com/51940778/173358429-7d6767f3-1d57-48ed-a315-3cf4688c4e3c.png)
There is a code snippet above.
上文中有一段前置代码。
The example in the English document will not report errors after running this.
运行之后英文版文档的示例就不会报错。
So it seems that the changes made in the simplified Chinese version of this is indeed unnecessary.
这样看来简体中文版对此进行的改动的确是多余的。

**Comment by awxiaoxian2020** [comment]
> > > If you try to run the sample code in the English version of the documentation in the browser console, you will see that it does not work properly. 如果你尝试在浏览器控制台中运行英文版本文档中的示例代码，你就会发现它无法正常运行。 ![A screenshot of the running result of the English version's sample code](https://user-images.githubusercontent.com/51940778/173350697-30b64b54-0f93-47eb-b6d3-14e468f3ed4e.png) The simplified Chinese version of the documentation makes changes to the sample code to solve this problem. 而简体中文文档对示例代码作出的修改正是为了解决这一问题。 ![A screenshot of the running result of the simplified Chinese version's sample code](https://user-images.githubusercontent.com/51940778/173351851-96286a0e-3945-4f25-8748-2336c3d6aa6a.png) As for the meaning of the comment, I believe that everyone who has seen the error message after running the English example can understand what it means: fix the error in the English documentation. 至于注释的含义，我相信每个看过英文版示例运行后的错误信息的人都能明白它的意思：修正了英文版文档中的这个错误。
> > 
> > 
> > Thanks for your reply. I don't know whether the English version fixed the problem. If not, Why not post an issue in content repo?
> 
> It seems that there is a problem with the Chinese version here. 这里中文版好像确实是有问题的。 ![Snipaste_2022-06-13_20-55-19](https://user-images.githubusercontent.com/51940778/173358429-7d6767f3-1d57-48ed-a315-3cf4688c4e3c.png) There is a code snippet above. 上文中有一段前置代码。 The example in the English document will not report errors after running this. 运行之后英文版文档的示例就不会报错。 So it seems that the changes made in the simplified Chinese version of this is indeed unnecessary. 这样看来简体中文版对此进行的改动的确是多余的。

I think you can make a PR. :)

**Comment by jiwangyihao** [comment]
> > > > If you try to run the sample code in the English version of the documentation in the browser console, you will see that it does not work properly. 如果你尝试在浏览器控制台中运行英文版本文档中的示例代码，你就会发现它无法正常运行。 ![A screenshot of the running result of the English version's sample code](https://user-images.githubusercontent.com/51940778/173350697-30b64b54-0f93-47eb-b6d3-14e468f3ed4e.png) The simplified Chinese version of the documentation makes changes to the sample code to solve this problem. 而简体中文文档对示例代码作出的修改正是为了解决这一问题。 ![A screenshot of the running result of the simplified Chinese version's sample code](https://user-images.githubusercontent.com/51940778/173351851-96286a0e-3945-4f25-8748-2336c3d6aa6a.png) As for the meaning of the comment, I believe that everyone who has seen the error message after running the English example can understand what it means: fix the error in the English documentation. 至于注释的含义，我相信每个看过英文版示例运行后的错误信息的人都能明白它的意思：修正了英文版文档中的这个错误。
> > > 
> > > 
> > > Thanks for your reply. I don't know whether the English version fixed the problem. If not, Why not post an issue in content repo?
> > 
> > 
> > It seems that there is a problem with the Chinese version here. 这里中文版好像确实是有问题的。 ![Snipaste_2022-06-13_20-55-19](https://user-images.githubusercontent.com/51940778/173358429-7d6767f3-1d57-48ed-a315-3cf4688c4e3c.png) There is a code snippet above. 上文中有一段前置代码。 The example in the English document will not report errors after running this. 运行之后英文版文档的示例就不会报错。 So it seems that the changes made in the simplified Chinese version of this is indeed unnecessary. 这样看来简体中文版对此进行的改动的确是多余的。
> 
> I think you can make a PR. :)

In fact I'm going to do that. (hh
