### ISSUE TITLE
Issue with "Ajouter un point d’arrêt conditionnel": Video Not Available

### ISSUE THREAD

**Issue by petittitouan** [mdn/translated-content#4750]
MDN URL: https://developer.mozilla.org/fr/docs/Tools/Debugger/How_to/Set_a_conditional_breakpoint

#### What information was incorrect, unhelpful, or incomplete?
Video Not Available

#### What did you expect to see?
The Video

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/tools/debugger/how_to/set_a_conditional_breakpoint`
* MDN URL: https://developer.mozilla.org/fr/docs/Tools/Debugger/How_to/Set_a_conditional_breakpoint
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/tools/debugger/how_to/set_a_conditional_breakpoint/index.html
* Last commit: https://github.com/mdn/translated-content/commit/36dd1801df270db5af29576e3ba0c071933e6cca
* Document last modified: 2021-02-11T17:22:05.000Z

</details>

**Comment by cw118** [comment]
Thanks for reporting! This will probably be "resolved" when the Tools docs are removed from MDN/redirected (cf. #4822).

**Comment by cw118** [comment]
The devtools section is no longer on MDN as of #4841.
