### ISSUE TITLE
Content bug: A example in Array.prototype.copyWithin() is incorrect

### ISSUE THREAD

**Issue by jiwoo84** [mdn/translated-content#4756]
## What page(s) did you find the problem on?

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Array/copyWithin

## Specific page section or heading?

in JavaScript Demo: Array.copyWithin()
second example

## What is the problem?

// expected output: Array ["d", "d", "e", "d", "e"]

## What did you expect to see?

// expected output: Array ["a", "d", "e", "d", "e"]

## Did you test this? If so, how?

yes. the result was ["a", "d", "e", "d", "e"].

**Comment by yin1999** [comment]
This example is correct. The `copyWithin` method will modify the origin array and then return the origin array. You can run the example in the console in the order of the examples.

The following code will modify the origin array:

```js
const array1 = ['a', 'b', 'c', 'd', 'e'];

// copy [ 'd' ] (index 3) to replace [ 'a' ] (index 0)
console.log(array1.copyWithin(0, 3, 4));  // expected output: Array ["d", "b", "c", "d", "e"]

console.log(array1) // the origin array will be `["d", "b", "c", "d", "e"]`
```

Then run the following code:

```js
// copy [ 'd', 'e' ] (index 3, 4) to replace [ 'd', 'e' ] (index 1, 2)
console.log(array1.copyWithin(1, 3));
// expected output: Array ["d", "d", "e", "d", "e"]
```

**Comment by yin1999** [comment]
This example is correct. The `copyWithin` method will modify the origin array and then return the origin array. You can run the example in the console in the order of the examples.

The following code will modify the origin array:

```js
const array1 = ['a', 'b', 'c', 'd', 'e'];

// copy [ 'd' ] (index 3) to replace [ 'a' ] (index 0)
console.log(array1.copyWithin(0, 3, 4));  // expected output: Array ["d", "b", "c", "d", "e"]

console.log(array1) // the origin array will be `["d", "b", "c", "d", "e"]`
```

Then run the following code:

```js
// copy [ 'd', 'e' ] (index 3, 4) to replace [ 'd', 'e' ] (index 1, 2)
console.log(array1.copyWithin(1, 3));
// expected output: Array ["d", "d", "e", "d", "e"]
```

**Comment by cw118** [comment]
@jiwoo84 thanks for the issue! @yin1999 is correct here, it looks like there's just a slight misunderstanding for this example — `array1` is first modified by the "first `copyWithin` line" (meaning `['a', 'b', 'c', 'd', 'e']` becomes `["d", "b", "c", "d", "e"]`), then `copyWithin(1, 3)` is used again on the array **returned from that first line** (so the result of the first `copyWithin()`, **`["d", "b", "c", "d", "e"]`**, is given as input and becomes `["d", "d", "e", "d", "e"]`).
