### ISSUE TITLE
Issue with "Navigator.geolocation": (ja-JP) Geolocation API spec is not recommendation by W3C.

### ISSUE THREAD

**Issue by Genbuchan** [mdn/translated-content#4763]
MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Navigator/geolocation

#### What information was incorrect, unhelpful, or incomplete?

Geolocation APIはW3Cによって勧告とされていません。

Geolocation API is not recommendation by W3C.

#### Specific section or headline?

- [仕様書 (Specifications)](https://developer.mozilla.org/ja-JP/docs/Web/API/Navigator/geolocation#specifications)

#### What did you expect to see?

Geolocation APIの仕様書は「Candidate Recommendation Draft (勧告候補案)」であるべきです。

Geolocation API specifications should be "Candidate Recommendation Draft".

* Folder: `ja/web/api/navigator/geolocation`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Navigator/geolocation
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/navigator/geolocation/index.md
* Last commit: https://github.com/mdn/translated-content/commit/72bddf5559211cc0f860ca9e1d7b10f701691cc1
* Document last modified: 2022-02-10T13:12:14.000Z

</details>

**Comment by mfuji09** [comment]
英語版の最新版に更新するPRを出しました。
最新版では仕様書の状態を表示する欄がなくなっているので、この問題は自然に解消します。
