### ISSUE TITLE
Content bug: Complete spanish translation of operators/delete

### ISSUE THREAD

**Issue by stripTM** [mdn/translated-content#4771]
## What page(s) did you find the problem on?

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Operators/delete

## Specific page section or heading?

[Temporal dead zone](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Operators/delete#temporal_dead_zone)

## What is the problem?

Contains untranslated paragraphs. In addition it is necessary to do the html -> md migration.

## What did you expect to see?

Migrate and finish the translation

**Comment by marcelozarate** [comment]
Me gustaría hacer la traducción completa y hacer la migración a md

**Comment by JuanVqz** [comment]
> Me gustaría hacer la traducción completa y hacer la migración a markdown.

es todo tuyo!!! muchas gracias
