### ISSUE TITLE
웹 개발자 안내서 페이지 최신화가 필요합니다.

### ISSUE THREAD

**Issue by kraccoon-dev** [mdn/translated-content#4775]
## What page(s) did you find the problem on?

https://developer.mozilla.org/ko/docs/Web/Guide

## What is the problem?

최신화가 되어있지 않습니다.

## What did you expect to see?

https://developer.mozilla.org/en-US/docs/Web/Guide

**Comment by seonhwadawn** [comment]
안녕하세요, 혹시 이 페이지 제가 맡아서 번역 진행해도 될까요? 번역 기여는 처음이라 혹시나 싶어 여쭤봅니다.

**Comment by kraccoon-dev** [comment]
> 안녕하세요, 혹시 이 페이지 제가 맡아서 번역 진행해도 될까요? 번역 기여는 처음이라 혹시나 싶어 여쭤봅니다.

네, 진행해주셔도 됩니다.😃

**Comment by seonhwadawn** [comment]
안녕하세요! 문서 번역중 궁금한것이 생겨 질문드립니다. 현재 md버젼이 아닌 html문서로 작성중에 있습니다. 

Developer Guides의 API영역을 보면 FormData가 링크가 연결되어있고 뒤쪽이 회색 박스처리되어 있습니다. Audio and video manipulation에 있는 canvas의 경우는 {{htmlelement("canvas")} < 이렇게 작성하여 번역을 진행하였으나, FormData는 위처럼 진행하면 의도한대로 나오지 않아 혹시 다른 방법이 있는지 질문드립니다. 이해를 돕기위해이미지를 함께 첨부합니다. 감사합니다 :)

![image](https://user-images.githubusercontent.com/83253922/165236642-f7a846e4-9f2d-4569-89e5-bd9367e8ca66.png)

**Comment by kraccoon-dev** [comment]
@seonhwadawn 제가 아직 yari의 문서 변환 과정을 전부 이해한것은 아니기 때문에 정확한 이유라고 확신할 순 없지만, 아마 문서 유형 차이때문에 최종 랜더링 과정에서 약간의 변화가 있는것으로 보입니다.
현재 한글 문서는 html로 저장되어 있고, 영어 문서는 md로 저장되어 있습니다. 한글 문서를 md로 변환하여 작업을 진행하거나, 기존 링크 표현 방식을 따르면 추후 변환 시 올바르게 교체될 수 있을것 같습니다.

**Comment by seonhwadawn** [comment]
@kraccoon-dev  답변감사합니다. 다른 문서들 참고하여 여러방법을 시도했는데, 여전히 적용이 되지 않아 일단은 md로 바꾸어 다시 작업 진행하겠습니다!
