### ISSUE TITLE
Content bug: Error: Server responded with 403

### ISSUE THREAD

**Issue by Zeldox55** [mdn/translated-content#4843]
When i start my command canvas its turn error Error: Server responded with 403

**Comment by cw118** [comment]
Hi @Zeldox55, could you please provide details about how this issue is related to [MDN Web Docs](https://developer.mozilla.org) and what page(s) may need to be fixed?

**Comment by SphinxKnight** [comment]
Closing this one if there is no further information. Will reopen if details about MDN content is added.
