### ISSUE TITLE
Issue with "Наследование в JavaScript": (uncorrect link to OOJS lesson example)

### ISSUE THREAD

**Issue by ithrforu** [mdn/translated-content#4854]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/Objects/Classes_in_JavaScript#дальнейшее_упражнение

#### What information was incorrect, unhelpful, or incomplete?

Привет! [Ссылка](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_JS#Object-oriented_programming_from_10000_meters) на пример из руководства по Объектно-ориентированному JavaScript для начинающих в [уроке](https://developer.mozilla.org/ru/docs/Learn/JavaScript/Objects/Classes_in_JavaScript#дальнейшее_упражнение) про наследование ведёт на сам урок про наследование, но в английской версии. В уроке [OOP JS для начинающих](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Objects/Object-oriented_programming), кажется, нет абзаца с id `#Object-oriented_programming_from_10000_meters`.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/learn/javascript/objects/classes_in_javascript`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/Objects/Classes_in_JavaScript
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/javascript/objects/classes_in_javascript/index.html
* Last commit: https://github.com/mdn/translated-content/commit/149b599368b4e27cf7d05f270a43519f599372fd
* Document last modified: 2022-01-18T00:57:02.000Z

</details>

**Comment by sashasushko** [comment]
The link was fixed. The block _Object-oriented programming from 10000 meters_ will be added after translation. Thanks
