### ISSUE TITLE
Russian "SVG и CSS" page: white text is hard to see in dark mode

### ISSUE THREAD

**Issue by JustShiba** [mdn/translated-content#4856]
MDN URL: https://developer.mozilla.org/ru/docs/Web/SVG/Tutorial/SVG_and_CSS

## What is the problem?

When browsing in dark mode, the "Немного подробностей" section under [Общая информация: SVG](https://developer.mozilla.org/ru/docs/Web/SVG/Tutorial/SVG_and_CSS#information_svg) has white text on a light background, which makes the text extremely difficult to see.

I'm just leave the screenshot

![image](https://user-images.githubusercontent.com/79520443/160295123-b3103fbb-9ac1-4f84-a7ea-4cea7a5888e7.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/svg/tutorial/svg_and_css`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/SVG/Tutorial/SVG_and_CSS
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/svg/tutorial/svg_and_css/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1386fed7d38652d5848d315927e7e23a66cffd13
* Document last modified: 2021-10-20T10:28:52.000Z

</details>

**Comment by Techi-Dev** [comment]
You will probably need to use js if you are using dark and light bg mode and put a different text color for each mode to make it more readable and visible, but if you will be using one bg mode , you can change it using pure css.

**Comment by sashasushko** [comment]
Fixed
