### ISSUE TITLE
Content bug: zh-CN content error image url

### ISSUE THREAD

**Issue by UESTCzhouyuchuan** [mdn/translated-content#4865]
## What page(s) did you find the problem on?
[page url](https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#%E7%BE%8E%E6%9C%AF%E8%AE%BE%E8%AE%A1)
## What is the problem?
zh-CN version image does't show,but english verison does

**Comment by yin1999** [comment]
related issues: #3752, mdn/yari#5652.

**Comment by cw118** [comment]
@UESTCzhouyuchuan I looked at the page and the images seem to be working — could you please provide more details?

(And @yin1999 for what it's worth I believe this issue doesn't involve embedlivesample but I could be wrong)
