### ISSUE TITLE
Issue with "Vertical-align" : (The default value is middle)

### ISSUE THREAD

**Issue by shongs27** [mdn/translated-content#4883]
MDN URL: https://developer.mozilla.org/ko/docs/MDN/Contribute/Howto/Report_a_problem

#### What information was incorrect, unhelpful, or incomplete?
vertical-align mdn page is incorrect

https://developer.mozilla.org/ko/docs/Web/CSS/vertical-align

#### Specific section or headline?

Formal Definition

#### What did you expect to see?

The initial Value is listed as "baseline", but when I was working with a Chrome browser about Table tag, I didn't give any properties, but I think "middle" was applied as the default.

#### Did you test this? If so, how?

I tested it in React and JavaScript and repeated it, but the default was middle.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ko/mdn/contribute/howto/report_a_problem`
* MDN URL: https://developer.mozilla.org/ko/docs/MDN/Contribute/Howto/Report_a_problem
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/mdn/contribute/howto/report_a_problem/index.html
* Last commit: https://github.com/mdn/translated-content/commit/da78a9e329e272dedb2400b79a3bdeebff387d47
* Document last modified: 2020-12-08T19:42:17.000Z

</details>

**Comment by alattalatta** [comment]
안녕하세요 @shongs27 님, [`vertical-align` 명세](https://drafts.csswg.org/css2/#propdef-vertical-align)의 "Initial"을 보시면 "baseline"인 것을 확인하실 수 있습니다.

또한 말씀하신 바와 같이 `<table>` 요소로 확인해봤을 때도 `vertical-align: middle`을 지정한 것과 지정하지 않은 초기 상태일 때 렌더링되는 것이 달랐습니다.

다음은 `vertical-align`이 없을 때입니다.

<img width="83" alt="image" src="https://user-images.githubusercontent.com/9212605/160816715-90d06427-4b98-4e89-9280-bcb850ced9f4.png">

다음은 `vertical-align: middle`을 지정했을 때입니다.

<img width="87" alt="image" src="https://user-images.githubusercontent.com/9212605/160816792-5a3ae1da-8d3e-49e4-9378-d7547b68ac67.png">

[![Edit twilight-wave-ikse6h](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/twilight-wave-ikse6h?fontsize=14&hidenavigation=1&theme=dark)

`vertical-align`은 블록 레벨 요소에는 효과가 없으므로 `<table>`에 `display: inline-table`을 지정한 것을 참고해주세요.

**Comment by Techi-Dev** [comment]
There might be an issue to override safari and chrome default sometimes.
so try to apply display-inline-block; and vertical-align: middle; to your css in this case.

**Comment by hochan222** [comment]
@shongs27 님, 안녕하세요.

해당 이슈에 대해 답변이 된 듯하여, 우선 이슈를 닫겠습니다. 추가적인 의문사항이 생기실 경우 [content repo](https://github.com/mdn/content) issue에 문의하시면 조금 더 많은 견해의 의견들을 얻으 실 수 있어서 추천드립니다!

감사합니다. 🙇🙇
