### ISSUE TITLE
Issue with "Referencia DOM de Gecko": broken links

### ISSUE THREAD

**Issue by federico-cloud** [mdn/translated-content#4884]
MDN URL: https://developer.mozilla.org/es/docs/Web/API/Document_Object_Model

#### What information was incorrect, unhelpful, or incomplete?

The links of the entire page that talks about Gecko do not work

#### What did you expect to see?

the information about DOM 

#### Did you test this? If so, how?

browsing

<details>
<summary>MDN Content page report details</summary>

* Folder: `es/web/api/document_object_model`
* MDN URL: https://developer.mozilla.org/es/docs/Web/API/Document_Object_Model
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/api/document_object_model/index.html
* Last commit: https://github.com/mdn/translated-content/commit/2318b37e3fd17a3e76a29b9be7d1ce82f040c3bb
* Document last modified: 2021-02-11T17:20:58.000Z

</details>

**Comment by JuanVqz** [comment]
@federico-cloud hola! gracias por tu reporte, revise la documentación en inglés https://developer.mozilla.org/en-US/docs/Web/API/Document_Object_Model y ocurren dos cosas:

1. La documentación en español esta des-actualizada por eso aún tiene esos enlaces a Gecko pero ya no deberian de estar ahí.
2. Creo que le dedicaron una sección en particular a Gecko https://developer.mozilla.org/en-US/docs/Glossary/Gecko y des-afortunadamente no esta disponible en español.

Si estas interesado en contribuir, esta es una muy buena opción para hacerlo. :+1: 

si tienes dudas o quieres abundar en el tema no dudes en dejar comentarios o escribirnos en el [chat en español](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org)

saludos

**Comment by Graywolf9** [comment]
Hola! @federico-cloud, muchas gracias por tú interés! una disculpa por la demora. 

Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)

**Comment by Graywolf9** [comment]
Muchas gracias por el interés y una disculpa por las demoras en los mensajes @federico-cloud 

Me he tomado el tiempo de actualizar la página completa en https://github.com/mdn/translated-content/pull/12094, lo que debería solucionar cualquier error.
