### ISSUE TITLE
Page macro on Russian "Object" page

### ISSUE THREAD

**Issue by Temirsultanov** [mdn/translated-content#4889]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object

#### What information was incorrect, unhelpful, or incomplete?

[This section](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object#properties_of_object_instances) look like this: ![issue](https://user-images.githubusercontent.com/60009099/160661116-f4c62ff8-e368-4aae-be98-efa65d1f8443.png)

May be "page" function is not working, idk

It is not isolated incident. This error occurs on many pages

#### What did you expect to see?
I expect to see useful content, not double curly braces

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/javascript/reference/global_objects/object`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/global_objects/object/index.html
* Last commit: https://github.com/mdn/translated-content/commit/09d10136633355937867a21d65db64ae3c4d5829
* Document last modified: 2021-10-27T15:02:34.000Z

</details>

**Comment by cw118** [comment]
@Temirsultanov Thanks for reporting!This is also caused by #3892 since the `{{page}}` macro has been removed and should no longer be used.
