### ISSUE TITLE
::-webkit-scrollbar" iso

### ISSUE THREAD

**Issue by syellowbird** [mdn/translated-content#4898]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/::-webkit-scrollbar

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/css/_doublecolon_-webkit-scrollbar`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/::-webkit-scrollbar
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/_doublecolon_-webkit-scrollbar/index.html
* Last commit: https://github.com/mdn/translated-content/commit/6d3234e3f9ff37cbd766dc00c607828ad6f34a53
* Document last modified: 2021-07-28T16:32:33.000Z

</details>

**Comment by SphinxKnight** [comment]
@syellowbird could you please provide a bit more details about the issue you're facing?

**Comment by catlair** [comment]
could you please provide a bit more details about the issue you're facing? Or are you just saying the translation is incomplete?

是想说这个页面翻译不完全？
