### ISSUE TITLE
Перевод фразы "first-party cookie"

### ISSUE THREAD

**Issue by myshov** [mdn/translated-content#4914]
В статье https://developer.mozilla.org/ru/docs/Web/HTTP/Cookies first-party cookie переводятся как "куки первого лица". Думаю, что этот перевод стоит заменить, например, на "собственные куки". Тем более что "куки первого лица" судя по запросу в гугл используется только на 9 страницах, а "собственные куки" на 7100.

@sashasushko @lex111 @mdn/yari-content-ru если нет возражений, то в ближайшие дни поправлю страницу

Связано с https://github.com/web-standards-ru/dictionary/pull/452

**Comment by sashasushko** [comment]
Мне нравится
