### ISSUE TITLE
On the problem of absolute positioning in Chinese translation 

### ISSUE THREAD

**Issue by zhangfanhang** [mdn/translated-content#4940]
## What page(s) did you find the problem on?

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/CSS_layout/Positioning

## Specific page section or heading?

 [固定定位](https://developer.mozilla.org/zh-CN/docs/Learn/CSS/CSS_layout/Positioning#fixed_positioning)
[Fixed positioning](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Positioning#fixed_positioning)

## What is the problem?

Absolute elements in Chinese documents fix elements relative to HTML elements.....But in the English document,
whereas absolute positioning fixes an element in place relative to its nearest positioned ancestor (the initial containing block if there isn't one),  

## What did you expect to see?

只有一个主要区别：绝对定位固定元素是相对于html元素或其最近的定位祖先，

修改为

只有一个主要区别：绝对定位固定元素是相对于初始包含块或其最近的定位祖先，

**Comment by UESTCzhouyuchuan** [comment]
I think @zhangfanhang  is right .the initial containing block is the containing block of html element. see [containg_block](https://developer.mozilla.org/en-US/docs/Web/CSS/Containing_block).
