### ISSUE TITLE
Missing Korean translation of 'learn/javascript/asynchronous' 

### ISSUE THREAD

**Issue by yechoi42** [mdn/translated-content#4948]
## What page(s) did you find the problem on?
[files/ko/learn/javascript/asynchronous/index.md] 파일이 번역되어 있지 않습니다. 
[해당 커밋](https://github.com/mdn/translated-content/commit/965063d495573ba7265743c0ad2d5d832b9cc59d)에서 한국어 대신  영어 MD 파일로 추가되었습니다.

## Specific page section or heading?
files/ko/learn/javascript/asynchronous/index.md

## What is the problem?
missing korean translation

**Comment by SnowMarble** [comment]
해당 파일은 번역이 완료된것으로 확인됐습니다. 이슈 닫아주세요:)
