### ISSUE TITLE
Issue with "CSS": (short summary here please)

### ISSUE THREAD

**Issue by Henderv** [mdn/translated-content#4964]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/web/css`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/CSS
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/css/index.html
* Last commit: https://github.com/mdn/translated-content/commit/204e7e0715f84e849140b19b88e8a81d95f44548
* Document last modified: 2021-06-26T14:33:02.000Z

</details>

**Comment by cw118** [comment]
@Henderv Could you please provide more details on the issue(s) you're facing?
