### ISSUE TITLE
Content bug: EventTarget.addEventListener() missing some information

### ISSUE THREAD

**Issue by yusixian** [mdn/translated-content#4975]
## What page(s) did you find the problem on?
[EventTarget.addEventListener()](https://developer.mozilla.org/zh-CN/docs/Web/API/EventTarget/addEventListener#%E5%A4%87%E6%B3%A8)
## Specific page section or heading?
- [Other notes](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#other_notes)

## What is the problem?
missing some information
![image](https://user-images.githubusercontent.com/43498495/161544594-09cfa28d-b40e-4c86-bb7d-8b7fd4c3f9e9.png)

## What did you expect to see?
Complete translation

**Comment by UESTCzhouyuchuan** [comment]
英文版需要社区慢慢同步过来，同学有时间也可以试试翻译一下。
Everyone participating in this project is expected to follow our [Code of Conduct](https://github.com/mdn/translated-content/blob/main/CODE_OF_CONDUCT.md).

**Comment by codenotkey** [comment]
我可以尝试做一些翻译
