### ISSUE TITLE
"Коды ответа HTTP" landing page doesn't link to 451 page

### ISSUE THREAD

**Issue by gamlielfishkin** [mdn/translated-content#4999]
MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Status

#### What information was incorrect, unhelpful, or incomplete?
Not said about 451.

#### Specific section or headline?
Клиентские

#### What did you expect to see?
"451 Unavailable For Legal Reasons", with its description and a link to https://developer.mozilla.org/ru/docs/Web/HTTP/Status/451.

#### Did you test this? If so, how?
Sorry, I know about git-sites (like MDN), but not learned how to edit them.

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/http/status`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Status
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/http/status/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a3d3f72729edf1ff829150bf7ddccfbc0a70497d
* Document last modified: 2021-07-27T06:54:07.000Z

</details>

**Comment by myshov** [comment]
На странице не хватает ещё кодов, да и страница в целом устарела, её нужно привести к тому виду, в котором она находится в англоязычном mdn. Буду работать над этим issue на следующей неделе!

**Comment by sashasushko** [comment]
Я добавил ярлык "отличная задача для начала". Буду рад, если кто-то возьмётся за неё.

Что нужно сделать:
- взять [англоязычную статью](https://github.com/mdn/content/blob/main/files/en-us/web/http/status/index.md) за источник
- перенести туда текущий перевод тех частей, которые соответствуют английскому оригиналу
- доперевести недостающие части

---

I've added the label "good first issue". I would be glad if someone would take it on.

What needs to be done:
- take the [English article](https://github.com/mdn/content/blob/main/files/en-us/web/http/status/index.md)
- Transfer there the current translation of the parts that correspond to the English original
- translate the missing parts

---

Может быть вы сами, @gamlielfishkin, готовы?

**Comment by leon-win** [comment]
Done in #16807
