### ISSUE TITLE
Issue with "Объединённый асинхронный JavaScript: Таймауты и ин…": broken links

### ISSUE THREAD

**Issue by nen54** [mdn/translated-content#5007]
MDN URL: https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous

#### What information was incorrect, unhelpful, or incomplete?
some of links with practice tasks or examples of said tasks lead to pages that don't exist,so it's hard to do these tasks(especially the latest and biggest one - the reaction game)

#### Specific section or headline?
almost all of the links for the practice 

#### What did you expect to see?
Set-up code and examples of completed tasks 

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/conflicting/learn/javascript/asynchronous`
* MDN URL: https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/conflicting/learn/javascript/asynchronous/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d53bae971e455859229bcb3246e29bcbc85179d2
* Document last modified: 2022-03-08T00:12:08.000Z

</details>

**Comment by sashasushko** [comment]
This page will be deleted in the new section structure. Thanks, @nen54, for report!
