### ISSUE TITLE
Issue with "合作异步JavaScript: 超时和间隔": (links fail)

### ISSUE THREAD

**Issue by chensj-sj** [mdn/translated-content#5018]
MDN URL: https://developer.mozilla.org/zh-CN/docs/conflicting/Learn/JavaScript/Asynchronous_ae5a561b0ec11fc53c167201aa8af5df

#### What information was incorrect, unhelpful, or incomplete?

Many active learning links fail

#### Specific section or headline?
Active learning: reaction game

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/conflicting/learn/javascript/asynchronous_ae5a561b0ec11fc53c167201aa8af5df`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/conflicting/Learn/JavaScript/Asynchronous_ae5a561b0ec11fc53c167201aa8af5df
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/conflicting/learn/javascript/asynchronous_ae5a561b0ec11fc53c167201aa8af5df/index.html
* Last commit: https://github.com/mdn/translated-content/commit/8824afb494e5398bc0efcf5f7eb78782096fc90c
* Document last modified: 2022-03-18T13:53:46.000Z

</details>很多主动学习的链接失效

#### Did you test this? If so, how?

<details>
<summary>MDage report details</summary>

* Folder: `zh-cn/conflicting/learn/javascript/asynchronous_ae5a561b0ec11fc53c167201aa8af5df`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/conflicting/Learn/JavaScript/Asynchronous_ae5a561b0ec11fc53c167201aa8af5df
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/conflicting/learn/javascript/asynchronous_ae5a561b0ec11fc53c167201aa8af5df/index.html
* Last commit: https://github.com/mdn/translated-content/commit/8824afb494e5398bc0efcf5f7eb78782096fc90c
* Document last modified: 2022-03-18T13:53:46.000Z

</details>

**Comment by yin1999** [comment]
This document has been removed from [mdncontent](https://github.com/mdn/translated-content) via commit: https://github.com/mdn/content/commit/7cf00aff32962e6135132531d699f4d21667f376 

In `en-US`, the URI `Learn/JavaScript/Asynchronous/Timeouts_and_intervals` has been redirected to `Learn/JavaScript/Asynchronous`. but in `pt-BR`, `ru`, `zh-CN`, `zh-TW`, `fr`, the URI has been redirect to `conflicting/Learn/JavaScript/Asynchronous_ae5a561b0ec11fc53c167201aa8af5df`. It seems ok in `ko`.

@cw118 should we deal with this difference ?

**Comment by cw118** [comment]
Thanks for letting us know @yin1999. You're definitely more than welcome to at least fix this particular conflicting page in `zh-CN/TW`. 

That being said, each locale tends to deal with conflicting files differently in my experience so I'm not sure about the rest of the locales; for example, l10n-fr doesn't really consider it a priority but we are currently working on taking care of `conflicting` and will fix this on our end soon.

**Comment by yin1999** [comment]
@irvin Is it ok to resolve with the redirects I have made in #5024

**Comment by irvin** [comment]
> @irvin Is it ok to resolve with the redirects I have made in #5024

please un-draft that PR, thanks

**Comment by yin1999** [comment]
@irvin ready for merge

**Comment by irvin** [comment]
@yin1999 can you also remove this conflict file and set a redirect from it to the correct version?  (try https://github.com/mdn/content#deleting-a-document )

https://developer.mozilla.org/zh-CN/docs/conflicting/Learn/JavaScript/Asynchronous_ae5a561b0ec11fc53c167201aa8af5df

**Comment by yin1999** [comment]
> > @irvin Is it ok to resolve with the redirects I have made in #5024
> 
> @yin1999 please un-draft that PR once you are ready, thanks

Done in 05f8d31a914193c65cbe501fc6edb1db7f29ae05

**Comment by irvin** [comment]
@yin1999 i think we can also remove /zh-CN/docs/conflicting/Learn/JavaScript/Asynchronous and redirect to /zh-CN/docs/Learn/JavaScript/Asynchronous

**Comment by yin1999** [comment]
Hi @irvin if we need to remove `/zh-CN/docs/conflicting/Learn/JavaScript/Asynchronous`, the other two documents should also be removed (or it cannot be processed):

- `conflicting/Learn/JavaScript/Asynchronous/Promises`
- `conflicting/Learn/JavaScript/Asynchronous/Introducing`

If you think it's ok, I'll remove those three documents.

**Comment by irvin** [comment]
> Hi @irvin if we need to remove `/zh-CN/docs/conflicting/Learn/JavaScript/Asynchronous`, the other two documents should also be removed (or it cannot be processed):
> 
> * `conflicting/Learn/JavaScript/Asynchronous/Promises`
> * `conflicting/Learn/JavaScript/Asynchronous/Introducing`
> 
> If you think it's ok, I'll remove those three documents.

sure

**Comment by yin1999** [comment]
It seems that google and other crawler will not index the documents in `conflicting`, maybe it's ok for us to just resolve those documents which has been redirected to `conflicting`. (sitemap of mdn: <https://developer.mozilla.org/sitemap.xml>, it has been include in [robots.txt](https://developer.mozilla.org/robots.txt))

And I have searched on google for the conflict documents, it seems that the documents are not visiable for google:

![image](https://user-images.githubusercontent.com/15844309/162382514-42fb26b1-848e-4174-b3a9-f918fedc9ec6.png)

@irvin Any idea?

**Comment by yin1999** [comment]
I've push the commit 41717be4b1327857218652323d177a20612999f2 to deal with removing conflict documents in `Learn/JavaScript/Asynchronous`.
