### ISSUE TITLE
Issue with "基本的光线投射": broken link on this page

### ISSUE THREAD

**Issue by Guleixibian2009** [mdn/translated-content#5089]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/A_basic_ray-caster#see also

#### What information was incorrect, unhelpful, or incomplete?
There are two broken links on this page.

#### Specific section or headline?
#See also.
[使用canvas绘图](https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/cn/Drawing_Graphics_with_Canvas)
[Canvas 教程](https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/cn/Canvas_tutorial)

#### What did you expect to see?
Um... Correct those links?

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/canvas_api/a_basic_ray-caster`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Canvas_API/A_basic_ray-caster
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/canvas_api/a_basic_ray-caster/index.html
* Last commit: https://github.com/mdn/translated-content/commit/8abd3787ac26bef69bd479ed4f79164a94f2174b
* Document last modified: 2022-03-22T04:47:58.000Z

</details>

**Comment by Guleixibian2009** [comment]
And why is it different from the en-US page? There's only one link on that page.

**Comment by yin1999** [comment]
This document is out of date.

**Comment by Guleixibian2009** [comment]
👍 Got it!
