### ISSUE TITLE
Issue with "Array.prototype.reduce()": Parêntese extra no fechamento da função reduce

### ISSUE THREAD

**Issue by gabe-sr** [mdn/translated-content#5120]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

#### What information was incorrect, unhelpful, or incomplete?
Erro de digitação na declaração da sintaxe de reduce, um fechamento de parênteses à mais.

#### Specific section or headline?
https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce#syntax

#### What did you expect to see?
Somente reduce e callback abrem parênteses, portanto dois fechamentos são necessários. 

`array.reduce(callback( acumulador, valorAtual[, index[, array]] )[, valorInicial])`

#### Did you test this? If so, how?
Indo a mesma seção traduzida em inglês, varias outras formas de declaração de reduce estão presentes, nenhuma na mesma formatação. Porém, os exemplos com callback indicam que somente este elemento necessitaria a abertura de outro grupo de parênteses.

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/javascript/reference/global_objects/array/reduce`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/javascript/reference/global_objects/array/reduce/index.html
* Last commit: https://github.com/mdn/translated-content/commit/48fcf3882f92f1120fc5f35abbd51b31327d3846
* Document last modified: 2022-04-09T01:09:53.000Z

</details>

**Comment by josielrocha** [comment]
Done!
