### ISSUE TITLE
mail

### ISSUE THREAD

**Issue by Lawrise** [mdn/translated-content#5142]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/Common_questions/Using_Github_pages

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/common_questions/using_github_pages`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/Common_questions/Using_Github_pages
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/common_questions/using_github_pages/index.md
* Last commit: https://github.com/mdn/translated-content/commit/500f444d23a7a758da229ebe6b9691cc5d4fe731
* Document last modified: 2022-03-16T16:52:18.000Z

</details>

**Comment by cw118** [comment]
Hi @Lawrise, could you please provide details on the issue(s) you're facing on this MDN page?

**Comment by cw118** [comment]
Closing since no information was provided, but we can reopen if needed and if more details are given.
