### ISSUE TITLE
Remove deprecated {{h3_gecko_minversion}} macro

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#5145]
The `{{h3_gecko_minversion}}` macro is/will be deprecated with mdn/yari#5995 and should be removed from `translated-content`.

The macro may have to be replaced by a title (e.g. `{{h3_gecko_minversion("Timers", "10.0")}}` -> `### Timers`), some can just be deleted. When doing this for `fr`, I just compared with the en-US files to see how to remove the macro "properly".

**Comment by yin1999** [comment]
I'll update the `zh-CN` document (found one place only).

**Comment by alattalatta** [comment]
`ko` was handled by #5164.

**Comment by yin1999** [comment]
`l10n-zh` is resolved by #5206 and #5207

**Comment by SphinxKnight** [comment]
cross-referencing https://github.com/mdn/mdn-community/discussions/53 here

**Comment by Graywolf9** [comment]
`es` handled in #5330

**Comment by italogois** [comment]
`pt-br` solved in issue https://github.com/mdn/translated-content/pull/5385

**Comment by SphinxKnight** [comment]
Forwarding https://github.com/mdn/mdn-community/discussions/53#discussioncomment-2745971 here regarding `ja` with:
- #5627
- #5629

**Comment by SphinxKnight** [comment]
There are also two files for inactive locales: 1 for `de` and 1 for `pl`, I took care of it #5642
