### ISSUE TITLE
Issue with "clip-path": (short summary here please)

### ISSUE THREAD

**Issue by KiKiKi1258** [mdn/translated-content#5175]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/clip-path

#### What information was incorrect, unhelpful, or incomplete?

The path attribute of clip path does not take effect
#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/clip-path`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/clip-path
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/clip-path/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a02f4b2f60c81e09b318a090e5c9c2d2d641c878
* Document last modified: 2021-07-19T15:04:27.000Z

</details>

**Comment by cw118** [comment]
Hi @KiKiKi1258, thanks for reporting. Could you please provide more details on which part of this MDN page has an issue (e.g. a live sample, an interactive example, a code snippet, etc.) ?

**Comment by yin1999** [comment]
adding css `basic-shape` list in #5454.
