### ISSUE TITLE
MDN 콘텐츠 번역 프로젝트에 여러분을 초대합니다. / Call to action: Help us maintain MDN's Korean content

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#519]
여러분의 도움이 필요합니다.
여러 MDN 지역이 비동결 상태로 MDN 컨텐츠에 많은 기여자들이 참여하고 있습니다.
하지만, 한국 지역은 현재 동결 상태로 한국 컨텐츠에 대해 어떠한 기여도 받을 수 없는 상태입니다.
많은 웹 플랫폼 문서를 보길 원하는 사람들이 MDN을 기반으로 공부합니다. 좋은 품질을 유지할 수 있게 도움이 필요합니다.

## 프로젝트에 참여하려면 무엇이 필요한가요?
우리는 한국 지역 콘텐츠에 적극적으로 참여할 자원 봉사자를 찾고 있습니다. 다음과 같은 책임이 따릅니다.

- [MDN ko 콘텐츠](https://github.com/mdn/translated-content/tree/main/files/ko)에 대해 제출 된 풀 요청에 대한 리뷰 공유.
- MDN ko 콘텐츠에 대해 제기 된 콘텐츠 버그 문제를 수정.

ko 페이지가 변경 될 때 en-US 페이지와 동기화되도록 유지하고 관심이있는 경우 새 ko 번역을 만드는 것과 같은 다른 작업도 있을 수 있습니다. 편안하게 처리 할 수있는 모든 작업에 주당 몇 시간을 할애해야합니다.

## 프로젝트에 참여하는 방법은 무엇입니까?
의견을 남겨주세요. 

---
This is a call for help. 
Many MDN locales are already unfrozen, and many contributors are participating in MDN content.
However, the Korean region is currently frozen and cannot receive any contribution for Korean content.
A lot of people who want to view a lot of web platform documents study based on MDN. We need help to keep it of good quality.

## What would this involve?
We want you to join a ko-locale active maintenance volunteer team. Your responsibilities would involve:

- Doing a share of reviews on pull requests filed against the [MDN ko content](https://github.com/mdn/translated-content/tree/main/files/ko).
- Doing a share of fixing content bug issues filed against the MDN ko content.

There also may be other tasks that come up, such as keeping ko pages in sync with en-US pages when they change, and creating new ko translations if you are interested. We would expect you to devote a few hours per week to these tasks — whatever you are able to handle comfortably.

## How do I get involved?
Please leave a comment.

**Comment by cos18** [comment]
Hello @hochan222 
I want to contribute MDN translate project!

**Comment by GwangYeol-Im** [comment]
참여 희망합니다 :) 평소 MDN 문서 보면서 많은 도움 얻었는데, 이번 기회를 통해 개발 공부하시는 분들을 위해 기여해보고 싶습니다 !

**Comment by nKiNk** [comment]
Hi @hochan222 
I would like to take a part in this wonderful project.

**Comment by pje1740** [comment]
As a web developer, it would be great if I could take part in MDN related project :)
@hochan222 Thank you so much for organizing this by the way!

**Comment by yechoi42** [comment]
참여를 희망합니다.

**Comment by hochan222** [comment]
@cos18 @GwangYeol-Im @nKiNk @pje1740 @yechoi42 Thank you for your interest in helping with this!

To lift the freeze, we followed the same procedure as in Russia. https://github.com/mdn/translated-content/issues/117

Do you have any questions about the tasks? Before joining, we have some time to think about.

**Comment by yujo11** [comment]
참여 희망합니다! 

MDN문서를 매일 보고 있는데 기여할 수 있는 방법을 제시해주셔서 감사합니다 @hochan222 👍👍

**Comment by hochan222** [comment]
@yujo11 좋아용! 같이 조금씩 기여해요!

**Comment by hochan222** [comment]
@SphinxKnight  Do you have any idea how to create a @yari-content-ko team?

**Comment by SphinxKnight** [comment]
@hochan222 I think this is something @chrisdavidmills can help with. And overall, give feedback about this.

**Comment by chrisdavidmills** [comment]
Hi @hochan222 ! Awesome progress here!

I'll create the team for you, and set it up in the codeowners file. You need to be an admin to do that. Thanks for all your help in the other tasks though, I really appreciate it.

We'll use this issue as a tracking issue for everything else that needs to be done, and close it when all the set up tasks are complete.

**Comment by chrisdavidmills** [comment]
Update — I've filed a PR to active the `ko` locale on yari: https://github.com/mdn/yari/pull/3581

This is needed before any changes can be made.

**Comment by chrisdavidmills** [comment]
Update; https://github.com/mdn/translated-content/pull/605 merged, so the `ko` team is now added to the readme!

**Comment by chrisdavidmills** [comment]
Update: check done, and the `l10n-ko` label already exists, so we are OK there.

**Comment by chrisdavidmills** [comment]
Update: [yari-content-ko](https://github.com/orgs/mdn/teams/yari-content-ko) team set up; all team members invited to team and given write access to repo so they can merge PRs from other members.

**Comment by chrisdavidmills** [comment]
Update: PR filed to add `yari-content-ko` team to CODEOWNERS file: https://github.com/mdn/translated-content/pull/610. This will cause the team to start getting PR reviews automatically assigned.

**Comment by chrisdavidmills** [comment]
Update: https://github.com/mdn/content/pull/4323 merged, so now the `ko` team will show up on the https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize page.

(Note: MDN content updates can take a day or so to show up...)

**Comment by chrisdavidmills** [comment]
STATUS: Very nearly ready to go!

STILL TO DO:

1. Wait for the above pending PRs to be merged.
2. Once they are merged, update the `yari-content-ko` team settings so that they are the same as the other teams (e.g. only assigned reviewers see their review requests; everyone does not have to see everything!)
3. *Optional*: If you wish, you can set up a ko-specific guidelines page under https://github.com/mdn/translated-content/tree/main/docs, and use it to store any specific guidelinesyou want you team to stick to.

**Comment by hochan222** [comment]
@SphinxKnight Thank you for caring us.

**Comment by hochan222** [comment]
@chrisdavidmills Are you having a good time this week? Thank you for making a good starting point. We hope that our small changes will contribute to MDN. :)

**Comment by hochan222** [comment]
@cos18 @yechoi42 @GwangYeol-Im @nKiNk @pje1740 @yujo11 
오픈톡방 들어와 주세요! https://open.kakao.com/o/gdfG288c

**Comment by chrisdavidmills** [comment]
@hochan222 I am having a good week thank you; hope you are too. I'm really enjoying helping you set up the team!

As an update, I've updated the team code review assignment settings, as mentioned above. The set up is complete from my point of view.

Is there anything else you think needs attention at this stage?

**Comment by hochan222** [comment]
@chrisdavidmills There seems to be no present. It seems that we will need time to make a plan for the future after we have had enough talks with each other. If we think about it in the future and do not know, is it okay to ask questions?

Other frozen issues mentioned above have been noted in the yari-team discussion. We plan to resolve it after discussion.

Thank you.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills There seems to be no present. It seems that we will need time to make a plan for the future after we have had enough talks with each other. If we think about it in the future and do not know, is it okay to ask questions?
> 
> Other frozen issues mentioned above have been noted in the yari-team discussion. We plan to resolve it after discussion.
> 
> Thank you.

Yes, it's fine to ask questions! I'm going to close this one for now, but you can ask questions in new issues, on the MDN Web Docs Matrix room, or in new issues.
