### ISSUE TITLE
Remove deprecated {{Interface}} macro

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#5193]
The `{{Interface}}` macro has been removed from mdn/content and is (being) deprecated (cf. mdn/yari#6011), so it should be removed from translated-content as well.

If I understood correctly, the macro can be replaced by its argument with code formatting (e.g. `{{Interface("nsIDOMElement")}}` becomes `nsIDOMElement`).

For the fr locale, I used find/replace regexp in VS Code:
- search `\{\{[ ]?interface[ ]?\(["'](\S*)(["'][ ]?\))[ ]?\}\}`
- for `.md` files (be careful with macros in HTML tables, I did a quick manual check for this): replace by <code>\`$1\`</code>
- for `.html` files: replace by `<code>$1</code>`

**Comment by yin1999** [comment]
`l10n-zh` done via #5197 and #5198.

**Comment by SphinxKnight** [comment]
`l10n-fr` taken care of in #5194 by @cw118: thanks!

**Comment by Graywolf9** [comment]
`es` ready thanks to @yin1999 !

**Comment by cw118** [comment]
l10n-ru taken care of in #5398 🎉

**Comment by cw118** [comment]
l10n-pt-br taken care of by #5225

**Comment by cw118** [comment]
l10n-ja taken care of by #5452

**Comment by cw118** [comment]
`de` and `pl` taken care of by #5651
