### ISSUE TITLE
Issue with "Первичные данные": Неудачный перевод | Not the best translation

### ISSUE THREAD

**Issue by dekhanov** [mdn/translated-content#5204]
MDN URL: https://developer.mozilla.org/ru/docs/Glossary/Origin

#### What information was incorrect, unhelpful, or incomplete?
Неудачный перевод термина "origin" как "Первичные данные"

#### What did you expect to see?
Стоило бы перевести как "Источник", как в статье о [same-origin policy](https://developer.mozilla.org/ru/docs/web/security/same-origin_policy)

<details>
<summary>Page report details</summary>

* Folder: `ru/glossary/origin`
* MDN URL: https://developer.mozilla.org/ru/docs/Glossary/Origin
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/glossary/origin/index.html
* Last commit: https://github.com/mdn/translated-content/commit/e2bc9a12a68bd713a2a49de5315649b9d660e54a
* Document last modified: 2021-05-13T17:05:41.000Z

</details>

**Comment by Phizick** [comment]
Исправил

**Comment by cw118** [comment]
Hi @Phizick, thank you for working on this issue! Could you please [create a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) to propose making your changes to this repository (`mdn/translated-content`)?

**Comment by Phizick** [comment]
yep, sure

**Comment by sashasushko** [comment]
https://github.com/mdn/translated-content/pull/11502

**Comment by leon-win** [comment]
Fixed on the third try in #17423 =))

Thanks to all! :+1:
