### ISSUE TITLE
Issue with "Gramática y Tipos": (misnamed variable in an educational example)

### ISSUE THREAD

**Issue by lucalquemist** [mdn/translated-content#5231]
MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Grammar_and_types

#### What information was incorrect, unhelpful, or incomplete?
in this example: 
(function() {
  console.log(myVar); // undefined
  var myvar = 'valor local';
})();

#### Specific section or headline?
[Elevación de variables (hoisting)](https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Grammar_and_types#elevaci%C3%B3n_de_variables_hoisting)

#### What did you expect to see?
I expected the example to work correctly, the variable has a misspelling: it is defined as "myvar" but is called as "myVar"

#### Did you test this? If so, how?
I corrected the name in the console and it worked correctly, it returned "undefined"

<details>
<summary>Page report details</summary>

* Folder: `es/web/javascript/guide/grammar_and_types`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Grammar_and_types
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/guide/grammar_and_types/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1109132f09d75da9a28b649c7677bb6ce07c40c0
* Document last modified: 2020-12-08T19:41:45.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! @lucalquemist muchas gracias por tu tiempo y apoyo.

Si interpreto bien el ejemplo y el comentario `// devolverá un valor de undefined` esto sería intencional para que no encuentre la variable y pueda devolver `undefined`.

Haznos saber cualquier duda o comentario para dar el seguimiento.

Saludos.

**Comment by marcelozarate** [comment]
Buenos días. Intercedo en esta ocasión, creo que la sugerencia es válida, más allá de que el output es el mismo (undefined) lo que intenta reflejar el ejemplo es respecto del hoisting, con lo cual sí, la variable debería ser myvar en lugar myVar. ¿Puedes crear una issue de esas que sueles hacer @Graywolf9 y así me asigno para traducir el documento completo y de paso solucionar esto?

**Comment by Graywolf9** [comment]
Hola! Muchas gracias por la observación @marcelozarate estas en lo correcto por lo que también la observación inicial de @lucalquemist, muchas gracias a ambos, una disculpa por la demora, pero puedes hacer libremente el PR para actualizar el artículo.

Respecto a este issue:
Fixed in #9909
