### ISSUE TITLE
Issue with es "eval" page: minor typo

### ISSUE THREAD

**Issue by icriscarr** [mdn/translated-content#5271]
MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/eval

#### What information was incorrect, unhelpful, or incomplete?
con una cadena de **carcteres** que podría ser afectada por un

#### Specific section or headline?
#no_utilice_eval_innecesariamente

#### What did you expect to see?

caracteres

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/eval`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/eval
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/eval/index.html
* Last commit: https://github.com/mdn/translated-content/commit/0ce7202a706c9036eeea42c158f433c2b7940457
* Document last modified: 2022-03-03T13:36:23.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! @icriscarr muchas gracias por reportar el error, ¿te animas a corregirlo? Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)
