### ISSUE TITLE
Issue with "POST": (short summary here please)

### ISSUE THREAD

**Issue by changsooleefarm** [mdn/translated-content#5295]
MDN URL: https://developer.mozilla.org/ja/docs/Web/HTTP/Methods/POST

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ja/web/http/methods/post`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/HTTP/Methods/POST
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/http/methods/post/index.html
* Last commit: https://github.com/mdn/translated-content/commit/eb070febe7d67ec636dcec561996e41a9531c712
* Document last modified: 2021-07-03T15:20:35.000Z

</details>

**Comment by SphinxKnight** [comment]
@changsooleefarm please provide more details about the issue you're facing. Without them, there's little we can do to help. In the meantime, I'm closing this issue.
