### ISSUE TITLE
Remove `h3_gecko_minversion` in `es` locale

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#5328]
Remove `h3_gecko_minversion` macro in `es` locale and update content/format for:

- [x] #6439
  - [x]  Remover macro
- [x] #6440
  - [x]  Remover macro
- [x] #6441
  - [x]  Remover macro
- [x] #6442
  - [x]  Remover macro
  - [x] Actualizar contenido
  - [x] Convertir a `md`

**Comment by Graywolf9** [comment]
Macro removed in #5330. Still pending update content and format

**Comment by yin1999** [comment]
Hi @Graywolf9, I think this issue has been resolved :)

**Comment by Graywolf9** [comment]
Closed to open a further issue with the outdates content
