### ISSUE TITLE
Issue with "keyup": don't show navigation and layout broken

### ISSUE THREAD

**Issue by italogois** [mdn/translated-content#5342]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/API/Document/keyup_event

#### What information was incorrect, unhelpful, or incomplete?
Don't show the side navigation and informações gerais is broke

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/api/document/keyup_event`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/API/Document/keyup_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/api/document/keyup_event/index.html
* Last commit: https://github.com/mdn/translated-content/commit/10d816ddd724a6a6765c2cc5951cc373d04fafa1
* Document last modified: 2022-04-09T01:18:42.000Z

</details>

**Comment by josielrocha** [comment]
Thank you @italogois!

🚀
