### ISSUE TITLE
Issue with "Math": incorrect description of math.pow

### ISSUE THREAD

**Issue by DaSh-More** [mdn/translated-content#5355]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math

description for `Math.pow(x, y)`: 

- on the page with all the methods not correct ([link](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math#math.powx_y)):

   Возвращает основание в степени _экспоненты_, то есть, значение выражения основание<sup>_экспонента_</sup>
   > _экспоненты_ Instead of _показатель_

- on the `pow` method page correct ([link](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/pow))
  Возвращает основание, возведённое в степень _показатель_, то есть, значение выражения основание<sup>_показатель_</sup>

---
<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/global_objects/math`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/global_objects/math/index.html
* Last commit: https://github.com/mdn/translated-content/commit/c08c48e16cb9e47c586925999362de104ecd710d
* Document last modified: 2021-10-29T17:34:32.000Z

</details>

**Comment by DaSh-More** [comment]
Is it possible to write in Russian or better in English?

**Comment by cw118** [comment]
Hi @DaSh-More, there is a `ru` translation team that specifically manages Russian content — they understand both Russian and English :)
