### ISSUE TITLE
Issue with "Set":  Interpolations not being resolved in spanish

### ISSUE THREAD

**Issue by vinjatovix** [mdn/translated-content#5358]
MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Set

#### What information was incorrect, unhelpful, or incomplete?
The interpolations are not being resolved correctly in "properties" and "methods" in Spanish

#### Specific section or headline?
["Properties" and "methods"](https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Set#instancias_set)

#### What did you expect to see?
All available set methods like .add, etc...

#### Did you test this? If so, how?
Chrome Versión 101.0.4951.41 (Build oficial) (64 bits)
Firefox 99.0 (64-bit)

<details>
<summary>Page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/set`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Set
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/set/index.html
* Last commit: https://github.com/mdn/translated-content/commit/325a9a16506132e984a82bbfce18f9220e81fbb0
* Document last modified: 2021-06-22T11:55:45.000Z

</details>

**Comment by Graywolf9** [comment]
Hola @vinjatovix! Parece que la página entera se acaba de actualizar en este PR: https://github.com/mdn/translated-content/pull/5803

Comenta si aún persiste este error o cualquier duda con confianza.

Saludos.

**Comment by Graywolf9** [comment]
Fixed in #5803
