### ISSUE TITLE
Issue with "prefers-contrast": wrong value `high` instead of `more`

### ISSUE THREAD

**Issue by skjnldsv** [mdn/translated-content#5364]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-contrast
W3C URL: https://docs.w3cub.com/css/@media/prefers-contrast

#### What information was incorrect, unhelpful, or incomplete?
French version displays `high` instead of `more`

#### Specific section or headline?
https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-contrast#syntaxe

#### What did you expect to see?
`more`

#### Did you test this? If so, how?
No

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/@media/prefers-contrast`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-contrast
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/@media/prefers-contrast/index.md
* Last commit: https://github.com/mdn/translated-content/commit/500f444d23a7a758da229ebe6b9691cc5d4fe731
* Document last modified: 2022-03-16T16:52:18.000Z

</details>

**Comment by SphinxKnight** [comment]
Thanks for the detailed report @skjnldsv, will fix this :)

**Comment by skjnldsv** [comment]
Thank you :)
Have a great day!! :v:
