### ISSUE TITLE
Issue with "visibility": documentation seems wrong

### ISSUE THREAD

**Issue by g-vitrac** [mdn/translated-content#5389]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/visibility

#### What information was incorrect, unhelpful, or incomplete?

Flex content with visibility: collapse are not visible but the space used by the element isn't freed for other elements. However the french documentation states it i don't know for the other language.

#### Specific section or headline?

Description of collapse property

#### What did you expect to see?

Remove the specification that states that the space will be freed while using flex content.

#### Did you test this? If so, how?

tested on code pen, by modyfing this page ansd by crossing this information with the documentation about the visibility property on W3c : https://www.w3schools.com/cssref/pr_class_visibility.asp

edit : https://codepen.io/g-vitrac/pen/oNEgdWa
A link to a code pen showing the difference between the two behaviour.
Checked the us documentation and it seems that there is a mistakes aswell for the same content

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/visibility`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/visibility
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/visibility/index.md
* Last commit: https://github.com/mdn/translated-content/commit/258ba7b4be62d8640477a3bd3146d08b00cb70ec
* Document last modified: 2021-10-12T05:57:33.000Z

</details>

**Comment by SphinxKnight** [comment]
@g-vitrac the French version (should) follow the English version which is located at https://developer.mozilla.org/en-US/docs/Web/CSS/visibility

In the current state, the English doc states "Collapsed flex items and ruby annotations are hidden, and the space they would have occupied is removed." which, I think matches the French translation (modulo the absence of "ruby annotations").

There are also notes regarding compatibility / compliance for `collapse` under https://developer.mozilla.org/fr/docs/Web/CSS/visibility#notes and in the browser compatibility table.

N.B. W3Schools does not originate from W3C

**Comment by g-vitrac** [comment]
Did not see compatibility, that's on me thanks !
