### ISSUE TITLE
Issue with "HTML básico": Image showing how P tag works

### ISSUE THREAD

**Issue by JoaoVSBraz** [mdn/translated-content#5391]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/HTML_basics

#### What information was incorrect, unhelpful, or incomplete?

There is an error message on console at developer tools telling that the page has some config blocking the image. Apparently, this only occurs with the first image.

#### Specific section or headline?

https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/HTML_basics#anatomia_de_um_elemento_html

#### What did you expect to see?

An image showing how P tag works

#### Did you test this? If so, how?

Microsoft Edge Versão 101.0.1210.32 (Compilação oficial) (64 bits)
![ms-edge-error](https://user-images.githubusercontent.com/32749482/166470809-3430c736-8fd4-49e7-acc4-6f40d7fc6243.png)

Firefox Versão 100.0 (64-bits)
![firefox-error](https://user-images.githubusercontent.com/32749482/166470940-583df44a-9063-4bd7-bcf8-5b3612e466a8.png)

Google Chrome 101.0.4951.41

<details>
<summary>Page report details</summary>

* Folder: `pt-br/learn/getting_started_with_the_web/html_basics`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/HTML_basics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/getting_started_with_the_web/html_basics/index.html
* Last commit: https://github.com/mdn/translated-content/commit/da778d8d0a9e9622c6a7fba6d1f9fb7d3ebf4a04
* Document last modified: 2021-08-19T13:37:01.000Z

</details>

**Comment by JoaoVSBraz** [comment]
It looks like other resources are being affected. Like the `image `with the `src` equals to "https://i.imgur.com/35Rirpx.png".

The image below can be helpful to fix this.
![devtools-error-fix-sugestion](https://user-images.githubusercontent.com/32749482/166474710-4c224dbf-6623-4931-84fe-664c8d530f68.png)

**Comment by italogois** [comment]
Thank you for this issue, this is a PR https://github.com/mdn/translated-content/pull/5423 for fix this
