### ISSUE TITLE
Issue with "Referencia de Elementos HTML": Error ortográfico

### ISSUE THREAD

**Issue by yadulgonzalez** [mdn/translated-content#5395]
MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Element

#### What information was incorrect, unhelpful, or incomplete?
La palabra castellana etiquéta es incorrecta

#### Specific section or headline?
[Seccionamiento del contenido](https://developer.mozilla.org/es/docs/Web/HTML/Element#seccionamiento_del_contenido)
<section>
Es, por lo tanto, una etiquéta semántica.

#### What did you expect to see?
Es, por lo tanto, una etiqueta semántica.

#### Did you test this? If so, how?
No se requiere

<details>
<summary>Page report details</summary>

* Folder: `es/web/html/element`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Element
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/html/element/index.html
* Last commit: https://github.com/mdn/translated-content/commit/2318b37e3fd17a3e76a29b9be7d1ce82f040c3bb
* Document last modified: 2021-02-11T17:20:58.000Z

</details>

**Comment by bpires** [comment]
Hi @cw118! I believe this issue was wrongly labelled [l10n-pt-br]. In fact, the content covered is in Spanish and not in Portuguese. Thus, it should receive the label [l10n-es].

**Comment by cw118** [comment]
Yes, thank you @bpires. I've changed the label :)

**Comment by Graywolf9** [comment]
Thank you for redirect @bpires
