### ISSUE TITLE
Issue with "s": (short summary here please)

### ISSUE THREAD

**Issue by N-TWD** [mdn/translated-content#5462]
MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Element/s

#### What information was incorrect, unhelpful, or incomplete?
Es una excelente etiqueta o elemento. Sin embargo, más que para 'destacar' una palabra o una frace, se debe emplear como una aclaración al usuario de el poque se elimina la palbra o frace tachada y se reemplaza por otra más actual o simplemente más apropiada. Thanks! 

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/web/html/element/s`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Element/s
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/html/element/s/index.html
* Last commit: https://github.com/mdn/translated-content/commit/2318b37e3fd17a3e76a29b9be7d1ce82f040c3bb
* Document last modified: 2021-02-11T17:20:58.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! @N-TWD muchas gracias por tu tiempo y ayuda, no me ha quedado muy claro cual es el motivo del issue, además del comentario sobre la etiqueta `<s>`

Cualquier cosa o duda puedes comentarnos.

Saludos.

Telegram: https://t.me/+Dr6qKQCAepw4MjFj
Matrix: https://chat.mozilla.org/#/room/#mdn-l10n-es:mozilla.org

**Comment by Graywolf9** [comment]
Hola! @N-TWD espero te encuentres muy bien, este PR será cerrado por falta de información, pero si tienes más dudas al respecto sientete libre de reabrirlo o abrir un nuevo issue.

Muchas gracias por tu tiempo
