### ISSUE TITLE
Issue with "animate": (Update embedded page)

### ISSUE THREAD

**Issue by zumuho** [mdn/translated-content#5477]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/SVG/Element/animate

#### What information was incorrect, unhelpful, or incomplete?
![LiveSampleFailed](https://user-images.githubusercontent.com/22559904/167258265-7574afb4-45b6-4bf1-b1bd-5a654f3f97e3.PNG)

#### What did you expect to see?
![animate](https://user-images.githubusercontent.com/22559904/167259591-316ff825-e04b-4c4f-92e1-1ca5e6a042ce.gif)

#### Did you test this? If so, how?
I recommend updating the html code of [svg example (zh-CN)](https://yari-demos.prod.mdn.mozit.cloud/zh-CN/docs/Web/SVG/Element/animate/_sample_.exemple.html) to the html code of [svg example (English)](https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/SVG/Element/animate/_sample_.example.html)

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/svg/element/animate`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/SVG/Element/animate
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/svg/element/animate/index.html
* Last commit: https://github.com/mdn/translated-content/commit/9a110dee28ae2ef12ee014b98fda6bae6ee48edb
* Document last modified: 2022-03-03T17:03:17.000Z

</details>

**Comment by yin1999** [comment]
That's because the `example` id does not exist in the document. I've created #5483 to fix this.
