### ISSUE TITLE
Issue with "try...catch": (A 'return' statement can only be used within a function body.)

### ISSUE THREAD

**Issue by grol-kun** [mdn/translated-content#5490]
MDN page: [try...catch](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/try...catch)

[Возвращение значения из блока finally]

## What is the problem?

Если блок finally возвращает какое-либо значение, оно становится значением, которое возвращает вся конструкция try...catch...finally, вне зависимости от любых инструкций return в блоках try и catch. Также игнорируются исключения, выброшенные блоком catch.

<details>
<summary>This block of code (found below the <a href="https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/try...catch#%D0%B2%D0%BE%D0%B7%D0%B2%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B7%D0%BD%D0%B0%D1%87%D0%B5%D0%BD%D0%B8%D1%8F_%D0%B8%D0%B7_%D0%B1%D0%BB%D0%BE%D0%BA%D0%B0_finally">Возвращение значения из блока finally</a> title):</summary>
<br>

```js
try {
  try {
    throw new Error('упс');
  }
  catch (e) {
    console.error('внутренний блок catch', e.message);
    throw e;
  }
  finally {
    console.log('finally');
    return;
  }
}
catch (e) {
  console.error('внешний блок catch', e.message);
}

// Output:
// "внутренний блок catch" "упс"
// "finally"
```

</details>

<details>
<summary>Should be changed to something like this, with some of the English translated to Russian (the <code>try</code> block should be inside a <code>function()</code>):</summary>
<br>

```js
(function() {
  try {
    try {
      throw new Error('упс');
    } catch (ex) {
      console.error('inner', ex.message);
      throw ex;
    } finally {
      console.log('finally');
      return;
    }
  } catch (ex) {
    console.error('outer', ex.message);
  }
})();

// Output:
// "inner" "oops"
// "finally"
```

</details>

**Comment by cw118** [comment]
Hi @grol-kun, could you please specify the [MDN page](https://developer.mozilla.org) where you found the issue(s)?

**Comment by cw118** [comment]
I'm closing this since it's difficult to fix an issue without knowing the page(s) where it was found. We can reopen if needed and if more information is provided.

**Comment by grol-kun** [comment]
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/try...catch

**Comment by cw118** [comment]
@grol-kun Thank you for the link; however, there isn't quite enough detail for maintainers/contributors. Could you please specify what issues were found in that page (e.g. a code example was wrong, typos, broken link, etc.)?

**Comment by grol-kun** [comment]
If you try to use it
finally {
console.log('finally');
return;
}
you have an error **A 'return' statement can only be used within a function body.**

**Comment by grol-kun** [comment]
This is an example from the mdn page:
_try {
try {
throw new Error('oops');
}
catch (e) {
console.error('inner catch block', e.message);
throw e;
}
finally {
console log('finally');
return;
}
}
catch (e) {
console.error('outer catch block', e.message);
}_
The error is that we can't use a return outside of a function.

**Comment by cw118** [comment]
@grol-kun Thank you very much for your patience and the additional information, you are absolutely correct. 

It looks like the code block you mentioned should be nested inside a function (the [en-US page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch#returning_from_a_finally-block) has been updated/fixed, but not the Russian one). I allowed myself to modify your original issue a bit to help contributors :)
