### ISSUE TITLE
Issue with "MediaRecorder()": (mediaRecorder cannot be used on ios)

### ISSUE THREAD

**Issue by asuka-boop** [mdn/translated-content#5500]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/MediaRecorder/MediaRecorder

#### What information was incorrect, unhelpful, or incomplete?
I found the mediaRecorder API is not usable on any version of IOS. At the very beginning I thought there was something wrong with our native design, but I found it hard to use on safari too, even though I’m using exactly safari-14 and ios-14

#### What did you expect to see?
I need to know how to let the API-mediaRecorder useful on iOS

#### Did you test this? If so, how?
Yes. We used it on the software we developed 

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/mediarecorder/mediarecorder`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/MediaRecorder/MediaRecorder
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/mediarecorder/mediarecorder/index.html
* Last commit: https://github.com/mdn/translated-content/commit/33058f2b292b3a581333bdfb21b8f671898c5060
* Document last modified: 2020-12-08T19:40:17.000Z

</details>

**Comment by yin1999** [comment]
You can try this: <https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/audio>. 

On Ipad OS 15.4.1 with Safari, I can use `mediaRecorder` API to record sound (but can't play the record in safari, I just created an `a` tag to download the record and it actually recorded the sound).

I think it's both ok on IOS, you can try it.

**Comment by yin1999** [comment]
Any response on this?

**Comment by PointWu** [comment]
I also have this problem. Is there a solution now ？

**Comment by yin1999** [comment]
> I also have this problem. Is there a solution now ？

Could you describe in detail the problem you have occured

**Comment by PointWu** [comment]
I use mediaRecorder API to record sound that only iOS cannot play, but I plan to try using ffmpeg to convert them now
