### ISSUE TITLE
Issue with "KeyboardEvent": (short summary here please)

### ISSUE THREAD

**Issue by kingleiCode** [mdn/translated-content#5503]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/KeyboardEvent

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/keyboardevent`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/KeyboardEvent
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/keyboardevent/index.html
* Last commit: https://github.com/mdn/translated-content/commit/8824afb494e5398bc0efcf5f7eb78782096fc90c
* Document last modified: 2022-03-18T13:53:46.000Z

</details>

**Comment by SphinxKnight** [comment]
@kingleiCode could you please provide some more details about the issue you're facing? Without information, there's little one can do here.
I'm going to close this but will reopen this swiftly if more information is shared.
