### ISSUE TITLE
Macro errors on pt-BR Glossary page

### ISSUE THREAD

**Issue by klaygueds** [mdn/translated-content#5530]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Glossary

#### What information was incorrect, unhelpful, or incomplete?
{{LearnBox({"title":"Aprenda um novo termo:"})}}
{{GlossaryList({"split":"h3", "css":"multiColumnList"})}}
{{GlossaryList({"terms":["TTL"], "filter":"notdefined", "css":"multiColumnList"})}}

#### Specific section or headline?
div

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `pt-br/glossary`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Glossary
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/glossary/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ad7f998115dd568832332484debf1f1b16b0c905
* Document last modified: 2021-02-11T17:27:17.000Z

</details>

**Comment by klaygueds** [comment]
I'm a beginner in web devoloper ,I dont 't know if these are errors, mas the text with these lines appearing is very ugly

**Comment by cw118** [comment]
@klaygueds Those are, in fact, errors, caused by macros that should be removed from this page by updating it (cf. [the en-US file](https://github.com/mdn/content/blob/main/files/en-us/glossary/index.md?plain=1) for a reference).

Thank you for reporting this :)
