### ISSUE TITLE
Content bug: private youtube videos in Chinese tutorial "你的第一個 WebExtension"

### ISSUE THREAD

**Issue by wdzeng** [mdn/translated-content#5535]
## What page(s) did you find the problem on?

[你的第一個 WebExtension](https://developer.mozilla.org/zh-TW/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension)

## Specific page section or heading?

- [安裝](https://developer.mozilla.org/zh-TW/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#%E5%AE%89%E8%A3%9D)
- [測試](https://developer.mozilla.org/zh-TW/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#%E6%B8%AC%E8%A9%A6)

## What is the problem?

YouTube videos in the tutorial are set to be private and cannot be played.

![image](https://user-images.githubusercontent.com/39057640/176516051-1419d07b-bc0c-49f4-b53f-0bcdf9d3b594.png)

## What did you expect to see?

YouTube videos should be public.

**Comment by awxiaoxian2020** [comment]
The reason is that https://github.com/mdn/content/pull/10567 is not synchronized here in zh docs, I will remove these videos later.
