### ISSUE TITLE
Content bug: Remove all occurrences of {{Pref}} macro.

### ISSUE THREAD

**Issue by teoli2003** [mdn/translated-content#5565]
Hey @mdn/localization-team-leads, 

The `{{Pref}}` macro is being [removed from mdn/content](https://github.com/mdn/content/pull/https://github.com/mdn/content/pull/15761) and [deprecated in mdn/yari](https://github.com/mdn/yari/pull/6241). 

When you have a moment, we would appreciate it if you could start the process of removing the macro from your area of `mdn/translated-content`.

**Note:** As the links are mostly broken, replacing the macro with its parameter in code font will do it.

Thank you for your continued work to ensure the health of our translated content.

I found 13 occurrences left on `mdn/translated-content`:
```
> rg -i "\{\{ *pref" -l
files/fr/web/api/webvtt_api/index.md
files/fr/mozilla/firefox/releases/11/index.md

files/ko/web/api/window/open/index.html

files/ru/orphaned/web/api/navigatorid/useragent/index.html
files/ru/web/api/webvtt_api/index.html

files/zh-cn/web/api/element/dommousescroll_event/index.html
files/zh-cn/web/api/webvtt_api/index.html

files/ja/web/api/webvtt_api/index.html
files/ja/orphaned/web/web_components/status_in_firefox/index.html
files/ja/mozilla/firefox/releases/38/index.html
files/ja/mozilla/firefox/releases/45/index.html
files/ja/mozilla/firefox/releases/11/index.html

files/zh-tw/mozilla/firefox/releases/11/index.html
```

**Comment by yin1999** [comment]
#5567 for `l10n-zh`

**Comment by mfuji09** [comment]
Created PR #5695 for 'ja'

**Comment by yin1999** [comment]
There seems to be no `{{Perf}}` macros left in this repo. I've run `rg -i "\{\{ *pref" -l` in main branch.

![image](https://user-images.githubusercontent.com/15844309/169751217-09179f8e-6587-43d4-875e-e8e4ab8bf6cc.png)

**Comment by teoli2003** [comment]
Thanks, all! This is fantastic!

I just opened mdn/yari#6336 for the actual removal.

We can close this issue!
