### ISSUE TITLE
Issue with "HTTP-куки": duplicated/typo in prefix

### ISSUE THREAD

**Issue by AnotherStupidDev** [mdn/translated-content#5566]
MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Cookies

#### What information was incorrect, unhelpful, or incomplete?
In Russian version, cookies with prefixes, duplicate usage of __Host- prefix, instead of __Secure-

#### Specific section or headline?
Cookies with prefixes

#### What did you expect to see?
 __Secure- prefix, instead of __Host-

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/web/http/cookies`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Cookies
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/http/cookies/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ee1610752b61c6e0fb804632bb11f4b68c7da6ec
* Document last modified: 2022-04-23T12:55:31.000Z

</details>

**Comment by sashasushko** [comment]
Fixed
