### ISSUE TITLE
Issue with "Modo Quirks y Modo Estándar": broken links

### ISSUE THREAD

**Issue by Jaroxvf** [mdn/translated-content#5579]
MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

#### What information was incorrect, unhelpful, or incomplete?
broken links:
https://developer.mozilla.org/en-US/docs/Mozilla_Quirks_Mode_Behavior
and
https://developer.mozilla.org/en-US/docs/Gecko's_%22Almost_Standards%22_Mode

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/web/html/quirks_mode_and_standards_mode`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/html/quirks_mode_and_standards_mode/index.html
* Last commit: https://github.com/mdn/translated-content/commit/4c9408f79ed6ccf2b81c4cfaf73cb34cf4d25eb4
* Document last modified: 2021-07-27T15:33:49.000Z

</details>

**Comment by Graywolf9** [comment]
Muchas gracias por reportar el error, he revisado y la sección que contiene las ligas mencionadas esta desactualizada y ha sido eliminado en el contenido principal (en-US), en este PR debería quedar actualizado: https://github.com/mdn/translated-content/pull/10554
