### ISSUE TITLE
Replace old-style compatibility/specification tables with new macro

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#5618]
In mid-2019, we have migrated all of the compatibility table information over to the [BCD project](https://github.com/mdn/browser-compat-data).  Recently, we have also transitioned to using BCD to generate the specifications table.

When I went and marked the old `{{CompatXXX}}` macros as deprecated in Yari, I happened to notice that there are a LOT of translations that are still using the old-style compatibility tables, which means readers may be getting outdated compatibility information.  We should go through and replace all of these tables with ones generated by the new `{{Compat}}` macro.  While we're at it, we should also replace the specifications tables with the `{{Specifications}}` macro as well.

Steps to fix pages:
- Find pages that use any of the following macros: ~`CompatAndroid`~, ~`CompatChrome`~, ~`CompatGeckoDesktop`~, ~`CompatGeckoMobile`~, ~`CompatibilityTable`~, ~`CompatIE`~, ~`CompatNo`~, ~`CompatOpera`~, ~`CompatOperaMobile`~, ~`CompatSafari`~, ~`CompatUnknown`~, ~`CompatVersionUnknown`~, `spec`, `spec2`, `SpecName`
- Replace all content in the "Specifications" section with `{{Specifications}}`
- Replace all content in the "Browser Compatibility" section with `{{Compat}}`

P.S. BCD has an open issue regarding how to handle localization for notes.  We're open to suggestions, see https://github.com/mdn/browser-compat-data/issues/114 for more!

**Comment by yin1999** [comment]
For replacing the specifications tables, I've using `<table class="standard-table">(?:[\s\S\r]*?)</table>` to match and replace with `{{Specifications}}` if existed in `en-US`. The script I've used is [here](https://gist.github.com/yin1999/c718218df49661031280de7eca10ba13) (in Golang, really simple, may not deal with all the cases).

And please check the modifications made by this script, because of the usage of `standard-table` in other tables.

**Comment by yin1999** [comment]
Hi @queengooborg, I found that yari will merge metadata from en-US when render a macro in l10n documents, so whether it's ok to remove `browser-compat` metadata from l10n documents (is there any other usage of this metadata)?

see: https://github.com/mdn/yari/blob/5d8d88976164b6f653c3f2de688f3cd76f8537bb/kumascript/index.js#L56-L69

**Comment by queengooborg** [comment]
Great catch, thanks for the info @yin1999!  Since the en-US metadata is merged, then we can omit the frontmatter key -- I've updated the instructions accordingly!

**Comment by hochan222** [comment]
@queengooborg Hello! 

> Replace all content in the "Browser Compatibility" section with {{Compat}}

I have a question for confirmation. Is it ok to change everything to {{Compat}} as shown below?

- AS IS
```
<h2 id="Browser_compatibility">Browser compatibility</h2>

<p>{{Compat("api.Cache.put")}}</p>
```
- TO BE
```
<h2 id="Browser_compatibility">Browser compatibility</h2>

{{Compat}}
```

**Comment by hochan222** [comment]
Thank you for the reply 🙇🙇

**Comment by yin1999** [comment]
done for l10n-zh

**Comment by SphinxKnight** [comment]
just in case someone needs a regex or two:

`\{\{\s*compatAndroid|\{\{\s*compatChrome|\{\{\s*compatGecko|\{\{\s*compatibilityTable|\{\{\s*compatIE|\{\{\s*compatIE|\{\{\s*CompatNo|\{\{\s*compatOpera|\{\{\s*compatSafari|\{\{\s*compatUnknown|\{\{\s*compatVersionUnknown`

`\{\{\s*spec\s*\(|\{\{\s*spec2\s*\(|\{\{\s*specName\s*\(`

**Comment by cw118** [comment]
`l10n-fr` taken care of by @SphinxKnight 🙌

**Comment by SphinxKnight** [comment]
> `l10n-fr` taken care of by @SphinxKnight 🙌

not really done yet 😅

**Comment by cw118** [comment]
Oops I didn't notice, sorry 😅

**Comment by cw118** [comment]
> `l10n-fr` taken care of by @SphinxKnight 🙌

*now* this is done for fr 😃

**Comment by hochan222** [comment]
Done for l10n-ko. Have a nice day :)

**Comment by Graywolf9** [comment]
Done for `es`. Thank you so much!

**Comment by queengooborg** [comment]
Closing in favor of the new tracking issue at #11594.
