### ISSUE TITLE
Issue with "hashchange": strange text layout

### ISSUE THREAD

**Issue by mainsmirnov** [mdn/translated-content#5637]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Window/hashchange_event

#### What information was incorrect, unhelpful, or incomplete?
Lots of missing spaces

#### Specific section or headline?
Общая информация

<img width="826" alt="Screenshot 2022-05-13 at 19 55 23" src="https://user-images.githubusercontent.com/45998835/168331916-c79c55ad-fab6-4bba-a750-16c9ca91cf42.png">

#### What did you expect to see?

An update of the entire `ru` page should fix this issue (cf. [the en-US page](https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event) for a reference).

<details>
<summary>Page report details</summary>

* Folder: `ru/web/api/window/hashchange_event`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Window/hashchange_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/window/hashchange_event/index.html
* Last commit: https://github.com/mdn/translated-content/commit/c08c48e16cb9e47c586925999362de104ecd710d
* Document last modified: 2021-10-29T17:34:32.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17422 :ok_hand: 

Thank you! :+1:
