### ISSUE TITLE
Issue with "mask": example does not work

### ISSUE THREAD

**Issue by clement-escolano** [mdn/translated-content#5686]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/mask

#### What information was incorrect, unhelpful, or incomplete?

The given example does not work.

#### Specific section or headline?

Example

#### What did you expect to see?

I don't know what I am supposed to see but there is a blank example on Firefox and Safari and full text on Chrome.

Screenshot from Firefox:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/11637509/168571581-a0021cdc-ebdb-4bab-bef3-76574a489a13.png">

The picture link is broken but replacing it with a correct link does not change anything.

#### Did you test this? If so, how?

Not applicable

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/mask`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/mask
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/mask/index.md
* Last commit: https://github.com/mdn/translated-content/commit/500f444d23a7a758da229ebe6b9691cc5d4fe731
* Document last modified: 2022-03-16T16:52:18.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour ce rapport @clement-escolano, j'ai corrigé avec une PR un peu tardive :x

**Comment by clement-escolano** [comment]
Merci pour la correction @SphinxKnight !
