### ISSUE TITLE
Issue with "カスタムプロパティ (--*): CSS 変数": embedlivesample failing

### ISSUE THREAD

**Issue by shingoitoh** [mdn/translated-content#5689]
MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/--*

#### What information was incorrect, unhelpful, or incomplete?
ページの表示がくずれています。

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ja/web/css/--_star_`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/--*
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/--_star_/index.html
* Last commit: https://github.com/mdn/translated-content/commit/adbd42a4e466e24bc462955b954224ae9961911f
* Document last modified: 2022-03-12T12:15:35.000Z

</details>
<img width="1246" alt="スクリーンショット 2022-05-17 9 13 35" src="https://user-images.githubusercontent.com/2138301/168702314-abb84a18-9087-4e73-8da9-293be3e67cb8.png">

**Comment by cw118** [comment]
Thanks for reporting! This is likely part of/related to #2843.
