### ISSUE TITLE
Content bug: 外部链接跳转错误 https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/Express_Nodejs/Introduction

### ISSUE THREAD

**Issue by Long-louis** [mdn/translated-content#5698]
## What page(s) did you find the problem on?

[](https://developer.mozilla.org/zh-CN/docs/Learn/Server-side/Express_Nodejs/Introduction)

## Specific page section or heading?

使用异步 APIs

## What is the problem?

该连接跳转错为http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/%C2%A0
![Screenshot_20220517-135853_Edge.jpg](https://user-images.githubusercontent.com/41790869/168739786-f116409f-2ad9-4384-8197-c4769170bd25.jpg)

## What did you expect to see?

应该为
http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js

**Comment by yin1999** [comment]
I've created #5701 to fix this.
