### ISSUE TITLE
Issue with "Responsive design": duplicated sentence

### ISSUE THREAD

**Issue by scytaleqc** [mdn/translated-content#5712]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/CSS/CSS_layout/Responsive_Design

#### What information was incorrect, unhelpful, or incomplete?

In the "Grilles Flexibles" section, 5th paragraph, the first sentence seems doubled.

"Cette approche se retrouve aujourd'hui à de nombreux endroits sur le Web, et elle est documentée ici dans la section sur la mise en page de notre article sur [Méthodes de mises en page traditionnelles](https://developer.mozilla.org/fr/docs/Learn/CSS/CSS_layout/Legacy_Layout_Methods). Cette approche se retrouve aujourd'hui à de nombreux endroits sur le Web, et elle est documentée ici dans la section sur la mise en page de notre article sur les méthodes de mise en page héritées."

#### Specific section or headline?

Grilles Flexibles, 5th paragraph

#### What did you expect to see?

No repetition of sentences.

#### Did you test this? If so, how?

It's on the webpage.

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/css/css_layout/responsive_design`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/CSS/CSS_layout/Responsive_Design
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/css/css_layout/responsive_design/index.md
* Last commit: https://github.com/mdn/translated-content/commit/500f444d23a7a758da229ebe6b9691cc5d4fe731
* Document last modified: 2022-03-16T16:52:18.000Z

</details>

**Comment by tramio** [comment]
Hi! This sentence does seem to have been inadvertently duplicated. May I work on this issue? 💪🏻

**Comment by cw118** [comment]
@tramio Of course :)

**Comment by SphinxKnight** [comment]
> Hi! This sentence does seem to have been inadvertently duplicated. May I work on this issue? 💪🏻

Please do :) and if you have any question along the way, don't hesitate to ask :)

**Comment by tramio** [comment]
Thanks both of you! I just submitted a PR, don't hesitate if changes need to be made. 😊 Cheers!
