### ISSUE TITLE
`HTML/Element/Input/file`: translation error (missing words)

### ISSUE THREAD

**Issue by 807460453** [mdn/translated-content#5720]
## What page(s) did you find the problem on?

https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input/file

## Specific page section or heading?

[capture](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/Input/file#attr-capture)
## What is the problem?
word missing
则它指定了使用哪个摄像头去这些数据

## What did you expect to see?
则它指定了使用哪个摄像头去获取这些数据

**Comment by AlwaysReVaule** [comment]
I tried to fix this issue on https://github.com/mdn/translated-content/pull/5741#issue-1242752799, you may be able to close this issue. 😁 @cw118 @807460453

**Comment by cw118** [comment]
Thank you @AlwaysReVaule, I have linked your PR to this issue (meaning this will close automatically when the pull request is merged) :)
