### ISSUE TITLE
Issue with "Объединённый асинхронный JavaScript: Таймауты и ин…": missing source code and examples

### ISSUE THREAD

**Issue by aytenweb** [mdn/translated-content#5733]
All code sources and examples are not found

**Comment by cw118** [comment]
@aytenweb Thank you for reporting! Could you please provide the full link and title of the MDN page in the description of the issue? It would be much easier for contributors/maintainers to fix these problems this way :)

**Comment by aytenweb** [comment]
Hello,
There are many such pages with such problems. For example
1.
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Introducing
->
https://github.com/mdn/learning-area/blob/main/javascript/asynchronous/introducing/async-sync.html
404
2.
https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous
->
https://mdn.github.io/learning-area/javascript/asynchronous/loops-and-intervals/reaction-game.html
,
https://github.com/mdn/learning-area/blob/main/javascript/asynchronous/loops-and-intervals/reaction-game.html
3.
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Promises
->
https://mdn.github.io/learning-area/javascript/asynchronous/async-await/promise-finally-async-await.html
,
https://github.com/mdn/learning-area/blob/main/javascript/asynchronous/async-await/promise-finally-async-await.html

чт, 19 мая 2022 г. в 17:08, Carolyn Wu ***@***.***>:

**Comment by leon-win** [comment]
Most of these pages no longer exist. And the remaining two examples have been fixed =)

That's why I'm closing the issue
