### ISSUE TITLE
Issue with "Window.navigator": (short summary here please)

### ISSUE THREAD

**Issue by sdmmj** [mdn/translated-content#5744]
MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Window/navigator

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/window/navigator`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Window/navigator
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/window/navigator/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1407c8fdef01ecd0ffb8a8bd46e7113f119b9fde
* Document last modified: 2021-10-02T15:30:20.000Z

</details>

**Comment by SphinxKnight** [comment]
Please provide some more details about the issue you are facing so that we can help fixing it.
I'll close this for now but will reopen it, should information be added.
