### ISSUE TITLE
Issue with "keydown": out of date information

### ISSUE THREAD

**Issue by AngiPardo** [mdn/translated-content#5746]
MDN URL: https://developer.mozilla.org/es/docs/Web/API/Document/keydown_event

#### What information was incorrect, unhelpful, or incomplete?
Information about event is deprecated (out of date) for keydown when using an addEventListener.

#### Specific section or headline?
const keyName = event.key;

#### What did you expect to see?
I hope the information is up to date to use it.

#### Did you test this? If so, how?
When I try to use event with keydown, I get a banner saying it is deprecated: 

"var event: Event @deprecated 'event' is deprecated.ts(6385)
lib.dom.d.ts(17314, 5): The declaration was marked as deprecated here.
No quick fixes available"

Thank you!

<details>
<summary>Page report details</summary>

* Folder: `es/web/api/document/keydown_event`
* MDN URL: https://developer.mozilla.org/es/docs/Web/API/Document/keydown_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/api/document/keydown_event/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1109132f09d75da9a28b649c7677bb6ce07c40c0
* Document last modified: 2020-12-08T19:41:45.000Z

</details>

**Comment by Graywolf9** [comment]
Thank you so much for reporting the erros!

I update the whole page that should solve it: https://github.com/mdn/translated-content/pull/12195
