### ISSUE TITLE
Issue with "Math.random()": (incomplete information)

### ISSUE THREAD

**Issue by EnriqueSource** [mdn/translated-content#5774]
MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Math/random

#### What information was incorrect, unhelpful, or incomplete?
The "Getting a random integer between two values, inclusive" section does not appear.
In addition, the differences between the Spanish article and the English or German article make the Spanish article less explanatory.
The explanation appears as a comment within the code box itself.

#### Specific section or headline?
Getting a random integer between two values, inclusive

#### What did you expect to see?
the detailed and complete explanation, as they appear in the English and German versions.

#### Did you test this? If so, how?
reading the article in Spanish language.

<details>
<summary>Page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/math/random`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Math/random
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/math/random/index.html
* Last commit: https://github.com/mdn/translated-content/commit/0ce7202a706c9036eeea42c158f433c2b7940457
* Document last modified: 2022-03-03T13:36:23.000Z

</details>

**Comment by marcelozarate** [comment]
Hola @EnriqueSource ¡muchas gracias por tu contribución! Veo que tienes experiencia con Git y con los idiomas, ¿te animas a colaborar solucionando esta issue?

Aquí tienes una [guía](https://github.com/mdn/translated-content/discussions/4029) de cómo empezar

Si no tienes tiempo o no quieres hacerlo, ¡perfecto! Solo avisa debajo y me encargaré por ti. Pero si quieres dar el salto y solucionarlo, con gusto lo recibiremos, puedes unirte a nuestro [chat](https://chat.mozilla.org/#/room/!cIEBGoIHFpsXNeVUwp:mozilla.org) para cualquier duda. ¡Necesitamos gente con experiencia como tú para colaborar en la comunidad en español!

**Comment by EnriqueSource** [comment]
Hola @marcelozarate. Gracias por tus comentarios. Por supuesto que me animo. MDN tiene la mejor documentación sobre programación Web existente y creo que es justo devolver esa ayuda que nos ofrece aportando algo.
