### ISSUE TITLE
Issue with "Les modules JavaScript": broken link for "un ensemble d'exemples disponibles sur GitHub"

### ISSUE THREAD

**Issue by agilare** [mdn/translated-content#5800]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules

#### What information was incorrect, unhelpful, or incomplete?

URL of link [un ensemble d'exemples disponibles sur GitHub](https://github.com/mdn/js-examples/tree/master/modules) is a 404 error

#### Specific section or headline?

https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules#commen%C3%A7ons_par_un_exemple

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/guide/modules/index.md
* Last commit: https://github.com/mdn/translated-content/commit/e1b8b2e3776b5e132a90fac2ab676a6885b7ca34
* Document last modified: 2022-03-23T07:21:29.000Z

</details>

**Comment by tramio** [comment]
Hey there! It appears that this URL broke following the commit [#a5ca9cdfafd1a684e8a7d317df14bd39171f031c](https://github.com/mdn/js-examples/commit/a5ca9cdfafd1a684e8a7d317df14bd39171f031c) whereby the "modules" folder was renamed "module-examples".

Broken URL: https://github.com/mdn/js-examples/tree/master/modules
Updated URL: https://github.com/mdn/js-examples/tree/master/module-examples

Additionally, I've noticed the above-mentioned commit broke other URLs from this same page; they should be updated as well. May I have this issue assigned?

**Comment by cw118** [comment]
@tramio Yes of course, assigned to you. Let me know if I can help in any way :)

**Comment by tramio** [comment]
Thank you, I just submitted a PR! ☀️

**Comment by cw118** [comment]
Fixed by #5861, I forgot to link this to the PR
