### ISSUE TITLE
Issue with "click": (Layout collapsed)

### ISSUE THREAD

**Issue by FlandreDaisuki** [mdn/translated-content#5829]
MDN URL: https://developer.mozilla.org/zh-TW/docs/Web/API/Element/click_event

#### What information was incorrect, unhelpful, or incomplete?

Layout collapsed in locale `zh-TW`

#### Did you test this? If so, how?

![screenshot](https://user-images.githubusercontent.com/5981459/170413661-93b2bdb5-28fd-4358-951b-5279449468ba.png)

<details>
<summary>Page report details</summary>

* Folder: `zh-tw/web/api/element/click_event`
* MDN URL: https://developer.mozilla.org/zh-TW/docs/Web/API/Element/click_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-tw/web/api/element/click_event/index.html
* Last commit: https://github.com/mdn/translated-content/commit/537ead9a93b5c05a2d7296bf05c6fbeddfc4d87e
* Document last modified: 2022-05-24T04:48:59.000Z

</details>

**Comment by cpWhitecat** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/audio#%E4%BA%8B%E4%BB%B6
this page also has this problem, the same of Event list.
canplaythrough_event , loadeddata_event,playing_event ....
