### ISSUE TITLE
issue with about git action(test)

### ISSUE THREAD

**Issue by Jack-Zhang-1314** [mdn/translated-content#5850]
## What page(s) did you find the problem on?

In my pr, translate(zh-CN):readeableStream/pipeto~ #5848
see:<https://github.com/mdn/translated-content/pull/5848>

## What is the problem?

![ ](https://user-images.githubusercontent.com/82551626/170637089-31580342-618d-44df-8ff6-c045f5c5e660.png)

>I don't think pr is the problem, but running the action is the problem

**Comment by yin1999** [comment]
Fixed in #5859.
