### ISSUE TITLE
Issue with "MDN Web 文档写作规范": (out-of-date document)

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#5866]
MDN URL: https://developer.mozilla.org/zh-CN/docs/MDN/Guidelines/Writing_style_guide

#### What information was incorrect, unhelpful, or incomplete?

The document is out-of-date, which may confuse contributors.

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/mdn/guidelines/writing_style_guide`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/MDN/Guidelines/Writing_style_guide
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/mdn/guidelines/writing_style_guide/index.html
* Last commit: https://github.com/mdn/translated-content/commit/6a0c7c90a1725ee783bada9ede480ae38b7fbe02
* Document last modified: 2022-05-25T18:30:46.000Z

</details>

**Comment by awxiaoxian2020** [comment]
Are there any plans for this issue?

**Comment by yin1999** [comment]
> Are there any plans for this issue?

I think it's better to complete the [markdown convertion](https://github.com/mdn/translated-content/discussions/2474) first (discussed with `l10n-zh` localization team), then working on those contribution documents. Or you can help to deal with this documents (I'm glad to review).

There is still a lot of work needs to be done here.

**Comment by awxiaoxian2020** [comment]
> > Are there any plans for this issue?
> 
> I think it's better to complete the [markdown convertion](https://github.com/mdn/translated-content/discussions/2474) first (discussed with `l10n-zh` localization team), then working on those contribution documents. Or you can help to deal with this document (I'm glad to review).
> 
> There is still a lot of work needs to be done here.

As a new contributor of this repo, I haven't known the workflow about the "big event" like `markdown convertion` or `a style of document` yet. So I don't know how to contribute about these events. I just have some questions and suggestions.
**questions**:

- You said the doc is out-of-date. What does it mean? It doesn't sync with the English version?
- In the doc, we can see:
> The language aspects of this guide apply primarily to English-language documentation. Other languages may have (and are welcome to create) style guides. These should be published as subpages of the localization team's page.

Are there subpages of `l10n-zh` team and some styles of Chinese? I need a reference link.

tips: These questions should have been solved by myself through looking into it. I will check sth. later but I'm glad if you can help me.

**suggestions**:

- Use the GitHub Project for this repo for some "big event" like what I said before.
- The MDN Web Docs is not only a doc but a website. But it's a doc mainly. We should give a brief doc of **writing styles** for contributors. Although there are some statements in our doc:
> We are more interested in content than formatting, so don't feel obligated to learn the style guide before contributing. 

But I think we should have a basic guide for writing.
- We can reference the [React 中文文档译文排版指南](https://github.com/reactjs/zh-hans.reactjs.org/wiki/React-%E4%B8%AD%E6%96%87%E6%96%87%E6%A1%A3%E8%AF%91%E6%96%87%E6%8E%92%E7%89%88%E6%8C%87%E5%8D%97) for the zh contributor doc if there are no details about it.

**original purpose of commenting here**:

when I'm working with #6162 , I haven't find some Chinese styles. It feels not so good.

**Comment by yin1999** [comment]
> You said the doc is out-of-date. What does it mean? It doesn't sync with the English version?

Yes, we just keep the document the same as the english version (if not necessary, we will not add extra sentences)

> Use the GitHub Project for this repo for some "big event" like what I said before.

We will consider this, like `l10n-fr`, `l10n-ko`.

> The MDN Web Docs is not only a doc but a website. But it's a doc mainly. We should give a brief doc of writing styles for contributors. Although there are some statements in our doc

I'm still working on it (maybe just for `markdown` file), and it will be something like: <https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md>. It will take us a lot of time to complete it, and if you have any suggestions, feel free to tell us (I will create a related PR later)

Thanks for your suggestion

**Comment by yin1999** [comment]
> > Use the GitHub Project for this repo for some "big event" like what I said before.
> 
> We will consider this, like `l10n-fr`, `l10n-ko`.

Setting up <https://github.com/mdn/translated-content/projects/9>

**Comment by yin1999** [comment]
> Could you please check it? I don't know whether removing or correcting it.

Just remove it.
