### ISSUE TITLE
Issue with "着色编辑器": (Cannot find Shader Editor)

### ISSUE THREAD

**Issue by Carlos920** [mdn/translated-content#591]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Tools/Shader_Editor

#### What information was incorrect, unhelpful, or incomplete?
找不到 Shader Editor 选项

#### Specific section or headline?
 this section 

#### Did you test this? If so, how?
yes

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/tools/shader_editor`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Tools/Shader_Editor
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/tools/shader_editor/index.html
* Last commit: https://github.com/mdn/translated-content/commit/33d52ff611c0da0039a2c07ebd7ca0c9645e2cff
* Document last modified: 2021-04-17T15:31:39.000Z

</details>

### Cannot find Shader_Editor!
![image](https://user-images.githubusercontent.com/32257015/115317212-8eac4200-a1ad-11eb-9a0f-be0faee5427e.png)

**Comment by fish-404** [comment]
>Note: This tool has been deprecated and will soon be removed from Firefox. For details, see [Deprecated tools](https://developer.mozilla.org/en-US/docs/Tools/Deprecated_tools).

**Comment by yin1999** [comment]
This issue might be closed by resolving #4822

**Comment by yin1999** [comment]
@cw118 resolve by pr #4844.
