### ISSUE TITLE
Content bug: <Layout collapsed>

### ISSUE THREAD

**Issue by cpWhitecat** [mdn/translated-content#5964]
## What page(s) did you find the problem on?
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/audio#%E4%BA%8B%E4%BB%B6

## Specific page section or heading?
they also have general info of heading in the event page

## What is the problem?
Some Event pages has, like loadeddata_event , canplaythrough_event , playing_event...

**Comment by cpWhitecat** [comment]
ended_event , canplay_event and canplaythrough_event ,they have the same problems.

**Comment by yin1999** [comment]
Todo list:

- [ ] https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/loadeddata_event
- [ ] https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/ended_event
- [ ] https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/playing_event
- [ ] https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/canplaythrough_event
- [ ] https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLMediaElement/canplay_event
