### ISSUE TITLE
Issue with "Módulos JavaScript": (github repo: page not found)

### ISSUE THREAD

**Issue by jo4web** [mdn/translated-content#5981]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Modules

All examples from the github repo, when I try access page is not found.

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/javascript/guide/modules/index.html
* Last commit: https://github.com/mdn/translated-content/commit/da778d8d0a9e9622c6a7fba6d1f9fb7d3ebf4a04
* Document last modified: 2021-08-19T13:37:01.000Z

</details>

**Comment by cw118** [comment]
Thank you for reporting! This is likely because the MDN js-examples folder `modules` was renamed to `module-examples` (cf. #5861).

**Comment by awxiaoxian2020** [comment]
It should be closed by https://github.com/mdn/translated-content/pull/6141 .
