### ISSUE TITLE
Issue with "Using XMLHttpRequest": (Possible spanish misspelling)

### ISSUE THREAD

**Issue by josep-castell-colom** [mdn/translated-content#5983]
MDN URL: https://developer.mozilla.org/es/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest

#### What information was incorrect, unhelpful, or incomplete?
The word "hallan".

#### Specific section or headline?
[Ejemplo: Solicitudes asíncronas](https://developer.mozilla.org/es/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#ejemplo_solicitudes_as%C3%ADncronas)

https://github.com/mdn/translated-content/blob/7619b14593cfd4b2b81093d10c5c5d30c5f599f0/files/es/web/api/xmlhttprequest/using_xmlhttprequest/index.html#L59

#### What did you expect to see?
The word "hayan".

#### Did you test this? If so, how?
[RAE: «Halla» / «haya» / «aya»](https://www.rae.es/espanol-al-dia/halla-haya-aya-0)

<details>
<summary>Page report details</summary>

* Folder: `es/web/api/xmlhttprequest/using_xmlhttprequest`
* MDN URL: https://developer.mozilla.org/es/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/api/xmlhttprequest/using_xmlhttprequest/index.html
* Last commit: https://github.com/mdn/translated-content/commit/adcc79aaec9b8077c11035c8e7c329d5c225fa3e
* Document last modified: 2022-05-05T16:33:40.000Z

</details>

**Comment by stripTM** [comment]
I take this issue, I see that the translation is no longer in sync with the original. I translate it again and convert it to md format.

**Comment by JuanVqz** [comment]
Closes by #6303
