### ISSUE TITLE
Issue with "Mathématiques de base en JavaScript — nombres et o…": broken link/example

### ISSUE THREAD

**Issue by JFgith** [mdn/translated-content#5991]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/Math

#### What information was incorrect, unhelpful, or incomplete?

The console link (https://mdn.github.io/learning-area/javascript/introduction-to-js-1/variables/) return a 404 page

#### Specific section or headline?

[Ce ne sont que des nombres pour moi](https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/Math#ce_ne_sont_que_des_nombres_pour_moi)

#### What did you expect to see?

A working link and example/updated page.

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/javascript/first_steps/math`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/JavaScript/First_steps/Math
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/javascript/first_steps/math/index.md
* Last commit: https://github.com/mdn/translated-content/commit/500f444d23a7a758da229ebe6b9691cc5d4fe731
* Document last modified: 2022-03-16T16:52:18.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour le rapport d'erreur @JFgith, #6146 devrait corriger ça :)
