### ISSUE TITLE
Issue with "RegExp": page macros for instance properties in Russian

### ISSUE THREAD

**Issue by Jazzmanpw** [mdn/translated-content#5995]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp

#### What information was incorrect, unhelpful, or incomplete?

There are badly rendered links

#### Specific section or headline?

Yep, [the one for RegExp prototype objects and instances](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp#regexp_prototype_objects_and_instances) in Russian 

#### What did you expect to see?

I expected to see instance fields and methods. Or a link to such info

#### Did you test this? If so, how?

I tried to enter the link directly into URL. It sais there's no such page in Russian, but it suggest I might want to see it in English. If the link may be there with some note (like "not translated, read in English?"), it'll improve UX for this section

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/global_objects/regexp`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/RegExp
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/global_objects/regexp/index.html
* Last commit: https://github.com/mdn/translated-content/commit/09d10136633355937867a21d65db64ae3c4d5829
* Document last modified: 2021-10-27T15:02:34.000Z

</details>

**Comment by cw118** [comment]
Thanks for reporting @Jazzmanpw ! This is a part of/caused by #3892 (the `{{page}}` macros need to be removed).
