### ISSUE TITLE
Broken `{{EmbedLiveSample}}` for "how_floated_elements_are_positioned" (`/es/docs/Web/CSS/float`)

### ISSUE THREAD

**Issue by Marlys-Aguila** [mdn/translated-content#6061]
MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/float

Live sample failed!
An error occurred trying to render this live sample.
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find any live code samples for "how_floated_elements_are_positioned" within /es/docs/Web/CSS/float

<details>
<summary>Page report details</summary>

* Folder: `es/web/css/float`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/float
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/float/index.html
* Last commit: https://github.com/mdn/translated-content/commit/9697aeab7d1f7b4fd249e5c4cf8dbf3c8e9e0b14
* Document last modified: 2021-07-07T16:40:08.000Z

</details>

**Comment by Marlys-Aguila** [comment]
Live sample failed!
An error occurred trying to render this live sample.
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find any live code samples for "how_floated_elements_are_positioned" within /es/docs/Web/CSS/float

**Comment by Graywolf9** [comment]
Muchas gracias por reportar el error

Fixed in #9409
