### ISSUE TITLE
Typo in "Formatação avançada de texto" page

### ISSUE THREAD

**Issue by genivanss** [mdn/translated-content#6092]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

#### What information was incorrect, unhelpful, or incomplete?
In Portuguese version, the word "Cotação" is incorrect. The correct word is "Citação".

#### Specific section or headline?
Yes, in the specific section Quotations (headlines and contents).
https://developer.mozilla.org/pt-BR/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting#cota%C3%A7%C3%B5es

#### What did you expect to see?
I expect to see the word "citação" instead of "cotação" in contents and headline in this page.

#### Did you test this? If so, how?
I performed the verification when I read the article in Portuguese (pt-BR)

<details>
<summary>Page report details</summary>

* Folder: `pt-br/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/html/introduction_to_html/advanced_text_formatting/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ad7f998115dd568832332484debf1f1b16b0c905
* Document last modified: 2021-02-11T17:27:17.000Z

</details>

**Comment by josielrocha** [comment]
Thanks a bunch @GuiCoutoSt!! 🚀
