### ISSUE TITLE
Issue with "undefined": (short summary here please)

### ISSUE THREAD

**Issue by Raf-sns** [mdn/translated-content#6119]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/undefined

#### What information was incorrect, unhelpful, or incomplete?
[L'opérateur typeof et undefined](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/undefined#lop%C3%A9rateur_typeof_et_undefined)

#### Specific section or headline?

The typeof operator and "undefined"

#### What did you expect to see?

with "typeof" undefined, must be evaluated as a character string. undefined should always be evaluated as a quoted string ( "undefined" )
#### Did you test this? If so, how?

typeof Chart === "undefined"
true
typeof Chart === undefined
false

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/undefined`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/undefined
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/undefined/index.md
* Last commit: https://github.com/mdn/translated-content/commit/1d4933b05458c39c8aeb37b83cd52d90d4bf66fb
* Document last modified: 2022-05-30T14:42:52.000Z

- I think it should be clarified because I had a misunderstanding on this subject and evaluating undefined either as a constant or as a character string, it can be confusing. Sincerely,
Raf

</details>

**Comment by cw118** [comment]
Hi @Raf-sns, the example in the section "L'opérateur `typeof` et `undefined`" is:

```js
// x n'a pas encore été défini
if (typeof x === 'undefined') { // donnera true sans erreur
   // ces instructions seront exécutées
}

if (x === undefined) { // déclenche une ReferenceError

}
```

`typeof x === 'undefined'` uses `undefined` as a quoted string, so I think the example is correct. Could you please confirm this or provide more details?

**Comment by Raf-sns** [comment]
Hi, 
look at  version without quotes and the version with :
- 
`if ( typeof x === undefined ) { 
  console.log('not defined');
}
else{
  console.log('is defined');
}
// > is defined `

`if ( typeof x === 'undefined' ) { 
  console.log('not defined');
}
else{
  console.log('is defined');
}
// > not defined`

**Comment by cw118** [comment]
Thank you for providing details @Raf-sns, I have created #6424 to hopefully resolve this :)
