### ISSUE TITLE
Issue with "Reason: CORS request did not succeed": (short summary here please)

### ISSUE THREAD

**Issue by ttkp1** [mdn/translated-content#6131]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/http/cors/errors/corsdidnotsucceed`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/http/cors/errors/corsdidnotsucceed/index.html
* Last commit: https://github.com/mdn/translated-content/commit/cf31101f504892ee58f06301e7a0a71229134dc2
* Document last modified: 2022-05-31T00:55:51.000Z

</details>

**Comment by cw118** [comment]
I am closing this because no information was provided. Please give more details on the issue(s) you're facing on the MDN page and we can reopen if needed.
