### ISSUE TITLE
Issue with "使用对象": Questionable "Translation Notes"

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/translated-content#6154]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Working_with_Objects

#### What information was incorrect, unhelpful, or incomplete?
There is a translation note https://github.com/mdn/translated-content/blob/b6a647eec4df2ae42be842b33af92dc7fc8b50b7/files/zh-cn/web/javascript/guide/working_with_objects/index.html#L25
It's so confusing about "鸭子".

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/guide/working_with_objects`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Guide/Working_with_Objects
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/guide/working_with_objects/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d75b52eb26fd66c02193b8b8ea66fb4c74c2f9e4
* Document last modified: 2022-05-29T07:21:49.000Z

</details>

**Comment by yin1999** [comment]
"鸭子类型" is a common translation, see [wikipedia](https://zh.wikipedia.org/zh-cn/%E9%B8%AD%E5%AD%90%E7%B1%BB%E5%9E%8B) or [baidu](https://baike.baidu.com/item/%E9%B8%AD%E5%AD%90%E7%B1%BB%E5%9E%8B/10845665).

I think it's ok to keep the `translation note`, until synced with english version.

If you have other question about this document, please tell us, we can reopen this issue.

**Comment by awxiaoxian2020** [comment]
@yin1999 My fault. But there are two points I want to say:
1. `动态语言面向对象的鸭子类型` seems not be read friendly, I think we can modify it to `此即动态语言中基于面向对象的“鸭子类型”`.
2. I don't understand what you said `until synced with english version` . I think the original text is clear, the note is not necessary(I'm not saying we should remove it, I just say about it, It's ok to keep it)

**Comment by yin1999** [comment]
We translate the documents in [mdn/content](https://github.com/mdn/content) into Chinese. And if not necessary, we will not add extra sentences here. So I think if the original translation is ok, we can just keep it, or we can modify the document to keep it the same as the english version in mdn/content.

**Comment by awxiaoxian2020** [comment]
> We translate the documents in [mdn/content](https://github.com/mdn/content) into Chinese. And if not necessary, we will not add extra sentences here. So I think if the original translation is ok, we can just keep it, or we can modify the document to keep it the same as the english version in mdn/content.

It seems that the `translation note` is not in [mdn/content](https://github.com/mdn/content). And as I said, There is a Chinese grammar error in `动态语言面向对象的鸭子类型`. We can be the same as the original text in [mdn/content](https://github.com/mdn/content), but not `the original translation`. I think there was a problem in this translation.

Now I'm not saying the original issue I post here. It's how to express `动态语言面向对象的鸭子类型` correctly.

**Comment by yin1999** [comment]
> Now I'm not saying the original issue I post here. It's how to express `动态语言面向对象的鸭子类型` correctly.

Yes, I understand. But I think the Chinese grammar is ok for this sentence. If you think this is difficult to understand, we can just remove it (for this is not in <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects>).

**Comment by awxiaoxian2020** [comment]
> > Now I'm not saying the original issue I post here. It's how to express `动态语言面向对象的鸭子类型` correctly.
> 
> Yes, I understand. But I think the Chinese grammar is ok for this sentence. If you think this is difficult to understand, we can just remove it (for this is not in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Working_with_Objects).

> I think the original text is clear, the note is not necessary.

I express the same about removing. But I think it's ok to keep and modify it.

All in all, I agree with removing it.

**Comment by yin1999** [comment]
> All in all, I agree with removing it.

PR is welcomed

**Comment by yin1999** [comment]
resolved in #6157
