### ISSUE TITLE
`zh-CN` translation guide

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#6166]
After @awxiaoxian2020 raised questions [here](https://github.com/mdn/translated-content/issues/5866#issuecomment-1149366569). I think we should start to discuss the translation guidelines for `zh-CN`.

For we are converting the `.html` files to `.md`, so I prefer to just fill it for markdown files only.

Feel free to give suggestions here

**Comment by yin1999** [comment]
1. 中文与英文、数字之间保留空格（全角标点和英文数字之间不留空格），同时忽略链接、内联代码的影响，即：链接文字、内联代码和正常文字部分也执行此规则：```这是一个[示例](#示例)```、``` 这是一个 `code` 示例 ```、```这是一个`内联代码`示例```
2. 英文原文中指向站内链接的，若无特殊情况，请更新相关的链接到 `zh-CN`，即使本地化的文档不存在（mdn/yari 平台会自动回落到 `en-US`），同时请只保留 URL 的 PATH 部分，例如：`https://developer.mozilla.org/en-US/docs/MDN/Contribute/Open_source_etiquette` 在中文文档中，应该写成 `/zh-CN/docs/MDN/Contribute/Open_source_etiquette`
3. 关于标点符号，请按中英文对应的符号关系，将半角符号换成全角，但请注意一些特殊的例子：如英文中使用逗号表示并列词语的关系，中文中请使用顿号：`a, b, and c` ---> `a、b 和 c`
4. 人称代词，如 `you`，在中文中，请直接使用`你`，而无需使用`您`这类尊称
5. 复数形式，如 `APIs`，在中文中，若不翻译，请去掉其复数形式 `API`
6. 还有一部分与 MDN 文档元数据（front matter）相关的内容，我后续再进行补充（如 `slug`、`browser-compat` 等）

**Comment by yin1999** [comment]
特别注意一部分 `kumascript` 宏的使用，如 `{{EmbedLiveSample}}`、`{{Interwiki}}`，其引用内容的参数需要指向本地化内容，而非仅使用英文原文

**Comment by yin1999** [comment]
在英文文档中 markdown 文档会使用一个换行符来代替一个空格，这样并不会影响英文文档内容的展示，而在中文中，请使用单独一行代替（避免正文部分空格的插入）

**Comment by awxiaoxian2020** [comment]
> 在英文文档中 markdown 文档会使用一个换行符来代替一个空格，而在中文中，请使用单独一行代替（避免正文部分空格的插入）

We should give an example.

**Comment by yin1999** [comment]
> We should give an example.

added

**Comment by yin1999** [comment]
I've raise #6172 to add `zh-CN` translation guide, it's still in process. Feel free to give suggestions.
