### ISSUE TITLE
Issue with "Приоритет операторов": (short summary here please)

### ISSUE THREAD

**Issue by MendeleevEgor** [mdn/translated-content#6171]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?
—
[Таблица](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table)
Операторы упорядочены **с самого высокого** (19) **до самого высокого** (1) приоритета.
—
P.S так какой приоритет выше?

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/operators/operator_precedence/index.html
* Last commit: https://github.com/mdn/translated-content/commit/676652069af1fba1bc41d3ed6e1ebe530ce50689
* Document last modified: 2022-05-06T18:27:51.000Z

</details>

**Comment by leon-win** [comment]
Hi @MendeleevEgor !

This issue was fixed, there is right description now:
![image](https://github.com/mdn/translated-content/assets/1682136/d429368b-bae4-4e6c-addb-3145c094f588)
