### ISSUE TITLE
Issue with "Принятие решений в вашем коде — условные конструкц…": English code options

### ISSUE THREAD

**Issue by FeelsGo-od** [mdn/translated-content#6177]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/Building_blocks/conditionals

#### What information was incorrect, unhelpful, or incomplete?
In Russian version of "changing color task" it has english names of the options in code (like 'black', 'white', etc.) instead of for example ('Белая', 'Чёрная' etc.) - it might be a little bit confusing. 

#### Specific section or headline?
"[Практическое упражнение: расширяем выбор цветов](https://developer.mozilla.org/ru/docs/Learn/JavaScript/Building_blocks/conditionals#%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%83%D0%BF%D1%80%D0%B0%D0%B6%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D1%8F%D0%B5%D0%BC_%D0%B2%D1%8B%D0%B1%D0%BE%D1%80_%D1%86%D0%B2%D0%B5%D1%82%D0%BE%D0%B2)"

#### What did you expect to see?
I tried to do this task for myself, but i wrote "Чёрная", "Белая"... and I was angry when it didn't work :D
It's a small issue, but still.

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/javascript/building_blocks/conditionals`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/Building_blocks/conditionals
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/javascript/building_blocks/conditionals/index.html
* Last commit: https://github.com/mdn/translated-content/commit/980fe00a74a9ad013b945755415ace2e5429c3c2
* Document last modified: 2021-10-26T23:31:24.000Z

</details>

**Comment by leon-win** [comment]
Hi @FeelsGo-od !

I'm sure it's no longer relevant, but still better late than never))

The example given is quite correct. As far as I understand, at that time you got confused with the values in the `select` tag in HTML))

So I close thie issue
