### ISSUE TITLE
[Help Wanted] Question about the `@mention` link we use for teams

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/translated-content#6185]
For example, in https://github.com/mdn/translated-content/blob/main/PEERS_GUIDELINES.md

> We use Brazilian Portuguese (pt-BR) content — the [@yari-content-pt-br](https://github.com/orgs/mdn/teams/yari-content-pt-br) team

We use[@yari-content-pt-br](https://github.com/orgs/mdn/teams/yari-content-pt-br) to refer to the team. But the behind link was 404.

Is there some wrong information? Or just a style of mentioning the team, we don't care about the link?

**Comment by yin1999** [comment]
It's used in mdn teams, so only MDN team member could see it.

If you need any help, please pin a member of a `l10n` team.

**Comment by awxiaoxian2020** [comment]
> It's used in mdn teams, so only MDN team member could see it.
> 
> If you need any help, please pin a member of a `l10n` team.

Thanks for your reply!

**Comment by yin1999** [comment]
> Thanks for your reply!

Feel free to discuess with us :)
