### ISSUE TITLE
Issue with "section": HTML specification for definition lists

### ISSUE THREAD

**Issue by S-Cesc** [mdn/translated-content#6209]
MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Element/section

#### What information was incorrect, unhelpful, or incomplete?
"section" tag can't be inside definition list, "dl" tag, while "div" tag (fortunatelly) can be.

About HTML specification:
It'd be fine a "section" inside definition list ("dl" tag), using "dt" tag as the title, content structured on "dd" tags, but "header" and "footer" tags allowed... of course it can be done other way, but it'd allow a richer semantic structure for definition lists ("dl").

Exemple; a definition list ("dl") with a "section" including "header" tag for classification of the term, the definition term ("dt"), acting as title of the section, two diferent description details ("dd"), and a "footer" including a "nav" to acces related terms.

```html
<pre>
<dl>
  <section>
    <header>noun</header>
    <dt>gait</dt>
    <dd>a particular way of walking</dd>
    <dd>the particular way a horse walks or runs</dd>
    <footer>
      <nav>
        <a href="#">Walking and walkers</a>
        <a href="#">Horse riding</a>
      </nav>
    </footer>
  </section>
</dl>
</pre>
```

:smiley:

#### Specific section or headline?
HTML specification

#### What did you expect to see?

The code usually is correctly rendered and displayed, but it is detected as an incorrect html structure on any syntax check.

#### Did you test this? If so, how?

W3C validation. Using "div" tag is allowed inside "dl" list, but then header and footer tags have to be "definition details", breaking the semantic meaning.

<details>
<summary>Page report details</summary>

* Folder: `es/web/html/element/section`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Element/section
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/html/element/section/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b7d7c41df1866896a99a27b26514760cc24dddde
* Document last modified: 2022-05-05T16:43:39.000Z

</details>

**Comment by marcelozarate** [comment]
Thanks for suggesting this, unfortunately this is not the place for content issues like those, we merely translate to `es` and correct inconsistencies between the official docs and localized ones. You should 
[open an issue on MDN/content](https://github.com/mdn/content/issues/new/choose)
