### ISSUE TITLE
Issue with "Категории контента": small typo

### ISSUE THREAD

**Issue by cy66a** [mdn/translated-content#6240]
MDN URL: https://developer.mozilla.org/ru/docs/Web/Guide/HTML/Content_categories

#### What information was incorrect, unhelpful, or incomplete?
К интерактивному контенту относятся элементы, которЫЕ...

#### Specific section or headline?
#интерактивный_контент

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/web/guide/html/content_categories`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/Guide/HTML/Content_categories
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/guide/html/content_categories/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1386fed7d38652d5848d315927e7e23a66cffd13
* Document last modified: 2021-10-20T10:28:52.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17389 :ok_hand: 

Thank you! :+1:
