### ISSUE TITLE
Global Objects - Symbol [ES]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#6249]
Dentro de la categoria `web/javascript/reference/global_objects/symbol` tenemos muchos documentos que no existen @Jalkhov se propuso para agregarlos a la documentación en español, así que trataremos de tenerlos registrados en este issue.

> Nota: existen algunas páginas de la lista que Jalkhov ya las realizó. (Jalkhov si tienes tiempo, podrias marcarlas como hechas chequeandolas y de ser posible aun mejor relacionandolas). 

- [x] https://github.com/mdn/translated-content/pull/6001
- [x] https://github.com/mdn/translated-content/pull/6076
- [x] https://github.com/mdn/translated-content/pull/6165
- [x] https://github.com/mdn/translated-content/pull/6195
- [x] https://github.com/mdn/translated-content/pull/6210
- [x] https://github.com/mdn/translated-content/pull/6213
- [x] #6250
- [x] #6252
- [x] #6695
- [x] #6702
- [x] #6796
- [x] #6845
- [x] #6866
- [x] #6884
- [x] #6940
- [x] #6971
- [x] #6973
- [x] #6975 (Eliminada)
- [x] #6996
- [x] #6998
- [x] #7025
- [x] #7027

**Comment by JuanVqz** [comment]
@Jalkhov puedes crear issues rapidamente con este boton 
![image](https://user-images.githubusercontent.com/7331511/173367586-6fd10b69-3452-4739-aeb1-73e0dd6d569d.png)

y no olvides colocarle la etiqueta `I10n-es`, por favor :pray: 

Muchas gracias!!

**Comment by Jalkhov** [comment]
> @Jalkhov puedes crear issues rapidamente con este boton ![image](https://user-images.githubusercontent.com/7331511/173367586-6fd10b69-3452-4739-aeb1-73e0dd6d569d.png)
> 
> y no olvides colocarle la etiqueta `I10n-es`, por favor 🙏
> 
> Muchas gracias!!

Sencillamente perfecto, comprendido.

**Comment by JuanVqz** [comment]
@Jalkhov cualquier pregunta con gusto la resolvemos por este medio

**Comment by Jalkhov** [comment]
Esto puede darse por terminado <3 @JuanVqz

**Comment by JuanVqz** [comment]
> Esto puede darse por terminado <3 @JuanVqz

Gracias @Jalkhov creo que seria bueno agregar el SHA a todas estas paginas, te gustaria hacerlo? en otro issue o aqui mismo?

**Comment by Jalkhov** [comment]
> Gracias @Jalkhov creo que seria bueno agregar el SHA a todas estas paginas, te gustaria hacerlo? en otro issue o aqui mismo?

Justo eso estaba pensando. Creo que puedo usar este mismo issue, y solo le comento al lado (SHA Agregado) o no se que se te ocurre a tí.

**Comment by JuanVqz** [comment]
> > Gracias @Jalkhov creo que seria bueno agregar el SHA a todas estas paginas, te gustaria hacerlo? en otro issue o aqui mismo?
> 
> Justo eso estaba pensando. Creo que puedo usar este mismo issue, y solo le comento al lado (SHA Agregado) o no se que se te ocurre a tí.

si completamente de acuerdo!

**Comment by JuanVqz** [comment]
@Jalkhov :1st_place_medal: 
![Muchas Gracias](https://media.giphy.com/media/lZKxVLKam8SssgY5SG/giphy.gif)

**Comment by JuanVqz** [comment]
@Jalkhov podrías abundar en la descripción por que fue eliminado este https://github.com/mdn/translated-content/issues/6975

para futura referenica. :pray:
