### ISSUE TITLE
Issue with "客户端框架介绍": (short summary here please)

### ISSUE THREAD

**Issue by algbrag** [mdn/translated-content#6269]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction

#### What information was incorrect, unhelpful, or incomplete?
The details are not be translated.

#### What did you expect to see?
The update of this ariticle. 

#### Did you test this? If so, how?

ALL I want to do is to show thanks to the translator.Thank you so much. If this post voliate the rules in forum,please delete it. LOVE YOU!

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/introduction`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/introduction/index.html
* Last commit: https://github.com/mdn/translated-content/commit/4f4c5edc1a315a4d929173164391c669417cddc1
* Document last modified: 2022-06-07T12:35:36.000Z

</details>

**Comment by awxiaoxian2020** [comment]
@bill0871 @yin1999 @algbrag I add some translations in #7122
