### ISSUE TITLE
Remove `exception` in `es` locale

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#6333]
Remove `exception` macro in `es` locale and update content/format for:

- [x] #9924
  - [x]  Remover macro
  - [x] Convertir a `md`
- [x] #9925
  - [x]  Remover macro
  - [x] Convertir a `md`

**Comment by Graywolf9** [comment]
Macro removed in #6330. Still pending update content and format

**Comment by JuanVqz** [comment]
Addressed here #6330

**Comment by Graywolf9** [comment]
Opened issues to update the content and closing this to avoid missunderstood
