### ISSUE TITLE
Removal of {{ifattribute}} and {{ifmethod}} macros [ES]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#6337]
{{ifmethod}} has only few occurrences left:

- [x] #6338
- [x] #6339
- [x] #6340
- [x] #6341

{{ifattribute}}:

- [x] #6343

{{ifmethod}} and {{ifattribute}}:

- [x] #6342

Related to: https://github.com/orgs/mdn/discussions/67 and https://github.com/mdn/yari/pull/6205

**Comment by JuanVqz** [comment]
@mdn/yari-content-es I'll pick the first one (alert page)

**Comment by JuanVqz** [comment]
@mdn/yari-content-es I did `ifattribute` #6343

**Comment by JuanVqz** [comment]
@mdn/yari-content-es I'll pick https://github.com/mdn/translated-content/issues/6341

**Comment by JuanVqz** [comment]
@mdn/yari-content-es Haré #6339

**Comment by JuanVqz** [comment]
@mdn/yari-content-es ya solo falta https://github.com/mdn/translated-content/issues/6342

**Comment by hectormoba** [comment]
@JuanVqz! Tomo el primero de la lista! #6338. Me lo asignas?

**Comment by JuanVqz** [comment]
> @JuanVqz! Tomo el primero de la lista! #6338. Me lo asignas? 

Ya lo hice, por favor checa cuál fslta no estoy en la pc

**Comment by hectormoba** [comment]
Al estar abierto de nuevo, pensé que no se había finalizado. Me quedo con el último pues #6342
