### ISSUE TITLE
files/es/mozilla/firefox/releases/9/updating_add-ons/index.html

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#6342]

**Comment by JuanVqz** [comment]
> My bad @JuanVqz! Listo para seguir avanzando

Hey @hectormoba, estas ya trabajando en este issue? 
saludos

**Comment by hectormoba** [comment]
@JuanVqz entre hoy y mañana lo empiezo 🙌🏻

**Comment by JuanVqz** [comment]
> > @JuanVqz entre hoy y mañana lo empiezo 🙌🏻
> 
> Excelente! gracias rocket

Hola @hectormoba como estas? solo dando seguimiento al issue, todo bien? alguna duda? podrias por favor subir los cambios que tienes hasta ahora? (no te presiones)

Saludos!

**Comment by hectormoba** [comment]
> 

Ahí la dejé lista. Perdón, me había olvidado. Fíjate si hay algunas cosas que corregir, porque hay algunas tecnicismos que se escapan a mi lenguaje técnico habitual.

**Comment by JuanVqz** [comment]
> > 
> 
> Ahí la dejé lista. Perdón, me había olvidado. Fíjate si hay algunas cosas que corregir, porque hay algunas tecnicismos que se escapan a mi lenguaje técnico habitual.

Hola @hectormoba, @Jalkhov realizó la revisión, podrías revisar las sugerencias por favor :+1: gracias
