### ISSUE TITLE
Content issue: Orthographic errors

### ISSUE THREAD

**Issue by jlorenzoC** [mdn/translated-content#637]
### What page(s) did you find the problem on?
https://developer.mozilla.org/es/docs/Web/HTML/Global_attributes/hidden

1. There are extra spaces before punctuation marks _(signposted in the photo below with the red lines and arrows)_. This extra space shouldn't exist before any punctuation mark, only after.
2. Instead ~_pudera_~, write _pudiera_. The i letter is missing.
3. I think there should exist a comma where i mark comma with the arrow in the photo below, after the word _estilo_.
4. The word ~_mostrandolos_~ near to the end of the second paragraph, should be accentuated at the a letter: _mostrándolos_.

![image](https://user-images.githubusercontent.com/43883758/115974843-bd1f7980-a52d-11eb-9c3f-82076d6ba4e5.png)

5. In the photo bellow, the word _Por_ is misspelled. It should be _Por_, not ~_For_~. And also occurs the same of the point 1.

![image](https://user-images.githubusercontent.com/43883758/115975389-6d8f7c80-a532-11eb-81fd-248aa5fa46bc.png)

**Comment by SphinxKnight** [comment]
Sorry @jlorenzoC but this locale is currently frozen and changes/fixes are not currently accepted. Please see https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ and [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo.
