### ISSUE TITLE
Issue with "HTML: Linguagem de Marcação de Hipertexto": (short summary here please)

### ISSUE THREAD

**Issue by FlavioHCA** [mdn/translated-content#6378]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTML

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/html`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTML
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/html/index.html
* Last commit: https://github.com/mdn/translated-content/commit/7bc6744472098eaaea483f07b30c93460ab34f5f
* Document last modified: 2021-11-07T12:48:10.000Z

</details>

**Comment by yin1999** [comment]
I'm going to close this because no information was provided. Please provide more infomation about this and we can reopen it :)
