### ISSUE TITLE
Remove DOMO word from es 

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#6385]
I didn't find the DOMO macro, this was the only coincidence I found within the DOMO word into files/es/

**Comment by cw118** [comment]
I believe it's DOM0 with a zero and not the letter O :)

**Comment by JuanVqz** [comment]
Let me search for it, I was just writing in the discussion I didn't find anything related to DOMO :).

Thank you @cw118, you are the best!

**Comment by JuanVqz** [comment]
That's true there is one coincidence with DOM0 (whit zero), already removed in the same PR. Thank you @cw118 anyway
