### ISSUE TITLE
Mistake in french translation

### ISSUE THREAD

**Issue by cryptrz** [mdn/translated-content#6409]
## What page(s) did you find the problem on?

https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Access-Control-Request-Headers

## Specific page section or heading?

Introduction

## What is the problem?

It's written "et faite vers le serveur" instead of "est faite vers le serveur"

## What did you expect to see?

"est faite vers le serveur"

## Did you test this? If so, how?

![mdn](https://user-images.githubusercontent.com/68272257/174543379-e5c9c495-1cb5-463c-aa89-2f427a2520d0.png)

**Comment by SphinxKnight** [comment]
Merci pour ce rapport et les informations détaillées @cryptrz, j'ai ouvert une PR pour corriger ça :)
