### ISSUE TITLE
Issue with "Использование геолокации": (short summary here please)

### ISSUE THREAD

**Issue by DaniilPo** [mdn/translated-content#6422]
MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Geolocation_API

#### What information was incorrect, unhelpful, or incomplete?
How fast can you receive data?

#### Specific section or headline?
Geolocation.watchPosition()

#### What did you expect to see?

I want to understand how fast it is possible to receive data and what it depends on
#### Did you test this? If so, how?
i tried to change the settings but no matter what the changes were, i could not receive data more often than once every 5 seconds
it is very interesting why this is so and is it possible to receive data, for example, once every 1 second

<details>
<summary>Page report details</summary>

* Folder: `ru/web/api/geolocation_api`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/API/Geolocation_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/api/geolocation_api/index.html
* Last commit: https://github.com/mdn/translated-content/commit/f3abb48a00c8c813e6b1bc8fee19e6b4c0414ce9
* Document last modified: 2021-10-25T07:06:22.000Z

</details>

**Comment by cw118** [comment]
Hi @DaniilPo, could you please specify what issues you faced with this MDN page? The `translated-content` repository is unfortunately not for asking code questions, please consider asking for help at the [MDN discourse learning community](https://discourse.mozilla.org/c/mdn/learn/250) instead.

**Comment by cw118** [comment]
I am closing this for the reasons given in my previous comment. If I misunderstood and there is a problem with the Использование геолокации page on MDN, please let me know and we can reopen this :)
