### ISSUE TITLE
Update ./files/es/web/http/cors/index.md

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#6440]
Actualizar contenido: cors

**Comment by EnriqueSource** [comment]
actualizando

**Comment by EnriqueSource** [comment]
Debido a la longitud del archivo (más de 500 lineas) he decidido dividir los PR's, en lugar de enviar uno solo con todo terminado. Creo que de ese modo se facilita tanto la traducción como la revisión. La división se hará en base a los encabezados del markdown original.
