### ISSUE TITLE
Update ./files/es/web/api/setinterval/index.md

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#6441]
Actualizar contenido: setinterval

**Comment by EnriqueSource** [comment]
Hola Graywolf9. Me ofrezco a actualizar y pasar a .md este artículo. ¿Puedes asignarlo?

**Comment by Graywolf9** [comment]
Asignado @EnriqueSource muchas gracias por tu ayuda

**Comment by JuanVqz** [comment]
Hola @EnriqueSource, como estas? estoy dando seguimiento al issue, como te va en la traduccion? tienes dudas? cualquier cosa pregunta por este medio, saludos!

**Comment by EnriqueSource** [comment]
Hola Juan. Me alegra que me escribas. Estoy trabajando en la traducción. Entre que ando algo liado y que la traducción es larga, me llevará algo más de tiempo terminarla, pero no mucho. Aprovecho este canal para preguntarte algo:

- Los "tags" al inicio del documento no se incluyen en la traducción, ¿cierto?

- Me he dado cuenta de que en el documento alojado en mdn, una vez que se ha realizado el "pull request", cuando pinchas en el enlace de "última modificación" te lleva a una lista de últimos commits. En dicha lista no aparecen los commits hechos por nosotros, es decir los commits de las traducciones.

Por otro lado, mientras se está traduciendo, si pinchas en dicho link desde el entorno de ejecución local te devuelve el siguiente mensaje: " Error: 404 on /es/docs/Web/API/setInterval/<http://contributors.txt/index.json>: Page not found".

La pregunta es ¿Deberíamos nosotros incluir ese archivo "contributors.txt" al directorio donde se aloja el nuevo "archivo.md" traducido, e incluir en él nuestros nombres como contribuyentes?.

Muchas gracias de antemano.

Un saludo.

**Comment by EnriqueSource** [comment]
Hola @JuanVqz . He enviado un PR temporal para que le eches un vistazo y me digas cualquier fallo. Este finde tengo algo más de tiempo y lo completo.El domingo lo envío finalizado. Un saludo
