### ISSUE TITLE
Content bug: Missing page Namespace [es]

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#6472]
## What page(s) did you find the problem on?

https://developer.mozilla.org/es/docs/Glossary/Namespace

## Specific page section or heading?

Entire page

## What is the problem?

Page not found

## What did you expect to see?

https://developer.mozilla.org/en-US/docs/Glossary/Namespace in `es` locale

## Did you test this? If so, how?

looking at: https://developer.mozilla.org/es/docs/Glossary/Namespace

**Comment by Yareaj** [comment]
@Graywolf9 quiero tomar este issue

**Comment by Graywolf9** [comment]
Excelente, ya te lo he asignado, muchas gracias!

**Comment by Yareaj** [comment]
@Graywolf9 pull request creada ^_^
