### ISSUE TITLE
 Is there an automated synchronization mechanism between `content` and `translated-content` ?

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/translated-content#6499]
like https://github.com/mdn/translated-content/issues/904#issuecomment-862405188 , when `content` updates, It seems that we must notice it by contributors or users. If nobody notice it, We will only find out that `translated content` is not synced with `content` when we have a problem. 

 Is there an automated synchronization mechanism between `content` and `translated-content`? For example, when `content` updates, there is a script or github action to post a new issue to indicate we need to work on updating translation.

**Comment by yin1999** [comment]
discuessed here: <https://github.com/orgs/mdn/discussions/129>.

And for now, we can use locale dashboard (#2619):

after running `yarn start`, open `http://localhost:5042/zh-CN/_translations/differences`

![image](https://user-images.githubusercontent.com/15844309/175813954-f331b061-7353-4016-966f-fb48d90d7ba9.png)

**Comment by awxiaoxian2020** [comment]
> discuessed here: https://github.com/orgs/mdn/discussions/129.
> 
> And for now, we can use locale dashboard (#2619):
> 
> after running `yarn start`, open `http://localhost:5042/zh-CN/_translations/differences`
> 
> ![image](https://user-images.githubusercontent.com/15844309/175813954-f331b061-7353-4016-966f-fb48d90d7ba9.png)

Thanks, as there is a discussion, I also have no better ideas about it, so I close the issue temporarily.

**Comment by awxiaoxian2020** [comment]
> discuessed here: https://github.com/orgs/mdn/discussions/129.
> 
> And for now, we can use locale dashboard (#2619):
> 
> after running `yarn start`, open `http://localhost:5042/zh-CN/_translations/differences`
> 
> ![image](https://user-images.githubusercontent.com/15844309/175813954-f331b061-7353-4016-966f-fb48d90d7ba9.png)

How should I set the .env file to show this page?
