### ISSUE TITLE
Issue with "Clipboard": (short summary here please)

### ISSUE THREAD

**Issue by SystemLight** [mdn/translated-content#6500]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Clipboard

#### What information was incorrect, unhelpful, or incomplete?
`Clipboard. The read() ` method actually returns the `clipboarditem[]` instead of the `datatransfer` object, which is inconsistent with the English document

#### What did you expect to see?
Correct or explain the problem

#### Did you test this? If so, how?
Yes, it does return 'clipboarditem[]` on 'chromeV102'

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/clipboard`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Clipboard
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/clipboard/index.md
* Last commit: https://github.com/mdn/translated-content/commit/7f8fe7408797b775ddd9f1633c14547836ba34d6
* Document last modified: 2022-05-31T18:54:08.000Z

</details>

**Comment by yin1999** [comment]
fixed in 0ee8f20
