### ISSUE TITLE
Issue with "Qu'est-ce que les WebExtensions ?": (short summary here please)

### ISSUE THREAD

**Issue by stephane484** [mdn/translated-content#6501]
MDN URL: https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/mozilla/add-ons/webextensions/what_are_webextensions`
* MDN URL: https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/mozilla/add-ons/webextensions/what_are_webextensions/index.md
* Last commit: https://github.com/mdn/translated-content/commit/fe25612ce6631daf3afc04ba638a48856692c1d5
* Document last modified: 2022-06-18T09:04:02.000Z

</details>

**Comment by SphinxKnight** [comment]
Hello @stephane484, could you please give us more information about what needs to be fixed here?

**Comment by SphinxKnight** [comment]
I'm closing this one due to lack of details. We'll reopen it if information is provided.
