### ISSUE TITLE
HTML basics 노트 누락 및 번역 수정

### ISSUE THREAD

**Issue by SnowMarble** [mdn/translated-content#6534]
## What page(s) did you find the problem on?

https://developer.mozilla.org/ko/docs/Learn/Getting_started_with_the_web/HTML_basics

## Specific page section or heading?

1. [HTML 요소 분석](https://developer.mozilla.org/ko/docs/Learn/Getting_started_with_the_web/HTML_basics#html_%EC%9A%94%EC%86%8C_%EB%B6%84%EC%84%9D)
2. [제목](https://developer.mozilla.org/ko/docs/Learn/Getting_started_with_the_web/HTML_basics#%EC%A0%9C%EB%AA%A9)
3. [이번 모듈에서는](https://developer.mozilla.org/ko/docs/Learn/Getting_started_with_the_web/HTML_basics#%EC%9D%B4%EB%B2%88_%EB%AA%A8%EB%93%88%EC%97%90%EC%84%9C%EB%8A%94)

## What did you expect to see?

1.
![image](https://user-images.githubusercontent.com/69508345/175951988-cb3cb1d9-4f26-47c9-a364-89db267be99d.png)

2.
![image](https://user-images.githubusercontent.com/69508345/175952046-83b9da3c-f4cf-46a3-bb59-114c18dae6fa.png)

3. [공통 용어](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EA%B3%B5%ED%86%B5-%EC%9A%A9%EC%96%B4)의 `Module` 항목에 기반하여 번역 수정이 필요해 보입니다.
> 어떠한 교육 과정, 단위에 의한 표현은 '과정'으로 번역한다. (예: In this module)

**Comment by kraccoon-dev** [comment]
2번째 사진에서 예제코드도 수정이 필요해 보입니다.
![image](https://user-images.githubusercontent.com/69508345/176422021-32d91391-5248-431e-b844-bea825c9431a.png)

**Comment by ProHC** [comment]
@mdn/yari-content-ko
