### ISSUE TITLE
Remove unwanted macros [ES]

### ISSUE THREAD

**Issue by JuanVqz** [mdn/translated-content#6554]
@todomagichere hizo una busqueda en los archivos en español y notó que existen `193` archivos los cuales tienen una o mas `macros` relacionadas y las macros totales a remover son `290`, tomando esa información seria genial que la pudieras detallar en esta descripción archivo por archivo 

@todomagichere como buscaste esas coincidencias? tienes una lista de los documentos relacionados? podrías editar esta descripción y agregarla por macro por favor?

- [x] `fx_minversion_header`
- [x] `fx_minversion_inline`
- [x] #6752
- [x] #6754
- [x] #6756
- [x] #6562

Related  #4579

Links: https://github.com/mdn/translated-content/issues/4579#issuecomment-1168784611

**Comment by JuanVqz** [comment]
No existen preguntas tontas, solo tontos que no preguntan.

1. borra todo y el espacio:

```md
texto texto

<p>{{gecko_minversion_header("2")}}</p>

texto texto
```

despues de remover la macro debe quedar

```md
texto texto

texto texto
```

2. el resultado seria `<div>{{APIRef("DOM")}}</div>`

3.  el resultado seria `<div>{{Non-standard_header}}{{CSSRef}}</div>`

Si tienes dudas mientras lo estas haciendo con gusto por aca mismo puedes preguntar.

Te lo asigné, gracias por enorme aporte!

**Comment by JuanVqz** [comment]
@todomagichere ya copie la lista que publicaste en la descripción si gustas borrarla estaría bien, y coloque checks por toda la sección así podremos saber como van tus avances, esta bien?

**Comment by todomagichere** [comment]
@Graywolf9 por favor, ¿podrías mostrarme las desviaciones? Analizando todo el contenido en un principio consideraba eliminar las macros mediante regex, pero en la sustitución quedarían tags y líneas vacías. Así pues estoy de acuerdo en eliminarlo de forma manual macro por macro.

**Comment by Graywolf9** [comment]
Hola! @todomagichere un ejemplo es en `languages` que es la que ya llevaba seguimiento, tienes 121 coincidencias y en el issue entre la comunidad y la revisión que hice aparecen 125. Por la parte de la sustitución al ya no ser un lenguaje inactivo es bueno procurar que no quede simplemente vacío si no poner a mano el contenido que esta rendereando la macro. 

Por otra parte el español acaba de ser reactivado y solo llevamos el 1.7% de páginas actualizadas por lo que hay más prioridad en actualizar ya que lleva de 2 a 5 años de desactualización, el avance lo puedes ver aquí o en un entorno local: https://github.com/mdn/translated-content/discussions/4029

**Comment by todomagichere** [comment]
Buenas @Graywolf9,  en el caso de `languages` al hacer pull y buscar las referencias ahora me encuentro con 126 coincidencias, parece que va variando según las ediciones. Entonces eliminar las macros pasa a segundo plano ya que la mayoría están en documentos html y centraré la atención en las traducciones. 

Saludos!

**Comment by Graywolf9** [comment]
Muchas gracias por tu tiempo, atención y contribuciones @todomagichere !

**Comment by Graywolf9** [comment]
Hola a todos!

Debido a la reciente migración de `html` a `md` cambiaron algunas prioridades y estas macros fueron atendidas con ayuda de la comunidad

Cada macro fue hecha por lotes de 100 archivos aproximadamente y revisado de forma manual

revisando con: 

```
rg -i "\{\{\s?(fx_minversion_header|fx_minversion_inline|gecko_minversion_header|gecko_minversion_inline|IncludeSubnav|languages)"
```

arroja 0 resultados

- `gecko_minversion_header`: https://github.com/mdn/translated-content/pull/9609
- `gecko_minversion_inline`: https://github.com/mdn/translated-content/pull/9639
- `IncludeSubnav`: https://github.com/mdn/translated-content/pull/9214
- `languages`: removed with the markdown conversion
