### ISSUE TITLE
1 file for `es` Update content and remove `gecko_callout_heading` macro [es]

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#6563]
Actualizar contenido y formato así como remover la referencia a la macro `gecko_callout_heading`

- [ ] ./mdn/structures/macros/other/index.html

Relacionado con #5603

**Comment by todomagichere** [comment]
@Graywolf9 por lo que veo este fichero el objetivo es este:
`{{TemplateLink("gecko_callout_heading")}}`

¿La macro, en este caso no sería TemplateLink?
