### ISSUE TITLE
"Glossary" word translation

### ISSUE THREAD

**Issue by mpstv** [mdn/translated-content#657]
У нас везде (по крайней мере в соответсвующем разделе) фигурирует перевод `Glossary` -> `Словарь`.

Может бысть стоит его изменить на `Глоссарий` ? Мне кажется, для перевода `Словарь`  больше подходит слово `Dictionary`.

Что думаете? @myshov @lex111 @sashasushko @Saionaro @armanpwnz @captainspring

**Comment by captainspring** [comment]
Учитывая, что глоссарий — это обычно словарь именно узкоспециализированных терминов, в этом есть смысл. Я за.

**Comment by sashasushko** [comment]
За.

**Comment by Saionaro** [comment]
+1. Верное замечание

**Comment by myshov** [comment]
+1, согласен
