### ISSUE TITLE
Russian language team's response time is delayed

### ISSUE THREAD

**Issue by DmitrySkripunov** [mdn/translated-content#6581]
Hello, looks like there is no one accessable in Russian language team. I made a PR, wrote to a matrix chat and mentioned russian translates reviewers.
No one answer.
So, is there some way either ping those guys or create a new team maybe?

**Comment by cw118** [comment]
Hi @DmitrySkripunov, could you please specify which PR(s) are affected? I can try to ping them for you there. Please also understand that all translated-content team members are volunteers, so the Russian team may simply be busy with other work :)

**Comment by DmitrySkripunov** [comment]
@cw118 hello!
https://github.com/mdn/translated-content/pull/6414

Yes, I understand it))
I want just to know that they are still with us, just a little message)

**Comment by DmitrySkripunov** [comment]
Thank you very much, @cw118 !
