### ISSUE TITLE
Issue with "Math.random()": (short summary here please)

### ISSUE THREAD

**Issue by mkose3** [mdn/translated-content#6589]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/random

#### What information was incorrect, unhelpful, or incomplete?

функция генерирует массив на N рандомных чисел в диапазоне от A до B и возвращает его  // Т.е. принимает 3 параметра и А не может быть больше чем B

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/global_objects/math/random`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Math/random
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/global_objects/math/random/index.html
* Last commit: https://github.com/mdn/translated-content/commit/6e9fe98036090a37cc6247b873845505e5b512fb
* Document last modified: 2022-02-22T09:49:36.000Z

</details>

**Comment by cw118** [comment]
Hi @mkose3, could you please provide more details (e.g. the section/headline, how this issue can/should be fixed, etc.) so that maintainers/contributors can resolve this issue more easily?

**Comment by leon-win** [comment]
To be honest, I didn’t understand what the problem was))

But I updated the page translation according to `en-US` version in #17414 :ok_hand:
