### ISSUE TITLE
Issue with "Using promises": (korean typo)

### ISSUE THREAD

**Issue by f2janyway** [mdn/translated-content#659]
URL = [https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Using_promises](https://developer.mozilla.org/ko/docs/Web/JavaScript/Guide/Using_promises)

콜백들을 전달지 않고 -> 콜백들을 전달하지 않고

**Comment by hochan222** [comment]
@f2janyway PR 올리실 계획이 있으신가요?

**Comment by f2janyway** [comment]
아니요.

2021년 4월 29일 (목) 오후 5:59, hochan Lee ***@***.***>님이 작성:

**Comment by hochan222** [comment]
@f2janyway 알려주셔서 감사합니다. 좋은 하루 보내세요 :)
