### ISSUE TITLE
Chore: repository branches

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#6627]
I'm opening this one to check if branches on this repository itself (i.e. not on forks) may be removed. I'll exclude dependabot branches and the most recent one.

On https://github.com/mdn/translated-content/branches/all, here is the current list (there are no opened PRs linked to them)

- https://github.com/mdn/translated-content/tree/20220521 @hmatrjp 
- https://github.com/mdn/translated-content/tree/revert-5138-ko_Set_values @yechoi42 
- https://github.com/mdn/translated-content/tree/Rumyra-patch-2 @Rumyra 
- https://github.com/mdn/translated-content/tree/revert-2234-20210827-Global_Objects/Promise/allSettled @mfuji09 

If there is a use case where some branches need to stay as is, let me know, I don't mind keeping them if they're useful ^^

**Comment by mfuji09** [comment]
@SphinxKnight 
It is safe to remove https://github.com/mdn/translated-content/tree/revert-2234-20210827-Global_Objects/Promise/allSettled . Thank you!

**Comment by SphinxKnight** [comment]
> @SphinxKnight It is safe to remove https://github.com/mdn/translated-content/tree/revert-2234-20210827-Global_Objects/Promise/allSettled . Thank you!

done, thanks!

**Comment by Rumyra** [comment]
Safe to delete https://github.com/mdn/translated-content/tree/Rumyra-patch-2 :) Thanks @SphinxKnight

**Comment by SphinxKnight** [comment]
> Safe to delete https://github.com/mdn/translated-content/tree/Rumyra-patch-2 :) Thanks @SphinxKnight

Thanks! done :)

**Comment by yechoi42** [comment]
Safe to delete https://github.com/mdn/translated-content/tree/revert-5138-ko_Set_values .Thank you @SphinxKnight

**Comment by SphinxKnight** [comment]
> @hmatrjp could you have a look at https://github.com/mdn/translated-content/tree/20220521 please?

I deleted this one.
