### ISSUE TITLE
keyfor [es]

### ISSUE THREAD

**Issue by Jalkhov** [mdn/translated-content#6695]
- [x] Actualizar contenido 
- [x] Actualizar formato de HTML a MD
- [x] Remover las etiquetas

**Comment by KevinMorales0** [comment]
Hola.
Quiero tomar esta issue.
Es mi primera contribución, ¿algun consejo para novatos?.

**Comment by Jalkhov** [comment]
Hola @KevinMorales0 muchas gracias por tu interés en colaborar. Más que un consejo para novato voy a pasarte las instrucciones para que puedas comenzar a contribuir, checa [esta discusión](https://github.com/mdn/translated-content/discussions/4029), debería cubrir todas tus dudas, de todas maneras comenta por acá alguna inquietud y responderemos a la brevedad.

**Comment by KevinMorales0** [comment]
Muchas gracias @Jalkhov, me fue muy util toda la información.
