### ISSUE TITLE
Issue with "Intersection Observer API": (short summary here please)

### ISSUE THREAD

**Issue by karastras** [mdn/translated-content#670]
MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Intersection_Observer_API

#### What information was incorrect, unhelpful, or incomplete?

At the end of the docs, the last exemple, "the Result" don't work correctly, I scroll the box but there is no changes. 

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/web/api/intersection_observer_api`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Intersection_Observer_API
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/intersection_observer_api/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a1711eaef7357451a07140b41bb970bc3c0e0ccb
* Document last modified: 2021-04-27T00:11:20.000Z

</details>

**Comment by SphinxKnight** [comment]
@karastras thanks for the report. For this example, this is not the box that needs scrolling but the page itself.
As far as I can tell, the English page (which acts as a reference for this one in French) is behaving similarly.

Here is what I get for different levels of scrolling. Let me know if this does not sound ok to you.
![image](https://user-images.githubusercontent.com/2413436/116505503-5eeeef80-a8bb-11eb-8342-d9679c894d91.png)
![image](https://user-images.githubusercontent.com/2413436/116505515-66ae9400-a8bb-11eb-8413-e9feebd9f466.png)
![image](https://user-images.githubusercontent.com/2413436/116505519-6adab180-a8bb-11eb-845d-5dbf0c6f9ecd.png)

**Comment by SphinxKnight** [comment]
@karastras I'm waiting a few more days before closing this. Let us know if you think something is wrong/missing.

**Comment by karastras** [comment]
Oh ! ok !!!! realy thanks to you!
I need to read the description better before open an issue :) 
now the demonstration is clear, thanks to you ;)

**Comment by SphinxKnight** [comment]
@karastras no worries :) thanks for the confirmation.
