### ISSUE TITLE
Issue with "SVG In HTML Introduction": (short summary here please)

### ISSUE THREAD

**Issue by XJR9** [mdn/translated-content#6743]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial/SVG_In_HTML_Introduction

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/svg/tutorial/svg_in_html_introduction`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/SVG/Tutorial/SVG_In_HTML_Introduction
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/svg/tutorial/svg_in_html_introduction/index.html
* Last commit: https://github.com/mdn/translated-content/commit/c9c7394f2605839e2992b28d39ad3e05beaf1c81
* Document last modified: 2022-07-02T22:31:35.000Z

</details>

**Comment by SphinxKnight** [comment]
Could you please provide some more details about the issue you are facing so that we can help fixing it.
I'll close this for now but will reopen it, should information be added.
