### ISSUE TITLE
Issue with "Object.defineProperty()" [ru]

### ISSUE THREAD

**Issue by Dreamsthinker** [mdn/translated-content#6782]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

#### Specific section or headline?
[https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#example:_modifying_a_property](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#example:_modifying_a_property)

- `Если у старого дескриптора атрибут configurable был установлен в false (говорит, что свойство является «ненастраиваемым»), то никакие атрибуты, кроме атрибута writable, не смогут быть изменены. В этом случае так же невозможно переключаться между типами дескрипторов.`
- `При попытке изменить ненастраиваемые атрибуты свойства будет выброшено исключение [TypeError] (кроме случая изменения атрибута writable), даже в том случае, если текущее и новое значения идентичны.`

#### What did you expect to see?

- В случае, когда **configurable: _false_** И **writable: _true_**, менять МОЖНО **value** (сколько угодно раз, пока writable остается true) и **writable** (один раз - на false).
- При попытке изменить ненастраиваемые атрибуты свойства в том случае, когда текущее и новое значения идентичны, исключение [TypeError] будет выброшено только для ключей **get** и **set**.

#### Did you test this? If so, how?
Visual Studio Code 1.68.1
Google Chrome 103.0

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/global_objects/object/defineproperty`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/global_objects/object/defineproperty/index.html
* Last commit: https://github.com/mdn/translated-content/commit/09d10136633355937867a21d65db64ae3c4d5829
* Document last modified: 2021-10-27T15:02:34.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17407 :ok_hand: 

Thank you! :+1:
