### ISSUE TITLE
Update Web/CSS/height [es]

### ISSUE THREAD

**Issue by KevinMorales0** [mdn/translated-content#6800]
- [ ] Update content with English versión
- [ ] Convert to md

**Comment by EnriqueSource** [comment]
Hola @KevinMorales0. Me gustaría actualizar y convertir a md este artículo. ¿Puedes asignármelo?. Un saludo

**Comment by EnriqueSource** [comment]
Hola @JuanVqz . ¿Me lo asignas?

**Comment by JuanVqz** [comment]
> Hola @JuanVqz . ¿Me lo asignas?

Que tal @EnriqueSource asignado! gracias por tu apoyo :+1:

**Comment by EnriqueSource** [comment]
Gracias @JuanVqz
