### ISSUE TITLE
Content bug: {{csssyntax}} got error in -moz-float-edge [es]

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#6815]
## What page(s) did you find the problem on?

https://developer.mozilla.org/es/docs/Web/CSS/-moz-float-edge
https://developer.mozilla.org/fr/docs/Web/CSS/-moz-float-edge
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-float-edge
https://developer.mozilla.org/ja/docs/Web/CSS/-moz-float-edge

## Specific page section or heading?

[Síntaxis Formal](https://developer.mozilla.org/es/docs/Web/CSS/-moz-float-edge#s%C3%ADntaxis_formal)

## What is the problem?

Error: could not find syntax for this item

## What did you expect to see?

Content about the heading

## Did you test this? If so, how?

looking at the pages
https://developer.mozilla.org/es/docs/Web/CSS/-moz-float-edge
https://developer.mozilla.org/fr/docs/Web/CSS/-moz-float-edge
https://developer.mozilla.org/en-US/docs/Web/CSS/-moz-float-edge
https://developer.mozilla.org/ja/docs/Web/CSS/-moz-float-edge

**Comment by VladiStep** [comment]
The same issue on this page - https://developer.mozilla.org/ru/docs/Web/CSS/overscroll-behavior

**Comment by Graywolf9** [comment]
Filled an issue on content repo: https://github.com/mdn/content/issues/25321
