### ISSUE TITLE
Typo in "Intersection Observer API": … in "Intersection obserer の作成

### ISSUE THREAD

**Issue by gengokumura** [mdn/translated-content#682]
MDN URL: https://developer.mozilla.org/ja/docs/Web/API/Intersection_Observer_API

Intersection obserer の作成 → Intersection Observer の作成

**Comment by mfuji09** [comment]
以下の観点から、このままでよいと思います。
- 英語版でも Creating an intersection observer と小文字になっている
- スタイルガイドでも各単語の先頭を大文字にしないよう規定がある
 https://developer.mozilla.org/ja/docs/MDN/Guidelines/Writing_style_guide#page_title

**Comment by gengokumura** [comment]
小文字大文字もですが`obserer`とスペルミスかなと思いますがいかがでしょうか
