### ISSUE TITLE
Issue with "parseInt": (short summary here please)

### ISSUE THREAD

**Issue by gtchappy** [mdn/translated-content#6856]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/parseInt

#### What information was incorrect, unhelpful, or incomplete?

![Snipaste_2022-07-14_15-58-27](https://user-images.githubusercontent.com/105959932/178932139-1ddd1d27-2ffd-4d5f-995f-8e0bc1ab712f.png)

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/parseint`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/parseInt
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/parseint/index.html
* Last commit: https://github.com/mdn/translated-content/commit/681f172ec06d168a99387f8f83693e47ac1b8555
* Document last modified: 2022-05-29T08:32:17.000Z

</details>

**Comment by roberthuang1024** [comment]
<img width="202" alt="image" src="https://user-images.githubusercontent.com/54730911/178941515-5a5e6110-f6da-4ddc-9053-7e9e2bd5c649.png">

**Comment by cw118** [comment]
Hello, thank you for creating this issue!

`parseInt(021, 8)` does, in reality, result in `15` because JS parses `021` as an *octal number* instead of as a string:

```js
parseInt(021, 8); // equivalent to parseInt(17, 8); because the octal number 021 = the decimal number 17

parseInt('021', 8); // result is 17 because '021' is a string, so this converts the decimal number 021 to the octal number 17
```

I will close this because the example is correct. I hope this helps, don't hesitate if you would like to discuss :)
