### ISSUE TITLE
class static `Point.displayName` should be `Point.name`

### ISSUE THREAD

**Issue by flywxc** [mdn/translated-content#687]
https://github.com/mdn/translated-content/blob/dcb7bc53bcf4471294790c22a8276bc1f846357a/files/zh-cn/web/javascript/reference/classes/index.html#L136

 `Point.displayName` should be `Point.name`

**Comment by yin1999** [comment]
This example shows that the `Static methods and properties` **cannot** be called through a class instance. `Point.displayName` is defined in the class `Point` as a static property.

So I think there is nothing need to be modified.

**Comment by cw118** [comment]
I agree with @yin1999 (thanks for this :)), the line mentioned here is part of the static methods/properties example so it makes sense for the static property (here it's `displayName`, which was defined for/in `class Point` using `static displayName = "Point";`) to be called on the class (`Point`).

(cf. [the full `Point` class with `static` methods and properties defined in the MDN example](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Classes#%E9%9D%99%E6%80%81%E6%96%B9%E6%B3%95))
