### ISSUE TITLE
please fix invalid image link.

### ISSUE THREAD

**Issue by Alkaidcc** [mdn/translated-content#6900]
https://github.com/mdn/translated-content/blob/c2341343b763d1d2064df3c4f4317b4972087697/files/zh-cn/learn/forms/form_validation/index.html#L379

`/files/4329/error-firefox-win7.png` is an invalid path and can not load image assets successfully.

**Comment by Alkaidcc** [comment]
https://github.com/mdn/translated-content/blob/c2341343b763d1d2064df3c4f4317b4972087697/files/zh-cn/learn/forms/form_validation/index.html#L383
and
https://github.com/mdn/translated-content/blob/c2341343b763d1d2064df3c4f4317b4972087697/files/zh-cn/learn/forms/form_validation/index.html#L387
not working too.

**Comment by linlinzzo** [comment]
https://github.com/mdn/translated-content/blob/62c9022b4951f57a794ef82c074c037608520245/files/zh-cn/learn/getting_started_with_the_web/html_basics/index.html?plain=1#L34

**Comment by yin1999** [comment]
We have replaced a lot of `src`s in #6366. And now, we should try to sync all those documents which have broken images. To quickly find those documents. We can search `mdn.mozillademos.org` in `files/zh-cn`.

On linux we can use rg:

```bash
cd files/zh-cn
rg "mdn.mozillademos.org" -i -l
```
