### ISSUE TITLE
Content bug: `アセンブリの出力` 画像が無効に

### ISSUE THREAD

**Issue by chansuke** [mdn/translated-content#6919]
## What page(s) did you find the problem on?
https://developer.mozilla.org/ja/docs/WebAssembly/Text_format_to_wasm#viewing_the_assembly_output

## Specific page section or heading?

アセンブリの出力を見る

## What is the problem?

アセンブリ出力結果の画像のURLが無効になっています。

**Comment by potappo** [comment]
英語版の画像がデモサイトから MDN サイト下に移動したのが原因です。日本語版にも画像をコピーすべきですが、ひとまず、英語版の画像参照する対応を取りました。
