### ISSUE TITLE
'Looking to become a front-end web developer?' callout is not standardized

### ISSUE THREAD

**Issue by SnowMarble** [mdn/translated-content#6951]
아래 세 페이지 모두 'Looking to become a front-end web developer?' 콜아웃이 통일되지 않은 상태입니다.

https://developer.mozilla.org/ko/docs/Learn/JavaScript/First_steps
https://developer.mozilla.org/ko/docs/Learn/JavaScript/Building_blocks
https://developer.mozilla.org/ko/docs/Learn/JavaScript/Asynchronous

번역을 하나로 통일해야할 것 같습니다.

**Comment by hochan222** [comment]
@SnowMarble 님 사실 callout 규칙은 https://github.com/mdn/translated-content/issues/1042 에서 정해놨었는데 가이드에 추가하는것을 누락했습니다. 

추가하겠습니다. 감사합니다 :)
