### ISSUE TITLE
Issue with "CanvasRenderingContext2D.currentTransform": (short summary here please)

### ISSUE THREAD

**Issue by logWC** [mdn/translated-content#6963]
MDN URL: https://developer.mozilla.org/zh-CN/docs/conflicting/Web/API/CanvasRenderingContext2D

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/conflicting/web/api/canvasrenderingcontext2d`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/conflicting/Web/API/CanvasRenderingContext2D
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/conflicting/web/api/canvasrenderingcontext2d/index.html
* Last commit: https://github.com/mdn/translated-content/commit/e17124dbb539ada1c829d723ef1f2c91b3b4dbaf
* Document last modified: 2022-04-25T00:13:19.000Z

</details>

**Comment by cw118** [comment]
Closing as no information was provided. Please give more details on the issue and we can reopen if needed.
