### ISSUE TITLE
Issue with "Tutorial de Django Parte 8: Autenticación y permis…": broken images

### ISSUE THREAD

**Issue by augustofavrearg** [mdn/translated-content#6968]
MDN URL: https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Authentication

#### What information was incorrect, unhelpful, or incomplete?

Some of the images in the tutorial are broken, do not load

#### Specific section or headline?

Images: 3-4-5-6-7-13 ... and some more

#### What did you expect to see?

I hope I can see the images correctly

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/learn/server-side/django/authentication`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Authentication
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/server-side/django/authentication/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1109132f09d75da9a28b649c7677bb6ce07c40c0
* Document last modified: 2020-12-08T19:41:45.000Z

</details>

**Comment by Graywolf9** [comment]
Fixed in #10474
