### ISSUE TITLE
tosource [es]

### ISSUE THREAD

**Issue by Jalkhov** [mdn/translated-content#6975]

**Comment by Jalkhov** [comment]
@JuanVqz Esta sección no existe en la documentación oficial https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

**Comment by JuanVqz** [comment]
> @JuanVqz Esta sección no existe en la documentación oficial https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

no entiendo, te refieres a que no existe en español?

**Comment by Jalkhov** [comment]
> no entiendo, te refieres a que no existe en español?
No existe en inglés.

**Comment by cw118** [comment]
@Jalkhov Hello, I hope it's OK for me to jump in here :)

I tested the URL `https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/toSource` and I was redirected to the `toString` page, meaning that in en-US, the page `toSource` was deleted and redirected to `toString` some time ago (I also found this redirect `/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toSource	/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString`). 

So, I'd say you can simply translate `toString` for `es` and "ignore" `toSource` :)

**Comment by Graywolf9** [comment]
Closed due that the page was removed for `en-US`
