### ISSUE TITLE
Issue with "PushManager.subscribe()": 

### ISSUE THREAD

**Issue by fanfanlin** [mdn/translated-content#7040]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/PushManager/subscribe

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/pushmanager/subscribe`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/PushManager/subscribe
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/pushmanager/subscribe/index.html
* Last commit: https://github.com/mdn/translated-content/commit/f204f2ed74eaa7c05e73ba349e045619be1de1a9
* Document last modified: 2022-07-20T06:51:45.000Z

</details>

**Comment by SphinxKnight** [comment]
Please provide some more details about the issue you are facing so that we can help fixing it.
I'll close this for now but will reopen it, should information be added.
