### ISSUE TITLE
Issue with "let": (short summary here please)

### ISSUE THREAD

**Issue by pangxueming** [mdn/translated-content#7058]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Statements/let

#####

![image](https://user-images.githubusercontent.com/54926979/180347697-b5384653-de55-4001-bf54-0efd5922e492.png)

## 上面图片中的 '快内' 应该是 '块内'

**Comment by yin1999** [comment]
Thanks for raising this, I've created #7059 to fix it.
