### ISSUE TITLE
Issue with "Raison: la requête CORS a échoué": (short summary here please)

### ISSUE THREAD

**Issue by meroma1** [mdn/translated-content#7064]
MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/web/http/cors/errors/corsdidnotsucceed`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/http/cors/errors/corsdidnotsucceed/index.md
* Last commit: https://github.com/mdn/translated-content/commit/19cb4ddee3502e23ecbe182e9ed44e7b89874d6c
* Document last modified: 2022-06-17T05:22:52.000Z

</details>

**Comment by yin1999** [comment]
Please provide more infomation about the issue. I'm going to close this issue, but when you provide more details, I'll reopen this.
