### ISSUE TITLE
Issue with "Tutorial Django Parte 3: Uso de modelos": Spanish version

### ISSUE THREAD

**Issue by gpioli** [mdn/translated-content#7065]
MDN URL: https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Models

Hi! Just noticed that the spanish version of the link published above has a problem with the images (the UML isn´t loading). In fact, spanish version of other pages shows the same problem:

- [ ] #10322
- [ ] #10323
- [ ] #10324

English version is just fine.

Thanks!

<details>
<summary>Page report details</summary>

* Folder: `es/learn/server-side/django/models`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Models
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/server-side/django/models/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1109132f09d75da9a28b649c7677bb6ce07c40c0
* Document last modified: 2020-12-08T19:41:45.000Z

</details>

**Comment by Graywolf9** [comment]
Fixed in #10079

And opened issues for the listed pages, so any volunteer can see and fix it
