### ISSUE TITLE
Issue with wrong value on "translation_of" parameter in heading

### ISSUE THREAD

**Issue by ManuSquall** [mdn/translated-content#7107]
## What page(s) did you find the problem on?
I find the problem on [the github page about CSSOM](https://github.com/mdn/translated-content/blob/main/files/fr/glossary/cssom/index.md)

Which is deployed here : https://developer.mozilla.org/fr/docs/Glossary/CSSOM

## Specific page section or heading?

The typo is in the heading.

## What is the problem?

The "translation_of" parameter have the wrong value:

![image](https://user-images.githubusercontent.com/29026887/180646016-bdd58cb9-6f7d-4ecd-9d68-36e4ce314df7.png)

## What did you expect to see?

the value should be: "Glossary/CSSOM"

## Did you test this? If so, how?

Nope.

**Comment by cw118** [comment]
Fixed in #7108.
