### ISSUE TITLE
Issue with "Использование промисов": (short summary here please)

### ISSUE THREAD

**Issue by softlab** [mdn/translated-content#7123]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Using_promises

#### What information was incorrect, unhelpful, or incomplete?
While reading this  page in Firefox on my device  I can't find the way to read it  on English. It looks there are no language switcher :(

#### Specific section or headline?
Whole page

#### What did you expect to see?
A reference to English version of this page/article or button to switch the language

#### Did you test this? If so, how?
The issue withe page 

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/guide/using_promises`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Using_promises
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/guide/using_promises/index.html
* Last commit: https://github.com/mdn/translated-content/commit/fc2dfdd130a517935466bbb6304e8b4a2fe2d65e
* Document last modified: 2022-03-29T14:31:14.000Z

</details>

**Comment by cw118** [comment]
Hi @softlab, you should be able to switch the language of a page by clicking "🌐 Русский" (or another language):

![mdn-changer-langue-firefox](https://user-images.githubusercontent.com/87150472/181019916-c06ee9a2-e6d9-4920-adbd-bfbf150572bb.png)

Could you confirm that this works, or if not, could provide more details (i.e. a screenshot, etc.)?

**Comment by leon-win** [comment]
I also couldn’t reproduce the problem, so I’m closing this issue
