### ISSUE TITLE
Content bug: Chinese translation error

### ISSUE THREAD

**Issue by zealer-young** [mdn/translated-content#7128]
## What page(s) did you find the problem on?

https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status

## Specific page section or heading?

redirection_messages

## What is the problem?

Chinese translation doesn't match the English
<img width="819" alt="image" src="https://user-images.githubusercontent.com/53923902/180817540-beb4f430-2c65-4e8a-b45d-45a541ed1a20.png">
<img width="842" alt="image" src="https://user-images.githubusercontent.com/53923902/180817652-bf9d75a7-8415-4236-910e-c00a586831ad.png">

## What did you expect to see?

The right translation of the circled part could be: 请求拥有不只一个响应.

**Comment by Jack-Zhang-1314** [comment]
#7136
