### ISSUE TITLE
`{{Source}}` macro removal in translated-content

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#7178]
The `{{Source}}` macro has been deprecated and [removed from `en-US`](https://github.com/mdn/content/pull/18872), we should remove it from l10n documents.

I've used rg to find all the usage: `rg "\{\{\s*source" -i -l`:

- ru
  - files/ru/web/api/selection/index.html
  - files/ru/web/api/event/comparison_of_event_targets/index.html

For `l10n-zh`, I've created #7177 to fix this.

**Comment by mfuji09** [comment]
Done for `ja` by #7290

**Comment by yin1999** [comment]
There is no `{{source}}` macro in translated-content. Let's close this
