### ISSUE TITLE
Issue with "类元素": (short summary here please)

### ISSUE THREAD

**Issue by changjin110** [mdn/translated-content#7180]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Classes/Public_class_fields

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/46441436/181479348-722ffa40-a7b2-4b32-9e97-218829592204.png)

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/classes/public_class_fields`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Classes/Public_class_fields
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/classes/public_class_fields/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a6ea767cc3bf0cafa2682e7cafa0a2fe3ff8ecd4
* Document last modified: 2022-07-20T23:33:19.000Z

</details>

**Comment by awxiaoxian2020** [comment]
The doc is out of date.
