### ISSUE TITLE
'In this module' 제목 번역 표준화

### ISSUE THREAD

**Issue by SnowMarble** [mdn/translated-content#7184]
가이드(Learn) 페이지에서 `In this module` 이라는 제목은 거의 매 페이지마다 등장하지만, 아무래도 아직 이 번역에 대한 규칙이 정해지지 않아 기여자에따라 '이번 강의에서는', '이번 단위에는', '이 과정은' 등과 같이 번역이 조금씩 다르게 이루어지고 있는 것 같습니다.

![image](https://user-images.githubusercontent.com/69508345/181526632-44b964d1-d49d-4824-8656-451ac3da70c6.png)
https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#section-title

이번 기회에 번역에 대한 규칙을 정해보는게 어떨까요?

번역 참고 링크:
1. [Learn/CSS/First_steps/What_is_CSS](https://developer.mozilla.org/ko/docs/Learn/CSS/First_steps/What_is_CSS#%EC%9D%B4%EB%B2%88_%EA%B0%95%EC%9D%98%EC%97%90%EC%84%9C%EB%8A%94)
2. [Learn/CSS/CSS_layout/Introduction](https://developer.mozilla.org/ko/docs/Learn/CSS/CSS_layout/Introduction#%EC%9D%B4%EB%B2%88_%EB%8B%A8%EC%9C%84%EC%97%90%EB%8A%94)
3. [Learn/JavaScript/First_steps/What_is_JavaScript](https://developer.mozilla.org/ko/docs/Learn/JavaScript/First_steps/What_is_JavaScript#%EC%9D%B4_%EA%B3%BC%EC%A0%95%EC%9D%80)

**Comment by hochan222** [comment]
[공통용어](https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md#%EA%B3%B5%ED%86%B5-%EC%9A%A9%EC%96%B4) 에서 `어떠한 교육 과정, 단위에 의한 표현은 '과정'으로 번역한다. (예: In this module)` 로 정의되어 있어서 module은 과정으로 해석하면 좋아보입니다.

따라서, `이 과정에서는` 을 추천합니다. 다른 좋은 표현 있을까요? (CC: @SnowMarble , @mdn/yari-content-ko

**Comment by SnowMarble** [comment]
`이번 과정에서는`도 좋고, `진행중인 과정`도 맥락면에선 자연스러워 괜찮아보입니다. :)
