### ISSUE TITLE
Issue with "<audio>": translation issue 

### ISSUE THREAD

**Issue by the8th** [mdn/translated-content#7195]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/audio

#### What information was incorrect, unhelpful, or incomplete?
![image](https://user-images.githubusercontent.com/3350112/181741966-aca42969-0d5e-4688-af9c-231af8a80d54.png)

#### Specific section or headline?
/files/zh-cn/web/html/element/audio/index.html
line 18
```html
<p>上述例子展示了 <code>&lt;audio&gt;</code> 元素的基本用法。与 {{htmlelement("img")}} 元素类似，我们在 <code>src</code> 属性中添加了嵌入媒体的路径；也可以使用其他属性来规定一些功能，例如是否自动播放、是否循环播放、是否显示浏览器的默认音频空间等等。</p>
```
#### What did you expect to see?
last word of this block "音频空间" should be “音频控件”

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/html/element/audio`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/audio
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/html/element/audio/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b5d89daa81b44704b14528f058d614970231481f
* Document last modified: 2022-07-23T01:45:41.000Z

</details>

**Comment by awxiaoxian2020** [comment]
PR welcomed.

**Comment by Jack-Zhang-1314** [comment]
#7212
