### ISSUE TITLE
chore: Convert ./files/es/learn/css/building_blocks/fundamental_css_comprehension/index.html to Markdown

### ISSUE THREAD

**Issue by lenevdm** [mdn/translated-content#7219]
Convert ./files/es/learn/css/building_blocks/fundamental_css_comprehension/index.html to Markdown
Part of 100% Markdown Hackday.

**Comment by Graywolf9** [comment]
This could be solved in #7480

**Comment by Graywolf9** [comment]
Fixed in #7704
