### ISSUE TITLE
chore: convert learn index page to Markdown

### ISSUE THREAD

**Issue by nqcm** [mdn/translated-content#7225]
Convert './files/es/learn/index.html' to Markdown

Part of 100% Markdown Hackday

**Comment by SphinxKnight** [comment]
@nqcm is there any matching PR for this? if not I'd suggest closing this one.

**Comment by nqcm** [comment]
Hi @SphinxKnight my apologies for not making a PR for this issue. I will create a new issue when I am ready. Thank you!
