### ISSUE TITLE
Convert pt-br/web/api/animationevent/animationevent to MD

### ISSUE THREAD

**Issue by nathipg** [mdn/translated-content#7235]
Part of 100% Markdown Hackday

**Comment by nathipg** [comment]
PR: https://github.com/mdn/translated-content/compare/main...nathipg:7235-convert-pt-br/web/api/animationevent/animationevent-md?expand=1

**Comment by SphinxKnight** [comment]
TBD if https://github.com/mdn/translated-content/pull/8517 shoud fix this or be applied after #7236
