### ISSUE TITLE
Chore Convert WebExtension Example Markdown. 

### ISSUE THREAD

**Issue by mrsilentemmanuel** [mdn/translated-content#7244]
Chore Convert WebExtension Example to Markdown.
Part of 100% Markdown Hackday.

**Comment by SphinxKnight** [comment]
@mrsilentemmanuel could you indicate which files are targeted here?

**Comment by Graywolf9** [comment]
I'm not sure what files are, but I think this could be closed since all the locales are done

cc @SphinxKnight
