### ISSUE TITLE
chore: markdown: convert all remaining html files inside files/es/web/accessibility/ to markdown

### ISSUE THREAD

**Issue by schalkneethling** [mdn/translated-content#7251]
There are still a couple of HTML files inside the `accessibility` directory for Spanish. It would be good to get these converted to Markdown.

**Comment by Graywolf9** [comment]
I'm not sure what `accesibility` folder is but there is some PRs where it could have been done:

https://github.com/mdn/translated-content/pull/7699
https://github.com/mdn/translated-content/pull/7478
https://github.com/mdn/translated-content/pull/8926
