### ISSUE TITLE
[Markdown conversion]  Translated Notes and Warnings on `pt-br`

### ISSUE THREAD

**Issue by bpires** [mdn/translated-content#7291]
cc @schalkneethling, @nathipg 

During the '100% Markdown Hackday' we noticed that translated Notes and Warnings weren't receiving the proper formatting as highlighted red/blue boxes after Markdown conversion.

Reading the Markdown specs more closely, I've found out that:

> Because the text "Note:" or "Warning:" also appears in the rendered output, it has to be sensitive to translations. In practice, this means that **every locale supported by MDN must supply its own translation of these strings, and the platform must recognize them as indicating that the construct needs special treatment**.
> [Markdown in MDN > Notes, warnings, and callouts](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#notes_warnings_and_callouts)

I'm opening this issue for further guidance on how to provide special treatment for translated notes and warnings in Brazilian Portuguese.

For now, we are maintaining `**Note:**` and `**Warning:**` untranslated by default, but the preferred translation would be `**Nota:**` and `**Aviso:**`.

Thanks in advance.

**Comment by cw118** [comment]
Hi @bpires (cc @mdn/yari-content-pt-br), you need to create a pull request on [`mdn/yari`](https://github.com/mdn/yari) to add a file named `pt-BR.json` in the [folder `markdown/localizations`](https://github.com/mdn/yari/tree/main/markdown/localizations). This will allow for notes, callouts, and warnings to use translated keywords in Brazilian Portuguese.

I hope this helps, don't hesitate to ask any questions if help is needed :)

**Comment by bpires** [comment]
Thanks so much for answering so promptly @cw118 ! I understand it clearly now, you were very helpful. 😀
