### ISSUE TITLE
Issue with "Introdução à Web": (short summary here please)

### ISSUE THREAD

**Issue by 5734Elias** [mdn/translated-content#7296]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `pt-br/learn/getting_started_with_the_web`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/getting_started_with_the_web/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ad7f998115dd568832332484debf1f1b16b0c905
* Document last modified: 2021-02-11T17:27:17.000Z

</details>

**Comment by cw118** [comment]
I'm closing this because no information was provided. Please give more details on the issue(s) you faced on this MDN page and we may reopen this.
