### ISSUE TITLE
Content bug: several error in spanish translation

### ISSUE THREAD

**Issue by ale94lko** [mdn/translated-content#7297]
## What page(s) did you find the problem on?

https://developer.mozilla.org/es/docs/Web/HTTP/Headers/User-Agent

## Specific page section or heading?

All the page

## What is the problem?

There are several error like:
1- Double spaces between words
2- Translation isn't complete (still words to translate)
3- Lists have duplicated items
4- Links should have the name in Spanish as well

## What did you expect to see?

The hole page translated correctly

**Comment by ale94lko** [comment]
I can start working to resolve that issues if the community agreed so. I speak Spanish natively.

**Comment by cw118** [comment]
Hi @ale94lko, you are welcome to create a pull request on this repository to update/retranslate this page (and possibly/ideally convert the HTML file to Markdown), which the Spanish team will review. Let us know if help or discussion is needed :)

**Comment by ale94lko** [comment]
Closed because it was resolved in another PR [#7304](https://github.com/mdn/translated-content/pull/7304)
