### ISSUE TITLE
Issue with "article": (the whole translation is just wrong)

### ISSUE THREAD

**Issue by MarceloAdrianGuardia** [mdn/translated-content#7299]
MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Element/article

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/web/html/element/article`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTML/Element/article
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/html/element/article/index.html
* Last commit: https://github.com/mdn/translated-content/commit/4c9408f79ed6ccf2b81c4cfaf73cb34cf4d25eb4
* Document last modified: 2021-07-27T15:33:49.000Z

</details>

**Comment by Graywolf9** [comment]
Closed in #9725
