### ISSUE TITLE
RU: broken external links

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/translated-content#7322]
All external broken links in `mdn/content` have been fixed: https://github.com/mdn/content/pull/19085

While working on the PRs I've found following broken links in `ru` locale:

- [x] https://www.affirmationsforpositivethinking (https://github.com/mdn/translated-content/pull/20321)
- [x] https://firefox-source-docs.mozilla.org/devtools-user/performance/*
- [x] https://github.com/mdn/panner-node (https://github.com/mdn/translated-content/pull/20322)
- [x] https://mail.mozilla.org/listinfo/dev-addons (https://github.com/mdn/translated-content/pull/20323)
- [x] https://mdn.mozillademos.org/ (exists in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest)
- [x] https://searchfox.org/mozilla-central (exists in https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Omnibox)
- [x] http://docs.activestate.com/komodo/8.5/ (https://github.com/mdn/translated-content/pull/20249)
- [x] http://mxr.mozilla.org/ (https://github.com/mdn/translated-content/pull/20307, https://github.com/mdn/translated-content/pull/20309)
- [x] https://amazing.site (https://github.com/mdn/translated-content/pull/20256)
- [x] https://developer.android.com/sdk/index.html
- [x] https://github.com/mdn/translated-content/pull/20249
- [x] https://github.com/mdn/translated-content/pull/20245
- [x] https://github.com/mdn/translated-content/pull/20201
- [x] https://github.com/mdn/translated-content/pull/20209
- [x] https://github.com/mdn/translated-content/pull/20223
- [x] https://github.com/mdn/translated-content/pull/20234
- [x] https://github.com/mdn/translated-content/pull/20241
- [x] https://xxxxxx/ (exists in https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Tools_and_setup/Using_GitHub_pages)
- [x] http://weblogs.mozillazine.org/roc/archives/2010/08/mozrequestanima.html (https://github.com/mdn/translated-content/pull/20243)

In the process we've removed all `Source`[[ref](https://github.com/mdn/content/pull/18872)] and `Interwiki` macros.
***
**Tips:**
- To find files for the links without using IDE use GitHub Code search feature, e.g.
 [`https://github.com/mdn/translated-content/search?q=modern.ie`](https://github.com/mdn/translated-content/search?q=modern.ie)
- For links that are only part of the discussion put them in code fences(e.g. `www.example.com`) to avoid creating actual hyper links for them on the site. [[ref](https://github.com/mdn/content/pull/18917)]
- To find the URL replacements we'll have to look at the same file on `mdn/content`.

**Comment by leon-win** [comment]
This issue is now resolved :ok_hand:
