### ISSUE TITLE
Issue with "Mise en page de tableaux": (short summary here please)

### ISSUE THREAD

**Issue by cetteSara** [mdn/translated-content#7335]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/CSS/Building_blocks/Styling_tables

#### What information was incorrect, unhelpful, or incomplete?
All the images links appear broken in the /fr localisation for the URL mentionned above. 
ex. /fr/docs/Learn/CSS/Building_blocks/Styling_tables/punk.png
/fr/docs/Learn/CSS/Building_blocks/Styling_tables/cadre_1.png
/fr/docs/Learn/CSS/Building_blocks/Styling_tables/cadre_2.png

#### Specific section or headline?
All sections of the page.

#### What did you expect to see?
I expected to see the images like in the /en-US localisation.
ex. /en-US/docs/Learn/CSS/Building_blocks/Styling_tables/table-unstyled.png

#### Did you test this? If so, how?
N/A

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/css/building_blocks/styling_tables`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/CSS/Building_blocks/Styling_tables
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/css/building_blocks/styling_tables/index.md
* Last commit: https://github.com/mdn/translated-content/commit/85e77d04070b5d8f37f8d191feec64000f8ca197
* Document last modified: 2022-06-18T09:06:34.000Z

</details>

**Comment by SphinxKnight** [comment]
Thanks for the report @cetteSara, we'll fix this shortly.
