### ISSUE TITLE
Issue with "Primeros pasos en CSS": (short summary here please)

### ISSUE THREAD

**Issue by AndresGH9309** [mdn/translated-content#7350]
MDN URL: https://developer.mozilla.org/es/docs/Learn/CSS/First_steps

#### What information was incorrect, unhelpful, or incomplete?
Link https://teach.mozilla.org/activities/intermediate-web-lit/ is not accesible

#### Specific section or headline?
https://developer.mozilla.org/es/docs/Learn/CSS/First_steps

#### What did you expect to see?
web page

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/learn/css/first_steps`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/CSS/First_steps
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/css/first_steps/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1109132f09d75da9a28b649c7677bb6ce07c40c0
* Document last modified: 2020-12-08T19:41:45.000Z

</details>

**Comment by Graywolf9** [comment]
Thank you so much for submitting the issue, the link is outdate so I made a PR to update that section
