### ISSUE TITLE
Issue with "Array.prototype.flat()": wrong syntax in French translation

### ISSUE THREAD

**Issue by clement-escolano** [mdn/translated-content#7370]
MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/flat

#### What information was incorrect, unhelpful, or incomplete?

The syntax is described as `var nouveauTableau = monTableau.flat([profondeur]);`.

#### Specific section or headline?

Syntax section.

#### What did you expect to see?
The `depth` variable should be without brackets.

```ts
var nouveauTableau = monTableau.flat(profondeur);
```

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/array/flat`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/flat
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/array/flat/index.md
* Last commit: https://github.com/mdn/translated-content/commit/323c27e338d4f1671af89aa196d56395d5176af9
* Document last modified: 2022-05-30T11:06:33.000Z

</details>

**Comment by SphinxKnight** [comment]
@clement-escolano merci pour le rapport ! les crochets étaient utilisés avant pour indiquer un paramètre facultatif, je vais aligner la page sur le modèle anglais avec la syntaxe sans puis avec le paramètre.
