### ISSUE TITLE
Ensure that internal links point to same locale

### ISSUE THREAD

**Issue by queengooborg** [mdn/translated-content#7413]
Throughout the localized content, there are many internal links that point to the English docs, rather than the docs of the same language.  These should be corrected to point to the same locale, even if the translated versions do not yet exist.

- [x] es #14247
- [x] fr #14249
- [ ] ja #14253
- [x] ko
  - [x] #14254
  - [x] #14256
  - [x] #14257
  - [x] #14259
- [x] pt-br #14262
- [x] ru
  - [x] #14263
  - [x] #14264
  - [x] #14265
  - [x] #14267
- [x] zh-cn #14273
- [x] zh-tw #14276

**Comment by awxiaoxian2020** [comment]
consider https://github.com/mdn/mdn-community/discussions/144 ?

**Comment by cw118** [comment]
Done for fr in #7418

**Comment by SnowMarble** [comment]
Done for `ko` in #7461

**Comment by yin1999** [comment]
Done for `l10n-zh`

**Comment by mfuji09** [comment]
Done for `ja` by #8808

**Comment by Graywolf9** [comment]
Done for `es` in #10123 and #10126

**Comment by queengooborg** [comment]
During formatting runs (namely #14226), some more instances were found in completed locales.  As such, I'm going to mark them as incomplete again, so that we can double-check and make sure no more instances remain.  (I'll probably do that some time today!)

**Comment by yin1999** [comment]
Hi @queengooborg. Is it possible to add a rule to markdown-lint to prevent adding more links that are point to en-US?

**Comment by queengooborg** [comment]
I don't know if Markdownlint is powerful enough for that form of search and replace, but I will definitely be looking into it, and if so, tweaking the rule accordingly!  (I'll also be looking into other solutions as well if we can't use Markdownlint!)

**Comment by yin1999** [comment]
> I don't know if Markdownlint is powerful enough for that form of search and replace, but I will definitely be looking into it, and if so, tweaking the rule accordingly! (I'll also be looking into other solutions as well if we can't use Markdownlint!)

Maybe we could use [`mdast-util-from-markdown`](https://github.com/syntax-tree/mdast-util-from-markdown) to iter over the links in document :) We have used this in [mdn/yari](https://github.com/mdn/yari/blob/53314f560aa767f8e7f40fb6209df669e0df70e0/build/flaws/broken-links.ts#L18-L27)
