### ISSUE TITLE
Chore: Converting Spanish HTML to markdown

### ISSUE THREAD

**Issue by Rico-Smit** [mdn/translated-content#7462]
I did not get a gap to contribute on the hosted 100% Markdown Hackday. I will be converting file: es/learn/css/building_blocks/selectors/index.html to 100% markdown.

**Comment by JuanVqz** [comment]
@Rico-Smit As you can see this is already converted to markdown, can you close this issue, please?

https://github.com/mdn/translated-content/edit/main/files/es/learn/css/building_blocks/selectors/index.md
