### ISSUE TITLE
Issue with "WindowOrWorkerGlobalScope.setTimeout": typo

### ISSUE THREAD

**Issue by vagtal** [mdn/translated-content#7467]
MDN URL: https://developer.mozilla.org/es/docs/Web/API/setTimeout

#### What information was incorrect, unhelpful, or incomplete?
"El siguiente ejemplo establece dos botenes simples"

#### Specific section or headline?
#example

#### What did you expect to see?
La palabra botones en vez dce 'botenes'

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/web/api/settimeout`
* MDN URL: https://developer.mozilla.org/es/docs/Web/API/setTimeout
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/api/settimeout/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b1dd1321860a07a1de1b6b8d4f85f084f121680e
* Document last modified: 2022-08-04T19:05:08.000Z

</details>

**Comment by Graywolf9** [comment]
Hola! @vagtal muchas gracias por reportar el error, te animas a corregirlo? Solo tienes que ir al final de la página y darle en editar en github, te pedirá hacer un fork en tu cuenta, posteriormente solo será cuestión de editar y enviar los cambios

![imagen](https://user-images.githubusercontent.com/13079269/203392912-c6e1a8ce-09d0-42ca-a971-8ec7104f0f23.png)
