### ISSUE TITLE
Issue with "Découvrir les outils de développement des navigate…": (short summary here please)

### ISSUE THREAD

**Issue by russell2fx** [mdn/translated-content#7468]
MDN URL: https://developer.mozilla.org/fr/docs/Learn/Common_questions/What_are_browser_developer_tools

#### What information was incorrect, unhelpful, or incomplete?

Les visuels ne s'affichent pas correctement.

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/common_questions/what_are_browser_developer_tools`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/Common_questions/What_are_browser_developer_tools
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/common_questions/what_are_browser_developer_tools/index.md
* Last commit: https://github.com/mdn/translated-content/commit/85e77d04070b5d8f37f8d191feec64000f8ca197
* Document last modified: 2022-06-18T09:06:34.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci @russell2fx pour ce rapport, nous allons corriger ça prochainement
