### ISSUE TITLE
Content bug: Missing page Tutorials [es]

### ISSUE THREAD

**Issue by Graywolf9** [mdn/translated-content#7472]
## What page(s) did you find the problem on?

https://developer.mozilla.org/es/docs/games/tutorials

## Specific page section or heading?

Entire page

## What is the problem?

Page not found

## What did you expect to see?

https://developer.mozilla.org/en-US/docs/games/tutorials in `es` locale

## Did you test this? If so, how?

looking at: https://developer.mozilla.org/es/docs/games/tutorials

related to #7373

**Comment by EnriqueSource** [comment]
Me gustaría resolverlo
