### ISSUE TITLE
Issue with "CSS 网格中基于线的定位": (short summary here please)

### ISSUE THREAD

**Issue by lqzo** [mdn/translated-content#7500]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout/Line-based_Placement_with_CSS_Grid

#### What information was incorrect, unhelpful, or incomplete?

[使用线编号定位元素](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout/Line-based_Placement_with_CSS_Grid#%E4%BD%BF%E7%94%A8%E7%BA%BF%E7%BC%96%E5%8F%B7%E5%AE%9A%E4%BD%8D%E5%85%83%E7%B4%A0)

这个章节下的示例展示出现了问题，出现了两次 `<div class="wrapper">....</div>`

![image](https://user-images.githubusercontent.com/30641714/183871614-d61840cc-5746-484c-a328-967acf4887cb.png)

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/css_grid_layout/line-based_placement_with_css_grid`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout/Line-based_Placement_with_CSS_Grid
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/css_grid_layout/line-based_placement_with_css_grid/index.html
* Last commit: https://github.com/mdn/translated-content/commit/0bcb47618b95296c775b967f5ae1eff112292909
* Document last modified: 2022-07-31T00:24:02.000Z

</details>

**Comment by yin1999** [comment]
Thanks for raising this, I've created #7511 to fix this :)
