### ISSUE TITLE
Issue with "类": (short summary here please)

### ISSUE THREAD

**Issue by flywxc** [mdn/translated-content#753]
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Classes

static function
`Point.displayName` => `Point.name`

**Comment by jadjoubran** [comment]
This can be closed now, right?

**Comment by sideshowbarker** [comment]
> This can be closed now, right?

@jadjoubran yup — thanks much

**Comment by sideshowbarker** [comment]
Fixed by e3511f4.
