### ISSUE TITLE
Meta - Tracking issue for Markdown conversion `ru`

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#7580]
This issue intends to track ongoing work to convert every HTML document into Markdown for the Russian-speaking section.

- Games
  - Cleanup: https://github.com/mdn/translated-content/pull/8482
  - Replace: https://github.com/mdn/translated-content/pull/8896
- Glossary
  - Cleanup: https://github.com/mdn/translated-content/pull/8483
  - Replace: https://github.com/mdn/translated-content/pull/8897
- Learn
  - Cleanup: https://github.com/mdn/translated-content/pull/8537
  - Replace: https://github.com/mdn/translated-content/pull/8898
- MDN
  - Cleanup: https://github.com/mdn/translated-content/pull/8539
  - Replace: https://github.com/mdn/translated-content/pull/8900
- Mozilla
  - Cleanup: https://github.com/mdn/translated-content/pull/8554
  - Replace: https://github.com/mdn/translated-content/pull/8901
- Web
  - Accessibility
    - Cleanup: https://github.com/mdn/translated-content/pull/8555
    - Replace: https://github.com/mdn/translated-content/pull/8902
  - API
    - Cleanup: https://github.com/mdn/translated-content/pull/7953
    - Replace: https://github.com/mdn/translated-content/pull/8837
  - CSS
    - Cleanup: https://github.com/mdn/translated-content/pull/7591
    - Replace: https://github.com/mdn/translated-content/pull/7614
  - Events
    - Cleanup: https://github.com/mdn/translated-content/pull/8556
    - Replace: https://github.com/mdn/translated-content/pull/8903
  - Guide
    - Cleanup: https://github.com/mdn/translated-content/pull/8557
    - Replace: https://github.com/mdn/translated-content/pull/8904
  - HTML
    - Cleanup: https://github.com/mdn/translated-content/pull/7573
    - Replace: https://github.com/mdn/translated-content/pull/7612
  - HTTP
    - Cleanup: https://github.com/mdn/translated-content/pull/8558
    - Replace: https://github.com/mdn/translated-content/pull/8905
  - JavaScript
    - Cleanup: https://github.com/mdn/translated-content/pull/7969
    - Replace: https://github.com/mdn/translated-content/pull/8838
  - Manifest
    - Cleanup: https://github.com/mdn/translated-content/pull/8559
    - Replace: https://github.com/mdn/translated-content/pull/8906
  - MathML
    - Cleanup: https://github.com/mdn/translated-content/pull/8560
    - Replace: https://github.com/mdn/translated-content/pull/8907
  - Media
    - Cleanup: https://github.com/mdn/translated-content/pull/8563
    - Replace: https://github.com/mdn/translated-content/pull/8908
  - Performance
    - Cleanup: https://github.com/mdn/translated-content/pull/8564
    - Replace: https://github.com/mdn/translated-content/pull/8949
  - Progressive Web Apps
    - Cleanup: Not needed as there is no error already.
    - Replace: https://github.com/mdn/translated-content/pull/8596
  - Security
    - Cleanup: Not needed as there is no error already.
    - Replace: https://github.com/mdn/translated-content/pull/8598
  - SVG
    - Cleanup: https://github.com/mdn/translated-content/pull/8579
    - Replace: https://github.com/mdn/translated-content/pull/8950
  - Tutorials
    - Cleanup: https://github.com/mdn/translated-content/pull/8589
    - Replace: https://github.com/mdn/translated-content/pull/8951
  - Web Components
    - Cleanup: Not needed as there is no error already.
    - Replace: https://github.com/mdn/translated-content/pull/8599
  - XML
    - Cleanup: Not needed as there is no error already.
    - Replace: https://github.com/mdn/translated-content/pull/8600
  - XPath
    - Cleanup: Not needed as there is no error already.
    - Replace: https://github.com/mdn/translated-content/pull/8601
  - XSLT
    - Cleanup: Not needed as there is no error already.
    - Replace: https://github.com/mdn/translated-content/pull/8602
- WebAssembly
  - Cleanup: https://github.com/mdn/translated-content/pull/8590
  - Replace: https://github.com/mdn/translated-content/pull/8637

See also:
- https://github.com/mdn/translated-content/issues/7486 for the general issue
- https://docs.google.com/spreadsheets/d/1Mk3bQoHXozN2rUWn9rxVHA5MiO0whDLuj71KKC0iMSg/edit#gid=1017304837 for the Google Spreadsheet

**Comment by SphinxKnight** [comment]
@mdn/yari-content-ru I intend to wait 20-30 days for each cleanup PR. If there is no feedback on them, I'll submit and merge a replace/conversion PR afterwards in order to minimize the risk of conflicts.

Please let me know if you want to deal with Markdown conversion differently.

**Comment by sashasushko** [comment]
@SphinxKnight sounds like a plan 😉 I'll try to review all your PRs ASAP

**Comment by SphinxKnight** [comment]
@sashasushko thanks a lot, please comment any PR if you need more time or want changes or whatever!

**Comment by sashasushko** [comment]
@SphinxKnight copy that 🫡 Thank you for your help with MD

**Comment by SphinxKnight** [comment]
Thanks for the reviews on the cleanup PRs @sashasushko 🙇, I'll create "replace" PRs in the coming hours/days.

**Comment by SphinxKnight** [comment]
@mdn/yari-content-ru as for the cleanup PRs, I'll wait 1 month for each PR (starting from the latest commit), and if there's no objection/raised hand, I'll merge. Please do not hesitate to comment/ask for more time if needed.

**Comment by sashasushko** [comment]
@SphinxKnight that's all? Are we done?

**Comment by nschonni** [comment]
I think there is still some of the "orphan" files, but I think that's the case for a few other locales

**Comment by SphinxKnight** [comment]
Huge thanks @sashasushko, yes I think we're done with that (orphaned and conflicting could be dealt with later I think)

**Comment by nschonni** [comment]
There are also a bunch of stale PRs that were made against the HTML files that probably need to be closed or migrated https://github.com/mdn/translated-content/pulls?q=is%3Aopen+is%3Apr+label%3A%22rebase+needed+%3Aconstruction%3A%22

**Comment by sashasushko** [comment]
@nschonni I'll deal with them gradually
