### ISSUE TITLE
Content bug: Broken links in JS Expressions and Operators FR guide

### ISSUE THREAD

**Issue by deraw** [mdn/translated-content#7594]
## What page(s) did you find the problem on?

On the page https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Expressions_and_Operators.

### Links to the Reference page

The links to specific sections of the Operators Reference page are broken.

For exemple, the page links to:
- [/Reference/Operators#affectation](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators#affectation) instead of [/Reference/Operators#op%C3%A9rateurs_daffectation](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators#op%C3%A9rateurs_daffectation)
- [/Reference/Operators#.c3.89galit.c3.a9_simple_(.3d.3d)](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators#.c3.89galit.c3.a9_simple_(.3d.3d)) instead of [/Reference/Operators#sect15](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators#sect15) or [/Reference/Operators/Equality](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Operators/Equality) directly

It seems that the content of the Reference page was updated but not the content of the Guide.

### Internal link

Under the [Opérateurs](https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Expressions_and_Operators#op%C3%A9rateurs) title, the first link of the list is [/Guide/Expressions_and_Operators#op%c3%a9rateurs_d'affectation](https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Expressions_and_Operators#op%c3%a9rateurs_d'affectation) instead of [/Guide/Expressions_and_Operators#op%C3%A9rateurs_daffectation](https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Expressions_and_Operators#op%C3%A9rateurs_daffectation)

**Comment by SphinxKnight** [comment]
Thanks for the report @deraw! A fix is on its way
