### ISSUE TITLE
Issue with "HTML basics": Any images are not shown

### ISSUE THREAD

**Issue by TheTryProgrammerName** [mdn/translated-content#7596]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web/HTML_basics

Any images are not shown if I use page in Russian but everything is fine in English

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/getting_started_with_the_web/html_basics`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/Getting_started_with_the_web/HTML_basics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/getting_started_with_the_web/html_basics/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ef86e40eda3a49fdae2ff3d8b5c904f707512987
* Document last modified: 2022-08-04T19:06:23.000Z

</details>

**Comment by yin1999** [comment]
This issue has been fixed.
