### ISSUE TITLE
zh-cn clear unnecessary metadata

### ISSUE THREAD

**Issue by Jack-Zhang-1314** [mdn/translated-content#7599]
## What is the new suggestion?

https://github.com/mdn/translated-content/blob/main/docs/zh-cn/translation-guide.md#%E5%85%83%E6%95%B0%E6%8D%AE

## Why is it important or useful?

metadata like this:

```
---
title: Fetch API
slug: Web/API/Fetch_API
page-type: web-api-overview
tags:
  - API
  - Fetch
  - Landing
  - Reference
  - Response
  - XMLHttpRequest
  - request
browser-compat: api.fetch
---
```

But we just need:

```
---
title: Fetch API
slug: Web/API/Fetch_API
---
```

one: clear unnecessary metadata(/web/api) #7598

**Comment by Jack-Zhang-1314** [comment]
Why it failed

**Comment by yin1999** [comment]
https://github.com/mdn/translated-content/pull/7598#issuecomment-1213604893
