### ISSUE TITLE
Issue with "405 Method Not Allowed": (short summary here please)

### ISSUE THREAD

**Issue by Alexandr-Ilin** [mdn/translated-content#7600]
MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Status/405

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/web/http/status/405`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/HTTP/Status/405
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/http/status/405/index.html
* Last commit: https://github.com/mdn/translated-content/commit/e09cfd6a5ae6c22b9342c5c3f53dc6aed19241e0
* Document last modified: 2022-08-04T19:10:23.000Z

</details>

**Comment by yin1999** [comment]
Please specify the problem you have occured, and then we can reopen this issue.
