### ISSUE TITLE
[ko] Markdown convertion /games

### ISSUE THREAD

**Issue by hochan222** [mdn/translated-content#7623]
## 상위 이슈

https://github.com/mdn/translated-content/issues/2894

## 진행 사항

- [x] introduction https://github.com/mdn/translated-content/pull/7638
- [x] tutorials https://github.com/mdn/translated-content/pull/7638
- [x] https://github.com/mdn/translated-content/pull/7194

**Comment by SphinxKnight** [comment]
@hochan222 seems like everyting is done with this one? :)

**Comment by hochan222** [comment]
Yes thank you for mention me!
