### ISSUE TITLE
Error in CSS code (From Chinese Page)

### ISSUE THREAD

**Issue by Maple-Idle** [mdn/translated-content#7658]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Glossary/CSS_Selector

#### What information was incorrect, unhelpful, or incomplete?

CSS Code

#### Specific section or headline?

**示例**

#### What did you expect to see?

Same effect as [Selector (CSS)](https://developer.mozilla.org/en-US/docs/Glossary/CSS_Selector)

#### Did you test this? If so, how?

Of course, The developer tools are already the best proof.
> ("culor" and "sulid" ) => should be ('color' and  'solid')

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/glossary/css_selector`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Glossary/CSS_Selector
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/glossary/css_selector/index.md
* Last commit: https://github.com/mdn/translated-content/commit/b87fb6fb04e333727406ddc26831736ab5107863
* Document last modified: 2022-08-12T02:00:55.000Z

</details>

**Comment by yin1999** [comment]
Thanks for raising this, I've created #7659 to fix it.
