### ISSUE TITLE
Issue with "Primeros pasos en la Web": (short summary here please)

### ISSUE THREAD

**Issue by leoellis** [mdn/translated-content#7680]
MDN URL: https://developer.mozilla.org/es/docs/Learn/Getting_started_with_the_web

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/learn/getting_started_with_the_web`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/Getting_started_with_the_web
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/getting_started_with_the_web/index.md
* Last commit: https://github.com/mdn/translated-content/commit/cb9ff7e45332907baaee55a6e81e01c0fca35af8
* Document last modified: 2022-08-13T07:00:35.000Z

</details>

**Comment by cw118** [comment]
Please provide more information on the issue(s) you faced on this MDN page. This can be reopened if necessary and if additional details are given.
