### ISSUE TITLE
Remove duplicated frontmatter keys from zh-{CN, TW}

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#7683]
Part of #7412

sections to remove from:

- [x] games #7682
- [x] glossary #7706
- [x] learn #7729 #7721
- [x] mdn #7732 #7744
- [x] mozilla #7761 #7744
- [x] web #7760 #7832 #7831 #7830 #7829
- [x] webassembly #7729 #7720

**Comment by Jack-Zhang-1314** [comment]
#7760

**Comment by yin1999** [comment]
Done.
