### ISSUE TITLE
Issue with "Navigator.doNotTrack": (Inconsistent Chinese and English content)

### ISSUE THREAD

**Issue by zhengxs2018** [mdn/translated-content#7710]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Navigator/doNotTrack

#### What information was incorrect, unhelpful, or incomplete?

内容与英文版有偏差
 > machine translation：The content deviates from the English version

translation

![image](https://user-images.githubusercontent.com/7506913/184787933-8192f347-95cd-495a-8bec-93c19647fbd5.png)

original 

![image](https://user-images.githubusercontent.com/7506913/184788280-6d88777b-d58e-4d6a-9337-7545893214fd.png)

#### What did you expect to see?

内容应该保持一致
> machine translation：Content should be consistent

应该类似这样的内容
> machine translation：Similar content

```text
已弃用: 该功能不再被推荐。尽管有些浏览器可能仍然支持它，但它可能已经从相关的网络标准中删除，可能正在被放弃或只是为了兼容的目的而被保留。如果可能的话，更新现有的代码，避免使用它。请参阅本页面底部的 兼容表，以指导您的决定。注意，该功能可能在任何时候停止工作。
```

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/navigator/donottrack`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Navigator/doNotTrack
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/navigator/donottrack/index.md
* Last commit: https://github.com/mdn/translated-content/commit/cf20a5cadd07f32b9353eaf836e84f0eded1b4f1
* Document last modified: 2022-08-13T00:37:29.000Z

</details>

**Comment by yin1999** [comment]
Thanks for raising this, I'll update the hint :)

**Comment by yin1999** [comment]
Related jobs:

- mdn/yari#6888
- #7711

**Comment by yin1999** [comment]
All the related jobs were done. Thanks for reporting this
