### ISSUE TITLE
Issue with "CSS 网格布局中的自动定位": update needed for an example

### ISSUE THREAD

**Issue by mofada** [mdn/translated-content#7748]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout

#### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout#%E8%B0%83%E6%95%B4%E7%BD%91%E6%A0%BC%E4%B8%AD%E9%9A%90%E5%BC%8F%E8%A1%8C%E7%9A%84%E5%A4%A7%E5%B0%8F

Running the example and the code are inconsistent

![image](https://user-images.githubusercontent.com/22286246/185196785-25322f89-c595-4ec2-98c7-ea8cbd924922.png)

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/css_grid_layout/auto-placement_in_css_grid_layout`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/css_grid_layout/auto-placement_in_css_grid_layout/index.md
* Last commit: https://github.com/mdn/translated-content/commit/90ff1a5fb5b6c795cb795cb3f14a0f8361e2b634
* Document last modified: 2022-08-15T11:15:52.000Z

</details>

**Comment by yin1999** [comment]
Thanks for report it. After markdown convertion, the live sample should be updated. And I think we can do those job together.

Closing this issue for I'll finnish it in #7747
