### ISSUE TITLE
Issue with "CSS 网格布局中的自动定位": Example and code are inconsistent

### ISSUE THREAD

**Issue by mofada** [mdn/translated-content#7750]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout

#### What information was incorrect, unhelpful, or incomplete?

Example and code are inconsistent

![image](https://user-images.githubusercontent.com/22286246/185198184-1d1b5402-9118-4ab7-b304-d6cebcdc9031.png)

Maybe it's class naming pollution

![image](https://user-images.githubusercontent.com/22286246/185198978-dac7b1b4-cbc5-496d-a9a7-524bba7eeca6.png)

#### What did you expect to see?

this is english version.

![image](https://user-images.githubusercontent.com/22286246/185198690-d9d7751b-6b5e-4ce2-939b-9b0d269761cc.png)

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/css_grid_layout/auto-placement_in_css_grid_layout`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Grid_Layout/Auto-placement_in_CSS_Grid_Layout
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/css_grid_layout/auto-placement_in_css_grid_layout/index.md
* Last commit: https://github.com/mdn/translated-content/commit/90ff1a5fb5b6c795cb795cb3f14a0f8361e2b634
* Document last modified: 2022-08-15T11:15:52.000Z

</details>

**Comment by yin1999** [comment]
Thanks for report it. After markdown convertion, the live sample should be updated. And I think we can do those job together.

Closing this issue for I'll finnish it in #7747
