### ISSUE TITLE
zh-CN: clearup unnecessary metadata

### ISSUE THREAD

**Issue by Jack-Zhang-1314** [mdn/translated-content#7760]
## What is the new suggestion?

clearup unnecessary metadata in the zh-cn

#7752  #7753 #7756 #7757 #7758 #7759

**Comment by Jack-Zhang-1314** [comment]
completed `web`: #7598 #7733 #7734 #7736 #7738 #7739

**Comment by yin1999** [comment]
Done for zh-CN
