### ISSUE TITLE
Issue with "RegExp.prototype.exec()": This document is lags behind the English document

### ISSUE THREAD

**Issue by myNameIsDu** [mdn/translated-content#7771]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec

#### What information was incorrect, unhelpful, or incomplete?
This document is lags behind the English document

#### What did you expect to see?
Correct Chinese translation

#### Did you test this? If so, how?
I'm willing to take on this translation job if possible

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/regexp/exec`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/regexp/exec/index.md
* Last commit: https://github.com/mdn/translated-content/commit/566fd0e6880776af9bcd1af3d7a96f65bd255192
* Document last modified: 2022-08-17T23:50:28.000Z

</details>

**Comment by yin1999** [comment]
> I'm willing to take on this translation job if possible
> 

That's ok, feel free to do this.
