### ISSUE TITLE
`ja` の記事を HTML から MD へ一括変換

### ISSUE THREAD

**Issue by mfuji09** [mdn/translated-content#7782]
日本語版の記事を HTML から MD へ、スクリプトを使用して一括変換します。
一括変換は下記のような分野に分けて、順に行っていきます。

## 分類と進捗
（分類は見直すことがあります）
- [x] conflicting
- [x] games
- [x] glossary
- [x] learn
- [x] mdn
- [x] mozilla
  - [x] mozilla/firefox
- [x] orphaned
- [ ] web
  - [x] web/accessibility
  - [x] web/api
    - [x] web/api/audio*
    - [x] web/api/blob*
    - [x] web/api/clients
    - [x] web/api/css*
    - [x] web/api/document
    - [x] web/api/element
    - [x] web/api/gamepad*
    - [x] web/api/htmlformelement
    - [x] web/api/media*
    - [x] web/api/navigator
    - [x] web/api/performance*
    - [x] web/api/readablestream*
    - [x] web/api/serviceworker*
    - [x] web/api/sourcebuffer
    - [x] web/api/speechrecognition
    - [x] web/api/url*
    - [x] web/api/vr*
    - [x] web/api/webglrenderingcontext
    - [x] web/api/webxr_device_api
    - [x] web/api/window
    - [x] web/api - 1
    - [x] web/api - 2
    - [x] web/api - 3
    - [x] web/api - 4
    - [x] web/api - 5
  - [x] web/css
  - [x] web/events
  - [x] web/guide
  - [x] web/html
  - [x] web/http
  - [x] web/javascript
  - [x] web/mathml
  - [x] web/media
  - [x] web/progressive_web_apps
  - [x] web/security
  - [x] web/svg
  - [x] web/xpath
  - [x] web/xslt
- [x] webassembly

## 進め方
1. 該当部分について前処理（手作業）を行い、スクリプトでの変換後の修正量が少なくなるようにする
2. スクリプトで一括変換を行う
3. 変換済みの状態で PR を作成
4. レビュー
  - 特にうまく変換できていない点に気が付いたら、レビュアーに限らず修正をお願いします。
  - markdown 変換作業を効率よく行うため、内容の更新や誤りの修正などについては、致命的なものを除き、変換後に別な PR にて行ってくださるようお願いします。
  - markdown 変換は放置すると影響が大きいので、大きな問題がないと判断できたら数日程度で自己マージしますのでご了承ください。
  - マージ完了後に問題に気づいた場合は、ふつうの修正の手順（PR の発行）に従って修正をお願いします。

## その他
- レビュアーの方は、マージを行うときには必ず Rebase and merge でマージするようにお願いします。（ファイル名変更によって履歴が継承できなくなるのを防ぐため。）
- その他、何か不明点や要望があればこの Issue に書き込んでください。

**Comment by potappo** [comment]
ざっとチェックし始めました。藤本さんも気が付いている通り(#7768)、Note ブロックの変換が上手く行っていないようです。
MDN ディレクトリがもうすぐ見終わるので、次に javascript ディレクトリの方を見ます（昔に関わっているページが多いので）。

実質、レビュアーが私一人なので、レビューの優先度上げて欲しいディレクトリがあれば、リクエストください。金、土（ミートアップが午後からあります）、日は対応可能です（月曜以降もなるべく時間取りますが、仕事始まるのでどれだけ取れるかは未定）。

自分でチェックして、問題の有無のコメントをしていただいてもかまいません。

**Comment by mfuji09** [comment]
@potappo さん
Note: ブロックは使われているところが多いうえに、書き方がたくさんあり（Markdown 化直前に導入された、新しい書き方すらある）、使われている翻訳語もまちまちなので、マージ前にすべてを対処しようとすると、かなり時間がかかってしまいそうです。

マージを待たせることの方が影響が大きいと思うので、単純な置換で済むところや、致命的なところだけをマージ前に対処して、それ以降はメンテナンスに合わせて対処していくという方が現実的かもしれません。

**Comment by potappo** [comment]
@mfuji09 さん
なるほど、Note ブロックについて了解です。その対処方針で問題ないと思います。

**Comment by potappo** [comment]
変換後に英語版と重複しているメタデータ項目を削除するという issue を見つけたので備忘録としてメモしておきます。
合わせて translation_of も削除とのこと。
- https://github.com/mdn/translated-content/issues/7412

**Comment by mfuji09** [comment]
@potappo さん
今までどのメタデータ項目が必要なのか、はっきりしていなかったんですよね・・・。
Issue を #7858 で作っておきました。

**Comment by mfuji09** [comment]
現在出ているプルリクエストがすべてマージできれば、 HTML ファイルはすべてなくなり、すべてのファイルが markdown になる見込みです。

**Comment by mfuji09** [comment]
`ja` ロケールのすべてのファイルの変換が完了しました。
