### ISSUE TITLE
Issue with "文档与网站架构": (short summary here please)

### ISSUE THREAD

**Issue by LynchMuse** [mdn/translated-content#7793]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure

#### What information was incorrect, unhelpful, or incomplete?
Unable to scroll down on Chinese page
#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/html/introduction_to_html/document_and_website_structure`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/html/introduction_to_html/document_and_website_structure/index.md
* Last commit: https://github.com/mdn/translated-content/commit/9dfde88db4f402d8510bc9cc3ea21fffa2543c61
* Document last modified: 2022-08-17T00:00:18.000Z

</details>

**Comment by yin1999** [comment]
Hi @LynchMuse, this is an issue about `mdn/yari`. I've reported before (mdn/yari#6908).

Closing this for now.

**Comment by yin1999** [comment]
You can refresh the web page to resolve it temporarily
