### ISSUE TITLE
Issue with "500 Internal Server Error": (short summary here please)

### ISSUE THREAD

**Issue by Mrba-Software** [mdn/translated-content#7794]
MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Status/500

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/web/http/status/500`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Status/500
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/http/status/500/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c2c0bf2ed0c17ff062c497de9f2ff9c3d22f506d
* Document last modified: 2022-01-29T11:09:19.000Z

</details>

**Comment by cw118** [comment]
Hello, could you please provide more information on the issue(s) you were facing on this MDN page? I am closing this because no details were reported, but we can reopen if needed.
