### ISSUE TITLE
Issue with "建構 Angular 應用程式與更多資源": (ng build --prod deprecated)

### ISSUE THREAD

**Issue by chanyayun** [mdn/translated-content#7817]
MDN URL: https://developer.mozilla.org/zh-TW/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_building

#### What information was incorrect, unhelpful, or incomplete?
```
ng build --prod
```
This command seems to be deprecated. [check here](https://angular.io/guide/deprecations#angularcli)
#### What did you expect to see?
```
ng build --configuration production
```

#### Did you test this? If so, how?
I got the following error when run `ng build --prod`
```
Error: Unknown argument: prod
```

<details>
<summary>Page report details</summary>

* Folder: `zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building`
* MDN URL: https://developer.mozilla.org/zh-TW/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Angular_building
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-tw/learn/tools_and_testing/client-side_javascript_frameworks/angular_building/index.md
* Last commit: https://github.com/mdn/translated-content/commit/fce64fe669dd1bc1688139df5ecbaaa1f8018b8f
* Document last modified: 2022-08-17T01:23:38.000Z

</details>

**Comment by yin1999** [comment]
confirmed in <https://github.com/angular/angular-cli/blob/main/CHANGELOG.md#1400-2022-06-02>
