### ISSUE TITLE
[ja] 日本語版 Markdown 変換後の Note ブロックについて

### ISSUE THREAD

**Issue by potappo** [mdn/translated-content#7848]
#7782
現在、Markdown 変換において、Note ブロックについての以下の問題があります。

# "Note: 注:" と二重で表示される
Note: で Note ブロックのスタイルが適用されますので、これは日本語訳の方を削除する必要があります。
日本語訳のパターンは "使用上の注意" や "補足" など多岐に渡っており、恐らく、Note: で検索して、パターンを把握した上で、削除する必要があります。

# 一つ目のリストがリストに変換されていない
"Note: 補足:- リストの内容" となっているパターンです。-が余計かと思いましたが、リストを示す文字であり、リストとして表示されるように位置を修正する必要があります。

**Comment by potappo** [comment]
バリエーションとして、Warning ブロックも同じ現象となっています。

**Comment by mfuji09** [comment]
マジックワードの整備とリスト記号への対処が完了しました。

**Comment by debiru** [comment]
日本語版で `Note:`, `Warning:`, `Callout:` をどうかけばいいかを説明したページを示しておきます。

[https://developer.mozilla.org/ja/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#メモ、警告、コールアウト](https://developer.mozilla.org/ja/docs/MDN/Writing_guidelines/Howto/Markdown_in_MDN#%E3%83%A1%E3%83%A2%E3%80%81%E8%AD%A6%E5%91%8A%E3%80%81%E3%82%B3%E3%83%BC%E3%83%AB%E3%82%A2%E3%82%A6%E3%83%88)
