### ISSUE TITLE
ja - フロントマターから不要なメタデータを削除

### ISSUE THREAD

**Issue by mfuji09** [mdn/translated-content#7858]
フロントマター（各ファイルのヘッダー部分）から、下記のタグを残し、それ以外のメタデータを削除します。
`title`, `slug`, `original_slug`, `l10n.*`

主に削除対象になるものは、以下のものと思われます。
`tags`, `translation_of`, `browser-compat`, `spec-urls` など

**Comment by debiru** [comment]
ファイルの更新、あるいは新規翻訳をするにあたって、「メタデータ項目をどう書けばいいか」を知るにはどうすればよいでしょうか。

例えば、新規翻訳する場合 `l10n (sourceCommit)` の項目は必須でしょうか。書くべき場合、どのように `sourceCommit` の値を調べればよいでしょうか。

**Comment by mfuji09** [comment]
@debiru さん
Mozilla の方から正式なアナウンスがあるわけではないのですが、 #7412 からすると、新規翻訳に当たっては上記のタグのみを追加すればよいのだと思います。

また、 sourceCommit は翻訳のベースとした英語版のコミット ID を設定します。 git の履歴から取ることができます。 git のコマンドラインを使うならば下記のコマンドで表示できます。
git log <英語版のファイル名のパス>

私は Visual Studio Code を使用しているのですが、この場合はソース管理の「タイムライン」ペインでベースとした英語版のコミットを右クリックすると、コミットIDをコピーすることができる機能があるので、こちらを使用しています。

**Comment by debiru** [comment]
@mfuji09 さん

`original_slug` はどういう場合に設定するものなのかご存知でしょうか。`original_slug` は基本的には不要という認識ですが、設定が必要なケースがどういう場合か理解できておりません。

`l10n` の `sourceCommit` については、https://github.com/mozilla-japan/translation/discussions/621#discussioncomment-3413109 でも説明頂いた通り、翻訳時に参照した英語版のバージョンを示すためのコミット ID を記述するとのことで承知しました。コミット ID の調べ方は content リポジトリから `git log` 等で調べるということですね。

ローカライズチーム内で共有しておきたいと思いますが、新規翻訳時には、必須である `title`, `slug` に加え、オプションとして `l10n` の `sourceCommit` を記述するようにする。他の項目は削除する。更に、必要な場合に限って `original_slug` を記述するという認識でよさそうでしょうか。

**Comment by yin1999** [comment]
> `original_slug` はどういう場合に設定するものなのかご存知でしょうか。`original_slug` は基本的には不要という認識ですが、設定が必要なケースがどういう場合か理解できておりません。

The `original_slug` is set by [sync translated-content workflow](https://github.com/mdn/translated-content/actions/workflows/sync-translated-content.yml), which is used to sync documents movement. When a document is moved to a new path, the `original_slug` is set with the old `slug` value.

**Comment by mfuji09** [comment]
@debiru さん
`original_slug` については、すでに @yin1999 さんからもコメントがあった通りですが、英語版の記事が移動したり削除されたりして、自動的に日本語版の記事のスラッグが修正された場合、元のスラッグを保持するためのものです。ですから、翻訳をする際に自分で設定する必要は全くありません。
後でリダイレクトを修正したりするときに参考になるので、削除せずに残しておくという程度の認識でよいと思います。

**Comment by debiru** [comment]
@yin1999 
Thank you for your comment. I now have some understanding of the use of `original_slug`.

@mfuji09
ありがとうございます。`original_slug` が既存の記事に付いているものについては、気にせずそのまま残しておけばよいと理解しておきます。また、新規翻訳では基本的には設定するようなものではないということも理解しました。

新規翻訳時は `title`, `slug` に加えて、`l10n` の `sourceCommit` を設定すればよいということで理解しました。

**Comment by potappo** [comment]
残っていた PR を承認してマージしました。作業完了かと思いますのでクローズします。
