### ISSUE TITLE
Issue with "Doctype": (short summary here please)

### ISSUE THREAD

**Issue by Alexalucky** [mdn/translated-content#7860]
MDN URL: https://developer.mozilla.org/ru/docs/Glossary/Doctype

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/glossary/doctype`
* MDN URL: https://developer.mozilla.org/ru/docs/Glossary/Doctype
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/glossary/doctype/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ef86e40eda3a49fdae2ff3d8b5c904f707512987
* Document last modified: 2022-08-04T19:06:23.000Z

</details>

**Comment by yin1999** [comment]
Hi @Alexalucky, could you please provide more information about the problem on this page. So we can try to fix it.

After that, we can reopen this issue.
