### ISSUE TITLE
Issue with "Array.prototype.flatMap()": The page is displaying macro code instead of interactive sample

### ISSUE THREAD

**Issue by josielrocha** [mdn/translated-content#7873]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap

#### What information was incorrect, unhelpful, or incomplete?
Macro code is displayed instead of interactive example

#### Specific section or headline?
Array.prototype.flatMap()

#### What did you expect to see?
I was expecting to see an interactive example instead of `{{EmbedInteractiveExample("pages/js/array-flatmap.html")}}`

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/javascript/reference/global_objects/array/flatmap`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/javascript/reference/global_objects/array/flatmap/index.html
* Last commit: https://github.com/mdn/translated-content/commit/1445de621707e84b1ea3e88cf26ebaec84906046
* Document last modified: 2022-08-06T02:54:39.000Z

</details>

**Comment by cw118** [comment]
Hi @josielrocha, I believe this is because the macro is not preceded by a space or newline (a newline/separate `<div>` or `<p>` would be best). I have not (yet) tested this but I would be happy to if "needed" :)

**Comment by yin1999** [comment]
May be the slash `\` before macro call. It will make the macro as a text.

**Comment by yin1999** [comment]
and it's better to start in a new line.

I've created #7876 to fix it.
