### ISSUE TITLE
Issue with "Приоритет операторов": the information in the article in Russian does not match the information in the article in English

### ISSUE THREAD

**Issue by Alexandre887** [mdn/translated-content#7889]
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?

In the Russian version of the article the highest priority value is `19`, while in the English version of the article the highest priority value is `18`. Because of this, the priority values of all operators differ by 1.

#### Specific section or headline?

Table

#### What did you expect to see?

Operator priorities should be the same in both versions of the articles.

#### Did you test this? If so, how?

—

<details>
<summary>Page report details</summary>

* Folder: `ru/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/operators/operator_precedence/index.html
* Last commit: https://github.com/mdn/translated-content/commit/e09cfd6a5ae6c22b9342c5c3f53dc6aed19241e0
* Document last modified: 2022-08-04T19:10:23.000Z

</details>

**Comment by leon-win** [comment]
Fixed in #17388 :ok_hand: 

The reason was in the conditional (ternary) operator))

Thank you! :+1:
