### ISSUE TITLE
Issue with "Присоединяйся к сообществу MDN": (краткое резюме)

### ISSUE THREAD

**Issue by warsan** [mdn/translated-content#791]
MDN URL: https://developer.mozilla.org/ru/docs/orphaned/MDN/Community

#### Вы это проверяли? Если да, то как?

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/orphaned/mdn/community`
* MDN URL: https://developer.mozilla.org/ru/docs/orphaned/MDN/Community
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/orphaned/mdn/community/index.html
* Last commit: https://github.com/mdn/translated-content/commit/15b682f3ce7549aac1711f78e64bdb5aa6679a41
* Document last modified: 2021-05-07T00:31:35.000Z

</details>

**Comment by captainspring** [comment]
@warsan, добра! Опишите, пожалуйста, в чем заключается проблема? 
Если вы ищете информацию про сообщество MDN, ее можно найти [на актуальной странице об MDN](https://developer.mozilla.org/ru/docs/MDN/About#mdn_%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D1%81%D1%82%D0%B2%D0%BE). Страница, на которую вы ссылаетесь в ишью, более неактуальна, и поскольку она отсутствует в англоязычной версии, мы удалили ее и из русскоязычной тоже.

**Comment by warsan** [comment]
В самом конце [этой "актуальной" страницы](https://developer.mozilla.org/ru/docs/orphaned/MDN/Community) есть "недопереведённая" информация. 
Это `<div class="metadata-content-container"><div id="on-github" class="on-github"><h4>Found a problem with this page?</h4>`
Раньше у меня была возможность переводить "недопереведённое" или исправлять опечатки прямо со страницы контента MDN, но сейчас такой возможности почему-то не стало. 
-- И вот, ищу возможность устранить этот "косяк", то-есть, минимизировать присутствие англоязычной информации на русскоязычной странице. 
_(всех благ!)_

**Comment by captainspring** [comment]
@warsan это не косяк, эта часть страницы не переводится ни в одной локализации. Вот [ссылка на эту страницу в репозитории](https://github.com/mdn/translated-content/blob/main/files/ru/mdn/about/index.html). Обратите внимание, что в конце исходного файла вообще нет секции «Found a problem on this page?».
Также обратите внимание, что если вы переключите любую страницу MDN на любой язык, эта секция всегда будет одинаковой. 
Она по умолчанию всегда на английском и подставляется в страницу автоматически. 🙂 

> Раньше у меня была возможность переводить "недопереведённое" или исправлять опечатки прямо со страницы контента MDN, но сейчас такой возможности почему-то не стало.

Да, MDN теперь работает полностью через GitHub. Можно делать все эти действия через этот репозиторий. Вы можете склонировать его себе, поправить всё, что заметили (если это перевод — то в соответствии с нашим [руководством по переводу](https://github.com/mdn/translated-content/blob/main/docs/ru/translation-guide.md)), и сделать пулреквест. Кто-то из нашей команды волонтёров посмотрит его и примет.
Либо, как вы сделали сейчас, создать ишью — тогда ошибку исправит кто-то из команды волонтёров.
