### ISSUE TITLE
Chore - Team maintenance - Removing audrasjb from @mdn/yari-content-fr

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/translated-content#7913]
See https://github.com/mdn/translated-content/pull/7912 and https://github.com/mdn/content/pull/19814
Could you please withdraw Jean-Baptiste from the @mdn/yari-content-fr from the team?

**Comment by SphinxKnight** [comment]
@mdn/mdn-community-engagement can we have an update about this one?

**Comment by Rumyra** [comment]
All done @SphinxKnight - sorry for the delay, I think we've been moving teams around a bit and may not have received the initial notification (we should moving forward) 👍

**Comment by SphinxKnight** [comment]
Thanks @Rumyra :)
