### ISSUE TITLE
[l10n-ru] Incorrect links

### ISSUE THREAD

**Issue by MaximP2014** [mdn/translated-content#795]
@armanpwnz @captainspring @mpstv @myshov @Saionaro @sashasushko @lex111 
Привет! Пожалуйста, исправьте:

1. https://developer.mozilla.org/ru/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting 
Во фрейме <**iframe** id="frame_Representing_computer_code" ... > в атрибуте **src** битая ссылка: "Firefox не может открыть эту страницу и т.д.".

2. https://developer.mozilla.org/ru/docs/Learn/HTML/Multimedia_and_embedding/Adding_vector_graphics_to_the_Web 
Во фрейме <**iframe** id="frame_What_is_SVG" ... > в атрибуте **src** битая ссылка: "Firefox не может открыть эту страницу и т.д."

3. https://developer.mozilla.org/ru/docs/Learn/CSS/First_steps/How_CSS_works 
Во фреймах <**iframe** id="frame_A_real_DOM_representation" ... > и <**iframe** id="frame_Applying_CSS_to_the_DOM" ... > в атрибутах **src** битые ссылки: браузер показывает просто черные полоски (в зависимости от темы браузера).

4. https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Styling_tables 
В списках <**ul** class="prev-next"> в якорях "Далее" ссылки **href** не туда "/en-US/docs/Learn/CSS/Building_blocks/Advanced_styling_effects". А надо на "/ru/docs/Learn/CSS/Building_blocks/**Debugging_CSS**"

5. https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout 
В заголовке <**h1**> и подзаголовках (терминах) <**dt**> все ссылки на en-US, хотя есть **ru**.

6. https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/What_is_JavaScript
Во фрейме <**iframe** id="frame_Определение_высокого_уровня" ... > в атрибуте **id** смесь латиницы и кириллицы (зачем ?), а в атрибуте **src** ссылка на файл, который сильно отличается от исходника - без самого JavaScript'а, поэтому _кнопка не работает_.

7. https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/Variables
Во фрейме <**iframe** id="frame_What_is_a_variable" ... > в атрибуте **src** битая ссылка: "Firefox не может открыть эту страницу и т.д.".

8. https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/Strings
 https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/Useful_string_methods
В якорях <**a** class="external" ...>открыть эту консоль</**a**> и <**a** class="external" ...>открыть данную консоль</**a**> битые ссылки. Да и вообще, английский оригинал руководства "JavaScript First Steps" **не использует встроенную консоль**!

9. https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/Arrays
Во фрейме <**iframe** id="frame_Hidden_code" ... > (встроенная консоль ?) в атрибуте **src** битая ссылка. 

* _**to be continued**_...

**Comment by mpstv** [comment]
@MaximP2014 спасибо за замечания!
1. Пример встраивается с помощью макроса: 
https://github.com/mdn/translated-content/blob/713bd8ae2bc76e8b85af57b77711c6414c9ffee9/files/ru/learn/html/introduction_to_html/advanced_text_formatting/index.html#L620
2. Пример встраивается с помощью макроса:
https://github.com/mdn/translated-content/blob/713bd8ae2bc76e8b85af57b77711c6414c9ffee9/files/ru/learn/html/multimedia_and_embedding/adding_vector_graphics_to_the_web/index.html#L71
3. Пример встраивается с помощью макроса:
https://github.com/mdn/translated-content/blob/713bd8ae2bc76e8b85af57b77711c6414c9ffee9/files/ru/learn/css/first_steps/how_css_works/index.html#L84
4. Исправил в https://github.com/mdn/translated-content/pull/870
5. Не для всех страниц, на которые ссылается статья, нашел `ru` версию. Для тех, у которых нашел, исправил ссылки в https://github.com/mdn/translated-content/pull/870
6. Пример встраивается с помощью макроса:
https://github.com/mdn/translated-content/blob/713bd8ae2bc76e8b85af57b77711c6414c9ffee9/files/ru/learn/javascript/first_steps/what_is_javascript/index.html#L74
7. Пример встраивается с помощью макроса:
https://github.com/mdn/translated-content/blob/713bd8ae2bc76e8b85af57b77711c6414c9ffee9/files/ru/learn/javascript/first_steps/variables/index.html#L45
8. Исправил в https://github.com/mdn/translated-content/pull/870
9. Исправил в https://github.com/mdn/translated-content/pull/870

Что касается примеров, встроенных с помощью макросов - я пока не знаю, что с ними делать.

**Comment by MaximP2014** [comment]
@mpstv Спасибо

> Что касается примеров, встроенных с помощью макросов - я пока не знаю, что с ними делать.

Значит, проблема где-то тут:
https://github.com/mdn/yari/blob/a5f3c4775ffaa100ecbcfedc1b825061d58a05f3/kumascript/macros/EmbedLiveSample.ejs#L51
(См. комментарий ниже)

**Comment by mpstv** [comment]
Удалось разобраться с макросами. Создал пулреквест с решением и описанием https://github.com/mdn/translated-content/pull/1088.
