### ISSUE TITLE
Issue with "Значения свойств CSS": part of the page is in English

### ISSUE THREAD

**Issue by geighttt** [mdn/translated-content#7957]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Values_and_units

#### What information was incorrect, unhelpful, or incomplete?
The "Values and units" is not all in Russian

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/css/building_blocks/values_and_units`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Values_and_units
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/css/building_blocks/values_and_units/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ef86e40eda3a49fdae2ff3d8b5c904f707512987
* Document last modified: 2022-08-04T19:06:23.000Z

</details>

**Comment by leon-win** [comment]
This page already listed in #14208, so close this issue
