### ISSUE TITLE
[l10n-ru] Incorrect translations

### ISSUE THREAD

**Issue by MaximP2014** [mdn/translated-content#796]
@armanpwnz @captainspring @mpstv @myshov @Saionaro @sashasushko @lex111 
Привет! Пожалуйста, исправьте:

1. https://developer.mozilla.org/ru/ 
Были "_Ресурсы для разработчиков, от разработчиков_". А после перехода на новую платформу Yari главная страница вообще без локализации ?

2. https://developer.mozilla.org/ru/docs/Learn и др. подстраницы: 
В боковой панели навигации <**nav** id="sidebar-quicklinks" class="sidebar"> у многих уже переведенных статей остались английские заголовки.

3. https://developer.mozilla.org/ru/docs/Learn/HTML/Introduction_to_HTML/Getting_started 
Дублируются заголовки <**h3**> на двух языках: "Вложенные элементы / Nesting_elements" и т. д.

4. https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/The_box_model 
Выражение "Модель коробки" - неудачное. Лучше привычное "**Блочная модель**" - как в "Инструментах веб-разработчика" Firefox.

5. https://developer.mozilla.org/ru/docs/Learn/CSS/Building_blocks/Images_media_form_elements 
В <**h1**> неточный перевод, надо: "**Элементы изображений, медиа и форм**".

6. https://developer.mozilla.org/ru/docs/Learn/CSS/Styling_text и др. подстраницы: 
термин **Styling** переводится то как "стилизирование", то как "_**стилизация**_". 2-й вариант короче и лучше.

7. https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Responsive_Design
В атрибутах **id** какая-то смесь латиницы и кириллицы, но зачем ? Термин "Медиавыражения" надо поменять на "**Медиа запросы**".

8. https://developer.mozilla.org/ru/docs/Learn/JavaScript/First_steps/Variables
Выражение "Свободная типизация" надо поменять на "**Динамическая** типизация"

* _**to be continued**_...

**Comment by captainspring** [comment]
@MaximP2014 добра! Спасибо, что собрали столько замечаний по переводу и иным ошибкам на страницах 🙂 
Всё, что касается страниц, которые ещё не были переведены или перевод которых нуждается в актуализации — скорее всего, об этом мы в курсе, у нас есть [трекеры перевода разделов MDN на русский язык](https://github.com/mdn/translated-content/issues/276). Отдельно трекер раздела Learn [можно посмотреть тут](https://github.com/mdn/translated-content/issues/275). Работы много, но всё со временем актуализируем и переведём.

> * https://developer.mozilla.org/ru/docs/Learn/CSS/CSS_layout/Responsive_Design
>   <...> Термин "Медиавыражения" надо поменять на "**Медиа запросы**".

Мы пользуемся общим [руководством по переводу](https://github.com/mdn/translated-content/blob/main/docs/ru/translation-guide.md) и, в частности, [словарём «Веб-стандартов»](https://github.com/web-standards-ru/dictionary/blob/main/dictionary.md#m), и согласно ему _media query_ — это _медиавыражение_. 

Ещё раз спасибо, остальное поправим!

**Comment by mpstv** [comment]
1. Судя по всему - главная теперь у всех одна (посмотрел другие локализации - у них тоже нет переводов для главной).
2. Сайдбар встраивается с помощью макроса:
https://github.com/mdn/translated-content/blob/c7dc6954326e240634081295a64236a45e911f78/files/ru/learn/index.html#L18
Пока не понял как исправить - отложил.
3. Исправлено в https://github.com/mdn/translated-content/pull/1345
4. Исправлено в https://github.com/mdn/translated-content/pull/1124
5. Мне показался этот момент спорным - оставил старый вариант.
6. Исправлено в https://github.com/mdn/translated-content/pull/1345
7. Как написано в комментарии выше - используем вариант из словаря веб-стандартов.
8. Исправлено в https://github.com/mdn/translated-content/pull/1345

**Comment by MaximP2014** [comment]
**2**. Значит, надо поправить ru-словарь: https://github.com/mdn/yari/blob/a5f3c4775ffaa100ecbcfedc1b825061d58a05f3/kumascript/macros/LearnSidebar.ejs#L785 и ниже (CSS и т.д.).
Кстати, по пути надо убрать в https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Keyed_collections#тип_weakmap неуместную шутку: ""Зачем _козе баян_ WeakMap?"" - в оригинале просто "Why WeakMap?" ಠ_ಠ

**5**. Давайте сравним:
- оригинал: "Images, media, and form elements"
- мой вариант: "Элементы изображений, медиа и форм" (дословный перевод)
- старый вариант: "**Элементы** изображений, форм и медиа-**элементы**" - это же нелепая тавтология ¯\_(ツ)_/¯

**Comment by mpstv** [comment]
@MaximP2014 спасибо за комментарий!

**2.** Создал отдельное ишью https://github.com/mdn/translated-content/issues/1352 .
Шутку убрал в https://github.com/mdn/translated-content/pull/1345.

**5.** Подумал еще раз - согласен. Внес изменения в https://github.com/mdn/translated-content/pull/1345.

**7.** Ссылаясь на словарь веб-стандартов мы лишь пытались сказать, что это не ошибка перевода, а умышенное следование определенным правилам. Я думаю, что обсуждение этого вопроса должно быть вынесено за рамких этого ишью.

**Comment by MaximP2014** [comment]
Точнее даже отсюда https://github.com/mdn/yari/blob/a5f3c4775ffaa100ecbcfedc1b825061d58a05f3/kumascript/macros/LearnSidebar.ejs#L818 :
`'CSS_first_steps': 'CSS first steps'`
поменять на
`'CSS_first_steps': 'Введение в CSS'`
и т. д.

**Comment by MaximP2014** [comment]
**7**. OK

**Comment by sashasushko** [comment]
Да, соглашусь, что по 7 пункту стоит прийти в репу словаря, а лучше прислать пулреквест, к которому приложить ваши ссылки, что "медиа запросы" больше в ходу
