### ISSUE TITLE
The formula of rotate3d in zh-cn is wrong

### ISSUE THREAD

**Issue by army8735** [mdn/translated-content#80]
![image](https://user-images.githubusercontent.com/174904/109616083-af71f700-7b6f-11eb-93f7-219bf2bda667.png)
img url: https://developer.mozilla.org/@api/deki/files/5987/=transform-functions-rotate3d_cart.png
page url: https://developer.mozilla.org/zh-CN/docs/Web/CSS/transform-function/rotate3d()

It should be
![1](https://user-images.githubusercontent.com/174904/109616140-c3b5f400-7b6f-11eb-9075-01f6774ed06e.png)

**Comment by CreaTorAlexander** [comment]
I can work on it 👍

**Comment by SphinxKnight** [comment]
@army8735 sorry for getting back more than a year later on this but the English page is using the same matrix https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate3d() could you please provide a bit more information about the error here?

**Comment by army8735** [comment]
I know what the problem is.

![image](https://user-images.githubusercontent.com/174904/158556390-9076807b-7fbc-48cb-9a66-b3ab3a60f1da.png)
