### ISSUE TITLE
Issue with "Promise.all()": (A markdown bold syntax error caused ** symbols to appear in the document)

### ISSUE THREAD

**Issue by gxy5202** [mdn/translated-content#8034]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all

#### What information was incorrect, unhelpful, or incomplete?
如果传入的参数是一个空的可迭代对象，则返回一个**已完成（already resolved）**状态的 Promise

#### Specific section or headline?
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all#%E8%BF%94%E5%9B%9E%E5%80%BC

#### What did you expect to see?
如果传入的参数是一个空的可迭代对象，则返回一个已完成（already resolved）状态的Promise

#### Did you test this? If so, how?
I see the source code, there is a markdown bold syntax error.

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/promise/all`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/promise/all/index.md
* Last commit: https://github.com/mdn/translated-content/commit/566fd0e6880776af9bcd1af3d7a96f65bd255192
* Document last modified: 2022-08-17T23:50:28.000Z

</details>

**Comment by yin1999** [comment]
Fixed by #8035
