### ISSUE TITLE
Remove `{{warning}}` macro from translated-content

### ISSUE THREAD

**Issue by yin1999** [mdn/translated-content#8108]
The `{{warning}}` macro has [been deprecated](https://github.com/mdn/yari/pull/6994), let's remove it from translated-content.

This macro will render a note card, we can easily replace it by:

**HTML**:

```html
<div class="notecard warning">
  <p><strong>{{warning-keyword}}</strong> {{warns}}</p>
</div>
```

**Markdown**:

```md
> **{{warning-keyword}}** {{warns}}
```

The `{{warning-keyword}}` could be found [here](https://github.com/mdn/yari/tree/main/markdown/localizations) (`card_warning_label.msgstr` field). And the `{{warns}}` is just the argument of `{{warning}}` macro.

An example in mdn/content (mdn/content#20015).

**Comment by mfuji09** [comment]
Removed from `ja`.
