### ISSUE TITLE
Issue with "418 I'm a teapot": (short summary here please)

### ISSUE THREAD

**Issue by Climber87** [mdn/translated-content#8120]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/418

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/http/status/418`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Status/418
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/http/status/418/index.html
* Last commit: https://github.com/mdn/translated-content/commit/5ce6dc5cf9df29b229e9e892fdcb1ddbc641498b
* Document last modified: 2021-06-04T21:38:22.000Z

</details>

**Comment by cw118** [comment]
Please provide more information on the problem(s) you faced on this MDN page. We can reopen this if "necessary" and more details are given :)
