### ISSUE TITLE
Issue with "text-transform": (Live sample failed! )

### ISSUE THREAD

**Issue by RicardoGlobal** [mdn/translated-content#8172]
MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/text-transform

#### What information was incorrect, unhelpful, or incomplete?
In EJEMPLOS, the first output sample says:
Live sample failed!
An error occurred trying to render this live sample.
Consider filing an issue or trying your hands at a fix of your own.

Error details:

KumascriptError: unable to find any live code samples for "none" within /es/docs/Web/CSS/text-transform

#### Specific section or headline?
EJEMPLOS

#### What did you expect to see?
Something like this:
Initial String Lorem ipsum dolor sit amet, consectetur adipisicing elit, ...
text-transform: none Lorem ipsum dolor sit amet, consectetur adipisicing elit, ...

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/web/css/text-transform`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/text-transform
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/text-transform/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b1dd1321860a07a1de1b6b8d4f85f084f121680e
* Document last modified: 2022-08-04T19:05:08.000Z

</details>

**Comment by Graywolf9** [comment]
Thank you so much for submitting the issue

Fixed in #9534
