### ISSUE TITLE
chore: convert mozilla/firefox/releases for Spanish to Markdown

### ISSUE THREAD

**Issue by schalkneethling** [mdn/translated-content#8192]
As part of the larger 100% Markdown project(https://github.com/mdn/translated-content/issues/7486) I am converting the set of documents under `mozilla/firefox/releases` to Markdown.

- [Tracking spreadsheet](https://docs.google.com/spreadsheets/d/1Mk3bQoHXozN2rUWn9rxVHA5MiO0whDLuj71KKC0iMSg/edit#gid=617080625)

**Comment by yin1999** [comment]
Hi @schalkneethling, `l10n-ja` is 100% markdown now. The files listed in <https://docs.google.com/spreadsheets/d/1Mk3bQoHXozN2rUWn9rxVHA5MiO0whDLuj71KKC0iMSg/edit#gid=353394626> seems to be folders.

![image](https://user-images.githubusercontent.com/15844309/188763389-9d6ac82f-0cbf-4d9c-a973-fd8a757ca602.png)

**Comment by schalkneethling** [comment]
> Hi @schalkneethling, `l10n-ja` is 100% markdown now. The files listed in [docs.google.com/spreadsheets/d/1Mk3bQoHXozN2rUWn9rxVHA5MiO0whDLuj71KKC0iMSg/edit#gid=353394626](https://docs.google.com/spreadsheets/d/1Mk3bQoHXozN2rUWn9rxVHA5MiO0whDLuj71KKC0iMSg/edit#gid=353394626) seems to be folders.

Thank you for the heads up, I will take a look.
