### ISSUE TITLE
Issue with "Éxaminer et modifier le code HTML": remove the accent in the title

### ISSUE THREAD

**Issue by A-d-r-i** [mdn/translated-content#822]
MDN URL: https://developer.mozilla.org/fr/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML

#### What information was incorrect, unhelpful, or incomplete?
No emphasis on "Examiner" in the title of this article in French.

#### What did you expect to see?
"**Examiner et modifier le code HTML**"

<details>
<summary>MDN Content page report details</summary>

* Folder: `fr/tools/page_inspector/how_to/examine_and_edit_html`
* MDN URL: https://developer.mozilla.org/fr/docs/Tools/Page_Inspector/How_to/Examine_and_edit_HTML
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/tools/page_inspector/how_to/examine_and_edit_html/index.html
* Last commit: https://github.com/mdn/translated-content/commit/056dd907dec16280916ee9779a1416c8b618f53e
* Document last modified: 2021-05-10T19:36:00.000Z

</details>

**Comment by tristantheb** [comment]
Bonjour/Bonsoir @A-d-r-i,

Merci pour votre signalement, un contributeur (ou un relecteur) prendra en charge ceci sous peu :)

Vous pouvez également, si vous le souhaitez, contribuer à la correction de cette page en suivant les indications suivantes présentes sur le Blog « Bidouilleux d'Web » et le README (Anglais) de MDN.

https://tech.mozfr.org/post/2021/03/16/MDN-sur-GitHub-comment-contribuer
https://github.com/mdn/content/blob/main/README.md

**Comment by A-d-r-i** [comment]
Merci @tristantheb ! Je vais suivre le tuto.
