### ISSUE TITLE
Page macro on chinese "WeakSet" page

### ISSUE THREAD

**Issue by sjh42** [mdn/translated-content#8221]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakSet

#### What information was incorrect, unhelpful, or incomplete?
[[WeakSet 实例](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#weakset_%E5%AE%9E%E4%BE%8B)](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakSet#weakset_%E5%AE%9E%E4%BE%8B)
![WeakSet](https://user-images.githubusercontent.com/34529275/188053828-becc1774-2794-4944-8239-e94dc70a6c10.jpeg)

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/weakset`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/WeakSet
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/weakset/index.md
* Last commit: https://github.com/mdn/translated-content/commit/566fd0e6880776af9bcd1af3d7a96f65bd255192
* Document last modified: 2022-08-17T23:50:28.000Z

</details>

**Comment by yin1999** [comment]
Part of #3893, I'll try to fix it today.
