### ISSUE TITLE
Issue with "Tutorial Django Parte 3: Uso de modelos": image not displaying

### ISSUE THREAD

**Issue by karlitosx3** [mdn/translated-content#8233]
MDN URL: https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Models

#### What information was incorrect, unhelpful, or incomplete?

<img alt="LocalLibrary Model UML" src="https://mdn.mozillademos.org/files/15646/local_library_model_uml.png" loading="lazy">

This image doesnt load

#### Specific section or headline?

https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Models#dise%C3%B1ando_los_modelos_de_locallibrary

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/learn/server-side/django/models`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/Server-side/Django/Models
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/server-side/django/models/index.html
* Last commit: https://github.com/mdn/translated-content/commit/b1dd1321860a07a1de1b6b8d4f85f084f121680e
* Document last modified: 2022-08-04T19:05:08.000Z

</details>

**Comment by Graywolf9** [comment]
Thank you so  much for submitting the issue!

**Comment by karlitosx3** [comment]
Hi everyone.

The problem is repeated in all sections of the course in Spanish. The
images do not appear.

Thanks

**Comment by Graywolf9** [comment]
Thank you for reporting us @karlitosx3 , would you mind make an issue for every page or if it is too much, open an issue listing the pages? So any volunteer can see and fix it
