### ISSUE TITLE
ja - CSSリファレンス記事内「形式文法」にエラー文字列が表示されているページがある

### ISSUE THREAD

**Issue by itsumoonazicode** [mdn/translated-content#8268]
## What page(s) did you find the problem on?

下記以外にも存在していると思われます。

border-spacing
https://developer.mozilla.org/ja/docs/Web/CSS/border-spacing#%E5%BD%A2%E5%BC%8F%E6%96%87%E6%B3%95
margin-bottom
https://developer.mozilla.org/ja/docs/Web/CSS/margin-bottom#%E5%BD%A2%E5%BC%8F%E6%96%87%E6%B3%95

## Specific page section or heading?

上記に挙げたページ内の「形式文法」セクションです。

## What is the problem?

上記セクション内に、下記エラー文字列が表示されているページとそうでないページとかがあります。
`Error: could not find syntax for this item`

## If you have an idea of what the solution to your problem is, please provide details here.

エラーが表示されているページのmarkdownファイルを書き換える必要があるように思われます。
具体的には、メタ情報のtagsです。

該当ページのmarkdownに記されているtagsは日本語に翻訳されていますが、
これを翻訳元と同じ文字列にすることで解決できるのではないかと推測されます。
（つまり英語の表記に変更する）

border-spacingのmdファイル
https://github.com/mdn/translated-content/blob/main/files/ja/web/css/border-spacing/index.md?plain=1
margin-bottomのmdファイル
https://github.com/mdn/translated-content/blob/main/files/ja/web/css/margin-bottom/index.md?plain=1

エラー文字列が表示されていないページを以下に列挙します。
その中のtagsの中身は、翻訳元と同じ文字列が使われています（英語表記になっている）

flex-growのmdファイル
https://github.com/mdn/translated-content/blob/main/files/ja/web/css/flex-grow/index.md?plain=1
text-decoration-colorのmdファイル
https://github.com/mdn/translated-content/blob/main/files/ja/web/css/text-decoration-color/index.md?plain=1 

※flex-growのtagsは、「英語版と同期」というコミットの中で日本語から英語に書き直されている
https://github.com/mdn/translated-content/commit/391fbe16708123c06baf38b9bbe82d9e16527aab

## Did you test this? If so, how?

すみません、目視確認のみでテスト等はおこなっていません。。

**Comment by YujiSoftware** [comment]
#7858 で、英語版のタグが反映されるように日本語版から tags を消す対応を行っています。
具体的には、以下のような変更をしています。
* https://github.com/mdn/translated-content/pull/8279/files#diff-aa5ba70c0dccb6f4bb1251f0443e3e4fd1d380dd637831d4f23f8b6d2250684c
* https://github.com/mdn/translated-content/pull/8281/files#diff-0171fcfca58727727b28a56bc916af5f3a6864bb2961f0d425abc8ead794132b

これで、おそらく修正されると思います。

**Comment by debiru** [comment]
調査してみました。

「形式文法」は [`CSSSyntax`](https://developer.mozilla.org/ja/docs/MDN/Writing_guidelines/Page_structures/Syntax_sections#%E5%BD%A2%E5%BC%8F%E6%96%87%E6%B3%95_2) マクロによって出力されています。

`CSS Syntax` マクロは内部で `CSS Property` tag をドキュメントが持つかどうかを判定しており、持つ場合に機能するようになっています。（持たない場合の else if も続いていますが、ともかく tag を識別しています）
https://github.com/mdn/yari/blob/v1.18.13/kumascript/macros/CSSSyntax.ejs#L88

> 該当ページのmarkdownに記されているtagsは日本語に翻訳されていますが、
> これを翻訳元と同じ文字列にすることで解決できるのではないかと推測されます。

この推測は正しいです。

ただし、コメントされているように、本質的な対応は日本語版の `tags` を「修正する」のではなく「削除する」方針です。

FrontMatterKeys の修正は一括修正されているので、ここで対象ファイルを洗い出す意味はさほど意味がありませんが、このトピックで問題となっている記事は 522 件ほどあるようです。

- `CSSSyntax` を持ち、かつ `tags:` を日本語独自に持ち、`CSS Property` を持たない記事

```sh
$ grep -i -r '{{CSSSyntax}}' files/ja -l | xargs grep -E '^tags:' -l | xargs grep -L 'CSS Property' | wc -l
522
```

#7858 の対応によって解決する見込みです。

**Comment by itsumoonazicode** [comment]
@YujiSoftware @debiru 
なるほどですね…！了解いたしました。
該当・参考リンクを拝見しました。ありがとうございます。

「MDN Web Docs プロジェクト」なるページがあることを初めて知ったので、
眺めておこうと思います…:writing_hand::writing_hand:

**Comment by mfuji09** [comment]
CSS関係のフロントマターをすべて承認しましたので、数日内に解決すると思います。

**Comment by itsumoonazicode** [comment]
@mfuji09 @YujiSoftware @debiru 

issueに挙げた2件のページに関しては、正常に表示されていることを確認しました。
取り急ぎご報告します…！

border-spacing
https://developer.mozilla.org/ja/docs/Web/CSS/border-spacing#%E5%BD%A2%E5%BC%8F%E6%96%87%E6%B3%95
margin-bottom
https://developer.mozilla.org/ja/docs/Web/CSS/margin-bottom#%E5%BD%A2%E5%BC%8F%E6%96%87%E6%B3%95

**Comment by debiru** [comment]
`@` から始まるページと、一部の `orphaned` なページがまだ残っているようですが、ほとんどのページではこの問題は解消できたようです。

残るページのこの問題は #7858 に引き継ぐとして、この issue はクローズしてしまっても良さそうに思います。

```
$ grep -i -r '{{CSSSyntax}}' files/ja -l | xargs grep -E '^tags:' -l | xargs grep -L 'CSS Property' | wc -l
33

$ grep -i -r '{{CSSSyntax}}' files/ja -l | xargs grep -E '^tags:' -l | xargs grep -L 'CSS Property' 
files/ja/orphaned/web/css/-moz-context-properties/index.md
files/ja/orphaned/web/css/_colon_host-context()/index.md
files/ja/web/css/@viewport/index.md
files/ja/web/css/@import/index.md
files/ja/web/css/@supports/index.md
files/ja/web/css/@keyframes/index.md
files/ja/web/css/@document/index.md
files/ja/web/css/@property/initial-value/index.md
files/ja/web/css/@property/inherits/index.md
files/ja/web/css/@property/index.md
files/ja/web/css/@property/syntax/index.md
files/ja/web/css/@color-profile/index.md
files/ja/web/css/@namespace/index.md
files/ja/web/css/@scroll-timeline/index.md
files/ja/web/css/@font-feature-values/index.md
files/ja/web/css/@layer/index.md
files/ja/web/css/@charset/index.md
files/ja/web/css/@page/index.md
files/ja/web/css/@page/size/index.md
files/ja/web/css/@media/index.md
files/ja/web/css/@font-face/line-gap-override/index.md
files/ja/web/css/@font-face/size-adjust/index.md
files/ja/web/css/@font-face/font-variation-settings/index.md
files/ja/web/css/@font-face/font-stretch/index.md
files/ja/web/css/@font-face/ascent-override/index.md
files/ja/web/css/@font-face/descent-override/index.md
files/ja/web/css/@font-face/index.md
files/ja/web/css/@font-face/unicode-range/index.md
files/ja/web/css/@font-face/font-weight/index.md
files/ja/web/css/@font-face/font-display/index.md
files/ja/web/css/@font-face/font-style/index.md
files/ja/web/css/@font-face/font-family/index.md
files/ja/web/css/@font-face/src/index.md
```

**Comment by potappo** [comment]
クローズしておきます。
