### ISSUE TITLE
Issue with "radial-gradient()": (one italic style error)

### ISSUE THREAD

**Issue by ghsgz** [mdn/translated-content#8364]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/gradient/radial-gradient

#### What information was incorrect, unhelpful, or incomplete?

`*两个或多个色值结束点（color stops）*定义而成`

#### Specific section or headline?

`#radial_gradient_的组成`

#### What did you expect to see?

`*两个或多个色值结束点*（color stop）定义而成`

#### Did you test this? If so, how?

.

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/css/gradient/radial-gradient`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/CSS/gradient/radial-gradient
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/css/gradient/radial-gradient/index.md
* Last commit: https://github.com/mdn/translated-content/commit/84bfa88d136a6b339137358a838858900e0ca519
* Document last modified: 2022-08-17T04:58:56.000Z

</details>

**Comment by jasonren0403** [comment]
这篇文档本身也过期了，需要同步

**Comment by Jack-Zhang-1314** [comment]
过期的太多了,没有好的机制能及时解决
