### ISSUE TITLE
Issue with "-webkit-tap-highlight-color": (short summary here please)

### ISSUE THREAD

**Issue by Sproinfo** [mdn/translated-content#8374]
MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/-webkit-tap-highlight-color

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/-webkit-tap-highlight-color`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/-webkit-tap-highlight-color
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/-webkit-tap-highlight-color/index.md
* Last commit: https://github.com/mdn/translated-content/commit/258ba7b4be62d8640477a3bd3146d08b00cb70ec
* Document last modified: 2021-10-12T05:57:33.000Z

</details>

**Comment by cw118** [comment]
Please provide more information on the issue(s) you faced on this MDN page, then we can reopen this if necessary.
