### ISSUE TITLE
Issue with "background-image": example not working

### ISSUE THREAD

**Issue by IanEvers** [mdn/translated-content#8416]
MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/background-image

#### What information was incorrect, unhelpful, or incomplete?
there's an example that is not working. It is trying to show how background iamges work but there are no background images in the example. It works in the US version, but not on the spanish version.

#### Specific section or headline?
the only example in the examples section.

#### What did you expect to see?
A working example.

<details>
<summary>Page report details</summary>

* Folder: `es/web/css/background-image`
* MDN URL: https://developer.mozilla.org/es/docs/Web/CSS/background-image
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/css/background-image/index.html
* Last commit: https://github.com/mdn/translated-content/commit/695a9b3854c1a00e5d28c35973a09c718d9bce8c
* Document last modified: 2022-08-13T23:43:28.000Z

</details>

**Comment by JuanVqz** [comment]
Que información es incorrecta, o no ayuda o esta incompleta?

Hay un ejemplo que no esta funcionando, deberla mostrar como las imágenes funcionan como fondos "background" pero no hay imágenes in el ejemplo. En la documentación de Estados Unidos funciona bien pero no en la documentación en Español.

**Comment by JuanVqz** [comment]
@Graywolf9 cerrando issue, fue resuelto.
