### ISSUE TITLE
Issue with "HTTP에서의 압축": Simple Typo

### ISSUE THREAD

**Issue by jiwonMe** [mdn/translated-content#8454]
MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/Compression

#### What information was incorrect, unhelpful, or incomplete?
Not "손실 압축 알고리즘은 무손실 압축 **알로리즘**보다 일반적으로 효율적입니다.",
"손실 압축 알고리즘은 무손실 압축 **알고리즘**보다 일반적으로 효율적입니다."

#### Specific section or headline?
[파일 포맷 압축](https://developer.mozilla.org/ko/docs/Web/HTTP/Compression#%ED%8C%8C%EC%9D%BC_%ED%8F%AC%EB%A7%B7_%EC%95%95%EC%B6%95)

#### What did you expect to see?
"손실 압축 알고리즘은 무손실 압축 **알고리즘**보다 일반적으로 효율적입니다."

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ko/web/http/compression`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/Compression
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/http/compression/index.html
* Last commit: https://github.com/mdn/translated-content/commit/4543415abed67b451d6efb87565149bcadf7b43f
* Document last modified: 2022-08-04T19:07:25.000Z

</details>

**Comment by JinleeJeong** [comment]
@hochan222 안녕하세요! 해당 이슈도 지워져도 되지 않을까 싶습니다 :)
