### ISSUE TITLE
Issue with "Express 教學 3: 使用資料庫 ( Mongoose)": (short summary here please)

### ISSUE THREAD

**Issue by anotherKyleFrom1994** [mdn/translated-content#8495]
MDN URL: https://developer.mozilla.org/zh-TW/docs/Learn/Server-side/Express_Nodejs/mongoose

#### What information was incorrect, unhelpful, or incomplete?
The image links are expired.

#### Specific section or headline?
https://developer.mozilla.org/zh-TW/docs/Learn/Server-side/Express_Nodejs/mongoose#%E6%9E%B6%E8%A8%AD_mongodb_%E6%95%B8%E6%93%9A%E5%BA%AB

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-tw/learn/server-side/express_nodejs/mongoose`
* MDN URL: https://developer.mozilla.org/zh-TW/docs/Learn/Server-side/Express_Nodejs/mongoose
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-tw/learn/server-side/express_nodejs/mongoose/index.md
* Last commit: https://github.com/mdn/translated-content/commit/c4f98c95fb266300d4635c263ec062c13aed62e7
* Document last modified: 2022-09-09T06:46:01.000Z

</details>

**Comment by yin1999** [comment]
Fixed in #10485.
