### ISSUE TITLE
Issue with "Origin": incorrect content on empty string in the French translation

### ISSUE THREAD

**Issue by Schnouki** [mdn/translated-content#8504]
MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Origin

#### What information was incorrect, unhelpful, or incomplete?

The `Syntax` sections mentions that `Origin: ""` is allowed, and explains that "`Origin` can be an empty string: this is useful, for instance, if the origin is a `data` URL". 

#### Specific section or headline?

"Syntaxe"

#### What did you expect to see?

Based on https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin and https://datatracker.ietf.org/doc/html/rfc6454#section-7:

- no mention of an empty string
- mention of `Origin: null`, with examples of when it can happen

#### Did you test this? If so, how?

No.

<details>
<summary>Page report details</summary>

* Folder: `fr/web/http/headers/origin`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Origin
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/http/headers/origin/index.md
* Last commit: https://github.com/mdn/translated-content/commit/19cb4ddee3502e23ecbe182e9ed44e7b89874d6c
* Document last modified: 2022-06-17T05:22:52.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci @Schnouki ! je vais effectuer une mise à jour de la page rapidement (si quelqu'un ne me coupe pas l'herbe sous le pied :))
