### ISSUE TITLE
Issue with "REST": incorrect Wikipedia link

### ISSUE THREAD

**Issue by Hug0PC** [mdn/translated-content#8532]
MDN URL: https://developer.mozilla.org/es/docs/Glossary/REST

#### What information was incorrect, unhelpful, or incomplete?
REST on Wikipedia

#### Specific section or headline?
es/docs/Glosary

#### What did you expect to see?
https://es.wikipedia.org/wiki/Transferencia_de_Estado_Representacional

#### Did you test this? If so, how?
https://es.wikipedia.org/wiki/Representational_state_transfer --> don´t exist in Spanish

<details>
<summary>Page report details</summary>

* Folder: `es/glossary/rest`
* MDN URL: https://developer.mozilla.org/es/docs/Glossary/REST
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/glossary/rest/index.md
* Last commit: https://github.com/mdn/translated-content/commit/510f3c71ae41b4634d6eee82176cac2eada105a4
* Document last modified: 2022-08-15T21:20:49.000Z

</details>

**Comment by marcelozarate** [comment]
Fixed at PR #8851
