### ISSUE TITLE
Issue with "mouseenter": pictures loaded failed 图片加载失败

### ISSUE THREAD

**Issue by Cathyluna** [mdn/translated-content#8544]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Element/mouseenter_event

#### What information was incorrect, unhelpful, or incomplete?

下列图片加载失败
The pictures of this article loaded failed:
1. mouseenter.png
2. mouseover.png

#### Specific section or headline?

Bellow the second paragraph
第二自然段下

#### What did you expect to see?

The pictures show just like the english version of this article
展示对应英文文章的图片

#### Did you test this? If so, how?

尝试修改页面但是按照文档插入的图片路径找不到图片位置
I tried to edit this article in github, but I don't know where the pictures stored and how the code bellow work. 
`![mouseenter.png](/@api/deki/files/5908/=mouseenter.png)`

麻烦在中文翻译文档的readme中补充图片插入规则
Cause I can't find the corresponding folder and the file. Please update the picture insertion roles in Chinese version readme. In case anyone like me what to edit and start a pull request to fix it.

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/element/mouseenter_event`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Element/mouseenter_event
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/element/mouseenter_event/index.md
* Last commit: https://github.com/mdn/translated-content/commit/7b5cb9871d72421996645caddaf63f90371bccef
* Document last modified: 2022-09-06T23:25:29.000Z

</details>

**Comment by jasonren0403** [comment]
1. 文档的图片都在[content仓库](https://github.com/mdn/content)里，一般无需再次添加，直接在这边引用文件名即可，平台有自己的fallback机制
2. 文章本身该更新了，我看看有没有时间搞一下吧
