### ISSUE TITLE
Issue with "Quel sera l'aspect de votre site web ?": (short summary here please)

### ISSUE THREAD

**Issue by Alwin6209** [mdn/translated-content#8547]
Bonjour, je veux juste vous faire remarquer, une erreur de traduction sur la conjugaison du verbe souhaiter.

Je vous joints une capture d'écran.

J'apprécie le contenue de votre site, s'ai super félicitation à la communauté.
![202209161048Souhaitais-je](https://user-images.githubusercontent.com/113674416/190602490-700094da-51c2-41f4-a50a-e4b2de3eb6aa.png)

**Comment by SphinxKnight** [comment]
Bonjour, la forme interrogative des verbes du premier groupe prend un e accent aigu. Même si cela n'est pas très employé.
![image](https://user-images.githubusercontent.com/2413436/190620281-23497209-1f52-4e2b-ba56-73dd88af6f31.png)

**Comment by Alwin6209** [comment]
Merci a vous! Je viens d'apprendre deux choses...
Bonne journée  sphinxknighf.

Le ven. 16 sept. 2022, 12:35, SphinxKnight ***@***.***> a
écrit :
