### ISSUE TITLE
Content suggestion: Adding a Configuration File

### ISSUE THREAD

**Issue by YangFong** [mdn/translated-content#8618]
## What is the new suggestion?

I want the current warehouse to sync upstream, adding `.editorconfig` and `.prettierrc.json`.

---

我希望当前仓库向上游同步，添加 `.editorconfig` 和 `.prettierrc.json`。

## Why is it important or useful?
  
In this way, when translating content, it can be more relaxed.  Now I always need to manually adjust the indentation of the sample code (default: 4; original: 2) .

---

这样在翻译内容时，可以更轻松一些。现在的我老是需要手动调整示例代码的缩进（默认为 4，原文为 2）。

**Comment by yin1999** [comment]
It's a good idea, we just have done this in [mdn/content](https://github.com/mdn/content)

/cc @nschonni @caugner Any opinion?

**Comment by nschonni** [comment]
I had included it in https://github.com/mdn/translated-content/pull/8181, but it's probably easier to do a separate PR to land it quicker.
It's not so much used by Markdownlint, but is important for IDEs and Prettier
