### ISSUE TITLE
Content bug: search function - Nullish coalescing operator page title

### ISSUE THREAD

**Issue by YangFong** [mdn/translated-content#8655]
## What is the problem?

When I use the search function, I find that some content does not come up, such as:

---

我在使用搜索功能时发现，有些内容搜索不出来，比如：

![image](https://user-images.githubusercontent.com/70502828/191175348-e4d3debc-400c-4bd8-bbbb-2fd72a5a3666.png)

<https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator>

It also reminds me that some content should not be deleted. In this scenario, I need to jump twice to get to the page I want to go to.

  
If there is no `??=`, it may be completely lost or difficult to find.

---

这也提醒我，一些内容不能完全翻译。在这个场景下，我就需要通过二次跳转，才能抵达我想去的页面。

如果没有 `??=`，就可能完全找不到了，或者说很难。

**Comment by YangFong** [comment]
I brought this up because I want to see `?.` and `??`, however, they D have this problem. Of course, most operator titles are normal.

**Comment by SphinxKnight** [comment]
@YangFong hello, just to be sure, this issue is not related to the translated content but to the site itself right? (if confirmed, I'll transfer the issue accordingly to mdn/yari)

**Comment by YangFong** [comment]
> @YangFong hello, just to be sure, this issue is not related to the translated content but to the site itself right? (if confirmed, I'll ask @mdn/mdn-community-engagement to transfer the issue accordingly to mdn/yari)
  
I am merely emphasizing that parts of the text should be preserved, not translated in its entirety.

The content is fine, and the current title makes the search function limited (because the user may not know what the specific professional name is).

**Comment by YangFong** [comment]
In addition, I have just changed the titles of these two documents to make it easier to find them.

**Comment by SphinxKnight** [comment]
Agreed the title on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator should be propagated in other locales

**Comment by yin1999** [comment]
closing it as fixed in #8658
