### ISSUE TITLE
chore: convert web/api/document for Spanish (es) to Markdown

### ISSUE THREAD

**Issue by jakul** [mdn/translated-content#8664]
As part of the larger 100% Markdown [project](https://github.com/mdn/translated-content/issues/7486), I am converting the set of documents under web/api/document to Markdown.

[Tracking spreadsheet](https://docs.google.com/spreadsheets/d/1Mk3bQoHXozN2rUWn9rxVHA5MiO0whDLuj71KKC0iMSg/edit#gid=617080625)

**Comment by SphinxKnight** [comment]
@jakul thanks! is there any related PR we could link to this issue?

**Comment by jakul** [comment]
Not yet, I'm still working on the conversion

**Comment by jakul** [comment]
@SphinxKnight Raised https://github.com/mdn/translated-content/pull/8670
