### ISSUE TITLE
Issue with "Generalidades del protocolo HTTP": (short summary here please)

### ISSUE THREAD

**Issue by tankez0r** [mdn/translated-content#8672]
MDN URL: https://developer.mozilla.org/es/docs/Web/HTTP/Overview

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `es/web/http/overview`
* MDN URL: https://developer.mozilla.org/es/docs/Web/HTTP/Overview
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/http/overview/index.html
* Last commit: https://github.com/mdn/translated-content/commit/695a9b3854c1a00e5d28c35973a09c718d9bce8c
* Document last modified: 2022-08-13T23:43:28.000Z

</details>

Images are broken.

**Comment by yin1999** [comment]
It seems that the images in this page are broken, are you going to report this problem @tankez0r?

**Comment by Graywolf9** [comment]
Fixed in #8912
