### ISSUE TITLE
Issue with "TCP": (short summary here please)

### ISSUE THREAD

**Issue by joseelieserbarbosaandrade** [mdn/translated-content#8683]
MDN URL: https://developer.mozilla.org/pt-BR/docs/Glossary/TCP

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `pt-br/glossary/tcp`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Glossary/TCP
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/glossary/tcp/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ad7f998115dd568832332484debf1f1b16b0c905
* Document last modified: 2021-02-11T17:27:17.000Z

</details>

**Comment by cw118** [comment]
Hi, please provide more information on the issue(s) found on this MDN page, and this can be reopened if needed :)
