### ISSUE TITLE
Issue with "Основные понятия асинхронного программирования": (broken links)

### ISSUE THREAD

**Issue by savvy-itch** [mdn/translated-content#8724]
MDN URL: https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous/Introducing

#### What information was incorrect, unhelpful, or incomplete?
example links don't work (error 404)

#### Specific section or headline?
https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous/Introducing#блокировка_кода
https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous/Introducing#потоки

#### What did you expect to see?
github page with code or live demonstration of it

#### Did you test this? If so, how?
no

<details>
<summary>Page report details</summary>

* Folder: `ru/conflicting/learn/javascript/asynchronous/introducing`
* MDN URL: https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous/Introducing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/conflicting/learn/javascript/asynchronous/introducing/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ef86e40eda3a49fdae2ff3d8b5c904f707512987
* Document last modified: 2022-08-04T19:06:23.000Z

</details>

**Comment by leon-win** [comment]
The https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous/Introducing page was removed from MDN, so I close this issue
