### ISSUE TITLE
Issue with "Composition et découpe": Exemple part cannot load

### ISSUE THREAD

**Issue by VincentSinel** [mdn/translated-content#8754]
MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Compositing

#### What information was incorrect, unhelpful, or incomplete?
Exemple page cannot be load anymore

#### What did you expect to see?
The exemple page

<details>
<summary>Page report details</summary>

* Folder: `fr/web/api/canvas_api/tutorial/compositing`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/API/Canvas_API/Tutorial/Compositing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/api/canvas_api/tutorial/compositing/index.md
* Last commit: https://github.com/mdn/translated-content/commit/040a7573de416de6d0defcdb706a19924bdd44d6
* Document last modified: 2022-09-21T09:43:04.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci @VincentSinel, voyons voir pour mettre à jour cette page et corriger ça
