### ISSUE TITLE
Issue with "Введение в асинхронный JavaScript": (broken links)

### ISSUE THREAD

**Issue by savvy-itch** [mdn/translated-content#8809]
MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Introducing

#### What information was incorrect, unhelpful, or incomplete?
example links don't work (error 404)

#### Specific section or headline?
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Introducing#асинхронные_колбэки
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Introducing#природа_асинхронного_кода
https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Introducing#активное_обучение_сделайте_все_это_асинхронно!

#### What did you expect to see?
github code or live example of it

#### Did you test this? If so, how?
by clicking the links

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/javascript/asynchronous/introducing`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous/Introducing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/javascript/asynchronous/introducing/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ef86e40eda3a49fdae2ff3d8b5c904f707512987
* Document last modified: 2022-08-04T19:06:23.000Z

</details>

**Comment by leon-win** [comment]
Removed broken links in #17387 

But this page is very outdated and requires a complete translation :crossed_fingers:
