### ISSUE TITLE
Issue with "Объединённый асинхронный JavaScript: Таймауты и ин…": (broken links)

### ISSUE THREAD

**Issue by savvy-itch** [mdn/translated-content#8810]
MDN URL: https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous

#### Specific section or headline?
https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous#settimeout
https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous#setinterval
https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous#что_нужно_помнить_о_settimeout_и_setinterval
https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous#requestanimationframe
https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous#активное_обучение_игра_на_реакцию

#### What did you expect to see?
github code or live example of it

#### Did you test this? If so, how?
by clicking the links

<details>
<summary>Page report details</summary>

* Folder: `ru/conflicting/learn/javascript/asynchronous`
* MDN URL: https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/conflicting/learn/javascript/asynchronous/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ef86e40eda3a49fdae2ff3d8b5c904f707512987
* Document last modified: 2022-08-04T19:06:23.000Z

</details>

**Comment by leon-win** [comment]
Hi, @savvy-itch!

The https://developer.mozilla.org/ru/docs/conflicting/Learn/JavaScript/Asynchronous page no longer exists.

Some information about asynchrony can be found at https://developer.mozilla.org/ru/docs/Learn/JavaScript/Asynchronous

That's why I'm closing this issue.

Thank you for trying to help the project! 👍
