### ISSUE TITLE
Content bug: invalid URL

### ISSUE THREAD

**Issue by Freed-Wu** [mdn/translated-content#8843]
## What page(s) did you find the problem on?

<https://developer.mozilla.org/zh-CN/docs/Learn/CSS/First_steps/How_CSS_is_structured#%E6%8E%A5%E4%B8%8B%E6%9D%A5%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%9F>
![Screenshot from 2022-09-26 21-51-47](https://user-images.githubusercontent.com/32936898/192294080-d0cde524-94ac-40a7-8105-7ca32b92375f.png)

**Comment by jasonren0403** [comment]
has PR: #8863
