### ISSUE TITLE
Issue with "Инструмент выбора цвета": (short summary here please)

### ISSUE THREAD

**Issue by Fenix-tatoo** [mdn/translated-content#8877]
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Colors/Color_picker_tool

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ru/web/css/css_colors/color_picker_tool`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/CSS_Colors/Color_picker_tool
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/css_colors/color_picker_tool/index.md
* Last commit: https://github.com/mdn/translated-content/commit/4a6b0a947e2798f458d398b52cb55a341fc0582a
* Document last modified: 2022-08-13T06:14:24.000Z

</details>

**Comment by SphinxKnight** [comment]
@Fenix-tatoo Could you please add some more details about the issue you're facing with this page?
In the meantime I'm going to close this issue. I'll reopen should more information make this actionable.
