### ISSUE TITLE
 "manifest_version": 2,I

### ISSUE THREAD

**Issue by lelpsome** [mdn/translated-content#8909]
MDN URL: https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/mozilla/add-ons/webextensions/manifest.json/manifest_version`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Mozilla/Add-ons/WebExtensions/manifest.json/manifest_version
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/mozilla/add-ons/webextensions/manifest.json/manifest_version/index.md
* Last commit: https://github.com/mdn/translated-content/commit/8fa6a25721045cefa0ad004d8fc7340475e86808
* Document last modified: 2022-09-24T03:41:21.000Z

</details>

**Comment by SphinxKnight** [comment]
@lelpsome
Please provide some more details about the issue you are facing so that we can help fixing it.
I'll close this for now but will reopen it, should information be added.
