### ISSUE TITLE
Localized issue template (`page-report.yml`)

### ISSUE THREAD

**Issue by cw118** [mdn/translated-content#8918]
@JuanVqz asked if `page-report.yml` can be translated in each locale now that the new English issue template is being used on `translated-content`, so I decided to create this issue for discussion :)

I was thinking of creating a `page-report-<locale>.yml` file for each locale (e.g. `page-report-fr.yml`) in a PR, all in English first. I will update the implementation on `yari`, then locale teams can:
  - translate them on that PR with suggestions/commits
  - *or* it could be merged first, and each team creates a PR after to translate the template for their locale

Poking @mdn/yari-content-ru @mdn/yari-content-ja @mdn/yari-content-pt-br @mdn/yari-content-zh (apologies for pinging so many times 😅) who have yet not approved

**Edit:** mdn/yari#7277 should take care of the "Report on GitHub" link

**Comment by nschonni** [comment]
What about stubbing each of the locales using the English template to start, then the change it Yari can land, with the translated templates to follow

**Comment by Jack-Zhang-1314** [comment]
> What about stubbing each of the locales using the English template to start, then the change it Yari can land, with the translated templates to follow

This is a good feature for localization. Tbh, I'm looking forward.

**Comment by cw118** [comment]
@nschonni as I wrote in the issue, 

> I was thinking of creating a page-report-<locale>.yml file for each locale all in English first.

The modifications are almost ready and I will create the PR very soon :)

**Comment by JuanVqz** [comment]
I like the second option:

or it could be merged first, and each team creates a PR after to translate the template for their locale

**Comment by Graywolf9** [comment]
Done for `es` in #9505

Thank you so much for all!

**Comment by mfuji09** [comment]
Done for `ja` in #10857.

**Comment by hochan222** [comment]
Done for ko in https://github.com/mdn/translated-content/pull/11536.
