### ISSUE TITLE
Incorrect translations

### ISSUE THREAD

**Issue by JellyL** [mdn/translated-content#904]
https://developer.mozilla.org/zh-CN/docs/Web/SVG/Attribute/d

https://github.com/mdn/translated-content/blob/40edc745dfb5c152e12080748f9357b376e8dbe9/files/zh-cn/web/svg/attribute/d/index.html#L89

There is no comparison between Chinese and English, it seems to be wrong here.
没有中英对比，这里好像是错误的
`声明相对而言有点复Visual Studio`

**Comment by KevinZonda** [comment]
这份文档已经过期，需要同步。
