### ISSUE TITLE
O fim do texto continua em Inglês, e não foi traduzido para outra linguagem.

### ISSUE THREAD

**Issue by sanchoirams** [mdn/translated-content#9042]
### MDN URL

https://developer.mozilla.org/pt-BR/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML

### What specific section or headline is this issue about?

interpretando as mensagens de erro

### What information was incorrect, unhelpful, or incomplete?

"Interpretando as mensagens de erros", a partir daqui o texto se mantem em inglês e não foi traduzido para outra linguagem no navegador.

### What did you expect to see?

linguagem traduzida para o meu idioma ou de quem estiver acessando.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/pt-BR/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML

Interpretando as mensagens de erros

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `pt-br/learn/html/introduction_to_html/debugging_html`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/HTML/Introduction_to_HTML/Debugging_HTML
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/html/introduction_to_html/debugging_html/index.html
* Last commit: https://github.com/mdn/translated-content/commit/bec25e522b17f939935865ac39a95c7760781e96
* Document last modified: 2022-08-04T19:07:07.000Z

</details>

**Comment by halcance** [comment]
Oi @sanchoirams obrigado pelo feedback! Irei providenciar a tradução do artigo.
