### ISSUE TITLE
Images lost

### ISSUE THREAD

**Issue by vinicius-namiuchi** [mdn/translated-content#9074]
### MDN URL

https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Overview

### What specific section or headline is this issue about?

Images do not load

### What information was incorrect, unhelpful, or incomplete?

The example images do not load.

### What did you expect to see?

The example images

### Do you have any supporting links, references, or citations?

https://mdn.mozillademos.org/files/13687/HTTP_Request.png

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `pt-br/web/http/overview`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Web/HTTP/Overview
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/web/http/overview/index.html
* Last commit: https://github.com/mdn/translated-content/commit/bec25e522b17f939935865ac39a95c7760781e96
* Document last modified: 2022-08-04T19:07:07.000Z

</details>

**Comment by yin1999** [comment]
This issue has been resolved.
