### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by cabelotaina** [mdn/translated-content#9082]
### MDN URL

https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/Dealing_with_files

### What specific section or headline is this issue about?

https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/Dealing_with_files#caminhos_de_arquivo

### What information was incorrect, unhelpful, or incomplete?

Two images are broken at this section

### What did you expect to see?

I expect to see the images

### Do you have any supporting links, references, or citations?

At the English US page I can see the images: https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/Dealing_with_files

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `pt-br/learn/getting_started_with_the_web/dealing_with_files`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/Getting_started_with_the_web/Dealing_with_files
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/getting_started_with_the_web/dealing_with_files/index.md
* Last commit: https://github.com/mdn/translated-content/commit/417264509939a6e3ffa940b2085cf48796a702df
* Document last modified: 2022-10-06T11:07:49.000Z

</details>

**Comment by elo1lson** [comment]
Olá, o erro é no domínio, parece que o mdncontent está fora do ar, várias imagens estão com esse mesmo problema, a solução seria adicionar a imagem diretamente no repositório brasileiro, porém não sei se é correto fazer isso

**Comment by caugner** [comment]
Part of https://github.com/mdn/translated-content/issues/10400.

**Comment by yin1999** [comment]
This issue has been resolved.
