### ISSUE TITLE
Any PR with "dangerous" edits should be considered dangerous

### ISSUE THREAD

**Issue by peterbe** [mdn/translated-content#91]
Assume this to be the exact same problem as described here: https://github.com/mdn/content/issues/2985

Let's finish this for the `mdn/content` repo and then remember to clone that to this repo.

**Comment by SphinxKnight** [comment]
@peterbe just wandering across issues and seeing this one. I believe this is now OK on mdn/content. Should https://github.com/mdn/content/pull/3200/ be "propagated" here?

**Comment by peterbe** [comment]
Hi @SphinxKnight I ran into a weird GitHub Action "bug" (or user-error) that totally derailed me. 
In the GitHub Action I'm trying to get a git diff as a big string, and I just can't get it to work on `translated-content`. 
https://github.community/t/how-do-i-get-the-git-diff-compared-to-main/179296/6

Without that, it won't be able to figure out which external URLs are new.

**Comment by queengooborg** [comment]
It looks like 838dbb88de878d9c2f7eb406621dc10bb6df7226 propagates mdn/content#3200 up, so it looks like this is all good now!
