### ISSUE TITLE
link failure

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#9113]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/inheritance

### What information was incorrect, unhelpful, or incomplete?

Hello,
On the 1st line of the page, it is written "Pour chaque propriété CSS, la spécification ...... " with a link for "chaque propriété CSS".
The link does not work (Page not found).

I think the link should point to:
https://developer.mozilla.org/fr/docs/Web/CSS/Reference#keyword_index

### What did you expect to see?

a link that works

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/inheritance`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/inheritance
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/inheritance/index.md
* Last commit: https://github.com/mdn/translated-content/commit/79faa1509d68be77f14971a843e43da59dedff2f
* Document last modified: 2022-09-21T09:43:31.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour le rapport sur ce lien cassé @DomOBU :bow: nous allons corriger ça en mettant à jour la page par rapport à son homologue anglaise et en corrigeant, bien entendu, le lien :)

**Comment by DomOBU** [comment]
Merci pour le retour et aux contributeurs pour les traductions en langue française.
