### ISSUE TITLE
A few updates

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#9236]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/all

### What information was incorrect, unhelpful, or incomplete?

Hello,
I suggest a few updates to make:

Topic “all:unset”: the word "blue" is missing at the end of the sentence (_et color vaut ? (valeur héritée_))

Topic “all:inherit”: "<div"> should be replaced by "<body"> (_c'est un élément de bloc (valeur héritée depuis l'élément englobant  "<div">))

The topics “all:revert” and “all:revert-layer” have not been translated in the French page

Sincerely

### What did you expect to see?

that the updates are done.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/all`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/all
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/all/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f66954d9bcc9f94b8dab0ba5452395282c5372cd
* Document last modified: 2022-10-01T14:10:29.000Z

</details>

**Comment by SphinxKnight** [comment]
@DomOBU merci pour ce retour, je fais une PR d'update sous peu :)
