### ISSUE TITLE
我觉得这篇文章里面有一段有语义冲突

### ISSUE THREAD

**Issue by 5z5** [mdn/translated-content#9250]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Values_and_units

### What specific section or headline is this issue about?

段落意思表述不清，不知道在讲什么

### What information was incorrect, unhelpful, or incomplete?

CSS 中的值是一种定义允许子值集合的方法。**这意味着如果您看到<color>是有效的，那么您就不需要考虑可以使用哪些不同类型的颜色值—关键字、十六进制值、rgb()函数等等**。假设浏览器支持这些可用的<color>值，则可以使用它们任意一个。**MDN 上针对每个值的页面将提供有关浏览器支持的信息。**例如，如果您查看 [<color>](https://developer.mozilla.org/zh-CN/docs/Web/CSS/color_value)的页面，您将看到浏览器兼容性部分列出了不同类型的颜色值以及对它们的支持。

这一段的这两句话给我的理解是不一样的，第一句加粗的语句的意思就好像是只要关键字和16进制、rgb()函数中的一个可以用，其他的值就可以用，而第二句加粗的语句的意思，还是要根据浏览器的支持区选择值。

### What did you expect to see?

更明确的语句吧，这样太摸棱两可了

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/learn/css/building_blocks/values_and_units`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Learn/CSS/Building_blocks/Values_and_units
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/learn/css/building_blocks/values_and_units/index.md
* Last commit: https://github.com/mdn/translated-content/commit/4c181a1a21dce82421acee56d07749bcad37c242
* Document last modified: 2022-10-03T13:46:51.000Z

</details>

**Comment by 5z5** [comment]
好的



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Xavi ***@***.***> |
| 日期 | 2022年10月17日 21:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [mdn/translated-content] 我觉得这篇文章里面有一段有语义冲突 (Issue #9250) |

这并不矛盾。

前提是 <color> 有效，在有效的前提下可以是任意值。

这个问题不属于翻译问题，建议向 content 仓库使用英文提 issue

**Comment by 5z5** [comment]
我再看看



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Xavi ***@***.***> |
| 日期 | 2022年10月17日 21:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [mdn/translated-content] 我觉得这篇文章里面有一段有语义冲突 (Issue #9250) |

这并不矛盾。

前提是 <color> 有效，在有效的前提下可以是任意值。

这个问题不属于翻译问题，建议向 content 仓库使用英文提 issue

**Comment by yin1999** [comment]
Hi @5z5, thanks for raising this. I've reviewed @awxiaoxian2020's PR. And I think this may be good enough. Could you review the above PR? Any opinion is welcomed 🤗
