### ISSUE TITLE
document out-of-date: `valueOf`

### ISSUE THREAD

**Issue by guda-art** [mdn/translated-content#9252]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/valueOf

### What specific section or headline is this issue about?

描述

### What information was incorrect, unhelpful, or incomplete?

> JavaScript 的许多内置对象都重写了该函数，以实现更适合自身的功能需要。因此，不同类型对象的 valueOf() 方法的返回值和返回值类型均可能不同。

这段话的后面是一个表格,让人误以为表格和这句话有强相关关系, 表格的最后一行强调 Math 和 Error 对象没有 valueOf 方法。Math和Error是没有继承, 还是没有重写 ?
表达不清楚
还有比如Array对象没有重写valueOf方法, 联系上上面那句话就好像它重写了valueOf

### What did you expect to see?

~在表格前面加上 **不同对象调用valueOf的返回值情况** ~
~表格最后一行改为  Math和Error没有重写valueOf方法~

Update the document to reflect the english version.

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no

**Comment by Jack-Zhang-1314** [comment]
see: #9286
