### ISSUE TITLE
Опечатка в слове

### ISSUE THREAD

**Issue by DimaKichigin** [mdn/translated-content#9254]
[Статья](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch)

>   Здесь мы забираем JSON файл по сети и выводим его содержимое в консоль. Самый простой способ использования fetch() заключается в вызове этой _**функии**_ с одним аргументом — строкой, содержащей путь к ресурсу, который вы хотите получить — которая возвращает promise, содержащее ответ (объект [Response](https://developer.mozilla.org/ru/docs/Web/API/Response)).

**Comment by bsmth** [comment]
Hi, it looks like the file you're looking for is located here: 

https://github.com/mdn/translated-content/blob/main/files/ru/web/api/fetch_api/using_fetch/index.html

**Comment by DimaKichigin** [comment]
Thanks
