### ISSUE TITLE
Create a page in ja /learn/javascript/first_steps/test_your_skills_colon__math/  label: l10n-ja

### ISSUE THREAD

**Issue by kisre** [mdn/translated-content#928]
Since I found no translated page in ja for 
en-US original:
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math

I would like to contribute this translation file in ja
-----------
https://github.com/kisre/translated-content/blob/a8df812844ee6906cb6d47dc27899cb25ef2c08b/files/ja/learn/javascript/first_steps/test_your_skills_colon__math/index.html

-----------
Supposed URL will be
https://developer.mozilla.org/ja/docs/Learn/JavaScript/First_steps/Test_your_skills:_Math

-----------
@yari-content-ja

I wonder this way* will work?
*make a Issue(label written in title since the labels cannot be put by myself) including URL to show the code to want to be reviewed.

**Comment by kisre** [comment]
This issue is also related to the following PR:
https://github.com/mdn/translated-content/pull/911

**Comment by mfuji09** [comment]
プルリクエストが既に完了しているので、このIssueを閉じます。
