### ISSUE TITLE
An update

### ISSUE THREAD

**Issue by DomOBU** [mdn/translated-content#9302]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/color_value

### What specific section or headline is this issue about?

Le mot-clé currentColor/Exemples/Exemple live n°1

### What information was incorrect, unhelpful, or incomplete?

Hello,

I suggest the following update:
In “Le mot-clé currentColor/Exemples/Exemple live n°1“ the color is not blue but darkred so the text should be:
“La couleur de ce texte est darkred.”

### What did you expect to see?

“La couleur de ce texte est darkred.”

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/color_value`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/color_value
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/color_value/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f66954d9bcc9f94b8dab0ba5452395282c5372cd
* Document last modified: 2022-10-01T14:10:29.000Z

</details>

**Comment by SphinxKnight** [comment]
should be fixed by https://github.com/mdn/translated-content/pull/9116
