### ISSUE TITLE
[ko] 한국 첫 기여자들을 위한 가이드라인 (Git Gui 응용법)

### ISSUE THREAD

**Issue by hwang1588** [mdn/translated-content#934]
### 감사합니다.

-------

**- 깃허브의 mdn 문서 번역 흐름을 이해하기 위한 청사진**

![개요](https://user-images.githubusercontent.com/75598328/118918925-83942f80-b96e-11eb-9e0f-51d8708e631b.png)

 -------

**1. 먼저 mdn/content (https://github.com/mdn/content) 에서 영어본을 fork해서 퍼옵니다.**
![1(mdn 오리지널)](https://user-images.githubusercontent.com/75598328/118919412-6dd33a00-b96f-11eb-8206-1bb27a70911f.png)

**2. mdn/translated-content (https://github.com/mdn/translated-content) 에서 번역본을 fork합니다.**
![1](https://user-images.githubusercontent.com/75598328/118919712-04076000-b970-11eb-9568-082c85113551.png)

**3. 
(1) fork한 자신의 리포지터리를 확인합니다.
(2) 코드 버튼을 클릭합니다.
(3) 자신의 리포지터리 주소를 복사합니다.**
![2](https://user-images.githubusercontent.com/75598328/118948327-2363b480-b993-11eb-8cc6-4dd36b3e54f1.png)

**4. 이제 이 가이드라인의 핵심인 Git Gui를 사용해야 합니다. 
본 가이드라인에서는 여러가지 Gui중 '소스트리'를 사용합니다. 설치 방법 및 기본 개요는 아래의 링크를 참조해주세요!**
https://opentutorials.org/course/1492/8037

**5. 이제 깃허브 계정과 소스트리를 연동했으면 사진과 같이 따라갑니다.
(1) +버튼을 클릭해 새 탭을 생성합니다.
(2) Clone을 클릭합니다.
(3) 해당 칸에 3.번에서 복사한 리포지터리 주소를 붙혀넣기 합니다.
(4) 4번칸에 자신의 로컬(내 컴퓨터)에 원격리포(리모트)를 저장할 위치를 지정합니다.
(5) 고급옵션을 클릭합니다.
(6) 브랜치 체크아웃을 main으로 잡습니다.
(7) 클론 버튼을 클릭해 원격 저장소를 내컴퓨터 저장합니다.**
![4](https://user-images.githubusercontent.com/75598328/118950035-c9fc8500-b994-11eb-94e9-722ff7d7aa45.png)

**6. 정상적으로 성공하셨다면 아래의 사진과 같이 저장소가 생성됩니다. 이제 mdn 문서를 번역 해봅시다.**
![5](https://user-images.githubusercontent.com/75598328/118950841-86564b00-b995-11eb-97d0-efd05dadbdfc.png)

------
시간 관계로 추가 내용에 대한 편집은 추후 진행하겠습니다. ^^;

**Comment by hochan222** [comment]
#878 

고생해주셔서 감사합니다. 한국 가이드라인이 머지가 되어서 이슈 닫겠습니다. https://github.com/mdn/translated-content/issues/827 GUI에 대해서는 해당 이슈에 링크 두었습니다. 좋은 하루 보내세요 :) 

- https://github.com/mdn/translated-content/blob/main/docs/ko/translation-guide.md
