### ISSUE TITLE
關於 zh-TW 翻譯指南中"複數形式"之疑問

### ISSUE THREAD

**Issue by cdcd72** [mdn/translated-content#9480]
## What information was incorrect, unhelpful, or incomplete?

![螢幕擷取畫面 2022-10-24 214324](https://user-images.githubusercontent.com/24297780/197542864-e1ab0805-3ab5-4d93-8c32-97f718dc1927.jpg)

## What is the new suggestion?

宜或不宜看起來一樣，感覺是寫錯...?（紅線處應該移除）

## Other supporting information

https://github.com/mdn/translated-content/blob/main/docs/zh-tw/translation-guide.md

**Comment by Jack-Zhang-1314** [comment]
API 不宜复数，中文使用单数保留特殊的名词

**Comment by yin1999** [comment]
注意括号内的内容，翻译指南的意思是：对于英文的单词，我们也应该移除其复数形式 `APIs` ---> `API`
