### ISSUE TITLE
Wrong image URLs

### ISSUE THREAD

**Issue by ccorcoles** [mdn/translated-content#9496]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/HTML/Introduction_to_HTML/Getting_started

### What specific section or headline is this issue about?

https://developer.mozilla.org/es/docs/Learn/HTML/Introduction_to_HTML/Getting_started#anatom%C3%ADa_de_un_elemento_html

### What information was incorrect, unhelpful, or incomplete?

First image in the section is not showing correctly. The img tag points to https://mdn.mozillademos.org/files/11913/htmlexp.png, which fails to load. As a quick fix, the English version of the image (/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started/grumpy-cat-small.png) could be used.

### What did you expect to see?

I 4expected to see the Spanish translation of the image at /en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started/grumpy-cat-small.png

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/learn/html/introduction_to_html/getting_started`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/HTML/Introduction_to_HTML/Getting_started
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/html/introduction_to_html/getting_started/index.md
* Last commit: https://github.com/mdn/translated-content/commit/0990e069c5abda7963d922445a083ce7eafe2d98
* Document last modified: 2022-10-10T21:25:17.000Z

</details>

**Comment by Graywolf9** [comment]
Thank you so much for submitting the bug!
