### ISSUE TITLE
Wrong image URI

### ISSUE THREAD

**Issue by ccorcoles** [mdn/translated-content#9499]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/HTML/Introduction_to_HTML/Getting_started

### What specific section or headline is this issue about?

https://developer.mozilla.org/es/docs/Learn/HTML/Introduction_to_HTML/Getting_started#aprendizaje_activo_a%C3%B1adir_algunas_caracter%C3%ADsticas_a_un_documento_html

### What information was incorrect, unhelpful, or incomplete?

The first image in the section points to https://mdn.mozillademos.org/files/12279/template-screenshot.png and the image fails to load. A quick fix would be to switch it to the English version, which points to /en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started/template-screenshot.png

### What did you expect to see?

The Spanish translation of the image at /en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started/template-screenshot.png

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/learn/html/introduction_to_html/getting_started`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/HTML/Introduction_to_HTML/Getting_started
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/html/introduction_to_html/getting_started/index.md
* Last commit: https://github.com/mdn/translated-content/commit/0990e069c5abda7963d922445a083ce7eafe2d98
* Document last modified: 2022-10-10T21:25:17.000Z

</details>

**Comment by Luisbo85** [comment]
Puedo agregar el cambio para apunta al link correcto

**Comment by ccorcoles** [comment]
Sería genial si pudiese hacerse.

**Comment by Graywolf9** [comment]
Muchas gracias por reportar el incidente @ccorcoles y muchas gracias @Luisbo85 por solventarlo <3
