### ISSUE TITLE
About the content not match the url

### ISSUE THREAD

**Issue by Jack-Zhang-1314** [mdn/translated-content#9532]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/TypedArray

### What information was incorrect, unhelpful, or incomplete?

The Link shows `TypedArray`, but its content is `ArrayBufferView`
![image](https://user-images.githubusercontent.com/82551626/198072530-583af0d9-6809-4c24-8100-acdcdd1c0763.png)

### What did you expect to see?

`TypedArray`

**Comment by jasonren0403** [comment]
The page is outdated and need sync

**Comment by yin1999** [comment]
See 07268465978deef5ac5e9120cda1c277f5968307, the document is moved from `ArrayBufferView`

**Comment by Jack-Zhang-1314** [comment]
There is no `ArrayBufferView` anymore. Maybe change it to English first?

**Comment by yin1999** [comment]
> There is no `ArrayBufferView` anymore. Maybe change it to English first?

I don't like this. If it present with English content, why not see the english document. But we can translate a part of it per PR.

**Comment by Jack-Zhang-1314** [comment]
But now it's simply a wrong content. Or translate it as soon as possible
