### ISSUE TITLE
Mauvais liens

### ISSUE THREAD

**Issue by jessygnt** [mdn/translated-content#9635]
![Capture d’écran 2022-11-01 à 20 23 43](https://user-images.githubusercontent.com/100865709/199320850-8ee9619e-bd24-43e8-bb5f-7ef1e8d581f7.png)

Les liens pour le deuxième article correspond à la page du quatrième article.

**Comment by yin1999** [comment]
Hi @jessygnt, could you please provide the url to the page :)

**Comment by SphinxKnight** [comment]
Looks like it's from https://developer.mozilla.org/fr/docs/Learn/JavaScript/Objects but links are working from there. I'll check the page and will submit an update if necessary (or close the issue if irrelevant)
