### ISSUE TITLE
I assume border-color - needs to be replaced with outline-color

### ISSUE THREAD

**Issue by Artur-Kli** [mdn/translated-content#9637]
### MDN URL

https://developer.mozilla.org/ru/docs/Learn/Forms/Your_first_form

### What information was incorrect, unhelpful, or incomplete?

input:focus, textarea:focus {
  /* To give a little highligh on active elements */
  border-color: #000;
}

### What did you expect to see?

input:focus, textarea:focus {
  /* To give a little highligh on active elements */
  outline-color: #000;
}

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ru/learn/forms/your_first_form`
* MDN URL: https://developer.mozilla.org/ru/docs/Learn/Forms/Your_first_form
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/learn/forms/your_first_form/index.md
* Last commit: https://github.com/mdn/translated-content/commit/ef86e40eda3a49fdae2ff3d8b5c904f707512987
* Document last modified: 2022-08-04T19:06:23.000Z

</details>

**Comment by leon-win** [comment]
Unfortunately, this page is not in the Russian version of MDN.
It was without translation, and now it doesn’t exist at all.

That's why I'm closing the issue too)
Thank you for trying to help the project! :+1:
