### ISSUE TITLE
  translation error ?

### ISSUE THREAD

**Issue by jinguangwang** [mdn/translated-content#9644]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Object/create

### What specific section or headline is this issue about?

Object.create()

### What information was incorrect, unhelpful, or incomplete?

console.log("nullProtoObj is: " + nullProtoObj); // throws error: Cannot convert object to primitive value

### What did you expect to see?

//  No exception occurred   { }

### Do you have any supporting links, references, or citations?

no

### Do you have anything more you want to share?

no

**Comment by yin1999** [comment]
Hi @jinguangwang, there is nothing wrong with this. The comment show that this does occurred an error (used to show the documation before).

![image](https://user-images.githubusercontent.com/15844309/199405806-ded9e664-794c-400b-b5b6-edffe73cc90a.png)
