### ISSUE TITLE
中文翻译的一个页面内容不正确

### ISSUE THREAD

**Issue by yuzhen1024** [mdn/translated-content#9678]
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/CSS/fit-content

### What information was incorrect, unhelpful, or incomplete?

 [该链接](https://developer.mozilla.org/zh-CN/docs/Web/CSS/fit-content)
 对应的应该是 
[这个页面](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content_function) 
的内容翻译。

### What did you expect to see?

https://developer.mozilla.org/zh-CN/docs/Web/CSS/fit-content
https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content
https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content_function

**Comment by yin1999** [comment]
Thanks for reporting this. I'll work on it /:)
