### ISSUE TITLE
CORS Error 문서 번역

### ISSUE THREAD

**Issue by rjsdn0124** [mdn/translated-content#9692]
### MDN URL

https://developer.mozilla.org/ko/docs/Web/HTTP/CORS/Errors/CORSDisabled

### What specific section or headline is this issue about?

CORS Error 관련 문서 번역

### What information was incorrect, unhelpful, or incomplete?

<img width="1440" alt="스크린샷 2022-11-04 오후 3 19 43" src="https://user-images.githubusercontent.com/44187187/199905214-1f33d1c3-24ff-4b84-bc88-82100b9e4f1c.png">

### What did you expect to see?

CORS 에러 관련 페이지가 한국어로 번역된 상태

**Comment by hochan222** [comment]
@rjsdn0124 님 안녕하세요.

혹시 해당 이슈가 번역을 진행했는데, 번역이 완료된 파일이 노출되지 않는 문제일까요? 

해당 페이지는 [현재 번역된 파일](https://github.com/mdn/translated-content/tree/main/files/ko/web/http/cors/errors)에 존재하지 않습니다.

<img width="1271" alt="image" src="https://user-images.githubusercontent.com/22424891/201271935-469cc6a0-7abf-4065-baad-a881da3b2143.png">

아래와 content repo 같은 경로에 파일이 존재해야 노출될 수 있습니다. 혹시 번역 예정이시라면 content repo와 동일한 경로에 파일 생성하여 기여주시면 됩니다!

<img width="1675" alt="image" src="https://user-images.githubusercontent.com/22424891/201272045-a6470c71-1399-438c-865f-e836b9abc23a.png">

좋은 하루 보내세요. 감사합니다 :)

**Comment by rjsdn0124** [comment]
앗 안녕하세요 개발자님! 

혼동을 드려 죄송합니다.
저희가 해당 부분에 번역을 하고자 이슈에 등록을 해두었었습니다,,
번역 작업을 이제 하려고 합니다!!

감사합니다 :)

**Comment by hochan222** [comment]
안녕하세요! 넵넵 이해했습니다. 감사합니다 :)

**Comment by rjsdn0124** [comment]
앗 감사합니다!
해결하고 PR드리겠습니다 :)

**Comment by SnowMarble** [comment]
@hochan222 해당 페이지의 번역본이 존재하기 때문에, 이 이슈는 이제 닫아도 될것 같습니다.

**Comment by hochan222** [comment]
@SnowMarble 님, 넵 이슈 닫겠습니다. 멘션 감사합니다. 좋은 주말 보내세요 :)
