### ISSUE TITLE
Secure flag for cookies are now accepted for localhost for Firefox and Chrome

### ISSUE THREAD

**Issue by xpoinsard** [mdn/translated-content#9696]
### MDN URL

https://developer.mozilla.org/fr/docs/Web/HTTP/Cookies

### What specific section or headline is this issue about?

Cookies Secure et HttpOnly

### What information was incorrect, unhelpful, or incomplete?

À partir de Chrome 52 et Firefox 52, les sites non sécurisés (http:) ne peuvent pas définir de cookies avec la directive Secure.

### What did you expect to see?

À partir de Chrome 52 et Firefox 52, les sites non sécurisés (http:) ne peuvent pas définir de cookies avec la directive Secure à l'exception de localhost

### Do you have any supporting links, references, or citations?

https://bugs.chromium.org/p/chromium/issues/detail?id=1056543

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/http/cookies`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/HTTP/Cookies
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/http/cookies/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d00f2a5989c4ca59e278585ba53f3181fe77ce43
* Document last modified: 2022-09-21T09:45:21.000Z

</details>

**Comment by SphinxKnight** [comment]
Merci pour ce retour :) je vais mettre à jour la page par rapport à son homologue anglaise.
