### ISSUE TITLE
missing link in French doc (Response/ok in Fetch API)

### ISSUE THREAD

**Issue by LordManta** [mdn/translated-content#98]
Not a huge one but this one :
 https://developer.mozilla.org/fr/docs/Web/API/Response/ok

**Comment by SphinxKnight** [comment]
@LordManta I'm not sure to understand the intent of this issue. Are you saying there is a link missing in some page or that this particular page needs to be created/translated in French?

**Comment by Scttpr** [comment]
I created a PR to handle this missing page by created a new one from scratch based on the us-US version.

I'm not sure about the workflow and the little details I need to set. Please let me know !

Btw, am I missing something with the local dev process ? It does not transpile the `{{domxref()}}` or even CSS locally.

**Comment by SphinxKnight** [comment]
@Scttpr thanks a lot!
The `{{domxref()}}` macro is a KumaScript macro. You should have a "decent" CSS display locally. For instance, I get this on my machine:
![image](https://user-images.githubusercontent.com/2413436/111038470-6ea89680-8429-11eb-9aa0-ec8278eefc82.png)

I'm closing the issue as the PR has been merged (check [What'sDeployed](https://whatsdeployed.io/s/16d/mdn/translated-content) if you can't see it on the site).

@Scttpr if you have any issue with your local setup, let me know on Matrix (or on an issue if necessary)
