### ISSUE TITLE
Artículo en español desactualizado y con importantes carencias respecto al artículo en inglés

### ISSUE THREAD

**Issue by EnriqueSource** [mdn/translated-content#9805]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/JavaScript/Asynchronous/Introducing

### What specific section or headline is this issue about?

general

### What information was incorrect, unhelpful, or incomplete?

No se mencionan ni los manejadores de eventos ni los callbacks, esenciales para el asincronismo es JavaScript. En el artículo en inglés se habla sobre ellos.

### What did you expect to see?

La misma documentación que el artículo en inglés.

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/es/docs/Learn/JavaScript/Asynchronous/Introducing

### Do you have anything more you want to share?

Podría resolverlo yo mismo si se me asigna.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/learn/javascript/asynchronous/introducing`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/JavaScript/Asynchronous/Introducing
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/javascript/asynchronous/introducing/index.md
* Last commit: https://github.com/mdn/translated-content/commit/99eb07dc4987d2c2f4982e81c046c9abbe827665
* Document last modified: 2022-11-07T18:02:37.000Z

</details>

**Comment by EnriqueSource** [comment]
Hola. ¿Podéis asignarme este issue? Gracias

**Comment by Graywolf9** [comment]
Hola! @EnriqueSource espero esteés muy bien, ¿cómo va todo?

**Comment by EnriqueSource** [comment]
Hola @Graywolf9 . Todo va bien. Este artículo es un poco largo, por lo que me lleva algo más de tiempo. Esta misma semana hago el PR. Un saludo
