### ISSUE TITLE
Missing bracket in flatMap page RU locale

### ISSUE THREAD

**Issue by deadmagic161** [mdn/translated-content#9815]
[flatMapPage](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap)

The bracket on the page of this method is missing. Please correct

![image](https://user-images.githubusercontent.com/22148648/200846214-f1089ef2-3397-4771-809a-11bd856bc462.png)

So the following line:

```js
let arr1 = 1, 2, 3, 4];
```

should be:

```js
let arr1 = [1, 2, 3, 4];
```

**Comment by bsmth** [comment]
Hi @deadmagic161 👋🏻, I've transferred this one over to the `translated-content` repository which I believe is the place to resolve this.
