### ISSUE TITLE
A Problem in "Basic Mathematics in JavaScript-Numbers and Operators" 

### ISSUE THREAD

**Issue by Good1Time** [mdn/translated-content#9832]
MDN page: https://developer.mozilla.org/zh-CN/docs/Learn/JavaScript/First_steps/Math#%E7%AE%97%E6%9C%AF%E8%BF%90%E7%AE%97%E7%AC%A6 (JavaScript 中的基础数学 — 数字和操作符)

### What is the problem?

Translation Errors of Chinese Web Pages 

On the [English page](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/First_steps/Math#arithmetic_operators):

operator: `/` ;Purpose : `Divides the left number by the right.` 

On the zh-CN page:
运算符: `/` ;作用 : `用右边的数除左边的数`

I think there's been a mistake！
Sincerely !

**Comment by yin1999** [comment]
Thanks for reporting this @Good1Time.

Let me explain this in Chinese:

---

“用右边的数除左边的数”就是`左边的数除以右边的数`的意思。

具体可看引用的知乎回答：https://www.zhihu.com/question/45496872/answer/1819402384
