### ISSUE TITLE
Error in documentation about regular expressions

### ISSUE THREAD

**Issue by MarisaAfuera** [mdn/translated-content#985]
In the location https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Regular_Expressions/Assertions, in spanish version is written the example: /\Bme/ coincide con "me" en "al mediodía". This is false, it doesn't match.

**Comment by SphinxKnight** [comment]
Sorry, but this locale is currently frozen and changes/fixes are not currently accepted. Please see https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ and [README](https://github.com/mdn/translated-content/blob/main/README.md) of this repo.
