### ISSUE TITLE
Typo 

### ISSUE THREAD

**Issue by kmylo** [mdn/translated-content#9899]
### MDN URL

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Proxy

### What specific section or headline is this issue about?

https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Proxy#extendiendo_el_contructor

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/5576764/201731631-9af37941-06f7-48dc-b600-3ac19e582234.png)

### What did you expect to see?

"constructor" instead of "contructor"

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/web/javascript/reference/global_objects/proxy`
* MDN URL: https://developer.mozilla.org/es/docs/Web/JavaScript/Reference/Global_Objects/Proxy
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/web/javascript/reference/global_objects/proxy/index.md
* Last commit: https://github.com/mdn/translated-content/commit/ed5a7b64d4f1d651f59cd7e4a18317cdb5eccf94
* Document last modified: 2022-11-07T18:23:57.000Z

</details>

**Comment by trieu099** [comment]
![image](https://user-images.githubusercontent.com/96922130/201933857-10fd50ad-f0f0-4041-ba97-5e02c7374f83.png)
I already fix like this, it's ok?

**Comment by cw118** [comment]
@trieu099 I have linked your PR to this issue, so this will automatically be closed once the pull request is merged. Thanks very much and welcome on MDN :)
