### ISSUE TITLE
@layerの構文ミス

### ISSUE THREAD

**Issue by satake-miyuki** [mdn/translated-content#9903]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/CSS/@layer

### What specific section or headline is this issue about?

構文

### What information was incorrect, unhelpful, or incomplete?

`@import(utilities.css) layer(utilities);`

### What did you expect to see?

Englishページ同様に以下のように書き換えて欲しいです。

`@import "theme.css" layer(utilities);`

またはカッコを使用するのであればurlが必要かと思います。

`@import url("utilities.css") layer(utilities);`

### Do you have any supporting links, references, or citations?

https://developer.mozilla.org/en-US/docs/Web/CSS/@layer
https://developer.mozilla.org/en-US/docs/Web/CSS/@import

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/css/@layer`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/CSS/@layer
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/css/@layer/index.md
* Last commit: https://github.com/mdn/translated-content/commit/96b4719efa326b650b5f602279540f910975224e
* Document last modified: 2022-10-03T15:13:59.000Z

</details>

**Comment by mfuji09** [comment]
@satake-miyuki さん
ご自分で対応されますか？

**Comment by mfuji09** [comment]
その後、英語版記事自体が更新されたので、それに合わせて日本語版記事も更新済です。
