### ISSUE TITLE
Links in "For more info on editing this repo" section of README.md are broken

### ISSUE THREAD

**Issue by mikecat** [mdn/translated-content#9957]
In the ["For more info on editing this repo" section of README.md](https://github.com/mdn/translated-content#for-more-info-on-editing-this-repo), these links looks broken:

```
[fundamental concepts](https://github.com/mdn/content#fundamental-concepts)
[pull request etiquette](https://github.com/mdn/content#pull-request-etiquette)
[adding](https://github.com/mdn/content#adding-a-new-document)
[moving](https://github.com/mdn/content#moving-one-or-more-documents)
[deleting](https://github.com/mdn/content#deleting-a-document)
```

It looks proper for these links other than "fundamental concepts" to go to corresponding sections of [content/CONTRIBUTING.md](https://github.com/mdn/content/blob/main/CONTRIBUTING.md) instead.
(note that `#moving-one-or-more-documents` should be `#moving-documents`)

The section corresponding to "fundamental concepts" looks deleted instead of migrating, so how to treat this part doesn't look obvious.

Related to mdn/content#21361

**Comment by cw118** [comment]
Thank you for reporting this @mikecat, we'll fix the links :)
