### ISSUE TITLE
broken image

### ISSUE THREAD

**Issue by mines1974** [mdn/translated-content#9968]
### MDN URL

https://developer.mozilla.org/es/docs/Learn/Getting_started_with_the_web/CSS_basics

### What information was incorrect, unhelpful, or incomplete?

hi,
this image is broken:
https://mdn.mozillademos.org/files/9455/website-screenshot-final.png
![image](https://user-images.githubusercontent.com/57153155/202510246-0928cdfa-4def-4e96-9fbf-ce398db309a1.png)

### What did you expect to see?

image

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `es/learn/getting_started_with_the_web/css_basics`
* MDN URL: https://developer.mozilla.org/es/docs/Learn/Getting_started_with_the_web/CSS_basics
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/es/learn/getting_started_with_the_web/css_basics/index.md
* Last commit: https://github.com/mdn/translated-content/commit/99eb07dc4987d2c2f4982e81c046c9abbe827665
* Document last modified: 2022-11-07T18:02:37.000Z

</details>

**Comment by Graywolf9** [comment]
Thank you so much for submitting the issue!
