### ISSUE TITLE
Specifications using "HTML5 Web Messaging" are rendered as "Unknown"

### ISSUE THREAD

**Issue by mikecat** [mdn/translated-content#9984]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/MessageChannel

### What specific section or headline is this issue about?

仕様

### What information was incorrect, unhelpful, or incomplete?

`{{SpecName("HTML5 Web Messaging")}}` is rendered as "Unknown".
`{{Spec2('HTML5 Web Messaging')}}` is rendered as "不明".

### What did you expect to see?

Valid links to the refered specifications.

### Do you have anything more you want to share?

This issue also exists on (at least) these pages:

* [MessageChannel() - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/MessageChannel/MessageChannel)
* [MessageChannel.port2 - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/MessageChannel/port2)
* [MessagePort.close() - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/MessagePort/close)
* [MessagePort.postMessage() - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/MessagePort/postMessage)
* [MessagePort.onmessage - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/MessagePort/message_event)

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/messagechannel`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/MessageChannel
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/messagechannel/index.md
* Last commit: https://github.com/mdn/translated-content/commit/633950267097296a772c42ade424e76cf7690775
* Document last modified: 2022-10-01T01:39:50.000Z

</details>

**Comment by YujiSoftware** [comment]
#10103 で、 `{{Specifications}}` マクロに置き換えました。これで修正されます。
マージをお待ちください。

**Comment by manjuu-eater** [comment]
解決したようですね。

**Comment by mfuji09** [comment]
解決したので閉じます。
