### ISSUE TITLE
Specifications using "WebVR" are rendered as "Unknown"

### ISSUE THREAD

**Issue by mikecat** [mdn/translated-content#9985]
### MDN URL

https://developer.mozilla.org/ja/docs/Web/API/VRStageParameters

### What specific section or headline is this issue about?

仕様

### What information was incorrect, unhelpful, or incomplete?

`{{SpecName("WebVR", ...)}}` is rendered as "Unknown".
`{{Spec2('WebVR')}}` is rendered as "不明".

### What did you expect to see?

Valid links to the refered specifications.

### Do you have anything more you want to share?

This issue is seen on many other pages.

Some examples of pages with this issue:

* [VRStageParameters - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/VRStageParameters)
* [VREyeParameters - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/VREyeParameters)
* [VRFieldOfView - Web API | MDN](https://developer.mozilla.org/ja/docs/Web/API/VRFieldOfView)

"WebVR 1.1" (seen on [VRDisplayCapabilities](https://developer.mozilla.org/ja/docs/Web/API/VRDisplayCapabilities)) may be what to replace "WebVR" with.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `ja/web/api/vrstageparameters`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/API/VRStageParameters
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/api/vrstageparameters/index.md
* Last commit: https://github.com/mdn/translated-content/commit/f01646c40eb0c51d267c54d0ae77d912fde1cb85
* Document last modified: 2022-09-26T14:51:40.000Z

</details>

**Comment by manjuu-eater** [comment]
Deprecatedになって仕様書自体が削除され、問題は解決したようです。
参考：https://github.com/mdn/translated-content/commit/0f9b2b4f38c8f92a2f3f787b0168f5cfd2d0da51

仕様書がちゃんと表示されない問題自体も別のPRで解決したようです。
参考：https://github.com/mdn/translated-content/pull/10103

**Comment by mfuji09** [comment]
解決したので閉じます。
